### ISSUE TITLE
Error Optifinr, again?

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#101]
java.util.zip.ZipException: duplicate entry: optifine/AndroidInstaller.class
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:234)
	at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
	at net.kdt.pojavlaunch.patcher.OptiFinePatcher.saveInstaller(OptiFinePatcher.java:44)
	at net.kdt.pojavlaunch.Tools.patchOptifineInstaller(Tools.java:319)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1005)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by khanhduytran0** [comment]
try install again

**Comment by FranzelDamasco909** [comment]
@khanhduytran0 , is the RAM can be updatable to 512 MB to 2 GB

**Comment by khanhduytran0** [comment]
No

**Comment by FranzelDamasco909** [comment]
Why

**Comment by khanhduytran0** [comment]
It load using DexClassLoader, but before has a class to increase heap size but deprecated. You could google with `Android Dev increase heap size`.

**Comment by FranzelDamasco909** [comment]
What can i do with that

**Comment by FranzelDamasco909** [comment]
How can i increase my heap size? i don't know what to use for code

**Comment by szarik001** [comment]
You can't. He literally just said that.

**Comment by khanhduytran0** [comment]
@dawid5635 try latest one.
