### ISSUE TITLE
I can't play version 1.12.2

### ISSUE THREAD

**Issue by bksuper** [PojavLauncherTeam/PojavLauncher#102]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
	at bib.<init>(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 5 more
Caused by: java.lang.ClassCastException: Bootstrap method returned null
	... 7 more

**Comment by FranzelDamasco909** [comment]
1.12.2 is not at the moment

**Comment by FranzelDamasco909** [comment]
so it won't work

**Comment by FranzelDamasco909** [comment]
you can only install up to 1.11.2
