### ISSUE TITLE
[BUG] <Still Can't Run 21w10a SnapShot After The Latest New Crowdin updates>

### ISSUE THREAD

**Issue by EnderBrine99FOX** [PojavLauncherTeam/PojavLauncher#1036]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/10/21 9:59 PM
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at ejd.b(SourceFile:461)
	at ejd.a(SourceFile:367)
	at adi.a(SourceFile:15)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)
	at dmw.e(SourceFile:309)
	at dse.e(SourceFile:1095)
	at dse.e(SourceFile:692)
	at net.minecraft.client.main.Main.main(SourceFile:216)
Caused by: wo: Invalid shaders/core/rendertype_armor_cutout_no_cull.json: Couldn't compile vertex program (Default, rendertype_armor_cutout_no_cull) : 0:4: S0054: Overloading built-in function 'min' not allowed
	at wo.a(SourceFile:48)
	at ejv.<init>(SourceFile:197)
	at ejd.a(SourceFile:397)
	at ejd.b(SourceFile:426)
	... 131 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_armor_cutout_no_cull) : 0:4: S0054: Overloading built-in function 'min' not allowed
	at dnc.b(SourceFile:63)
	at dnc.a(SourceFile:45)
	at ejv.a(SourceFile:237)
	at ejv.<init>(SourceFile:179)
	... 133 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ejd.b(SourceFile:461)
	at ejd.a(SourceFile:367)
	at adi.a(SourceFile:15)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:704)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:717)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at adm.a(SourceFile:71)
	at apq.execute(SourceFile:94)
	at adm.a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:649)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)

-- Overlay render details --
Details:
	Overlay name: dwm
Stacktrace:
	at ejd.a(SourceFile:828)
	at dse.e(SourceFile:1070)
	at dse.e(SourceFile:692)
	at net.minecraft.client.main.Main.main(SourceFile:216)

-- System Details --
Details:
	Minecraft Version: 21w10a
	Minecraft Version ID: 21w10a
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 793110464 bytes (756 MB) / 1370488832 bytes (1307 MB) up to 1370488832 bytes (1307 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xms1346M -Xmx1346M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 21w10a
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: Using framebuffer using OpenGL 3.2
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x null

**Comment by khanhduytran0** [comment]
Known issue. Current GL4ES is not yet enough to run it.

**Comment by khanhduytran0** [comment]
__Duplicate #1035__!!
