### ISSUE TITLE
Mod bud

### ISSUE THREAD

**Issue by balamurugan116** [PojavLauncherTeam/PojavLauncher#1071]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 3/17/21 8:10 AM
Description: Unexpected error

com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdxarm64.so' for target: Linux, 64-bit
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:120) ~[physicsmod:1.0] {re:classloading}
	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:33) ~[physicsmod:1.0] {re:classloading}
	at net.diebuddies.physics.PhysicsMod.onRenderTick(PhysicsMod.java:183) ~[physicsmod:1.0] {re:mixin,re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_0_PhysicsMod_onRenderTick_RenderTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onRenderTickEnd(BasicEventHooks.java:80) ~[forge:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:980) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch/cache/libgdxu0_a640/7f06eb57/libgdxarm64.so: dlopen failed: library "libm.so.6" not found
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:316) ~[physicsmod:1.0] {re:classloading}
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:116) ~[physicsmod:1.0] {re:classloading}
	... 19 more
Caused by: java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch/cache/libgdxu0_a640/7f06eb57/libgdxarm64.so: dlopen failed: library "libm.so.6" not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0-internal] {}
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[?:1.8.0-internal] {}
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817) ~[?:1.8.0-internal] {}
	at java.lang.Runtime.load0(Runtime.java:810) ~[?:1.8.0-internal] {}
	at java.lang.System.load(System.java:1088) ~[?:1.8.0-internal] {}
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:322) ~[physicsmod:1.0] {re:classloading}
	at com.badlogic.gdx.utils.SharedLibraryLoader.loadFile(SharedLibraryLoader.java:291) ~[physicsmod:1.0] {re:classloading}
	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:116) ~[physicsmod:1.0] {re:classloading}
	... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 227580720 bytes (217 MB) / 750780416 bytes (716 MB) up to 750780416 bytes (716 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms512m -Xmx800m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.4.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.4
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		physics-mod-1.3.4_forge.jar                       |Physics Mod                   |physicsmod                    |1.0                 |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.4-universal.jar                 |Forge                         |forge                         |35.1.4              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
	Crash Report UUID: b14ca7e5-e193-4e3e-956a-e8515d02b50c
	Launched Version: 1.16.4
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 9x null

**Comment by khanhduytran0** [comment]
Just patch the Physics mod as this instruction: https://youtu.be/rnq4dbLpLAM :eyes:
