### ISSUE TITLE
Minecraft crashes when I try to connect to the server

### ISSUE THREAD

**Issue by Pawoog** [PojavLauncherTeam/PojavLauncher#109]
---- Minecraft Crash Report ----
// Sorry :(

Time: 17.04.2020 23:04
Description: Rendering Block Entity

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4812)
	at brj.a(SourceFile:125)
	at bms.a(SourceFile:64)
	at bms.a(SourceFile:35)
	at bms.a(SourceFile:21)
	at bmk.a(SourceFile:100)
	at bmk.a(SourceFile:92)
	at bma.a(SourceFile:383)
	at blt.a(SourceFile:994)
	at blt.b(SourceFile:816)
	at bao.ak(SourceFile:801)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at brk.a(SourceFile:48)
	at brk.load(SourceFile:45)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4812)
	at brj.a(SourceFile:125)
	at bms.a(SourceFile:64)
	at bms.a(SourceFile:35)

-- Block Entity Details --
Details:
	Name: Skull // apn
	Block type: ID #144 (tile.skull // anl)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-27,79,-53), Chunk: (at 5,4,11 in -2,-4; contains blocks -32,0,-64 to -17,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #144 (tile.skull // anl)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at b.a(SourceFile:250)
	at bmk.a(SourceFile:103)
	at bmk.a(SourceFile:92)
	at bma.a(SourceFile:383)
	at blt.a(SourceFile:994)
	at blt.b(SourceFile:816)
	at bao.ak(SourceFile:801)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)

-- Affected level --
Details:
	Level name: MpServer
	All players: 13 total; [bjk['Pawook'/1571, l='MpServer', x=-29,42, y=81,01, z=-49,59], bll['§f'/22, l='MpServer', x=-16,47, y=75,02, z=-60,53], bll['§f'/53, l='MpServer', x=-12,47, y=75,02, z=-62,34], bll['§f'/56, l='MpServer', x=-8,56, y=75,02, z=-63,41], bll['§f'/59, l='MpServer', x=-4,47, y=75,02, z=-62,56], bll['bheadr'/1566, l='MpServer', x=-27,53, y=78,02, z=-47,75], bll['§f'/43, l='MpServer', x=-16,53, y=75,02, z=-37,34], bll['§e§lEmail'/46, l='MpServer', x=-23,63, y=74,52, z=-36,59], bll['§f'/37, l='MpServer', x=-4,53, y=75,02, z=-36,47], bll['§f'/40, l='MpServer', x=-8,44, y=75,02, z=-35,69], bll['§f'/49, l='MpServer', x=-12,47, y=75,02, z=-36,53], bll['§e§lFriends'/62, l='MpServer', x=4,69, y=74,52, z=-62,41], bll['§e§lLinks'/65, l='MpServer', x=3,28, y=74,02, z=-34,53]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-30,80,-50), Chunk: (at 2,5,14 in -2,-4; contains blocks -32,0,-64 to -17,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 35914 game time, 102500 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 26 total; [bjk['Pawook'/1571, l='MpServer', x=-29,42, y=81,01, z=-49,59], bll['§f'/22, l='MpServer', x=-16,47, y=75,02, z=-60,53], bll['§e§lLinks'/65, l='MpServer', x=3,28, y=74,02, z=-34,53], bll['§f'/53, l='MpServer', x=-12,47, y=75,02, z=-62,34], bll['§f'/56, l='MpServer', x=-8,56, y=75,02, z=-63,41], bll['§f'/59, l='MpServer', x=-4,47, y=75,02, z=-62,56], bll['bheadr'/1566, l='MpServer', x=-27,53, y=78,02, z=-47,75], bll['§f'/43, l='MpServer', x=-16,53, y=75,02, z=-37,34], bll['§e§lEmail'/46, l='MpServer', x=-23,63, y=74,52, z=-36,59], bll['§f'/37, l='MpServer', x=-4,53, y=75,02, z=-36,47], bll['§f'/40, l='MpServer', x=-8,44, y=75,02, z=-35,69], bll['§f'/49, l='MpServer', x=-12,47, y=75,02, z=-36,53], bll['§e§lFriends'/62, l='MpServer', x=4,69, y=74,52, z=-62,41], bll['§e§lLinks'/65, l='MpServer', x=3,28, y=74,02, z=-34,53], bll['§f'/22, l='MpServer', x=-16,47, y=75,02, z=-60,53], bll['bheadr'/1566, l='MpServer', x=-27,53, y=78,02, z=-47,75], bll['§f'/37, l='MpServer', x=-4,53, y=75,02, z=-36,47], bll['§f'/40, l='MpServer', x=-8,44, y=75,02, z=-35,69], bll['§f'/43, l='MpServer', x=-16,53, y=75,02, z=-37,34], bll['§e§lEmail'/46, l='MpServer', x=-23,63, y=74,52, z=-36,59], bll['§f'/49, l='MpServer', x=-12,47, y=75,02, z=-36,53], yv['§f§a§oFind The heads'/52, l='MpServer', x=12,59, y=78,00, z=-49,47], bll['§f'/53, l='MpServer', x=-12,47, y=75,02, z=-62,34], bll['§f'/56, l='MpServer', x=-8,56, y=75,02, z=-63,41], bll['§f'/59, l='MpServer', x=-4,47, y=75,02, z=-62,56], bll['§e§lFriends'/62, l='MpServer', x=4,69, y=74,52, z=-62,41]]
	Retry entities: 0 total; []
	Server brand: FlameCord (0.2.1 SNAPSHOT) <- Paper
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (armv8l) version 4.14.62-18098116
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-A505FM, Android 10), The Android Project
	Memory: 8015872 bytes (7 MB) / 103628488 bytes (98 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Anisotropic filtering is not supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.

	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by khanhduytran0** [comment]
This crash only happend in Android 5.x devices. I'm finding a solution...

**Comment by Pawoog** [comment]
> This crash only happend in Android 5.x devices. I'm finding a solution...

My device runs on android 10

**Comment by khanhduytran0** [comment]
OK see your crash is Android 10... need more time to find a way to fix this...

**Comment by artdeell** [comment]
This bug occurs only on servers with SkinRestorer

**Comment by khanhduytran0** [comment]
This problem can be solved by replace Java Google Guava with Android specific version.

**Comment by monleak** [comment]
Where can I find an Android-specific version and how to install it?

**Comment by khanhduytran0** [comment]
Try v3, fixed without any library changes
