### ISSUE TITLE
Minecraft crashes when switching from Freeform mode to default mode

### ISSUE THREAD

**Issue by artdeell** [PojavLauncherTeam/PojavLauncher#11]
I checked the Freeform mode capabitities of the app, and found a bug: when I  swipe to switch app back to default mode. Crash report says something about GL context.

**Comment by khanhduytran0** [comment]
Please put crash report here.

**Comment by artdeell** [comment]
`---- Minecraft Crash Report ----
// Sorry :(

Time: 27.03.2020 19:30
Description: Initializing game

java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Client thread,5,main] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(Unknown Source:49)
	at org.lwjgl.opengl.ContextGL.makeCurrent(Unknown Source:1)
	at org.lwjgl.opengl.DrawableGL.makeCurrent(Unknown Source:8)
	at org.lwjgl.opengl.Display.makeCurrent(Unknown Source:2)
	at org.lwjgl.opengl.Display.makeCurrentAndSetSwapInterval(Unknown Source:0)
	at org.lwjgl.opengl.Display.setDisplayMode(Unknown Source:47)
	at bcx.aq(SourceFile:609)
	at bcx.an(SourceFile:433)
	at bcx.a(SourceFile:381)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:760)
	at net.kdt.pojavlaunch.MainActivity.access$1000072(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000012$100000011.run(MainActivity.java:499)
	at java.lang.Thread.run(Thread.java:919)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.ContextGL.checkAccess(Unknown Source:49)
	at org.lwjgl.opengl.ContextGL.makeCurrent(Unknown Source:1)
	at org.lwjgl.opengl.DrawableGL.makeCurrent(Unknown Source:8)
	at org.lwjgl.opengl.Display.makeCurrent(Unknown Source:2)
	at org.lwjgl.opengl.Display.makeCurrentAndSetSwapInterval(Unknown Source:0)
	at org.lwjgl.opengl.Display.setDisplayMode(Unknown Source:47)
	at bcx.aq(SourceFile:609)

-- Initialization --
Details:
Stacktrace:
	at b.a(SourceFile:245)
	at bcx.a(SourceFile:384)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:760)
	at net.kdt.pojavlaunch.MainActivity.access$1000072(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000012$100000011.run(MainActivity.java:499)
	at java.lang.Thread.run(Thread.java:919)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (aarch64) version 3.18.120-g995ab9456635-dirty
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (null), The Android Project
	Memory: 16626960 bytes (15 MB) / 167147824 bytes (159 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.2
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'bxm bxn.c()' on a null object reference
	Profiler Position: N/A (disabled)
	CPU: <unknown>`

**Comment by khanhduytran0** [comment]
Use ` ``` multi-line text ``` `:
```
An
Example
```
Seems like `onCreate` called twice.

**Comment by khanhduytran0** [comment]
Freeform is experimental, can't know why `onCreate` called while resize or full screen.

**Comment by Zeyrox1090** [comment]
lol

**Comment by Zeyrox1090** [comment]
fist issue

**Comment by Mathias-Boulay** [comment]
Freeform will be deprecated soon.
This issue is now irrelevant
