### ISSUE TITLE
When i'm trying to join a server it gives me an issue about Rendering screen.

### ISSUE THREAD

**Issue by Kirillka22** [PojavLauncherTeam/PojavLauncher#1109]
---- Minecraft Crash Report ----
// There are four lights!

Time: 3/26/21 10:27 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:580)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:574)
	at net.minecraft.client.gui.GuiDisconnected.func_73863_a(SourceFile:44)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:580)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:574)
	at net.minecraft.client.gui.GuiDisconnected.func_73863_a(SourceFile:44)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiDisconnected
	Mouse location: Scaled: (165, 65). Absolute: (165, 79)
	Screen size: Scaled: (299, 145). Absolute: (299, 145). Scale factor of 1
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 766378064 bytes (730 MB) / 1509949440 bytes (1440 MB) up to 1509949440 bytes (1440 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=70 -XX:G1HeapRegionSize=32M -Xms1425M -Xmx1425M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version       | Source                                     | Signature                                |
	|:------ |:----------- |:------------- |:------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2        | minecraft.jar                              | None                                     |
	| LCHIJA | mcp         | 9.42          | minecraft.jar                              | None                                     |
	| LCHIJA | FML         | 8.0.99.99     | forge-1.12.2-14.23.5.2854.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2854  | forge-1.12.2-14.23.5.2854.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | divinerpg   | 1.7.1         | DivineRPG-1.7.1.jar                        | None                                     |
	| LCHIJA | ic2         | 2.8.221-ex112 | industrialcraft-2-2.8.221-ex112.jar        | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | jei         | 4.15.0.294    | jei_1.12.2-4.15.0.294.jar                  | None                                     |
	| LCHIJA | journeymap  | 1.12.2-5.7.1  | journeymap-1.12.2-5.7.1.jar                | None                                     |
	| LCHIJA | railcraft   | 12.0.0        | railcraft_12.0.0.jar                       | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | reborncore  | 3.19.4.529    | reborncore-1.12.2-3.19.4.529-universal.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | stevescarts | 2.4.32.137    | stevescarts-1.12.2-2.4.32.137.jar          | None                                     |

	Loaded coremods (and transformers): 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.4.529
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: 1.12.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by khanhduytran0** [comment]
@Kirillka22 fill the template. Crash log is not enough. Also why you need forge on joining server?
