### ISSUE TITLE
Android 9, 1.12.2 doesn't start...but i know why

### ISSUE THREAD

**Issue by BranchScope** [PojavLauncherTeam/PojavLauncher#111]
**Bug Description**

_When i try to run Minecraft 1.12.2 without changes like Optifine or something it shows me an error:_

`java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:748)
 at net.kdt.pojavlaunch.MainActivity.access$1000073(Unknown Source:0)
 at net.kdt.pojavlaunch.MainActivity$100000013$100000012.run(MainActivity.java:509)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
 at bib.<init>(SourceFile:395)
 at net.minecraft.client.main.Main.main(SourceFile:123)
 ... 5 more
Caused by: java.lang.ClassCastException: Bootstrap method returned null
 ... 7 more`

_So, you just told we how to run Java8_ [here](https://stackoverflow.com/questions/54224065/bootstrap-method-returned-null-android-crash-immediately-on-launch/57861173#57861173) _that's fun because we need to decompile the app? lol, so, in the_ `.zip` _and in the_ `.tar.gz` _file on releases, there are just 2 file, the readme and the json, what we must do?_

**Comment by khanhduytran0** [comment]
You can't get the `build.grade` in decompiler. I'm even added `Java 8` but without success.

**Comment by khanhduytran0** [comment]
So you can't run 1.12.x at the moment.

**Comment by BranchScope** [comment]
F, thx u for the info.

**Comment by BranchScope** [comment]
Anyway, why u don't show the source? Maybe users can help you to update the project...

**Comment by khanhduytran0** [comment]
Maybe OK...

**Comment by khanhduytran0** [comment]
Yep it not prepared for anything, codes are ton of classes.
