### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#1121]
--------- beggining with launcher debug
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms750m -Xmx750m -Dorg.lwjgl.opengl.libname=libgl4es_115.so"
Headless version detected! (20210324)
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
" unused DT entry: type 
0xf
 arg 
0x361

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
" unused DT entry: type 
0xf
 arg 
0x450

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
" unused DT entry: type 
0xf
 arg 
0x33c0

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" unused DT entry: type 
0xf
 arg 
0x13b8

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" unused DT entry: type 
0xf
 arg 
0x2196

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
" unused DT entry: type 
0xf
 arg 
0x6a68

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" unused DT entry: type 0xf arg 0x4d9
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
" unused DT entry: type 
0xf
 arg 
0xda0

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
" unused DT entry: type 
0xf
 arg 
0x5e6

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjpeg.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so
" unused DT entry: type 
0xf
 arg 
0x77

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjawt.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" unused DT entry: type 
0xf
 arg 
0x1c7

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjdwp.so
" has unsupported flags DT_FLAGS_1=
0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" unused DT entry: type 0xf arg 0x8ff
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" unused DT entry: type 0xf arg 0x16fe
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmanagement.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so
" unused DT entry: type 
0xf
 arg 
0x2e6

WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pcsc.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so
" unused DT entry: type 
0xf
 arg 
0xe6

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava_crw_demo.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so
" unused DT entry: type 
0xf
 arg 
0x119

WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsound.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so
" unused DT entry: type 
0xf
 arg 
0x364

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libunpack.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so
" unused DT entry: type 
0xf
 arg 
0x139

WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjsdt.so
" has unsupported flags DT_FLAGS_1=
0x81

WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" unused DT entry: type 0xf arg 0xf13
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2pkcs11.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" unused DT entry: type 0xf arg 0x3f1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/liblcms.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" unused DT entry: type 0xf arg 0x158
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libmlib_image.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" unused DT entry: type 0xf arg 0x6af
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libsctp.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" unused DT entry: type 0xf arg 0x1c1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libdt_socket.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" unused DT entry: type 0xf arg 0x6c1
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libj2gss.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" unused DT entry: type 0xf arg 0x23a
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libtinyiconv.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so
" unused DT entry: type 
0xf
 arg 
0x103
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjaas_unix.so" has unsupported flags DT_FLAGS_1=0x81
WARNING: linker: 
"
/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so
" unused DT entry: type 0xf arg 0x1d2
WARNING: linker: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libhprof.so" has unsupported flags DT_FLAGS_1=0x81
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes

[05:18:13] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[05:18:13] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[05:18:13] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions

OptiFineTweaker: injectIntoClassLoader

OptiFine ClassTransformer

OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/optifine/OptiFine/1.16.5_HD_U_G8_pre10/OptiFine-1.16.5_HD_U_G8_pre10.jar

OptiFineTweaker: getLaunchArguments

OptiFineTweaker: getLaunchTarget

[05:18:14] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[05:18:16] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[05:18:17] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[05:18:17] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.hasTileEntity
[05:18:17] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[05:18:17] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.CrashReportExtender
[05:18:19] [main/INFO]: [OptiFine] (Reflector) Method not present: aeg.createOptional
[05:18:47] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[05:18:48] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[05:18:54] [main/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[YggdrasilSocialInteractionsService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[YggdrasilSocialInteractionsService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[YggdrasilAuthenticationService.class:?]
	at djz.a(SourceFile:625) [djz.class:?]
	at djz.<init>(SourceFile:409) [djz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:177) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
[05:18:54] [main/INFO]: Setting user: Lance_Aldrei
[05:18:55] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[05:18:55] [main/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[05:18:55] [main/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[05:18:56] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[05:18:57] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[05:18:57] [main/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
OSMDroid: using built-in libOSMesa_8.so
OSMDroid: unable to load: dlopen failed: library "libOSMesa_8.so" wasn't loaded and RTLD_NOLOAD prevented it
[0328/131900.734540:ERROR:elf_dynamic_array_reader.h(61)] tag not found
[0328/131900.820553:ERROR:elf_dynamic_array_reader.h(61)] tag not found

**Comment by LANCECRAFT1104** [comment]
Failed to Launch

**Comment by khanhduytran0** [comment]
![CE1A5F8F-145C-4C90-9285-F7A207A97020](https://user-images.githubusercontent.com/40482367/112743306-7be48a00-8fc0-11eb-8a93-a6eeeda7d2e7.jpeg)

**Comment by LANCECRAFT1104** [comment]
What is that?

**Comment by khanhduytran0** [comment]
It is what you’ve downloaded, right?

**Comment by LANCECRAFT1104** [comment]
Yeah

**Comment by AutumnVN** [comment]
do you understand "dev-tests"?

**Comment by LANCECRAFT1104** [comment]
[0328/131900.734540:ERROR:elf_dynamic_array_reader.h(61)] tag not found
[0328/131900.820553:ERROR:elf_dynamic_array_reader.h(61)] tag not found

After I see this the game crashing

**Comment by artdeell** [comment]
U stupid?
*These are dev tests, they are not mean to be used by anyone except devs*

**Comment by LANCECRAFT1104** [comment]
K

**Comment by LANCECRAFT1104** [comment]
K
