### ISSUE TITLE
[Question] Optifine

### ISSUE THREAD

**Issue by issuereporter292** [PojavLauncherTeam/PojavLauncher#117]
How do I use Optifine after I download? Is it functioning or is it just a thing that's there?

**Comment by khanhduytran0** [comment]
To install: Options -> Install OptiFine-> Select downloaded OptiFine.

To launch: find OptiFine versions at the bottom of release version list.

**Comment by issuereporter292** [comment]
> To install: Options -> Install OptiFine-> Select downloaded OptiFine.
> 
> To launch: find OptiFine versions at the bottom of release version list.

This keeps popping up

Unable to convert library optifine:launchwrapper-of:2.1
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false
java.lang.RuntimeException: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:502)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:556)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:32)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

UNEXPECTED TOP-LEVEL EXCEPTION:
java.io.FileNotFoundException: /storage/emulated/0/games/minecraft/libraries/optifine/launchwrapper-of/2.1/launchwrapper-of-2.1_orig.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
	at java.util.zip.ZipFile.<init>(ZipFile.java:201)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.pojavdx.dx.command.dexer.Main.processOne(Main.java:682)
	at com.pojavdx.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.pojavdx.dx.command.dexer.Main.runMultiDex(Main.java:361)
	at com.pojavdx.dx.command.dexer.Main.runDx(Main.java:283)
	at com.pojavdx.dx.command.dexer.Main.main(Main.java:241)
	at com.pojavdx.dx.command.Main.main(Main.java:95)
	at net.kdt.pojavlaunch.Tools.runDx(Tools.java:339)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:574)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
1 error; aborting
Exiting with code 1

**Comment by khanhduytran0** [comment]
[fix here](https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine#since-optifine-mc-19-a-file-called-launchwrapper-of-21jar-cause-error-unable-to-launch-simply-fix-by-follow-the-video-or-do-actions-as-below)

**Comment by issuereporter292** [comment]
> [fix here](https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine#since-optifine-mc-19-a-file-called-launchwrapper-of-21jar-cause-error-unable-to-launch-simply-fix-by-follow-the-video-or-do-actions-as-below)

Thanks
