### ISSUE TITLE
[BUG] <Short description>Everyday it makes me download the files of any version I want to play on :(

### ISSUE THREAD

**Issue by Deactivator** [PojavLauncherTeam/PojavLauncher#1177]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
So ,when I wake up in the morning I want to play Pojav but when I hit play for optifine I says that it's  not there in the files so I click on 1.16.5 and hit play and it automatically starts the download for it. The download takes like 10mins but the thing is that I have to download 1.16.5 as well as I have to install all the things I have like resource packs, shaders, optifine , etc

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.16.5-OptiFine_HD_U_G7/1.16.5-OptiFine_HD_U_G7.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:606)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:344)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:44)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.16.5-OptiFine_HD_U_G7/1.16.5-OptiFine_HD_U_G7.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:674)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:525)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8367)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 13 more

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected that it wouldn't let me download the files for mc versions everyday.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model Samsung M31 Prime
 - CPU architecture idk
 - Android Version 11
 - PojavLauncher Version 3.3.1.1_rel_20210125

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Harsh-bot-beep** [comment]
Bruh

**Comment by ebuild-1** [comment]
You need to download 1.16 first then optifine.

**Comment by Deactivator** [comment]
> You need to download 1.16 first then optifine.

i did download 1.16 before optifine but after a day it again tells me to download 1.16 to play

**Comment by ebuild-1** [comment]
Idk maybe you touched the files.

**Comment by khanhduytran0** [comment]
@Deactivator make sure all file cleaners are disabled.

**Comment by DRONZER7212** [comment]
I also have this type of problem in Samsung Galaxy m30s  all you have to do is go to setting and go to device care and go to storage and go to storage booster and then turn off auto delete unnecessary data.

**Comment by mchnjt** [comment]
> I also have this type of problem in Samsung Galaxy m30s  all you have to do is go to setting and go to device care and go to storage and go to storage booster and then turn off auto delete unnecessary data.

k whatever

**Comment by Mathias-Boulay** [comment]
Issues due to file cleaners, not an issue on our end.
closing
