### ISSUE TITLE
[BUG] Not is possible play in snapshots 1.13

### ISSUE THREAD

**Issue by OwzygZawg** [PojavLauncherTeam/PojavLauncher#1189]
---- Minecraft Crash Report ----
// Don't do that.

Time: 09-04-2021 2:51
Description: Initializing game

java.lang.NoSuchMethodError: org.lwjgl.system.MemoryUtil.memCopy(JJI)V
	at ctw$b.b(SourceFile:152)
	at ctw$a.a(SourceFile:54)
	at org.lwjgl.stb.STBIReadCallbackI.callback(STBIReadCallbackI.java:35)
	at org.lwjgl.stb.STBImage.nstbi_info_from_callbacks(Native Method)
	at org.lwjgl.stb.STBImage.stbi_info_from_callbacks(STBImage.java:817)
	at ctw.<init>(SourceFile:41)
	at cua.b(SourceFile:73)
	at cua.a(SourceFile:53)
	at cvq.n(SourceFile:690)
	at cvq.a(SourceFile:183)
	at cvr.a(SourceFile:23)
	at uc.a(SourceFile:119)
	at bxt.an(SourceFile:497)
	at bxt.a(SourceFile:368)
	at net.minecraft.client.main.Main.main(SourceFile:141)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ctw$b.b(SourceFile:152)
	at ctw$a.a(SourceFile:54)
	at org.lwjgl.stb.STBIReadCallbackI.callback(STBIReadCallbackI.java:35)
	at org.lwjgl.stb.STBImage.nstbi_info_from_callbacks(Native Method)
	at org.lwjgl.stb.STBImage.stbi_info_from_callbacks(STBImage.java:817)
	at ctw.<init>(SourceFile:41)
	at cua.b(SourceFile:73)
	at cua.a(SourceFile:53)
	at cvq.n(SourceFile:690)
	at cvq.a(SourceFile:183)
	at cvr.a(SourceFile:23)
	at uc.a(SourceFile:119)
	at bxt.an(SourceFile:497)

-- Initialization --
Details:
Stacktrace:
	at bxt.a(SourceFile:368)
	at net.minecraft.client.main.Main.main(SourceFile:141)

-- System Details --
Details:
	Minecraft Version: 18w07a
	Operating System: Linux (arm) version Android-8.0.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 666509160 bytes (635 MB) / 778502144 bytes (742 MB) up to 778502144 bytes (742 MB)
	JVM Flags: 3 total; -Xms768M -Xmx768M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 18w07a
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x null

**Comment by WesleyVanNeck** [comment]
Disable gl4es 1.1.5

**Comment by OwzygZawg** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 11-04-2021 0:26
Description: Initializing game

java.lang.NoSuchMethodError: org.lwjgl.system.MemoryUtil.memCopy(JJI)V
	at ctw$b.b(SourceFile:152)
	at ctw$a.a(SourceFile:54)
	at org.lwjgl.stb.STBIReadCallbackI.callback(STBIReadCallbackI.java:35)
	at org.lwjgl.stb.STBImage.nstbi_info_from_callbacks(Native Method)
	at org.lwjgl.stb.STBImage.stbi_info_from_callbacks(STBImage.java:817)
	at ctw.<init>(SourceFile:41)
	at cua.b(SourceFile:73)
	at cua.a(SourceFile:53)
	at cvq.n(SourceFile:690)
	at cvq.a(SourceFile:183)
	at cvr.a(SourceFile:23)
	at uc.a(SourceFile:119)
	at bxt.an(SourceFile:497)
	at bxt.a(SourceFile:368)
	at net.minecraft.client.main.Main.main(SourceFile:141)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at ctw$b.b(SourceFile:152)
	at ctw$a.a(SourceFile:54)
	at org.lwjgl.stb.STBIReadCallbackI.callback(STBIReadCallbackI.java:35)
	at org.lwjgl.stb.STBImage.nstbi_info_from_callbacks(Native Method)
	at org.lwjgl.stb.STBImage.stbi_info_from_callbacks(STBImage.java:817)
	at ctw.<init>(SourceFile:41)
	at cua.b(SourceFile:73)
	at cua.a(SourceFile:53)
	at cvq.n(SourceFile:690)
	at cvq.a(SourceFile:183)
	at cvr.a(SourceFile:23)
	at uc.a(SourceFile:119)
	at bxt.an(SourceFile:497)

-- Initialization --
Details:
Stacktrace:
	at bxt.a(SourceFile:368)
	at net.minecraft.client.main.Main.main(SourceFile:141)

-- System Details --
Details:
	Minecraft Version: 18w07a
	Operating System: Linux (arm) version Android-8.0.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 638081064 bytes (608 MB) / 770375680 bytes (734 MB) up to 770375680 bytes (734 MB)
	JVM Flags: 3 total; -Xms760M -Xmx760M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 18w07a
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x null

**Comment by OwzygZawg** [comment]
Gl4es 1.1.4 not work too

**Comment by OwzygZawg** [comment]
:(

**Comment by OwzygZawg** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
> da missing ~~symbol~~method hmmm

but why you need run 18w07a?

**Comment by OwzygZawg** [comment]
> > da missing ~~symbol~~method hmmm
> 
> but why you need run 18w07a?

I like to play old snapshots!
