### ISSUE TITLE
Optifine crash

### ISSUE THREAD

**Issue by Kodaz313** [PojavLauncherTeam/PojavLauncher#119]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 21/04/2020 00:03
Description: Initializing game

java.lang.NullPointerException: Attempt to invoke virtual method 'void civ.a(int, int, int)' on a null object reference
	at civ.c(WorldRenderer.java:561)
	at ckx.b(SourceFile:21)
	at bsu.a(SourceFile:749)
	at bsu.aj(SourceFile:373)
	at bsu.a(SourceFile:299)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:940)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at civ.c(WorldRenderer.java:561)
	at ckx.b(SourceFile:21)
	at bsu.a(SourceFile:749)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:347)
	at bsu.a(SourceFile:302)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:940)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (armv7l) version 3.18.120-perf-g1627ed5
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (motorola moto g(6) play, Android 9), The Android Project
	Memory: 0 bytes (0 MB) / 97311128 bytes (92 MB) up to 402653184 bytes (384 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8-OptiFine_HD_U_I7
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	OptiFine Version: OptiFine_1.8_HD_U_I7
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
That's weird ...

**Comment by Kodaz313** [comment]
can you help me

**Comment by Kodaz313** [comment]
Another problem, when I add a server it goes offline

**Comment by khanhduytran0** [comment]
> can you help me

Not sure...

> Another problem, when I add a server it goes offline 

No MOTD?

**Comment by Kodaz313** [comment]
![Screenshot_20200421-110752](https://user-images.githubusercontent.com/64055612/79875761-79e17680-83c0-11ea-87a4-a0a2304be6fd.png)

**Comment by artdeell** [comment]
@Kodaz313 this happens on PC too. Just click "Refresh"

**Comment by Kodaz313** [comment]
Did not work

**Comment by khanhduytran0** [comment]
> Did not work

But can you join?

Some servers with different encryption can't be decrypted by Android.

**Comment by Kodaz313** [comment]
I can't get into the server, it's like he's offline

**Comment by khanhduytran0** [comment]
Try v3
