### ISSUE TITLE
error when starting

### ISSUE THREAD

**Issue by fulano16** [PojavLauncherTeam/PojavLauncher#123]
![Screenshot_20200421-151938](https://user-images.githubusercontent.com/64099031/79900495-b1621a00-83e4-11ea-9d14-5cd62ddc4c33.png)
(Android 6.0)

when start this error is returned

java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.7.10/1.7.10.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:967)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(MainActivity.java)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:818)
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/versions/1.7.10/1.7.10.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:964)
		... 3 more
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/data/app/net.kdt.pojavlaunch-1/base.apk"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /data/app/net.kdt.pojavlaunch-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 5 more
		Suppressed: java.lang.ClassNotFoundException: net.minecraft.client.main.Main
			at java.lang.Class.classForName(Native Method)
			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 6 more
		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by khanhduytran0** [comment]
Try delete minecraft folder and re-install.

**Comment by khanhduytran0** [comment]
Hmm... almost any Android 6 devices got this...

**Comment by khanhduytran0** [comment]
So try to run in VMOS!

**Comment by khanhduytran0** [comment]
V2 will not work on Android 6. Try v3
