### ISSUE TITLE
[BUG] what happened to my account?

### ISSUE THREAD

**Issue by ebuild-1** [PojavLauncherTeam/PojavLauncher#1247]
java.lang.RuntimeException: Respone error, code: 403, message: {"error":"ForbiddenOperationException","errorMessage":"Token does not exist"}
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:16)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:21)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.refresh(YggdrasilAuthenticator.java:109)
	at net.kdt.pojavlaunch.authenticator.mojang.RefreshTokenTask.doInBackground(RefreshTokenTask.java:48)
	at net.kdt.pojavlaunch.authenticator.mojang.RefreshTokenTask.doInBackground(RefreshTokenTask.java:15)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

I can't log in....

**Comment by EnderBrine99FOX** [comment]
Are you Using NFA Account?

**Comment by ebuild-1** [comment]
> Are you Using NFA Account?

No this is premium account

**Comment by Harsh-bot-beep** [comment]
Quite Devs......

**Comment by Harsh-bot-beep** [comment]
> java.lang.RuntimeException: Respone error, code: 403, message: {"error":"ForbiddenOperationException","errorMessage":"Token does not exist"}
> at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:16)
> at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:21)
> at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.refresh(YggdrasilAuthenticator.java:109)
> at net.kdt.pojavlaunch.authenticator.mojang.RefreshTokenTask.doInBackground(RefreshTokenTask.java:48)
> at net.kdt.pojavlaunch.authenticator.mojang.RefreshTokenTask.doInBackground(RefreshTokenTask.java:15)
> at android.os.AsyncTask$2.call(AsyncTask.java:333)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:764)
> 
> I can't log in....

Wanna know how to fix

**Comment by khanhduytran0** [comment]
Just delete it and login again.
