### ISSUE TITLE
Error loading on labymod 1.8.9

### ISSUE THREAD

**Issue by kkfoxin** [PojavLauncherTeam/PojavLauncher#1276]
---- Minecraft Crash Report ----
// There are four lights!

Time: 23-04-2021 1:39
Description: Initializing game

java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:43)
	at net.labymod.main.LabyMod.init(LabyMod.java:290)
	at ave.am(SourceFile:470)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:43)
	at net.labymod.main.LabyMod.init(LabyMod.java:290)
	at ave.am(SourceFile:470)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 771023200 bytes (735 MB) / 930086912 bytes (887 MB) up to 930086912 bytes (887 MB)
	JVM Flags: 3 total; -Xms940M -Xmx940M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: ! §2Sammyfault §a[16x].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x null
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by AutumnVN** [comment]
use laby 1.12

**Comment by kkfoxin** [comment]
> use laby 1,12

I play on servers

**Comment by AutumnVN** [comment]
use viaforge to join

**Comment by kkfoxin** [comment]
> use viaforge to join

Ok

**Comment by ghost** [comment]
I think the Launcher_profiles.json file is the cause because in that file there is an argument jvm -Xmx5g

**Comment by GoneSubject** [comment]
> I think the Launcher_profiles.json file is the cause because in that file there is an argument jvm -Xmx5g
> 

welp you can edit it in the PojavLauncher setting

**Comment by ghost** [comment]
> > I think the Launcher_profiles.json file is the cause because in that file there is an argument jvm -Xmx5g
> 
> welp you can edit it in the PojavLauncher setting

Can you test?please

**Comment by GoneSubject** [comment]
> > > I think the Launcher_profiles.json file is the cause because in that file there is an argument jvm -Xmx5g
> > 
> > welp you can edit it in the PojavLauncher setting
> 
> Can you test?please 

i recommend you to delete everything in there because PojavLauncher will automatically set the JVM![IMG_20220101_202155.jpg](https://user-images.githubusercontent.com/95298052/147851565-4a658b77-15d7-40b0-9807-32efa473053b.jpg)

**Comment by ghost** [comment]
> > > > Menurut saya file Launcher_profiles.json penyebabnya karena di file itu ada argumen jvm -Xmx5g
> > > 
> > > 
> > > wah, Anda dapat mengeditnya di pengaturan PojavLauncher
> > 
> > 
> > Bisakah Anda menguji? tolong
> 
> saya sarankan Anda untuk menghapus semua yang ada di sana karena PojavLauncher akan secara otomatis mengatur JVM![IMG_20220101_202155.jpg](https://user-images.githubusercontent.com/95298052/147851565-4a658b77-15d7-40b0-9807-32efa473053b.jpg)

Noo,delet jvm arhuments from files in directory 

net.dkt.pojavlaunch/files/.minecraft/launcher_profiles.json

**Comment by GoneSubject** [comment]
> > > > > Menurut saya file Launcher_profiles.json penyebabnya karena di file itu ada argumen jvm -Xmx5g
> > > > 
> > > > 
> > > > wah, Anda dapat mengeditnya di pengaturan PojavLauncher
> > > 
> > > 
> > > Bisakah Anda menguji? tolong
> > 
> > saya sarankan Anda untuk menghapus semua yang ada di sana karena PojavLauncher akan secara otomatis mengatur JVM![IMG_20220101_202155.jpg](https://user-images.githubusercontent.com/95298052/147851565-4a658b77-15d7-40b0-9807-32efa473053b.jpg)
> 
> Noo,delet jvm arhuments from files in directory 
> 
> net.dkt.pojavlaunch/files/.minecraft/launcher_profiles.json

1. it didn't shown for me
2. i think delete the JVM in PojavLauncher setting is a better option because you may mess up if you try to change the JVM in the file

**Comment by AlirezaParsi** [comment]
i tried delete that and i did all methods but it didnt works. 

> > > > > > Menurut saya file Launcher_profiles.json penyebabnya karena di file itu ada argumen jvm -Xmx5g
> > > > > 
> > > > > 
> > > > > wah, Anda dapat mengeditnya di pengaturan PojavLauncher
> > > > 
> > > > 
> > > > Bisakah Anda menguji? tolong
> > > 
> > > 
> > > saya sarankan Anda untuk menghapus semua yang ada di sana karena PojavLauncher akan secara otomatis mengatur JVM![IMG_20220101_202155.jpg](https://user-images.githubusercontent.com/95298052/147851565-4a658b77-15d7-40b0-9807-32efa473053b.jpg)
> > 
> > 
> > Noo,delet jvm arhuments from files in directory
> > net.dkt.pojavlaunch/files/.minecraft/launcher_profiles.json
> 
> 1. it didn't shown for me
> 2. i think delete the JVM in PojavLauncher setting is a better option because you may mess up if you try to change the JVM in the file

**Comment by GoneSubject** [comment]
can you send the log again?

**Comment by AlirezaParsi** [comment]
> can you send the log again?

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/14/22 6:49 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:44)
	at net.labymod.main.LabyMod.init(LabyMod.java:332)
	at ave.am(SourceFile:470)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:44)
	at net.labymod.main.LabyMod.init(LabyMod.java:332)
	at ave.am(SourceFile:470)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 670824048 bytes (639 MB) / 892338176 bytes (851 MB) up to 892338176 bytes (851 MB)
	JVM Flags: 3 total; -Xms936M -Xmx936M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null
