### ISSUE TITLE
Didnt start with me

### ISSUE THREAD

**Issue by vitreace** [PojavLauncherTeam/PojavLauncher#1285]
_Here is the bug report:_

java.lang.RuntimeException: LWJGL3 was not installed!
	at net.kdt.pojavlaunch.BaseMainActivity.checkLWJGL3Installed(BaseMainActivity.java:949)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:898)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:764)

**Comment by khanhduytran0** [comment]
@vitreace where is the issue template?
