### ISSUE TITLE
Optifine not working

### ISSUE THREAD

**Issue by glancist** [PojavLauncherTeam/PojavLauncher#129]
Hey so optifine isn't working for me in any version.
I have Android 5
here's the error:java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1040)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: java.io.IOException: Base resource not found: ans.class
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:32)
	... 10 more
Caused by: java.io.IOException: Base resource not found: ans.class
	at optifine.Patcher.applyPatch(Patcher.java:143)
	at optifine.Patcher.process(Patcher.java:87)
	at optifine.AndroidInstaller.installOptiFineLibrary(AndroidInstaller.java:56)
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:28)
	... 10 more

**Comment by khanhduytran0** [comment]
Remove downloaded Minecraft client jar and:
- Re-install that Minecraft version.
- Make sure that Minecraft version launch.
- Re-install OptiFine version.
- Try a launch.

**Comment by glancist** [comment]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:940)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(MainActivity.java)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Cannot set property {{}=null} as it does not exist in null
	at beg.a(SourceFile:121)
	at bed.<init>(SourceFile:55)
	at atr.e(SourceFile:897)
	at atr.<init>(SourceFile:272)
	at asy.<init>(SourceFile:13)
	at atr.R(SourceFile:924)
	at od.c(SourceFile:477)
	at bsu.<init>(SourceFile:293)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	... 8 more

**Comment by glancist** [comment]
Still not working hmm 😒

**Comment by glancist** [comment]
I did everything and the other versions work but optifine doesnt

**Comment by glancist** [comment]
@khanhduytran0  how to fix

**Comment by khanhduytran0** [comment]
```
Caused by: java.lang.IllegalArgumentException: Cannot set property {{}=null} as it does not exist in null
```

Looks like you are launching Minecraft 1.8. This happend same with me and same Android 5. Try other Minecraft versions: 1.7.10, 1.8.8. Android 5.0 can't convert OptiFine 1.8.9 or above (may have a way to fix, but code).

**Comment by glancist** [comment]
I was using optifine 1.8 and no optifine doesn't work at all in any version :(

**Comment by glancist** [comment]
Gives the same bug/issue @khanhduytran0

**Comment by khanhduytran0** [comment]
Did OptiFine 1.7.10 make a force close?

**Comment by khanhduytran0** [comment]
> Did OptiFine 1.7.10 make a force close?

[This is an example](https://youtu.be/k_d_AxglnZU)

**Comment by glancist** [comment]
java.lang.RuntimeException: Unable to convert library optifine:OptiFine:1.7.10_HD_U
propertyValue:true
[CDS]rx timeout:0
[socket][1] connection libraries.minecraft.net/13.224.96.78:443;LocalPort=46445(10000)
[CDS]connect[libraries.minecraft.net/13.224.96.78:443] tm:10
[socket][/192.168.43.243:46445] connected
gba_cipher_suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
[OkHttp] sendRequest>>
[OkHttp] sendRequest<<
java.lang.RuntimeException: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:514)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:550)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:32)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

UNEXPECTED TOP-LEVEL EXCEPTION:
java.io.FileNotFoundException: /storage/emulated/0/games/minecraft/libraries/optifine/OptiFine/1.7.10_HD_U/OptiFine-1.7.10_HD_U_orig.jar: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:491)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:158)
	at java.util.zip.ZipFile.<init>(ZipFile.java:119)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.pojavdx.dx.command.dexer.Main.processOne(Main.java:682)
	at com.pojavdx.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.pojavdx.dx.command.dexer.Main.runMultiDex(Main.java:361)
	at com.pojavdx.dx.command.dexer.Main.runDx(Main.java:283)
	at com.pojavdx.dx.command.dexer.Main.main(Main.java:241)
	at com.pojavdx.dx.command.Main.main(Main.java:95)
	at net.kdt.pojavlaunch.Tools.runDx(Tools.java:347)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:568)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:477)
	... 22 more
1 error; aborting
Exiting with code 1

**Comment by glancist** [comment]
@khanhduytran0 This appears when I run later version of optifine for 1.7.10.And no it doesn't close like that

**Comment by khanhduytran0** [comment]
Try Optifine in v3.
