### ISSUE TITLE
[BUG] Microsoft Login Error

### ISSUE THREAD

**Issue by RafaelRViana** [PojavLauncherTeam/PojavLauncher#1297]
### Describe the bug
It's not exactly a bug because there was previous closed issues, but I didn't find the answer on them and they're already closed.

I downloaded PojavLauncher to help my son to play Pixelmon as described in this video: https://www.youtube.com/watch?v=E5TXrgqoNIA

But the unique login method at PojavLauncher is through Microsoft Account that throws me error below. I already have purchased Minecraft Pocket Edition at this Microsoft Account and all other issues says that I need to have purchased Minecraft.

Do I need to have PC edition also purchased?

**Add a log file if you want to see your bug fixed !**

java.lang.RuntimeException: MSA Error: 404: Not Found, error stream:
{
"path" : "/minecraft/profile",
"errorType" : "NOT_FOUND",
"error" : "NOT_FOUND",
"errorMessage" : "The server has not found anything matching the request URI",
"developerMessage" : "The server has not found anything matching the request URI"
}
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:276)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:208)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.(Msa.java:44)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. Try to login with Microsoft Account (with Minecraft Pocket Edition bought, but not PC edition)

### Expected behavior:
I expected to have access to PojavLauncher

**Platform:**
 - Device Model: Tablet Samsung Galaxy Tab A7
 - Android Version 10
 - PojavLauncher Version: Lastest Released

**Comment by AutumnVN** [comment]
you cant use pe on pojav

**Comment by GreenNinja00** [comment]
So there is a catch pocket edition is the completely different version then the one pojav uses pojav is a way to play pc version(java) on android so you need to buy it but if you want to play for free in the username section put any name and check the box called use a offline account so you will get a cracked account with it you can play mods but not servers (like hypixel) but you can still play cracked servers (like jartex and pika network) hope this helps
