### ISSUE TITLE
[BUG] <Cannot login my minecraft>

### ISSUE THREAD

**Issue by Wenz-jam** [PojavLauncherTeam/PojavLauncher#1323]
java.lang.RuntimeException: MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
> The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult.
