### ISSUE TITLE
Error to login

### ISSUE THREAD

**Issue by aren215** [PojavLauncherTeam/PojavLauncher#1329]
java.lang.RuntimeException: Respone error, code: 403, message: {"error":"ForbiddenOperationException","errorMessage":"Token does not exist"}
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:16)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.NetworkResponse.throwExceptionIfNeed(NetworkResponse.java:21)
	at net.kdt.pojavlaunch.authenticator.mojang.yggdrasil.YggdrasilAuthenticator.refresh(YggdrasilAuthenticator.java:112)
	at net.kdt.pojavlaunch.authenticator.mojang.RefreshTokenTask.run(RefreshTokenTask.java:22)
	at net.kdt.pojavlaunch.PojavProfile.updateTokens(PojavProfile.java:63)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:32)
	at net.kdt.pojavlaunch.uikit.UIKit.launchUI(Native Method)
	at net.kdt.pojavlaunch.PLaunchApp.main(PLaunchApp.java:39)

**Comment by lxzcl** [comment]
Me too.....

**Comment by khanhduytran0** [comment]
@aren215 plz login again

**Comment by lxzcl** [comment]
Ok ,I try again

**Comment by lxzcl** [comment]
Although there is no solution, but thank you for your reply，I have tried for a long time, but it is still the same, I can be sure that there is no problem with my network

**Comment by Smolbeans2** [comment]
its not a bug.

**Comment by Mathias-Boulay** [comment]
buy the game I guess 😂
