### ISSUE TITLE
OptiFine 1.9 Crash

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#133]
---- Minecraft Crash Report ----
// Sorry :(

Time: 25/4/20 1:41 a. m.
Description: Initializing game

java.lang.IllegalStateException: Already building!
	at bmz.a(VertexBuffer.java:294)
	at bcf.a(SourceFile:852)
	at bcf.a(SourceFile:834)
	at bcf.an(SourceFile:451)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:940)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at bmz.a(VertexBuffer.java:294)
	at bcf.a(SourceFile:852)
	at bcf.a(SourceFile:834)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:330)
	at bcf.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:940)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 4.4.153-perf+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (Xiaomi Redmi Note 7, Android 9), The Android Project
	Memory: 0 bytes (0 MB) / 100881528 bytes (96 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9-OptiFine_HD_U_E3
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 4 (v8l)
	OptiFine Version: OptiFine_1.9_HD_U_E3
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
Try latest OptiFine version or other one.

**Comment by ghost** [comment]
> Try latest OptiFine version or other one.

I tried the latest (OptiFine 1.9.0 HD U H5) and version (OptiFine 1.9.0 HD U E3) I will continue testing versions

**Comment by khanhduytran0** [comment]
@Cesar-Garza please provide result.

**Comment by khanhduytran0** [comment]
re-open if something same wrong
