### ISSUE TITLE
I can't connect on a server

### ISSUE THREAD

**Issue by Siiphanopas02** [PojavLauncherTeam/PojavLauncher#134]
It's the error: INFO beg Connecting to WorldOfPeignoir.cursehosting.fr, 25565
ERROR beg Couldn't connect to server java.net.UnknownHostException: Unable to resolve host "WorldOfPeignoir.cursehosting.fr": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
	at java.net.InetAddress.getByName(InetAddress.java:1108)
	at beg$1.run(SourceFile:60)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
	... 3 more

The server worked on my PC.

**Comment by khanhduytran0** [comment]
Servers with encryption not supported by ART will can't connect.

**Comment by khanhduytran0** [comment]
You may try connect in v3
