### ISSUE TITLE
[BUG] mod installer error

### ISSUE THREAD

**Issue by CharaW12** [PojavLauncherTeam/PojavLauncher#1382]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.minecraftforge.installer.ClientInstall.getSponsorMessage(ClientInstall.java:326)
	at net.minecraftforge.installer.InstallerAction.getSponsorMessage(InstallerAction.java:59)
	at net.minecraftforge.installer.InstallerPanel.updateFilePath(InstallerPanel.java:236)
	at net.minecraftforge.installer.InstallerPanel.<init>(InstallerPanel.java:217)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:153)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:40)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at net.minecraftforge.installer.MirrorData.buildMirrorList(MirrorData.java:84)
	at net.minecraftforge.installer.MirrorData.<init>(MirrorData.java:63)
	at net.minecraftforge.installer.MirrorData.<clinit>(MirrorData.java:17)
	... 6 more

**Comment by WesleyVanNeck** [comment]
Fill the template

**Comment by mchnjt** [comment]
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at net.minecraftforge.installer.ClientInstall.getSponsorMessage(ClientInstall.java:326)
> 	at net.minecraftforge.installer.InstallerAction.getSponsorMessage(InstallerAction.java:59)
> 	at net.minecraftforge.installer.InstallerPanel.updateFilePath(InstallerPanel.java:236)
> 	at net.minecraftforge.installer.InstallerPanel.<init>(InstallerPanel.java:217)
> 	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:153)
> 	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:40)
> Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
> 	at net.minecraftforge.installer.MirrorData.buildMirrorList(MirrorData.java:84)
> 	at net.minecraftforge.installer.MirrorData.<init>(MirrorData.java:63)
> 	at net.minecraftforge.installer.MirrorData.<clinit>(MirrorData.java:17)
> 	... 6 more
> 

you cant install versions below the latest ones
