### ISSUE TITLE
Bug Optifine Installer and launcher_profiles.json

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#14]
There is optifine installer problem...

java.lang.NoClassDefFoundError: Failed resolution of: Lbao;
	at Config.<clinit>(Config.java:106)
	at java.lang.reflect.Field.get(Native Method)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.fromConfig(MCLauncherActivity.java:1036)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1013)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "bao" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/optifine/445062f5aaf982c36c72d90530c26850.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-LgRRVPOwhasYyH8dijQDMQ==/lib/arm64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 11 more

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.7
This is an attempt because I have an old Android device (installer works)

**Comment by Doxelix** [comment]
Thank you

**Comment by khanhduytran0** [comment]
Is it fixed?

**Comment by khanhduytran0** [comment]
If problem appear again, reopen issue.
