### ISSUE TITLE
[BUG] 安装不了forge，会说闪退回主页。

### ISSUE THREAD

**Issue by jjj273** [PojavLauncherTeam/PojavLauncher#1419]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 21-5-23 上午4:22
Description: Initializing game

java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.MainWindow.<init>(MainWindow.java:134) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.VirtualScreen.func_217626_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:373) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2-Forge.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.47.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.2.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.2.jar:?] {}
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: libgl4es_115.so���
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147) ~[?:1.8.0-internal] {}
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71) ~[?:1.8.0-internal] {}
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281) ~[?:1.8.0-internal] {}
	at java.nio.file.Paths.get(Paths.java:84) ~[?:1.8.0-internal] {}
	at org.lwjgl.system.Library.loadNative(Library.java:231) ~[lwjgl.jar:SNAPSHOT] {}
	at org.lwjgl.system.Library.loadNative(Library.java:222) ~[lwjgl.jar:SNAPSHOT] {}
	at org.lwjgl.system.Library.loadNative(Library.java:203) ~[lwjgl.jar:SNAPSHOT] {}
	at org.lwjgl.system.Library.loadNative(Library.java:402) ~[lwjgl.jar:SNAPSHOT] {}
	at org.lwjgl.system.Library.loadNative(Library.java:378) ~[lwjgl.jar:SNAPSHOT] {}
	at org.lwjgl.opengl.GL.create(GL.java:108) ~[lwjgl-glfw-classes.jar:?] {}
	at org.lwjgl.opengl.GL.<clinit>(GL.java:90) ~[lwjgl-glfw-classes.jar:?] {}
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.MainWindow.<init>(MainWindow.java:134)
	at net.minecraft.client.renderer.VirtualScreen.func_217626_a(SourceFile:21)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:373)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (aarch64) version Android-7.1.2
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3329204128 bytes (3174 MB) / 3489660928 bytes (3328 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 2
	JVM Flags: 3 total; -Xms4096M -Xmx4096M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.15.2_HD_U_G6
	OptiFine Build: 20210124-205244
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 2

**Comment by jjj273** [comment]
这上面是出现的bug报告，我看不懂谁能帮我看一下吗？帮我解决一下。

**Comment by khanhduytran0** [comment]
We don't know Chinese, you know.

**Comment by khanhduytran0** [comment]
@jjj273 
> libgl4es_115.so���

Bruh invalid gl4es lib name

**Comment by jjj273** [comment]
You can just read the report on it, and you will know what it means.

**Comment by khanhduytran0** [comment]
> You can just read the report on it, and you will know what it means.

The only thing I see is invalid OpenGL library name.

**Comment by ENDERMANYK** [comment]
更改JVM参数，是不是又在里面加不是英文的字符了？

> 这上面是出现的bug报告，我看不懂谁能帮我看一下吗？帮我解决一下。

**Comment by jjj273** [comment]
不是

**Comment by jjj273** [comment]
我安装不了forge

**Comment by khanhduytran0** [comment]
Then please send latestlog.txt :eyes:

**Comment by mchnjt** [comment]
GitHub translators when :trollface:

**Comment by jjj273** [comment]
我无法安装forge，点击下载的forge文件闪退回主页

**Comment by jjj273** [comment]
这儿没有大佬帮我解决一下

**Comment by mchnjt** [comment]
- could you stop using Google translate? :trollface:

**Comment by jjj273** [comment]
我并没有使用谷歌翻译

**Comment by ENDERMANYK** [comment]
> 这儿没有大佬帮我解决一下

把sdcard/0/games/Pojavlauncher/latestlog.txt发过来
