### ISSUE TITLE
Microsoft account not working

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#1421]
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:292)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

Can't login with microsoft

**Comment by khanhduytran0** [comment]
@KiprasMas 

> AddChildToFamily

**Comment by ghost** [comment]
So what do i do

**Comment by ghost** [comment]
I have no fucking clue what that means

**Comment by WesleyVanNeck** [comment]
> I have no fucking clue what that means

add microsoft account to fammilie

**Comment by ghost** [comment]
Ok how do i do that how do i add microsoft account to a familly

**Comment by mchnjt** [comment]
> java.lang.RuntimeException: 
> 
> MSA Error: 401: Unauthorized, error stream:
> {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:292)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
> 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:919)
> 
> 
> Can't login with microsoft

:trollface: *hello guys welcome to* **searching problem with no** ***fill the template*** label with rsc and we are in episode 3

come on man.
