### ISSUE TITLE
Not loading [black screen]

### ISSUE THREAD

**Issue by infinite9898** [PojavLauncherTeam/PojavLauncher#1454]
The pojav launcher is black screen after clicking the play button in minecraft 1.16.5 java 
My device specs
Lenovo tab M10 fhd
4gb ram

**Comment by mchnjt** [comment]
Any solutions for not ripping the template?

**Comment by firstiik** [comment]
I have the same problem, tried to set up another renderer, force the phone to use GPU, Enable 4x MSAA in OpenGL ES 2.0 applications, delete data / catches, version 1.16.5 and 1.7.10. You can always hear only interactions when clicking on the menu, but the screen is still black, only the controls are visible, I also tried version 3.3.1.1., I currently have the android market version crocus-v3_openjdk, I also tried github version 3.3.1.1., there was the same problem just the screen was dark gray.
ROG phone II 12/512 without root.
1080 x 2340 pixels
Qualcomm SDM855 Snapdragon 855
CPU
Octa-core (1x2.96 GHz Kryo 485 & 3x2.42 GHz Kryo 485 & 4x1.8 GHz Kryo 485)
GPU
Adreno 640 (700 MHz)

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7133776/latestlog.txt)

Here when I tried to start the game with forge.
[Info Java arguments [-Djavaawtheadless=false, -Dcaciomanaged.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7134004/Info.Java.arguments.-Djavaawtheadless.false.-Dcaciomanaged.txt)

[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/7133733/latest.log)
`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3229)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3466)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:7500)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
Caused by: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference
	at net.kdt.pojavlaunch.Tools.dpToPx(Tools.java:386)
	at net.kdt.pojavlaunch.BaseMainActivity.<init>(BaseMainActivity.java:53)
	at net.kdt.pojavlaunch.MainActivity.<init>(MainActivity.java:18)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3217)
	... 11 more`

**Comment by ElijahCoder** [comment]
same problem but i use chromebook

**Comment by GaucovyAero** [comment]
> same problem but i use chromebook

send latestlog.txt

**Comment by ElijahCoder** [comment]
where?

**Comment by ElijahCoder** [comment]
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/9032465/latest.log)
?

**Comment by bobtheplank** [comment]
I am having the same problem where its a black screen and I can still interact with buttons even though I cannot see them. I use chromebook, in 1.8.9, and it was working for 8 hours or something, i leave for about half an hour with pojav still running, come back and its the black screen again.
latestlog is below

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9174613/latestlog.txt)

**Comment by Zhou-Shilin** [comment]
> I am having the same problem where its a black screen and I can still interact with buttons even though I cannot see them. I use chromebook, in 1.8.9, and it was working for 8 hours or something, i leave for about half an hour with pojav still running, come back and its the black screen again. latestlog is below
> 
> [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9174613/latestlog.txt)

same. im using ipados 15.5 (JIT enabled)
