### ISSUE TITLE
Black screen in Alpha/Beta versions.

### ISSUE THREAD

**Issue by Phobos232** [PojavLauncherTeam/PojavLauncher#149]
I tried to release alpha version 1.2.6 and got a black screen, tried beta version 1.7.3 and got the same result. I have a J7 Prime (2017) Android 7.0 I hope there is a solution.

**Comment by Phobos232** [comment]
Btw this is the log:

Downloading a1.2.6 configuration...
Ignored net.java.jinput:jinput:2.0.5
Ignored org.lwjgl.lwjgl:lwjgl:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.0
Ignored org.lwjgl.lwjgl:lwjgl:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl_util:2.9.1-nightly-20130708-debug3
Ignored org.lwjgl.lwjgl:lwjgl-platform:2.9.1-nightly-20130708-debug3
Ignored net.java.jinput:jinput-platform:2.0.5
Ignored net.java.jinput:jinput-platform:2.0.5
Downloading Minecraft %sa1.2.6
Cleaning cache files
Prepaping to download resources

**Comment by khanhduytran0** [comment]
Just Send F11 (fullscreen keycode)

**Comment by Phobos232** [comment]
> Just Send F11 (fullscreen keycode)

I dont know what is that, can you please tell me?
(Im a noob in these things)

**Comment by khanhduytran0** [comment]
- Swipe from right to left
- Press Send custom keycode
- Find `F11` and press it.

**Comment by Phobos232** [comment]
I cant find the Send Custom Keycode that you are talking about.
![Screenshot_20200427-222606](https://user-images.githubusercontent.com/64449367/80439920-9d7f5200-88d5-11ea-9b45-3c7e69482bc0.png)

**Comment by Azapru** [comment]
You must do this when the game is started.

**Comment by khanhduytran0** [comment]
You must start game and swipe the menu.

**Comment by Phobos232** [comment]
Hi again i found this:
java.lang.RuntimeException: javax.net.ssl.SSLException: Read error: ssl=0xc8c83640: I/O error during system call, Software caused connection abort
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:520)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:609)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: javax.net.ssl.SSLException: Read error: ssl=0xc8c83640: I/O error during system call, Software caused connection abort
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:789)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:141)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:466)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:396)
	at java.io.InputStream.read(InputStream.java:101)
	at net.kdt.pojavlaunch.util.IoUtil.pipe(IoUtil.java:31)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:37)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

**Comment by khanhduytran0** [comment]
> I/O error during system call, Software caused connection abort

Check your internet connection, then try again.

**Comment by Phobos232** [comment]
Ok i will try that.

**Comment by Phobos232** [comment]
My internet conection is fine

**Comment by Phobos232** [comment]
Hi, I finally understood what you were talking about, the game works well, it only has no sound and a little lag, although I think that is on my phone, thank you very much!

**Comment by khanhduytran0** [comment]
>  it only has no sound 

Did you download the v2.5?

**Comment by Phobos232** [comment]
I am using version 2.5.0 preview 1

**Comment by khanhduytran0** [comment]
Didn't you skip download assets?

**Comment by Phobos232** [comment]
I just downloaded the apk
