### ISSUE TITLE
Crush zink Virson in Android 11

### ISSUE THREAD

**Issue by tjmu4mhe** [PojavLauncherTeam/PojavLauncher#1496]
--- Describe the bug ---
A clear and concise description of what the bug 
I am send crush file

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/6/21 5:38 AM
Description: Initializing game

java.lang.RuntimeException: glCheckFramebufferStatus returned unknown status:33305
	at bqr.b(SourceFile:151)
	at bqr.a(SourceFile:57)
	at bqr.<init>(SourceFile:42)
	at bes.an(SourceFile:441)
	at bes.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bqr.b(SourceFile:151)
	at bqr.a(SourceFile:57)
	at bqr.<init>(SourceFile:42)
	at bes.an(SourceFile:441)

-- Initialization --
Details:
Stacktrace:
	at bes.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 570184832 bytes (543 MB) / 730857472 bytes (697 MB) up to 730857472 bytes (697 MB)
	JVM Flags: 3 total; -Xms736M -Xmx736M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.11.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: zink (Mali-G52 MC2) GL version 4.6 (Compatibility Profile) Mesa 21.0.2 (git-9d2e7e7940), Collabora Ltd
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 9x null
	OptiFine Version: OptiFine_1.11.2_HD_U_G5
	OptiFine Build: 20210124-162126
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.0.01.zip
	OpenGlVersion: 4.6 (Compatibility Profile) Mesa 21.0.2 (git-9d2e7e7940)
	OpenGlRenderer: zink (Mali-G52 MC2)
	OpenGlVendor: Collabora Ltd
	CpuCount: 8

**Platform:**
 - Device Model [e.g. Realme C25 ]
 - CPU architecture [e.g. aarch64
 - Android Version [e.g. 11]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

**Comment by WesleyVanNeck** [comment]
Stop spanning the issue tracker
