### ISSUE TITLE
[BUG] <BUG>

### ISSUE THREAD

**Issue by ailsonlindo** [PojavLauncherTeam/PojavLauncher#1509]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:208)
	at java.lang.StringBuilder.setLength(Unknown Source:0)
	at net.kdt.pojavlaunch.Tools.getLWJGL3ClassPath(Tools.java:304)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:117)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:764)

**Comment by ghost** [comment]
Pls fill template
