### ISSUE TITLE
V3 preview 3 error

### ISSUE THREAD

**Issue by TarikBR** [PojavLauncherTeam/PojavLauncher#151]
Motorola one vision (android 10) (tested with and without VMOS)

java.lang.RuntimeException: java.lang.NegativeArraySizeException: -1
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadString(DownloadUtils.java:51)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:222)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(Unknown Source:6)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NegativeArraySizeException: -1
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:35)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 9 more

![Screenshot_20200427-223206](https://user-images.githubusercontent.com/64391349/80443161-f86c7580-88e4-11ea-8f63-94a9efa8b1e3.png)
![Screenshot_20200427-223228](https://user-images.githubusercontent.com/64391349/80443164-f99da280-88e4-11ea-9ec5-3a47504cc587.png)
![Screenshot_20200427-223238](https://user-images.githubusercontent.com/64391349/80443166-fa363900-88e4-11ea-9011-66cc7319bd5d.png)
![Screenshot_20200427-224451](https://user-images.githubusercontent.com/64391349/80443167-fb676600-88e4-11ea-87a5-c5a22f7967c1.png)

**Comment by khanhduytran0** [comment]
Enable internet before start.

**Comment by TarikBR** [comment]
but I already have the internet enabled

Em ter, 28 de abr de 2020 00:20, khanhduytran0 <notifications@github.com>
escreveu:

**Comment by Fuzion22** [comment]
Mine don't work either I used VMOS and it still don't work😭😭

**Comment by TarikBR** [comment]
On my j5 prime (custom rom android 9) gave the same error

**Comment by khanhduytran0** [comment]
@TarikBR Try latest one, v3.0.1
