### ISSUE TITLE
Modpacks

### ISSUE THREAD

**Issue by GGGhaith** [PojavLauncherTeam/PojavLauncher#1513]
In evry pc minecraft luncher, there is a modpack loader, please add a feature so we can load modpacks. 

Please make it as putting mod loadere

**Comment by ghost** [comment]
You can

**Comment by ghost** [comment]
Copy to pojav and enjoy

And don't forget to close issue

**Comment by GGGhaith** [comment]
How It didn't work for me

**Comment by GGGhaith** [comment]
@LegacyGamerHD why did you close it please open it

**Comment by GGGhaith** [comment]
@IceCreamUwU I put it in the versions place, and this come: java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/stoneBlock-1.0.37/stoneBlock-1.0.37.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:673)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:402)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:44)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/stoneBlock-1.0.37/stoneBlock-1.0.37.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:741)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:581)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8198)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 13 more

**Comment by GGGhaith** [comment]
@IceCreamUwU if you could send me a video on discord. My ign PikaNeko#9036

**Comment by ghost** [comment]
Install in PC and copy to phone

**Comment by kareemnew2019** [comment]
https://youtube.com/c/FrostBTW
This channel have some tutorials
But modpacks need decent phone
NOT ALL MODPACKS WORK
JUST 80% 1.7.10 MODPACKS
JUST 30% 1.12.2 MODPACKS
JUST 0% 1.16.5 ALL DON'T WORK

**Comment by GGGhaith** [comment]
> Install in PC and copy to phone

Dude to where I should paste it in pojavluncher, that is what I am asking

**Comment by GGGhaith** [comment]
And I made this issue to make it like pc, run modpacks like pc
