### ISSUE TITLE
You can't land in Microsoft.

### ISSUE THREAD

**Issue by jjvjj** [PojavLauncherTeam/PojavLauncher#1532]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug

**Add a log file if you want to see your bug fixed !**

The log file called *latestlog.txt* is located under "*Android/data/net.kdt.pojavlaunch/files*", "*games/PojavLauncher/*" or "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
... *(your set of actions to reproduce the bug)*

### Expected behavior:
I expected ...

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model [e.g. Mi 8 Pro 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]
 - PojavLauncher Version [e.g Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:292)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by khanhduytran0** [comment]
@jjvjj attempt to login using an account which wasn't even created yet. bruh
