### ISSUE TITLE
Patched a1.2.6 not working

### ISSUE THREAD

**Issue by anton2007** [PojavLauncherTeam/PojavLauncher#155]
not working retrowrapper versions i patched a1.2.6 please help me!

**Comment by khanhduytran0** [comment]
Anything about this?

**Comment by anton2007** [comment]
> Anything about this?

I need to play a1.2.6 server it server request retrowrapper

**Comment by khanhduytran0** [comment]
Please give me the error log.

**Comment by anton2007** [comment]
> Please give me the error log.

java.lang.RuntimeException: Unable to convert library com.zero:retrowrapper:installer
java.lang.RuntimeException: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:520)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:555)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:6)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:32)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

UNEXPECTED TOP-LEVEL EXCEPTION:
java.io.FileNotFoundException: File doesn't exist: /storage/emulated/0/games/minecraft/libraries/com/zero/retrowrapper/installer/retrowrapper-installer_orig.jar
	at java.util.zip.ZipFile.<init>(ZipFile.java:212)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.pojavdx.dx.command.dexer.Main.processOne(Main.java:682)
	at com.pojavdx.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.pojavdx.dx.command.dexer.Main.runMultiDex(Main.java:361)
	at com.pojavdx.dx.command.dexer.Main.runDx(Main.java:283)
	at com.pojavdx.dx.command.dexer.Main.main(Main.java:241)
	at com.pojavdx.dx.command.Main.main(Main.java:95)
	at net.kdt.pojavlaunch.Tools.runDx(Tools.java:353)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:573)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:6)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
1 error; aborting
Exiting with code 1

**Comment by khanhduytran0** [comment]
>  File doesn't exist: /storage/emulated/0/games/minecraft/libraries/com/zero/retrowrapper/installer/retrowrapper-installer_orig.jar

Did you put?

**Comment by anton2007** [comment]
![Screenshot_20200428-152003](https://user-images.githubusercontent.com/37032392/80464284-c77f5580-8963-11ea-82e4-cd4a875084cf.png)

**Comment by anton2007** [comment]
> > File doesn't exist: /storage/emulated/0/games/minecraft/libraries/com/zero/retrowrapper/installer/retrowrapper-installer_orig.jar
> 
> Did you put?

New error

**Comment by khanhduytran0** [comment]
> ![Screenshot_20200428-152003](https://user-images.githubusercontent.com/37032392/80464284-c77f5580-8963-11ea-82e4-cd4a875084cf.png)
> 

Just ignore if you click Exit.

**Comment by anton2007** [comment]
> > ![Screenshot_20200428-152003](https://user-images.githubusercontent.com/37032392/80464284-c77f5580-8963-11ea-82e4-cd4a875084cf.png)
> 
> Just ignore if you click Exit.

Minecraft not working

**Comment by khanhduytran0** [comment]
Maybe try regular unmodified?
