### ISSUE TITLE
[BUG] Can't Login Using Microsoft Account

### ISSUE THREAD

**Issue by kimsmith65** [PojavLauncherTeam/PojavLauncher#1566]
I have already a microsoft account.
I even created a new account just for pojavlauncher

But if i login with it, this is what it says:

java.lang.RuntimeException: Can't login a demo account!

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:292)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

And unfortunately some of them i didn't read cause it's quite long and I can't read some of them.

Will you add this feature in the next version?
Will it update?

**Comment by khanhduytran0** [comment]
You have a Microsoft account doesn't mean that **you have bought Minecraft** worth of $26.

**Comment by Druxelite** [comment]
Did you buy minecraft java edition with the microsoft account?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: kimsmith65 ***@***.***>
Sent: Saturday, June 19, 2021 7:57:22 PM
To: PojavLauncherTeam/PojavLauncher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PojavLauncherTeam/PojavLauncher] [BUG] Can't Login Using Microsoft Account (#1566)


I have already a microsoft account.
I even created a new account just for pojavlauncher

But if i login with it, this is what it says:

java.lang.RuntimeException: Can't login a demo account!

MSA Error: 404: Not Found, error stream:
{
"path" : "/minecraft/profile",
"errorType" : "NOT_FOUND",
"error" : "NOT_FOUND",
"errorMessage" : "The server has not found anything matching the request URI",
"developerMessage" : "The server has not found anything matching the request URI"
}
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:292)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
at net.kdt.pojavlaunch.authenticator.microsoft.Msa.(Msa.java:35)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)

And unfortunately some of them i didn't read cause it's quite long and I can't read some of them.

Will you add this feature in the next version?
Will it update?

**Comment by khanhduytran0** [comment]
> Did you buy minecraft java edition with the microsoft account?
> 
> Get Outlook for Android<https://aka.ms/AAb9ysg>

He didn't says that he bought Minecraft.
