### ISSUE TITLE
show hidden files for pojavlauncher because it says no such file or directory and my system makes all files that start with "." are hidden and I can't install mods because of that

### ISSUE THREAD

**Issue by iFady** [PojavLauncherTeam/PojavLauncher#1571]
### No such file or directory
My phone automatically hide folders start with "." so pojavlauncher can't find the versions folder to install forge because the mc folder name is ".Minecraft"

**there are very few information In the latest logs file**

**Platform:**
 - Device Model [x3 nfc 6/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [ 10]
 - PojavLauncher Version [Latest Release || version 3.3.1.1_rel_20210206 ]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by Mathias-Boulay** [comment]
No template.
Fill it or be terminated.

**Comment by iFady** [comment]
> No template.
> Fill it or be terminated.

sorry wdym

**Comment by iFady** [comment]
![IMG_20210621_035442.jpg](https://user-images.githubusercontent.com/86205728/122697632-034f3b80-d246-11eb-82d2-082b807ab932.jpg)

**Comment by iFady** [comment]
I don't know how to upload latestlogs.txt but here's a screenshot (385b) ![Screenshot_2021-06-21-04-08-03-648_cn.wps.xiaomi.abroad.lite.jpg](https://user-images.githubusercontent.com/86205728/122697779-51643f00-d246-11eb-8c29-dedb663e1658.jpg)

**Comment by nabiloi** [comment]
you can reinstall minecraft version,may be?

**Comment by khanhduytran0** [comment]
@iFady You have an outdated build. Get latest from google play.

**Comment by iFady** [comment]
> @iFady You have an outdated build. Get latest from google play.

ok

**Comment by iFady** [comment]
> you can reinstall minecraft version,may be?

ok

**Comment by iFady** [comment]
> @iFady You have an outdated build. Get latest from google play.

tried it, i tried installing forge 1.7.10 then it gave me 3 options (extract, install server, install client) I installed client and it said "these libraries couldn't be downloaded (libraries idk them but I can tell you if I redo it) then my screen got stuck in black I waited some time and restarted then I tried running forge it had the same error even though I deleted the **games** file and uninstalled pojavlauncher

**Comment by iFady** [comment]
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.7.10-Forge10.13.4.1614-1.7.10/1.7.10-Forge10.13.4.1614-1.7.10.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:673)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:402)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:44)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.7.10-Forge10.13.4.1614-1.7.10/1.7.10-Forge10.13.4.1614-1.7.10.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:741)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:581)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7464)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 13 more

**Comment by iFady** [comment]
nevermind, thanks it worked
