### ISSUE TITLE
[BUG] crashes

### ISSUE THREAD

**Issue by Calexanderr** [PojavLauncherTeam/PojavLauncher#1582]
When I try to download something crashes when I open a version sometimes crashes but what I complain about is this code when I try to change the section crashes and it does not let me do anything              code:java.lang.IllegalStateException: Could not execute method for android:onClick
	at android.view.View$DeclaredOnClickListener.onClick(View.java:6033)
	at android.view.View.performClick(View.java:7192)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.view.View$DeclaredOnClickListener.onClick(View.java:6028)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String net.kdt.pojavlaunch.value.MinecraftAccount.accessToken' on a null object reference
	at net.kdt.pojavlaunch.value.MinecraftAccount.load(MinecraftAccount.java:56)
	at net.kdt.pojavlaunch.PojavLoginActivity.loginSavedAcc(PojavLoginActivity.java:656)
	... 13 more

**Comment by rscAvePlex** [comment]
Oh boi, that's not the log we want.

**Comment by Mathias-Boulay** [comment]
Fill the template or the issue will be terminated
