### ISSUE TITLE
Bug optifine installer (again.)

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#16]
Problem

java.lang.NoSuchFieldException: No field optifineOutputJar in class Loptifine/AndroidOptiFineUtilities; (declaration of 'optifine.AndroidOptiFineUtilities' appears in /storage/emulated/0/games/minecraft/optifine/445062f5aaf982c36c72d90530c26850.jar)
	at java.lang.Class.getDeclaredField(Native Method)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1023)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:6)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by khanhduytran0** [comment]
Delete folder /storage/sdcard0/games/minecraft/optifine and try again

**Comment by khanhduytran0** [comment]
Some optifine will error: `Trucanted source file aborting`. Current no workaround.

**Comment by khanhduytran0** [comment]
also delete optifine generated library

**Comment by Doxelix** [comment]
Ok
