### ISSUE TITLE
When i open my launcher i get this error and i cant play any versions

### ISSUE THREAD

**Issue by FireSight32** [PojavLauncherTeam/PojavLauncher#1607]
java.io.FileNotFoundException: /data/app/net.kdt.pojavlaunch-1/lib/x86/libawt_xawt.so (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at net.kdt.pojavlaunch.PojavLoginActivity.copyDummyNativeLib(PojavLoginActivity.java:462)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:389)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:74)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:159)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:101)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by khanhduytran0** [comment]
@FireSight32 bruh fill the template

**Comment by khanhduytran0** [comment]
or this will be closed

**Comment by FireSight32** [comment]
what is the template sorry.

**Comment by WesleyVanNeck** [comment]
> what is the template sorry.

The thing at begin of your issue ...
