### ISSUE TITLE
Game file automatically getting delete

### ISSUE THREAD

**Issue by Dharm24** [PojavLauncherTeam/PojavLauncher#1609]
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.16.5-OptiFine_HD_U_G8/1.16.5-OptiFine_HD_U_G8.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:606)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:335)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:44)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.16.5-OptiFine_HD_U_G8/1.16.5-OptiFine_HD_U_G8.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:674)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:525)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8448)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 13 more

**Comment by mchnjt** [comment]
dumb

it's not a bug
