### ISSUE TITLE
When I tried to run 1.17, it crashed after mojang[BUG] <Short description>

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#1620]
<！--
如果您不填写此模板，此问题将被标记为无效并关闭。
->

<Details><汇总><b>提交前阅读</b></汇总>
<br>
-确保没有重复的问题。<br>
-确保您已填写此问题模板，否则将被拒绝。
</Details>

#描述bug
对错误是什么的清晰而简明的描述。

**如果您希望看到您的错误得到修复，请添加日志文件！**

名为*latestlog.txt*的日志文件位于“*android/data/net.kdt.pojavstart/files*”、“*Games/PojavLauncher/*”或“*Games/PojavLauncher/.min克拉夫特*”下面。
您可能需要在文件资源管理器中激活一个选项来查看隐藏的文件和文件夹。

不要粘贴整个日志文本！相反，将其添加为有关此问题的文件。

##复制：
指出再现bug行为的步骤：

1.启动PojavLauncher
.*(您的一组复制bug的操作)*

##预期行为：
我以为..。

#截图或视频：
*如果可能的话，在这里上传错误行为的截图或视频。

**平台：**
-装置型号[例如Mi 8 Pro 8/128]
-CPU架构[例如aarch64]
-Android版本[例如10]
-PojavLauncher版本[例如最新的发行版_REL_20210206]

<Details><汇总><b>附加上下文</b></汇总>
<br>
<PRE>
在这里添加有关此问题的任何其他上下文。
</PRE>
</Details>

**Comment by yanluol** [comment]
---- Minecraft Crash Report ----
// Oops.

Time: 2021/7/4 上午10:08
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at ena.b(SourceFile:492)
	at ena.a(SourceFile:380)
	at adu.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)
	at dpq.e(SourceFile:310)
	at dvo.f(SourceFile:1139)
	at dvo.e(SourceFile:730)
	at net.minecraft.client.main.Main.main(SourceFile:217)
Caused by: wz: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 1:16: 'clamp' : no matching overloaded function found 
ERROR: 1:16: 'texture' : no matching overloaded function found 
ERROR: 1:16: 'return' : function return is not matching type: 
ERROR: 4 compilation errors.  No code generated.
	at wz.a(SourceFile:48)
	at ens.<init>(SourceFile:197)
	at ena.b(SourceFile:448)
	... 118 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 1:16: 'clamp' : no matching overloaded function found 
ERROR: 1:16: 'texture' : no matching overloaded function found 
ERROR: 1:16: 'return' : function return is not matching type: 
ERROR: 4 compilation errors.  No code generated.
	at dpz.b(SourceFile:72)
	at dpz.a(SourceFile:54)
	at ens.a(SourceFile:237)
	at ens.<init>(SourceFile:179)
	... 119 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ena.b(SourceFile:492)
	at ena.a(SourceFile:380)
	at adu.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqu.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)

-- Overlay render details --
Details:
	Overlay name: ead
Stacktrace:
	at ena.a(SourceFile:867)
	at dvo.f(SourceFile:1114)
	at dvo.e(SourceFile:730)
	at net.minecraft.client.main.Main.main(SourceFile:217)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1591510728 bytes (1517 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 12 (aarch64)
	Identifier: 0x51 Family 8 Model 0x802 Stepping r0x7p12
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5374.95
	Virtual memory used (MB): 6160.83
	Swap memory total (MB): 2560.00
	Swap memory used (MB): 929.57
	JVM Flags: 2 total; -Xms4096M -Xmx4096M
	Launched Version: 1.17
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 2159x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x AArch64 Processor rev 13 (aarch64)

**Comment by khanhduytran0** [comment]
~~bruh 1.17 is UNsupported!~~

**Comment by khanhduytran0** [comment]
**Minecraft 1.17 is not working?**
The “fix” is here <:ULTIMATEROFEL:786306660141629441> 

• __Notes__:
- Requires a GitHub account logged in to download stuff below.
- Download [this resource pack](https://cdn.discordapp.com/attachments/724164160761626624/860864619350065162/assets-v0.zip). This patches the shader to work on gl4es.

• __Known issues__:
- [Android only] Crosshair icon doesn’t render.
- ~~Tell us~~

• __Android__:
- Get latest build: [here](<https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk>).
- Get JRE17: [here](<https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/actions?query=branch%3Abuildjre16>). Pick the artifact that matches your device architecture: `jre17-<architecture>`, don’t pick `jdk17` or `debuginfo`.
- Install APK, it will be displayed as second app if you have one installed before.
- Install the downloaded JRE17 runtime on the second app.
- Go to launcher settings, switch renderer to `gl4es 1.1.5 - OpenGL ES 2 or 3`.
- Enable show hidden folder on your file manager.
- Go to `/sdcard/games/PojavLauncher/.minecraft/resourcepacks`, place the downloaded resource pack here.
- Go up (go to `.minecraft` folder), edit options.txt: modify `resourcePacks` key:
`resourcePacks:["assets-v0.zip"]`
- Now launch Minecraft 1.17 and enjoy!

**Comment by yanluol** [comment]
thanks

**Comment by yanluol** [comment]
Has entered the game, but no sound and adjust the language

**Comment by ghost** [comment]
How to install jre in the game

**Comment by ghost** [comment]
@yanluol 
How you make it work

**Comment by ghost** [comment]
@khanhduytran0

**Comment by yanluol** [comment]
Download the latest version without runtime, and then import jre17

**Comment by LANCECRAFT1104** [comment]
@yanluol TANGA KA BA? AN DOON NA NGA YUNG INSTRUCTIONS!

**Comment by yanluol** [comment]
???

**Comment by ghost** [comment]
How to install jre in the game itself @LANCECRAFT1104

**Comment by ghost** [comment]
> Download the latest version without runtime, and then import jre17

How do you import it?

**Comment by yanluol** [comment]
Enter the software, he will remind you to install the runtime

**Comment by ghost** [comment]
Ok thx

**Comment by khanhduytran0** [comment]
Duplicate of #1035
