### ISSUE TITLE
An issue in server

### ISSUE THREAD

**Issue by ZH-XiJun** [PojavLauncherTeam/PojavLauncher#163]
I'm playing MineMC server (a offline-server) , you know a server has multiple world so we need move in every world. The bug is over there, I can't move to other world. When I do this, the game crash. How to do?
The original word (If you can't read, go to Google Translate)
原文（如果看不懂自行Google Translate）
我在玩MineMC（离线服务器），一个服务器有多个世界，我们需要在这些世界里来回穿梭，这个你应该都知道的。Bug就在这，我不能移动到其他世界，不然游戏就崩溃。怎么办？
Crash log? Try to visit baidu.com first! (I can't visit Google Drive)
崩溃报告？先试试能不能访问baidu.com（我不能访问谷歌云盘）
Just a kidding, Crash log in 2nd floor
开个玩笑，崩溃报告在二楼
crash log in 2nd floor is wrong, look at down!
二楼的崩溃报告错了，再看看下面！

**Comment by ZH-XiJun** [comment]
2 floor!
I think '2nd floor' is right

---- Minecraft Crash Report ----
// There are four lights!

Time: 2020/4/26 15:52
Description: Initializing game

java.lang.IllegalStateException: Only one LWJGL context may be instantiated at any one time.
	at org.lwjgl.opengl.Display.create(Unknown Source:13)
	at org.lwjgl.opengl.Display.create(Unknown Source:7)
	at bcf.ap(SourceFile:581)
	at bcf.an(SourceFile:430)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.Display.create(Unknown Source:13)
	at org.lwjgl.opengl.Display.create(Unknown Source:7)
	at bcf.ap(SourceFile:581)

-- Initialization --
Details:
Stacktrace:
	at b.a(SourceFile:244)
	at bcf.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 4.9.186-perf-gd054b09
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (Xiaomi MI 8, Android 10), The Android Project
	Memory: 4409400 bytes (4 MB) / 143902376 bytes (137 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'bwp bwq.c()' on a null object reference
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by ZH-XiJun** [comment]
2nd floor
---- Minecraft Crash Report ----
// There are four lights!

Time: 2020/4/26 15:52
Description: Initializing game

java.lang.IllegalStateException: Only one LWJGL context may be instantiated at any one time.
	at org.lwjgl.opengl.Display.create(Unknown Source:13)
	at org.lwjgl.opengl.Display.create(Unknown Source:7)
	at bcf.ap(SourceFile:581)
	at bcf.an(SourceFile:430)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.Display.create(Unknown Source:13)
	at org.lwjgl.opengl.Display.create(Unknown Source:7)
	at bcf.ap(SourceFile:581)

-- Initialization --
Details:
Stacktrace:
	at b.a(SourceFile:244)
	at bcf.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 4.9.186-perf-gd054b09
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (Xiaomi MI 8, Android 10), The Android Project
	Memory: 4409400 bytes (4 MB) / 143902376 bytes (137 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'bwp bwq.c()' on a null object reference
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by ZH-XiJun** [comment]
### **THIS IS THE WRONG CRASH LOG**
### **LOOK AT DOWN**

**Comment by ZH-XiJun** [comment]
something is not displayed or not true, and I don't know how can I upload the crash log (Google Drive is unworkable)

**Comment by khanhduytran0** [comment]
> java.lang.IllegalStateException: Only one LWJGL context may be instantiated at any one time.

Are you trying to launch multiple versions?

**Comment by ZH-XiJun** [comment]
No, I'm not. I just move to other world.

**Comment by ZH-XiJun** [comment]
wait, this is the wrong crash report

**Comment by ZH-XiJun** [comment]
```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2020/5/3 22:40
Description: Rendering item

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bwn.a(SourceFile:126)
	at bpu.a(SourceFile:81)
	at bne.a(SourceFile:67)
	at brz.a(SourceFile:152)
	at brz.a(SourceFile:328)
	at brz.a(SourceFile:363)
	at bcu.a(SourceFile:1017)
	at bcu.a(SourceFile:466)
	at bcu.a(SourceFile:155)
	at bng.a(SourceFile:1038)
	at bcf.av(SourceFile:985)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at bwn$1.a(SourceFile:47)
	at bwn$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bwn.a(SourceFile:126)
	at bpu.a(SourceFile:81)
	at bne.a(SourceFile:67)
	at brz.a(SourceFile:152)

-- Item being rendered --
Details:
	Item Type: aeq@76b603b
	Item Aux: 3
	Item NBT: {ench:[0:{lvl:0s,id:32s}],HideFlags:63,SkullOwner:{Id:"e367d6c7-8354-318b-a6b4-5ba49fcc3331",Properties:{textures:[0:{Signature:"X/vgDihdXj4xeRRCylJMzdx+uth3Ra4oFvy5foTYt/HDj0B4/9gvbChMcjjrR1pE+URx2kKRsv9abGHv5lsi+NbT9K2O0hJB4OckVei7msgLhXsTHu7oUqSZPy2REJZnU/3OCsNqZi3UEpT/XvExkYpjdf7MMGrmX+S/5XtTv+xjf5bOHGwIrE2Bx/hmEmFsTO+BGRidTSS1NLFMXlel2kyf5TAyh82F/xZ07zlXj9wAZ+pU7h2zI9W/jyeCBipuwDIeFUSuZHhfJfLIMVdood70roXXUmNpdfhpKModx5lqwh2WiHL5Sj6NptvmByNgUSmap2h6miFcEa/dE108dHn/WWcdIxmApGBcpdyPliECUJvrJu7zmn1JJTERmDXNL/zUlYz9xU+Va8lm85mkCs/TLBQQMWRRPRE9ZKX6tNJkjPbGQWU9i5pzhq2SjDEVav3jhii5gXeReWEvIRjYcCjc/HPFBI+a/jQdg0koCIVOGF1gebzWgMKkXI9gU5EgjfUXLje6H8Q97rGnZAax/448lHzlaYQngsFgNnp6GJLh0qc3Nw86tR81bt/RwU5zvDXK9opc7r7AvFB4hWMUdPOPZ/96GrBW1hIKFp+ch7M52FOngqzXwFTnj3uN4/9iKzh7235s0gEPuxOL+8TOheyP6U03yj4FcvZmrw82rmM=",Value:"ewogICJ0aW1lc3RhbXAiIDogMTU4ODUxNjI3Mjc1OSwKICAicHJvZmlsZUlkIiA6ICI1MDNhYzVlYmUyMDQ0ZjE5OTg0NWQyMjA1MWUxNmI2MSIsCiAgInByb2ZpbGVOYW1lIiA6ICJjb2xkbWFuMjAxOCIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kNGZiNjdhZGQ3NjQ3NTA2NGE4ZTBjZWQ5YzFkMzZkNDJjNjQwYWM4Mzk4MmRmYmVlM2YwNzU0MTJjMmIzYTYiCiAgICB9CiAgfQp9"}]},Name:"coldman2018"},display:{Lore:[0:"§7我的称号我做主~"],Name:"§6§l更换称号"}}
	Item Foil: true
Stacktrace:
	at b.a(SourceFile:244)
	at brz.a(SourceFile:366)
	at bcu.a(SourceFile:1017)
	at bcu.a(SourceFile:466)
	at bcu.a(SourceFile:155)
	at bng.a(SourceFile:1038)
	at bcf.av(SourceFile:985)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)

-- Affected level --
Details:
	Level name: MpServer
	All players: 11 total; [bmt['coldman2018'/25538, l='MpServer', x=-1498.50, y=78.00, z=575.50], bmu['Lera2212'/4751, l='MpServer', x=-1498.50, y=78.00, z=575.50], bmu['Meng_Ycbl'/4752, l='MpServer', x=-1498.44, y=78.00, z=575.50], bmu['Q_XinE'/53, l='MpServer', x=-1482.50, y=75.00, z=562.56], bmu['SB'/59, l='MpServer', x=-1474.59, y=74.50, z=560.69], bmu['SB'/62, l='MpServer', x=-1474.63, y=74.50, z=562.41], bmu['SB'/65, l='MpServer', x=-1473.66, y=74.50, z=561.41], bmu['SB'/68, l='MpServer', x=-1475.59, y=74.50, z=561.59], bmu['***'/47, l='MpServer', x=-1482.53, y=75.00, z=588.38], bmu['疫情主题'/44, l='MpServer', x=-1469.69, y=74.00, z=575.44], bmu['_DJQ_'/50, l='MpServer', x=-1470.38, y=75.00, z=562.56]]
	Chunk stats: MultiplayerChunkCache: 20, 20
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1497,78,575), Chunk: (at 7,4,15 in -94,35; contains blocks -1504,0,560 to -1489,255,575), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
	Level time: 1087682 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 21 total; [bmu['SB'/65, l='MpServer', x=-1473.66, y=74.50, z=561.41], bmu['SB'/68, l='MpServer', x=-1475.59, y=74.50, z=561.59], bmt['coldman2018'/25538, l='MpServer', x=-1498.50, y=78.00, z=575.50], bmu['Lera2212'/4751, l='MpServer', x=-1498.50, y=78.00, z=575.50], bmu['Meng_Ycbl'/4752, l='MpServer', x=-1498.44, y=78.00, z=575.50], bmu['Q_XinE'/53, l='MpServer', x=-1482.50, y=75.00, z=562.56], bmu['SB'/59, l='MpServer', x=-1474.59, y=74.50, z=560.69], bmu['SB'/62, l='MpServer', x=-1474.63, y=74.50, z=562.41], bmu['SB'/65, l='MpServer', x=-1473.66, y=74.50, z=561.41], bmu['疫情主题'/44, l='MpServer', x=-1469.69, y=74.00, z=575.44], bmu['SB'/68, l='MpServer', x=-1475.59, y=74.50, z=561.59], bmu['***'/47, l='MpServer', x=-1482.53, y=75.00, z=588.38], bmu['Lera2212'/4751, l='MpServer', x=-1498.50, y=78.00, z=575.50], bmu['***'/47, l='MpServer', x=-1482.53, y=75.00, z=588.38], bmu['疫情主题'/44, l='MpServer', x=-1469.69, y=74.00, z=575.44], bmu['Meng_Ycbl'/4752, l='MpServer', x=-1498.44, y=78.00, z=575.50], bmu['_DJQ_'/50, l='MpServer', x=-1470.38, y=75.00, z=562.56], bmu['_DJQ_'/50, l='MpServer', x=-1470.38, y=75.00, z=562.56], bmu['Q_XinE'/53, l='MpServer', x=-1482.50, y=75.00, z=562.56], bmu['SB'/59, l='MpServer', x=-1474.59, y=74.50, z=560.69], bmu['SB'/62, l='MpServer', x=-1474.63, y=74.50, z=562.41]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:b4b998b:1474) <- PaperSpigot
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 4.9.186-perf-gd054b09
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (Xiaomi MI 8, Android 10), The Android Project
	Memory: 0 bytes (0 MB) / 325867288 bytes (310 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: New Default Betapack V2.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 12 (v8l)
```

**Comment by ZH-XiJun** [comment]
that is true.

**Comment by khanhduytran0** [comment]
This can be fixed by replace Google Guava.

**Comment by ZH-XiJun** [comment]
？？？？？？？？？？？？HOW TO DO？？？？？？？？？？？？

**Comment by artdeell** [comment]
json modification?
or just downloading and copy-pasting required lib?
the only two ways for end-user.

**Comment by khanhduytran0** [comment]
> or just downloading and copy-pasting required lib?

https://mvnrepository.com/artifact/com.google.guava/guava

There are same version with android edition.

**Comment by ZH-XiJun** [comment]
awa

**Comment by artdeell** [comment]
https://github.com/google/guava/tree/master/android

**Comment by ZH-XiJun** [comment]
ok, now I'm downloading `29.0-android`

**Comment by ZH-XiJun** [comment]
should I update Google Guava?
The latest version is 29.0 but my Guava is only 17.0 and 21.0
and the size is not same!!!
I'm already replaced

**Comment by ZH-XiJun** [comment]
not good, the game is crashed

**Comment by ZH-XiJun** [comment]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.VerifyError: Verifier rejected class bcf: com.google.common.util.concurrent.ListenableFuture bcf.a(java.util.concurrent.Callable) failed to verify: com.google.common.util.concurrent.ListenableFuture bcf.a(java.util.concurrent.Callable): [0x2B] copy1 v5<-v3 type=Undefined cat=3 (declaration of 'bcf' appears in /storage/emulated/0/games/minecraft/versions/1.9/1.9.jar!classes6.dex)
	at bcf.I(SourceFile:2744)
	at net.minecraft.client.main.Main.main(SourceFile:39)
	... 5 more

**Comment by khanhduytran0** [comment]
Try older Guava versions!!!

**Comment by ZH-XiJun** [comment]
I replaced the same version of Guava(17.0)
so game crashed

**Comment by ZH-XiJun** [comment]
and I'm not tried other version

**Comment by khanhduytran0** [comment]
Try v3.
