### ISSUE TITLE
[BUG] Unable to open the create mod for 1.16.5. Crash a few seconds after entry. Is this a problem with the renderer

### ISSUE THREAD

**Issue by KurashinaSyou** [PojavLauncherTeam/PojavLauncher#1643]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 21/07/09 0:47
Description: Rendering overlay

java.lang.RuntimeException: Could not compile shader. See log for details.
	at com.simibubi.create.foundation.render.backend.gl.shader.GlShader.<init>(GlShader.java:31) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.loadShader(ShaderLoader.java:178) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.loadProgram(ShaderLoader.java:124) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.loadProgramFromSpec(ShaderLoader.java:103) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0-internal] {}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.onResourceManagerReload(ShaderLoader.java:66) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at net.minecraftforge.resource.ISelectiveResourceReloadListener.func_195410_a(ISelectiveResourceReloadListener.java:33) ~[forge:?] {re:classloading}
	at net.minecraft.resources.IResourceManagerReloadListener.func_232635_a_(IResourceManagerReloadListener.java:18) ~[?:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0-internal] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) ~[?:1.8.0-internal] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0-internal] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.32.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.32.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.simibubi.create.foundation.render.backend.gl.shader.GlShader.<init>(GlShader.java:31) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.loadShader(ShaderLoader.java:178) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.loadProgram(ShaderLoader.java:124) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.loadProgramFromSpec(ShaderLoader.java:103) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:981) ~[?:1.8.0-internal] {}
	at com.simibubi.create.foundation.render.backend.ShaderLoader.onResourceManagerReload(ShaderLoader.java:66) ~[create:mc1.16.5_v0.3.1c+151] {re:classloading}
	at net.minecraftforge.resource.ISelectiveResourceReloadListener.func_195410_a(ISelectiveResourceReloadListener.java:33) ~[forge:?] {re:classloading}
	at net.minecraft.resources.IResourceManagerReloadListener.func_232635_a_(IResourceManagerReloadListener.java:18) ~[?:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[?:1.8.0-internal] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) ~[?:1.8.0-internal] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0-internal] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:484) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:ShaderCloseMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.1.32.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.32.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1791162704 bytes (1708 MB) / 2134900736 bytes (2036 MB) up to 2134900736 bytes (2036 MB)
	CPUs: 7
	JVM Flags: 3 total; -Xms2050M -Xmx2050M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.32.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.32.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.32
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.32-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.32-universal.jar                |Forge                         |forge                         |36.1.32             |ENQUEUE_IM|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 7c50160d-5e5d-4854-adb1-26285fc78d69
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 9x null

**Comment by khanhduytran0** [comment]
Create mod is not supported. Did you read the crash report? *It uses shader!* *you will have to insert RTX 3090 into your device to get it work* :trollface:

**Comment by khanhduytran0** [comment]
also, fill the template
