### ISSUE TITLE
[BUG] <unable to run 1.17 optifine>

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#1690]
### Describe the bug

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 18.07.2021, 11:26
Description: Initializing game

java.lang.IllegalStateException: could not preload shader rendertype_text
	at ena.a(GameRenderer.java:464)
	at ena.a(GameRenderer.java:450)
	at dvo.<init>(SourceFile:625)
	at net.minecraft.client.main.Main.main(SourceFile:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: wz: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:26: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at wz.a(SourceFile:48)
	at ens.<init>(ShaderInstance.java:214)
	at ena.a(GameRenderer.java:458)
	... 9 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:26: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at dpz.b(Program.java:94)
	at dpz.a(Program.java:55)
	at ens.a(ShaderInstance.java:253)
	at ens.<init>(ShaderInstance.java:187)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ena.a(GameRenderer.java:464)
	at ena.a(GameRenderer.java:450)
	at dvo.<init>(SourceFile:625)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 902870512 bytes (861 MiB) / 1719664640 bytes (1640 MiB) up to 1719664640 bytes (1640 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 2 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd09 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4079,94
	Virtual memory used (MB): 4244,75
	Swap memory total (MB): 2240,00
	Swap memory used (MB): 1013,19
	JVM Flags: 2 total; -Xms1640M -Xmx1640M
	Launched Version: 1.17
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 8x AArch64 Processor rev 2 (aarch64)
	OptiFine Version: OptiFine_1.17_HD_U_G9_pre26
	OptiFine Build: 20210709-184608
	Render Distance Chunks: 10
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
1.Downloaded and installed preview_OptiFine_1.17_HD_U_G9_pre26
2. I launched this version and the game unexpectedly crashed.
```

### Expected Behavior

I expected the game to start, but there was an error 

### Platform

```markdown
- Device model:honor 9c 
- CPU architecture:aarch64 
- Android version:10
- PojavLauncher version:3.3.1.1
```

**Comment by khanhduytran0** [comment]
Neither 1.17 optifine nor sodium is supported at the moment.

**Comment by ghost** [comment]
its supported i can play with optifine
