### ISSUE TITLE
[BUG] <Short description>java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference 	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91) 	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906) 	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27) 	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709) 	at java.lang.Thread.run(Thread.java:919)

### ISSUE THREAD

**Issue by King26d** [PojavLauncherTeam/PojavLauncher#1719]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
@King26d ~~ok boomer~~
