### ISSUE TITLE
[BUG] <Short description>java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference 	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91) 	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906) 	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27) 	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709) 	at java.lang.Thread.run(Thread.java:919)

### ISSUE THREAD

**Issue by King26d** [PojavLauncherTeam/PojavLauncher#1720]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)
Please help

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)
```

### Expected Behavior

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)

**Comment by khanhduytran0** [comment]
Anything else?
Spam?

**Comment by khanhduytran0** [comment]
@King26d ~~ok boomer~~
