### ISSUE TITLE
CODE 1 GAME CLOSED

### ISSUE THREAD

**Issue by slimiii** [PojavLauncherTeam/PojavLauncher#1736]
### Describe the bug

My game closed and shows Code 1
I dont know what I can do now...
Please help I just need to play java and now this happened...

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.17.1-rc2/1.17.1-rc2.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:673)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:402)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:44)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.17.1-rc2/1.17.1-rc2.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:741)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:581)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8373)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 13 more

### Steps To Reproduce

```markdown
1. Start the launcher 
2. Try to play one of the game versions
3. Code 1
```

### Expected Behavior

I wanted to play minecraft java

### Platform

```markdown
- Samsung galaxy A21s
- Android 11
```

**Comment by slimiii** [comment]
![Screenshot_20210727-125636_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88033502/127142842-a312d3e1-4c66-4a10-a4a7-95ef38cd4452.jpg)

**Comment by khanhduytran0** [comment]
Your Minecraft version directory is just damaged or cleaned by some sort of "device boosters"

**Comment by slimiii** [comment]
How I can fix that?

**Comment by slimiii** [comment]
Oh close is end im New sorry

**Comment by Pgabrielmnecraft** [comment]
> Como posso consertar isso?

remove it from the device

**Comment by slimiii** [comment]
> > Como posso consertar isso?
> 
> vom Gerät entfernen

I did so...
Dont work at my Problem

**Comment by slimiii** [comment]
Wow this Translation is so bad

**Comment by YuMore233** [comment]
Me, too. But mine log different .....

I/jrelog  ( 9364): dlopen /data/app/net.kdt.pojavlaunch-clgfdU3aSY33SE3JVw5czw==/lib/arm64/libgl4es_114.so success
I/jrelog  ( 9364): Done processing args
I/jrelog  ( 9364): Found JLI lib
I/jrelog  ( 9364): Calling JLI_Launch
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0

	at java.lang.ClassLoader.defineClass1(Native Method)

	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)

	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
Java Exit code: 1
I/jrelog  ( 9364): Going to free args
I/jrelog  ( 9364): Free done
--------- beginning of system

**Comment by Mathias-Boulay** [comment]
You have to remove the "file cleaner" on your device
Not an issue from pojav
