### ISSUE TITLE
Needed launch JVM

### ISSUE THREAD

**Issue by ZhakiThePro** [PojavLauncherTeam/PojavLauncher#1742]
### Describe the bug

Why no Launch JVM?

### The log file and images/videos

![Screenshot_20210728_214414](https://user-images.githubusercontent.com/78971591/127334130-ee0959a2-2bc6-4b4d-8a60-7ab53e7ee19f.jpg)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.i forgot
```

### Expected Behavior

Crashing while starting

### Platform

```markdown
- Device model: Vivo 1915
- CPU architecture: 64 BITS,maybe
- Android version: 11
- PojavLauncher version: 3.3.1.1-1084-a916a528-vgpu
```

### Anything else?

If you have Launched JVM for Beta, can I request it or not? pls

**Comment by ZhakiThePro** [comment]
By Indonesian (lover minecraft launcher)

**Comment by WesleyVanNeck** [comment]
dont use this experimental build

**Comment by khanhduytran0** [comment]
> Why no Launch JVM?

It's graphics renderer, not java "renderer".

**Comment by ZhakiThePro** [comment]
Ohh now i know 😅

**Comment by ZhakiThePro** [comment]
How to use?

**Comment by khanhduytran0** [comment]
There's no JVM arguments required, you can just plug and play ~~bruh~~

**Comment by ZhakiThePro** [comment]
Oooooooooooooo now i know again 😅😅😅

**Comment by CriticalRange** [comment]
Real bruh moment

**Comment by Pukhrajwdg** [comment]
java.lang.RuntimeException: excessive total memory usage, total usage 1605 MB
	at com.vivo.vspa.AppThreadCmd$2.run(AppThreadCmd.java:84)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:239)
	at android.app.ActivityThread.main(ActivityThread.java:8149)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015) my pojavlauncher crash report and I play 1or 2 minutes and automatically back to home screen or pojavlauncher home screen device specs name v20a59   rom 64 ram 3 arch 64 proceser Snapdragon
