### ISSUE TITLE
[BUG] <Short description> game exited mod colormatic with fabric

### ISSUE THREAD

**Issue by Bertdurant** [PojavLauncherTeam/PojavLauncher#1746]
### Describe the bug

game exited mod colormatic with fabric, here error log
[08:06:22] [main/FATAL]: Mixin apply failed colormatic.mixins.json:dye.TextureManagerMixin -> net.minecraft.class_1060: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on onReload could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap colormatic-refmap.json Method is @Dynamic(Post reload lambda method). [PREINJECT Applicator Phase -> colormatic.mixins.json:dye.TextureManagerMixin -> Prepare Injections ->  -> handler$zgf000$onReload(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onReload could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap colormatic-refmap.json Method is @Dynamic(Post reload lambda method). [PREINJECT Applicator Phase -> colormatic.mixins.json:dye.TextureManagerMixin -> Prepare Injections ->  -> handler$zgf000$onReload(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2
]
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0-internal]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.9.2+mixin.0.8.2.
jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.11.3.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) [fabric-loader-0.11.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0-internal]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0-internal]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) [?:1.8.0-internal]
	at java.lang.Class.getDeclaredFields(Class.java:1916) [?:1.8.0-internal]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) [Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:530) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:425) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) [intermediary-fabric-loader-0.11.3-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.j
ar:?]
Exception in thread "main" 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)

	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)

	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

Caused by: java.lang.reflect.InvocationTargetException

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)

	... 2 more

Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)

	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)

	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)

	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)

	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

	at java.lang.Class.getDeclaredFields0(Native Method)

	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)

	at java.lang.Class.getDeclaredFields(Class.java:1916)

	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)

	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:530)

	at net.minecraft.class_128.method_559(class_128.java:101)

	at net.minecraft.class_128.<init>(class_128.java:54)

	at net.minecraft.class_128.method_24305(class_128.java:425)

	at net.minecraft.client.main.Main.main(Main.java:135)

	... 7 more

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [colormatic.mixins.json:dye.TextureManagerMixin] from phase [DEFAULT] in config [colormatic.mixins.json] FAILED during APPLY

	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onReload could not find any targets matching 'method_18167' in net.minecraft.class_1060. Using refmap colormatic-refmap.json Method is @Dynamic(Post reload lambda method). [PREINJECT Applicator Phase -> colormatic.mixins.json:dye.TextureManagerMixin -> Prepare Injections ->  -> handler$zgf000$onReload(Lnet/minecraft/class_3300;Ljava/util/concurrent/Executor;Ljava/lang/Void;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]

	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)

	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at sun.reflect.GeneratedConstructorAccessor16.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)

	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)

	... 22 more
Java Exit code: 1

### Steps To Reproduce

```markdown
1.
```

### Expected Behavior

I expect the game to launches

### Platform

```markdown
- Device model: samsung j8
- CPU architecture: 64
- Android version: 10
- PojavLauncher version: Play store
```

**Comment by khanhduytran0** [comment]
@Bertdurant please send latestlog.txt

**Comment by Bertdurant** [comment]
Latest log above, Devs pls fix bug

**Comment by khanhduytran0** [comment]
It was trucanted

**Comment by Mathias-Boulay** [comment]
All "mod not working" will be fused into a pinned post.
Closing
