### ISSUE TITLE
[BUG] server unknown host?

### ISSUE THREAD

**Issue by Collierson** [PojavLauncherTeam/PojavLauncher#1747]
### Describe the bug

The existing server can be accessed on the computer but cannot be accessed on the mobile phone.
Why?
(I don’t know English so the above are all google translations.)

### The log file and images/videos

![Screenshot_2021-07-29-19-14-11-07_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/71831461/127482931-4ac135cc-216e-4f41-8656-8d6212b48851.jpg)
![Screenshot_2021-07-29-19-14-13-68_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/71831461/127482946-874ab0fb-3dbf-4b90-bde0-d6dedb86321a.jpg)

### Steps To Reproduce

```markdown
Enter a multiplayer game
Enter IP
See Can't connect to server (pictured)
```

### Expected Behavior

Hope this is a solvable problem.

### Platform

```markdown
- Device model: realme XT  8/128G
- CPU architecture: Qualcomm SDM712 8core
- Android version: 10
- PojavLauncher version: v3.3.1.1-1077-ef2060a8-v3_openjdk
```

**Comment by CJFC01** [comment]
what is the server?

**Comment by khanhduytran0** [comment]
*latestlog.txt moment*

**Comment by cmy2008** [comment]
me too

**Comment by cmy2008** [comment]
> *latestlog.txt moment*

[13:33:33] [main/INFO]: Connecting to maxkim.vip, 25565
[13:33:33] [Server Connector #1/ERROR]: Couldn't connect to server
java.net.UnknownHostException: maxkim.vip
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0-internal]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[?:1.8.0-internal]
	at net.minecraft.class_412$1.run(class_412.java:65) [intermediary-fabric-loader-0.11.6-1.15.2.jar:?]
[13:33:46] [main/INFO]: Connecting to mc.sz.yijiong.vip, 25565
[13:33:50] [main/INFO]: Connecting to maxkim.vip, 25565
[13:33:51] [Server Connector #3/ERROR]: Couldn't connect to server
java.net.UnknownHostException: maxkim.vip: No address associated with hostname
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0-internal]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0-internal]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[?:1.8.0-internal]
	at net.minecraft.class_412$1.run(class_412.java:65) [intermediary-fabric-loader-0.11.6-1.15.2.jar:?]
[13:34:01] [main/INFO]: Connecting to maxkim.vip, 25565
[13:34:01] [Server Connector #4/ERROR]: Couldn't connect to server
java.net.UnknownHostException: maxkim.vip: No address associated with hostname
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0-internal]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1277) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0-internal]
	at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0-internal]
	at java.net.InetAddress.getByName(InetAddress.java:1077) ~[?:1.8.0-internal]
	at net.minecraft.class_412$1.run(class_412.java:65) [intermediary-fabric-loader-0.11.6-1.15.2.jar:?]

**Comment by cmy2008** [comment]
好像电脑端的解析出的地址和手机上不一样，看电脑端日志可以找到源地址，再用这个地址到手机上添加服务器就行了

**Comment by Collierson** [comment]
> 好像电脑端的解析出的地址和手机上不一样，看电脑端日志可以找到源地址，再用这个地址到手机上添加服务器就行了

你怎麼知道我說中文？？好的謝謝

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
