### ISSUE TITLE
Worked for the first time, now doesn't even launch

### ISSUE THREAD

**Issue by UDPSendToFailed** [PojavLauncherTeam/PojavLauncher#18]
Hi!

First I want to say thanks for this launcher, works much better than others.

I've downloaded Minecraft 1.9 just for testing, it ran surprisingly well, 10-20FPS on multiplayer servers, with other launcher I got <5FPS. 

Then I wanted to install Optifine, but it didn't do anything for a long time, just stood at converting screen, step 2/5. So I force closed the app, deleted the optifine folder, tried again with another versions, still no luck. Various errors, null pointer exceptions, 1.7.10 can't be found (why would I need 1.7.10 for 1.9 Optifine?) etc, so Optifine can't be installed for 1.9.

So I tried to launch 1.9 again without Optifine, but it crashes. Same with other versions, I've tried 1.7.10 and 1.8, both crashing with this error:

```
java.lang.ClassCastException: java.lang.String cannot be cast to android.graphics.Rect
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.onPostExecute(MCLauncherActivity.java:750)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.onPostExecute(Unknown Source:6)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```

Any ideas on what the problem could be? Also any working Optifine versions? Thanks a lot for help!

I have a Samsung Galaxy Tab A (2018) with Snapdragon 450 (8x Cortex A53 1.8GHz, Adreno 506) and 3GB RAM, Android 9.

**Comment by khanhduytran0** [comment]
Disable freeform option.

**Comment by khanhduytran0** [comment]
Did you get the latest preview7b1?
Freeform Mode didn't work, you can try to disable and try again.
![Screenshot_2020-03-29-16-49-21](https://user-images.githubusercontent.com/40482367/77846021-50786500-71dd-11ea-8705-c9bc4bd5afa7.png)

**Comment by UDPSendToFailed** [comment]
Thanks, disabling Freeform mode did the trick! I didn't know what is that option, just turned it on to test if it affects something about Optifine installations or not.

Yea, I have downloaded the latest preview version from releases.

I keep getting the same errors for 1.8.9 OF too:
```

java.lang.NullPointerException: Attempt to get length of null array
	at net.kdt.pojavlaunch.patcher.OptiFinePatcher.saveInstaller(OptiFinePatcher.java:46)
	at net.kdt.pojavlaunch.Tools.patchOptifineInstaller(Tools.java:311)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:991)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:6)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

```
java.lang.RuntimeException: Unable to copy optifine_patch/OptiFineClassTransformer.class.patch to /storage/emulated/150/games/minecraft/optifine/optifine_patch/OptiFineClassTransformer.class.patch
	at net.kdt.pojavlaunch.Tools.copyAssetFile(Tools.java:119)
	at net.kdt.pojavlaunch.Tools.copyAssetFile(Tools.java:105)
	at net.kdt.pojavlaunch.Tools.extractAssetFolder(Tools.java:133)
	at net.kdt.pojavlaunch.Tools.extractAssetFolder(Tools.java:140)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:989)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:6)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
	at java.io.File.createNewFile(File.java:1008)
	at net.kdt.pojavlaunch.Tools.copyAssetFile(Tools.java:115)
	... 11 more

```
`
Unable to copy optifine_patch/AndroidInstaller.class.patch to /storage/emulated/150/games/minecraft/optifine/optifine_patch/AndroidInstaller.class.patch`

**Comment by UDPSendToFailed** [comment]
BTW, 1.8.9 is playable without Optifine too, 20+ FPS almost everywhere, sometimes it reaches even 40+

![kép](https://user-images.githubusercontent.com/16057404/77846329-a89b7100-71b5-11ea-871f-3dd496d03595.png)

**Comment by emelin2004** [comment]
> BTW, 1.8.9 is playable without Optifine too, 20+ FPS almost everywhere, sometimes it reaches even 40+
> 
> ![kép](https://user-images.githubusercontent.com/16057404/77846329-a89b7100-71b5-11ea-871f-3dd496d03595.png)
> 

Same here,1.9 runs quite nice,30fps at the most time,sometimes up to 50-60.

**Comment by artdeell** [comment]
Hm, for me 1.9 runs at 60 fps when standing, but when I start walking or sprinting, it lags too much.
I have a pretty high-spec phone (Snapdragon 821 2.3Ghz, Adreno 530)

**Comment by khanhduytran0** [comment]
Try v3
