### ISSUE TITLE
Corrupted OpenJDK upon install

### ISSUE THREAD

**Issue by 121291** [PojavLauncherTeam/PojavLauncher#183]
I installed:

LabyMod 1.8.9
1.8.9
1.11.2

and then upon startup, I get an error 127.

**Comment by 121291** [comment]
Pojav Version: v3.0.1_preview_2

**Comment by khanhduytran0** [comment]
I don't fix since you spam

**Comment by khanhduytran0** [comment]
@121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291 @121291

**Comment by khanhduytran0** [comment]
# This is 7 ***lol*** issue.
# ***@121291 @121291 @121291 @121291 @121291 @121291 @121291***

**Comment by khanhduytran0** [comment]
Dudekid @121291 @121291 @121291 @121291 @121291 @121291 @121291 Dudekid @121291 @121291 @121291 @121291 @121291 @121291 @121291 Dudekid @121291 @121291 @121291 @121291 @121291 @121291 @121291 Dudekid @121291 @121291 @121291 Dudekid @121291 @121291 @121291 @121291 @121291 @121291 @121291  @121291 @121291 @121291 @121291

**Comment by WesleyVanNeck** [comment]
well @khanhduytran0 i have smae issue so yeah 😢

**Comment by khanhduytran0** [comment]
> well @khanhduytran0 i have smae issue so yeah 😢 

Fixed but not sure if it work.

**Comment by GDPL115** [comment]
I have the same problema :
java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/controlmap/default.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at net.kdt.pojavlaunch.Tools.getByteArray(Tools.java:518)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:538)
	at net.kdt.pojavlaunch.value.customcontrols.ControlsLayout.loadLayout(ControlsLayout.java:63)
	at android.androidVNC.VncCanvasActivity.onCreate(VncCanvasActivity.java:136)
	at android.app.Activity.performCreate(Activity.java:7224)
	at android.app.Activity.performCreate(Activity.java:7213)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
![Screenshot_2020-05-13-18-28-08-761_net kdt pojavlaunch](https://user-images.githubusercontent.com/65316715/81876394-29d17c00-9548-11ea-84ef-2050bc467c89.jpg)

**Comment by khanhduytran0** [comment]
> I have the same problema :
> java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/controlmap/default.json (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:231)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:165)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:112)
> 	at net.kdt.pojavlaunch.Tools.getByteArray(Tools.java:518)
> 	at net.kdt.pojavlaunch.Tools.read(Tools.java:538)
> 	at net.kdt.pojavlaunch.value.customcontrols.ControlsLayout.loadLayout(ControlsLayout.java:63)
> 	at android.androidVNC.VncCanvasActivity.onCreate(VncCanvasActivity.java:136)
> 	at android.app.Activity.performCreate(Activity.java:7224)
> 	at android.app.Activity.performCreate(Activity.java:7213)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:201)
> 	at android.app.ActivityThread.main(ActivityThread.java:6810)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> ![Screenshot_2020-05-13-18-28-08-761_net kdt pojavlaunch](https://user-images.githubusercontent.com/65316715/81876394-29d17c00-9548-11ea-84ef-2050bc467c89.jpg)
> 

That only same error code but may different error message.

**Comment by khanhduytran0** [comment]
Use v3.2
