### ISSUE TITLE
[BUG] Undefined renderer: opengles 3

### ISSUE THREAD

**Issue by PTALTS-LK** [PojavLauncherTeam/PojavLauncher#1831]
### Describe the bug

When I try to start the game, I get this error

### The log file and images/videos

java.lang.RuntimeException: Undefined renderer: opengles3
	at net.kdt.pojavlaunch.utils.JREUtils.launchJavaVM(JREUtils.java:283)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:132)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:748)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1200(BaseMainActivity.java:31)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:560)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:784)
![Screenshot_20210812_113338_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/62936489/129134658-239f4c8c-6887-4ebf-a5e6-d85974f2ce7b.jpg)
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6972658/latestlog.txt)

### Steps To Reproduce

```markdown
1.start pojav
2.start game
```

### Expected Behavior

Start the game normally

### Platform

```markdown
- Device model: honor play 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version: v3.3.1.1-1168-27cee857a-clean_vgpu
```

### Anything else?

No matter which renderer I choose, this error will still appear

**Comment by WITHERPROWER** [comment]
Use gpengl es 2 1.1.4 or 1.1.5

**Comment by PTALTS-LK** [comment]
> 使用 gpengl es 2 1.1.4 或 1.1.5

No matter which renderer I choose, this error will still appear

**Comment by WITHERPROWER** [comment]
Ok so these renderer choose if you want in v3_openjdk
1:gl4es 1.1.4 OpenGL ES 2 export OpenGL 2.1
2:gl4es 1.1.5 OpenGL ES 2 export OpenGL 2.1
3:zink (Vulkan) export OpenGL 4.6
4:vgpu 3.0 export OpenGL 4.4

**Comment by WesleyVanNeck** [comment]
do not use vgpu
