### ISSUE TITLE
LWJGL3 not installed

### ISSUE THREAD

**Issue by pickaxe828** [PojavLauncherTeam/PojavLauncher#1858]
```java
java.lang.RuntimeException: LWJGL3 was not installed!
	at net.kdt.pojavlaunch.BaseMainActivity.checkLWJGL3Installed(BaseMainActivity.java:949)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:898)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Geruays** [comment]
``````

**Comment by NotAHero04** [comment]
Could you try reinstalling the launcher? It’ll automatically reinstall all the libraries needed.

**Comment by Mathias-Boulay** [comment]
Un-install an re-install
