### ISSUE TITLE
[BUG] Custom controls error

### ISSUE THREAD

**Issue by Zeyrox1090** [PojavLauncherTeam/PojavLauncher#1870]
### Describe the bug

When pressing load or select default control json
An error shows up

### The log file and images/videos

![Screenshot_2021-08-20-20-33-12-39_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/73925046/130233730-7dcc1de5-2766-4deb-ad76-feb2ec634c6f.jpg)

Log:

java.lang.NullPointerException: Attempt to get length of null array
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:114)
	at com.kdt.pickafile.FileListView.init(FileListView.java:93)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:52)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:46)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:36)
	at net.kdt.pojavlaunch.CustomControlsActivity.load(CustomControlsActivity.java:215)
	at net.kdt.pojavlaunch.CustomControlsActivity$1.onNavigationItemSelected(CustomControlsActivity.java:60)
	at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:217)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
	at android.view.View.performClick(View.java:7254)
	at android.view.View.performClickInternal(View.java:7212)
	at android.view.View.access$3800(View.java:828)
	at android.view.View$PerformClick.run(View.java:27888)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7822)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

### Steps To Reproduce

```markdown
1 download latest actions
2 run pojav
3 go to custom controls
4 swipe from right to left
5 tap load or select default controls json
```

### Expected Behavior

I expect to not get an error lol

### Platform

```markdown
- Device model: RMX 2020
- CPU architecture: aarch 64
- Android version: 10
- PojavLauncher version: latesy actions
```

**Comment by Zeyrox1090** [comment]
Also why is pojav on root folder its still not fixed 😂 i downloaded the fix actions 5 mins ago

**Comment by khanhduytran0** [comment]
> Also why is pojav on root folder its still not fixed 😂 i downloaded the fix actions 5 mins ago

~~but the fix was 2 hours ago~~ :trollface:

**Comment by Zeyrox1090** [comment]
I mean i downloaded the fix 5 mins ago :trollface:

**Comment by Zeyrox1090** [comment]
And its still not fixed in fix 2

**Comment by artdeell** [comment]
The fix was made for Android 9 and lower, android 10 or higher still require to have their storage in a hidden folder

**Comment by Zeyrox1090** [comment]
Hmmm ok

**Comment by Zeyrox1090** [comment]
Then why isn't pojav app using the games/pojavlauncher/.Minecraft
Instead it uses the root derictory

**Comment by Zeyrox1090** [comment]
The data/user something

**Comment by artdeell** [comment]
Because we want to continue updating Pojav, and Android enforced the new storage system

**Comment by Zeyrox1090** [comment]
Then how to import custom controls :trollface:

**Comment by Zeyrox1090** [comment]
Hehe boi
