### ISSUE TITLE
[BUG] can't login with Microsoft 

### ISSUE THREAD

**Issue by greatwitedragon** [PojavLauncherTeam/PojavLauncher#1883]
### Describe the bug

I can't login 

### The log file and images/videos

java.lang.RuntimeException: Can't login a demo account!

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:312)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:208)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
Start pojovlauncher

Click Microsoft account 

Click continue
```

### Expected Behavior

I expect it to login via my Microsoft account 

### Platform

```markdown
- Device model: samsung s21
- CPU architecture: Exynos 2100
- Android version: 11
- PojavLauncher version: 3.3.1.1
```

**Comment by WesleyVanNeck** [comment]
Can't look gin with a demo account
