### ISSUE TITLE
1.17 not working with asset v0 file

### ISSUE THREAD

**Issue by ajit850** [PojavLauncherTeam/PojavLauncher#1897]
### Describe the bug

Application exited with code-1 

### Steps To Reproduce

```markdown
1.
```

### Expected Behavior

I want to play 1.17

### Platform

```markdown
- Device model: Samsung galaxy m31
- CPU architecture: 64 bits
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210321v3_openjdk
```

### Anything else?

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 8/25/21, 9:22 AM
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at enb.b(SourceFile:496)
	at enb.a(SourceFile:384)
	at adu.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)
	at dpr.e(SourceFile:310)
	at dvp.f(SourceFile:1137)
	at dvp.e(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:217)
Caused by: wz: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : 0:7: S0054: Overloading built-in function 'clamp' not allowed
	at wz.a(SourceFile:48)
	at ent.<init>(SourceFile:197)
	at enb.b(SourceFile:452)
	... 118 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : 0:7: S0054: Overloading built-in function 'clamp' not allowed
	at dqa.b(SourceFile:72)
	at dqa.a(SourceFile:54)
	at ent.a(SourceFile:237)
	at ent.<init>(SourceFile:179)
	... 119 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at enb.b(SourceFile:496)
	at enb.a(SourceFile:384)
	at adu.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)

-- Overlay render details --
Details:
	Overlay name: eae
Stacktrace:
	at enb.a(SourceFile:866)
	at dvp.f(SourceFile:1112)
	at dvp.e(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:217)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1144044032 bytes (1091 MiB) / 2097152000 bytes (2000 MiB) up to 2097152000 bytes (2000 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd09 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5346.54
	Virtual memory used (MB): 6628.71
	Swap memory total (MB): 2560.00
	Swap memory used (MB): 1750.07
	JVM Flags: 2 total; -Xms1999M -Xmx1999M
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 2340x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x

**Comment by artdeell** [comment]
Your own log says that the asset pack isn't applied

**Comment by ajit850** [comment]
How to apply asset pack

**Comment by ajit850** [comment]
tutorialStep:none
key_key.pickItem:key.mouse.middle
chatDelay:0.0
chatLinksPrompt:true
key_key.playerlist:key.keyboard.tab
textBackgroundOpacity:0.5
useNativeTransport:true
chatScale:1.0
enableVsync:false
modelPart_cape:true
particles:1
toggleSprint:false
mouseSensitivity:0.5070422535211268
key_key.advancements:key.keyboard.l
advancedItemTooltips:true
key_key.swapOffhand:key.keyboard.f
modelPart_hat:true
entityShadows:true
touchscreen:false
incompatibleResourcePacks:[]
version:2724
ao:0
mipmapLevels:0
hideMatchedNames:true
key_key.hotbar.5:key.keyboard.5
key_key.hotbar.6:key.keyboard.6
key_key.hotbar.7:key.keyboard.7
key_key.hotbar.8:key.keyboard.8
fullscreen:false
renderDistance:12
key_key.hotbar.1:key.keyboard.1
key_key.hotbar.2:key.keyboard.2
key_key.hotbar.3:key.keyboard.3
discrete_mouse_scroll:false
key_key.hotbar.4:key.keyboard.4
modelPart_left_sleeve:true
soundCategory_record:1.0
key_key.sprint:key.keyboard.left.control
key_key.forward:key.keyboard.w
skipMultiplayerWarning:true
key_key.drop:key.keyboard.q
key_key.back:key.keyboard.s
soundCategory_music:0.0
toggleCrouch:false
key_key.attack:key.mouse.left
soundCategory_master:1.0
key_key.use:key.mouse.right
chatWidth:1.0
key_key.saveToolbarActivator:key.keyboard.unknown
chatHeightUnfocused:0.44366196
realmsNotifications:true
showSubtitles:true
key_key.smoothCamera:key.keyboard.unknown
backgroundForChatOnly:true
chatHeightFocused:1.0
hideServerAddress:false
glDebugVerbosity:1
modelPart_right_pants_leg:true
maxFps:260
renderClouds:false
guiScale:3
forceUnicodeFont:false
hideBundleTutorial:false
biomeBlendRadius:2
entityDistanceScaling:0.5
chatOpacity:1.0
gamma:1.0
key_key.right:key.keyboard.d
key_key.jump:key.keyboard.space
resourcePacks:["vanilla"/file"assets-v0.zip"]
modelPart_left_pants_leg:true
chatLineSpacing:0.0
chatColors:true
soundCategory_weather:0.9975853
mouseWheelSensitivity:1.0
key_key.sneak:key.keyboard.left.shift
modelPart_jacket:true
heldItemTooltips:true
key_key.spectatorOutlines:key.keyboard.unknown
screenEffectScale:1.0
autoSuggestions:true
soundCategory_player:1.0
key_key.left:key.keyboard.a
graphicsMode:0
difficulty:2
mainHand:right
lastServer:MiniGames.Rede
overrideHeight:1080
darkMojangStudiosBackground:false
autoJump:true
chatLinks:true
soundCategory_block:1.0
invertYMouse:false
reducedDebugInfo:false
modelPart_right_sleeve:true
key_key.command:key.keyboard.slash
key_key.screenshot:key.keyboard.f2
fov:0.0
key_key.hotbar.9:key.keyboard.9
soundCategory_neutral:1.0
rawMouseInput:true
attackIndicator:1
snooperEnabled:false
key_key.togglePerspective:key.keyboard.f5
soundCategory_ambient:1.0
pauseOnLostFocus:true
lang:en_us
key_key.chat:key.keyboard.t
bobView: true
soundCategory_hostile:1.0
fovEffectScale:1.0
overrideWidth:2340
syncChunkWrites:false
key_key.inventory:key.keyboard.e
key_key.fullscreen:key.keyboard.f11
key_key.loadToolbarActivator:key.keyboard.x
chatVisibility:0
narrator:0
joinedFirstServer:true
fullscreenResolution:1778x820@60:24
soundCategory_voice:1.0
key_key.socialInteractions:key.keyboard.p

**Comment by khanhduytran0** [comment]
I saw your attempt to run Minecraft on Java <ins>Development Kit</ins> instead of Java <ins>**Runtime** Environment</ins>. Minecraft has never been used to compile Java code.

> resourcePacks:["vanilla"/file"assets-v0.zip"]

Ah yes minecraft didn’t understand that.

**Comment by ajit850** [comment]
What I do to run 1.17.1

**Comment by khanhduytran0** [comment]
valid:
> resourcePacks:["vanilla","file/assets-v0.zip"]

Also, there’s no “assets-v3” as the title.
