### ISSUE TITLE
[F-Req] i cant login with Microsoft account

### ISSUE THREAD

**Issue by harispoppylatip** [PojavLauncherTeam/PojavLauncher#1911]
### Is this request related to a bug?

java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:292)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### Describe the request.

-

### Anything else?

No

**Comment by Zidan68568** [comment]
Pleaseee

**Comment by mchnjt** [comment]
what

**Comment by Ahmadutma** [comment]
java.lang.RuntimeException:   MSA Error: 401: Unauthorized, error stream: {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"} 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293) 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169) 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122) 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75) 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22) 	at android.os.AsyncTask$3.call(AsyncTask.java:394) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:923)

**Comment by GaucovyAero** [comment]
AddChildToFamily, create a microsoft family and add you (child) into it

**Comment by sumitdafda300** [comment]
![Screenshot_20230408-024921](https://user-images.githubusercontent.com/130185382/230682141-65c9eb0b-5de0-4b6c-b083-31996ca00205.png)

**Comment by sumitdafda300** [comment]
Sunn m s r e d jha se baat kar

**Comment by VenomousSteam81** [comment]
> ![Screenshot_20230408-024921](https://user-images.githubusercontent.com/130185382/230682141-65c9eb0b-5de0-4b6c-b083-31996ca00205.png)

Ok what the hell is this @sumitdafda300
