### ISSUE TITLE
[BUG] Appears when played with keyboard and mouse.

### ISSUE THREAD

**Issue by PadMadoff** [PojavLauncherTeam/PojavLauncher#1975]
### Describe the bug

java.lang.RuntimeException: InputChannel is not initialized.
	at android.view.InputEventSender.nativeInit(Native Method)
	at android.view.InputEventSender.<init>(InputEventSender.java:66)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.<init>(InputMethodManager.java:3152)
	at android.view.inputmethod.InputMethodManager.sendInputEventOnMainLooperLocked(InputMethodManager.java:2671)
	at android.view.inputmethod.InputMethodManager.dispatchInputEvent(InputMethodManager.java:2603)
	at android.view.ImeFocusController.onProcessImeInputStage(ImeFocusController.java:237)
	at android.view.ViewRootImpl$ImeInputStage.onProcess(ViewRootImpl.java:5659)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8099)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8050)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8011)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8222)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8179)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8261)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:724)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7667)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### The log file and images/videos

[That's bug video](https://youtu.be/ghOPY_UOjWg) 

### Steps To Reproduce

```markdown
1. Starting Pojav.
2. Enter in local world.
3. Waiting 10 and more minutes.
4. Done
```

### Expected Behavior

I expected a normal survival gameplay.

### Platform

```markdown
- Device model: POCO X3 NFC
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Latest Release (Beta)
- Custom ROM: Havoc OS
```

**Comment by Mathias-Boulay** [comment]
State the fucking version or I'll hunt you down

**Comment by PadMadoff** [comment]
> State the fucking version or I'll hunt you down

1.16.5

**Comment by Mathias-Boulay** [comment]
FOR FUCK'S SAKE THE LAUNCHER VERSION
I hAvE LaTeSt isn't a version.

Also, chances are you need to change your custom rom, at no point in the stacktrace our code can be found.

**Comment by PadMadoff** [comment]
> FOR FUCK'S SAKE THE LAUNCHER VERSION
> I hAvE LaTeSt isn't a version.
> 
> Also, chances are you need to change your custom rom, at no point in the stacktrace our code can be found.

crocus-14-bacb4070b-v3_openjdk
Why u so toxic

**Comment by PadMadoff** [comment]
> FOR FUCK'S SAKE THE LAUNCHER VERSION
> I hAvE LaTeSt isn't a version.
> 
> Also, chances are you need to change your custom rom, at no point in the stacktrace our code can be found.

Custom rom does not affect the operation of applications in any way. I have root rights in case this program needs them.

**Comment by Mathias-Boulay** [comment]
> Why u so toxic

Because of your inability to provide the launcher version when asked.

> Custom rom does not affect the operation of applications in any way

And yet, there is only android's code in the stacktrace.
Do you have any apps that fails with prolonged mouse and keyboard use ?
Better yet, have you tried reproducing the bug with only the keyboard/the mouse /noone of those two devices ?

Bear in mind I'm only asking ultra basic stuff here

**Comment by PadMadoff** [comment]
> > Why u so toxic
> 
> Because of your inability to provide the launcher version when asked.

YOU DIDN'T told about which version and what we are talking about.
> 
> > Custom rom does not affect the operation of applications in any way
> 
> And yet, there is only android's code in the stacktrace.
> Do you have any apps that fails with prolonged mouse and keyboard use ?
> Better yet, have you tried reproducing the bug with only the keyboard/the mouse /noone of those two devices ?
> 
> Bear in mind I'm only asking ultra basic stuff here

MCPE Work Perfect

**Comment by Mathias-Boulay** [comment]
😂 ~~okay let's ignore the fact the version is asked by the form you improperly filled~~

That's half the question answered though.
