### ISSUE TITLE
[BUG] Restarting pojavlauncher may reset control map

### ISSUE THREAD

**Issue by fengyec2** [PojavLauncherTeam/PojavLauncher#1977]
### Describe the bug

I spent lot of time editing control map,but I found restarting pojavlauncher may reset control map !

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Edit control map
3.Restart pojavlauncher or make a crash
4.Try step 3 multiple times
5.The control map reset by itself !!!
```

### Expected Behavior

I expect the control map won't be reset

### Platform

```markdown
- Device model: HUAWEI_MatePad 10.4  6/128G
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest Release
```

### Anything else?

Nope

**Comment by khanhduytran0** [comment]
Why did you save to "default"?

**Comment by fengyec2** [comment]
because When I change the default control map setting, it shows 

java.lang.NullPointerException: Attempt to get length of null array
at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:114)
at com.kdt.pickafile.FileListView.init(FileListView.java:93)
at com.kdt.pickafile.FileListView.<init>(FileListView.java:52)
at com.kdt.pickafile.FileListView.<init>(FileListView.java:46)
at com.kdt.pickafile.FileListView.<init>(FileListView.java:36)
at net.kdt.pojavlaunch.CustomControlsActivity.dialogSelectDefaultCtrl(CustomControlsActivity.java:116)
at net.kdt.pojavlaunch.CustomControlsActivity$1.onNavigationItemSelected(CustomControlsActivity.java:69)
at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:217)
at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
at android.view.View.performClick(View.java:7316)
at android.view.View.performClickInternal(View.java:7290)
at android.view.View.access$3600(View.java:838)
at android.view.View$PerformClick.run(View.java:28262)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.app.ActivityThread.main(ActivityThread.java:8668)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

so I saved it to default
