### ISSUE TITLE
[BUG] The game cannot be started after the resource pack is loaded (1.17.1)

### ISSUE THREAD

**Issue by fengyec2** [PojavLauncherTeam/PojavLauncher#2011]
### Describe the bug

When the resource pack is loaded in the game (successfully!) and then the game restarts, the game will not start properly and it will always be on the Mojang page.

### The log file and images/videos

[00:22:23] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:179) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:166) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1137) [intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at net.minecraft.class_757.method_34538(class_757.java:496) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_757.method_14491(class_757.java:384) [intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 122 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : 0:7: S0054: Overloading built-in function 'clamp' not allowed
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:197) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:452) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_757.method_14491(class_757.java:384) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 122 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : 0:7: S0054: Overloading built-in function 'clamp' not allowed
	at net.minecraft.class_281.method_34416(class_281.java:72) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_281.method_1283(class_281.java:54) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:237) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:179) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:452) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_757.method_14491(class_757.java:384) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-1.17.1%E5%AE%9E%E7%94%A8%E5%9F%BA%E7%A1%80%E6%95%B4%E5%90%88.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 122 more
[00:22:23] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), MultiConnect API, GBfabrictools, Fabric Loader, Fabric Transfer API (v1), Fabric Structure API (v1), Fabric Containers (v0), Fabric Dimensions API (v1), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Tweakeroo, Fabric Rendering Fluids (v1), Litematica, Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), MiniHUD, Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric API Lookup API (v1), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Mod Menu, Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric Item API (v1), Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Cloth Config v5, Fabric Resource Loader (v0), MaLiLib, Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), AppleSkin, Fabric Commands (v0), Fabric Registry Sync (v0), Lan Server Properties, Giselbaers Durability Viewer, Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Wurst Client, Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))

https://user-images.githubusercontent.com/85821538/132930044-3bb418e4-cc35-42be-b9c5-3c0a2fc98702.mp4

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Launch the game 1.17.1
3.Load resource pack
4.Restart the game
5.Find it can not start properly and it will always be on the Mojang page
```

### Expected Behavior

I expect the game launches properly with resource pack

### Platform

```markdown
- Device model: HUAWEI_MatePad 10.4   6/128GB
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

No

**Comment by ajit850** [comment]
Please close and reopen issue

**Comment by EnderBrine99FOX** [comment]
remove all the texture pack you have because the texture pack that you have is on top of the main texture pack it's also happened with me

**Comment by rscDMTalt** [comment]
anagsauwgsgsusgsgs

**Comment by rscDMTalt** [comment]
just edit the damn version jar

**Comment by rscDMTalt** [comment]
just edit the damn version jar

**Comment by Yashjbk17** [comment]
Delete the old resource pack and reinstall it than try again.It happened with me also

**Comment by ghost** [comment]
Same problem except it crashes in black screen

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
