### ISSUE TITLE
[BUG] Running Forge 1.12.2 Failed

### ISSUE THREAD

**Issue by Abdulhadi5692HDI** [PojavLauncherTeam/PojavLauncher#2018]
### Describe the bug

Error: no procotol when starting forge 1.12.2

### The log file and images/videos

java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:601)
	at java.net.URL.<init>(URL.java:498)
	at java.net.URL.<init>(URL.java:447)
	at net.kdt.pojavlaunch.Tools.downloadFileMonitored(Tools.java:729)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.downloadLibrary(MinecraftDownloaderTask.java:270)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:151)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
1. Start PoJavLauncher
2. Start Forge 1.12.2 (install it first)
3. Error occuress
```

### Expected Behavior

I expected it to run

### Platform

```markdown
- Device model:  Samsung Galaxy S9
- CPU architecture:  aarch64
- Android version: 10.0
- PojavLauncher version: Play Store release
```

**Comment by ZuVEnO** [comment]
Try re-install or update PojavLauncher.

**Comment by WesleyVanNeck** [comment]
playstore release isnt a version

**Comment by Abdulhadi5692HDI** [comment]
It worked :)
