### ISSUE TITLE
Unexpected error: Application/Game exited with code 1 on 1.12.2 forge

### ISSUE THREAD

**Issue by Abdulhadi5692HDI** [PojavLauncherTeam/PojavLauncher#2034]
**it happened then**  _i removed some mods but same error_ .

**Comment by Abdulhadi5692HDI** [comment]
Log:

```
--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.12.2-forge-14.23.5.2855 (1.12.2)
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2220
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-HsYsj5s4tn1QOodtNfrZtw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
I/LIBGL   (30281): Initialising gl4es
I/LIBGL   (30281): v1.1.4 built on Jul 19 2020 08:20:42
I/LIBGL   (30281): Using GLES 2.0 backend
I/LIBGL   (30281): loaded: libGLESv2.so
I/LIBGL   (30281): loaded: libEGL.so
I/LIBGL   (30281): Using GLES 2.0 backend
I/LIBGL   (30281): Hardware Full NPOT detected and used
I/LIBGL   (30281): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (30281): FBO are in core, and so used
I/LIBGL   (30281): PointSprite are in core, and so used
I/LIBGL   (30281): CubeMap are in core, and so used
I/LIBGL   (30281): BlendColor is in core, and so used
I/LIBGL   (30281): Blend Substract is in core, and so used
I/LIBGL   (30281): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (30281): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (30281): Extension GL_OES_mapbuffer  detected
I/LIBGL   (30281): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (30281): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (30281): Extension GL_OES_depth24  detected and used
I/LIBGL   (30281): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (30281): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (30281): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (30281): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (30281): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (30281): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (30281): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (30281): high precision float in fragment shader available and used
I/LIBGL   (30281): Max vertex attrib: 16
I/LIBGL   (30281): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (30281): Max texture size: 8192
I/LIBGL   (30281): Max Varying Vector: 15
I/LIBGL   (30281): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (30281): Max Color Attachments: 1 / Draw buffers: 1
I/LIBGL   (30281): Hardware vendor is ARM
I/LIBGL   (30281): GLSL 300 es supported
I/LIBGL   (30281): GLSL 310 es supported and used
I/LIBGL   (30281): sRGB surface supported
I/LIBGL   (30281): EGLImage to Texture2D supported
I/LIBGL   (30281): EGLImage to RenderBuffer supported
I/LIBGL   (30281): ignore MipMap
I/LIBGL   (30281): Targeting OpenGL 2.1
I/LIBGL   (30281): NPOT texture handled in hardware
I/LIBGL   (30281): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (30281): try to use VBO
I/LIBGL   (30281): glXMakeCurrent FBO workaround enabled
I/LIBGL   (30281): FBO workaround for using binded texture enabled
I/LIBGL   (30281): glX Will try to recycle EGL Surface
I/LIBGL   (30281): Current folder is:/
I/jrelog  (30281): dlopen libgl4es_114.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (30281): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (30281): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  (30281): dlopen /data/app/net.kdt.pojavlaunch-HsYsj5s4tn1QOodtNfrZtw==/lib/arm64/libopenal.so success
I/jrelog  (30281): Done processing args
I/jrelog  (30281): Found JLI lib
I/jrelog  (30281): Calling JLI_Launch
[19:49:56] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:49:56] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:49:56] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:49:56] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[19:49:56] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0-internal, running on Linux:aarch64:Android-10, installed at /data/data/net.kdt.pojavlaunch/runtimes/Internal
[19:49:56] [main/INFO] [FML]: Searching /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods for mods
[19:49:56] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in B3M-1.12.2-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:49:56] [main/WARN] [FML]: The coremod sedridor.B3M.core.B3M_CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:49:56] [main/WARN] [FML]: The coremod B3M_CorePlugin (sedridor.B3M.core.B3M_CorePlugin) is not signed!
[19:49:56] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[19:49:56] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.2.1.jar
[19:49:56] [main/WARN] [FML]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:49:56] [main/WARN] [FML]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[19:49:56] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:49:56] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[19:49:56] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[19:49:56] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0-internal]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0-internal]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0-internal]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Exception in thread "main" 
[19:49:56] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:49:56] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:49:56] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[19:49:56] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[19:49:56] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:973)
[19:49:56] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:49:56] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java Exit code: 1
I/jrelog  (30281): Going to free args
I/jrelog  (30281): Free done
 
```

**Comment by Abdulhadi5692HDI** [comment]
Its the latest log

**Comment by Abdulhadi5692HDI** [comment]
```
**
__
Device Info:
Samsung Galaxy S9
Android 10
CPU arch: aarch64
Pojavlauncher Info:
Version: crocus-v3_openjdk
__
**
```

**Comment by Abdulhadi5692HDI** [comment]
Upgraded to 1.16.5
