### ISSUE TITLE
It doesn't start after resources are loaded

### ISSUE THREAD

**Issue by gitanswer** [PojavLauncherTeam/PojavLauncher#204]
Minecraft does not start although all resources were downloaded after that the gray screen (on versions three white) and all. Also, why does stable release version 2 not support versions higher than 1.12?
Practically full error (clicked "Copy") 
Java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at bhz.<init>(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 5 more
P.S. I'll Add that other boardwalk-based launchers have a similar problem.

**Comment by khanhduytran0** [comment]
> Minecraft does not start although all resources were downloaded after that the gray screen (on versions three white) and all.

Did you checked log output?

> Also, why does stable release version 2 not support versions higher than 1.12?
```
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
 at bhz.(SourceFile:395)
 at net.minecraft.client.main.Main.main(SourceFile:123)
 ... 5 more
```

That's because Android does not fully support Java8. What launcher version and what your Android version?

> P.S. I'll Add that other boardwalk-based launchers have a similar problem.

Can you describe?

**Comment by gitanswer** [comment]
Launcher 2.5.0, MIUI 11 (OS based on Android 10), phone - Xiaomi Mi 9

**Comment by khanhduytran0** [comment]
Use v3 so you could get 1.12 work.
