### ISSUE TITLE
[BUG] Randomly crashed after 5-10 minutes

### ISSUE THREAD

**Issue by PadMadoff** [PojavLauncherTeam/PojavLauncher#2075]
### Describe the bug

When I try to play minecraft, after every 5-10 minutes, the screen freezes on 1 picture. I hear the sounds of what I am doing, but the picture of the game freezes and crashes after a while.I tried to play without keyboard and mouse, the result is the same. Tried to hide root from Pojav, same.

### The log file and images/videos

java.lang.RuntimeException: InputChannel is not initialized.
at android.view.InputEventSender.nativeInit(Native Method)
at android.view.InputEventSender.(InputEventSender.java:66)
at android.view.inputmethod.InputMethodManager$ImeInputEventSender.(InputMethodManager.java:3152)
at android.view.inputmethod.InputMethodManager.sendInputEventOnMainLooperLocked(InputMethodManager.java:2671)
at android.view.inputmethod.InputMethodManager.dispatchInputEvent(InputMethodManager.java:2603)
at android.view.ImeFocusController.onProcessImeInputStage(ImeFocusController.java:237)
at android.view.ViewRootImpl$ImeInputStage.onProcess(ViewRootImpl.java:5659)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8099)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8050)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8011)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8222)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8179)
at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8261)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
at android.view.Choreographer.doCallbacks(Choreographer.java:796)
at android.view.Choreographer.doFrame(Choreographer.java:724)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7667)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Steps To Reproduce

```markdown
1. Starting Pojav (Settings 1960m RAM)
2. Enter in game (1.17.1)
3. Enter in the world.
4. Wait some minutes.
5. Crash.
```

### Expected Behavior

I wanted to be able to play with keyboard and mouse without problems.

### Platform

```markdown
- Device model: POCO X3 NFC
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus-70-103aba6f6-v3_openjdk

And custom rom with root (For improve fps in game).
```

**Comment by Mathias-Boulay** [comment]
Duplicate from another issue

**Comment by Mathias-Boulay** [comment]
Can we get the latestlog.txt as well ?
There may be something of worth there

**Comment by PadMadoff** [comment]
> Duplicate from another issue

Because no one noticed my past problem.

**Comment by Mathias-Boulay** [comment]
And you fucking didn't close the previous one.
Also do that again and you'll be blocked.
I can't reproduce the issue on my x3 with a stock rom.

**Comment by PadMadoff** [comment]
> Can we get the latestlog.txt as well ?
> There may be something of worth there

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/7238685/latestlog.txt)

**Comment by Mathias-Boulay** [comment]
Wait there is something that might be of worth here.
Try to use a version with optifine, but set the auto save time to the biggest number you can (30min I think)

**Comment by PadMadoff** [comment]
> Wait there is something that might be of worth here.
> Try to use a version with optifine, but set the auto save time to the biggest number you can (30min I think)

On 1.17.1, the optfine crashes :/

**Comment by ZIONJADEHD505** [comment]
Did u patch it?

**Comment by PadMadoff** [comment]
> Did u patch it?

What are you talking about

**Comment by ZIONJADEHD505** [comment]
OK nvm

**Comment by Yashjbk17** [comment]
You have to download pojav launcher patcher for 1.17 optifine then only it will work

**Comment by Yashjbk17** [comment]
Because 1.17 optifine can't patch automatically you have to download a patcher

**Comment by Mathias-Boulay** [comment]
I'm weirded out by this device specific issue tbh

**Comment by Mathias-Boulay** [comment]
Weren't able to reproduce it on any device. Assumed to be a custom rom specific issue.
Closing
