### ISSUE TITLE
Error In Starting game!

### ISSUE THREAD

**Issue by HeyBlueMito** [PojavLauncherTeam/PojavLauncher#21]
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:139)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:712)
	at net.kdt.pojavlaunch.MainActivity.access$1000073(MainActivity.java)
	at net.kdt.pojavlaunch.MainActivity$100000013$100000012.run(MainActivity.java:508)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:130)
	... 5 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.Minecraft" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/net/minecraft/launchwrapper/1.5/launchwrapper-1.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/versions/a1.2.1_01/a1.2.1_01.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-2/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 8 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/minecraft/launchwrapper/1.5/launchwrapper-1.5.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:35)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:35)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:35)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:35)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/versions/a1.2.1_01/a1.2.1_01.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:35)
		... 5 more
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.Minecraft" on path: DexPathList[[zip file "/data/app/net.kdt.pojavlaunch-2/base.apk"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-2/lib/arm, /data/app/net.kdt.pojavlaunch-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 9 more
		Suppressed: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
			at java.lang.Class.classForName(Native Method)
			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 10 more
		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by khanhduytran0** [comment]
Not sure if old `a1.2.1_01` version works.

Delete `/storage/emulated/0/games/minecraft/versions/a1.2.1_01` and try again

**Comment by khanhduytran0** [comment]
Reopen if problem happend again.
