### ISSUE TITLE
Game failing

### ISSUE THREAD

**Issue by ashton1200** [PojavLauncherTeam/PojavLauncher#210]
Whenever I play any version I get this java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/controlmap/default.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at net.kdt.pojavlaunch.Tools.getByteArray(Tools.java:518)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:538)
	at net.kdt.pojavlaunch.value.customcontrols.ControlsLayout.loadLayout(ControlsLayout.java:63)
	at android.androidVNC.VncCanvasActivity.onCreate(VncCanvasActivity.java:136)
	at android.app.Activity.performCreate(Activity.java:7149)
	at android.app.Activity.performCreate(Activity.java:7140)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by williambulin** [comment]
I have the exact same issue. Android 10 on a OnePlus 5T.

**Comment by khanhduytran0** [comment]
This is problem at custom control. Just ignore it or create new custom control.

**Comment by khanhduytran0** [comment]
> This is problem at custom control. Just ignore it or create new custom control.

@inkysansy please reply

**Comment by zian04** [comment]
can i play 6.0.1 android btw
