### ISSUE TITLE
[BUG] <Short description> A Error Is coming See It In Screenshort

### ISSUE THREAD

**Issue by TEJASVABG** [PojavLauncherTeam/PojavLauncher#2116]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.BaseMainActivity.initLayout(BaseMainActivity.java:145)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:26)
	at android.app.Activity.performCreate(Activity.java:7272)
	at android.app.Activity.performCreate(Activity.java:7263)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3163)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3318)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

### The log file and images/videos

![Screenshot_20211012_150620](https://user-images.githubusercontent.com/91388013/137130443-e7bc6bb6-0617-4921-91cc-e7c6fab431ed.jpg)

### Steps To Reproduce

```markdown
please Fix It
```

### Expected Behavior

IF A START THE GAME IT HAPPENS

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
- Vivo V9 1723 2GB RAM
```

**Comment by WesleyVanNeck** [comment]
fill the template

**Comment by WesleyVanNeck** [comment]
how about we dont fix it as we arnt paid by you to fix it

**Comment by NotAHero04** [comment]
(oof @LegacyGamerHD you have seemingly enough things)
@TEJASVABG find the PojavLauncher folder and delete per-version-config.json.

**Comment by WesleyVanNeck** [comment]
> (oof @LegacyGamerHD you have seemingly enough things) @TEJASVABG find the PojavLauncher folder and delete per-version-config.json.

Anough things yeah right only the device is filt out rest is not so the template is invalid

**Comment by Mathias-Boulay** [comment]
Hmm, so much infos are missing.
How the fuck do we even fix this then
