### ISSUE TITLE
(BUG) The arm architecture is incompatible with Java Runtime aarch64.

### ISSUE THREAD

**Issue by lertiland** [PojavLauncherTeam/PojavLauncher#2121]
### Describe the bug

java.lang.RuntimeException: The arm architecture is incompatible with Java Runtime aarch64.
at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install the JRE of my architecture (aarch64)
3. Start 1.17.1
```

### Expected Behavior

I expect for the game bug

### Platform

```markdown
- Device model: SM-A015M
- CPU architecture: aarch64
- Android version: Android 11
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by khanhduytran0** [comment]
Basically, you can’t expect 32bit userspace to run 64bit things. JRE17 is not currently available for 32bit.
