### ISSUE TITLE
[BUG] <The new snapshot failed to start>

### ISSUE THREAD

**Issue by tipnsp** [PojavLauncherTeam/PojavLauncher#2127]
### Describe the bug

Since Mojang had changed the new render channel in the latest snapshot and had to modify the file to start the game, ZINK seemed to be able to do it, just displaying errors on my device.

### The log file and images/videos

I can't give you the log file.But I can copy it.
The following is the crash low.
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2021/10/16 上午10:20
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at eoc.b(SourceFile:496)
	at eoc.a(SourceFile:384)
	at aej.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:181)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:168)
	at dqo.e(SourceFile:310)
	at dwn.f(SourceFile:1145)
	at dwn.e(SourceFile:736)
	at net.minecraft.client.main.Main.main(SourceFile:238)
Caused by: xh: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : 0:7: S0054: Overloading built-in function 'clamp' not allowed
	at xh.a(SourceFile:48)
	at eou.<init>(SourceFile:197)
	at eoc.b(SourceFile:452)
	... 118 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : 0:7: S0054: Overloading built-in function 'clamp' not allowed
	at dqx.b(SourceFile:72)
	at dqx.a(SourceFile:54)
	at eou.a(SourceFile:237)
	at eou.<init>(SourceFile:179)
	... 119 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eoc.b(SourceFile:496)
	at eoc.a(SourceFile:384)
	at aej.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aen.a(SourceFile:71)
	at atc.execute(SourceFile:101)
	at aen.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:181)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:168)

-- Overlay render details --
Details:
	Overlay name: ebd
Stacktrace:
	at eoc.a(SourceFile:866)
	at dwn.f(SourceFile:1120)
	at dwn.e(SourceFile:736)
	at net.minecraft.client.main.Main.main(SourceFile:238)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 21w41a
	Minecraft Version ID: 21w41a
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2210355056 bytes (2107 MiB) / 3649044480 bytes (3480 MiB) up to 3649044480 bytes (3480 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 2 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd09 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7948.49
	Virtual memory used (MB): 8624.18
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 1794.82
	JVM Flags: 2 total; -Xms3479M -Xmx3479M
	Launched Version: 21w41a
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 2180x1026
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: English
	CPU: 8x AArch64 Processor rev 2 (aarch64)

### Steps To Reproduce

```markdown
I think I made myself very clear.
```

### Expected Behavior

I was ready to launch 21w41a but the game crashed at the last point of loading, I tried to change the renderer but Zink rendering error

### Platform

```markdown
- Device model: HUAWEI--P50
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest version of actions
```

### Anything else?

No, not really.

**Comment by khanhduytran0** [comment]
from @NotAHero04 in discord:
> Since 21w37a, Mojang bumped the resource pack version to 8, which rendered the current assets-v0 patch unusable. This is the patch for those versions. Simply replace it to the existing assets-v0, and you’re good to go!
A small note: When the popup about 1.17 appears, tap **Play Anyway**. Tapping OK **will overwrite the patch**.
Another small note: 1.17.1 or below will simply not work with this patch. ~~I recommend using per-version config feature with it.~~ If you still want to play 1.17.1 or below, keep the original assets-v0 and check this video: (advertising moment <:pepekek:793775166085005312>) https://youtu.be/1MzpwEk-J9c
STATUS: ✅ Working (as of the snapshot 21w41a)
[assets-v0.zip - 130kb](https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip)

**Comment by aaaapai** [comment]
> 从 @NotAHero04 在不和谐：
> 
> > 自 21w37a 以来，Mojang 将资源包版本提升为 8，这使得当前资产 v0 修补程序无法使用。这是这些版本的补丁。只需将其替换为现有资产-v0，您就可以走了！
> > 一个小注释：当弹出窗口约 1.17 出现时，点击 **无论如何玩**.点击确定 **将覆盖补丁**.
> > 另一个小注释：1.17.1 或以下将根本不适用于此修补程序。 ~我建议使用每个版本的配置功能。~ 如果您仍想播放 1.17.1 或以下游戏，请保留原始资产-v0 并查看此视频：（广告时刻<:p ekek：793775166085005312>） https://youtu.be/1MzpwEk-J9c
> > 地位： ✅ 工作（截至快照 21w41a）
> > [资产-v0.zip - 130kb](https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip)

I can't use VPN, so two links can't be opened

**Comment by khanhduytran0** [comment]
[assets-v0.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7358512/assets-v0.zip)

**Comment by aaaapai** [comment]
> [assets-v0.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/7358512/assets-v0.zip)

thank you

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
