### ISSUE TITLE
Crash when use 1.12 ver (will be fixed in V3)

### ISSUE THREAD

**Issue by truong0235** [PojavLauncherTeam/PojavLauncher#215]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at bhz.<init>(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 5 more

**Comment by khanhduytran0** [comment]
V2 is not support 1.12 and above. V3 is in progress.

**Comment by khanhduytran0** [comment]
Looks like VN? If it's you are welcome to say with that language.

**Comment by khanhduytran0** [comment]
Use v3 instead.
