### ISSUE TITLE
How do I fix this

### ISSUE THREAD

**Issue by leah54** [PojavLauncherTeam/PojavLauncher#2150]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
can you help me

### The log file and images/videos

Help me

### Steps To Reproduce

```markdown
How do I fix this
```

### Expected Behavior

Pls

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Pls

**Comment by WesleyVanNeck** [comment]
Fill template

**Comment by NotAHero04** [comment]
@leah54 can you give us a copy of your `per-version-config.json`? It’s located in the PojavLauncher folder.
After uploading that file here, you can delete it and the launcher should work fine.

**Comment by leah54** [comment]
@NotAHero04  how do I copy it

**Comment by leah54** [comment]
Its fix

**Comment by AdammSy7** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by ChooweKamska999** [comment]
How To Fix This?


java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by Amea12** [comment]
I don't know, that's what I'm trying to figure out.

**Comment by Dharmadas8** [comment]
But i can't Fix pIs Make a Video on Youtube and Tell Channel Name (pIs)

**Comment by Therealrex** [comment]
Idk But It Happened To Me 1 or 2 hours ago here's the code so you can copy and paste: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

**Comment by rapozinha2924** [comment]
Está tendo um problema ao carregar a conta que eu criei

**Comment by Naufalvikriseti** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:922)

**Comment by YANZZZ196** [comment]
Pojav launcher kayak kontol

**Comment by kiokori-git** [comment]
> Pojav launcher kayak kontol

yo lajulah pake mcinabox ato foldcraftlauncher, lebih bagus kan menurut kau? kalo nak nge-hate, dak usah disini

**Comment by YANZZZ196** [comment]
Developer semoga meninggal lu memek kontol gak bisa buat game tolol

**Comment by kiokori-git** [comment]
> Developer semoga meninggal lu memek kontol gak bisa buat game tolol

lu kenapa? orang indonesia gini kah?
ini launcher loh, bukan game
lu marah karna kenapa 💀
