### ISSUE TITLE
Crash when try joining server (will be fixed in V3)

### ISSUE THREAD

**Issue by truong0235** [PojavLauncherTeam/PojavLauncher#216]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 29/05/2020 22:51
Description: Rendering Block Entity

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bxk.a(SourceFile:126)
	at bqn.a(SourceFile:81)
	at bqn.a(SourceFile:43)
	at bqn.a(SourceFile:22)
	at bqf.a(SourceFile:129)
	at bqf.a(SourceFile:117)
	at boh.a(SourceFile:662)
	at bnz.a(SourceFile:1266)
	at bnz.b(SourceFile:1171)
	at bnz.a(SourceFile:1018)
	at bcx.av(SourceFile:991)
	at bcx.a(SourceFile:396)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at bxk$1.a(SourceFile:47)
	at bxk$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bxk.a(SourceFile:126)
	at bqn.a(SourceFile:81)
	at bqn.a(SourceFile:43)

-- Block Entity Details --
Details:
	Name: Skull // ard
	Block type: ID #144 (tile.skull // aoy)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-87,5,-96), Chunk: (at 9,0,0 in -6,-6; contains blocks -96,0,-96 to -81,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #144 (tile.skull // aoy)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at b.a(SourceFile:245)
	at bqf.a(SourceFile:132)
	at bqf.a(SourceFile:117)
	at boh.a(SourceFile:662)
	at bnz.a(SourceFile:1266)
	at bnz.b(SourceFile:1171)
	at bnz.a(SourceFile:1018)
	at bcx.av(SourceFile:991)
	at bcx.a(SourceFile:396)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:919)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bnn['hongtruong'/9014, l='MpServer', x=-87,50, y=6,50, z=-71,50]]
	Chunk stats: MultiplayerChunkCache: 6, 6
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-87,6,-71), Chunk: (at 9,0,9 in -6,-5; contains blocks -96,0,-80 to -81,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 405445652 game time, 172272000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 4 total; [xx['§7/§anapthe§e để nạp thẻ nhận points sử dụng cho §7/§apshop'/37200791, l='MpServer', x=-78,70, y=5,98, z=-71,47], xx['Armor Stand'/37200784, l='MpServer', x=-81,50, y=4,30, z=-95,50], xx['§fClick trái để xem thông tin rương'/37200800, l='MpServer', x=-65,47, y=6,06, z=-79,42], bnn['hongtruong'/9014, l='MpServer', x=-87,50, y=6,50, z=-71,50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.15-SNAPSHOT:e6b0d43:1479) <- Spigot
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (armv8l) version 3.18.140-18069845
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-A600G, Android 10), The Android Project
	Memory: 0 bytes (0 MB) / 340173944 bytes (324 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.2
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x null

**Comment by khanhduytran0** [comment]
Duplicate. It's unfixable in v2.

**Comment by khanhduytran0** [comment]
So now use v3
