### ISSUE TITLE
PLEASE HELP[BUG] <Short description>

### ISSUE THREAD

**Issue by GreenFlame09** [PojavLauncherTeam/PojavLauncher#2171]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:612)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:435)
	at android.view.View.dispatchPointerEvent(View.java:12876)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5208)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4582)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4548)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4688)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4556)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4745)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4582)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4548)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4556)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7225)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7170)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7131)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7351)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7299)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:690)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6971)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)

### The log file and images/videos

JUST PLEASE HELP

### Steps To Reproduce

```markdown
PLSSSS HELPPPPP
```

### Expected Behavior

I NEED HELP TO GET IN ANY OF THE UPDATES

### Platform

```markdown
- Device model: cromebook
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by ajit850** [comment]
Fill the tamplate

**Comment by ghost** [comment]
"Please Help"

Nice issue 🤣

**Comment by ajit850** [comment]
What is problem

> ### Describe the bug
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:612) at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79) at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:435) at android.view.View.dispatchPointerEvent(View.java:12876) at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5208) at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5011) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4582) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4548) at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4688) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4556) at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4745) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4582) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4548) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4556) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4529) at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7225) at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7170) at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7131) at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7351) at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186) at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method) at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177) at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7299) at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7399) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949) at android.view.Choreographer.doCallbacks(Choreographer.java:761) at android.view.Choreographer.doFrame(Choreographer.java:690) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:193) at android.app.ActivityThread.main(ActivityThread.java:6971) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
> 
> ### The log file and images/videos
> JUST PLEASE HELP
> 
> ### Steps To Reproduce
> ```gfm
> PLSSSS HELPPPPP
> ```
> 
> ### Expected Behavior
> I NEED HELP TO GET IN ANY OF THE UPDATES
> 
> ### Platform
> ```gfm
> - Device model: cromebook
> - CPU architecture: 
> - Android version: 
> - PojavLauncher version:
> ```
> 
> ### Anything else?
> _No response_

Whai is problem

**Comment by ajit850** [comment]
@GreenFlame09 ?

**Comment by Mathias-Boulay** [comment]
Template not filled
