### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by dynmsx** [PojavLauncherTeam/PojavLauncher#218]
I copied from launcher.

java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/controlmap/default.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:200)
	at java.io.FileInputStream.<init>(FileInputStream.java:150)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at net.kdt.pojavlaunch.Tools.getByteArray(Tools.java:518)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:538)
	at net.kdt.pojavlaunch.value.customcontrols.ControlsLayout.loadLayout(ControlsLayout.java:63)
	at android.androidVNC.VncCanvasActivity.onCreate(VncCanvasActivity.java:136)
	at android.app.Activity.performCreate(Activity.java:7314)
	at android.app.Activity.performCreate(Activity.java:7305)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2959)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3084)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1781)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:210)
	at android.app.ActivityThread.main(ActivityThread.java:7080)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)

**Comment by khanhduytran0** [comment]
Options -> Custom controls and Try again.

**Comment by dynmsx** [comment]
and? 
![Screenshot_2020-05-31-15-48-54-09](https://user-images.githubusercontent.com/66199719/83348384-4b0ed680-a356-11ea-8168-a18fe8417b7d.png)

**Comment by khanhduytran0** [comment]
Back button, then try launch again.

**Comment by khanhduytran0** [comment]
@dynmsx please reply

**Comment by dynmsx** [comment]
sorry. The game was crash when i click play so i don't wanna play anymore

**Comment by khanhduytran0** [comment]
So can you put crash here?

**Comment by khanhduytran0** [comment]
> Options -> Custom controls and Try again.

Closing. Fix by that.
