### ISSUE TITLE
Cant Launch

### ISSUE THREAD

**Issue by Crouzxoo** [PojavLauncherTeam/PojavLauncher#2185]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

### The log file and images/videos

![Screenshot_20211031_183643](https://user-images.githubusercontent.com/92728662/139585780-b34b44de-afa8-43e0-ba1c-1d2ee149a168.jpg)

### Steps To Reproduce

```markdown
Please fix it
```

### Expected Behavior

Why i cant launch

### Platform

```markdown
- Device model: Vivo Y71
- CPU architecture: Core 1,2,3,4
- Android version: 8.1.0
- PojavLauncher version:all versions
```

**Comment by ChooweKamska999** [comment]
How

**Comment by artistic62827272** [comment]
Same problem
