### ISSUE TITLE
[BUG] minecraft 1.18 experimental Snapshot not working!!

### ISSUE THREAD

**Issue by 1493028** [PojavLauncherTeam/PojavLauncher#2196]
### Describe the bug

I'm trying to play minecraft 1.18 experimental Snapshot, the Mojang logo hasn't shown up yet, it's crashed, I've used assets v0 shaderpack, it still crashes

### Steps To Reproduce

```markdown
I open my PojavLauncher and I select 1.18 experimental Snapshot 2 when I enter the game it crashes!!
```

### Expected Behavior

Minecraft 1.18 experimental Snapshot not working on pojav launcher crocus V3 jdk

### Platform

```markdown
- Device model: Vivo y50 8/128G
- CPU architecture: Aarch64
- Android version: 10
- PojavLauncher version: [latest release] version crocus V3 jdk
```

**Comment by Pgabrielmnecraft** [comment]
ok but, where's the log?

**Comment by 1493028** [comment]
> ok but, where's the log?

the text is rendering overlay 

I forgot to send the crash log

**Comment by 1493028** [comment]
This is the crash log
---- Minecraft Crash Report ----
// You're mean.

Time: 28/10/21 23.33
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at emy.b(SourceFile:492)
	at emy.a(SourceFile:380)
	at adx.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)
	at dpo.e(SourceFile:310)
	at dvm.f(SourceFile:1137)
	at dvm.e(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:233)
Caused by: xa: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 1:16: 'clamp' : no matching overloaded function found 
ERROR: 1:16: 'texture' : no matching overloaded function found 
ERROR: 1:16: 'return' : function return is not matching type: 
ERROR: 4 compilation errors.  No code generated.
	at xa.a(SourceFile:48)
	at enq.<init>(SourceFile:197)
	at emy.b(SourceFile:448)
	... 118 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 1:16: 'clamp' : no matching overloaded function found 
ERROR: 1:16: 'texture' : no matching overloaded function found 
ERROR: 1:16: 'return' : function return is not matching type: 
ERROR: 4 compilation errors.  No code generated.
	at dpx.b(SourceFile:72)
	at dpx.a(SourceFile:54)
	at enq.a(SourceFile:237)
	at enq.<init>(SourceFile:179)
	... 119 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at emy.b(SourceFile:492)
	at emy.a(SourceFile:380)
	at adx.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at aeb.a(SourceFile:71)
	at ary.execute(SourceFile:101)
	at aeb.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:179)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:166)

-- Overlay render details --
Details:
	Overlay name: eab
Stacktrace:
	at emy.a(SourceFile:867)
	at dvm.f(SourceFile:1112)
	at dvm.e(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:233)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.18 experimental snapshot 2
	Minecraft Version ID: 1.18_experimental-snapshot-2
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1412675072 bytes (1347 MiB) / 1784676352 bytes (1702 MiB) up to 1784676352 bytes (1702 MiB)
	CPUs: 6
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 4 (aarch64)
	Identifier: 0x51 Family 8 Model 0x800 Stepping r0xap4
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7900,30
	Virtual memory used (MB): 8105,29
	Swap memory total (MB): 4096,00
	Swap memory used (MB): 1946,44
	JVM Flags: 2 total; -Xms1701M -Xmx1701M
	Launched Version: 1.18_experimental-snapshot-2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 2242x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AArch64 Processor rev 4 (aarch64)

**Comment by TristanSO** [comment]
I got this bug too
But it's 1.17 and 1.18.x
