### ISSUE TITLE
[BUG -Kinda*]

### ISSUE THREAD

**Issue by RayZxyo** [PojavLauncherTeam/PojavLauncher#2204]
### Describe the bug

Can someone help me? (forge 1.17.1)

### The log file and images/videos

Exception in thread "main" 
java.lang.module.FindException: Module cpw.mods.securejarhandler not found, required by cpw.mods.bootstraplauncher
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:83)
Java Exit code: 1

### Steps To Reproduce

```markdown
empty
```

### Expected Behavior

empty

### Platform

```markdown
- Device model: Samsung A50
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel/20210226
```

### Anything else?

nope

**Comment by NotAHero04** [comment]
You have an outdated launcher build. But anyway, reinstall Forge to download all the libraries needed.

**Comment by NotAHero04** [comment]
@khanhduytran0 stated that Forge 1.17.1 is currently not supported. :fr:

**Comment by ghost** [comment]
Modded fabric turns on but never loads a world bruhh..

**Comment by RayZxyo** [comment]
What do you mean I can't open minecraft

**Comment by Mathias-Boulay** [comment]
Pojav launcher version is too old
