### ISSUE TITLE
Error in Pojav Launcher 3.0.1 preview 5

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#221]
java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/controlmap/default.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at net.kdt.pojavlaunch.Tools.getByteArray(Tools.java:518)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:538)
	at net.kdt.pojavlaunch.value.customcontrols.ControlsLayout.loadLayout(ControlsLayout.java:63)
	at android.androidVNC.VncCanvasActivity.onCreate(VncCanvasActivity.java:136)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3101)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by artdeell** [comment]
Create a keymap before starting.

**Comment by Doxelix** [comment]
What?

**Comment by khanhduytran0** [comment]
> Create a keymap before starting.

Options -> Custom controls
Then exit and do a run.

**Comment by Doxelix** [comment]
Thank you.

**Comment by irman917** [comment]
What

**Comment by stema180** [comment]
How do you reset your pojavlauncher...? Without Deleting it? Like just reset everything to the way it was?

**Comment by stema180** [comment]
Because I cant delete it or I cant get it back

**Comment by stema180** [comment]
Because its saying this thing:
java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/controlmap/default.json: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:691)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:697)
	at net.kdt.pojavlaunch.customcontrols.CustomControls.save(CustomControls.java:62)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.saveLayout(ControlLayout.java:198)
	at net.kdt.pojavlaunch.CustomControlsActivity.doSaveCtrl(CustomControlsActivity.java:132)
	at net.kdt.pojavlaunch.CustomControlsActivity.access$300(CustomControlsActivity.java:23)
	at net.kdt.pojavlaunch.CustomControlsActivity$4$1.onClick(CustomControlsActivity.java:179)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7567)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 20 more
But I cant like... change the thing because im... A re-tard

**Comment by Doxelix** [comment]
1

> Because its saying this thing: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/controlmap/default.json: open failed: EACCES (Permission denied) at libcore.io.IoBridge.open(IoBridge.java:492) at java.io.FileOutputStream.(FileOutputStream.java:236) at java.io.FileOutputStream.(FileOutputStream.java:125) at net.kdt.pojavlaunch.Tools.write(Tools.java:691) at net.kdt.pojavlaunch.Tools.write(Tools.java:697) at net.kdt.pojavlaunch.customcontrols.CustomControls.save(CustomControls.java:62) at net.kdt.pojavlaunch.customcontrols.ControlLayout.saveLayout(ControlLayout.java:198) at net.kdt.pojavlaunch.CustomControlsActivity.doSaveCtrl(CustomControlsActivity.java:132) at net.kdt.pojavlaunch.CustomControlsActivity.access$300(CustomControlsActivity.java:23) at net.kdt.pojavlaunch.CustomControlsActivity$4$1.onClick(CustomControlsActivity.java:179) at android.view.View.performClick(View.java:7448) at android.view.View.performClickInternal(View.java:7425) at android.view.View.access$3600(View.java:810) at android.view.View$PerformClick.run(View.java:28305) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7737) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954) Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied) at libcore.io.Linux.open(Native Method) at libcore.io.ForwardingOs.open(ForwardingOs.java:166) at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254) at libcore.io.ForwardingOs.open(ForwardingOs.java:166) at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7567) at libcore.io.IoBridge.open(IoBridge.java:478) ... 20 more But I cant like... change the thing because im... A re-tard

1. Install ZArchiver (If you are Android 10+)
2. Show invisible folders
3. Go to Android/data
4. Copy net.kdt.pojavlaunch to internal storage/"where do you want"
5. Re-install PojavLauncher.
6. Copy net.kdt.pojavlaunch to Android/data/
7. Done

**Comment by Andrewson2009** [comment]
Where it's internal storage

**Comment by nevfuxon** [comment]
> How do you reset your pojavlauncher...? Without Deleting it? Like just reset everything to the way it was?

For a clean reset, use the UDR method; my acrostic of Uninstall, Delete, and Reinstall

If you're referring to resetting the launcher; Clear the data to remove the runtimes (cache doesn't matter:troll:)
For Android 10+, it'll automatically delete the user directory (`Android/data/net.kdt.pojavlaunch`)

For Android <9, you'll have to manually delete `.../games/PojavLauncher`

**Comment by mchnjt** [comment]
> Where it's internal storage

What do you refer by "Internal Storage"?
Do you mean the location where the launcher saves it's data?
