### ISSUE TITLE
Unable to start mod installer from java8

### ISSUE THREAD

**Issue by aaaapai** [PojavLauncherTeam/PojavLauncher#2216]
### Describe the bug

I installed the latest version and found that the game could not be started. Java8 could not start the mod installer.

### The log file and images/videos

**java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.utils.JREUtils.setJavaEnvironment(JREUtils.java:213)
	at net.kdt.pojavlaunch.utils.JREUtils.launchJavaVM(JREUtils.java:284)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.launchJavaRuntime(JavaGUILauncherActivity.java:346)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.doCustomInstall(JavaGUILauncherActivity.java:311)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity.access$700(JavaGUILauncherActivity.java:20)
	at net.kdt.pojavlaunch.JavaGUILauncherActivity$6.run(JavaGUILauncherActivity.java:214)
	at java.lang.Thread.run(Thread.java:929)**

### Steps To Reproduce

```markdown
1.Install new version
2.open
3.Unable to start mod setup
```

### Expected Behavior

The game can be started and the mod installer can be started

### Platform

```markdown
- Device model: 荣耀30青春版
- CPU architecture: 天玑800
- Harmony OS version: Harmony OS
- PojavLauncher version: crocus-126-48cf6ca69-v3-virgl
```

### Anything else?

Play the old version first

**Comment by Mathias-Boulay** [comment]
Non supported branch
