### ISSUE TITLE
Can't unzip Optifine 1.17

### ISSUE THREAD

**Issue by crischutu07** [PojavLauncherTeam/PojavLauncher#2316]
### Describe the bug

When I install Optifine 1.17.1 jar file and I got this error

### The log file and images/videos

OptiFine Version: OptiFine_1.17.1_HD_U_G9
Minecraft Version: 1.17.1
OptiFine Edition: HD_U_G9
URL: file:/data/data/net.kdt.pojavlaunch/cache/OptiFine_1.17.1_HD_U_G9.jar

Dir minecraft: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft

Dir libraries: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries
Dir versions: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions
OptiFine Version: OptiFine_1.17.1_HD_U_G9

Minecraft Version: 1.17.1
OptiFine Edition: HD_U_G9
Minecraft_OptiFine Version: 1.17.1-OptiFine_HD_U_G9
Dir version MC: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.17.1

Dir version MC-OF: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.17.1-OptiFine_HD_U_G9
URL: file:/data/data/net.kdt.pojavlaunch/cache/OptiFine_1.17.1_HD_U_G9.jar

Source: /data/data/net.kdt.pojavlaunch/cache/OptiFine_1.17.1_HD_U_G9.jar
Dest: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/optifine/OptiFine/1.17.1_HD_U_G9/OptiFine-1.17.1_HD_U_G9.jar
java.util.zip.ZipException: error in opening zip file

	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at optifine.Patcher.process(Patcher.java:74)
	at optifine.Installer.installOptiFineLibrary(Installer.java:371)
	at optifine.Installer.doInstall(Installer.java:96)
	at optifine.InstallerFrame.onInstall(InstallerFrame.java:425)
	at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:490)
	at optifine.InstallerFrame.access$7(InstallerFrame.java:484)
	at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Dir minecraft: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft

Dir libraries: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries

Dir versions: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions
OptiFine Version: OptiFine_1.17.1_HD_U_G9
Minecraft Version: 1.17.1
OptiFine Edition: HD_U_G9
Minecraft_OptiFine Version: 1.17.1-OptiFine_HD_U_G9
Dir version MC: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.17.1
Dir version MC-OF: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.17.1-OptiFine_HD_U_G9
URL: file:/data/data/net.kdt.pojavlaunch/cache/OptiFine_1.17.1_HD_U_G9.jar

Source: /data/data/net.kdt.pojavlaunch/cache/OptiFine_1.17.1_HD_U_G9.jar
Dest: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/optifine/OptiFine/1.17.1_HD_U_G9/OptiFine-1.17.1_HD_U_G9.jar
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)

	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at optifine.Patcher.process(Patcher.java:74)
	at optifine.Installer.installOptiFineLibrary(Installer.java:371)
	at optifine.Installer.doInstall(Installer.java:96)
	at optifine.InstallerFrame.onInstall(InstallerFrame.java:425)

	at optifine.InstallerFrame.connEtoC1(InstallerFrame.java:490)
	at optifine.InstallerFrame.access$7(InstallerFrame.java:484)
	at optifine.InstallerFrame$IvjEventHandler.actionPerformed(InstallerFrame.java:46)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)

	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)

	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
logcat: Unexpected EOF!

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Install Optifine on download folder and click it
3. click install
4. And got error
```

### Expected Behavior

I expect to installing Optifine 1.17.1 jar

### Platform

```markdown
- Device model: Oppo A53
- CPU architecture: Snapdragon 460
- Android version: 11 
- PojavLauncher version: crocus-v3-openjdk [3.3.1.1_rel_20210206]
```

### Anything else?

no

**Comment by GoneSubject** [comment]
did you used java 17?

**Comment by crischutu07** [comment]
Yeah

**Comment by GoneSubject** [comment]
you must use java 8

**Comment by GoneSubject** [comment]
only java 8 can install .jar files

**Comment by crischutu07** [comment]
> only java can install .jar files

Is have same error too

**Comment by GoneSubject** [comment]
> > only java can install .jar files
> 
> Is have same error too

did you used java 8?

**Comment by crischutu07** [comment]
> > > only java can install .jar files
> > 
> > 
> > Is have same error too
> 
> đi you úed java 8?

I use both jre 8 and jre 17 arm64

**Comment by crischutu07** [comment]
Is have same error

**Comment by GoneSubject** [comment]
hmm

**Comment by GoneSubject** [comment]
let me ask for help

**Comment by GoneSubject** [comment]
i think the file is corrupted or something

**Comment by GoneSubject** [comment]
can you download another file like that and try again?

**Comment by crischutu07** [comment]
> i think the file is corrupted or something

I downloaded on Optifine website ._.

**Comment by crischutu07** [comment]
> can you download another file like that and try again?

o thx

**Comment by crischutu07** [comment]
> can you download another file like that and try again?

I will try

**Comment by crischutu07** [comment]
> can you download another file like that and try again?

There the website I downloaded https://optifine.net/downloads

**Comment by GoneSubject** [comment]
> > can you download another file like that and try again?
> 
> There the website I downloaded https://optifine.net/downloads

hm that's the offical one so it safe

**Comment by crischutu07** [comment]
I downloaded pre version of Optifine 1.17.1 is same

**Comment by crischutu07** [comment]
> > > can you download another file like that and try again?
> > 
> > 
> > There the website I downloaded https://optifine.net/downloads
> 
> hm that's the offical one so it safe

Can you add me as friends?
crischutu07#1165

**Comment by GoneSubject** [comment]
> > > > can you download another file like that and try again?
> > > 
> > > 
> > > There the website I downloaded https://optifine.net/downloads
> > 
> > 
> > hm that's the offical one so it safe
> 
> Can you add me as friends? crischutu07#1165

ok im GoneSubject#3207

**Comment by NotAHero04** [comment]
Maybe check if you can unzip 1.17.1 JAR file? Or just launch 1.17.1 to see

**Comment by GoneSubject** [comment]
how bruh

**Comment by tenpeisit** [comment]
Can you help me to learn English?
I am Chinese.

**Comment by GoneSubject** [comment]
> Can you help me to learn English? I am Chinese.

learn it yourself
