### ISSUE TITLE
[BUG] cant load or set main controls

### ISSUE THREAD

**Issue by officialdakari** [PojavLauncherTeam/PojavLauncher#2321]
### Describe the bug

Cant read file

### The log file and images/videos

`java.lang.NullPointerException: Attempt to get length of null array
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:114)
	at com.kdt.pickafile.FileListView.init(FileListView.java:93)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:52)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:46)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:36)
	at net.kdt.pojavlaunch.CustomControlsActivity.dialogSelectDefaultCtrl(CustomControlsActivity.java:116)
	at net.kdt.pojavlaunch.CustomControlsActivity$1.onNavigationItemSelected(CustomControlsActivity.java:69)
	at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:217)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
	at android.view.View.performClick(View.java:7146)
	at android.view.View.performClickInternal(View.java:7119)
	at android.view.View.access$3500(View.java:803)
	at android.view.View$PerformClick.run(View.java:27533)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7389)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
`

### Steps To Reproduce

```markdown
1. Set up user controls
2. Save them
3. Select set as main
4. Select any file
5. Boom, here is the error
```

### Expected Behavior

I expect that in-game controls will set as main

### Platform

```markdown
- Device model: Blackview BV4900
- CPU architecture: Arm64
- Android version: 10
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I cant set my in-game controls as main (I'm playing with mods)

**Comment by GoneSubject** [comment]
welp i think the control that you choose it does get error but the control that you choose still set as main

**Comment by Mathias-Boulay** [comment]
Fixed with the release candidate build
