### ISSUE TITLE
[BUG] Android 11(SDK 30): crash when add new java runtime

### ISSUE THREAD

**Issue by shadichy** [PojavLauncherTeam/PojavLauncher#2336]
### Describe the bug

when i press **runtime manager** -> **add new**, it crashes
also, when i launch a mod installer, it crashes

### The log file and images/videos

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/x-xz }
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
    at android.app.Activity.startActivityForResult(Activity.java:5320)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
    at android.app.Activity.startActivityForResult(Activity.java:5278)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:560)
    at net.kdt.pojavlaunch.multirt.MultiRTConfigDialog.openRuntimeSelector(MultiRTConfigDialog.java:42)
    at net.kdt.pojavlaunch.multirt.MultiRTConfigDialog.lambda$prepare$0(MultiRTConfigDialog.java:28)
    at net.kdt.pojavlaunch.multirt.-$$Lambda$MultiRTConfigDialog$fP8_1TBMcwakCrixe6YEcNNbUdM.onClick(Unknown Source:2)
    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:178)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7705)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

### Steps To Reproduce

```markdown
runtime manager -> add new -> crash
option -> launch a mod installer -> crash
```

### Expected Behavior

open files and choose file/folder

### Platform

```markdown
- Device model: VSmart Star 4
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Google Play latest | latest success action build | custom compilation (modified runtime and mainfest)
```

### Anything else?

manually move custom runtime folder to **/data/data/net.kdt.pojavlauch/runtimes** gives me what i need

**Comment by GoneSubject** [comment]
uh where did you get the runtime that you want to add to the runtime manager?

**Comment by shadichy** [comment]
your source

**Comment by khanhduytran0** [comment]
As what it says, there's no file picker on your device, then how can you pick it? Install one moment 👀 :

**Comment by shadichy** [comment]
i have a lot
SD Maid, RAR, Total Commander, TermOnePlus (not a FM but have file picker function)
and also Midnight Commander if count :)

**Comment by GoneSubject** [comment]
bruh ._.

**Comment by khanhduytran0** [comment]
Try installing ZArchiver.

**Comment by GoneSubject** [comment]
> Try installing ZArchiver.

yea

**Comment by shadichy** [comment]
weird, but it works
thanks

**Comment by GoneSubject** [comment]
cool
