### ISSUE TITLE
I have a problem when I am trying to join server

### ISSUE THREAD

**Issue by HypeePl** [PojavLauncherTeam/PojavLauncher#234]
It always happen when I try to join any server ;(

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 19.06.2020 12:13
Description: Rendering entity in world

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at csh.a(SourceFile:86)
	at cqv.a(SourceFile:411)
	at cqv.a(SourceFile:170)
	at cqv.a(SourceFile:30)
	at cpt.a(SourceFile:294)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:583)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)
	at cji.b(SourceFile:983)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at cvx.a(SourceFile:47)
	at cvx.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at csh.a(SourceFile:86)
	at cqv.a(SourceFile:411)
	at cqv.a(SourceFile:170)

-- Entity being rendered --
Details:
	Entity Type: ArmorStand (adi)
	Entity ID: 41
	Entity Name: Armor Stand
	Entity's Exact location: -31,19, 61,02, -23,56
	Entity's Block location: -32,00,61,00,-24,00 - World: (-32,61,-24), Chunk: (at 0,3,8 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0,00, 0,00, 0,00
	Entity's Rider: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'java.lang.String wv.toString()' on a null object reference
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'java.lang.String wv.toString()' on a null object reference
Stacktrace:
	at b.a(SourceFile:244)
	at cpt.a(SourceFile:319)
	at cpt.a(SourceFile:259)
	at cpt.a(SourceFile:226)
	at ckn.a(SourceFile:583)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)
	at cji.b(SourceFile:983)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

-- Renderer details --
Details:
	Assigned renderer: cpe@ae51889
	Location: -31,69,-4,98,-24,06 - World: (-32,-5,-25), Chunk: (at 0,-1,7 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: 94.21875
	Delta: 0.77246165

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [cio['HypeePl'/756, l='MpServer', x=0,50, y=66,00, z=0,50], cip['Natalia0108'/752, l='MpServer', x=-26,84, y=60,02, z=-2,50]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 0,00,66,00,0,00 - World: (0,66,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 57519 game time, 49115408000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 29 total; [adi['Armor Stand'/72, l='MpServer', x=28,16, y=66,14, z=-31,91], adi['Armor Stand'/73, l='MpServer', x=30,94, y=59,36, z=47,28], adi['Armor Stand'/74, l='MpServer', x=31,63, y=60,02, z=47,16], adi['Armor Stand'/75, l='MpServer', x=18,25, y=60,02, z=33,28], adi['Armor Stand'/76, l='MpServer', x=19,72, y=60,02, z=33,44], adi['Armor Stand'/77, l='MpServer', x=18,94, y=62,48, z=33,03], adi['Armor Stand'/78, l='MpServer', x=18,91, y=62,48, z=33,00], adi['Armor Stand'/80, l='MpServer', x=47,25, y=59,89, z=33,97], cio['HypeePl'/756, l='MpServer', x=0,50, y=66,00, z=0,50], adi['Armor Stand'/38, l='MpServer', x=-46,34, y=59,89, z=-30,75], adi['Armor Stand'/39, l='MpServer', x=-45,03, y=59,11, z=-30,66], adi['Armor Stand'/40, l='MpServer', x=-45,09, y=59,14, z=-30,97], adi['Armor Stand'/41, l='MpServer', x=-31,19, y=61,02, z=-23,56], adi['§6███████████████████████████'/106, l='MpServer', x=-8,50, y=68,48, z=0,50], adi['Armor Stand'/42, l='MpServer', x=-19,50, y=60,05, z=19,50], cip['Natalia0108'/752, l='MpServer', x=-26,84, y=60,02, z=-2,50], adi[' §6§lNOWOSC! LOGOWANIE PREMIUM'/107, l='MpServer', x=-8,50, y=68,23, z=0,50], adi['Armor Stand'/43, l='MpServer', x=-28,47, y=63,45, z=34,66], adi[' §b§lPOSIADASZ KONTO PREMIUM MINECRAFT?'/108, l='MpServer', x=-8,50, y=67,98, z=0,50], adi[' §6§lNIE CHCE CI SIE ZA KAZDYM RAZEM WPISYWAC'/109, l='MpServer', x=-8,50, y=67,73, z=0,50], adi[' §6§lHASLA PRZY WCHODZENIU NA SERWER?'/110, l='MpServer', x=-8,50, y=67,48, z=0,50], adi['Armor Stand'/46, l='MpServer', x=-0,28, y=60,02, z=55,56], adi[' §6§lWPROWADZILISMY DLA CIEBIE NOWA MOZLIWOSC'/111, l='MpServer', x=-8,50, y=67,23, z=0,50], adi[' §6§lOD TERAZ MOZESZ WLACZYC AUTOLOGOWANIE'/112, l='MpServer', x=-8,50, y=66,98, z=0,50], cip['Natalia0108'/752, l='MpServer', x=-26,84, y=60,02, z=-2,50], adi[' §6§lABY TO ZROBIC WEJDZ NA SERWER O ADRESIE IP:'/113, l='MpServer', x=-8,50, y=66,73, z=0,50], adi[' §6§lPREMIUM.MCSURVI.PL §6§lI WPISZ KOMENDE §6§l/PREMIUM!'/114, l='MpServer', x=-8,50, y=66,48, z=0,50], adi[' §b§lOPCJA TA DOSTEPNA TYLKO DLA OSOB Z ORYGINALNYM MC!'/115, l='MpServer', x=-8,50, y=66,23, z=0,50], adi['§6███████████████████████████'/116, l='MpServer', x=-8,50, y=65,98, z=0,50]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326) <- Paper
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (armv8l) version 4.4.153-perf+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (Xiaomi Redmi Note 7, Android 9), The Android Project
	Memory: 0 bytes (0 MB) / 392411352 bytes (374 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by khanhduytran0** [comment]
Looks like duplicate.

**Comment by HypeePl** [comment]
> Looks like duplicate.

What do you mean?

**Comment by khanhduytran0** [comment]
Duplicate with other issues that was created.

**Comment by HypeePl** [comment]
> Looks like duplicate.

Oops, i see now.. I'm sorry for taking your time...

**Comment by khanhduytran0** [comment]
Duplicate #163
