### ISSUE TITLE
[BUG] Crashed Pojavlancher

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2342]
### Describe the bug

The game crashes while running

### The log file and images/videos

java.lang.ArrayIndexOutOfBoundsException: -33
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1140)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
(I ran without fabric and the problem remained)

### Steps To Reproduce

```markdown
1.Start Pojavlancher
2.Run the game
3.Enter the world and the server
4.The game freezes for a few minutes and I crash
5.End
```

### Expected Behavior

I wanted it not to crash during the game because I was playing BedWars on a game server, it suddenly crashes during the game
I realized the problem still exists

### Platform

```markdown
- Device model:Redmi Note 8
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: crocus..
```

### Anything else?

Version 1.18 font is not known.
Sodium does not run in version 1.17 and above.

**Comment by GoneSubject** [comment]
1. that sodium is not fully supported
> Sodium does not run in version 1.17 and above
2. where's log?

**Comment by NotAHero04** [comment]
@MohammadRTX Update your launcher to the [latest build.](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1538968538)

**Comment by GoneSubject** [comment]
oh nvm

**Comment by Sharkle5587** [comment]
FUCK I,M CRASH

**Comment by GoneSubject1** [comment]
bruh

**Comment by GoneSubject** [comment]
what happened?

**Comment by ghost** [comment]
> 

Sodium is not a problem in the Google Play version, but it crashes in the developer version
Minecraft 1.16.5

**Comment by ghost** [comment]
> @MohammadRTX Update your launcher to the [latest build.](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1538968538)

thank you

**Comment by ghost** [comment]
The problem still exists

**Comment by ghost** [comment]
I do not have sodium

**Comment by Mathias-Boulay** [comment]
where log ?

**Comment by ghost** [comment]
java.lang.ArrayIndexOutOfBoundsException: -33
at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1140)
at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
at net.minecraft.class_1041.method_15998(class_1041.java:308)
at net.minecraft.class_310.method_1523(class_310.java:1068)
at net.minecraft.class_310.method_1514(class_310.java:681)
at net.minecraft.client.main.Main.main(Main.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at

**Comment by NotAHero04** [comment]
This has been fixed in the latest GitHub build, check it out.

**Comment by Mathias-Boulay** [comment]
That's not the full log, provide it or the issue will be terminated

**Comment by ghost** [comment]
> This has been fixed in the latest GitHub build, check it out.
thank you❤️

I honestly could not find the continuation of the crash log.

**Comment by Mathias-Boulay** [comment]
Fixed on dev builds
