### ISSUE TITLE
Crash when joining a cracked server 

### ISSUE THREAD

**Issue by DarkLord063** [PojavLauncherTeam/PojavLauncher#236]
Hi, I entered a cracked server and everything seems to work, I went in looked up and read something and about 15 seconds later my game crashes.

This is the crash log:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020/06/21 3:59 PM
Description: Rendering Block Entity

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at cnw.a(SourceFile:38)
	at cnw.a(SourceFile:21)
	at cno.a(SourceFile:114)
	at cno.a(SourceFile:102)
	at ckn.a(SourceFile:597)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)
	at cji.b(SourceFile:983)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:780)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at cvx.a(SourceFile:47)
	at cvx.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at cnw.a(SourceFile:38)

-- Block Entity Details --
Details:
	Name: Skull // bdm
	Block type: ID #144 (tile.skull // baj)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-51,60,29), Chunk: (at 13,3,13 in -4,1; contains blocks -64,0,16 to -49,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #144 (tile.skull // baj)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at b.a(SourceFile:244)
	at cno.a(SourceFile:117)
	at cno.a(SourceFile:102)
	at ckn.a(SourceFile:597)
	at cji.a(SourceFile:1225)
	at cji.a(SourceFile:1130)
	at cji.b(SourceFile:983)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:970)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:780)

-- Affected level --
Details:
	Level name: MpServer
	All players: 5 total; [cio['DarkLord063'/21642, l='MpServer', x=-47,14, y=74,43, z=-0,39], cip['GameInstict'/128725, l='MpServer', x=-28,63, y=60,00, z=-1,44], cip['THC_Mesha'/128693, l='MpServer', x=-34,25, y=87,02, z=16,69], cip['Rupayan_YT'/118706, l='MpServer', x=-46,22, y=62,00, z=-1,91], cip['burgee'/128733, l='MpServer', x=-16,50, y=61,63, z=0,31]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0,00,65,00,0,00 - World: (0,65,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 689234130 game time, 36326358014 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 24 total; [cio['DarkLord063'/21642, l='MpServer', x=-47,14, y=74,43, z=-0,39], cip['Othyiscool'/108562, l='MpServer', x=1,41, y=65,00, z=0,47], cip['mckenzra'/78423, l='MpServer', x=3,19, y=65,00, z=0,66], cip['stuntpoke28'/128687, l='MpServer', x=2,53, y=65,00, z=0,84], cip['NGLOLPLAYER'/128727, l='MpServer', x=1,41, y=65,00, z=0,47], adi['§9§l--------------------'/7828, l='MpServer', x=-26,41, y=62,16, z=-6,56], cip['GameInstict'/128725, l='MpServer', x=-3,91, y=65,00, z=0,91], adi['§aVisit our forums at §9www.Blockdrop.org'/7829, l='MpServer', x=-26,41, y=61,91, z=-6,56], cip['Naitik132'/128728, l='MpServer', x=-11,94, y=63,50, z=0,78], adi['§9§l--------------------'/7830, l='MpServer', x=-26,41, y=61,66, z=-6,56], cip['THC_Mesha'/128693, l='MpServer', x=-20,69, y=60,00, z=0,78], adi['§9§l--------------------'/7831, l='MpServer', x=-26,50, y=62,16, z=7,44], adi['§aJoin us on discord at §9https://discord.gg/Wk68Ceh'/7832, l='MpServer', x=-26,50, y=61,91, z=7,44], cip['GameInstict'/128725, l='MpServer', x=-28,63, y=60,00, z=-1,44], adi['§9§l--------------------'/7833, l='MpServer', x=-26,50, y=61,66, z=7,44], cip['burgee'/128733, l='MpServer', x=-0,75, y=65,00, z=0,38], cip['burgee'/128733, l='MpServer', x=-16,50, y=61,63, z=0,31], ahj['arrow'/128737, l='MpServer', x=-33,25, y=89,25, z=16,47], cip['NGLOLPLAYER'/128734, l='MpServer', x=1,41, y=65,00, z=0,47], cip['THC_Mesha'/128693, l='MpServer', x=-34,25, y=87,02, z=16,69], cip['Rupayan_YT'/118706, l='MpServer', x=-46,22, y=62,00, z=-1,91], cip['burgee'/128733, l='MpServer', x=-16,50, y=61,63, z=0,31], cip['Rupayan_YT'/118706, l='MpServer', x=-46,22, y=62,00, z=-1,91], cip['THC_Mesha'/128693, l='MpServer', x=-34,25, y=87,02, z=16,69]]
	Retry entities: 0 total; []
	Server brand: FlameCord (0.2.5 SNAPSHOT) <- Spigot
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (armv8l) version 4.4.95+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (HUAWEI DRA-LX2, Android 8.1.0), The Android Project
	Memory: 722872 bytes (0 MB) / 184637568 bytes (176 MB) up to 402653184 bytes (384 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (UK)
	Profiler Position: N/A (disabled)

**Comment by khanhduytran0** [comment]
Duplicate #163

**Comment by DarkLord063** [comment]
What does that mean😅

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/issues/163#issuecomment-623243098

**Comment by khanhduytran0** [comment]
I will close this as no more respond
