### ISSUE TITLE
Error (Dubplicate?)

### ISSUE THREAD

**Issue by TrueCy4n** [PojavLauncherTeam/PojavLauncher#237]
Tried playing on beta 1.2_0.2 and beta 1.8, got this instead.
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:943)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(MainActivity.java)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:122)
	... 5 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.Minecraft" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/net/minecraft/launchwrapper/1.5/launchwrapper-1.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/versions/b1.8/b1.8.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 8 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/minecraft/launchwrapper/1.5/launchwrapper-1.5.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:26)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:26)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/ow2/asm/asm-all/4.1/asm-all-4.1.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:26)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:26)
		... 5 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/versions/b1.8/b1.8.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at net.minecraft.launchwrapper.LaunchClassLoader.<init>(LaunchClassLoader.java:103)
		at net.minecraft.launchwrapper.Launch.<init>(Launch.java:26)
		... 5 more
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.Minecraft" on path: DexPathList[[zip file "/data/app/net.kdt.pojavlaunch-1/base.apk"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /data/app/net.kdt.pojavlaunch-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 9 more
		Suppressed: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
			at java.lang.Class.classForName(Native Method)
			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 10 more
		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by khanhduytran0** [comment]
Did 1.7.10 worked?

**Comment by TrueCy4n** [comment]
> Did 1.7.10 worked?
I got:
Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.7.10/1.7.10.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by khanhduytran0** [comment]
So what's your Android version?

**Comment by TrueCy4n** [comment]
Android 6.0, Samsung J2 Prime.

**Comment by khanhduytran0** [comment]
I think Android 6 is the problem, many other similar issues reported they run on Android 6 too. So you may try to run inside VMOS.

**Comment by khanhduytran0** [comment]
Confirmed in #123 #55. Not confirmed in #217 #46 #21.

**Comment by khanhduytran0** [comment]
v2
