### ISSUE TITLE
[BUG] Only 1.7.10 working in action builds

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#2383]

**Comment by SprainedSpark89** [comment]
try launching 1.12.2 that might work
then get optifine for it if works and if it lag badly

**Comment by TyraVex** [comment]
![Screenshot_2021-12-12-12-18-21-010_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/34800546/145710211-9f22fc43-3326-4cdc-8c6a-18e9be4bc52d.jpg)
1.12.2 doesn't launch
```
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:621)
	at net.kdt.pojavlaunch.BaseMainActivity.initLayout(BaseMainActivity.java:75)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:28)
	at android.app.Activity.performCreate(Activity.java:8127)
	at android.app.Activity.performCreate(Activity.java:8098)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3513)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3700)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:689)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:529)
	... 17 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7934)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 21 more
```

**Comment by WesleyVanNeck** [comment]
launch 1.7.10 first

**Comment by TyraVex** [comment]
> launch 1.7.10 first

I did and it's working great
But I can't launch any other version exept this one

**Comment by SprainedSpark89** [comment]
get the playstore version i can't use the debug one on any version and you can have both playstore and debug so the playstore will work

**Comment by TyraVex** [comment]
> get the playstore version i can't use the debug one on any version and you can have both playstore and debug so the playstore will work

I already have the playstore version running flawlessly. I just want to point out some bugs that could be patched in the lastest builds to help the devs making a bugfree experience for the next update

**Comment by SprainedSpark89** [comment]
are you able to run older version

**Comment by TyraVex** [comment]
> are you able to run older version

Nope

**Comment by mkikets99** [comment]
Can confirm: Artifact `Android CI#3497` still have this issue

**Comment by mkikets99** [comment]
Also... if you install `1.7.10` and then use another version launcher will start the `1.7.10` version

**Comment by mkikets99** [comment]
[Android CI #3502](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1595113384) same here

**Comment by TyraVex** [comment]
Any update about this bug?

**Comment by mkikets99** [comment]
[Android CI #3506](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1598242529) have same issue

**Comment by ChromaPIE** [comment]
Confirmed on [Android CI #3530](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/1665251442). Haven't been officially responded yet? It's been nearly a month.

**Comment by Mathias-Boulay** [comment]
Fixed with candidate release build
