### ISSUE TITLE
[BUG] Game crashed while starting

### ISSUE THREAD

**Issue by irice7** [PojavLauncherTeam/PojavLauncher#2388]
### Describe the bug

I don't know, the game just crashed. I give log (including screenshot) below.

### The log file and images/videos

PojavLauncher crash report
 - Time: 12 Des 2021 08.25.07
 - Device: CPH1909 CPH1909
 - Android version: 8.1.0
 - Crash stack trace:
 - Launcher version: crocus-v3_openjdk
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2878)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3072)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1766)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6977)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)
Caused by: java.lang.NullPointerException: Attempt to read from field 'float android.util.DisplayMetrics.density' on a null object reference
	at net.kdt.pojavlaunch.Tools.dpToPx(Tools.java:386)
	at net.kdt.pojavlaunch.BaseMainActivity.<init>(BaseMainActivity.java:53)
	at net.kdt.pojavlaunch.MainActivity.<init>(MainActivity.java:18)
	at java.lang.Class.newInstance(Native Method)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2868)
	... 9 more
![Screenshot_2021-12-13-09-39-58-43](https://user-images.githubusercontent.com/79078329/145744413-0fe2639e-557f-48cb-9e72-86b8f352bd6e.jpg)

### Steps To Reproduce

```markdown
When i start the game, it shows the message that i screen shot above.
```

### Expected Behavior

The game should launch. I didn't have this kind of problem before.

### Platform

```markdown
- Device model: Oppo A5S 3/32G
- CPU architecture: aarch64
- Android version: 8.1.0
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by LightestMC** [comment]
Try deleting Pojavlauncher and the PojavLauncher folder, then reinstall Pojav again.

**Comment by irice7** [comment]
Thanks, it worked. I also make a backup (because i have a lot of client installed). I'll close this issue.
