### ISSUE TITLE
[BUG] I Can't start the game

### ISSUE THREAD

**Issue by AARININ** [PojavLauncherTeam/PojavLauncher#2406]
### Describe the bug

java.io.FileNotFoundException: /data/user/0/net.kdt.pojavlaunch/jre_runtime/release: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:58)
	at net.kdt.pojavlaunch.utils.JREUtils.readJREReleaseProperties(JREUtils.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:881)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2300(BaseMainActivity.java:26)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:679)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7463)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 8 more

### Steps To Reproduce

```markdown
I started to play 1.18.1 and it didn't work
```

### Expected Behavior

. 

### Platform

```markdown
- Device model: Redimi Note 8T
- CPU architecture: 
- Android version: 10 QKQ1.200114.002
- PojavLauncher version:
```

**Comment by GoneSubject** [comment]
did you followed [here](https://pojavlauncherteam.github.io/updates/117.html)?

**Comment by t3st-account** [comment]
can reproduce on 
oneplus 6
android 11
snapdragon 845
pojav version: crocus-a24d3cf1d-v3_openjdk
jre17 installed following  https://pojavlauncherteam.github.io/updates/117.html

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory)
 at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:621)
 at net.kdt.pojavlaunch.BaseMainActivity.initLayout(BaseMainActivity.java:71)
 at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:28)
 at android.app.Activity.performCreate(Activity.java:8006)
 at android.app.Activity.performCreate(Activity.java:7990)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:233)
 at android.app.ActivityThread.main(ActivityThread.java:8068)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory)
 at libcore.io.IoBridge.open(IoBridge.java:492)
 at java.io.FileInputStream.<init>(FileInputStream.java:160)
 at java.io.FileInputStream.<init>(FileInputStream.java:115)
 at net.kdt.pojavlaunch.Tools.read(Tools.java:689)
 at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:529)
 ... 17 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
 at libcore.io.Linux.open(Native Method)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
 at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7929)
 at libcore.io.IoBridge.open(IoBridge.java:478)
 ... 21 more

Also the game folder is not there..

![photo5323678565906103480](https://user-images.githubusercontent.com/90215638/146396282-39528356-179b-4816-b14e-8d70176db01c.jpg)

**Comment by GoneSubject** [comment]
> can reproduce on oneplus 6 android 11 snapdragon 845 pojav version: crocus-a24d3cf1d-v3_openjdk jre17 installed following https://pojavlauncherteam.github.io/updates/117.html
> 
> java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory) at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:621) at net.kdt.pojavlaunch.BaseMainActivity.initLayout(BaseMainActivity.java:71) at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:28) at android.app.Activity.performCreate(Activity.java:8006) at android.app.Activity.performCreate(Activity.java:7990) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:233) at android.app.ActivityThread.main(ActivityThread.java:8068) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory) at libcore.io.IoBridge.open(IoBridge.java:492) at java.io.FileInputStream.(FileInputStream.java:160) at java.io.FileInputStream.(FileInputStream.java:115) at net.kdt.pojavlaunch.Tools.read(Tools.java:689) at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:529) ... 17 more Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory) at libcore.io.Linux.open(Native Method) at libcore.io.ForwardingOs.open(ForwardingOs.java:166) at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254) at libcore.io.ForwardingOs.open(ForwardingOs.java:166) at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7929) at libcore.io.IoBridge.open(IoBridge.java:478) ... 21 more
> 
> Also the game folder is not there..
> 
> ![photo5323678565906103480](https://user-images.githubusercontent.com/90215638/146396282-39528356-179b-4816-b14e-8d70176db01c.jpg)

why virgl?

**Comment by GoneSubject** [comment]
and send the file logs pls don't send like that
> The log file called latestlog.txt is located under sdcard/Android/data/net.kdt.pojavlaunch/files or sdcard/games/PojavLauncher. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by t3st-account** [comment]
![photo5323678565906103513](https://user-images.githubusercontent.com/90215638/146400368-79936f58-0c49-45cc-8aec-098704745c3d.jpg)
 logfile is 0b unfortunately

virgl, because i read, it won't work othervise

**Comment by t3st-account** [comment]
OK I think i fixed it, in the launcher i was logged in, however it showed "ofline", only by ticking 'keep me logged in' during the loginprocess (I have a MS account) it sowed up a connected, now 1.18.1 runs fine (using virgl)

**Comment by EncryptedLeaFy** [comment]
@GoneSubject1 <image src="https://cdn.discordapp.com/emojis/773175876954619966.png" alt="drunkcat" width="20"/>

**Comment by GoneSubject** [comment]
> @GoneSubject1 <img alt="drunkcat" width="20" src="https://camo.githubusercontent.com/7ad610f0fe0075c739df3ec89048694895bac38972b7d56dcf2f0c4649b26076/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3737333137353837363935343631393936362e706e67">

hm?

**Comment by EncryptedLeaFy** [comment]
> > @GoneSubject1 <img alt="drunkcat" width="20" src="https://camo.githubusercontent.com/7ad610f0fe0075c739df3ec89048694895bac38972b7d56dcf2f0c4649b26076/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3737333137353837363935343631393936362e706e67">
> 
> hm?

Haha clown

**Comment by GoneSubject** [comment]
> > > @GoneSubject1 <img alt="drunkcat" width="20" src="https://camo.githubusercontent.com/7ad610f0fe0075c739df3ec89048694895bac38972b7d56dcf2f0c4649b26076/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3737333137353837363935343631393936362e706e67">
> > 
> > 
> > hm?
> 
> Haha clown

ok

**Comment by NdraaGaminz** [comment]
Thats sad because, my realme c12 3/32 Helio g35 can launch it with no crashes💀

**Comment by khanhduytran0** [comment]
> /data/user/0/net.kdt.pojavlaunch/jre_runtime

@AARININ  This path indicates that the launcher is outdated, please update to latest.

**Comment by khanhduytran0** [comment]
> java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.7.10/1.7.10.json: open failed: ENOENT (No such file or directory)

@t3st-account the path is not place to java, so it has nothing to do with this issue, try launching again (with latest build)

**Comment by Sandwichdevi** [comment]
Some phones are not supported.

**Comment by Shamstabrez648** [comment]
I Have This problem in Pojavlaunch
 IQOO Z6 5G
Snapdragon 695

Android 13 



java.lang.RuntimeException: java.io.IOException: Failed to create parent directory
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.write(LauncherProfiles.java:51)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.save(ProfileEditorFragment.java:208)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.lambda$onViewCreated$0$net-kdt-pojavlaunch-fragments-ProfileEditorFragment(ProfileEditorFragment.java:80)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7590)
	at android.view.View.performClickInternal(View.java:7567)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29724)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)
Caused by: java.io.IOException: Failed to create parent directory
	at net.kdt.pojavlaunch.Tools.write(Tools.java:830)
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.write(LauncherProfiles.java:48)
	... 15 more











![Uploading Screenshot_20231209_120351.jpg…]()

**Comment by GaucovyAero** [comment]
create a new issue

**Comment by Mihai61** [comment]
> ### Describe the bug
> java.io.FileNotFoundException: /data/user/0/net.kdt.pojavlaunch/jre_runtime/release: open failed: ENOENT (No such file or directory) at libcore.io.IoBridge.open(IoBridge.java:496) at java.io.FileInputStream.(FileInputStream.java:159) at java.io.FileInputStream.(FileInputStream.java:115) at java.io.FileReader.(FileReader.java:58) at net.kdt.pojavlaunch.utils.JREUtils.readJREReleaseProperties(JREUtils.java:91) at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:881) at net.kdt.pojavlaunch.BaseMainActivity.access$2300(BaseMainActivity.java:26) at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:679) at java.lang.Thread.run(Thread.java:919) Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory) at libcore.io.Linux.open(Native Method) at libcore.io.ForwardingOs.open(ForwardingOs.java:167) at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252) at libcore.io.ForwardingOs.open(ForwardingOs.java:167) at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7463) at libcore.io.IoBridge.open(IoBridge.java:482) ... 8 more
> 
> ### The log file and images/videos
> _No response_
> 
> ### Steps To Reproduce
> I started to play 1.18.1 and it didn't work
> ### Expected Behavior
> .
> 
> ### Platform
> - Device model: Redimi Note 8T
> - CPU architecture: 
> - Android version: 10 QKQ1.200114.002
> - PojavLauncher version:
> ### Anything else?
> _No response_
