### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Darsmen** [PojavLauncherTeam/PojavLauncher#2419]
### Describe the bug

Не работает 1.18.1

### The log file and images/videos

---- Minecraft Crash Report ----
// Don't do that.

Time: 19.12.2021, 00:02
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at epe.b(SourceFile:497)
	at epe.a(SourceFile:385)
	at afl.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:209)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:196)
	at drp.e(SourceFile:310)
	at dxo.f(SourceFile:1142)
	at dxo.e(SourceFile:733)
	at net.minecraft.client.main.Main.main(SourceFile:238)
Caused by: yk: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 1:16: 'clamp' : no matching overloaded function found 
ERROR: 1:16: 'texture' : no matching overloaded function found 
ERROR: 1:16: 'return' : function return is not matching type: 
ERROR: 4 compilation errors.  No code generated.
	at yk.a(SourceFile:48)
	at epw.<init>(SourceFile:200)
	at epe.b(SourceFile:453)
	... 118 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : ERROR: 1:16: '/' :  wrong operand types  no operation '/' exists that takes a left-hand operand of type 'in 2-component vector of int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 1:16: 'clamp' : no matching overloaded function found 
ERROR: 1:16: 'texture' : no matching overloaded function found 
ERROR: 1:16: 'return' : function return is not matching type: 
ERROR: 4 compilation errors.  No code generated.
	at dry.b(SourceFile:72)
	at dry.a(SourceFile:54)
	at epw.a(SourceFile:241)
	at epw.<init>(SourceFile:182)
	... 119 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.b(SourceFile:497)
	at epe.a(SourceFile:385)
	at afl.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:209)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:196)

-- Overlay render details --
Details:
	Overlay name: ece
Stacktrace:
	at epe.a(SourceFile:867)
	at dxo.f(SourceFile:1117)
	at dxo.e(SourceFile:733)
	at net.minecraft.client.main.Main.main(SourceFile:238)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1829569536 bytes (1744 MiB) / 3149922304 bytes (3004 MiB) up to 3149922304 bytes (3004 MiB)
	CPUs: 6
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 14 (aarch64)
	Identifier: 0x51 Family 8 Model 0x804 Stepping r0xdp14
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7797,68
	Virtual memory used (MB): 7695,40
	Swap memory total (MB): 4048,00
	Swap memory used (MB): 1659,24
	JVM Flags: 2 total; -Xms3004M -Xmx3004M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 2400x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AArch64 Processor rev 14 (aarch64)

### Steps To Reproduce

```markdown
Просто запускаю игру
```

### Expected Behavior

Ошибка 1

### Platform

```markdown
- Device model: Poco X3 pro
- CPU architecture: незнаю
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210206
```

**Comment by GoneSubject** [comment]
don't send the crash log pls send the latestlog
> The log file called latestlog.txt is located under sdcard/Android/data/net.kdt.pojavlaunch/files or sdcard/games/PojavLauncher. You may need to activate an option in your file explorer to see hidden files and folders

**Comment by Darsmen** [comment]
https://drive.google.com/file/d/1-abmI7npuA_u6etYNHoEo2uD-JleJlJX/view?usp=drivesdk

**Comment by Darsmen** [comment]
https://drive.google.com/file/d/1-bpgkf_bEEtpTubMAUsiuy83ZA3RxLZz/view?usp=drivesdk

**Comment by GoneSubject** [comment]
> https://drive.google.com/file/d/1-bpgkf_bEEtpTubMAUsiuy83ZA3RxLZz/view?usp=drivesdk

the jvm argument should empty
> Info: Custom Java arguments: "-Xms800m -Xmx800m"

**Comment by Darsmen** [comment]
![Screenshot_2021-12-19-10-18-02-223_net kdt pojavlaunch](https://user-images.githubusercontent.com/96358986/146667114-7a59f5f6-a0f8-4942-b451-09f5d234e895.jpg)

**Comment by Darsmen** [comment]
Он был пустым

**Comment by GoneSubject** [comment]
> Он был пустым

так почему я вижу их в журнале?

**Comment by Darsmen** [comment]
Значит они сами генерируются как то там журнал пустой и я его не трогал

**Comment by Darsmen** [comment]
Я даже им пользоваться не умею

**Comment by Darsmen** [comment]
Сейчас переустановил, сделав всё действия что нужно было тоже самое, вот второй лог https://drive.google.com/file/d/1-mcbEi7_-XR-gkcg5CIaJ-m--aECgqWs/view?usp=drivesdk

**Comment by GoneSubject** [comment]
я все еще вижу, что он не пустой
> Информация: настраиваемые аргументы Java: "-Xms800m -Xmx800m"

**Comment by Darsmen** [comment]
Как его почистить?

**Comment by Darsmen** [comment]
У меня в той графе пусто

**Comment by GoneSubject** [comment]
можно ли запустить игру и отправить лог после ее падения?

**Comment by Darsmen** [comment]
Это и были логи после её падения, при загрузке игры

**Comment by Darsmen** [comment]
https://drive.google.com/file/d/1-z-qMsxtdlSJjavIoyXBgmFPx0oRmVyP/view?usp=drivesdk

**Comment by TranCongVinh** [comment]
![image](https://user-images.githubusercontent.com/90259221/146670883-f839472f-6f04-45f8-a1c8-ca4c8d708d91.png)

**Comment by GoneSubject** [comment]
> https://drive.google.com/file/d/1-z-qMsxtdlSJjavIoyXBgmFPx0oRmVyP/view?usp=drivesdk

я думаю, следуй за этим
https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

**Comment by Darsmen** [comment]
Да не работает оно, сколько раз уже пробовал

**Comment by GoneSubject** [comment]
> Да не работает оно, сколько раз уже пробовал

получить этот assets-v0 и заменить старую папку с пакетом ресурсов i и исправь это снова
https://cdn.discordapp.com/attachments/724163890803638277/892912425366589460/assets-v0.zip

**Comment by TranCongVinh** [comment]
close đi :fr:

**Comment by hirobrin356** [comment]
Здравствуйте можно вопрос почему на редми 9 при open 3.2 видны чёрные жирные полосы когда я использываю шейдеры любые а когда я включаю 4.3 то шейдерах исчезают полосы но даёт конкурентные лаги 4/10 fps
