### ISSUE TITLE
Please help what happened with my game 😭

### ISSUE THREAD

**Issue by kaicryptx** [PojavLauncherTeam/PojavLauncher#2430]
### Describe the bug

Idk what happened with my game

### The log file and images/videos

![Screenshot_2021-12-20-19-01-26-82_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/89289445/146775080-b5a0b593-8887-4af1-a19c-1e8f4e500c25.jpg)
![Screenshot_2021-12-20-19-03-53-53_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/89289445/146775100-1dade236-6397-4774-a51f-c02b906413c4.jpg)

### Steps To Reproduce

```markdown
Help!
```

### Expected Behavior

Help!

### Platform

```markdown
- Device model: Realme C3
- CPU architecture: MT6769V/CB
- Android version: 10
- PojavLauncher version: LATEST
```

### Anything else?

Plz Hlp!

**Comment by kaicryptx** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.BaseMainActivity.initLayout(BaseMainActivity.java:145)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:26)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3498)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3682)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:140)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:100)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2239)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7805)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
