### ISSUE TITLE
[BUG] Pojavlauncher fails to download Forge Update 1.12.2 

### ISSUE THREAD

**Issue by Abdulhadi5692HDI** [PojavLauncherTeam/PojavLauncher#2448]
### Describe the bug

A Dialog came up about a GSON error:
It went like this:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 143141 path $.objects
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.downloadIndex(MinecraftDownloaderTask.java:399)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:126)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 143141 path $.objects
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:492)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 12 more

### The log file and images/videos

![Screenshot_20211224-111622_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/87948364/147348315-b198b068-a29e-4447-8ba1-4cf48bee2694.jpg)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Click on version 1.12.2-forge-14.23.5.2860
3. A dialog pops-up saying a error with GSON
```

### Expected Behavior

The game to launch with the forge loader

### Platform

```markdown
- Device model: Samsung Galaxy S9
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk
```

**Comment by Abdulhadi5692HDI** [comment]
I changed and the same error appeared

**Comment by Abdulhadi5692HDI** [comment]
```
- - - [ ] # > `~~@Abdulhadi5692HDI @Abdulhadi5692HDI []()_****_~~`
```

**Comment by khanhduytran0** [comment]
How did you install forge? send 1.12.2-forge-14.23.5.2860.json moment

**Comment by Camitohulto14** [comment]
- Device model: Samsung Galaxy S9
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk

**Comment by Adamsbs685** [comment]
And how you Solved the problem?
