### ISSUE TITLE
[BUG] game won't launch 

### ISSUE THREAD

**Issue by Psych0Zs** [PojavLauncherTeam/PojavLauncher#2464]
### Describe the bug

I just can't launch the game on my Xiaomi Redmi note 10 pro

### The log file and images/videos

java.lang.RuntimeException: L'architecture arm64 est incompatible avec l'environnement d'exécution Java arm.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
1 start pojav launcher 
2 choose 1.18.1
3 start the game
```

### Expected Behavior

I expect the game to launch 

### Platform

```markdown
- Device model: M2101k6g
- CPU architecture: 
- Android version: 11
- PojavLauncher version: last release on the playstore
```

**Comment by GoneSubject** [comment]
the arm runtime you choose is not compatible for your phone

**Comment by khanhduytran0** [comment]
Well, your phone is not 32bit.

**Comment by Psych0Zs** [comment]
And can I found one that is compatible ?

Le lun. 27 déc. 2021 à 15:03, GoneSubject ***@***.***> a
écrit :

**Comment by khanhduytran0** [comment]
All can be found in https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559

**Comment by Psych0Zs** [comment]
Sorry but I tried to download the 3 java runtime but none worked. Do I do
something wrong ?

Le lun. 27 déc. 2021 à 23:46, Duy Tran Khanh ***@***.***> a
écrit :
