### ISSUE TITLE
[BUG]  Chain verification isnt working (sorry if it aint a pojav bug)

### ISSUE THREAD

**Issue by DerShendi** [PojavLauncherTeam/PojavLauncher#2478]
### Describe the bug

Well i keep having the problem where it says to me that theres a chain verification problem starting all the versions it had that for a while aswell for logging in but it stopped poping up when i somehow managed to log in
Heres a screenshot of what it says 
![Screenshot_20211228-010028_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/51245094/147615762-392ffc2d-23b6-4713-bd87-2a70a3887ce4.jpg)
And heres the error that pops up
javax.net.ssl.SSLHandshakeException: Chain validation failed
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1450)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1399)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1343)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.Tools.downloadFileMonitored(Tools.java:730)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.downloadLibrary(MinecraftDownloaderTask.java:270)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:151)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.security.cert.CertificateException: Chain validation failed
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:724)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:554)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:575)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:620)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:620)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:643)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:510)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:428)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:356)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:161)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:250)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1644)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 30 more
Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
	at android.sec.enterprise.certificate.DelegatingCertPathValidator.engineValidate(DelegatingCertPathValidator.java:63)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:720)
	... 47 more
Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 54 more
	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
		at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
		at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
		... 56 more

### Steps To Reproduce

```markdown
1 start pojav
2 try
3 cry
```

### Expected Behavior

I expect to game (sorry im not taking most of the other stuff serious im just ODing on coffe

### Platform

```markdown
- Device model: Samsung a50
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by khanhduytran0** [comment]
Please check if you have VPN enabled, or try changing internet connection.

**Comment by DerShendi** [comment]
> Please check if you have VPN enabled, or try changing internet connection.

Didnt have any but i checked some other stuff like if i have dns or something on. Funny enough, it was the time settings that caused that one. I had timetraveled for another game and and forgot to turn it back on automatic but it got fixed once i set time to automatic

**Comment by khanhduytran0** [comment]
> it got fixed
close moment

**Comment by VKGAMER31** [comment]
I also same problem how to fix please tell me 


1.Error
Chain validation failed

Error
Failed to download Minecraft!
This could be due to bad network
connection, incorrectly placed files,
etc.


How to fix
