### ISSUE TITLE
[BUG] Null Array With Custom Controls

### ISSUE THREAD

**Issue by JustinKyle11** [PojavLauncherTeam/PojavLauncher#2484]
### Describe the bug

Everytime i load or save an Custom control, it would show an error that would say "null array"

Video :
Uploading recording_20211231_014017.mp4…

screenshot :
![Screenshot_2021-12-31-01-40-45-522](https://user-images.githubusercontent.com/96884191/147775543-b049c4b0-05f2-4c83-b0e6-a7734d8ea0f8.jpeg)

heres the copy thing

java.lang.NullPointerException: Attempt to get length of null array
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:114)
	at com.kdt.pickafile.FileListView.init(FileListView.java:93)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:52)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:46)
	at com.kdt.pickafile.FileListView.<init>(FileListView.java:36)
	at net.kdt.pojavlaunch.CustomControlsActivity.load(CustomControlsActivity.java:215)
	at net.kdt.pojavlaunch.CustomControlsActivity$1.onNavigationItemSelected(CustomControlsActivity.java:60)
	at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:217)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:416)
	at android.view.View.performClick(View.java:7147)
	at android.view.View.performClickInternal(View.java:7120)
	at android.view.View.access$3500(View.java:804)
	at android.view.View$PerformClick.run(View.java:27538)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7405)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

PerformClick.run

MethodAndArgsCaller.run #

### The log file and images/videos

its at the top i think pls idk how to submit anything

### Steps To Reproduce

```markdown
im not sure i just happen to encounter this
```

### Expected Behavior

custom controls

### Platform

```markdown
- Device model: lenovo tab 8505x
- CPU architecture: not sure
- Android version: android 10
- PojavLauncher version: playstore or most recent
```

**Comment by JustinKyle11** [comment]
just ignore how i put it, im new

**Comment by GoneSubject** [comment]
this happen when you choose a control right?

**Comment by JustinKyle11** [comment]
yes, it happens nearly everytime i open "load" in custom controls

**Comment by GoneSubject** [comment]
> yes, it happens nearly everytime i open "load" in custom controls

welp to replace the new control with the old one you must press select default .json and choose the control, the load button is just for you to load a control to edit it so when you press save you will see your current control
 not the control you load

**Comment by JustinKyle11** [comment]
i need to edit default.json?

**Comment by GoneSubject** [comment]
> i need to edit default.json?

so you need to choose a control or you need to edit a control?

**Comment by JustinKyle11** [comment]
choose control

**Comment by GoneSubject** [comment]
> choose control

then do like this https://user-images.githubusercontent.com/95298052/147809683-0ef78df7-60d3-4448-8996-213f9245d364.mp4

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
