### ISSUE TITLE
Error or not on 2.5.1

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#249]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1053)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: java.io.IOException: Base resource not found: aha.class
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:32)
	... 9 more
Caused by: java.io.IOException: Base resource not found: aha.class
	at optifine.Patcher.applyPatch(Patcher.java:146)
	at optifine.Patcher.process(Patcher.java:90)
	at optifine.AndroidInstaller.installOptiFineLibrary(AndroidInstaller.java:56)
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:28)
	... 9 more

**Comment by khanhduytran0** [comment]
So did you downloaded target version first?

**Comment by Doxelix** [comment]
Yes, 1.11.2

**Comment by dawid5635** [comment]
Why I am author? What is this?

**Comment by khanhduytran0** [comment]
Did you tried other Optifine?

**Comment by Doxelix** [comment]
Yes, 1.8 and 1.9, but it doesn't work. When I run Optifine 1.11.2 it crashed but doesn't show I have optifine

PS. I speak polish

**Comment by khanhduytran0** [comment]
So what about other OptiFine version?

**Comment by khanhduytran0** [comment]
(other)

**Comment by Doxelix** [comment]
I dont know

**Comment by Doxelix** [comment]
Wait...

**Comment by khanhduytran0** [comment]
Meaning older version of Optifine target same version

**Comment by Doxelix** [comment]
1.7.10 too.

**Comment by Doxelix** [comment]
Not work :(

**Comment by Doxelix** [comment]
Wait? I have an idea for an application! Languages ​​such as Polish, English and so on

**Comment by khanhduytran0** [comment]
@dawid5635 Discord have problem now

**Comment by khanhduytran0** [comment]
About Polish translation: I will add later, current busying on build OpenJDK.

**Comment by ZloyDobrec** [comment]
У меня тоже такая проблема! Я все версии optifine пробывал для 1.11.2

**Comment by ZloyDobrec** [comment]
> Значение старой версии Optifine предназначено для той же версии

I have the same error I tried all versions of optifine for 1.11.2

**Comment by artdeell** [comment]
Best working OptiFine fpr 1.11.2 is B9 Ultra

**Comment by khanhduytran0** [comment]
@dawid5635 so now?

**Comment by khanhduytran0** [comment]
Reopen if you got same bug in 2.5.2+
