### ISSUE TITLE
Optifine 1.8????

### ISSUE THREAD

**Issue by BryleHelll** [PojavLauncherTeam/PojavLauncher#251]
Try playing optifine 1.8 on android 8.1 and this happened:
java.lang.reflect.InvocationTargetException

**Comment by khanhduytran0** [comment]
- Try other OptiFine revisions
- Try other Minecraft versions.
- Try another device.
(Some devices will not launch OptiFine)

**Comment by BryleHelll** [comment]
1.9+:
Unable to convert library optifine:launchwrapper-of:2.1
e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaHttp
[OkHttp] sendRequest>>
[OkHttp] sendRequest<<
java.lang.RuntimeException: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:508)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:566)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:32)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

UNEXPECTED TOP-LEVEL EXCEPTION:
java.io.FileNotFoundException: File doesn't exist: /storage/emulated/0/games/minecraft/libraries/optifine/launchwrapper-of/2.1/launchwrapper-of-2.1_orig.jar
	at java.util.zip.ZipFile.<init>(ZipFile.java:212)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.pojavdx.dx.command.dexer.Main.processOne(Main.java:682)
	at com.pojavdx.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.pojavdx.dx.command.dexer.Main.runMultiDex(Main.java:361)
	at com.pojavdx.dx.command.dexer.Main.runDx(Main.java:283)
	at com.pojavdx.dx.command.dexer.Main.main(Main.java:241)
	at com.pojavdx.dx.command.Main.main(Main.java:95)
	at net.kdt.pojavlaunch.Tools.runDx(Tools.java:341)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:584)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
1 error; aborting
Exiting with code 1

**Comment by BryleHelll** [comment]
1.7.2 or 1.7.10 Crash On Mojang logo 😞😞😞

**Comment by khanhduytran0** [comment]
> launchwrapper-of-2.1.jar

Did you read install wiki?

> 1.7.2 or 1.7.10 Crash On Mojang logo 😞😞😞

Maybe your device is not supported

**Comment by BryleHelll** [comment]
Wiki???

**Comment by BryleHelll** [comment]
Wikipedia 😆😆😆😆

**Comment by khanhduytran0** [comment]
No, but this one

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/wiki

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine

**Comment by BryleHelll** [comment]
Still crash

**Comment by BryleHelll** [comment]
Maybe add optifine support for android 8 devices.

**Comment by BryleHelll** [comment]
Nothing work!!!!!!

**Comment by BryleHelll** [comment]
Crash on logo

**Comment by BryleHelll** [comment]
All versions!!!!

**Comment by BryleHelll** [comment]
Maybe my device is not supported but have 1.40GB/3.00GB

**Comment by BryleHelll** [comment]
😞😞😞

**Comment by gabbosta** [comment]
try in version 2.5.1

**Comment by BryleHelll** [comment]
I play on 2.5.1

**Comment by gabbosta** [comment]
In mine it worked in 2.5.1

**Comment by khanhduytran0** [comment]
Known issue v2 some devices can't launch optifine.
