### ISSUE TITLE
Cant login with microsoft

### ISSUE THREAD

**Issue by MrTwixxy** [PojavLauncherTeam/PojavLauncher#2543]
### Describe the bug

My Pojavlauncher was woeking before but if after i updated my phone i cant login anymore:

I have minecraft for free with Xbox Gamepass ultimate but that shouldnt be the problem because it was working before 

### The log file and images/videos

java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
I click microsoft login and i login and it gived me this error
```

### Expected Behavior

I expert the game to login

### Platform

```markdown
- Device model: Samsung Galaxy A51 (SM-A515F/DSN)
- CPU architecture: I dont know where to find this
- Android version: 11
- PojavLauncher version:Latest Play Store Version
```

**Comment by GoneSubject** [comment]
welp the minecraft you get for free is in your Xbox account not your microsoft account

**Comment by MrTwixxy** [comment]
1. Thats the same, xbox is owned by microsoft and an xbox account is also just a microsoft account

2. Why was it working before then

**Comment by Starlii10** [comment]
Having similar issues. Don't know why MS can't just add the license to the MS account then check for that on an MS account, then use the same thing they're using for Mojang accounts.

**Comment by GoneSubject** [comment]
> 1. Thats the same, xbox is owned by microsoft and an xbox account is also just a microsoft account
> 2. Why was it working before then

did you linked your microsoft account with your xbox account?

**Comment by Starlii10** [comment]
> > 1. Thats the same, xbox is owned by microsoft and an xbox account is also just a microsoft account
> > 2. Why was it working before then
> 
> did you linked your microsoft account with your xbox account?

...It literally says that an Xbox account is just a Microsoft account. You need a Microsoft account to make an Xbox account.

**Comment by GoneSubject** [comment]
> > > 1. Thats the same, xbox is owned by microsoft and an xbox account is also just a microsoft account
> > > 2. Why was it working before then
> > 
> > 
> > did you linked your microsoft account with your xbox account?
> 
> ...It literally says that an Xbox account is just a Microsoft account. You need a Microsoft account to make an Xbox account.

so the microsoft you trying to login to is the microsoft account that you used to make xbox account?

**Comment by khanhduytran0** [comment]
> Why was it working before then

Did you login into Minecraft.net and set up a profile?

**Comment by MrTwixxy** [comment]
As i said it was all working before, i can also just play on the pc but on my phone its not working anymore for some reason

**Comment by mar4ello6** [comment]
Same thing
#2265

**Comment by PATIYO** [comment]
java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by ellaabjl** [comment]
my prolem is i cant login to my real account

**Comment by Blazej151** [comment]
T

**Comment by NAKL2KHGGKBOYTT** [comment]
java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by GaucovyAero** [comment]
> java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.
> 
> MSA Error: 404: Not Found, error stream: { "path" : "/minecraft/profile", "errorType" : "NOT_FOUND", "error" : "NOT_FOUND", "errorMessage" : "The server has not found anything matching the request URI", "developerMessage" : "The server has not found anything matching the request URI" } at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293) at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256) at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200) at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167) at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122) at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75) at net.kdt.pojavlaunch.authenticator.microsoft.Msa.(Msa.java:35) at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72) at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22) at android.os.AsyncTask$3.call(AsyncTask.java:394) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:923)

Hi, you have to set up a profile on minecraft.net first.

**Comment by nakkh302** [comment]
java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by NekonexDev** [comment]
Having similar issues. But i set up minecraft.net account

**Comment by PSRMAHAJA** [comment]
I have some similar  issue

**Comment by DeliriumxK** [comment]
I don't know if this will fix it for you guys but I signed in on (Default) - 1.7.10 and then tried to play the latest release and it worked.

**Comment by tomxzd** [comment]
I'm having the same issue:

```
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by KeceGezz** [comment]
Gimana mo login

**Comment by Flowerr4sr0** [comment]
so here i gave you an email
