### ISSUE TITLE
Can't open minecraft

### ISSUE THREAD

**Issue by Josef0929** [PojavLauncherTeam/PojavLauncher#2556]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.BaseMainActivity.initLayout(BaseMainActivity.java:145)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:26)
	at android.app.Activity.performCreate(Activity.java:7383)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
	at android.app.ActivityThread.-wrap12(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

### Steps To Reproduce

```markdown
Start minecraf
```

### Expected Behavior

Open minecraft

### Platform

```markdown
- Device model: idk
- CPU architecture: idk
- Android version: 8
- PojavLauncher version: idk
```

**Comment by khanhduytran0** [comment]
The custom controls layout is corrupted or not selected.
Also unspecified launcher version moment.

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
