### ISSUE TITLE
java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by windows715** [PojavLauncherTeam/PojavLauncher#2566]
### Describe the bug

 - Time: Jan 15, 2022 6:39:06 PM
 - Device: WAS-L03T WAS-L03T
 - Android version: 8.0.0
 - Crash stack trace:
 - Launcher version: crocus-v3_openjdk
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.FatalErrorActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
    at android.app.ActivityThread.-wrap12(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
    at android.app.Activity.onCreate(Activity.java:1081)
    at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
    at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:298)
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
    at net.kdt.pojavlaunch.FatalErrorActivity.onCreate(FatalErrorActivity.java:25)
    at android.app.Activity.performCreate(Activity.java:7383)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
    ... 9 more

### The log file and images/videos

 - Time: Jan 15, 2022 6:39:06 PM
 - Device: WAS-L03T WAS-L03T
 - Android version: 8.0.0
 - Crash stack trace:
 - Launcher version: crocus-v3_openjdk
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.FatalErrorActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
    at android.app.ActivityThread.-wrap12(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
    at android.os.Handler.dispatchMessage(Handler.java:108)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7529)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
    at android.app.Activity.onCreate(Activity.java:1081)
    at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
    at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:298)
    at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
    at net.kdt.pojavlaunch.FatalErrorActivity.onCreate(FatalErrorActivity.java:25)
    at android.app.Activity.performCreate(Activity.java:7383)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
    ... 9 more

### Steps To Reproduce

```markdown
launch 1.18
```

### Expected Behavior

i expect minecraft to load

### Platform

```markdown
- Device model: Huawei p10 lite
- CPU architecture: aarch64
- Android version: 8.0
- PojavLauncher version: not sure
```

**Comment by Mathias-Boulay** [comment]
Fixed in the release candidate build
