### ISSUE TITLE
Log into Microsoft account failure  add to child to family

### ISSUE THREAD

**Issue by LanUAriesEchos** [PojavLauncherTeam/PojavLauncher#2574]
### Describe the bug

When logging into a Microsoft account it gives me an error after putting in all my log in details and after the wait loading thing

### The log file and images/videos

java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
1. Start up app
2. Click Microsoft login
3. Log into your account 
4. Watch it load something 
5. Get the error
```

### Expected Behavior

I expect it to log me in to my Microsoft account

### Platform

```markdown
- Device model: galaxy z fold3 5g
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I have migrated my mojang account to a Microsoft account.

**Comment by LanUAriesEchos** [comment]
Please fix or help me please

**Comment by khanhduytran0** [comment]
> The account is a child (under 18) and cannot proceed unless the account is added to a Family by an adult.

**Comment by LanUAriesEchos** [comment]
How can my dad add it to his Microsoft account? as in add it to the family

**Comment by LanUAriesEchos** [comment]
He figured it out.
