### ISSUE TITLE
[BUG] Dose anyone have JRE 17 for x86_64 bit CPUS?

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2580]
### Describe the bug

I Can't Find A JRE that works, and the JRE I found is "corrupted"...

### The log file and images/videos

![image](https://user-images.githubusercontent.com/65428515/149998987-9bab1773-2ae7-471c-a9aa-ebf39ced045d.png)

[JRE Download](https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz)

Here is the logs:
```
org.tukaani.xz.XZFormatException: Input is not in the XZ format
	at org.tukaani.xz.common.DecoderUtil.decodeStreamHeader(Unknown Source:19)
	at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source:31)
	at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source:9)
	at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source:4)
	at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source:1)
	at org.tukaani.xz.SingleXZInputStream.<init>(Unknown Source:1)
	at org.apache.commons.compress.compressors.xz.XZCompressorInputStream.<init>(Unknown Source:13)
	at org.apache.commons.compress.compressors.xz.XZCompressorInputStream.<init>(Unknown Source:1)
	at net.kdt.pojavlaunch.multirt.MultiRTUtils.uncompressTarXZ(MultiRTUtils.java:213)
	at net.kdt.pojavlaunch.multirt.MultiRTUtils.installRuntimeNamed(MultiRTUtils.java:91)
	at net.kdt.pojavlaunch.BaseLauncherActivity.lambda$onActivityResult$2$BaseLauncherActivity(BaseLauncherActivity.java:269)
	at net.kdt.pojavlaunch.-$$Lambda$BaseLauncherActivity$ncugCop2_XO4hYWBTvgenl4I4KI.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
```

### Steps To Reproduce

```markdown
* Download the JRE
* Open Projav Launcher and Sign In
* Go to settings click "Runtime Manager"
* Click "Add New" and click the newly installed JVM
* Wait
* See Error
```

### Expected Behavior

FOR IT TO WORK!!!

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I'm on an Acer Chromebook With Intel Inside

**Comment by Errorbot1122** [comment]
**I also can't post this on the discord because discord is broken and won't let me verify my phone number**

*P.S: I already contacted support 👍*

**Comment by WesleyVanNeck** [comment]
https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/tag/jre17-ec28559

**Comment by WesleyVanNeck** [comment]
btw you have wrong pojav runtime

**Comment by WesleyVanNeck** [comment]
its for linux not android

**Comment by Errorbot1122** [comment]
OMG, THANK YOU SO MUCH @LegacyGamerHD 🥲 

For anyone seeing this with the same problem, [here's the like to the file](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-x86_64-20210825-release.tar.xz)
