### ISSUE TITLE
1.8.8 ares exited

### ISSUE THREAD

**Issue by BottomotPH29** [PojavLauncherTeam/PojavLauncher#2589]
### Describe the bug

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/20/22 4:58 AM
Description: Registering texture

java.lang.NullPointerException: Registering texture
	at net.minecraft.client.renderer.texture.TextureUtil.uploadTextureImageAllocate(TextureUtil.java:147)
	at net.minecraft.client.renderer.texture.SimpleTexture.loadTexture(SimpleTexture.java:63)
	at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:88)
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:55)
	at net.minecraft.client.renderer.ItemRenderer.func_178095_a(ItemRenderer.java:233)
	at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:388)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1019)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:964)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1902)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1532)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1328)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1394)
	at net.minecraft.client.Minecraft.run(Minecraft.java:442)
	at net.minecraft.client.main.Main.main(Main.java:113)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.uploadTextureImageAllocate(TextureUtil.java:147)
	at net.minecraft.client.renderer.texture.SimpleTexture.loadTexture(SimpleTexture.java:63)

-- Resource location being registered --
Details:
	Resource location: minecraft:
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:88)
	at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:55)
	at net.minecraft.client.renderer.ItemRenderer.func_178095_a(ItemRenderer.java:233)
	at net.minecraft.client.renderer.ItemRenderer.renderItemInFirstPerson(ItemRenderer.java:388)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:1019)
	at net.minecraft.client.renderer.EntityRenderer.renderHand(EntityRenderer.java:964)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1902)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1532)

-- Affected level --
Details:
	Level name: MpServer
	All players: 4 total; [EntityPlayerSP['XannXD'/108548, l='MpServer', x=0.18, y=110.00, z=2.95], EntityOtherPlayerMP['Roast_Gamerz'/108901, l='MpServer', x=2.03, y=110.00, z=-2.38], EntityOtherPlayerMP['huntergame'/109287, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['Bellakiyoo'/109397, l='MpServer', x=-1.13, y=110.00, z=1.69]]
	Chunk stats: MultiplayerChunkCache: 440, 440
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,110.00,0.00 - World: (0,110,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2568 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 12 total; [EntityPig['Pig'/105376, l='MpServer', x=35.28, y=83.00, z=-7.84], EntityOtherPlayerMP['huntergame'/109287, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['huntergame'/109287, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['huntergame'/109287, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['Roast_Gamerz'/108901, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['Roast_Gamerz'/108901, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['Bellakiyoo'/109397, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['Roast_Gamerz'/108901, l='MpServer', x=2.03, y=110.00, z=-2.38], EntityPlayerSP['XannXD'/108548, l='MpServer', x=0.18, y=110.00, z=2.95], EntityOtherPlayerMP['Bellakiyoo'/109397, l='MpServer', x=0.50, y=110.00, z=0.50], EntityOtherPlayerMP['Bellakiyoo'/109397, l='MpServer', x=-1.13, y=110.00, z=1.69], EntityChicken['Chicken'/105375, l='MpServer', x=38.19, y=79.99, z=3.25]]
	Retry entities: 0 total; []
	Server brand: Spigot (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:403)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:3105)
	at net.minecraft.client.Minecraft.run(Minecraft.java:463)
	at net.minecraft.client.main.Main.main(Main.java:113)

-- System Details --
Details:
	Minecraft Version: 1.8.8
	Operating System: Linux (aarch64) version Android-11
	CPU: <unknown>
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 839999968 bytes (801 MB) / 1109393408 bytes (1058 MB) up to 1109393408 bytes (1058 MB)
	JVM Flags: 3 total; -Xms1100M -Xmx1100M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: Ares
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: §2Yon§5Pack.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.8.8_HD_U_I7
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### The log file and images/videos

Bug

### Steps To Reproduce

```markdown
Bug
```

### Expected Behavior

Bug

### Platform

```markdown
- Device model: Galaxy A12 
- CPU architecture: Aarch64 
- Android version: android 11
- PojavLauncher version: 1.8.8 ares client
```

### Anything else?

Bug

**Comment by Mathias-Boulay** [comment]
custom client fuckury, not our problem.
Maybe fixed in the current release candidate
