### ISSUE TITLE
[BUG] Cannot login it with microsoft accounts.

### ISSUE THREAD

**Issue by greenhandzdl** [PojavLauncherTeam/PojavLauncher#2601]
### Describe the bug

It can't be  loginned

### The log file and images/videos

java.io.IOException: unexpected end of stream on com.android.okhttp.Address@2b1dc718
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:204)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	... 21 more

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Login Microsoft Accounts.
3.Error
```

### Expected Behavior

I Hope Game can be start normally.

### Platform

```markdown
- Device model: Huawei Matepad Pro
- CPU architecture: Qualcomm Snapdragon 870
- Android version: Harmony 2.0
- PojavLauncher version: The Newest
```

### Anything else?

No Other..

**Comment by khanhduytran0** [comment]
Check your internet connection.

**Comment by greenhandzdl** [comment]
> Check your internet connection.

My system show me 'good quality'
