### ISSUE TITLE
[Bug] crash when using a ps4 controller instantly.

### ISSUE THREAD

**Issue by Cpugog** [PojavLauncherTeam/PojavLauncher#2604]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setInt(java.lang.Object, int)' on a null object reference
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.setDummyEventKeycode(GamepadDpad.java:76)
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.convertEvent(GamepadDpad.java:67)
	at net.kdt.pojavlaunch.customcontrols.gamepad.Gamepad.update(Gamepad.java:158)
	at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:593)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:958)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processGenericMotionEvent(ViewRootImpl.java:7724)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7442)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6773)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6830)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6796)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6994)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6804)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7051)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6777)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6830)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6796)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6804)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6777)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6830)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6796)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7027)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7214)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3387)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2948)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2939)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3364)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

### The log file and images/videos

https://linksharing.samsungcloud.com/kHkoDdDVXHnx

### Steps To Reproduce

```markdown
I loaded 1.18.1 optifine with a ps4 controller connected started it up then while in main screen or in any screen press or push the analog on your ps4 controller and it instantly crashes the game.
```

### Expected Behavior

I expected to see that I was able to use a controller like I would on mobile but if you guys and girls can't fix this it's ok you have good enough to this community already.

### Platform

```markdown
- Device model: S21 plus/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version:[Latest Release || version v3.3.1.1]
```

**Comment by blackvampire231** [comment]
Having the same issue galaxy s20 fe 5g. Android 12. Insta crash when using any input on my xbox controller.

**Comment by WesleyVanNeck** [comment]
Version info not complete CPU architecture wrong that has to be arm or aarch64 or x86 or x86_64

**Comment by NotAHero04** [comment]
Try out GitHub builds, it should fix Android 12 support.

**Comment by Cpugog** [comment]
> Version info not complete CPU architecture wrong that has to be arm or aarch64 or x86 or x86_64

Thank you I didn't see that I just assumed.

**Comment by Cpugog** [comment]
> Try out GitHub builds, it should fix Android 12 support.

Everything works fine all the custom buttons and all that it's just the controller that crashes it but thank you.

**Comment by SprainedSpark89** [comment]
must not have enough memory

**Comment by SkySpnc** [comment]
happens when pressing any input on my xbox controller on my s20 ultra. pojav has about 7gb of ram to play around with, including its reservation of 2gb.

**Comment by KK4009** [comment]
When I  connect ps5 control, Minecraft always crash.
ROG Phone 5 
Android 12

**Comment by JoseDuvanGuzmanTorres** [comment]
happens the same with me, using a xiaomi redmi note 9s this doesnt happen but when i use my s20fe 5g it crashes when i press a buttom on the joystick

**Comment by Mathias-Boulay** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/2605
