### ISSUE TITLE
Cannot enter to games...

### ISSUE THREAD

**Issue by greenhandzdl** [PojavLauncherTeam/PojavLauncher#2606]
### Describe the bug

Black screen, then flashes back

### The log file and images/videos

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/23/22 11:10 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: org/lwjgl/util/mapped/CacheUtil
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/util/mapped/CacheUtil
	at mods.flammpfeil.slashblade.ItemRendererBaseWeapon.<init>(ItemRendererBaseWeapon.java:171)
	at mods.flammpfeil.slashblade.InitProxyClient.initializeItemRenderer(InitProxyClient.java:52)
	at mods.flammpfeil.slashblade.SlashBlade.preInit(SlashBlade.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.util.mapped.CacheUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 39 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2373973344 bytes (2263 MB) / 3405774848 bytes (3248 MB) up to 3405774848 bytes (3248 MB)
	JVM Flags: 2 total; -Xms3506M -Xmx3506M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 81 mods loaded, 81 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
	UCH	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCH	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCH	FoamFixCore{1.0.0-beta3} [FoamFixCore] (minecraft.jar) 
	UCH	foamfix{@VERSION@} [FoamFix] ([1.7.10]泡沫修复FoamFix-1.0.0-beta3-客户端.jar) 
	UCH	pozo{4.0.0} [梦境科技最终版] ([RPG贴图]pozo1.jar) 
	UCE	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] ([拔刀本体]SlashBlade-mc1.7.10-r87.jar) 
	UCE	flammpfeil.slashblade.exsa{mc1.7.10-r6} [SlashBlade-ExSa] ([云轮风暴]SlashBlade-ExSa-r6.jar) 
	UCH	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] ([和风]Bamboo.jar) 
	UCH	IC2{2.2.756-experimental} [IndustrialCraft 2] (【工业】industrialcraft-2-2.2.756-experimental.jar) 
	UCH	NoIC2Destruction{1.0.0} [No IC2 Destruction] ([工业2防爆]NoIC2Destruction-1.0.0-1.7.10.jar) 
	UCE	foxex{1.1.2} [FoxBlade Extra] ([拔��剑]-狐月刀改.jar) 
	UCE	flammpfeil.slashblade.zxsa{mc1.7.10-r5} [ZxSa] ([拔刀剑]SA技能.jar) 
	UCE	mrblade{1.0.1} [Technology Revolution Blade Extra] ([拔刀剑]TRblade技术革新v1.0.1.jar) 
	UCE	flammpfeil.nihil{mc1.7.x-r8} [Nihil] ([拔刀剑]【似蛭】Nihil-mc1.7.x-r8.jar) 
	UCH	balumg{1.0.0} [balumg] ([拔刀剑]【巴鲁蒙格】Balmung+1.7.10-r1.0-1.jar) 
	UCE	flammpfeil.slashblade.laemmle{mc1.7.10-r1} [Slashblade-Laemmle] ([拔刀剑]【幻魔炼金拵】Slashblade-Laemmle-mc1.7.10-r1.jar) 
	UCE	flammpfeil.slashblade.kirisaya{r1} [SlashBlade-Kirisaya] ([拔刀剑]【无神】SlashBlade-Kirisaya-r1.jar) 
	UCH	flammpfeil.toyako{mc1.7.2-r1} [toyako] ([拔刀剑]【洞爷湖】-toyako-mc1.7.2-r1.jar) 
	UCE	flammpfeil.fluorescentbar{mc1.7.2-r3} [fluorescentbar] ([拔刀剑]【荧光】-fluorescentbar-mc1.7.2-r3(1).jar) 
	UCE	ND{r3} [ND] ([拔刀剑]拔刀剑附属-不正经的剑-r3.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (��神秘时代】M-Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCE	flammpfeil.slashblade.zephyr{1.7.2 r1.2} [SlashBladeZephyr] ([拔刀剑]风雷太刀r1.2.2.jar) 
	UCE	flammpfeil.slashblade.splight{r5} [SlashBlade-SPLight] ([拔刀剑]龙一文字.jar) 
	UCH	exnihilo{1.38-53} [Ex Nihilo] ([无中生有]Ex-Nihilo-1.38-53.jar) 
	UCH	armourersWorkshop{1.7.10-0.48.3} [Armourer's Workshop] ([时装工坊]1.7.10-0.48.3.jar) 
	UCH	exastris{MC1.7.10-1.16-36} [Ex Astris] ([星辉万物]Ex-Astris-MC1.7.10-1.16-36.jar) 
	UCH	Forestry{4.2.16.64} [Forestry for Minecraft] ([林业]Forestry.jar) 
	UCH	PTRModelLib{1.0.0} [PTRModelLib] ([装饰品]mckuai1.7.10Decocraft-2.4.2mod.jar) 
	UCH	props{2.4.2} [Decocraft] ([装饰品]mckuai1.7.10Decocraft-2.4.2mod.jar) 
	UCH	YoHern{2.1.0} [YoHern] ([贴图]YoHern's RPG items.jar) 
	UCH	ChunkAnimator{@VERSION@} [Chunk Animator] ([辅助-区块加载优化].jar) 
	UCH	UnicodeFontFixer{1.1.12-mc1.7.10} [UnicodeFontFixer] (D-Fix-UnicodeFontFixer-1.1.12.jar) 
	UCH	Dynmap{2.4-169} [Dynmap] (Dynmap-2.4-forge-1.7.10.jar) 
	UCH	FpsReducer{1.0} [FPS Reducer] (FPS_excellent.jar) 
	UCH	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mcmap.cc-[战备双持MOD][1.7.10].jar) 
	UCH	AencEx{0.0.1} [AencEx] (mcmap.cc-[更多的附魔MOD][1.7.10].jar) 
	UCH	me{1.3.2.1} [More Enchantments] (mcmap.cc-[更多的附魔MOD][1.7.10].jar) 
	UCH	bikesystem{1.0} [bikesystem] (mod3.jar) 
	UCH	BANK-ONEPIECE BLOCK3D{Takakung} [Takakung BLOCK3D] (mod3.jar) 
	UCH	chillingmoneysystem{1.0} [ChillingMoneySystem] (mod3.jar) 
	UCH	PIXEL-STATION{Takakung} [PIXEL-STATION] (mod3.jar) 
	UCH	PIXEL-STATION 3D{Takakung} [PIXEL-STATION 3D] (mod3.jar) 
	UCH	shopplayers{1.7.10} [CubeMMOShop] (mod3.jar) 
	UCH	customnpcs{1.7.10d} [CustomNpcs] (NPC服务器mod[正常版].jar) 
	UCH	AdvNPCs{BWv2} [AdvNPCs] (NPC服务器mod[正常版].jar) 
	UCH	alluwant{2.1} [背包物品编辑器] (op用的【可删】.jar) 
	UCH	rpghud{2.5.1} [RPG Hud] (RPG界面rpgfgjmMOD.jar) 
	UCE	flammpfeil.slashblade.blademaster{mc1.7.2-r1} [BladeMaster] (【剑圣����刃】BladeMaster-mc1.7.2-r1.2.jar) 
	UCH	Botania{r1.8-249} [Botania] (植物魔法Botania r1.8-249.jar) 
	UCE	flammpfeil.slashblade.terra{mc1.7.10-r1} [SlashBlade-Terra] (【大地之刃】SlashBlade-Terra-mc1.7.10-r1.jar) 
	UCH	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (【太阳能】AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) 
	UCE	flammpfeil.darkraven{mc1.7.2-r2} [DarkRaven] (【暗鸦】DarkRaven-mc1.7.2-r2.jar) 
	UCH	TwilightForest{2.3.7} [The Twilight Forest] (【暮色】twilightforest-1.7.10-2.3.7.jar) 
	UCH	craftSaddle{2.0} [Craft Saddle] (【物品修复】craftSaddle-1.7.10.0.2.jar) 
	UCH	creativecore{1.3.14} [CreativeCore] (【真实掉落依赖】CreativeCore-1.7.10-v1.3.24.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (【矿石箱子】ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (【神秘工匠】ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCH	MoreBows2{1.0.1} [More Bows 2] (【通过】更多弓.jar) 
	UCH	NotEnoughWands{1.2.3} [Not Enough Wands] (【通过】更多魔杖.jar) 
	UCH	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (【重力装甲】GraviSuite-1.7.10-2.0.3.jar) 
	UCE	Pseudo{1.0.0} [Pseudo] (伪刃.jar) 
	UCE	slashblade.yukari{mc1.7.10-r2} [Yukari] (拔刀剑-结月刀改r2.jar) 
	UCE	flammpfeil.slashblade.kamuy{mc1.7.10-r6} [Kamuy] (拔刀剑mckuai1.7 (1).jar) 
	UCE	flammpfeil.slashblade.wanderer{mc1.7.2-r1} [SlashBladeWanderer] (拔刀剑mckuai1.7 (3).jar) 
	UCH	MSM3{3.0.0a} [More Swords 3] (更多的剑youxigt_mc1.7.10gengduojianMOD.jar) 
	UCH	Backpack{2.0.1} [Backpack] (更多背包.jar) 
	UCH	BetterSprinting{1.1.3} [Better Sprinting] (更好的冲刺1.7.10Better-Sprinting-Mod.jar) 
	UCH	betterrain{0.15} [Better Rain] (更真实的雨betterrain-1.7.2-1.7.10_0.15.jar) 
	UCH	myitem3d{1.0} [Myitem3d] (武器[适合RPG].jar) 
	UCH	tnb_gildedarmor{1.1} [TNB Gilded Armor] (氪金盔甲TNB_GildedArmor_1.7.10_1.1-CN.jar) 
	UCH	tnbcraftingrecipes{1.0} [TNB Useful Crafting Recipes] (氪金盔甲TNB_GildedArmor_1.7.10_1.1-CN.jar) 
	UCH	nshowmod{1.1} [nshowmod] (玩家数值血量显示.jar) 
	UCH	custom_sword{1.7.10} [Custom Sword  By Kelco_K22] (组装武器custom_sword_1.7.10_V0.14.jar) 
	UCH	shouldersurfing{1.0} [ShoulderSurfing] (肩上视角-1.7.10.jar) 
	UCH	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (自定义标题BetterTitleScreen-1.7.10-1.1.jar) 
	UCH	mfw{2.1.0} [Mine Ferris Wheel] (观览车1.7.10MineFerrisWheel-2.1.0s光影兼容兼容.jar) 
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
1.Start PoJavlauncher
2.Load Forge(1.7.10-10.13.4.1614)
3.Mv mods to Mods Files
4.Enter games
```

### Expected Behavior

Can enter it normally.

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
(The logs have been described)
```

**Comment by WesleyVanNeck** [comment]
platform info is invalid

**Comment by greenhandzdl** [comment]
Device Name:Huawei MatePad Pro
CPU:Qualcomm Snapdragon 870
Version: Harmony 2.0
PoJavlauncher: newest

**Comment by greenhandzdl** [comment]
mods error
