### ISSUE TITLE
[BUG] 1.18.1 debug crash with error code -1

### ISSUE THREAD

**Issue by 51nya51** [PojavLauncherTeam/PojavLauncher#2654]
### Describe the bug

1.18.1 optifine crash

### The log file and images/videos

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 30.01.2022, 16:42
Description: Initializing game

java.lang.IllegalStateException: could not preload shader rendertype_text
	at epe.a(GameRenderer.java:465)
	at epe.a(GameRenderer.java:451)
	at dxo.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: yk: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:23: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at yk.a(SourceFile:48)
	at epw.<init>(ShaderInstance.java:225)
	at epw.<init>(ShaderInstance.java:103)
	at epe.a(GameRenderer.java:459)
	... 9 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:23: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at dry.b(Program.java:94)
	at dry.a(Program.java:55)
	at epw.a(ShaderInstance.java:269)
	at epw.<init>(ShaderInstance.java:198)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.a(GameRenderer.java:465)
	at epe.a(GameRenderer.java:451)
	at dxo.<init>(SourceFile:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2517097112 bytes (2400 MiB) / 3607101440 bytes (3440 MiB) up to 3607101440 bytes (3440 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x002 Stepping r0x0p1
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5351,52
	Virtual memory used (MB): 6465,20
	Swap memory total (MB): 2560,00
	Swap memory used (MB): 1454,21
	JVM Flags: 2 total; -Xms3440M -Xmx3440M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 8x 
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.start minecraft 1.18.1 optifine
3.crash with code -1
```

### Expected Behavior

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 30.01.2022, 16:42
Description: Initializing game

java.lang.IllegalStateException: could not preload shader rendertype_text
	at epe.a(GameRenderer.java:465)
	at epe.a(GameRenderer.java:451)
	at dxo.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: yk: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:23: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at yk.a(SourceFile:48)
	at epw.<init>(ShaderInstance.java:225)
	at epw.<init>(ShaderInstance.java:103)
	at epe.a(GameRenderer.java:459)
	... 9 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:23: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at dry.b(Program.java:94)
	at dry.a(Program.java:55)
	at epw.a(ShaderInstance.java:269)
	at epw.<init>(ShaderInstance.java:198)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.a(GameRenderer.java:465)
	at epe.a(GameRenderer.java:451)
	at dxo.<init>(SourceFile:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2517097112 bytes (2400 MiB) / 3607101440 bytes (3440 MiB) up to 3607101440 bytes (3440 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x002 Stepping r0x0p1
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5351,52
	Virtual memory used (MB): 6465,20
	Swap memory total (MB): 2560,00
	Swap memory used (MB): 1454,21
	JVM Flags: 2 total; -Xms3440M -Xmx3440M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 8x 
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### Platform

```markdown
- Device model: samsung galaxy note 10 lite
- CPU architecture: 64
- Android version: 11
- PojavLauncher version: [latest debug || version 3 ]
```

### Anything else?

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 30.01.2022, 16:42
Description: Initializing game

java.lang.IllegalStateException: could not preload shader rendertype_text
	at epe.a(GameRenderer.java:465)
	at epe.a(GameRenderer.java:451)
	at dxo.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: yk: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:23: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at yk.a(SourceFile:48)
	at epw.<init>(ShaderInstance.java:225)
	at epw.<init>(ShaderInstance.java:103)
	at epe.a(GameRenderer.java:459)
	... 9 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:23: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at dry.b(Program.java:94)
	at dry.a(Program.java:55)
	at epw.a(ShaderInstance.java:269)
	at epw.<init>(ShaderInstance.java:198)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at epe.a(GameRenderer.java:465)
	at epe.a(GameRenderer.java:451)
	at dxo.<init>(SourceFile:617)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2517097112 bytes (2400 MiB) / 3607101440 bytes (3440 MiB) up to 3607101440 bytes (3440 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x002 Stepping r0x0p1
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5351,52
	Virtual memory used (MB): 6465,20
	Swap memory total (MB): 2560,00
	Swap memory used (MB): 1454,21
	JVM Flags: 2 total; -Xms3440M -Xmx3440M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 8x 
	OptiFine Version: OptiFine_1.18.1_HD_U_H4
	OptiFine Build: 20211212-175054
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by 51nya51** [comment]
I fix it
