### ISSUE TITLE
[BUG] App Start Err

### ISSUE THREAD

**Issue by muyunil** [PojavLauncherTeam/PojavLauncher#2665]
### Describe the bug

Install the latest test version, open the software to automatically install jre, then close the software, and report an error when opening it again.

### The log file and images/videos

java.io.IOException: Success
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1006)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:699)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:707)
	at net.kdt.pojavlaunch.customcontrols.CustomControls.save(CustomControls.java:66)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:335)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:72)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitRunnable._start(PojavLoginActivity.java:148)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitRunnable.run(PojavLoginActivity.java:170)
	at java.lang.Thread.run(Thread.java:920)

### Steps To Reproduce

```markdown
Install the latest test version, open the software to automatically install jre, then close the software, and report an error when opening it again.
```

### Expected Behavior

No Err

### Platform

```markdown
- Device model: RMX3366 8/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: latest
```

**Comment by muyunil** [comment]
![Screenshot_2022-02-03-19-55-19-02_67a64f1fc1b88908dad3392f76c1969b](https://user-images.githubusercontent.com/57998963/152338444-183dfcb9-38e4-49b7-b25b-9b443a6c3b31.jpg)

**Comment by muyunil** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8004561/latestlog.txt)
