### ISSUE TITLE
Game crashes when I go into 1.18.1

### ISSUE THREAD

**Issue by CharredMist** [PojavLauncherTeam/PojavLauncher#2683]
### Describe the bug

When I open 1.18.1 and go into a world/server, game crashes with no error in a minute.

### The log file and images/videos

--------- beggining with launcher debug
Info: Launcher version: crocus-v3_openjdk
Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.18.1
--------- beginning of main
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~R8M2UZSsErV3QGpnQCROpg==/net.kdt.pojavlaunch-4wXsa7vwFDYeRdTb-vveiw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3
Added custom env: LIBGL_ES=3
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Aug 18 2021 16:47:47
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_draw_buffers is in core ES3, and so used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Max Color Attachments: 8 / Draw buffers: 8
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
Targeting OpenGL 2.1
NPOT texture handled in hardware
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  (32634): dlopen libgl4es_115.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjli.so success
I/jrelog  (32634): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/server/libjvm.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libverify.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjava.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libnet.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libnio.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libawt.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libawt_headless.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libfreetype.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libfontmanager.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libawt.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/server/libjvm.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/server/libjsig.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libattach.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjavajpeg.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libsyslookup.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libfontmanager.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libj2pcsc.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libmanagement.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjaas.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libfreetype.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjli.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjimage.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjsig.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libj2gss.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libnet.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjava.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libnio.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libprefs.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libmanagement_ext.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libj2pkcs11.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libdt_socket.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjdwp.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libzip.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libsctp.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libmlib_image.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libextnet.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libinstrument.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libmanagement_agent.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/librmi.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/liblcms.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libjawt.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libverify.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libawt_headless.so success
I/jrelog  (32634): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/libawt_xawt.so success
I/jrelog  (32634): dlopen /data/app/~~R8M2UZSsErV3QGpnQCROpg==/net.kdt.pojavlaunch-4wXsa7vwFDYeRdTb-vveiw==/lib/arm64/libopenal.so success
I/jrelog  (32634): Done processing args
I/jrelog  (32634): Found JLI lib
I/jrelog  (32634): Calling JLI_Launch
[13:57:21] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:57:21] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:57:21] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:57:21] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:57:24] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:132) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:44) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:153) ~[authlib-3.2.38.jar:?]
	at dxo.a(SourceFile:670) [1.18.1.jar:?]
	at dxo.<init>(SourceFile:424) [1.18.1.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:199) [1.18.1.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:78) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.2.38.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:113) ~[authlib-3.2.38.jar:?]
	... 5 more
[13:57:24] [Render thread/INFO]: Setting user: ErenProo1665
[13:57:25] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=4713
EGLBridge: EGLDisplay=0x1, EGLSurface=0x7b36335850
EGLBridge: Created CTX pointer = 0x7b36335bb0
[13:57:25] [Render thread/INFO]: [STDERR]: java.lang.Exception: Trace exception
[13:57:25] [Render thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwMakeContextCurrent(GLFW.java:1004)
[13:57:25] [Render thread/INFO]: [STDERR]: 	at drp.<init>(SourceFile:106)
[13:57:25] [Render thread/INFO]: [STDERR]: 	at eqa.a(SourceFile:21)
[13:57:25] [Render thread/INFO]: [STDERR]: 	at dxo.<init>(SourceFile:476)
[13:57:25] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:199)
EGLBridge: Comparing: thr=4713, this=0x7b36335bb0, curr=0x0
EGLBridge: Making current on window 0x7b36335bb0 on thread 4713
EGLBridge: eglMakeCurrent() succeed!
[13:57:25] [Render thread/INFO]: [STDOUT]: 7b36335bb0
EGLBridge: Comparing: thr=4713, this=0x7b36335bb0, curr=0x7b36335bb0
[13:57:26] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible
[13:57:28] [Render thread/WARN]: ERROR : Couldn't load Narrator library : /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna4460751736764943258.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna4460751736764943258.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar(2).xz/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
[13:57:29] [Render thread/INFO]: Reloading ResourceManager: Default, assets-v0.zip, assets-v8.zip
[13:57:33] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[13:57:56] [Render thread/INFO]: OpenAL initialized on device OpenSL
[13:57:56] [Render thread/INFO]: Sound engine started
[13:57:58] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[13:57:58] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[13:57:58] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[13:57:58] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[13:57:58] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[13:57:58] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[13:57:58] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:58:02] [Render thread/WARN]: Shader rendertype_text could not find sampler named Sampler2 in the specified shader program.
[13:58:02] [Render thread/WARN]: Shader rendertype_text_intensity could not find sampler named Sampler2 in the specified shader program.
[13:58:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:58:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:58:04] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:58:22] [Render thread/INFO]: Reloading ResourceManager: Default, assets-v8.zip, assets-v0.zip
[13:58:32] [Render thread/INFO]: OpenAL initialized on device OpenSL
[13:58:32] [Render thread/INFO]: Sound engine started
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[13:58:33] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[13:58:33] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/signs.png-atlas
[13:58:33] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[13:58:33] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[13:58:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[13:58:33] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[13:58:33] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[13:58:35] [Render thread/WARN]: Shader rendertype_text could not find sampler named Sampler2 in the specified shader program.
[13:58:35] [Render thread/WARN]: Shader rendertype_text_intensity could not find sampler named Sampler2 in the specified shader program.
[13:58:36] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[13:58:36] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[13:58:36] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[13:58:55] [Render thread/INFO]: Connecting to ServerWithDeathBan.aternos.me, 53763
[13:58:58] [Server Connector #1/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 8e:04:23:62:ad:b8:62:41
[13:59:33] [Render thread/INFO]: Connecting to ServerWithDeathBan.aternos.me, 53763
[13:59:38] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:59:45] [Render thread/INFO]: [CHAT] ErenProo1665 oyuna katıldı(this means joined to game)
[13:59:45] [Render thread/INFO]: Loaded 0 advancements
--------- beginning of crash

### Steps To Reproduce

```markdown
1 start launcher
2 open 1.18.1
3 go into a server
4 wait one or two minutes
```

### Expected Behavior

Game crashes with no error and goes to the login screen

### Platform

```markdown
- Device model: Samsung Galaxy a71/128G
- CPU architecture: arm64
- Android version: Android 11
- PojavLauncher version: Latest release (crocus-v3_openjdk),(playstore)
```

**Comment by SprainedSpark89** [comment]
when it says game exited without exiting it doesn't think it's a crash

**Comment by khanhduytran0** [comment]
Try disabling clouds before playing.

**Comment by CharredMist** [comment]
> Try disabling clouds before playing.

Ok

**Comment by CharredMist** [comment]
> Try disabling clouds before playing.

Datapacks should look like this right?
![Screenshot_20220207-231309_PojavLauncher (Minecraft Java Edition for Android).jpg](https://user-images.githubusercontent.com/89633652/152864551-9fa4e47c-dde1-4f8c-ac7b-6805184960fd.jpg)
(Sorry for different language, I am Turkish)

**Comment by CharredMist** [comment]
> Try disabling clouds before playing.

It didnt work it crashes over and over again

**Comment by CharredMist** [comment]
I just resetted PojavLauncher and its working properly
