### ISSUE TITLE
[BUG] rendering overlay ??

### ISSUE THREAD

**Issue by Finluxian** [PojavLauncherTeam/PojavLauncher#2710]
### Describe the bug

i just wanted to play 1.18.1 when i try to start game crush (sorry for bad english)

### The log file and images/videos

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 8.02.2022 15:22
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at epe.b(SourceFile:497)
	at epe.a(SourceFile:385)
	at afl.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at afp.a(SourceFile:71)
	at auh.execute(SourceFile:101)
	at afp.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. select 1.18.1 (release)
3. start the game
4. crush
```

### Expected Behavior

I expected game to start

### Platform

```markdown
- Device model: Poco X3 Pro
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest release
```

**Comment by Finluxian** [comment]
nevermind, i solved
