### ISSUE TITLE
[BUG] Can't play MC Java with some RAM and storage spacee

### ISSUE THREAD

**Issue by AURezo** [PojavLauncherTeam/PojavLauncher#2720]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8037682/latestlog.txt)

### Steps To Reproduce

```markdown
Start PojavLauncher.
Select version if wanted.
Click Play. 
Bug will happen.
```

### Expected Behavior

Expected the game to download and launch.

### Platform

```markdown
- Device model: vivo 1714
- CPU architecture: 1.5GHz Octa-Core
- Android version: 7.0
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by khanhduytran0** [comment]
This is a random issue, try launching the game again.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
