### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by fantom12403** [PojavLauncherTeam/PojavLauncher#2729]
### Describe the bug

Не устанавливается майнкрафт варила и из-за этого не работает фордж

### The log file and images/videos

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:215)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:145)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:61)
	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:397)
	at java.io.InputStream.read(InputStream.java:101)
	at net.kdt.pojavlaunch.Tools.downloadFileMonitored(Tools.java:736)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:174)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
1) Я запустил pojavlauncher
2) зашёл в учётную запись онлайн или оффлайн
3) начал установку Майнкрафт  1.7.10
4) произошла ошибка из-за которой майнкрафт не установился
5) попробовал другую версию таже самая проблема
6) проделал всё что можно было переустанавливал лаунчер, чистил все данные папки лаунчера ни чего не помогло.
```

### Expected Behavior

Я ожидал что Майнкрафт установится и будит работать но произошла ошибка с установкой.

### Platform

```markdown
- Device model: Самсунг а12
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: crocus_v3_openjdk
```

### Anything else?

У меня произошла ошибка лаунчере pojavlauncher в версии crocus_v3_openjdk не устанавливается версии Майнкрафта при полном соединении интернета все установки стали похожи как на пк фордж не установить без чистой версии из лаунчера и это ладно, но что делать с установкой Майнкрафт из лаунчера не устанавливается установка останавливается по середине и некуда не идёт всё уже перепробовал а если установилось всё-таки то не работает фордж с модами всегда ошибка приложения с кодом 1, сколько не пробовал и до сих пор пробую не получается ни чего. Подскажите что мне делать или как это исправить. Со старыми версиями таже проблема.

**Comment by villager1314** [comment]
не могу читать по-русски

**Comment by fantom12403** [comment]
Sorry I didn't know, I'll translate it now. Minecraft has not been installed, and because of this, forge does not work.
1) I launched pojavlauncher 2) logged into an online or offline account 3) started installing Minecraft 1.7.10 4) an error occurred due to which minecraft was not installed 5) tried another version of the same problem 6) did everything that could be reinstalled.
I expected Minecraft to install and start working, but there was an error with the installation.

Platform

- Device model: Samsung a12 - CPU architecture: aarch64 - Android version: 11 - PojavLauncher version: crocus_v3_openjdk

Anything else?

I had an error in the pojavlauncher launcher in the crocus_v3_openjdk version, the Minecraft version is not installed with a full Internet connection, all installations have become similar to a pc forge cannot be installed without a clean version from the launcher and that's fine, but what to do with installing Minecraft from the launcher, the installation does not install, stops in the middle and there is nowhere to go, everything has already been tried and if it is installed, then the forge with mods always does not work, the application error with code 1, how many have not tried and still try, it does not work . Tell me what to do or how to fix it. The old versions have the same problem.

**Comment by SprainedSpark89** [comment]
you have to first press play on minecraft version that is the same version as forge version you want then you go to https://files.minecraftforge.net/net/minecraftforge/forge/ then select the version then download then install forge
if you don't know how to choose a version you tap the version

**Comment by fantom12403** [comment]
Thanks, but I know how to install I just All the time stops at the same place I from above I brought the error code that I have and the Internet is stable and I don't know why the installation of Minecraft is not roosting, but how to install forge or Mine itself, I know I've been playing podzhavlauncher for 3 years and the error appeared with downloading for the first time

**Comment by SprainedSpark89** [comment]
is it from forge or pojavlauncher?

**Comment by fantom12403** [comment]
well, in general, I went in and Main chose the version and it is not installed, and the forge is possible.

**Comment by SprainedSpark89** [comment]
then install the main version first

**Comment by fantom12403** [comment]
У I don't have vanilla versions installed at all

**Comment by SprainedSpark89** [comment]
it needs them as a version to copy then modify same if you try installing optifine but it gives you a error that says it.

**Comment by fantom12403** [comment]
https://youtu.be/Ud-tuV07_EM in the video on this link, I showed my mistake of not installing Minecraft versions in the launcher

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
