### ISSUE TITLE
Minecraft 1.8 crashes when joining Hypixel

### ISSUE THREAD

**Issue by RadiatedExodus** [PojavLauncherTeam/PojavLauncher#273]
![Screenshot_20200809-122408_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/30568955/89726039-52321f00-da40-11ea-91ec-c968fe1c765c.png)
Minecraft 1.8 crashes when joining Hypixel, yes I am using a premium account, joining using 1.11 is fine however.

Crash log:
`
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 8/9/20 12:24 PM
Description: Rendering item

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at cjd.a(SourceFile:52)
	at cqh.a(SourceFile:119)
	at cqh.a(SourceFile:335)
	at cqh.b(SourceFile:371)
	at btz.a(SourceFile:878)
	at btz.a(SourceFile:334)
	at btz.a(SourceFile:142)
	at cji.b(SourceFile:1002)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1015)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at cvx.a(SourceFile:47)
	at cvx.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at cvw.a(SourceFile:124)
	at cnw.a(SourceFile:76)
	at cjd.a(SourceFile:52)
	at cqh.a(SourceFile:119)

-- Item being rendered --
Details:
	Item Type: anh@c0906bb
	Item Aux: 3
	Item NBT: {SkullOwner:{Id:"681af1a4-f650-4b2e-9cdf-509f5223e450",Properties:{textures:[0:{Signature:"GnLmY3LZGPkrQMWZJnHZvwpCzXEfjtLV4PBMF0wH4k0kDai2ZdgKIWTSLJEH9hMa6nOGxS3EUsmIzyqVyzbkNG3PFFVB2X0gYQyz9eh8Z2Zjx1ky+l41gnhcio1bZX2BNwdA1lnXRQvzHZAa+KAgXEW+ExF+u5L2HAdEMF5J8cv+rwPIGscYQEU9MemAjH4wimNZbOLCdrqao3EHYTgsMvUMIdzS0oT3fp717/3OrKf8BP9ENz66QyG00Pljalsh9qThLhyP+m44N+8TzSxJQxfIsuBSg7JRLgGQXjBQcYvOOGewqegZFU8LJaJi62tzGF9qcJX4vdVtBzGpdeOmSabeCk1ZpKK3IlpK2IkjFeuMrQ57798cAUf3W9gWYFEzyScB+DsHNuDoSm7CQyMUCQDlrNUWwXjuvVgsTbqaRNhCj5Irjaw9Kg8yDlbtj5VBa5Y/1O4hb3he1gVM6xVq+t5mIO9Tikuu8pNF05BHmQWYzdfBjKBgxSOJxxfYooBNG9C5hZktCG9u3Di/DgF5oTxp7YkndfmVAnEei/wjNqWRuaSda9sFJAi2vfYaCBFqw37W1QViZFZRlLouQi1p1KzP1hkN7EwRLFdZJvmJXO/PrIiOtyHEiEbiJWX+pYq88fWjctTxppwrx2bThKSR0YQIL35HtUdBJB6PN74/BKA=",Value:"ewogICJ0aW1lc3RhbXAiIDogMTU5Njk1MDYzODQ5MiwKICAicHJvZmlsZUlkIiA6ICI2ODFhZjFhNGY2NTA0YjJlOWNkZjUwOWY1MjIzZTQ1MCIsCiAgInByb2ZpbGVOYW1lIiA6ICJSZWFsRXRoYW5QbGF5eiIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iZWYzNWZhZDJjOTkyOTUwN2ExODM1MjhiNGY4MDlhZDY2Y2E5ZDljMjlmMjY5YWI2MDQ2NmYwODM4MTFiNmE4IgogICAgfQogIH0KfQ==",},],},Name:"RealEthanPlayz",},display:{Lore:[0:"§7§7Right-click to browse quests, view achievements,",1:"§7activate Network Boosters and more!",],Name:"§aMy Profile §7(Right Click)",},}
	Item Foil: false
Stacktrace:
	at b.a(SourceFile:244)
	at cqh.b(SourceFile:374)
	at btz.a(SourceFile:878)
	at btz.a(SourceFile:334)
	at btz.a(SourceFile:142)
	at cji.b(SourceFile:1002)
	at bsu.as(SourceFile:903)
	at bsu.a(SourceFile:314)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1015)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:919)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [cio['RealEthanPlayz'/564672, l='MpServer', x=-150.21, y=69.00, z=149.77]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -151.00,69.00,149.00 - World: (-151,69,149), Chunk: (at 9,4,5 in -10,9; contains blocks -160,0,144 to -145,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 26 game time, 26 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [cio['RealEthanPlayz'/564672, l='MpServer', x=-150.21, y=69.00, z=149.77]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (Hypixel) <- vanilla
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Linux (armv8l) version 4.14.113-18770262
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-A515F, Android 10), The Android Project
	Memory: 21430272 bytes (20 MB) / 190259696 bytes (181 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
`

**Comment by RadiatedExodus** [comment]
I just realised this was something to do with Base64 encoding?

**Comment by khanhduytran0** [comment]
That bug is very common and there's a way to fix

**Comment by khanhduytran0** [comment]
First let's look to `/sdcard/games/minecraft/libraries/com/google/guava`

**Comment by RadiatedExodus** [comment]
![Screenshot_20200809-130407_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/30568955/89726102-e43a2780-da40-11ea-9cd9-bd5d9ffcdb72.png)
1.11.2 joining Hypixel works

**Comment by khanhduytran0** [comment]
> First let's look to `/sdcard/games/minecraft/libraries/com/google/guava`

Then copy latest version of Guava to older one, override them

**Comment by RadiatedExodus** [comment]
> > First let's look to `/sdcard/games/minecraft/libraries/com/google/guava`
> 
> Then copy latest version of Guava to older one, override them

Got it! I'll try.

**Comment by RadiatedExodus** [comment]
> > First let's look to `/sdcard/games/minecraft/libraries/com/google/guava`
> 
> Then copy latest version of Guava to older one, override them

Opening the folder, theres another folder named guava, opening that gives me 2 folder, 17.0 and 21.0 , should I extract the content on 17.0?

**Comment by RadiatedExodus** [comment]
Also inside both folders has a jar file

**Comment by RadiatedExodus** [comment]
Nope, can't get it to work...

**Comment by khanhduytran0** [comment]
Use v3 to fix this issue
