### ISSUE TITLE
[BUG] <game exited (1.18.1)>

### ISSUE THREAD

**Issue by zdavreal** [PojavLauncherTeam/PojavLauncher#2752]
### Describe the bug

black screen and crash

### The log file and images/videos

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2/18/22, 5:14 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: no extnet in system library path: /data/data/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:814)
	at java.base/java.lang.System.loadLibrary(System.java:1948)
	at jdk.net/jdk.net.LinuxSocketOptions.<clinit>(LinuxSocketOptions.java:130)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.newInstance(ExtendedSocketOptions.java:352)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.create(ExtendedSocketOptions.java:368)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.<clinit>(ExtendedSocketOptions.java:376)
	at jdk.net/jdk.net.ExtendedSocketOptions.<clinit>(ExtendedSocketOptions.java:203)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/sun.net.ext.ExtendedSocketOptions.getInstance(ExtendedSocketOptions.java:178)
	at java.base/sun.nio.ch.Net.<clinit>(Net.java:388)
	at java.base/sun.nio.ch.NioSocketImpl.create(NioSocketImpl.java:466)
	at java.base/java.net.DelegatingSocketImpl.create(DelegatingSocketImpl.java:74)
	at java.base/java.net.Socket.createImpl(Socket.java:530)
	at java.base/java.net.Socket.connect(Socket.java:632)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:65)
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:113)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:44)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:153)
	at dxo.a(SourceFile:670)
	at dxo.<init>(SourceFile:424)
	at net.minecraft.client.main.Main.main(SourceFile:199)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:814)
	at java.base/java.lang.System.loadLibrary(System.java:1948)
	at jdk.net/jdk.net.LinuxSocketOptions.<clinit>(LinuxSocketOptions.java:130)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.newInstance(ExtendedSocketOptions.java:352)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.create(ExtendedSocketOptions.java:368)
	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.<clinit>(ExtendedSocketOptions.java:376)
	at jdk.net/jdk.net.ExtendedSocketOptions.<clinit>(ExtendedSocketOptions.java:203)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/sun.net.ext.ExtendedSocketOptions.getInstance(ExtendedSocketOptions.java:178)
	at java.base/sun.nio.ch.Net.<clinit>(Net.java:388)
	at java.base/sun.nio.ch.NioSocketImpl.create(NioSocketImpl.java:466)
	at java.base/java.net.DelegatingSocketImpl.create(DelegatingSocketImpl.java:74)
	at java.base/java.net.Socket.createImpl(Socket.java:530)
	at java.base/java.net.Socket.connect(Socket.java:632)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:65)
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:113)
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:44)
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:153)
	at dxo.a(SourceFile:670)
	at dxo.<init>(SourceFile:424)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:199)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 352983168 bytes (336 MiB) / 1069547520 bytes (1020 MiB) up to 1069547520 bytes (1020 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd09 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4347.54
	Virtual memory used (MB): 4133.20
	Swap memory total (MB): 2560.00
	Swap memory used (MB): 1174.68
	JVM Flags: 2 total; -Xms1019M -Xmx1019M
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>

### Steps To Reproduce

```markdown
1. play on 1.18.1 
2. wait for error
```

### Expected Behavior

i expected game to run

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by artdeell** [comment]
The issue is likely caused by a corrupt Java runtime, but we'll never know because you did not send us the actual latestlog.txt

**Comment by zdavreal** [comment]
> The issue is likely caused by a corrupt Java runtime, but we'll never know because you did not send us the actual latestlog.txt

where do i find the latest log

**Comment by zdavreal** [comment]
--------- beggining with launcher debug Info: Launcher version: crocus-v3_openjdk Info: LWJGL3 directory: [jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version] Architecture: arm64 Info: Custom Java arguments: "" Info: Selected Minecraft version: 1.18.1 Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache Added custom env: AWTSTUB_WIDTH=2000 Added custom env: REGAL_GL_VERSION=4.5 Added custom env: REGAL_GL_VENDOR=Android Added custom env: LIBGL_MIPMAP=3 Added custom env: allow_higher_compat_version=true Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin Added custom env: force_glsl_extensions_warn=true Added custom env: LIBGL_NORMALIZE=1 Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-rmjJPxW4msHWl8GScC6vAQ==/lib/arm64 Added custom env: POJAV_RENDERER=vulkan_zink Added custom env: LIBGL_ES=3 Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink Added custom env: MESA_GLSL_VERSION_OVERRIDE=460 Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz Added custom env: MESA_GL_VERSION_OVERRIDE=4.6 Added custom env: allow_glsl_extension_directive_midshader=true Added custom env: REGAL_GL_RENDERER=Regal Added custom env: AWTSTUB_HEIGHT=1200 --------- beginning of main I/jrelog ( 3810): dlopen libOSMesa_8.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success I/jrelog ( 3810): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success I/jrelog ( 3810): dlopen libverify.so failed: dlopen failed: library "libverify.so" not found I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success I/jrelog ( 3810): dlopen /data/app/net.kdt.pojavlaunch-rmjJPxW4msHWl8GScC6vAQ==/lib/arm64/libawt_headless.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: cannot locate symbol "AWTFontDefaultChar" referenced by "/data/data/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so"... I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libawt.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjsig.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libattach.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjavajpeg.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libsyslookup.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so failed: dlopen failed: cannot locate symbol "AWTFontDefaultChar" referenced by "/data/data/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfontmanager.so"... I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pcsc.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjaas.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libfreetype.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjli.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjimage.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjsig.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2gss.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnet.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjava.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libnio.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libprefs.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libmanagement_ext.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libj2pkcs11.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libdt_socket.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libjdwp.so success I/jrelog ( 3810): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib/libzip.so success I/jrelog ( 3810): dlopen /data/app/net.kdt.pojavlaunch-rmjJPxW4msHWl8GScC6vAQ==/lib/arm64/libopenal.so success I/jrelog ( 3810): Done processing args I/jrelog ( 3810): Found JLI lib I/jrelog ( 3810): Calling JLI_Launch [05:21:21] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions: 	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath. 	b) Add the JAR that contains the shared library to the classpath. [05:21:21] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics. [05:21:21] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics. [05:21:22] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' ---- Minecraft Crash Report ---- // Sorry :( Time: 2/18/22, 5:21 AM Description: Initializing game java.lang.UnsatisfiedLinkError: no extnet in system library path: /data/data/net.kdt.pojavlaunch/runtimes/jre17-arm64-20210825-release.tar.xz/lib 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403) 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:814) 	at java.base/java.lang.System.loadLibrary(System.java:1948) 	at jdk.net/jdk.net.LinuxSocketOptions.<clinit>(LinuxSocketOptions.java:130) 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:375) 	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.newInstance(ExtendedSocketOptions.java:352) 	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.create(ExtendedSocketOptions.java:368) 	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.<clinit>(ExtendedSocketOptions.java:376) 	at jdk.net/jdk.net.ExtendedSocketOptions.<clinit>(ExtendedSocketOptions.java:203) 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:375) 	at java.base/sun.net.ext.ExtendedSocketOptions.getInstance(ExtendedSocketOptions.java:178) 	at java.base/sun.nio.ch.Net.<clinit>(Net.java:388) 	at java.base/sun.nio.ch.NioSocketImpl.create(NioSocketImpl.java:466) 	at java.base/java.net.DelegatingSocketImpl.create(DelegatingSocketImpl.java:74) 	at java.base/java.net.Socket.createImpl(Socket.java:530) 	at java.base/java.net.Socket.connect(Socket.java:632) 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498) 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603) 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) 	at java.base/sun.net.www.protocol.https.Abstract DelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) 	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:65) 	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:113) 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:44) 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:153) 	at dxo.a(SourceFile:670) 	at dxo.<init>(SourceFile:424) 	at net.minecraft.client.main.Main.main(SourceFile:199) A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403) 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:814) 	at java.base/java.lang.System.loadLibrary(System.java:1948) 	at jdk.net/jdk.net.LinuxSocketOptions.<clinit>(LinuxSocketOptions.java:130) 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:3 75) 	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.newInstance(ExtendedSocketOptions.java:352) 	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.create(ExtendedSocketOptions.java:368) 	at jdk.net/jdk.net.ExtendedSocketOptions$PlatformSocketOptions.<clinit>(ExtendedSocketOptions.java:376) 	at jdk.net/jdk.net.ExtendedSocketOptions.<clinit>(ExtendedSocketOptions.java:203) 	at java.base/java.lang.Class.forName0(Native Method) 	at java.base/java.lang.Class.forName(Class.java:375) 	at java.base/sun.net.ext.ExtendedSocketOptions.getInstance(ExtendedSocketOptions.java:178) 	at java.base/sun.nio.ch.Net.<clinit>(Net.java:388) 	at java.base/sun.nio.ch.NioSocketImpl.create(NioSocketImpl.java:466) 	at java.base/java.net.DelegatingSocketImpl.create(DelegatingSocketImpl.java:74) 	at java.base/java.net.Socket.createImpl(Socket.java:530) 	at java.base/java.net.Socket.connect(Socket.java:632) 	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498) 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603) 	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) 	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) 	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:65) 	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:113) 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:44) 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:153) 	at dxo.a(SourceFile:670) 	at dxo.<init>(SourceFile:424) -- Initialization -- Details: 	Modules: Stacktrace: 	at net.minecraft.client.main.Main.main(SourceFile:199) -- System Details -- Details: 	Minecraft Version: 1.18.1 	Minecraft Version ID: 1.18.1 	Operating System: Linux (aarch64) version Android-10 	Java Version: 17-internal, N/A 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 844990920 bytes (805 MiB) / 1069547520 bytes (1020 MiB) up to 1069547520 bytes (1020 MiB) 	CPUs: 8 	Processor Vendor: 0x41 	Processor Name: 	Identifier: 0x41 Family 8 Model 0xd09 Stepping r0x0p4 	Microarchitecture: unknown 	Frequency (GHz): -0.00 	Number of physical packages: 1 	Number of physical CPUs: 1 	Number of logical CPUs: 8 	Graphics card #0 name: unknown 	Graphics card #0 vendor: unknown 	Graphics card #0 VRAM (MB): 0.00 	Graphics card #0 deviceId: unknown 	Graphics card #0 versionInfo: unknown 	Virtual memory max (MB): 4347.54 	Virtual memory used (MB): 4049.93 	Swap memory total (MB): 2560.00 	Swap memory used (MB): 1120.54 	JVM Flags: 2 total; -Xms1019M -Xmx1019M 	Launched Version: 1.18.1 	Backend library: LWJGL version 3.2.3 SNAPSHOT 	Backend API: Unknown 	Window size: <not initialized> 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is M odde d: Probably not. Client jar signature and brand is untouched 	Type: Client (map_client.txt) 	CPU: <unknown> #@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2022-02-18_05.21.24-client.txt FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7fbb62fa28) process killed with signal 6 code 0xffffffff addr 0x284000000ee2 --------- beginning of crash


alright is this the right one?

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
