### ISSUE TITLE
[BUG] <Short description> Lucraft:Core break

### ISSUE THREAD

**Issue by KingSteal** [PojavLauncherTeam/PojavLauncher#2755]
### Describe the bug

Application exited with code -1 

### The log file and images/videos

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/18/22 4:00 PM
Description: Updating screen events

java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2421)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2421)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:224)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiScreenWorking
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 647205264 bytes (617 MB) / 1141899264 bytes (1089 MB) up to 1141899264 bytes (1089 MB)
	JVM Flags: 3 total; -Xms1148M -Xmx1148M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version       | Source                                  | Signature                                |
	|:------ |:--------------- |:------------- |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2        | minecraft.jar                           | None                                     |
	| LCHIJA | mcp             | 9.42          | minecraft.jar                           | None                                     |
	| LCHIJA | FML             | 8.0.99.99     | forge-1.12.2-14.23.5.2860.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2860  | forge-1.12.2-14.23.5.2860.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | armorpointspp   | v2.0.0-rc1    | armorpointspp-1.12.2-2.0.1.jar          | None                                     |
	| LCHIJA | ebwizardry      | 4.3.5         | ElectroblobsWizardry-4.3.5-MC1.12.2.jar | None                                     |
	| LCHIJA | speedsterheroes | 1.12.2-2.2.1  | SpeedsterHeroes-1.12.2-2.2.1.jar        | None                                     |
	| LCHIJA | lucraftcore     | 1.12.2-2.4.16 | LucraftCore-1.12.2-2.4.16.jar           | None                                     |
	| LCHIJA | heroesexpansion | 1.12.2-1.3.5  | HeroesExpansion-1.12.2-1.3.5.jar        | None                                     |
	| LCHIJA | the-fifth-world | 0.5           | the-fifth-world-0.5.1.jar               | None                                     |

	Loaded coremods (and transformers): 
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.16.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
	Launched Version: 1.12.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null

### Steps To Reproduce

```markdown
1.download latest 1.12.2 forge
2.add latest lucraft core 
3. attempt to loada world
```

### Expected Behavior

I expect the world to be able to load.

### Platform

```markdown
- Device model: 
- CPU architecture: exynos9611
- Android version: 11
- PojavLauncher version:[Latest Release]
```

**Comment by NotAHero04** [comment]
#2679
