### ISSUE TITLE
[BUG] I keep getting this error pls help me

### ISSUE THREAD

**Issue by MR-GAMER7644** [PojavLauncherTeam/PojavLauncher#2766]
### Describe the bug

I have java 17 still I get this error 

java.lang.RuntimeException: Architecture arm is incompatible with Java Runtime aarch64.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

### The log file and images/videos

java.lang.RuntimeException: Architecture arm is incompatible with Java Runtime aarch64.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
Start povjav
Select account
Start game
Get prompt
Got exited
```

### Expected Behavior

I expect it to launch successful

### Platform

```markdown
- Device model: Samsung galaxy tab A
- CPU architecture: I don't know
- Android version: 11
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
**Please install** [**aarch32 jre17 runtime**](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm-20210914-release.tar.xz) **instead of aarch64.**

**Comment by SprainedSpark89** [comment]
try arm if it doesn't work
**java.lang.RuntimeException: Architecture arm is incompatible with Java Runtime aarch64.**
and what version of minecraft

**Comment by MR-GAMER7644** [comment]
Hmm I think it's because of my device because it's working fine on my mom's device

**Comment by GaucovyAero** [comment]
> Hmm I think it's because of my device because it's working fine on my mom's device

Dude, we already told you 2 fixes for this issue. Please fix it yourself if you want to play, thanks.

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
