### ISSUE TITLE
Crash in Xiaomi redmi 8 pro

### ISSUE THREAD

**Issue by Cybercraft-77** [PojavLauncherTeam/PojavLauncher#278]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1040)
	at net.kdt.pojavlaunch.MainActivity.access$3000(MainActivity.java:37)
	at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:677)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: [Lorg/lwjgl/opengl/DisplayMode;
	at bao.<clinit>(SourceFile:92)
	at bao.K(SourceFile:2173)
	at net.minecraft.client.main.Main.main(SourceFile:72)
	... 5 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.lwjgl.opengl.DisplayMode" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/org/lwjgl/lwjglboardwalk/2.9.1/lwjglboardwalk-2.9.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/15.0/guava-15.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.7.10/1.7.10.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-HIKHW07486xn_lX7cz3yoQ==/lib/arm, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more

**Comment by khanhduytran0** [comment]
Do not use latest autobuild.

**Comment by Cybercraft-77** [comment]
Ok

**Comment by Cybercraft-77** [comment]
The application on version 2.5.2 release is not installed on the smartphone

**Comment by Cybercraft-77** [comment]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1015)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
	at bib.<init>(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 5 more
Caused by: java.lang.ClassCastException: Bootstrap method returned null
	... 7 more

**Comment by khanhduytran0** [comment]
1.12?

**Comment by xXFrostXx1** [comment]
> 1.12?

1.12??!
The update is not working

**Comment by khanhduytran0** [comment]
You need a special converted jar to get 1.12 to run

**Comment by artdeell** [comment]
> The application on version 2.5.2 release is not installed on the smartphone

First remove all previous PojavLauncher installations before installing a new one

**Comment by khanhduytran0** [comment]
@Cybercraft-77 anymore reply? Will this be closed?

**Comment by mglovers123** [comment]
@Cybercraft-77  closed the issue

**Comment by khanhduytran0** [comment]
You may also use v3 to get 1.12.x work.
