### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GEROGIANNIS** [PojavLauncherTeam/PojavLauncher#281]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1045)
	at net.kdt.pojavlaunch.MainActivity.access$3000(MainActivity.java:37)
	at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:677)
	at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/lwjgl/LWJGLUtil;
	at org.lwjgl.Sys.createImplementation(Unknown Source)
	at org.lwjgl.Sys.<clinit>(Unknown Source)
	at ave.J(SourceFile:2539)
	at net.minecraft.client.main.Main.main(SourceFile:41)
	... 5 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.lwjgl.LWJGLUtil" on path: DexPathList[[zip file "/data/app/net.kdt.pojavlaunch-1/base.apk"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /data/app/net.kdt.pojavlaunch-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 9 more

**Comment by khanhduytran0** [comment]
Do not use autobuilds.
