### ISSUE TITLE
It crash?! But how?

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#2819]
### Describe the bug

I play minecraft fabric version of 1.18.1 with create mod fabric port version of it, it was used to work perfectly fine, no error, no bugs. Untill one day, I play with it again, it crash. After I see it crash, I rage quit immedietly

### The log file and images/videos

![Screenshot_20220228-102838_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/100254075/155919204-c67baf73-7c70-401a-8617-40110ce56a3a.jpg)
[10:20:19] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3 [10:20:20] [main/INFO]: Loading 70 mods: 	- appleskin 2.3.0+mc1.18.1 	- cloth-basic-math 0.6.0 via cloth-config 	- cloth-config 6.0.42 via appleskin 	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport 	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport 	- com_google_code_findbugs_jsr305 3.0.2 via create 	- create mc1.18.1_v0.4d+440 	- dripstone_fluid_lib 1.1.1 via milk 	- effective 1.1 	- fabric 0.46.4+1.18 	- fabric-api-base 0.4.2+d7c144a865 via fabric 	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric 	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric 	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric 	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric 	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric 	- fabric-containers-v0 0.1.19+d7c144a865 via fabric 	- fabric-content-registries-v0 0.4.8+d7c144a865 via fabric 	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric 	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8 via registrate-fabric 	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric 	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric 	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric 	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric 	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric 	- fabric-item-api-v1 1.3.1+691a79b565 via fabric 	- fabric-item-groups-v0 0.3.6+3ac43d9565 via fabric 	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric 	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric 	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric 	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric 	- fabric-mining-level-api-v1 1.0.6+d7c144a865 via fabric 	- fabric-mining-levels-v0 0.1.11+b4f4f6cd65 via fabric 	- fabric-models-v0 0.3.4+d7c144a865 via fabric 	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric 	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric 	- fabric-object-builder-api-v1 1.11.4+d7c144a865 via fabric 	- fabric-object-builders-v0 0.7.12+d7c144a865 via fabric 	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric 	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric 	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric 	- fabric-renderer-indigo 0.4.15+6825030165 via fabric 	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric 	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric 	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric 	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric 	- fabric-rendering-v1 1.10.6+713c266865 via fabric 	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric 	- fabric-resource-loader-v0 0.4.14+713c266865 via fabric 	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric 	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric 	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric 	- fabric-tag-extensions-v0 1.2.8+d7c144a865 via fabric 	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric 	- fabric-tool-attribute-api-v1 1.3.8+fb3b57b465 via fabric 	- fabric-transfer-api-v1 1.5.9+d7c144a865 via fabric 	- fabricloader 0.13.3 	- fake-player-api 0.3.0 via create 	- flywheel 1.18-0.6.1.24 via create 	- forge_tags 2.0 via create 	- forgeconfigapiport 3.1.0 via create 	- interactic 0.1.8+1.18 	- java 17 	- milk 0.1.6 via create 	- minecraft 1.18.1 	- mm 2.3 via optifabric 	- modmenu 3.0.1 	- optifabric 1.12.10 	- reach-entity-attributes 2.1.1 via create 	- registrate-fabric MC1.18.1-1.0.7 via create [10:20:20] [main/WARN]: Mod `create` (mc1.18.1_v0.4d+440) does not respect SemVer - comparison support is limited. [10:20:20] [main/WARN]: Mod `registrate-fabric` (MC1.18.1-1.0.7) does not respect SemVer - comparison support is limited. [10:20:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT [10:20:21] [main/INFO]: Compatibility level set to JAVA_17 [10:20:29] [main/ERROR]: Minecraft has crashed! net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?] Caused by: java.lang.ExceptionInInitializerError 	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?] 	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.1.jar:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?] 	... 2 more Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?] 	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?] 	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.1.jar:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?] 	... 2 more Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?] 	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?] 	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.1.jar:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?] 	... 2 more Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method wrapBlockEntityIterator(Ljava/util/Iterator;)Ljava/util/Iterator; in create_lib.mixins.client.json:LevelRendererMixin from mod create failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap create-refmap.json Messages: { @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1151 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1159 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1172 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1196 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1200 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1232 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1255 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1273 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1279 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1312 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1320 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 3 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1328 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 3 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1341 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required. @At("STORE" implicit Iterator) has invalid IMPLICIT discriminator for opcode 1365 in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V: Found 2 candidate variables but exactly 1 is required.} 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.13.3.jar:?] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?] 	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?] 	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?] 	at net.minecraft.client.main.Main.main(Main.java:153) ~[fabric-loader-0.13.3-1.18.1.jar:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?] 	... 2 more

### Steps To Reproduce

```markdown
Step 1. Play pojavlauncher fabric 1.18.1 with create mod fabric port from this link
⬇️     ⬇️
https://github.com/Fabricators-of-Create/Create/actions
Step 2. Rage quit (see the game crash)
```

### Expected Behavior

I expected the gane to launch perfectly fine like it was to.

### Platform

```markdown
- Device model: samsung galaxy a32
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: *A playstore version*
```

### Anything else?

This bug was fixed now, I know what cause it to crash, it because of optifine.

**Comment by khanhduytran0** [comment]
It's hard to guess without a visible latestlog.txt, but
> One day, you realized that you didn't buy the game.

**Comment by Thollp** [comment]
> It's hard to guess without a visible latestlog.txt, but
> 
> > One day, you realized that you didn't buy the game.

I already put the lastest log now

**Comment by Thollp** [comment]
Now shut the fuck up

**Comment by khanhduytran0** [comment]
The log is incomplete. Send it as a file here. The attach image button is what you’re looking for (it allows picking non-image file, right?). Also, it looks more like `latest.log` than `latestlog.txt`

> Now shut the f\*\*\*\ up

It’s strange that you requested for help but told me to shut up.

**Comment by Thollp** [comment]
> The log is incomplete. Send it as a file here. The attach image button is what you’re looking for (it allows picking non-image file, right?). Also, it looks more like `latest.log` than `latestlog.txt`
> 
> > Now shut the f***\ up
> 
> It’s strange that you requested for help but told me to shut up.

Sorry, I'm just in rage because of it
