### ISSUE TITLE
Rendering entity in world

### ISSUE THREAD

**Issue by Thollp** [PojavLauncherTeam/PojavLauncher#2820]
### Describe the bug

This is the bug that I experience so many times when I use sodium and iris mod. This bug was so annoying that I need to restart an entire game when I set the setting in minecraft before entering world

### The log file and images/videos

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 2/28/22, 7:56 AM
Description: Rendering entity in world

java.lang.RuntimeException: Cannot use BufferBuilder with format: 9 elements: Position=3,Position,Float Color=4,Vertex Color,Unsigned Byte UV0=2,UV,Float UV2=2,UV,Short Normal=3,Normal,Byte Padding=1,Padding,Byte mc_Entity=4,Generic,Float mc_midTexCoord=2,Generic,Float at_tangent=4,Generic,Float
	at com.jozufozu.flywheel.core.vertex.BlockVertex.createReader(BlockVertex.java:72)
	at com.jozufozu.flywheel.core.model.WorldModel.<init>(WorldModel.java:22)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption.buildLayers(FlwContraption.java:144)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption.<init>(FlwContraption.java:56)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:84)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:22)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderingWorld.getRenderInfo(ContraptionRenderingWorld.java:94)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.renderFromEntity(ContraptionRenderDispatcher.java:85)
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.render(ContraptionEntityRenderer.java:41)
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.method_3936(ContraptionEntityRenderer.java:12)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.method_22710(class_761.java:1325)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.jozufozu.flywheel.core.vertex.BlockVertex.createReader(BlockVertex.java:72)
	at com.jozufozu.flywheel.core.model.WorldModel.<init>(WorldModel.java:22)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption.buildLayers(FlwContraption.java:144)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraption.<init>(FlwContraption.java:56)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:84)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.FlwContraptionManager.create(FlwContraptionManager.java:22)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderingWorld.getRenderInfo(ContraptionRenderingWorld.java:94)
	at com.simibubi.create.content.contraptions.components.structureMovement.render.ContraptionRenderDispatcher.renderFromEntity(ContraptionRenderDispatcher.java:85)
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.render(ContraptionEntityRenderer.java:41)
	at com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer.method_3936(ContraptionEntityRenderer.java:12)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.method_22710(class_761.java:1325)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Entity being rendered --
Details:
	Entity Type: create:stationary_contraption (com.simibubi.create.content.contraptions.components.structureMovement.ControlledContraptionEntity)
	Entity ID: 5414
	Entity Name: Stationary Contraption
	Entity's Exact location: -11.00, 2.00, 37.00
	Entity's Block location: World: (-11,2,37), Section: (at 5,2,5 in -1,0,2; chunk contains blocks -16,-64,32 to -1,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.method_22710(class_761.java:1325)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: com.simibubi.create.content.contraptions.components.structureMovement.ContraptionEntityRenderer@1ffff650
	Location: -35.31,8.38,-22.72 - World: (-36,8,-23), Section: (at 12,8,9 in -3,0,-2; chunk contains blocks -48,-64,-32 to -33,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: 0.0
	Delta: 0.37997723
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1577)
	at net.minecraft.class_761.method_22710(class_761.java:1325)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Trollge345'/68, l='ClientLevel', x=24.31, y=-8.00, z=59.72]]
	Chunk stats: 1024, 469
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 125647 game time, 1 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 420293360 bytes (400 MiB) / 1101004800 bytes (1050 MiB) up to 1101004800 bytes (1050 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd0a Stepping r0x1p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 6294.02
	Virtual memory used (MB): 9631.83
	Swap memory total (MB): 2560.00
	Swap memory used (MB): 2446.65
	JVM Flags: 2 total; -Xms1050M -Xmx1050M
	Fabric Mods: 
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 3.7.26
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_google_code_findbugs_jsr305: jsr305 3.0.2
		com_typesafe_config: config 1.4.1
		confabricate: confabricate 2.2.0-SNAPSHOT+4.1.1
		create: Create mc1.18.1_v0.4d+441
		croptopia: Croptopia 1.8.1
		dripstone_fluid_lib: Dripstone Fluid Lib 1.1.1
		effective: Effective 1.1
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.13.3
		fake-player-api: Fake Player API 0.3.0
		flywheel: Flywheel 1.18-0.6.1.24
		forge_tags: Forge Tags 2.0
		forgeconfigapiport: Forge Config API Port 3.1.0
		interactic: Interactic 0.1.8+1.18
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		lithium: Lithium 0.7.8
		milk: Milk Lib 0.1.6
		minecraft: Minecraft 1.18.1
		modmenu: Mod Menu 3.0.1
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		phosphor: Phosphor 0.8.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		registrate-fabric: Registrate for Fabric MC1.18.1-1.0.7
		roughlyenoughitems: Roughly Enough Items 7.3.435
		sodium: Sodium 0.4.0-alpha6+build.14
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: virgl GL version 4.3 (Compatibility Profile) Mesa 21.2.1 (git-c403646518), Mesa/X.org
	Window size: 2400x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Trollge345'/68, l='ServerLevel[New World]', x=24.31, y=-8.00, z=59.72]]
	Data Packs: vanilla, Fabric Mods

### Steps To Reproduce

```markdown
Step 1. Play the fabric version of 1.18.1 with sodium and iris mod for minute/hours 
Step 2. Set any graphic setting during gameplay
Step 3. See it crash
Step 4. Read crash log
```

### Expected Behavior

I expected the setting will work

### Platform

```markdown
- Device model: samsung galaxy a32
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: *A version with virglrenderer*
```

### Anything else?

Iris is a mod that allows you to use shader while playing with sodium mod. I use this mod to fix the virgl entity block bug that I reported, not for use with shader.

**Comment by khanhduytran0** [comment]
> Read crash log

Crash log is not enough for us in most cases. Please send latestlog.txt.

**Comment by SprainedSpark89** [comment]
sodium doesn't work last time i looked

**Comment by SprainedSpark89** [comment]
and also a texture pack can crash your game

**Comment by Thollp** [comment]
> and also a texture pack can crash your game

Nope, I don't use any texture pack before the game crash

**Comment by Thollp** [comment]
> > Read crash log
> 
> Crash log is not enough for us in most cases. Please send latestlog.txt.

Sorry, I already delete it

**Comment by SprainedSpark89** [comment]
use optifine or change your render to zink

**Comment by Mathias-Boulay** [comment]
#1948

**Comment by lost72738** [comment]
Turn off use entity culling
