### ISSUE TITLE
[BUG] java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by Errorbot1122** [PojavLauncherTeam/PojavLauncher#2832]
### Describe the bug

Lunching 1.18 with mods and it shows this error in the latest.txt file after its crash:

```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.65) ~[?:?]
	at org.lwjgl.glfw.GLFW.glfwGetWindowAttrib(GLFW.java:949) ~[lwjgl-glfw-classes.jar:?]
	at dynamicfps.DynamicFPSMod.checkForRender(DynamicFPSMod.java:68) ~[dynamic-fps-2.1.0.jar:?]
	at net.minecraft.client.render.GameRenderer.handler$zgb000$onRender(GameRenderer:1516) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
```

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8166002/latestlog.txt)

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

For my game to launch 

### Platform

```markdown
- Device model: R96-14268.67.0
- CPU architecture: x86_64
- Android version: 11
- PojavLauncher version: crocus-v3_openjdk
```

### Anything else?

I WOULD add my MODS .zip file in here but I keep getting this error >:(

![image](https://user-images.githubusercontent.com/65428515/156281276-d2e18e61-8ea3-4969-bf4e-13b41a01061e.png)

**Comment by NotAHero04** [comment]
Your log did say what caused the problem.
> at dynamicfps.DynamicFPSMod.checkForRender(DynamicFPSMod.java:68) ~[dynamic-fps-2.1.0.jar:?]

**Comment by Errorbot1122** [comment]
uh... WAT 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8170290/latestlog.txt)
[latest.log.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8170304/latest.log.txt)

**Comment by khanhduytran0** [comment]
The latest changes might have already done something to this issue.

**Comment by Errorbot1122** [comment]
ooof :(

**Comment by khanhduytran0** [comment]
> ooof :(

wait, I mean fix. See 1f1d542ed79ce591efc9171dfbfe50cd93dd2bbb

**Comment by ghost** [comment]
Its like my issue

**Comment by ghost** [comment]
But fixed in latest build
But stucking at loading screen if using the mod
