### ISSUE TITLE
[BUG] Pojav crashes whenever i open it

### ISSUE THREAD

**Issue by 23ergbcf** [PojavLauncherTeam/PojavLauncher#2884]
### Describe the bug

I used to have no problems and then I just get a crash suddenly

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

### Steps To Reproduce

```markdown
1. Start Pojav
2.Crash
3.Crash message:java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
```

### Expected Behavior

I expect the gane starts

### Platform

```markdown
- Device model: Samsung Galaxy S8
- CPU architecture: 4x Samsung Exynos M2 @ 2.31 GHz
- Android version: 9
- PojavLauncher version: Newest version
```

### Anything else?

Nothing else

**Comment by 23ergbcf** [comment]
can someone help me please

**Comment by WesleyVanNeck** [comment]
Newest version isnt a version

**Comment by 23ergbcf** [comment]
eh its like crocus-v3_openjdk, sorry i was kinda lazy to type it out

**Comment by 23ergbcf** [comment]
also the CPU is aarch64

**Comment by 23ergbcf** [comment]
some1 pls help

**Comment by 23ergbcf** [comment]
plssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss

**Comment by Evenz3839** [comment]
I'm haveing the same thing on my galaxy tab 2

**Comment by 23ergbcf** [comment]
i thought it was only me

**Comment by ghost** [comment]
Update your launcher to the latest action build.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.

**Comment by Therealrex** [comment]
Same :[ Pls Help java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
