### ISSUE TITLE
[BUG] <error on launch 1.12.2>

### ISSUE THREAD

**Issue by Nikit2345** [PojavLauncherTeam/PojavLauncher#2891]
### Describe the bug

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:208)
	at java.lang.StringBuilder.setLength(StringBuilder.java:77)
	at net.kdt.pojavlaunch.Tools.getLWJGL3ClassPath(Tools.java:291)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:151)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:734)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)

### The log file and images/videos

![Screenshot_20220313_183916](https://user-images.githubusercontent.com/101510441/158062626-4f421192-72f8-4397-95b9-062fd2597c4d.jpg)

### Steps To Reproduce

```markdown
1. start pojavlauncher
2. Select 1.12.2
3. Start 1.12.2
```

### Expected Behavior

I expect game to launch

### Platform

```markdown
- Device model: zte blade A5 2019ru
- CPU architecture: 
- Android version: 9
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by SamGoneMissing** [comment]
Go to actions and use the version from the latest tick mark

**Comment by Evenz3839** [comment]
You tried to play on 2b2t lol

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
