### ISSUE TITLE
Problem opening 1.11.2

### ISSUE THREAD

**Issue by Doxelix** [PojavLauncherTeam/PojavLauncher#29]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 3/31/20 15:28
Description: Initializing game

java.lang.IllegalAccessError: Method 'void java.lang.System.arraycopy(int[], int, int[], int, int)' is inaccessible to class 'org.apache.harmony.awt.gl.image.OffscreenImage' (declaration of 'org.apache.harmony.awt.gl.image.OffscreenImage' appears in base.apk)
	at org.apache.harmony.awt.gl.image.OffscreenImage.setPixels(OffscreenImage.java:195)
	at org.apache.harmony.awt.gl.image.ImageDecoder.setPixels(ImageDecoder.java:234)
	at com.android.internal.awt.AndroidImageDecoder.sendPixels(AndroidImageDecoder.java:266)
	at com.android.internal.awt.AndroidImageDecoder.decodeImage(AndroidImageDecoder.java:109)
	at org.apache.harmony.awt.gl.image.DecodingImageSource.load(DecodingImageSource.java:252)
	at org.apache.harmony.x.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:84)
	at org.apache.harmony.x.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:93)
	at javax.imageio.ImageIO.read(ImageIO.java:477)
	at javax.imageio.ImageIO.read(ImageIO.java:429)
	at bes.a(SourceFile:819)
	at bes.an(SourceFile:457)
	at bes.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:748)
	at net.kdt.pojavlaunch.MainActivity.access$1000073(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000013$100000012.run(MainActivity.java:509)
	at java.lang.Thread.run(Thread.java:764)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.apache.harmony.awt.gl.image.OffscreenImage.setPixels(OffscreenImage.java:195)
	at org.apache.harmony.awt.gl.image.ImageDecoder.setPixels(ImageDecoder.java:234)
	at com.android.internal.awt.AndroidImageDecoder.sendPixels(AndroidImageDecoder.java:266)
	at com.android.internal.awt.AndroidImageDecoder.decodeImage(AndroidImageDecoder.java:109)
	at org.apache.harmony.awt.gl.image.DecodingImageSource.load(DecodingImageSource.java:252)
	at org.apache.harmony.x.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:84)
	at org.apache.harmony.x.imageio.plugins.png.PNGImageReader.read(PNGImageReader.java:93)
	at javax.imageio.ImageIO.read(ImageIO.java:477)
	at javax.imageio.ImageIO.read(ImageIO.java:429)
	at bes.a(SourceFile:819)

-- Initialization --
Details:
Stacktrace:
	at b.a(SourceFile:245)
	at bes.a(SourceFile:386)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:748)
	at net.kdt.pojavlaunch.MainActivity.access$1000073(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000013$100000012.run(MainActivity.java:509)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (aarch64) version 4.4.111-16762587
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (null), The Android Project
	Memory: 17445456 bytes (16 MB) / 78826856 bytes (75 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.11.2
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'java.lang.String cai.toString()' on a null object reference
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by artdeell** [comment]
This is due to legacy AWT. To fix that, you must downgrade to previous preview.

**Comment by Azapru** [comment]
Don't install preview 9! Jump to Preview 8b1!

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/releases/tag/v2.4.2-preview.9b1

**Comment by khanhduytran0** [comment]
Use latest preview will solve the issue

**Comment by khanhduytran0** [comment]
Please reply
