### ISSUE TITLE
Unable to sign in with Microsoft account

### ISSUE THREAD

**Issue by TGranit3** [PojavLauncherTeam/PojavLauncher#2901]
### Describe the bug

java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### The log file and images/videos

No logs - Fresh new save data

### Steps To Reproduce

```markdown
1. Login to Microsoft account
2. Error occurs
```

### Expected Behavior

I expect it to login completely as it is a valid Microsoft account.

### Platform

```markdown
- Device model: Samsung j6
- CPU architecture: x86
- Android version: 10
- PojavLauncher version: crocorus-387-ddae3efc1-v3_openjdk
```

### Anything else?

I owned the Minecraft java via Xbox gamepass ultimate

**Comment by Mathias-Boulay** [comment]
The Microsoft account may be valid, but you have to buy minecraft **java** edition on it

**Comment by Mathias-Boulay** [comment]
Gamepass is not game ownership

**Comment by TGranit3** [comment]
> Gamepass is not game ownership

But the Minecraft java works on my pc, is something happening?

**Comment by TGranit3** [comment]
> Gamepass is not game ownership

+ I wasn't able to play java on pc untill I got the gamepass so it has to be something on the app

**Comment by TGranit3** [comment]
> Gamepass is not game ownership

+ I wasn't able to play java on pc untill I got the gamepass so it has to be something on the app

**Comment by CriticalRange** [comment]
> > Gamepass is not game ownership
> 
> * I wasn't able to play java on pc untill I got the gamepass so it has to be something on the app

Go to your Minecraft.net profile
Check if it wants you to set up your account again
I'm having the same problem
That is occured due to a game pass feature i believe

**Comment by TGranit3** [comment]
> > > Gamepass is not game ownership
> > 
> > 
> > 
> > * I wasn't able to play java on pc untill I got the gamepass so it has to be something on the app
> 
> Go to your Minecraft.net profile Check if it wants you to set up your account again I'm having the same problem That is occured due to a game pass feature i believe

Sorry for a month wait, your tip actually works. Thanks.
