### ISSUE TITLE
[F-Req] Does Openj9 exist for PojavLauncher? 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#2904]
### Is this request related to a bug?

What was the result of the attempt to install openj9 on the last debug build
java.io.FileNotFoundException: /data/user/0/net.kdt.pojavlaunch.debug/runtimes/openj9-openj9-0.30.1.tar.xz/lib/libawt_xawt.so: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at net.kdt.pojavlaunch.multirt.MultiRTUtils.copyDummyNativeLib(MultiRTUtils.java:195)
	at net.kdt.pojavlaunch.multirt.MultiRTUtils.postPrepare(MultiRTUtils.java:103)
	at net.kdt.pojavlaunch.BaseLauncherActivity.lambda$onActivityResult$6$BaseLauncherActivity(BaseLauncherActivity.java:196)
	at net.kdt.pojavlaunch.-$$Lambda$BaseLauncherActivity$Z9ICzeUEgQdu3BlHdxbTzek2tbY.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:929)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8198)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 7 more

### Describe the request.

Is there an openj9 for PojavLauncher? If yes, then drop the download link.

**Comment by khanhduytran0** [comment]
OpenJ9 Android port is only available for internal testing for now. However, changes are made public on GitHub. It hasn’t worked yet.
