### ISSUE TITLE
Crash when joining Prison

### ISSUE THREAD

**Issue by KienOne** [PojavLauncherTeam/PojavLauncher#291]
I'm playing on mc.ultranetwork.net and I can join the lobby but when I try join prison, the game crashes. Here's the crash report:

---- Minecraft Crash Report ----
// There are four lights!

Time: 8/29/20 8:59 PM
Description: Rendering Block Entity

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bnp.a(SourceFile:126)
	at bhk.a(SourceFile:76)
	at bhk.a(SourceFile:38)
	at bhk.a(SourceFile:21)
	at bhc.a(SourceFile:114)
	at bhc.a(SourceFile:102)
	at bfr.a(SourceFile:615)
	at bfk.a(SourceFile:1244)
	at bfk.b(SourceFile:1149)
	at bfk.a(SourceFile:1002)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1015)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at bnp$1.a(SourceFile:47)
	at bnp$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bnp.a(SourceFile:126)
	at bhk.a(SourceFile:76)
	at bhk.a(SourceFile:38)

-- Block Entity Details --
Details:
	Name: Skull // alo
	Block type: ID #144 (tile.skull // ajm)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (2,14,2), Chunk: (at 2,0,2 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #144 (tile.skull // ajm)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at b.a(SourceFile:244)
	at bhc.a(SourceFile:117)
	at bhc.a(SourceFile:102)
	at bfr.a(SourceFile:615)
	at bfk.a(SourceFile:1244)
	at bfk.b(SourceFile:1149)
	at bfk.a(SourceFile:1002)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1015)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:764)

-- Affected level --
Details:
	Level name: MpServer
	All players: 5 total; [bew['KienOne'/14759, l='MpServer', x=0.50, y=25.00, z=0.50], bex['ADAMZOGAMER1'/234734, l='MpServer', x=0.88, y=24.50, z=-2.91], bex['§b§lMissions'/1789, l='MpServer', x=21.66, y=21.00, z=4.34], bex['Han_'/224316, l='MpServer', x=-4.34, y=34.88, z=-4.59], bex['§b§lDaily'/1792, l='MpServer', x=21.13, y=21.00, z=-4.22]]
	Chunk stats: MultiplayerChunkCache: 15, 15
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 8.00,64.00,8.00 - World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16 game time, 16 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 9 total; [bex['§b§lDaily'/1792, l='MpServer', x=21.13, y=21.00, z=-4.22], bew['KienOne'/14759, l='MpServer', x=0.50, y=25.00, z=0.50], bex['ADAMZOGAMER1'/234734, l='MpServer', x=0.88, y=24.50, z=-2.91], bex['§b§lMissions'/1789, l='MpServer', x=21.66, y=21.00, z=4.34], bex['Han_'/224316, l='MpServer', x=-4.34, y=34.88, z=-4.59], bex['ADAMZOGAMER1'/234734, l='MpServer', x=0.88, y=24.50, z=-2.91], bex['§b§lMissions'/1789, l='MpServer', x=21.66, y=21.00, z=4.34], bex['§b§lDaily'/1792, l='MpServer', x=21.13, y=21.00, z=-4.22], bex['Han_'/224316, l='MpServer', x=-4.34, y=34.88, z=-4.59]]
	Retry entities: 0 total; []
	Server brand: Waterfall <- Paper
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (armv8l) version 4.9.117+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (OPPO CPH2015, Android 9), The Android Project
	Memory: 5383480 bytes (5 MB) / 246153336 bytes (234 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8.9
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 4 (v8l)

**Comment by khanhduytran0** [comment]
You need join in 1.11+

**Comment by WesleyVanNeck** [comment]
dublicated of #173
