### ISSUE TITLE
Cant play the Ares client[BUG] <Short description>

### ISSUE THREAD

**Issue by GOPRO12345905920** [PojavLauncherTeam/PojavLauncher#2916]
### Describe the bug

Cant play ares client

### The log file and images/videos

[05:00:44] [Client thread/INFO]: Setting user: LegendX45
[05:00:51] [Client thread/INFO]: [OptiFine] *** Reflector Forge ***
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.ChunkWatchEvent$UnWatch
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.relauncher.CoreModManager
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.DimensionManager
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Post
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$CameraSetup
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.EntityViewRenderEvent$FogColors
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.eventhandler.Event
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.eventhandler.EventBus
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.eventhandler.Event$Result
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.property.ExtendedBlockState
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.FMLClientHandler
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.FMLCommonHandler
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.biome.BiomeGenBase.getWaterColorMultiplier
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.addDestroyEffects
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.addHitEffects
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.canCreatureSpawn
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.canRenderInLayer
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.doesSideBlockRendering
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.getBedDirection
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.getExtendedState
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.getLightOpacity
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.getLightValue
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.hasTileEntity
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isAir
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isBed
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isBedFoot
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.block.Block.isSideSolid
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.ChunkCache.isSideSolid
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.entity.Entity.canRiderInteract
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.entity.Entity.captureDrops
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.entity.Entity.capturedDrops
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.entity.Entity.shouldRenderInPass
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.entity.Entity.shouldRiderSit
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.ForgeEventFactory
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeHooks
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.item.Item.delegate
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.item.Item.getDurabilityForDisplay
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.item.Item.getModel
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.item.Item.onEntitySwing
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.item.Item.shouldCauseReequipAnimation
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.item.Item.showDurabilityBar
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.ForgeModContainer
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.potion.PotionEffect.isCurativeItem
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.tileentity.TileEntity.canRenderBreaking
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.tileentity.TileEntity.getRenderBoundingBox
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.tileentity.TileEntity.hasFastRenderer
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.tileentity.TileEntity.shouldRenderInPass
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.postDraw
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.World.countEntities
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.World.getPerWorldStorage
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.WorldProvider.getCloudRenderer
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.WorldProvider.getSkyRenderer
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.WorldProvider.getWeatherRenderer
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.world.WorldProvider.getSaveFolder
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.GuiModList
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.IColoredBakedQuad
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.property.IExtendedBlockState
[05:00:51] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.IModel
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.IRenderHandler
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ItemModelMesherForge
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.LightUtil
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.MinecraftForge
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.MinecraftForgeClient
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.ModContainer
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.ModelLoader
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderBlockOverlayEvent$OverlayType
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.registry.RenderingRegistry
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderItemInFrameEvent
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Pre
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Post
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Pre
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Post
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.SplashProgress
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.event.world.WorldEvent$Load
[05:00:52] [Client thread/INFO]: [OptiFine] *** Reflector Vanilla ***
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Field not present: net.minecraft.client.gui.GuiMainMenu.(type: class java.lang.String, index: 0)
[05:00:52] [Client thread/INFO]: LWJGL Version: 3.2.3 SNAPSHOT
[05:00:52] [Client thread/INFO]: [Shaders] OpenGL Version: 2.1 gl4es wrapper 1.1.4
[05:00:52] [Client thread/INFO]: [Shaders] Vendor:  ptitSeb
[05:00:52] [Client thread/INFO]: [Shaders] Renderer: GL4ES wrapper
[05:00:52] [Client thread/INFO]: [Shaders] Capabilities:  2.0  2.1  -  -  - 
[05:00:52] [Client thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[05:00:52] [Client thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[05:00:52] [Client thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[05:00:52] [Client thread/INFO]: [Shaders] Load shaders configuration.
[05:00:52] [Client thread/INFO]: [Shaders] Shaders can not be loaded, Fast Render is enabled.
[05:00:52] [Client thread/INFO]: [Shaders] No shaderpack loaded.
[05:00:52] [Client thread/INFO]: [Shaders] OpenGL Version: 2.1 gl4es wrapper 1.1.4
[05:00:52] [Client thread/INFO]: [Shaders] Vendor:  ptitSeb
[05:00:52] [Client thread/INFO]: [Shaders] Renderer: GL4ES wrapper
[05:00:52] [Client thread/INFO]: [Shaders] Capabilities:  2.0  2.1  -  -  - 
[05:00:52] [Client thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[05:00:52] [Client thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8
[05:00:52] [Client thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[05:00:52] [Client thread/INFO]: [Shaders] Load shaders configuration.
[05:00:52] [Client thread/INFO]: [Shaders] Shaders can not be loaded, Fast Render is enabled.
[05:00:52] [Client thread/INFO]: [Shaders] No shaderpack loaded.
[05:00:52] [Client thread/INFO]: [OptiFine] VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
[05:00:52] [Client thread/INFO]: Reloading ResourceManager: Default, [Minecraft-INSIDE.com] faithful_1.8.zip
[05:00:52] [Client thread/INFO]: [OptiFine] *** Reloading textures ***
[05:00:52] [Client thread/INFO]: [OptiFine] Resource packs: [Minecraft-INSIDE.com] faithful_1.8.zip
[05:00:52] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.Attributes
[05:00:53] [Sound Library Loader/INFO]: Starting up SoundSystem...
[05:00:53] [Thread-5/INFO]: Initializing LWJGL OpenAL
[05:00:53] [Thread-5/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[05:00:53] [Thread-5/INFO]: OpenAL initialized.
[05:00:53] [Sound Library Loader/INFO]: Sound engine started

### Steps To Reproduce

```markdown
---- Minecraft Crash Report ----
// My bad.

Time: 3/17/22 5:00 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: /storage/emulated/0/games/PojavLauncher/.discord-rpc/libdiscord-rpc.so: dlopen failed: library "/storage/emulated/0/games/PojavLauncher/.discord-rpc/libdiscord-rpc.so" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so" is not accessible for the namespace "classloader-namespace" (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at com.aresclient.discordrpc.DiscordApp.init(Unknown Source)
	at com.aresclient.Ares.startMinecraft(Unknown Source)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:514)
	at net.minecraft.client.Minecraft.run(Minecraft.java:396)
	at net.minecraft.client.main.Main.main(Main.java:116)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:810)
	at java.lang.System.load(System.java:1088)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:159)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:21)
	at com.aresclient.discordrpc.DiscordApp.init(Unknown Source)
	at com.aresclient.Ares.startMinecraft(Unknown Source)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:514)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:396)
	at net.minecraft.client.main.Main.main(Main.java:116)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1911480952 bytes (1822 MB) / 2075394048 bytes (1979 MB) up to 2075394048 bytes (1979 MB)
	JVM Flags: 24 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:+UseBiasedLocking -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:+UseCodeCacheFlushing -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:ReservedCodeCacheSize=2048m -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -Xmn768m -Xms2056M -Xmx2056M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Ares-3.0.1.8
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Ares'
	Type: Client (map_client.txt)
	Resource Packs: [Minecraft-INSIDE.com] faithful_1.8.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x null
	OptiFine Version: OptiFine_1.8.9_HD_U_L5
	OptiFine Build: ~~NULL~~
	Render Distance Chunks: 2
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 8
```

### Expected Behavior

I think it should launch beacuse we in monjang screen

### Platform

```markdown
- Device model: iBall itab moviez pro
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version:[Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by artdeell** [comment]
Most hacked clients use RPC, which is not available in pojav.
