### ISSUE TITLE
1.17.1 optifine crashes (somehow)

### ISSUE THREAD

**Issue by Evenz3839** [PojavLauncherTeam/PojavLauncher#2943]
### Describe the bug

Just crashes after 2 or 3 seconds of waiting 

### The log file and images/videos

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 22. 3. 20. 오전 8:50
Description: Initializing game

java.lang.IllegalStateException: could not preload shader rendertype_text
	at enb.a(GameRenderer.java:464)
	at enb.a(GameRenderer.java:450)
	at dvp.<init>(SourceFile:617)
	at net.minecraft.client.main.Main.main(SourceFile:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: wz: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:26: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at wz.a(SourceFile:48)
	at ent.<init>(ShaderInstance.java:222)
	at ent.<init>(ShaderInstance.java:100)
	at enb.a(GameRenderer.java:458)
	... 9 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:26: S0001: Type mismatch in arithmetic operation between 'ivec2' and 'float'
	at dqa.b(Program.java:94)
	at dqa.a(Program.java:55)
	at ent.a(ShaderInstance.java:265)
	at ent.<init>(ShaderInstance.java:195)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at enb.a(GameRenderer.java:464)
	at enb.a(GameRenderer.java:450)
	at dvp.<init>(SourceFile:617)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1255122688 bytes (1196 MiB) / 1509949440 bytes (1440 MiB) up to 1509949440 bytes (1440 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd0d Stepping r0x1p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5565.66
	Virtual memory used (MB): 6938.35
	Swap memory total (MB): 3072.00
	Swap memory used (MB): 2262.51
	JVM Flags: 2 total; -Xms1440M -Xmx1440M
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: 8x 
	OptiFine Version: OptiFine_1.17.1_HD_U_H2_pre1
	OptiFine Build: 20211104-233441
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
Install 1.17.1 vanila 
Install java runtime on pojava github
Install optifine 1.17.1 (bata)
Tap play
Crash
```

### Expected Behavior

Just excited the game without error code

### Platform

```markdown
- Device model: samsung a51
- CPU architecture: arm 
- Android version: 11
- PojavLauncher version: the newest version on play store
```

### Anything else?

Pls fix

**Comment by PugBroKid** [comment]
Try the 1.17 assets patcher

**Comment by PugBroKid** [comment]
go to my directory for a shortcut idk where it is located

**Comment by PugBroKid** [comment]
im not self promoting

**Comment by ghost** [comment]
1. Update your launcher to the latest action build.
2. You will get a pop-up to apply the patcher.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
