### ISSUE TITLE
[BUG] <pantalla muy oscura despues de la carga del juego>

### ISSUE THREAD

**Issue by Jjoossuuee3** [PojavLauncherTeam/PojavLauncher#2958]
### Describe the bug

Cuando carga el juego la pantalla esta muy oscura, no se puede distinguir nada de lo que está sucediendo en el juego

### The log file and images/videos

https://user-images.githubusercontent.com/102112954/159381430-f55893c0-5461-4445-9ff8-413481376314.mp4

![Screenshot_20220321-164021_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/102112954/159381448-cf53c198-a292-44d3-a88c-0c18727f53db.jpg)

### Steps To Reproduce

```markdown
1 ingresa al juego
2 espera a que cargue
3 ya esta el error
```

### Expected Behavior

Espero poder ver bien la pantalla del juego

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: la más nueva que esta en la playstore
```

**Comment by GaucovyAero** [comment]
Update to the latest Actions build [here.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

**Comment by Jjoossuuee3** [comment]
> Actualice a la última versión de Acciones [aquí.](https://github.com/PojavLauncherTeam/PojavLauncher/actions)

 Descargue el de ci Android  y cuando intento entrar me saca y me manda eso
java.lang.NullPointerException: Attempt to get length of null array
	at net.kdt.pojavlaunch.Tools.lastFileModified(Tools.java:669)
	at net.kdt.pojavlaunch.fragments.CrashFragment.refreshCrashFile(CrashFragment.java:52)
	at net.kdt.pojavlaunch.fragments.CrashFragment.onResume(CrashFragment.java:42)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:3039)
	at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer.updateFragmentMaxLifecycle(FragmentStateAdapter.java:726)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer$1.onPageScrollStateChanged(FragmentStateAdapter.java:632)
	at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrollStateChanged(CompositeOnPageChangeCallback.java:87)
	at androidx.viewpager2.widget.CompositeOnPageChangeCallback.onPageScrollStateChanged(CompositeOnPageChangeCallback.java:87)
	at androidx.viewpager2.widget.ScrollEventAdapter.dispatchStateChanged(ScrollEventAdapter.java:426)
	at androidx.viewpager2.widget.ScrollEventAdapter.onScrolled(ScrollEventAdapter.java:214)
	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5338)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
	at android.view.Choreographer.doFrame(Choreographer.java:740)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8570)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by llorona09** [comment]
ami me pasa lo mismo pero cuando entro a jugar se ve todo oscuro menos los controles y cuando grabo o me voy a cambiar controles se ve todo
