### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by ZenZenXD** [PojavLauncherTeam/PojavLauncher#296]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 9/1/20 7:36 PM
Description: Rendering Block Entity

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bnp.a(SourceFile:126)
	at bhk.a(SourceFile:76)
	at bhk.a(SourceFile:38)
	at bhk.a(SourceFile:21)
	at bhc.a(SourceFile:114)
	at bhc.a(SourceFile:102)
	at bfr.a(SourceFile:615)
	at bfk.a(SourceFile:1244)
	at bfk.b(SourceFile:1149)
	at bfk.a(SourceFile:1002)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at bnp$1.a(SourceFile:47)
	at bnp$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bnp.a(SourceFile:126)
	at bhk.a(SourceFile:76)
	at bhk.a(SourceFile:38)

-- Block Entity Details --
Details:
	Name: Skull // alo
	Block type: ID #144 (tile.skull // ajm)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-73,118,115), Chunk: (at 7,7,3 in -5,7; contains blocks -80,0,112 to -65,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #144 (tile.skull // ajm)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at b.a(SourceFile:244)
	at bhc.a(SourceFile:117)
	at bhc.a(SourceFile:102)
	at bfr.a(SourceFile:615)
	at bfk.a(SourceFile:1244)
	at bfk.b(SourceFile:1149)
	at bfk.a(SourceFile:1002)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:973)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:2)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)

-- Affected level --
Details:
	Level name: MpServer
	All players: 5 total; [bew['Monkeyy_D_Luffy'/3543, l='MpServer', x=-62.50, y=115.00, z=91.50], bex['§eClick'/10, l='MpServer', x=-70.50, y=116.00, z=91.50], bex['§eClick'/4, l='MpServer', x=-91.50, y=114.00, z=88.50], bex['§eClick'/7, l='MpServer', x=-91.50, y=114.00, z=94.50], bex['§7Brownbeard'/1, l='MpServer', x=-106.53, y=104.00, z=87.56]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -63.00,115.00,91.00 - World: (-63,115,91), Chunk: (at 1,7,11 in -4,5; contains blocks -64,0,80 to -49,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 140774 game time, 13200 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 24 total; [um['§7► §fClick an npc'/2272, l='MpServer', x=-70.50, y=116.66, z=99.50], bex['§7Brownbeard'/1, l='MpServer', x=-106.53, y=104.00, z=87.56], um['§f§lWelcome to §e§lLegends§6§lMC'/2273, l='MpServer', x=-70.50, y=117.25, z=83.50], bew['Monkeyy_D_Luffy'/3543, l='MpServer', x=-62.50, y=115.00, z=91.50], um['§eChoose a server to start'/2274, l='MpServer', x=-70.50, y=116.97, z=83.50], um['§7§fOnline Players §7► §e108'/2275, l='MpServer', x=-70.50, y=116.66, z=83.50], bex['§eClick'/10, l='MpServer', x=-70.50, y=116.00, z=91.50], bex['§eClick'/4, l='MpServer', x=-91.50, y=114.00, z=88.50], um['§7§fOnline Players §7► §e75'/2276, l='MpServer', x=-91.50, y=116.25, z=88.50], bex['§eClick'/4, l='MpServer', x=-91.50, y=114.00, z=88.50], um['§6§lSkyblock'/2277, l='MpServer', x=-91.50, y=116.00, z=88.50], bex['§eClick'/7, l='MpServer', x=-91.50, y=114.00, z=94.50], um['§7§fOnline Players §7► §e30'/2278, l='MpServer', x=-91.50, y=116.25, z=94.50], bex['§eClick'/7, l='MpServer', x=-91.50, y=114.00, z=94.50], um['§6§lSurvival [BETA]'/2279, l='MpServer', x=-91.50, y=116.00, z=94.50], um['§eCosmetic Crate'/2280, l='MpServer', x=-67.50, y=116.19, z=37.50], um['§7Coming Soon'/2281, l='MpServer', x=-67.50, y=115.94, z=37.50], bex['§eClick'/10, l='MpServer', x=-70.50, y=116.00, z=91.50], um['§a§lEVENT FINISHED'/2282, l='MpServer', x=-70.50, y=118.53, z=91.50], um['§7§fOnline Players §7► §e1'/2283, l='MpServer', x=-70.50, y=118.28, z=91.50], um['§d§lPARKOUR EVENT'/2284, l='MpServer', x=-70.50, y=118.03, z=91.50], uk['§d§lENDER BOSS UPDATE §f» §e§l§nUPDATE LIVE'/2147473667, l='MpServer', x=-110.50, y=115.00, z=91.50], um['§e§lHow to Connect'/2270, l='MpServer', x=-70.50, y=117.25, z=99.50], um['§7► §fClick the compass in your inventory'/2271, l='MpServer', x=-70.50, y=116.97, z=99.50]]
	Retry entities: 0 total; []
	Server brand: FlameCord <- Paper
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (armv8l) version 4.14.98-perf+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (OPPO CPH1933, Android 9), The Android Project
	Memory: 0 bytes (0 MB) / 273643336 bytes (260 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.8.9
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 4 (v8l)

**Comment by WesleyVanNeck** [comment]
dublicated from #173
