### ISSUE TITLE
[BUG] <sodium>

### ISSUE THREAD

**Issue by kuzy21** [PojavLauncherTeam/PojavLauncher#2960]
### Describe the bug

It closes the game when I want to join a sever or world  on 1.18.2

### The log file and images/videos

No

### Steps To Reproduce

```markdown
Use optifine but doesn't want to
```

### Expected Behavior

To run 

### Platform

```markdown
- Device model: s20 fe
- CPU architecture: 64arm
- Android version:12 
- PojavLauncher version: idk
```

### Anything else?

Pls tell me how to fix

**Comment by Pgabrielmnecraft** [comment]
How can i help with out the log? It's important.

**Comment by GaucovyAero** [comment]
Pirate detected. Buy the game if you want it to not crash. The crash is likely happening because of the Mojang Authentication System/YggdrasilAuthenticationService.

**Comment by kuzy21** [comment]
But I did buy the game

**Comment by kuzy21** [comment]
Here Is pic

**Comment by kuzy21** [comment]
![Screenshot_20220322-131546_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/88117142/159568084-cdc724cf-1f09-477c-8939-68f6f5ac49bc.jpg)

**Comment by kuzy21** [comment]
Ok I get log

**Comment by kuzy21** [comment]
[00:42:22] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[00:42:22] [main/INFO]: Loading 47 mods:
	- fabric 0.48.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.2+2540745460 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- java 17
	- minecraft 1.18.2
	- org_joml_joml 1.10.2 via sodium
	- sodium 0.4.1+build.15
[00:42:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[00:42:23] [main/INFO]: Compatibility level set to JAVA_16
[00:42:23] [main/INFO]: Compatibility level set to JAVA_17
[00:42:23] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[00:42:29] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zdf000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[00:42:31] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[00:42:31] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[00:42:31] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[00:42:32] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:42:34] [Render thread/INFO]: Setting user: Teqoo0
[00:42:35] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[00:42:36] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[00:42:37] [Render thread/WARN]: Removed resource pack assets-v0.zip from options because it is no longer compatible
[00:42:40] [Render thread/WARN]: ERROR : Couldn't load Narrator library
java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna12362854931116309484.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna12362854931116309484.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:751) ~[?:?]
	at java.lang.System.load(System.java:1912) ~[?:?]
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045) ~[jna-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015) ~[jna-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87) ~[jna-5.10.0.jar:5.10.0 (b0)]
	at com.mojang.text2speech.NarratorLinux.<clinit>(NarratorLinux.java:18) [text2speech-1.12.4.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:21) [text2speech-1.12.4.jar:?]
	at net.minecraft.class_333.<init>(class_333.java:26) [client-intermediary.jar:?]
	at net.minecraft.class_333.<clinit>(class_333.java:24) [client-intermediary.jar:?]
	at net.minecraft.class_329.<init>(class_329.java:165) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:593) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
[00:42:40] [Render thread/INFO]: Reloading ResourceManager: Default, assets-v0.zip, Fabric Mods (Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Sodium)
[00:42:49] [Render thread/INFO]: OpenAL initialized on device OpenSL
[00:42:49] [Render thread/INFO]: Sound engine started
[00:42:51] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[00:42:51] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[00:42:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[00:42:51] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[00:42:51] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[00:42:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[00:42:51] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[00:42:55] [Render thread/WARN]: Shader rendertype_text could not find sampler named Sampler2 in the specified shader program.
[00:42:55] [Render thread/WARN]: Shader rendertype_text_intensity could not find sampler named Sampler2 in the specified shader program.
[00:42:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[00:42:56] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[00:42:56] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[00:43:01] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[00:43:09] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:43:09] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:43:10] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:43:10] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[00:43:10] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[00:43:11] [Render thread/INFO]: Loaded 7 recipes
[00:43:12] [Render thread/INFO]: Loaded 1141 advancements
[00:43:16] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:43:16] [Render thread/INFO]: Applied 0 biome modifications to 0 of 61 new biomes in 15.28 ms
[00:43:16] [Server thread/INFO]: Starting integrated minecraft server version 1.18.2
[00:43:16] [Server thread/INFO]: Generating keypair
[00:43:17] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[00:43:28] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:28] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:29] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:29] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:29] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:29] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:30] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:30] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:30] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:30] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:30] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:30] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:31] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:31] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:31] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:31] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:31] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:31] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:31] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:41] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:41] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:41] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:42] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:43] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:44] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:45] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:46] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:46] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:47] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:47] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:48] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:48] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:49] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:50] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:50] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:50] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:51] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:51] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:52] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:52] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:53] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:53] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:54] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:54] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:55] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:55] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:56] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:56] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:57] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:57] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:58] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:58] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:59] [Render thread/INFO]: Preparing spawn area: 0%
[00:43:59] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:00] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:00] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:01] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:01] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:02] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:02] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:03] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:03] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:04] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:04] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:05] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:06] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:06] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:06] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:07] [Render thread/INFO]: Preparing spawn area: 0%
[00:44:07] [Render thread/INFO]: Preparing spawn area: 1%
[00:44:08] [Render thread/INFO]: Preparing spawn area: 1%
[00:44:08] [Render thread/INFO]: Preparing spawn area: 4%
[00:44:09] [Render thread/INFO]: Preparing spawn area: 4%
[00:44:09] [Render thread/INFO]: Preparing spawn area: 4%
[00:44:10] [Render thread/INFO]: Preparing spawn area: 4%
[00:44:10] [Render thread/INFO]: Preparing spawn area: 4%
[00:44:11] [Render thread/INFO]: Preparing spawn area: 4%
[00:44:11] [Render thread/INFO]: Preparing spawn area: 4%
[00:44:12] [Render thread/INFO]: Preparing spawn area: 7%
[00:44:12] [Render thread/INFO]: Preparing spawn area: 12%
[00:44:13] [Render thread/INFO]: Preparing spawn area: 22%
[00:44:13] [Render thread/INFO]: Preparing spawn area: 22%
[00:44:14] [Render thread/INFO]: Preparing spawn area: 35%
[00:44:14] [Render thread/INFO]: Preparing spawn area: 35%
[00:44:15] [Render thread/INFO]: Preparing spawn area: 35%
[00:44:15] [Render thread/INFO]: Preparing spawn area: 61%
[00:44:16] [Render thread/INFO]: Preparing spawn area: 61%
[00:44:17] [Render thread/INFO]: Preparing spawn area: 69%
[00:44:17] [Render thread/INFO]: Preparing spawn area: 69%
[00:44:17] [Render thread/INFO]: Preparing spawn area: 69%
[00:44:18] [Render thread/INFO]: Preparing spawn area: 90%
[00:44:18] [Render thread/INFO]: Preparing spawn area: 98%
[00:44:18] [Render thread/INFO]: Time elapsed: 61092 ms
[00:44:19] [Server thread/INFO]: Changing view distance to 8, from 10
[00:44:19] [Server thread/INFO]: Changing simulation distance to 5, from 0
[00:44:19] [Render thread/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: fe:63:8b:54:9b:eb:ae:e6
[00:44:20] [Server thread/INFO]: Teqoo0[local:E:c1f1ac84] logged in with entity id 127 at (-645.9306505305472, 4.0, 55.63773025196298)
[00:44:20] [Server thread/INFO]: Teqoo0 joined the game
[00:44:20] [Server thread/INFO]: Teqoo0 has made the advancement [Cover Me with Diamonds]
[00:44:21] [Render thread/INFO]: Started 2 worker threads
[00:44:21] [Render thread/INFO]: [CHAT] Teqoo0 has made the advancement [Cover Me with Diamonds]
[00:44:21] [Render thread/INFO]: Loaded 7 advancements
[00:44:22] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.vsh: ERROR: 0:26: 'switch' : Reserved word. 
ERROR: 0:26: 'switch' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 2 compilation errors.  No code generated.


[00:44:22] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221) ~[sodium-fabric-mc1.18.2-0.4.1+build.15.jar:?]
	at net.minecraft.class_761.method_3251(class_761.java:5466) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1034) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:813) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
[00:44:23] [Server thread/INFO]: Stopping server
[00:44:23] [Server thread/INFO]: Saving players
[00:44:23] [Server thread/INFO]: Teqoo0 lost connection: Server closed
[00:44:23] [Server thread/INFO]: Teqoo0 left the game
[00:44:23] [Server thread/INFO]: Stopping singleplayer server as player logged out
[00:44:23] [Server thread/INFO]: Saving worlds
[00:44:27] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[00:44:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[00:44:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[00:44:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World-): All chunks are saved
[00:44:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[00:44:28] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[00:44:28] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[00:44:28] [Render thread/INFO]: Stopping worker threads

**Comment by kuzy21** [comment]
Also Aerolome watch ur mouth ok

**Comment by kuzy21** [comment]
So how to fix?

**Comment by kuzy21** [comment]
So how can I fix it

**Comment by GaucovyAero** [comment]
Sodium for 1.18.2 isn't compatible with pojav. Latest compatible is Sodium 0.1.0 for Minecraft 1.16.3 (Works on 1.16.5).

**Comment by kuzy21** [comment]
Ok thx

**Comment by kuzy21** [comment]
Very much
