### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Sah1ep** [PojavLauncherTeam/PojavLauncher#2964]
### Describe the bug

 arm64 mimarisi Java Runtime arm ile uyumsuz.

### The log file and images/videos

java.lang.RuntimeException: arm64 mimarisi Java Runtime arm ile uyumsuz.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
Xd
```

### Expected Behavior

Oyunum başlaması gerekiyor

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
Join the official PojavLauncher discord server and first verify yourself. Then ask someone for the guide on how to install 1.17+.

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
