### ISSUE TITLE
[Bug] <Short description> crash with gamepad

### ISSUE THREAD

**Issue by Kshantir** [PojavLauncherTeam/PojavLauncher#2965]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setInt(java.lang.Object, int)' on a null object reference
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.setDummyEventKeycode(GamepadDpad.java:76)
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.convertEvent(GamepadDpad.java:67)
	at net.kdt.pojavlaunch.customcontrols.gamepad.Gamepad.update(Gamepad.java:158)
	at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:593)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:541)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processGenericMotionEvent(ViewRootImpl.java:6717)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6457)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5888)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6076)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6133)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6109)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6283)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:337)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setInt(java.lang.Object, int)' on a null object reference
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.setDummyEventKeycode(GamepadDpad.java:76)
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.convertEvent(GamepadDpad.java:67)
	at net.kdt.pojavlaunch.customcontrols.gamepad.Gamepad.update(Gamepad.java:158)
	at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:593)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:541)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processGenericMotionEvent(ViewRootImpl.java:6717)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6457)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5888)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6076)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6133)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6109)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6283)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:337)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### Steps To Reproduce

```markdown
1
```

### Expected Behavior

I expected that i will can play with gamepad as usual, but...

### Platform

```markdown
- Device model:poco x3 pro
- CPU architecture:cant remember
- Android version:12
- PojavLauncher version:last on google
```

**Comment by DovydasTEDS** [comment]
Old version, on github click on actions, the latest one with green tick and then download app-debug.apk

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.

**Comment by Kshantir** [comment]
Can i play without license or account? Just offline account?

ср, 23 мар. 2022 г., 19:53 DovydasTEDS ***@***.***>:
