### ISSUE TITLE
1.18.2 not working on chromebook 4

### ISSUE THREAD

**Issue by MassiveBeefJrky** [PojavLauncherTeam/PojavLauncher#2975]
### Describe the bug

When I launch 1.18.2 I get an error even though I downloaded the right java runtime.

### The log file and images/videos

java.lang.RuntimeException: Architecture x86_64 is incompatible with Java Runtime x86.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)

### Steps To Reproduce

```markdown
1. Start Pojav on Samsung Chromebook 4
2. Start 1.18.2 
3. 1.18.2 doesn't start
4. Gives error
```

### Expected Behavior

I expect 1.18.2 to launch

### Platform

```markdown
- Device model: Samsung Chromebook 4
- CPU architecture: x86
- Android version: 9
- PojavLauncher version: newest
```

**Comment by kuzy21** [comment]
Did you patch 1.18.2

**Comment by kuzy21** [comment]
Use this: https://cdn.discordapp.com/attachments/724163890803638277/922043517860212736/Pojav117AssetsPatcher.jar 
And then patch 1.18.2

**Comment by barrelcrowd9741** [comment]
a mi tampoco me corre

**Comment by khanhduytran0** [comment]
You picked the 32bit Java while your Chromebook is 64bit. Try again with x86_64 java.
