### ISSUE TITLE
Game crashes when i connect controller

### ISSUE THREAD

**Issue by Eduard2010gh** [PojavLauncherTeam/PojavLauncher#2998]
### Describe the bug

Game crashed when I try to play with a dualshock controller

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setInt(java.lang.Object, int)' on a null object reference
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.setDummyEventKeycode(GamepadDpad.java:76)
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.convertEvent(GamepadDpad.java:67)
	at net.kdt.pojavlaunch.customcontrols.gamepad.Gamepad.update(Gamepad.java:158)
	at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:593)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:987)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processGenericMotionEvent(ViewRootImpl.java:7853)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7571)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6901)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7122)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7179)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6932)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6905)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6958)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6924)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7155)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7342)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3399)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2960)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2951)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3376)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Start 1.16.5
3.Press x to connect controller
4.Move joystick or press any other button
5.Game crash
```

### Expected Behavior

I expect the game to not crash

### Platform

```markdown
- Device model: Samsung Galaxy Tab S7 FE
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest Release [crocus-v3_openjdk]
```

**Comment by GaucovyAero** [comment]
crocus-v3_openjdk is definitely not latest and it's over a YEAR old now. Update to the latest one by clicking on Actions here on GitHub, clicking a build that has the green checkmark and just download app-debug.apk. Then just install and you're ready to go.

**Comment by Eduard2010gh** [comment]
> crocus-v3_openjdk is definitely not latest and it's over a YEAR old now. Update to the latest one by clicking on Actions here on GitHub, clicking a build that has the green checkmark and just download app-debug.apk. Then just install and you're ready to go.

I tried doing that's and it's saying my account is local

**Comment by WesleyVanNeck** [comment]
> > crocus-v3_openjdk is definitely not latest and it's over a YEAR old now. Update to the latest one by clicking on Actions here on GitHub, clicking a build that has the green checkmark and just download app-debug.apk. Then just install and you're ready to go.
> 
> I tried doing that's and it's saying my account is local

piracy detected buy the game to get support

**Comment by Eduard2010gh** [comment]
> > > crocus-v3_openjdk is definitely not latest and it's over a YEAR old now. Update to the latest one by clicking on Actions here on GitHub, clicking a build that has the green checkmark and just download app-debug.apk. Then just install and you're ready to go.
> > 
> > 
> > I tried doing that's and it's saying my account is local
> 
> piracy detected buy the game to get support

I bought the game

**Comment by Eduard2010gh** [comment]
I have proof

**Comment by ghost** [comment]
Make sure to log in with your Microsoft account.

**Comment by Eduard2010gh** [comment]
The debug version worked nvm

**Comment by Eduard2010gh** [comment]
*

**Comment by Eduard2010gh** [comment]
And it's happening again

**Comment by GaucovyAero** [comment]
send logs moment

**Comment by SprainedSpark89** [comment]
You may have to turn down the memory or it's using memory that it doesn't have

**Comment by mchnjt** [comment]
> You may have to turn down the memory or it's using memory that it doesn't have

Since when did controller use memory?

**Comment by SprainedSpark89** [comment]
Bluetooth and convert the controls to work (don't recomend external controls very wacky/broken)

**Comment by Thollp** [comment]
> Make sure to log in with your Microsoft account.

You can't, I try login with Microsoft account to play online account just for me play with forge without turn off internet connection before join the world, it does not work

**Comment by Thollp** [comment]
> > Make sure to log in with your Microsoft account.
> 
> You can't, I try login with Microsoft account to play online account just for me play with forge without turn off internet connection before join the world, it does not work

and I still don't know why.

**Comment by Thollp** [comment]
And also, I already know why I can't enter world with forge mod loader so please don't tell me

**Comment by Thollp** [comment]
> > Make sure to log in with your Microsoft account.
> 
> You can't, I try login with Microsoft account to play online account just for me play with forge without turn off internet connection before join the world, it does not work

I already tried login with my actual Microsoft account, not my github account that appears when it said "more options to login", it still not work

**Comment by Eduard2010gh** [comment]
It finally worked

**Comment by SprainedSpark89** [comment]
good for you!!! but aren't your controls messed up?

**Comment by mchnjt** [comment]
iSprainedMyAnkle69 😱😱😱
