### ISSUE TITLE
How do i fix

### ISSUE THREAD

**Issue by DeviateBacon3** [PojavLauncherTeam/PojavLauncher#3009]
### Describe the bug

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:95)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
But I am using the  default Java

### The log file and images/videos

No I can't 

### Steps To Reproduce

```markdown
I start Minecraft it give me the error
```

### Expected Behavior

I tried java 17

### Platform

```markdown
- Device model: idk
- CPU architecture: 
- Android version: 11
- PojavLauncher version:
```

**Comment by kuzy21** [comment]
What version of minecraft r u running

**Comment by DeviateBacon3** [comment]
1.8.9

**Comment by SprainedSpark89** [comment]
use java 8 not 17

**Comment by DeviateBacon3** [comment]
> use java 8 not 17

I cant it is a 1.18
