### ISSUE TITLE
[BUG] <Short description>--- Minecraft Crash Report ---- // Quite honestly, 

### ISSUE THREAD

**Issue by Amir8881** [PojavLauncherTeam/PojavLauncher#3015]
### Describe the bug

Скачал плазмо войс после нажатия на в получается настроить мод он вылетает и выходит данная ошибка  
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 02.04.2022, 15:43
Description: Unexpected error

java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.NativeLibrary
	at su.plo.voice.rnnoise.Denoiser$RNNoise.<clinit>(Denoiser.java:95)
	at su.plo.voice.rnnoise.Denoiser.platformSupported(Denoiser.java:80)
	at su.plo.voice.client.gui.tabs.AdvancedTabWidget.<init>(AdvancedTabWidget.java:26)
	at su.plo.voice.client.gui.VoiceSettingsScreen.method_25426(VoiceSettingsScreen.java:181)
	at net.minecraft.class_437.method_25423(class_437.java:387)
	at net.minecraft.class_310.method_1507(class_310.java:984)
	at su.plo.voice.client.VoiceClientFabric.lambda$onInitializeClient$3(VoiceClientFabric.java:131)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zzo000$onEndTick(class_310.java:3573)
	at net.minecraft.class_310.method_1574(class_310.java:1806)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at su.plo.voice.rnnoise.Denoiser$RNNoise.<clinit>(Denoiser.java:95)
	at su.plo.voice.rnnoise.Denoiser.platformSupported(Denoiser.java:80)
	at su.plo.voice.client.gui.tabs.AdvancedTabWidget.<init>(AdvancedTabWidget.java:26)
	at su.plo.voice.client.gui.VoiceSettingsScreen.method_25426(VoiceSettingsScreen.java:181)
	at net.minecraft.class_437.method_25423(class_437.java:387)
	at net.minecraft.class_310.method_1507(class_310.java:984)
	at su.plo.voice.client.VoiceClientFabric.lambda$onInitializeClient$3(VoiceClientFabric.java:131)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zzo000$onEndTick(class_310.java:3573)

-- Affected level --
Details:
	All players: 8 total; [class_746['amir15888'/169243, l='ClientLevel', x=-276.13, y=65.00, z=-143.87], class_745['lololoh24'/84235, l='ClientLevel', x=-249.53, y=65.06, z=-138.87], class_745['_KpaKuN'/39520, l='ClientLevel', x=-262.76, y=65.00, z=-145.93], class_745['BazertGG'/1, l='ClientLevel', x=-274.30, y=66.00, z=-141.05], class_745['Utochkav2010'/129284, l='ClientLevel', x=-275.74, y=65.00, z=-139.10], class_745['MrArche_'/133471, l='ClientLevel', x=-275.89, y=65.06, z=-141.61], class_745['KaMMon_'/23101, l='ClientLevel', x=-277.14, y=65.06, z=-141.93], class_745['XuTpbIu_JluCeHok'/163462, l='ClientLevel', x=-276.90, y=65.00, z=-139.50]]
	Chunk stats: 225, 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (-187,71,-2110), Section: (at 5,7,2 in -12,4,-132; chunk contains blocks -192,0,-2112 to -177,255,-2097), Region: (-1,-5; contains chunks -32,-160 to -1,-129, blocks -512,0,-2560 to -1,255,-2049)
	Level time: 153391 game time, 39408714 day time
	Server brand: Airplane
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, assets-v0.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (aarch64) version Android-9
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 404361384 bytes (385 MiB) / 1308622848 bytes (1248 MiB) up to 1308622848 bytes (1248 MiB)
	CPUs: 7
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 1 (aarch64)
	Identifier: 0x51 Family 8 Model 0x800 Stepping r0xap4
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 3842,96
	Virtual memory used (MB): 4351,04
	Swap memory total (MB): 2048,00
	Swap memory used (MB): 1231,25
	JVM Flags: 2 total; -Xms1248M -Xmx1248M
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 1024x640
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: assets-v0.zip
	Current Language: Русский (Россия)
	CPU: 8x AArch64 Processor rev 1 (aarch64)

### The log file and images/videos

Это плазмо войс для версии 1.17.1

### Steps To Reproduce

```markdown
Запустил лаунчер зашел на сервер и когда хочу активировать мод плазмо войс на разговоры маин простотговорит сохранение мира вылетает и ошибка 1
```

### Expected Behavior

Должно было быть меню мода и настройка его самого и уже разговаривать

### Platform

```markdown
- Device model: самсунг таб с 4
- CPU architecture: arm64-v8a
- Android version: 9
- PojavLauncher version: последняя с плей маркета
```

**Comment by artdeell** [comment]
Жди обновления мода, с программным энкодером. До этого он работать не будет.

**Comment by Amir8881** [comment]
Привет объясните что вы написали

сб, 2 апр. 2022 г., 21:53 ArtDev ***@***.***>:

**Comment by Mathias-Boulay** [comment]
#1948
