### ISSUE TITLE
[BUG] 1.8.9 Labymod Crashes Upon Startup

### ISSUE THREAD

**Issue by PugBroKid** [PojavLauncherTeam/PojavLauncher#3020]
### Describe the bug

I launched 1.8.9 Labymod and it got to 75% and crashed 

https://user-images.githubusercontent.com/95888812/161453564-c6b65b3e-39c5-498c-b6c7-c4535dbeb84b.mp4

### The log file and images/videos

https://user-images.githubusercontent.com/95888812/161453564-c6b65b3e-39c5-498c-b6c7-c4535dbeb84b.mp4
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 4/3/22 11:20 PM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:44)
	at net.labymod.main.LabyMod.init(LabyMod.java:339)
	at ave.am(SourceFile:470)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:44)
	at net.labymod.main.LabyMod.init(LabyMod.java:339)
	at ave.am(SourceFile:470)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1488479952 bytes (1419 MB) / 2122317824 bytes (2024 MB) up to 2122317824 bytes (2024 MB)
	JVM Flags: 3 total; -Xms2111M -Xmx2111M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 2

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Sign in (I did offline idk about online(
3. install labyMod 1.8.9 (i had all of the optional files)
4. Launch LabyMod 1.8.9
(Wait Until Launch)

Done
```

### Expected Behavior

Expected it to get to 100% and go to the main menu

### Platform

```markdown
- Device model: Chromebook 
- CPU architecture: x86_64
- Android version: 9
- PojavLauncher version: Latest for android
```

### Anything else?

it works with 1.12 and 1.16 works but the mouse capture doesnt work.

**Comment by kuzy21** [comment]
Use gl4s 1.14

**Comment by artdeell** [comment]
LabyMod 1.8.9 is not supported without workarounds
