### ISSUE TITLE
Jre17 not work

### ISSUE THREAD

**Issue by Luke14jXX2nd** [PojavLauncherTeam/PojavLauncher#3027]
### Describe the bug

I clicked play when i had java runtime 17 as default and it crashed and gave me a error and wont let me play and i tried switching to the one it gives you but that didn't work either.

### The log file and images/videos

java.lang.RuntimeException: Architecture arm is incompatible with Java Runtime aarch64.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
I do not know what to put here
```

### Expected Behavior

Above is description

### Platform

```markdown
- Device model: LG LMK500
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest release
```

**Comment by WesleyVanNeck** [comment]
use arm as your dvive aint aarch64

**Comment by SprainedSpark89** [comment]
'-' try installing arm jre 17
