### ISSUE TITLE
Error when starting 1.16.2

### ISSUE THREAD

**Issue by mangotango69202** [PojavLauncherTeam/PojavLauncher#303]
java.lang.RuntimeException: java.lang.RuntimeException: Server returned HTTP 206: Partial Content
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:530)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:568)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: Server returned HTTP 206: Partial Content
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:32)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

**Comment by nicknickeryt** [comment]
PojavLauncher v2 actually supports versions up to 1.11.2

**Comment by khanhduytran0** [comment]
V3 support and run well, but not yet finished (no input support yet). Join our discord server to track current progress.
