### ISSUE TITLE
[BUG] The microsoft account login doesn't work.

### ISSUE THREAD

**Issue by zenithwzj** [PojavLauncherTeam/PojavLauncher#3039]
### Describe the bug

Microsoft login error:
It doesn't work after i signed in the popup window.

### The log file and images/videos

**information below**
```log
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:312)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Press "MICROSOFT LOGIN"
3. Sign in to your microsoft account(already registered on minecraft.net)
4. Go back to the application(there is a button to go back)
5. Wait the app to load.
6. See the popup window of "Error"
```

### Expected Behavior

I expect to login by microsoft account.I've just migrated my account on minecraft.net , and I can't login by mojang account after it was migrated.

### Platform

```markdown
- Device model: Huawei M6 4/64G
- CPU architecture: ARM
- Android version: HARMONY OS 2.0.0
- PojavLauncher version: version 3.3.1.1 app-debug.apk
```

### Anything else?

(I've tried other apps to launch minecraft java edition on andriod devices,but also failed)

**Comment by zenithwzj** [comment]
Should I use a vpn?

**Comment by 1493028** [comment]
> Should I use a vpn?

Try it use vpn

**Comment by jorgieee** [comment]
Use the newest version of pojavlaucher

**Comment by zenithwzj** [comment]
> Use the newest version of pojavlaucher

[information page](https://github.com/PojavLauncherTeam/PojavLauncher/releases/tag/v3.3.1.1)

[v3.3.1.1-app_debug.apk download](https://github.com/PojavLauncherTeam/PojavLauncher/releases/download/v3.3.1.1/app-debug.apk)

**Comment by Smokeybear12** [comment]
Use the latest action build. That version is over a year old.

**Comment by zenithwzj** [comment]
so where to download the latest one?i dont have a vpn to use GPlay

**Comment by phantom12355** [comment]
try aoxvpn
it's free

**Comment by Smokeybear12** [comment]
Download the latest action build. Preferably the latets from the v3_openjdk branch. 

![6240E056-ADD0-474D-89F0-3726890ACA80](https://user-images.githubusercontent.com/86984307/162367722-2b78fe89-9ee2-4dbc-875d-37961ca1149b.jpeg)

**Comment by zenithwzj** [comment]
i used vpn and [the latest one](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2143451817).Then i tried it again after i closed the vpn it still didn't work

**Comment by zenithwzj** [comment]
anyone?

**Comment by artdeell** [comment]
Microsoft account not set up properly

**Comment by Pojavlauncheruser123** [comment]
How to fix login errror

**Comment by ghosthuntr3** [comment]
I tried to log in with my Microsoft account but it didn't work! I have the game on play pass but pojavlauncher keeps saying- error not found! SOMEONE HELP IM LOSING MY MIND OVER THIS

**Comment by Louezalbis** [comment]
pojava bug 






java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
