### ISSUE TITLE
Microsoft account login error 

### ISSUE THREAD

**Issue by bubbelbadHD** [PojavLauncherTeam/PojavLauncher#3040]
### Describe the bug

java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### The log file and images/videos

No crash detected

### Steps To Reproduce

```markdown
1. Start pojav launcher
2. Try to login with microsoft
```

### Expected Behavior

I expect it to login because I bought the game and its connected to a parent account.

### Platform

```markdown
- Device model: mido
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest one
```

### Anything else?

I am facing this issue from 2 months please anybody give me a fix.

**Comment by Thollp** [comment]
> Make sure that you have brought/migrated to your Microsoft account

I also face the same issue. But the reason why I quote this one of the part of issue is because @Mathias-Boulay  said to me that I need to buy minecraft java on the account and link it.

**Comment by bubbelbadHD** [comment]
I have bought minecraft Java it works with pc launcher but not here. I'm using pojav because my pc has gone for repairing

**Comment by Thollp** [comment]
> I have bought minecraft Java it works with pc launcher but not here. I'm using pojav because my pc has gone for repairing

What account you use on java, mojang or microsoft?

**Comment by bubbelbadHD** [comment]
Ofcource Microsoft account

**Comment by Thollp** [comment]
> Ofcource Microsoft account

I finally run out of solution, but I still want to help you solve this problem

**Comment by Thollp** [comment]
> > Ofcource Microsoft account
> 
> I finally run out of solution, but I still want to help you solve this problem



The only solution I have is download playstore version or play the older action build version where there is an option to use offline account

**Comment by bubbelbadHD** [comment]
I wanna play hypixel and I have the pojavlauncher from playstore

**Comment by Thollp** [comment]
I will private message you

**Comment by Thollp** [comment]
What's your email

**Comment by Mathias-Boulay** [comment]
👀

**Comment by Thollp** [comment]
> I wanna play hypixel and I have the pojavlauncher from playstore

I finally ran out of solutions

**Comment by Thollp** [comment]
I knew it now, your microsoft account must have to be migrated from mojang account. If don't, you can only play offline account on pojav.

**Comment by bubbelbadHD** [comment]
Oh ok now it started working...Thank you guys for helping me :)

**Comment by Johnraven3300894** [comment]
Pls fix the Microsoft account I can not login my account

**Comment by Thollp** [comment]
> Pls fix the Microsoft account I can not login my account

You must have to buy Minecraft(and login) to be able to login microsoft account in Pojav. And if you already buy it earlier, I have no solution for the problem (because it seems that this is the microsoft login problem which some of the pojav playes already face this problem)

**Comment by DarkOutfi** [comment]
I was putting a microsorft account and when I put it it was not entering

**Comment by PojavFan777122** [comment]
my mistake java.lang.RuntimeException: 

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "error" : "NOT_FOUND",
  "errorMessage" : "Not Found"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Mess909** [comment]
Bantu
