### ISSUE TITLE
[BUG] <When I plug the ps4 controller into my phone and control it inside the game, pojavlancher takes me out and the game shuts down by itself 

### ISSUE THREAD

**Issue by Omar7575** [PojavLauncherTeam/PojavLauncher#3047]
### Describe the bug

When I plug the ps4 controller into my phone and control it inside the game, pojavlancher takes me out and the game shuts down by itself

### The log file and images/videos

![Screenshot_20220407-214742_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/103256207/162425807-2811363e-2651-43f5-b29a-b35e3fe93a8c.jpg)

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Samsung galaxy A52s 5g
- CPU architecture: snap dragon 778G 5g
- Android version: 12
- PojavLauncher version: latest version
```

### Anything else?

No

**Comment by domportera** [comment]
I get this same issue with the Razer kishi USB controller. The crash happens as soon as an input on the controller is pressed.

Here's the full error log:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setInt(java.lang.Object, int)' on a null object reference
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.setDummyEventKeycode(GamepadDpad.java:76)
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.convertEvent(GamepadDpad.java:67)
	at net.kdt.pojavlaunch.customcontrols.gamepad.Gamepad.update(Gamepad.java:158)
	at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:593)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:503)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processGenericMotionEvent(ViewRootImpl.java:6649)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6392)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5809)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5832)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5840)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5813)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5832)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6014)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5840)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6071)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5813)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5832)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5840)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5813)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5832)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6047)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6205)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3184)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2741)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2732)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3161)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8001)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)
```

Device: LG V60
Android 12
Snapdragon 865 5G

**Comment by Mathias-Boulay** [comment]
Fixed on the release candidate build.
