### ISSUE TITLE
Launcher chashes when setting custom controls

### ISSUE THREAD

**Issue by Pairman** [PojavLauncherTeam/PojavLauncher#306]
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.CustomControlsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at net.kdt.pojavlaunch.value.customcontrols.ControlView.setProperties(ControlView.java:62)
	at net.kdt.pojavlaunch.value.customcontrols.ControlView.setProperties(ControlView.java:44)
	at net.kdt.pojavlaunch.value.customcontrols.ControlView.<init>(ControlView.java:30)
	at net.kdt.pojavlaunch.value.customcontrols.ControlsLayout.addControlView(ControlsLayout.java:57)
	at net.kdt.pojavlaunch.value.customcontrols.ControlsLayout.loadLayout(ControlsLayout.java:45)
	at net.kdt.pojavlaunch.CustomControlsActivity.onCreate(CustomControlsActivity.java:79)
	at android.app.Activity.performCreate(Activity.java:7825)
	at android.app.Activity.performCreate(Activity.java:7814)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more

**Comment by khanhduytran0** [comment]
You are entering Custom controls which is a broken option.

**Comment by Pairman** [comment]
> You are entering Custom controls which is a broken option.

Now I see. Btw, I've had the runtime and jdk set correctly, but JE1.15.2 keeps blank screen on my device(Essential PH-1, Android 10)(Same when using https://github.com/longjunyu2/MCinaBox , maybe it's my device's issue). Is there any way to fix it?
![Screenshot_20200912-185742](https://user-images.githubusercontent.com/18365163/92994156-66c77280-f52a-11ea-9071-abb0ad44d728.png)

**Comment by khanhduytran0** [comment]
Maybe check latestlog.txt?
