### ISSUE TITLE
Crash 1.18.2

### ISSUE THREAD

**Issue by GOPRO12345905920** [PojavLauncherTeam/PojavLauncher#3060]
### Describe the bug

I just download the jre 17 and try to run it and after little time in crash 

### The log file and images/videos

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/9/22, 2:50 PM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:421)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)

### Steps To Reproduce

```markdown
Start pojav
Login 
Download the jre 17
Run 1.18.2 
Crash after sometime
```

### Expected Behavior

I expect it to launch

### Platform

```markdown
- Device model: iBall movie z pro
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by ghost** [comment]
Please! Read other issues and their solutions on this. 

1. Update to the latest actions build.
2. Read the instructions availbile on the website to run versions above 21w37a.

**Comment by GOPRO12345905920** [comment]
Giving this after i try running 1.17.1


---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/10/22, 5:55 AM
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at enb.b(SourceFile:496)
	at enb.a(SourceFile:384)
	at adu.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at ady.a(SourceFile:71)
	at aqv.execute(SourceFile:101)
	at ady.a(SourceFile:70)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)

**Comment by GaucovyAero** [comment]
Your pojav is outdated. Update to the latest one in GitHub Actions.

**Comment by GOPRO12345905920** [comment]
Thank work

**Comment by zoromou** [comment]
Não consegui entrar com a minha conta Microsoft
