### ISSUE TITLE
La 1.16.3 se cierra cuando se abre

### ISSUE THREAD

**Issue by matsus1234** [PojavLauncherTeam/PojavLauncher#307]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1087)
	at net.kdt.pojavlaunch.MainActivity.access$3100(MainActivity.java:37)
	at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at afj.<clinit>(SourceFile:36)
	at afj.a(SourceFile:112)
	at x.a(SourceFile:101)
	at x.<clinit>(SourceFile:63)
	at x.b(SourceFile:89)
	at net.minecraft.client.main.Main.main(SourceFile:64)
	... 5 more

**Comment by WesleyVanNeck** [comment]
English or i will close the issue

**Comment by khanhduytran0** [comment]
@matsus1234 it's on v2, and v2 is not support to run 1.13+
