### ISSUE TITLE
[Error] resource pack not load

### ISSUE THREAD

**Issue by BNaise** [PojavLauncherTeam/PojavLauncher#3083]
### Describe the bug

ERROR: 0:25: 'texture' : no matching overloaded function found 
ERROR: 1 compilation errors.  No code generated.

[04:17:03] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:1
18) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at
 auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:48
2) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.Co
mple
tableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at agf.a(SourceFile:69) ~[agf.class:?]
	at auz.execute(BlockableEventLoop.java:118) ~[auz.class:?]
	at agf.a(SourceFile:68) ~[agf.class:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:212) ~[RenderSystem.class:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:199) ~[RenderSystem.class:?]
	at dsr.e(Window.java:442) ~[dsr.class:?]
	at dyr.f(SourceFile:1147) [dyr.class:?]
	at dyr.e(SourceFile:737) [dyr.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:236) [Main.class:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.3.jar:2.3]
Caused by: java.lang.RuntimeException: could not reload shaders
	at eql.b(GameRenderer.java:708) ~[eql.class:?]
	at eql.a(GameRenderer.java:412) [eql.class:?]
	at agb.a(SourceFile:15) ~[agb.class:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 121 more
Caused by: yw: Invalid shaders/core/rendertype_soli
d.json: Couldn't compile vertex program (assets-v0.zip, rendertype_solid) : ERROR: 0:25: 'texture' : no matching overloaded function found 
ERROR: 1 compilation errors.  No code generated.
	at yw.a(SourceFile:48) ~[yw.class:?]
	at erd.<init>(ShaderInstance.java:227) ~[erd.class:?]
	at erd.<init>(ShaderInstance.java:105) ~[erd.class:?]
	at eql.b(GameRenderer.java:530) ~[eql.class:?]
	at eql.a(GameRenderer.java:412) ~[eql.class:?]
	at agb.a(SourceFile:15) ~[agb.class:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 121 more
Caused by: java.io.IOException: Couldn't compile vertex program (assets-v0.zip, rendertype_solid) : ERROR: 0:25: 'texture' : no matching overloaded function found 
ERROR: 1 compilation errors.  No code generated.
	at dtb.b(Program.java:94) ~[dtb.class:?]
	at dtb.a(Program.java:55) ~[dtb.class:?]
	at erd.a(ShaderInstance.java:272) ~[erd.class:?]
	at erd.<init>(ShaderInstance.java:200) ~[erd.class:?]
	at erd.<init>(ShaderInstance.java:105) ~[erd.class:?]
	at eql.b(GameRenderer.java:530) ~[eql.class:?]
	at eql.a(GameRenderer.java:412) ~[eql.class:?]
	at agb.a(SourceFile:15) ~[agb.class:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	... 121 more

### The log file and images/videos

Resource pack not load

### Steps To Reproduce

```markdown
1.start pojavlauncher version 1.18.2 optifine
2.go to resource pack
3.enable assets-v0.zip
4.then it's reloading
5.and it's again reloading
6.then its not loaded
```

### Expected Behavior

I expect the resource pack was load but not

### Platform

```markdown
- Device model: Redmi Note 7 Pro
- CPU architecture: aarch64
- Android version:10
- PojavLauncher version: [Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by kuzy21** [comment]
Ok use this patcher for 1.17 and up, ONLY FOR OPTIFINE NOTHING ELSE, ok don't choose 1.18
 Or 1.17.5 choose 1.18 optifine U h7 or something like that, here: https://cdn.discordapp.com/attachments/724163890803638277/922043517860212736/Pojav117AssetsPatcher.jar

**Comment by kuzy21** [comment]
And if u want the assist pack here it is, but when u apply you are gonna need to rename it to something else but keep .zip in don't, change that here:https://cdn.discordapp.com/attachments/724163890803638277/923349783589056522/assets-v0.zip

**Comment by BNaise** [comment]
Thanks but with your assets-v0 blocks outline not showing

**Comment by BNaise** [comment]
Thanks

**Comment by BNaise** [comment]
Jorgieee

**Comment by BUGAMING7355** [comment]
I have a new issue now please help me

**Comment by kuzy21** [comment]
No problem:)

**Comment by BNaise** [comment]
But I have another issue please help

**Comment by BNaise** [comment]
your assets-v0 blocks outline not showing
