### ISSUE TITLE
fix vrigl renderer crash latest github pojav 

### ISSUE THREAD

**Issue by MarcyIgop** [PojavLauncherTeam/PojavLauncher#3093]
### Describe the bug

crashing when using virgl renderer

### The log file and images/videos

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/15/22, 10:11 AM
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: 
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:76)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:660)
	at dyr.<init>(SourceFile:473)
	at net.minecraft.client.main.Main.main(SourceFile:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:76)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:660)
	at dyr.<init>(SourceFile:473)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (arm) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 424051144 bytes (404 MiB) / 1027604480 bytes (980 MiB) up to 1027604480 bytes (980 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4601.28
	Virtual memory used (MB): 3548.99
	Swap memory total (MB): 2684.08
	Swap memory used (MB): 740.09
	JVM Flags: 2 total; -Xms980M -Xmx980M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Very likely; Client jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.18.2_HD_U_H6
	OptiFine Build: 20220313-160847
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 8

### Steps To Reproduce

```markdown
1.open pojav 
2. uses virgl renderer
3.crash
```

### Expected Behavior

i dunno wut to put here

### Platform

```markdown
- Device model: Huawei y6p 
- CPU architecture: aarch32 
- Android version: Android 10 
- PojavLauncher version: latest github pojav
```

### Anything else?

i dunno

**Comment by kuzy21** [comment]
Get the latest, latest build from github they fixed it

**Comment by MarcyIgop** [comment]
> Get the latest, latest build from github they fixed it

i installed the latest one but still. no working

**Comment by offbeat-stuff** [comment]
use gl4es in the gl4es extra build it has native optifine support now and gl4es is magnitudes faster than virgl

**Comment by MarcyIgop** [comment]
zink vulkan?

**Comment by Mevin815** [comment]
Virgl not support arm 34 btw how to fix crash When entering the world
