### ISSUE TITLE
java.lang.RuntimeException: MSA Error: 429: Too Many Requests, error stream

### ISSUE THREAD

**Issue by DogeLord081** [PojavLauncherTeam/PojavLauncher#3111]
### Describe the bug

This happened when I tried to run 1.18.2 on my unc0ver 14.4.2 iPhone 12:

java.lang.RuntimeException: MSA Error: 429: Too Many Requests, error stream:
{
  "path" : "/authentication/login_with_xbox"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:212)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:32)
	at net.kdt.pojavlaunch.uikit.UIKit.launchUI(Native Method)
	at net.kdt.pojavlaunch.PLaunchApp.main(PLaunchApp.java:40)

### The log file and images/videos

2022-04-20 11:32:31.476 PojavLauncher[5471:352142] [Pre-Init] iPhone13,2 with iOS 14.4.2 (unc0ver)
2022-04-20 11:32:31.476 PojavLauncher[5471:352142] [Pre-Init] PojavLauncher version: release - a2145e3
2022-04-20 11:32:31.476 PojavLauncher[5471:352142] [Pre-init] Beginning JVM launch
2022-04-20 11:32:31.476 PojavLauncher[5471:352142] [Pre-Init] Restored preference: JAVA_HOME is set to /usr/lib/jvm/java-16-openjdk
2022-04-20 11:32:31.476 PojavLauncher[5471:352142] [Pre-Init] Restored preference: RENDERER is set to libgl4es_114.dylib
2022-04-20 11:32:31.480 PojavLauncher[5471:352142] [Pre-init] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2022-04-20 11:32:31.480 PojavLauncher[5471:352142] [Pre-init] Restored preference: MULTI_DIR is set to default
2022-04-20 11:32:31.480 PojavLauncher[5471:352142] [Pre-init] Java executable path: /usr/lib/jvm/java-16-openjdk/bin/java
2022-04-20 11:32:31.490 PojavLauncher[5471:352142] [Init] Found JLI lib
2022-04-20 11:32:31.490 PojavLauncher[5471:352142] [Init] Calling JLI_Launch
2022-04-20 11:32:31.491 PojavLauncher[5471:352177] [Pre-init] Reading custom environment variables (custom_env.txt), opened=0
2022-04-20 11:32:31.491 PojavLauncher[5471:352177] [Pre-Init] iPhone13,2 with iOS 14.4.2
2022-04-20 11:32:31.491 PojavLauncher[5471:352177] [Pre-Init] PojavLauncher version: release - a2145e3
2022-04-20 11:32:31.491 PojavLauncher[5471:352177] [Pre-init] Beginning JVM launch
2022-04-20 11:32:31.491 PojavLauncher[5471:352177] [Pre-Init] Restored preference: JAVA_HOME is set to /usr/lib/jvm/java-16-openjdk
2022-04-20 11:32:31.491 PojavLauncher[5471:352177] [Pre-Init] Restored preference: RENDERER is set to libgl4es_114.dylib
2022-04-20 11:32:31.494 PojavLauncher[5471:352177] [Pre-init] Classpath generated: /Applications/PojavLauncher.app/libs/.:/Applications/PojavLauncher.app/libs/..:/Applications/PojavLauncher.app/libs/launcher.jar:/Applications/PojavLauncher.app/libs/gson-2.8.6.jar:/Applications/PojavLauncher.app/libs/jsr305.jar:/Applications/PojavLauncher.app/libs/lwjgl3-minecraft.jar:/Applications/PojavLauncher.app/libs/json-20201115.jar:
2022-04-20 11:32:31.494 PojavLauncher[5471:352177] [Pre-init] Restored preference: MULTI_DIR is set to default
2022-04-20 11:32:31.495 PojavLauncher[5471:352177] [Pre-init] RENDERER has been set to libgl4es_114.dylib
2022-04-20 11:32:31.495 PojavLauncher[5471:352177] [Init] Found JLI lib
2022-04-20 11:32:31.495 PojavLauncher[5471:352177] [Init] Calling JLI_Launch
[0.021s][warning][os,thread] Attempt to protect stack guard pages failed (0x0000000169adc000-0x0000000169ae8000).
[0.021s][warning][os,thread] Attempt to deallocate stack guard pages failed.
We are on java now! Starting UI...
java.lang.RuntimeException: MSA Error: 429: Too Many Requests, error stream:
{
  "path" : "/authentication/login_with_xbox"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:212)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:32)
	at net.kdt.pojavlaunch.uikit.UIKit.launchUI(Native Method)
	at net.kdt.pojavlaunch.PLaunchApp.main(PLaunchApp.java:40)

java.lang.RuntimeException: MSA Error: 429: Too Many Requests, error stream:
{
  "path" : "/authentication/login_with_xbox"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:304)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:212)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.run(MicrosoftAuthTask.java:39)
	at net.kdt.pojavlaunch.uikit.AccountJNI.loginAccount(AccountJNI.java:32)
	at net.kdt.pojavlaunch.uikit.UIKit.launchUI(Native Method)
	at net.kdt.pojavlaunch.PLaunchApp.main(PLaunchApp.java:40)

2022-04-20 11:34:15.178 PojavLauncher[5471:352142] Returning local object of class NSString

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start 1.18.2
```

### Expected Behavior

The game to launch

### Platform

```markdown
- Device model: iPhone 12
- CPU architecture: Apple A14
- ios version: 14.4.2
- PojavLauncher version: v3.3.1.1
```

**Comment by khanhduytran0** [comment]
You have submitted to the wrong repository.

> MSA Error: 429: Too Many Requests

You have made Too Many Requests, which then cause the server to reject any further attempts for a while.
