### ISSUE TITLE
Fix PojavLauncher game after launching a version

### ISSUE THREAD

**Issue by MarcyIgop** [PojavLauncherTeam/PojavLauncher#3115]
### Describe the bug

when i open pojavlauncher after that i launched a version thenbit instantly crashed pls fix it i dont want my survival world disappear 

### The log file and images/videos

Uploading 2022_04_22_10_06_29.mp4…

### Steps To Reproduce

```markdown
1.open pojav
2.launch a single version
3.boom instantly crashed
```

### Expected Behavior

pls fic it

### Platform

```markdown
- Device model: Huawei y6p 
- CPU architecture: aarch32 
- Android version: Android 10 
- PojavLauncher version: holy edition
```

**Comment by kuzy21** [comment]
What minecraft version are u running

**Comment by MarcyIgop** [comment]
oh holy version

**Comment by khanhduytran0** [comment]
> oh holy version

Holy version isn’t a valid Minecraft version
Also, the log is not sent.

**Comment by MarcyIgop** [comment]
> > oh holy version
> 
> Holy version isn’t a valid Minecraft version
> Also, the log is not sent.

there is no crash log i also checked the latest crash logs and its the log yesterday not today

**Comment by MarcyIgop** [comment]
> > oh holy version
> 
> Holy version isn’t a valid Minecraft version
> Also, the log is not sent.

hey um i downloaded the crocus-299-f1bd7099-v3_openjdk
version of pojav and i downloaded again the 1.18.2 and still the same it crashes when i open it pls help

**Comment by MarcyIgop** [comment]
> > oh holy version
> 
> Holy version isn’t a valid Minecraft version
> Also, the log is not sent.

and btw this is the crashlog

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 4/22/22, 8:27 AM
Description: Rendering overlay

java.lang.RuntimeException: could not reload shaders
	at eql.b(SourceFile:499)
	at eql.a(SourceFile:387)
	at agb.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:211)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:198)
	at dsr.e(SourceFile:310)
	at dyr.f(SourceFile:1147)
	at dyr.e(SourceFile:737)
	at net.minecraft.client.main.Main.main(SourceFile:236)
Caused by: yw: Invalid shaders/core/rendertype_solid.json: Couldn't compile vertex program (Default, rendertype_solid) : Compile failed.
ERROR: 1:15: '/' : Wrong operand types. No operation '/' exists that takes a left-hand operand of type 'in invalid 2-component vector of int' and a right operand of type 'const float' (and there is no acceptable conversion)
ERROR: 1:15: 'clamp' : no matching overloaded function found
ERROR: 1:15: 'texture' : no matching overloaded function found
ERROR: 1:15: 'return' : type does not match function's return type
4 compilation errors. No code generated.
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.b(SourceFile:455)
	... 118 more
Caused by: java.io.IOException: Couldn't compile vertex program (Default, rendertype_solid) : Compile failed.
ERROR: 1:15: '/' : Wrong operand types. No operation '/' exists that takes a left-hand operand of type 'in invalid 2-component vector of int' and a right operand of type 'const float' (and there is no acceptable conversion)
ERROR: 1:15: 'clamp' : no matching overloaded function found
ERROR: 1:15: 'texture' : no matching overloaded function found
ERROR: 1:15: 'return' : type does not match function's return type
4 compilation errors. No code generated.
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 119 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.b(SourceFile:499)
	at eql.a(SourceFile:387)
	at agb.a(SourceFile:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:795)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at agf.a(SourceFile:69)
	at auz.execute(SourceFile:103)
	at agf.a(SourceFile:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:211)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:198)

-- Overlay render details --
Details:
	Overlay name: edj
Stacktrace:
	at eql.a(SourceFile:869)
	at dyr.f(SourceFile:1122)
	at dyr.e(SourceFile:737)
	at net.minecraft.client.main.Main.main(SourceFile:236)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (arm) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 674245992 bytes (643 MiB) / 1006632960 bytes (960 MiB) up to 1006632960 bytes (960 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4601.28
	Virtual memory used (MB): 4246.90
	Swap memory total (MB): 2684.08
	Swap memory used (MB): 1211.21
	JVM Flags: 2 total; -Xms960M -Xmx960M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 1200x540
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x ARMv8 Processor rev 4 (v8l)

**Comment by DovydasTEDS** [comment]
You might have to increase your ram

**Comment by MarcyIgop** [comment]
> You might have to increase your ram

ok ill try

**Comment by MarcyIgop** [comment]
> You might have to increase your ram

still not working do i need to to use assets 0 for it? because it said could not preload shader and i higher the memory allocation to 980 and still crashing

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 4/23/22, 2:24 AM
Description: Initializing game

java.lang.IllegalStateException: could not preload shader position
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:197)
Caused by: yw: Invalid shaders/core/position.json: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at yw.a(SourceFile:48)
	at erd.<init>(SourceFile:202)
	at eql.a(SourceFile:421)
	... 3 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/position.vsh, position) : Compile failed.
ERROR: 0:7: 'max' : cannot redeclare or overload built-in function
ERROR: main() function is missing.
2 compilation errors. No code generated.
	at dtb.b(SourceFile:72)
	at dtb.a(SourceFile:54)
	at erd.a(SourceFile:244)
	at erd.<init>(SourceFile:184)
	... 4 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at eql.a(SourceFile:425)
	at eql.a(SourceFile:409)
	at dyr.<init>(SourceFile:619)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:197)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (arm) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK Server VM (mixed mode), Oracle Corporation
	Memory: 335089632 bytes (319 MiB) / 1027604480 bytes (980 MiB) up to 1027604480 bytes (980 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: ARMv8 Processor rev 4 (v8l)
	Identifier: 0x41 Family 8 Model 0xd03 Stepping r0x0p4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4601.28
	Virtual memory used (MB): 4448.55
	Swap memory total (MB): 2684.08
	Swap memory used (MB): 1468.05
	JVM Flags: 2 total; -Xms980M -Xmx980M
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: 8x ARMv8 Processor rev 4 (v8l)

**Comment by DovydasTEDS** [comment]
Upgrade to the latest openjdk actions build as holy gl4es has merged into it.

**Comment by MarcyIgop** [comment]
> Upgrade to the latest openjdk actions build as holy gl4es has merged into it.

yooooo!!!! it finally worked ty!!

**Comment by DovydasTEDS** [comment]
Please close this issue now
