### ISSUE TITLE
PojavLauncher won't let me login with Microsoft account.

### ISSUE THREAD

**Issue by JustJoshinDev** [PojavLauncherTeam/PojavLauncher#3125]
### Describe the bug

I open the app, go to Microsoft Login, and it opens a window to my browser that is the Microsoft login. Since I've tried to log in before it asks if I'm opening the MC launcher and tells me to only continue if it is an app that I trust. I continue and it gets through 3/6 steps before it stops and gives me error code 301.

### The log file and images/videos

java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:312)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:177)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Microsoft Login
3. Continue
4. Goes to step 3/6 and gives error code.
```

### Expected Behavior

I expect the game to log me in, so I can play online.

### Platform

```markdown
- Device model: Fire HD 10
- CPU architecture: arm64-v8a
- Android version: Fire OS 7.3.2.2
- PojavLauncher version: 3.3.1.1
```

**Comment by DovydasTEDS** [comment]
You may need to link your child microsoft account to an adults and change a few settings. You may want to google this issue up as it is not just pojav.

**Comment by ghost** [comment]
Also update your launcher to the latest actions build.

**Comment by JustJoshinDev** [comment]
Thank you!

**Comment by bjcmcncncjgj** [comment]
No download pojavlauncher
