### ISSUE TITLE
[BUG] nooo, i cant sign in through microsoft acc

### ISSUE THREAD

**Issue by OverLooper1** [PojavLauncherTeam/PojavLauncher#3156]
### Describe the bug

MSA error 403? i have no idea

### The log file and images/videos

java.lang.RuntimeException: 

MSA Error: 403: Forbidden, error stream:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: TmQXhpldfC9yk8ZmL68vye9NfX07rPKmvBiEHUDSLpS3ixrIprtGlw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:312)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:212)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

### Steps To Reproduce

```markdown
press the microsoft login button and go through the microsoft login page, after that the error occurs, i don't know if it's just me
```

### Expected Behavior

when i sign in, i expected to sign in successfully

### Platform

```markdown
- Device model: SM-G781U
- CPU architecture: Qualcomm Snapdragon 865
- Android version: 12
- PojavLauncher version: 3.1.1, idk, but its recent
```

### Anything else?

tjbgh crahs

**Comment by PayToUse** [comment]
Bruh the account isn't migrated man or maybe

**Comment by OverLooper1** [comment]
> Bruh the account isn't migrated man or maybe

![Screenshot_20220430-161422_Samsung Internet](https://user-images.githubusercontent.com/94162582/166122912-5012d1e6-7efa-4bf5-a867-959451328130.png)

**Comment by OverLooper1** [comment]
it is

**Comment by Mathias-Boulay** [comment]
there was a temporary issue on their end
