### ISSUE TITLE
[BUG] Error -1 in minecraft 1.17.1(fabric)

### ISSUE THREAD

**Issue by andr0d1v** [PojavLauncherTeam/PojavLauncher#3157]
### Describe the bug

I used to run Minecraft 1.17.1 fabric and everything was fine (the game started and everything worked) But one day I started the game and when it started it crashed with the code -1 (although I have a license) I tried completely reinstalling the launcher (didn't help) And now I can't play

PLZ HELP ME

### The log file and images/videos

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 29.04.2022, 02:43
Description: Initializing game

java.lang.IllegalStateException: could not preload shader rendertype_text
	at net.minecraft.class_757.method_34522(class_757.java:422)
	at net.minecraft.class_757.method_34521(class_757.java:413)
	at net.minecraft.class_310.<init>(class_310.java:617)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_2973: Invalid shaders/core/rendertype_text.json: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:7: S0032: no default precision defined for parameter 'sampler'
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:197)
	at net.minecraft.class_757.method_34522(class_757.java:418)
	... 10 more
Caused by: java.io.IOException: Couldn't compile vertex program (minecraft:shaders/core/rendertype_text.vsh, rendertype_text) : 0:7: S0032: no default precision defined for parameter 'sampler'
	at net.minecraft.class_281.method_34416(class_281.java:72)
	at net.minecraft.class_281.method_1283(class_281.java:54)
	at net.minecraft.class_5944.method_34579(class_5944.java:237)
	at net.minecraft.class_5944.<init>(class_5944.java:179)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_34522(class_757.java:422)
	at net.minecraft.class_757.method_34521(class_757.java:413)
	at net.minecraft.class_310.<init>(class_310.java:617)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 560602624 bytes (534 MiB) / 838860800 bytes (800 MiB) up to 838860800 bytes (800 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd0a Stepping r0x1p0
	Microarchitecture: unknown
	Frequency (GHz): -0,00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0,00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4106,72
	Virtual memory used (MB): 4195,56
	Swap memory total (MB): 2252,00
	Swap memory used (MB): 1039,83
	JVM Flags: 2 total; -Xms800M -Xmx800M
	Launched Version: 1.17.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x 

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Launch Minecraft 1.17.1(Fabric)
3. A few seconds after starting to see an error
```

### Expected Behavior

I expect that the game will start without errors and will work

### Platform

```markdown
- Device model: Redmi 10 4/128G
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest version
```

**Comment by offbeat-stuff** [comment]
use the latest version
https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk+is%3Asuccess
you are getting a shader compile error
if that does not work read through this:
https://pojavlauncherteam.github.io/updates/117.html#note-for-minecraft-21w37a-on-android-thanks-to-notahero04

**Comment by andr0d1v** [comment]
@offbeat-stuff I tried your methods, it didn't help :(

**Comment by artdeell** [comment]
Fixed on holy gl4es
