### ISSUE TITLE
O forge não está instalando 

### ISSUE THREAD

**Issue by Borutinho132** [PojavLauncherTeam/PojavLauncher#3159]
### Describe the bug

Toda vez q eu vou tentar instalar o forge aparece o erro de código -1

### The log file and images/videos

Prfvr consertem o erro de código -1

### Steps To Reproduce

```markdown
Aplicativo/Jogo fechou com código -1
```

### Expected Behavior

Espero q erro de código -1 seja consertado

### Platform

```markdown
- Device model: Moto G Play
- CPU architecture: aarch32
- Android version: 7.1.1
- PojavLauncher version: [Última versão || versão 3.3.1.1_rel_20210206]
```

### Anything else?

Eu preciso q o erro pra quando for iníciar o Minecraft não de esse erro java.lang.RuntimeException: A arquitetura arm é incompatível com o Java Runtime x86_64.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

**Comment by GaucovyAero** [comment]
Update to the latest (updated 28.04.2022) PojavLauncher Actions build [here](https://github.com/PojavLauncherTeam/PojavLauncher/suites/6294284472/artifacts/225472760) and download Java 17 for your device [here.](https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/releases/download/jre17-ec28559/jre17-arm-20210914-release.tar.xz)

**Comment by Mathias-Boulay** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/3154

**Comment by Mathias-Boulay** [comment]
Fixed in the latest release candidate build.
