### ISSUE TITLE
Launcher Can't start on my Asus ZenFone 5 T00f and ZenFone 2 ZE551ML

### ISSUE THREAD

**Issue by KostyanSigaev** [PojavLauncherTeam/PojavLauncher#320]
I ALREADY WRITTEN ABOUT THIS REASON, BUT AN INDEQUATE COMMUNITY GIVEN NO ANSWER AND MY QUESTION HAS BEEN CLOSED !!!
Both my phones are running android 6, Intel Atom z2580 on zenfone 5 and z3580 on zenfone 2.
I launch the launcher, select the version, press play and an error pops up:
Error:
java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.9/1.9.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1084)
at net.kdt.pojavlaunch.MainActivity.access$3100(MainActivity.java:37)
at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:709)
at java.lang.Thread.run(Thread.java:818)
Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar
at dalvik.system.DexFile.openDexFileNative(Native Method)
at dalvik.system.DexFile.openDexFile(DexFile.java:295)
at dalvik.system.DexFile.(DexFile.java:111)
at dalvik.system.DexFile.loadDex(DexFile.java:151)
at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
at dalvik.system.DexPathList.(DexPathList.java:120)
at dalvik.system.BaseDexClassLoader.(BaseDexClassLoader.java:48)
at dalvik.system.DexClassLoader.(DexClassLoader.java:57)
at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1081)
... 3 more
Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
at dalvik.system.DexFile.openDexFileNative(Native Method)
at dalvik.system.DexFile.openDexFile(DexFile.java:295)
at dalvik.system.DexFile.(DexFile.java:111)
at dalvik.system.DexFile.loadDex(DexFile.java:151)
at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
at dalvik.system.DexPathList.(DexPathList.java:120)
at dalvik.system.BaseDexClassLoader.(BaseDexClassLoader.java:48)
at dalvik.system.DexClassLoader.(DexClassLoader.java:57)
at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1081)
... 3 more
Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.22/authlib-1.5.22.jar
at dalvik.system.DexFile.openDexFileNative(Native Method)
at dalvik.system.DexFile.openDexFile(DexFile.java:295)
at dalvik.system.DexFile.(DexFile.java:111)
at dalvik.system.DexFile.loadDex(DexFile.java:151)
at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
at dalvik.system.DexPathList.(DexPathList.java:120)
at dalvik.system.BaseDexClassLoader.(BaseDexClassLoader.java:48)
at dalvik.system.DexClassLoader.(DexClassLoader.java:57)
at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1081)
... 3 more
Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/versions/1.9/1.9.jar
at dalvik.system.DexFile.openDexFileNative(Native Method)
at dalvik.system.DexFile.openDexFile(DexFile.java:295)
at dalvik.system.DexFile.(DexFile.java:111)
at dalvik.system.DexFile.loadDex(DexFile.java:151)
at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
at dalvik.system.DexPathList.(DexPathList.java:120)
at dalvik.system.BaseDexClassLoader.(BaseDexClassLoader.java:48)
at dalvik.system.DexClassLoader.(DexClassLoader.java:57)
at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1081)
... 3 more
Suppressed: java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/data/app/net.kdt.pojavlaunch-1/base.apk"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-1/lib/arm, /data/app/net.kdt.pojavlaunch-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 5 more
Suppressed: java.lang.ClassNotFoundException: net.minecraft.client.main.Main
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 6 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Malaska678** [comment]
Android 6, and android 4.0 or below wont work

**Comment by Malaska678** [comment]
@KostyanSigaev Android 6.0 users can use vmos.

**Comment by Malaska678** [comment]
Vmos would be useful for u but multiplayer wont work

**Comment by Malaska678** [comment]
Close this again

**Comment by KostyanSigaev** [comment]
> Android 6, and android 4.0 or below wont work

It may sound like a surprise, but I just rolled to android 5 and the result hasn't changed ... Maybe it's the processor architecture

**Comment by Malaska678** [comment]
Use vmos. It will android 5.1 on android.

**Comment by WesleyVanNeck** [comment]
@KostyanSigaev  umm its because of your rinning 86X tou need arm32 at least

**Comment by WesleyVanNeck** [comment]
> I ALREADY WRITTEN ABOUT THIS REASON, BUT AN INDEQUATE COMMUNITY GIVEN NO ANSWER AND MY QUESTION HAS BEEN CLOSED !!!

i gave answer 86 arcitecture isnt supported

**Comment by WesleyVanNeck** [comment]
alos your android version is to low 5.0 and 6.0 have issues

**Comment by WesleyVanNeck** [comment]
also i Suggest using a ARM device

**Comment by khanhduytran0** [comment]
Use v3, I just added support for x86 @KostyanSigaev

**Comment by khanhduytran0** [comment]
If you don't know, v2 is having problem about loading jar files on Android 6.
