### ISSUE TITLE
[BUG] game now crashing after trying to add a shader pack

### ISSUE THREAD

**Issue by Ripme999** [PojavLauncherTeam/PojavLauncher#3214]
### Describe the bug

I tried to add bbs shader to 1.12.2 with forge and optifine and after I tried to add it to my shader pack folder and load up the game it crashed so I tried again a few times until I decided to remove it due to it not working,  once it was removed I tried to load the game again and it crashes.

### The log file and images/videos

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/10/22 8:15 AM
Description: Updating screen events

java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2421)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:734)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:249)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:163)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:117)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:49)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
	at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2421)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:734)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:249)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:163)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:117)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:49)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiScreenWorking
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 941982704 bytes (898 MB) / 1521483776 bytes (1451 MB) up to 1521483776 bytes (1451 MB)
	JVM Flags: 3 total; -Xms1536M -Xmx1536M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                   | Signature                                |
	|:------ |:-------------------- |:------------------------ |:---------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                            | None                                     |
	| LCHIJA | mcp                  | 9.42                     | minecraft.jar                            | None                                     |
	| LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | carryon              | 1.12.3                   | carryon-1.12.2-1.12.6.20.jar             | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | chiseled_me          | 1.12-3.0.0.0-git-e5ce416 | chiseled-me-1.12-3.0.0.0-git-e5ce416.jar | c677c954974252994736eb15e855e1e6fc5a2e62 |
	| LCHIJA | chiselsandbits       | 14.33                    | chiselsandbits-14.33-1.jar               | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                | None                                     |
	| LCHIJA | extrabitmanipulation | 1.12.2-3.4.1             | ExtraBitManipulation-1.12.2-3.4.1.jar    | None                                     |
	| LCHIJA | forgelin             | 1.8.4                    | Forgelin-1.8.4.jar                       | None                                     |
	| LCHIJA | jei                  | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar              | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                 | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar         | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.4.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: vgpu 1.3.6 GL version 3.0, vgpu
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x null
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 14
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0
	OpenGlRenderer: vgpu 1.3.6
	OpenGlVendor: vgpu
	CpuCount: 6

### Steps To Reproduce

```markdown
load pojav launcher, play my specific build, starts to load then crashes.
```

### Expected Behavior

load the game as intended and begin to use shaders.

### Platform

```markdown
- Device model: galaxy A70
- CPU architecture: arch64
- Android version: Android 11
- PojavLauncher version: 3.3.1.1
```

**Comment by Ripme999** [comment]
this one was an accident..
