### ISSUE TITLE
ye optifine go brr then di

### ISSUE THREAD

**Issue by 4hxu** [PojavLauncherTeam/PojavLauncher#322]
optifine 1.9 literally keeps crashing on the loading screen 1.9 works fine but the world lags like the mobs's movement is slower and when i install optifine and try to play with it i cant enjoy my life and it crashes and then i cry
idek tis is de crash log

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 21/09/2020 12:39 am
Description: Initializing game

java.lang.NullPointerException: Attempt to invoke virtual method 'bxo bxr.bakeModel(bok, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at bxr.a(ModelBakery.java:696)
	at bxs.a(SourceFile:23)
	at bwl.a(SourceFile:100)
	at bcf.an(SourceFile:513)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:986)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:764)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at bxr.a(ModelBakery.java:696)
	at bxs.a(SourceFile:23)
	at bwl.a(SourceFile:100)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:330)
	at bcf.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:986)
	at net.kdt.pojavlaunch.MainActivity.access$1000087(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:655)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 3.18.91-15641782-QB31228608
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-A260F, Android 8.1.0), The Android Project
	Memory: 5846376 bytes (5 MB) / 111370232 bytes (106 MB) up to 268435456 bytes (256 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9-OptiFine_HD_U_H5
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer, OpenGL 1.4
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null
	OptiFine Version: OptiFine_1.9_HD_U_H5
	OptiFine Build: 20191204-142824
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by WesleyVanNeck** [comment]
some more info woeld be nice

**Comment by WesleyVanNeck** [comment]
such as android version device brand etc

**Comment by WesleyVanNeck** [comment]
pojav version to

**Comment by khanhduytran0** [comment]
> `java.lang.NullPointerException: Attempt to invoke virtual method 'bxo bxr.bakeModel(bok, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference`
> 
Known issue
