### ISSUE TITLE
[BUG] Instant crash when pressing a button (gamepad)

### ISSUE THREAD

**Issue by iLuros** [PojavLauncherTeam/PojavLauncher#3223]
### Describe the bug

suddenly crashes when pressing any button from the gamepad controller and it happens when u r inside the world/server (im using M tech 7004)

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.reflect.Field.setInt(java.lang.Object, int)' on a null object reference
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.setDummyEventKeycode(GamepadDpad.java:76)
	at net.kdt.pojavlaunch.customcontrols.gamepad.GamepadDpad.convertEvent(GamepadDpad.java:67)
	at net.kdt.pojavlaunch.customcontrols.gamepad.Gamepad.update(Gamepad.java:158)
	at net.kdt.pojavlaunch.BaseMainActivity.dispatchGenericMotionEvent(BaseMainActivity.java:593)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:79)
	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:541)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processGenericMotionEvent(ViewRootImpl.java:6717)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6457)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5888)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6076)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6133)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5892)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5911)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6109)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6283)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:337)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

### Steps To Reproduce

```markdown
1. enter a world/server
2. press any button
3. crash
```

### Expected Behavior

no idea

### Platform

```markdown
- Device model: Poco x3 Pro
- CPU architecture: SD 860
- Android version: 12
- PojavLauncher version: crocus-v3_opendjk (31 aug 21 update)
```

**Comment by artdeell** [comment]
"Latest Release" is not a version. State the exact version.

**Comment by kedrick022** [comment]
> "Latest Release" is not a version. State the exact version.

Plss fix auto rotate screen on 1.16 and blinking white screen when open the settings in game

**Comment by iLuros** [comment]
> "Latest Release" is not a version. State the exact version.

is that enough?

**Comment by artdeell** [comment]
> > "Latest Release" is not a version. State the exact version.
> 
> is that enough?

Please update to a build from the GitHub Actions tab

**Comment by Mathias-Boulay** [comment]
old build, fixed in actions since 200 commits
