### ISSUE TITLE
[BUG] MSA ERROR 404

### ISSUE THREAD

**Issue by aotgamerz** [PojavLauncherTeam/PojavLauncher#3234]
### Describe the bug

java.lang.RuntimeException: 

MSA Error: 504: Gateway Time-out, error stream:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>504 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: AQ7JW25Tc3EZ-xavdPnBClbqi3a2p3G08qoC8a2P17qdUYIYQ3YXnA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:204)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### The log file and images/videos

http://www.w3.org/TR/html4/loose.dtd

### Steps To Reproduce

```markdown
idk this happens to me or anyone else
```

### Expected Behavior

login errors or disconnection from servers ?

### Platform

```markdown
- Device model: android
- CPU architecture: mali
- Android version: 10
- PojavLauncher version: latest
```

### Anything else?

uhh how much time this can take

**Comment by NotAHero04** [comment]
https://twitter.com/MojangStatus/status/1526155959336423429?s=20&t=UtKJpWpMO-cu9ddhqqt5Ow

**Comment by artdeell** [comment]
Mojang issue, closing
