### ISSUE TITLE
[BUG] <Fix GL Error Exiting on Latest PojavLauncher>

### ISSUE THREAD

**Issue by ProSteve12301** [PojavLauncherTeam/PojavLauncher#3235]
### Describe the bug

I just playing SinglePlayer modded with hack client and when its render too long it exits.

Mod Github: [FDPClient](www.github.com/UnlegitMC/FDPClient) made by UnlegitMC Team.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8700041/latestlog.txt)
``
Read the Bottom because there is the GL error log.
``

### Steps To Reproduce

```markdown
1. Start PojavLauncher.
2. Play Singleplayer(Modded) or Multiplayer.
3. Exits
```

### Expected Behavior

Its freeze and Exits and Launch again and Exits Again.

### Platform

```markdown
- Device model: OPPO A12
- CPU architecture: Aarch64(64Bit)
- Android version: 9
- PojavLauncher version: Latest beta
```

### Anything else?

Please fix your GL4ES Renderer or your LWJGL or the Bootstrap Packages.

**Comment by ProSteve12301** [comment]
Wrong github link
>https://github.com/UnlegitMC/FDPClient

**Comment by GaucovyAero** [comment]
This is the crash if you want to know, and/or send it to the FDPClient dev team. We don't support hacked clients. 

**java.lang.reflect.InvocationTargetException**
at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.ccbluex.liquidbounce.event.EventManager.callEvent(EventManager.kt:87)
at net.minecraft.client.entity.EntityPlayerSP.func_70091_d(EntityPlayerSP.java:1245)
at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1446)
at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1690)
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1808)
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:544)
at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1234)
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1614)
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
at net.minecraft.world.World.func_72866_a(World.java:1860)
at net.minecraft.world.World.func_72870_g(World.java:1829)
at net.minecraft.world.World.func_72939_s(World.java:1661)
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
**Caused by: java.lang.NullPointerException**
at net.ccbluex.liquidbounce.features.module.modules.movement.TargetStrafe.getCanStrafe(TargetStrafe.kt:92)
at net.ccbluex.liquidbounce.features.module.modules.movement.TargetStrafe.onMove(TargetStrafe.kt:42)
at java.lang.Throwable:printStackTrace:635]: 	... 26 more

**Comment by ProSteve12301** [comment]
FDP Dev Team cannot fix it.It says the launcher renderer is the problem.

**Comment by ProSteve12301** [comment]
I try all renderer but its exits.

Some GL Errors i found:
• SCP Containment Breanch Mod (1.8.9)
• Any types of shader that using an VirGL Renderer.
• Optifine 1.8.9 or 1.12.2 using VirGL or VGPU renderer exits.

**Comment by Mathias-Boulay** [comment]
Well, maybe update the launcher to action builds then.
Because 'latest beta' is not a version.
