### ISSUE TITLE
[BUG] <Crash on opening labymod 1.8.9>

### ISSUE THREAD

**Issue by NotMeYT** [PojavLauncherTeam/PojavLauncher#3239]
### Describe the bug

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 5/17/22 8:15 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:44)
	at net.labymod.main.LabyMod.init(LabyMod.java:339)
	at ave.am(SourceFile:470)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:135)
	at com.sun.jna.Structure.<clinit>(Structure.java:146)
	at net.labymod.discordapp.DiscordApp.<init>(DiscordApp.java:44)
	at net.labymod.main.LabyMod.init(LabyMod.java:339)
	at ave.am(SourceFile:470)

-- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (aarch64) version Android-8.0.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 875342752 bytes (834 MB) / 1056178176 bytes (1007 MB) up to 1056178176 bytes (1007 MB)
	JVM Flags: 24 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:+UseBiasedLocking -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:+UseCodeCacheFlushing -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:ReservedCodeCacheSize=2048m -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10 -Xmn128m -Xms1020M -Xmx1020M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: vgpu 1.3.6 GL version 3.0, vgpu
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.0
	OpenGlRenderer: vgpu 1.3.6
	OpenGlVendor: vgpu
	CpuCount: 8

### The log file and images/videos

. 

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

I expected the game to open

### Platform

```markdown
- Device model:HUAWEI NOVA LITE(PRA-LX2) 
- CPU architecture: 8x ARM Cortex-A53 @ 1.71 GHz 
- Android version: 8
- PojavLauncher version: crocus-v3_openjdk
```

**Comment by NotAHero04** [comment]
A [very complicated] solution for LabyMod is described [here.](https://github.com/NotAHero04/RandomPojavThings/tree/main/LabyMod)

**Comment by artdeell** [comment]
LabyMod 1.8.9 is not natively supprted, use the solution above
