### ISSUE TITLE
Minecraft 1.12.2 not working on Realme 3i aarch64 

### ISSUE THREAD

**Issue by halomanlodestar** [PojavLauncherTeam/PojavLauncher#327]
Here I was using your app 'Pojav Launcher' but when I tried to play v1.12.2 it didn't worked it shows a message which I pasted below

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1070)
	at net.kdt.pojavlaunch.MainActivity.access$3100(MainActivity.java:37)
	at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	... 5 more
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at bib.<init>(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 7 more

This problem happened with 1.12.2, so I decided to download v1.9.0 but whenever I try to create a world it sticks on world creating screen. Hope you will fix it soon.

**Comment by khanhduytran0** [comment]
v2 currently don't support patch 1.12.x to get it work (yes it work) and v3 currently don't support run 1.12.2-
I didn't upload patched 1.12.2 yet, but 1.12 is available. If you want try 1.12, this is https://drive.google.com/file/d/18LBDyLysq19INyGhOoi3HrkGeaGI4jvy/view?usp=drivesdk
