### ISSUE TITLE
[BUG] I can't enter the game since version 1.17.1

### ISSUE THREAD

**Issue by Helaik** [PojavLauncherTeam/PojavLauncher#3282]
### Describe the bug

`java.lang.RuntimeException: Архитектура arm64 несовместима с Java Runtime arm.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:43)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:725)
	at net.kdt.pojavlaunch.BaseMainActivity.access$1300(BaseMainActivity.java:36)
	at net.kdt.pojavlaunch.BaseMainActivity$4.lambda$onSurfaceTextureAvailable$0$BaseMainActivity$4(BaseMainActivity.java:552)
	at net.kdt.pojavlaunch.-$$Lambda$BaseMainActivity$4$zq_3Ecok-LKbTEHUCxKaZo-5qB4.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)
`

### The log file and images/videos

![Screenshot_20220529-121842](https://user-images.githubusercontent.com/102434373/170861257-e02b83df-9693-4ef9-914b-8c873ffc4986.png)

### Steps To Reproduce

```markdown
1. Запуск PojavLauncher
2. Запуск игры с версии 1.17.1
3. Ошыбка: Arm64 не совместима с Java Runtimr arm
```

### Expected Behavior

Ожидал запуск игры.

### Platform

```markdown
- Device model: Nokia 3.1 Plus
- CPU architecture: 
- Android version: 10
- PojavLauncher version: Crocus_v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
You downloaded the wrong architecture
The correct architecture will get auto unpacked starting with the dahlia update, which is available on the play store
