### ISSUE TITLE
unable to log in via Microsoft

### ISSUE THREAD

**Issue by Szymon64** [PojavLauncherTeam/PojavLauncher#3291]
### Describe the bug

while logging in an error pops up

### The log file and images/videos

java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
1I run pojav launcher
2, log in with Microsoft and log in 
3 An error pops up
```

### Expected Behavior

I expected him to log in 

### Platform

```markdown
- Device model: Oppo a53
- CPU architecture: qualcomm sm4250 
- Android version: 11
- PojavLauncher version: dahlia v3_openjdk
```

### Anything else?

because I can't log in, I can't install any version of minicraft

**Comment by mchnjt** [comment]
buy minecraft.

**Comment by vanistillhere** [comment]
> buy minecraft.

at https://minecraft.net/ btw

**Comment by Szymon64** [comment]
> buy minecraft.

I have bought one and still can't log in anyway, they just destroyed the login

**Comment by ThePolishLemon** [comment]
Same problem i own the game , login with the correct account and it gives me error 404

**Comment by XiaoMeow-1145** [comment]
> Same problem i own the game , login with the correct account and it gives me error 404

 Me too

**Comment by yesayans** [comment]
I also have this problem, it appeared a week ago.Although I bought Minecraft.I can provide proof...

**Comment by GaucovyAero** [comment]
> I also have this problem, it appeared a week ago.Although I bought Minecraft.I can provide proof...

join the pojavlauncher discord server and we will help you there
