### ISSUE TITLE
[BUG] Minecraft Freezes when joining the world

### ISSUE THREAD

**Issue by ASGAMING009** [PojavLauncherTeam/PojavLauncher#3326]
### Describe the bug

When i join my modded server my minecraft freezes and run on 0fps maybe cause nothing is working well i can still press buttons and pojav is working fine
![Screenshot_2022-06-05-11-18-04-935_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/68546736/172037276-8e8c1daf-6bd9-4846-8c66-9d8e51d687be.jpg)

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8839395/latestlog.txt)

### Steps To Reproduce

```markdown
1.Start Pojav
2.open/play minecraft
3.join server
```

### Expected Behavior

It was working fine with older pojav like 6days old one
And it was giving atleast 50-60 fps but now it just freezes.

### Platform

```markdown
- Device model: Redmi 9 prime
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: The latest actions version
```

**Comment by ASGAMING009** [comment]
Working fine in single player worlds!
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8839410/latest.log)

**Comment by ASGAMING009** [comment]
I can give the server log too If You Guys Want Just Tell me how to fix this Please!

**Comment by Mathias-Boulay** [comment]
We need the latestlog.txt to investigate first

**Comment by ASGAMING009** [comment]
> We need the latestlog.txt to investigate first

What the https://github.com/PojavLauncherTeam/PojavLauncher/files/8839395/latestlog.txt

**Comment by Mathias-Boulay** [comment]
Oh my bad indeed 😓 
Anyway, good news for you. You are using a built which isn't from the mainline branch. Using actions build from v3_openjdk will solve your issue 😄

**Comment by ASGAMING009** [comment]
> Oh my bad indeed 😓 Anyway, good news for you. You are using a built which isn't from the mainline branch. Using actions build from v3_openjdk will solve your issue 😄

No problem my friend and Thanks for Helping! But can you give a link Please Cause I want the best version

**Comment by Mathias-Boulay** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/2440004159 should do

**Comment by ASGAMING009** [comment]
Nah still stuck btw i can hear the music in background but the game is stuck like its going on 0 fps or somthing. Music and sound is not shuttering so i think This might be something else. Keep in mind offline worlds work perfectly but its just server where its getting stuck.

**Comment by ASGAMING009** [comment]
Wtf is this.(press the gui button to hide other button then slide)
![Screenshot_2022-06-05-17-53-56-592_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/68546736/172050863-ddaca6e3-85bc-4535-9606-7f2cd49770c4.jpg)

**Comment by ASGAMING009** [comment]
@Mathias-Boulay ?

**Comment by Mathias-Boulay** [comment]
it might need a full reinstall since you used a non mainline build

**Comment by ASGAMING009** [comment]
> it might need a full reinstall since you used a non mainline build

Oh fudge what can i copy mods and asstes and library

**Comment by Mathias-Boulay** [comment]
mods sure, assets not so sure

**Comment by ASGAMING009** [comment]
@Mathias-Boulay 
java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:601)
	at java.net.URL.<init>(URL.java:498)
	at java.net.URL.<init>(URL.java:447)
	at net.kdt.pojavlaunch.Tools.downloadFileMonitored(Tools.java:809)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.downloadLibrary(MinecraftDownloaderTask.java:322)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:188)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:27)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by ASGAMING009** [comment]
Game exite with code -1
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8840184/latest.log)

**Comment by Mathias-Boulay** [comment]
Whatever you kept from your previous install most likely created a problem 👀

**Comment by ASGAMING009** [comment]
Versions / assets / mods / config

**Comment by ASGAMING009** [comment]
Well i fixed everything but its still not work so im deleting config and assets

**Comment by Aerolome** [comment]
> Well i fixed everything but its still not work so im deleting config and assets

Looks like too high memory allocation to me.

**Comment by ASGAMING009** [comment]
Its still getting stuck. Maybe i should re-install a old version.

**Comment by GaucovyAero** [comment]
> Its still getting stuck. Maybe i should re-install a old version.

What is your ram allocation again? It's best to not reinstall an old version, because we can't fix the issue if you don't help us. We of course, don't know what the issue is, and also don't have the issue you are having.

**Comment by ASGAMING009** [comment]
1300

**Comment by GaucovyAero** [comment]
> 1300

i don't know which version of Minecraft is the server running on, but try turning it down to 600MB.

**Comment by ASGAMING009** [comment]
Its running on 1.12.2. And is modded with 63 mods

**Comment by ASGAMING009** [comment]
Im just sad i have deleted every thing (other than mods folder) and its still freezing i just talk the server aternos server mods if this a server side bug or something but nop they told its ln my end. I am trying everything and if you think of asking anything just ask. I really need this to fix.
And thanks for helping.

**Comment by GaucovyAero** [comment]
> Im just sad i have deleted every thing (other than mods folder) and its still freezing i just talk the server aternos server mods if this a server side bug or something but nop they told its ln my end. I am trying everything and if you think of asking anything just ask. I really need this to fix. And thanks for helping.

Yeah, I am also pulling at straws here, maybe you could freeze it and then send us latestlog.txt?

**Comment by ASGAMING009** [comment]
Well im saying thing again Singleplayer still works fine.
And should i send you a new Latest log?

**Comment by GaucovyAero** [comment]
> Well im saying thing again Singleplayer still works fine. And should i send you a new Latest log?

Yep, that would be great.

**Comment by ASGAMING009** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8840573/latestlog.txt)
![Screenshot_2022-06-06-00-34-10-467_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/68546736/172066483-11d4cdce-41a9-469d-98ab-e786998f455a.jpg)

I can see that its says either 8 or most probably 0 fps 
Under the bar.
I have a recording to! If you want i can send it!

**Comment by ASGAMING009** [comment]
https://user-images.githubusercontent.com/68546736/172066561-12c09184-75fd-49e9-a8b1-38fddbb1570b.mp4

Here is the recording and you can hear the sounds!

**Comment by ASGAMING009** [comment]
@Aerolome this should be good!

**Comment by GaucovyAero** [comment]
[19:02:26] [Netty Client IO #1/ERROR]: Parsing error loading built-in advancement biomesoplenty:recipes/buildingblocks/ebony_planks
com.google.gson.JsonSyntaxException: Unknown recipe 'biomesoplenty:ebony_planks'
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:171) ~[l$a.class:?]
	at net.minecraft.advancements.AdvancementRewards$Deserializer.deserialize(AdvancementRewards.java:147) ~[l$a.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[TreeTypeAdapter$GsonContextImpl.class:?]
	at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:439) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:455) ~[rc.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:203) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:517) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188178_a(SourceFile:537) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1381) ~[ForgeHooks.class:14.23.5.2860]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359) [ForgeHooks.class:14.23.5.2860]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(Fo
rgeHooks.java:1326) [ForgeHooks.class:14.23.5.2860]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at codersafterdark.reskillable.client.base.ClientProxy.connect(ClientProxy.java:42) [ClientProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_885_ClientProxy_connect_ClientConnectedToServerEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeClientSideConnection(NetworkDispatcher.java:245) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:567) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:36) [HandshakeCompletionHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:30) [HandshakeCompletionHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) [netty-all-4.1.9
.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4
.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:274) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:99) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147) [gw.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:49) [gw.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleClientSideCustomPacket(NetworkDispatcher.java:372) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:268) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty
.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Abstra
ctChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.ni
o.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0-internal]
	
**This error repeats itself every frame, no wonder it's lagging like hell.**

**Comment by ASGAMING009** [comment]
How to fix it?

**Comment by GaucovyAero** [comment]
> How to fix it?

Looks like something is wrong with Biomes O' Plenty, but I don't know if that's normal, or if it's the config, or the mod. Try switching your config with the one that your friend has.

**Comment by ASGAMING009** [comment]
Umm ok all of my friends are asleep soo idk if i can ask them

**Comment by ASGAMING009** [comment]
> > How to fix it?
> 
> Looks like something is wrong with Biomes O' Plenty, but I don't know if that's normal, or if it's the config, or the mod. Try switching your config with the one that your friend has.

Its still not working i tried it!

**Comment by ASGAMING009** [comment]
@Aerolome i am still getting 0fps

**Comment by GaucovyAero** [comment]
> @Aerolome i am still getting 0fps

We don't know what's the issue. Maybe you could send us the mods thru mediafire?

**Comment by ASGAMING009** [comment]
I HAVE UPDATED THE VERSION TO THE NEW ONE WHERE MOUSE SPEED IS DOUBLED AND ITS FRICKING WORKING

**Comment by ASGAMING009** [comment]
Thanks everyone for helping!

**Comment by GaucovyAero** [comment]
> I HAVE UPDATED THE VERSION TO THE NEW ONE WHERE MOUSE SPEED IS DOUBLED AND ITS FRICKING WORKING

mouse speed is doubled?

**Comment by ASGAMING009** [comment]
> > I HAVE UPDATED THE VERSION TO THE NEW ONE WHERE MOUSE SPEED IS DOUBLED AND ITS FRICKING WORKING
> 
> mouse speed is doubled?

(Pottential fix for double mouse speed ) yeah i used this build and now its fixed

**Comment by ASGAMING009** [comment]
[latest.log](https://github.com/PojavLauncherTeam/PojavLauncher/files/8845950/latest.log)
@Aerolome

**Comment by GaucovyAero** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Trinkets and Baubles (xat)
Caused by: java.lang.NoClassDefFoundError: team/creative/enhancedvisuals/api/event/FireParticlesEvent

Trinkets and Baubles mod isn't compatible with Pojav. Remove it if you want the game to launch.
