### ISSUE TITLE
[BUG] Unable to add window -- token (forge)

### ISSUE THREAD

**Issue by jelebruh** [PojavLauncherTeam/PojavLauncher#3329]
### Describe the bug

When I join to server app crashes without anything - hoa and I'm on login screen

### The log file and images/videos

PojavLauncher crash report
 - Time: 31 мая 2022 г. 19:17:28
 - Device: RMX3081
 - Android version: 11
 - Crash stack trace:
 - Launcher version: dahlia-v3_openjdk
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@29a3e11 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1238)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:413)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:110)
	at android.app.Dialog.show(Dialog.java:353)
	at net.kdt.pojavlaunch.authenticator.microsoft.ui.MicrosoftLoginGUIActivity$WebViewTrackClient.onPageStarted(MicrosoftLoginGUIActivity.java:63)
	at Uy0.b(chromium-TrichromeWebViewGoogle.aab-stable-495106133:406)
	at P9.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-495106133:170)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:254)
	at android.app.ActivityThread.main(ActivityThread.java:8235)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

### Steps To Reproduce

```markdown
1. Start 1.18.2 forge
2. join server
```

### Expected Behavior

Joined to server without problems

### Platform

```markdown
- Device model: realme 8 Pro
- CPU architecture: armv8
- Android version: 11
- PojavLauncher version: v3
```

**Comment by Mathias-Boulay** [comment]
We need the latestlog.txt, not the latestcrash.txt, as the latter report the crashing of the launcher and not minecraft
