### ISSUE TITLE
[BUG] <error code 1 in new pojavluncher build>

### ISSUE THREAD

**Issue by MHMD456** [PojavLauncherTeam/PojavLauncher#3349]
### Describe the bug

I updated the pojavluncher in Google play and wen I go in versions I downloaded in past and I have they in my folder any version pojavluncher run get me this error that's really Surprising 

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/8873263/latestlog.txt)

### Steps To Reproduce

```markdown
1. go to pojavluncher
2.start any version
3.give me this error
```

### Expected Behavior

I expected the pre-downloaded file to work and the game to run 

### Platform

```markdown
- Device model: Redmi note 8 pro/ 128G
- CPU architecture: Eight-core / 64-bit
- Android version:11 
- PojavLauncher version: The latest version of the Play Store
```

**Comment by GaucovyAero** [comment]
```
java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
Java Exit code: 1
```

Looks like the **joptsimple** library is corrupted. Make sure you don't accidentally interrupt the download of Minecraft libraries. Try again by deleting the libraries folder located in /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/

**Comment by Elisem941** [comment]
Try to delete all mods in .minecraft
