### ISSUE TITLE
Optifine 1.7.10 is crashing! 

### ISSUE THREAD

**Issue by Azapru** [PojavLauncherTeam/PojavLauncher#34]
Crash:

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 01.04.2020 16:11
Description: Initializing game

java.lang.ExceptionInInitializerError
	at bao.ag(SourceFile:401)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:797)
	at net.kdt.pojavlaunch.MainActivity.access$1000075(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:585)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List bix.spriteList' on a null object reference
	at bix.addSprite(ModelRenderer.java:329)
	at bif.<init>(SourceFile:15)
	at bou.<init>(SourceFile:18)
	at bnn.<init>(SourceFile:66)
	at bnn.<clinit>(SourceFile:37)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at b.a(CrashReport.java:357)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:357)
	at bao.f(SourceFile:716)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:797)
	at net.kdt.pojavlaunch.MainActivity.access$1000075(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:585)
	at java.lang.Thread.run(Thread.java:784)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version 4.9.148
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (null), The Android Project
	Memory: 19378176 bytes (18 MB) / 94158768 bytes (89 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10-OptiFine_HD_U
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Anisotropic filtering is not supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.

	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'java.lang.String brq.toString()' on a null object reference
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (339413640)
	OptiFine Version: OptiFine_1.7.10_HD_U_D3
	Render Distance Chunks: 3
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

Pls help me

**Comment by khanhduytran0** [comment]
The error is inside OptiFine, try install other like `OptiFine 1.7.10 HD U E7`

**Comment by abdo-A028** [comment]
> The error is inside OptiFine, try install other like `OptiFine 1.7.10 HD U E7`

I tested it and didn't download

**Comment by khanhduytran0** [comment]
What's your device????

**Comment by khanhduytran0** [comment]
Try v3
