### ISSUE TITLE
crash after installing fabric

### ISSUE THREAD

**Issue by rhjdvsgsgks** [PojavLauncherTeam/PojavLauncher#340]
```
S/jrelog  ( 2683): Exception in thread "main" 
S/jrelog  ( 2683): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:229)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): Caused by: java.lang.reflect.InvocationTargetException
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	... 2 more
S/jrelog  ( 2683): 
S/jrelog  ( 2683): Caused by: joptsimple.MissingRequiredOptionsException: Missing required option(s) [version]
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at joptsimple.OptionParser.parse(OptionParser.java:400)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	at net.minecraft.client.main.Main.main(Main.java:79)
S/jrelog  ( 2683): 
S/jrelog  ( 2683): 	... 7 more
S/jrelog  ( 2683): 
```

**Comment by khanhduytran0** [comment]
It's known issue as Fabric could not be launch yet...

**Comment by rhjdvsgsgks** [comment]
could you please add a function to manage Minecraft start option, i want to try if set "version" argument can resolve this problem

**Comment by khanhduytran0** [comment]
You may put custom arguments to json, but at that already have `--version` argument.

**Comment by khanhduytran0** [comment]
Why are you closing this?

**Comment by rhjdvsgsgks** [comment]
cause it can't be able to resolve right now, but it seems you prefer to keep it open

**Comment by mglovers123** [comment]
how do I crash when installing forge headless installer 1.0.

**Comment by khanhduytran0** [comment]
Use latest launcher build, Fabric might work.

**Comment by khanhduytran0** [comment]
@rhjdvsgsgks try fabric fix
- Launcher Dev build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/365689284
- GLFW https://github.com/PojavLauncherTeam/lwjgl3-glfw-java/actions/runs/365718763

**Comment by rhjdvsgsgks** [comment]
fabric works now after using these files, and I'm trying to install sodium mod to boost my fps, but game crashes after "player joined world", because there are no log about crash (just one line "--------- beginning of crash" and nothing after it) so i can't determine game crash caused by what

**Comment by khanhduytran0** [comment]
Yeah, it's known issues, maybe Sodium is incompatible with GL4ES.

**Comment by khanhduytran0** [comment]
So, you may use OptiFabric instead.

**Comment by khanhduytran0** [comment]
Also, Sodium will work after disable these options:
- Compact Vertex Format
- Fog occlusion

**Comment by rhjdvsgsgks** [comment]
thanks, after applying these settings, enter world will not crash anymore
