### ISSUE TITLE
Not found libdiscord-rpc.so

### ISSUE THREAD

**Issue by sunleafs** [PojavLauncherTeam/PojavLauncher#3409]
### Describe the bug

Not found libdiscord-rpc.so

### The log file and images/videos

---- Minecraft Crash Report ----
// My bad.

Time: 29/6/2022, 8:16 น.
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:174) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.35.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.35.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0-internal] {}
-- MOD pixelmon --
Details:
	Mod File: Pixelmon-1.16.5-9.0.4-universal.jar
	Failure message: Pixelmon Mod (pixelmon) encountered an error during the sided_setup event phase
		java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch/cache/drpc6471230307188456688/libdiscord-rpc.so: dlopen failed: "/data/data/net.kdt.pojavlaunch/cache/drpc6471230307188456688/libdiscord-rpc.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
	Mod Version: 9.0.4
	Mod Issue URL: https://pixelmonmod.com/tracker.php?p=2
	Exception message: java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch/cache/drpc6471230307188456688/libdiscord-rpc.so: dlopen failed: "/data/data/net.kdt.pojavlaunch/cache/drpc6471230307188456688/libdiscord-rpc.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
Stacktrace:
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0-internal] {}
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.System.load(Unknown Source) ~[?:1.8.0-internal] {}
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:156) ~[pixelmon:1.16.5-9.0.4] {re:classloading}
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:23) ~[pixelmon:1.16.5-9.0.4] {re:classloading}
	at com.pixelmonmod.pixelmon.client.richpresence.PixelmonRichPresence.init(PixelmonRichPresence.java:52) ~[pixelmon:1.16.5-9.0.4] {re:classloading}
	at com.pixelmonmod.pixelmon.client.richpresence.PixelmonRichPresence.<init>(PixelmonRichPresence.java:39) ~[pixelmon:1.16.5-9.0.4] {re:classloading}
	at com.pixelmonmod.pixelmon.client.ClientProxy.init(ClientProxy.java:187) ~[pixelmon:1.16.5-9.0.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_43_ClientProxy_init_FMLClientSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0-internal] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1227360648 bytes (1170 MB) / 2066219008 bytes (1970 MB) up to 2066219008 bytes (1970 MB)
	CPUs: 8
	JVM Flags: 4 total; -Xms2048M -Xmx2048M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.35.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.35.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.35
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.35-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |ENQUEUE_IM|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Pixelmon-1.16.5-9.0.4-universal.jar               |Pixelmon Mod                  |pixelmon                      |9.0.4               |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 2c29db83-56fd-4e2e-8768-11d6b39c73e3
![Screenshot_2022-06-29-15-25-07-27_bab8561a5f94f0a53956d8cbbeaad774](https://user-images.githubusercontent.com/58482247/176389481-0ad8b774-4c69-4963-aa30-8bbeb1b6d7c8.jpg)

### Steps To Reproduce

```markdown
I don' t understand
```

### Expected Behavior

I try to play pixelmon mod in 1.16.5

### Platform

```markdown
- Device model: Oppo Reno2
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: latest version
```

**Comment by GaucovyAero** [comment]
If I remember correctly, this is quite a complex issue. DiscordRPC is a mod likely built into Pixelmon and when you launch Minecraft on PC, it shows that you are playing Pixelmon. It's fine, but of course, it doesn't work on mobile. So, what you could try to do is disabling DiscordRPC in the Pixelmon config, if there even is a setting like that in the config file.

**Comment by Darkproxess** [comment]
> If I remember correctly, this is quite a complex issue. DiscordRPC is a mod likely built into Pixelmon and when you launch Minecraft on PC, it shows that you are playing Pixelmon. It's fine, but of course, it doesn't work on mobile. So, what you could try to do is disabling DiscordRPC in the Pixelmon config, if there even is a setting like that in the config file.

I deleted a file called lib.discord.so, or something like that and it worked, ty

**Comment by sunleafs** [comment]
> 

Can you give me your pixelmon file? Thx

**Comment by sunleafs** [comment]
> > If I remember correctly, this is quite a complex issue. DiscordRPC is a mod likely built into Pixelmon and when you launch Minecraft on PC, it shows that you are playing Pixelmon. It's fine, but of course, it doesn't work on mobile. So, what you could try to do is disabling DiscordRPC in the Pixelmon config, if there even is a setting like that in the config file.
> 
> I deleted a file called lib.discord.so, or something like that and it worked, ty

Can you give me your pixelmon file ? Thx

**Comment by digi65** [comment]
> ib.discord.so

can you send a sceenshot how the file looked liked because i dont where it is plz help

**Comment by huzaimbro** [comment]
In Pixelmon jar file open it then go to Linux folder and delete discord.rpc.so file the. It will work :)

**Comment by digi65** [comment]
i dont have the discord.rpc.so plz help me

**Comment by Animatoragfresh** [comment]
My pojavlauncher not run pixelmon 9.0.11

**Comment by ashvin127** [comment]
Same

**Comment by digi65** [comment]
does anybody know how to play pixelmon 9.0.11 on pojavluancher

**Comment by digi65** [comment]
plz help me

**Comment by huzaimbro** [comment]
I tried but it doesn't work let me fix it then I'll tell you

**Comment by Albedo13** [comment]
I also need help because the pixelmon reforged from version 9.1.0 does not open and I delete the file and nothing comes out because it says that the discord rpc file is missing

**Comment by victorYghor** [comment]
I have the same problem, I try to exlcude every file that have wirte pixelmon, but I dont know how transform this to a .jar file again, after the descompilation. I try to use  jar --create --file Pixelmon-1.16.5-9.1.9-universal.jar -C pixelmonn .
but the terminal says illegal option: - the project dont have a pom.xml file then in not possible to use maven for build the project

**Comment by victorYghor** [comment]
Hey guys you dont need to delete the discord files you can just, change some configure file, see how to do this: You can disable the discord RPC
Config folder - > pixelmon - > config.yml
https://pixelmonmod.com/wiki/Finding_your_config_files
