### ISSUE TITLE
[BUG] Create Fabric Mod not working / Crash

### ISSUE THREAD

**Issue by 0gp** [PojavLauncherTeam/PojavLauncher#3445]
### Describe the bug

I can not launch a instance with the Create mod installed.
Tested with both rendering engines.

### The log file and images/videos

```
---- Minecraft Crash Report ----
// Oops.

Time: 7/19/22, 8:06 AM
Description: Initializing game

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at net.minecraft.class_276.method_1239(class_276.java:167)
	at net.minecraft.class_276.method_1231(class_276.java:146)
	at net.minecraft.class_276.method_22596(class_276.java:69)
	at net.minecraft.class_276.method_1234(class_276.java:58)
	at net.minecraft.class_276.enableStencil(class_276.java:605)
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:273)
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:39)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:211)
	at com.mojang.blaze3d.systems.RenderSystem.finishInitialization(RenderSystem.java:1131)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_276.method_1239(class_276.java:167)
	at net.minecraft.class_276.method_1231(class_276.java:146)
	at net.minecraft.class_276.method_22596(class_276.java:69)
	at net.minecraft.class_276.method_1234(class_276.java:58)
	at net.minecraft.class_276.enableStencil(class_276.java:605)
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:273)
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:39)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:211)
	at com.mojang.blaze3d.systems.RenderSystem.finishInitialization(RenderSystem.java:1131)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 674226248 bytes (642 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd48 Stepping r0x0p2
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 12811.48
	Virtual memory used (MB): 9329.04
	Swap memory total (MB): 7168.00
	Swap memory used (MB): 1480.50
	JVM Flags: 2 total; -Xms2048M -Xmx2048M
	Fabric Mods: 
		create: Create mc1.18.2_v0.4.1+637
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 1.18-0.7.0.26
			forge_tags: Forge Tags 2.1
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			registrate-fabric: Registrate for Fabric MC1.18.2-1.0.3
		createaddition: Create Crafts & Additions ${version}
		createplus: CreatePlus 1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		fabric: Fabric API 0.56.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.0+6f01bfd860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.13+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.3+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.2+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.1+e747827960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		iknowwhatimdoing: I Know What I'm Doing 4.1.0
		java: OpenJDK 64-Bit Server VM 17
	Flywheel Backend: Uninitialized
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 8x 
```

### Steps To Reproduce

```markdown
1. install Fabric 0.14.8 MC 1.18.2
2. install Fabric API and Create Mod
3. Launch the game
4. crash ... :(
```

### Expected Behavior

game should load up

### Platform

```markdown
- Device model: Xiaomi 12 Pro
- CPU architecture: Snapdragon 8 Gen 1
- Android version: 12
- PojavLauncher version: Dahlia (Latest release from PlayStore)
```

**Comment by GaucovyAero** [comment]
Remove Create and Flywheel. These mods are not compatible with Pojav.

**Comment by MSandro** [comment]
Sad :(
