### ISSUE TITLE
Sign in with Microsoft 

### ISSUE THREAD

**Issue by alispectre** [PojavLauncherTeam/PojavLauncher#3450]
### Describe the bug

Hello, I bought a premium Microsoft account, but when I log in with Microsoft, Puchav Launcher gives error 401. Do you know why? 
error : 
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916235,"Message":"","Redirect":"http://support.xbox.com/xbox-live/country-not-authorized"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### The log file and images/videos

![Uploading Screenshot_۲۰۲۲-۰۷-۲۲-۲۳-۳۳-۵۳-۲۹۰_net.kdt.pojavlaunch.jpg…]()

### Steps To Reproduce

```markdown
خ
```

### Expected Behavior

پ

### Platform

```markdown
- Device model: XIAOMI REDMI NOTE 9
- CPU architecture: 8
- Android version: 11
- PojavLauncher version: latest version
```

**Comment by tomerda3** [comment]
What happen is that you Redirect to other page or some error page 
it maybe have something to do about kids strict
what you can try is to open a family package and then from them add your user

**Comment by GaucovyAero** [comment]
As the error says, country not authorized. You are probably located in Russia or somewhere where Minecraft is forbidden.
