### ISSUE TITLE
[BUG] <Error code 1>

### ISSUE THREAD

**Issue by 0bla4k0** [PojavLauncherTeam/PojavLauncher#3465]
### Describe the bug

Minecraft 1.19 Optifine, when creating a world, an error with code 1 pops up

### The log file and images/videos

12:47:18] [Render thread/INFO]: Loaded 1179 advancements
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

[12:47:24] [Server thread/INFO]: Starting integrated minecraft server version 1.19
[12:47:24] [Server thread/INFO]: Generating keypair
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

[12:47:29] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[12:47:29] [Render thread/INFO]: Подготовка области возрождения: 0%
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

ERROR: Unable to get more log.
[12:47:29] [Render thread/INFO]: Подготовка области возрождения: 0%
[12:47:30] [Render thread/INFO]: Подготовка области возрождения: 0%
[12:47:30] [Render thread/INFO]: Подготовка области возрождения: 0%
[12:47:31] [Render thread/INFO]: Подготовка области возрождения: 10%
[12:47:31] [Render thread/INFO]: Подготовка области возрождения: 47%
[12:47:32] [Render thread/INFO]: Подготовка области возрождения: 47%
[12:47:33] [Render thread/INFO]: Подготовка области возрождения: 47%
[12:47:33] [Render thread/INFO]: Подготовка области возрождения: 47%
[12:47:33] [Render thread/INFO]: Подготовка области возрождения: 47%
[12:47:34] [Render thread/INFO]: Подготовка области возрождения: 47%
[12:47:34] [Render thread/INFO]: Подготовка области возрождения: 47%
[12:47:35] [Render thread/INFO]: Подготовка области возрождения: 48%
[12:47:35] [Render thread/INFO]: Подготовка области возрождения: 50%
[12:47:36] [Render thread/INFO]: Подготовка области возрождения: 54%
[12:47:36] [Render thread/INFO]: Подготовка области возрождения: 58%
[12:47:37] [Render thread/INFO]: Подготовка области возрождения: 60%
[12:47:37] [Render thread/INFO]: Подготовка области возрождения: 64%
[12:47:38] [Render thread/INFO]: Подготовка области возрождения: 68%
[12:47:38] [Render thread/INFO]: Подготовка области возрождения: 71%
[12:47:39] [Render thread/INFO]: Подготовка области возрождения: 74%
[12:47:39] [Render thread/INFO]: Подготовка области возрождения: 78%
[12:47:40] [Render thread/INFO]: Подготовка области возрождения: 80%
[12:47:42] [Render thread/INFO]: Подготовка области возрождения: 82%
[12:47:42] [Render thread/INFO]: Подготовка области возрождения: 82%
[12:47:42] [Render thread/INFO]: Подготовка области возрождения: 82%
[12:47:42] [Render thread/INFO]: Подготовка области возрождения: 82%
[12:47:42] [Render thread/INFO]: Подготовка области возрождения: 82%
[12:47:42] [Render thread/INFO]: Time elapsed: 13829 ms
[12:47:43] [Server thread/INFO]: Changing view distance to 2, from 10
[12:47:43] [Server thread/INFO]: Changing simulation distance to 5, from 0
[12:47:44] [Render thread/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 95:ea:14:18:14:4c:93:75
[12:47:46] [Server thread/INFO]: JettWeber24[local:E:08f74148] logged in with entity id 1 at (-7.5, -60.0, 3.5)
[12:47:46] [Server thread/INFO]: JettWeber24 присоединился к игре
[12:47:48] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2004ms or 40 ticks behind
FATAL ERROR in native method: Thread[Render thread,10,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL30C.nglBindFragDataLocation(Native Method)
	at org.lwjgl.opengl.GL30C.glBindFragDataLocation(GL30C.java:1297)
	at org.lwjgl.opengl.GL30.glBindFragDataLocation(GL30.java:1315)
	at net.optifine.shaders.Shaders.setupProgram(Shaders.java:2998)
	at net.optifine.shaders.Shaders.init(Shaders.java:2592)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4820)
	at exn.a(GameRenderer.java:1501)
	at exn.a(GameRenderer.java:1187)
	at eev.f(SourceFile:1143)
	at eev.e(SourceFile:734)
	at net.minecraft.client.main.Main.main(SourceFile:237)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17-internal/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17-internal/Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17-internal/Unknown Source)
	at java.lang.reflect.Method.invoke(java.base@17-internal/Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
process killed with signal 6 code 0xffffffff addr 0x297e000029bd
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7c6eb61bac)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7c6eb60110)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7c6eb60110)

### Steps To Reproduce

```markdown
1.Захожу в Майнкрафт 
2.I choose the world and go into it 
3.The world is loading after 100% an error pops up
```

### Expected Behavior

Waiting for the game to launch 

### Platform

```markdown
- Device model: redmi note 9 pro 6/64
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: (latest version)
```

**Comment by SrBinfrut** [comment]
En lo que yo instalo optifine me sale error code 1 y no puedo instalar

**Comment by GaucovyAero** [comment]
Make sure you have Render Regions disabled.
