### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by 1248257** [PojavLauncherTeam/PojavLauncher#3485]
### Describe the bug

java.lang.RuntimeException: It seems that this Microsoft Account does not own the game. Make sure that you have bought/migrated to your Microsoft account.

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

### The log file and images/videos

![Screenshot_20220807-110042_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/68475844/183294511-55d0c556-f48b-4085-9cdd-db5dfcdfacab.jpg)

### Steps To Reproduce

```markdown
Tentar entrar na conta da Microsoft
```

### Expected Behavior

Qua entre na conta pra poder baixar o jogo

### Platform

```markdown
- Device model:j4+
- CPU architecture:aarch32
- Android version:9
- PojavLauncher version:Última versão
```

**Comment by selut06** [comment]
not a bug, you must get minecraft account/online account on minecraft.net
