### ISSUE TITLE
why pojavlauncher doesn't work?(pls help me)

### ISSUE THREAD

**Issue by elyesgmzboi** [PojavLauncherTeam/PojavLauncher#351]
i copied this from the launcher
java.io.FileNotFoundException: /data/data/net.kdt.pojavlaunch/jre_runtime/release (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:755)
	at net.kdt.pojavlaunch.MainActivity.checkJavaArchitecture(MainActivity.java:961)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:951)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:28)
	at net.kdt.pojavlaunch.MainActivity$13$1.run(MainActivity.java:717)
	at java.lang.Thread.run(Thread.java:764)

**Comment by khanhduytran0** [comment]
Seems you installed an invalid java runtime.

**Comment by khanhduytran0** [comment]
Which one do you installed?

**Comment by elyesgmzboi** [comment]
i installed aarch64

**Comment by elyesgmzboi** [comment]
i mean aarch64-20200927.tar.xz

**Comment by khanhduytran0** [comment]
Mcinabox runtime is not compatible with this launcher!

**Comment by khanhduytran0** [comment]
Use this instead https://github.com/PojavLauncherTeam/PojavLauncher/releases/download/v3.2.0-testing6/jre9-arm64-20200929.tar.xz

**Comment by 8charac** [comment]
idk
