### ISSUE TITLE
Microsoft login error

### ISSUE THREAD

**Issue by IAmGaryTheCat** [PojavLauncherTeam/PojavLauncher#3523]
### Describe the bug

I own minecraft but whe i trybto login it gives me this error

java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
Login with microsoft
```

### Expected Behavior

It logs in

### Platform

```markdown
- Device model: galaxy s20fe
- CPU architecture: arm
- Android version: 12 
- PojavLauncher version: newest
```

**Comment by GaucovyAero** [comment]
the known AddChildToFamily crash, you have to create an xbox parent account and link your child account to it, otherwise you wont be able to log in

**Comment by SkulZOnTheYT** [comment]
there is another way to fix, namely by buying Minecraft with a mojang account, so you don't have problems logging in 🗿

**Comment by SkulZOnTheYT** [comment]
I also have difficulty logging in using Microsoft, the method is difficult in the Pojav launcher, I recommend using a Mojang account, besides being practical, it's also easy.

**Comment by khanhduytran0** [comment]
@SkulZOnTheYT Mojang account is deprecated in favor of Microsoft account. You have no way to use a Mojang account to buy Minecraft nowadays.

**Comment by SkulZOnTheYT** [comment]
> @SkulZOnTheYTAkun Mojang tidak digunakan lagi untuk akun Microsoft. Anda tidak memiliki cara untuk menggunakan akun Mojang untuk membeli Minecraft saat ini.

but many online shops sell Mojang accounts cheaply and safely, btw I bought from the online shop for only $9 USD 😅
I'm from Indonesia our currency rate is $9 USD = IDR 139.000

**Comment by SkulZOnTheYT** [comment]
Maybe some countries can't do a mojang account to buy minecraft, but in my country it's still valid so it's only natural🗿

**Comment by SkulZOnTheYT** [comment]
> @SkulZOnTheYTAkun Mojang tidak digunakan lagi untuk akun Microsoft. Anda tidak memiliki cara untuk menggunakan akun Mojang untuk membeli Minecraft saat ini.

I'm not wrong, I see you're using Indonesian 💀

**Comment by GaucovyAero** [comment]
AddChildToFamily and pirating issue. The issues are not necessarily leading to PojavLauncher being the problem. Closing.

**Comment by E6rg7t** [comment]
649097649097649097794595794595752603794595752603649097752603649097794595752603794595752603794595649097752603794595752603649097794595649097752603794595_649097649097794595649097794595649097649097794595649097649097794595649097794595649097794595649097_

**Comment by VenomousSteam81** [comment]
> 649097649097649097794595794595752603794595752603649097752603649097794595752603794595752603794595649097752603794595752603649097794595649097752603794595_649097649097794595649097794595649097649097794595649097649097794595649097794595649097794595649097_

whar
