### ISSUE TITLE
Getting isuues to login my Microsoft account 

### ISSUE THREAD

**Issue by anuragamer** [PojavLauncherTeam/PojavLauncher#3538]
When I use to login my Minecraft account this error come 

java.net.ConnectException: Failed to connect to api.minecraftservices.com/52.84.150.25:443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:191)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

![Screenshot_20220905_190529](https://user-images.githubusercontent.com/112882168/188473310-6dd58475-057d-45dd-baa7-7f61c5a3eaa6.jpg)

### Steps To Reproduce

```markdown
api.minecraftservices.com/52.84.150.25:443
```

### Expected Behavior

When I try to login my Minecraft account it's show me above error 

### Platform

```markdown
- Device model: iqoo Neo 6 8gb 
- CPU architecture: aarch 64
- Android version: 12
- PojavLauncher version: dahila-8
```

### Anything else?

Please help me to fix

**Comment by GaucovyAero** [comment]
never seen this (or rather, no one has had this yet before), absolutely no idea

**Comment by GaucovyAero** [comment]
but maybe it could be caused by your country being banned from Minecraft, not sure.

**Comment by SmileBoy45** [comment]
Prueba reiniciando la app

**Comment by dontbanmeplz** [comment]
Sounds dumb, but restarting helped me

**Comment by SmileBoy45** [comment]
En serio??

**Comment by anuragamer** [comment]
Thanks

**Comment by orang498** [comment]
https://github.com/session
