### ISSUE TITLE
Pojav launcher 1.6.4 forge issu.....

### ISSUE THREAD

**Issue by Secure96t** [PojavLauncherTeam/PojavLauncher#3549]
### Describe the bug

as soon as i start forge 1.6.4 it shows black screen does not open completely forge 1.6.4 i have downloaded version 1.6.4 fully still this issu coming  Watch my screenshot and provide me best apk forge with optifine. 

### The log file and images/videos
images.githubusercontent.com/113331700/189585138-a03ddd43-d53d-414c-ad33-9049e68e2b85.jpg)
![Screenshot_2022-09-12-11-27-30-507_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/113331700/189585175-136a2bb0-3e35-42fc-9267-55aaa52ca81f.jpg)
![Screenshot_2022-09-12-11-27-18-990_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/113331700/189585185-80a89d2f-b4d5-4190-a368-5eb56c171bad.jpg)
![Screenshot_2022-09-12-11-26-30-189_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/113331700/189585188-6a4f516a-c5de-4c43-95d5-3fd624b39b70.jpg)
![Screenshot_2022-09-12-11-23-59-664_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/113331700/189585195-0c7b72e6-156b-444a-9b60-c015869066c6.jpg)

### Steps To Reproduce

```markdown
2022-09-12 05:56:56 [INFO] [ForgeModLoader] Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
2022-09-12 05:56:56 [INFO] [ForgeModLoader] Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
2022-09-12 05:56:56 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2022-09-12 05:56:56 [INFO] [STDOUT] Loaded 110 rules from AccessTransformer config file forge_at.cfg
2022-09-12 05:56:56 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
2022-09-12 05:56:56 [INFO] [ForgeModLoader] Launching wrapped minecraft {net.minecraft.client.main.Main}
2022-09-12 05:56:56 [SEVERE] [ForgeModLoader] Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at net.minecraft.client.main.Main.main(SourceFile:37)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:186)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.findAndMergeSuperMaps(FMLDeobfuscatingRemapper.java:378)
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getMethodMap(FMLDeobfuscatingRemapper.java:355)
	at cpw.mods.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mapMethodName(FMLDeobfuscatingRemapper.java:328)
	at org.objectweb.asm.commons.RemappingMethodAdapter.visitMethodInsn(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:39)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:274)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClas
s(LaunchClassLoader.java:172)
	... 9 more
Java Exit code: 0
I/jrelog  (20321): Going to free args
I/jrelog  (20321): Free done
```

### Expected Behavior

Pojav launcher 1.6.4 not start please help.

### Platform

```markdown
- Device model: redmi note 10s 
- CPU architecture:
- Android version: 13.0.3
- PojavLauncher version: crocus-299-f1bd70996-v3_openjdk
```

**Comment by mchnjt** [comment]
forge issu.......

**Comment by GaucovyAero** [comment]
ima send the fix in a few minutes

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/file/ojhk4i28sizplnl/PojavLauncher_Forge_1.3.2-1.7.2_Patchpack_v1.0.zip/file

extract this ZIP and then replace your Forge 1.6.4 JSON with the one included here.

**Comment by Secure96t** [comment]
where to do paste files folder name and full details please.

**Comment by Secure96t** [comment]
Screenshot upload please

**Comment by GaucovyAero** [comment]
> where to do paste files folder name and full details please.

`/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.6.4-Forge9.11.1.1345/1.6.4-Forge9.11.1.1345.json`

**Comment by GaucovyAero** [comment]
> > where to do paste files folder name and full details please.
> 
> `/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.6.4-Forge9.11.1.1345/1.6.4-Forge9.11.1.1345.json`

just like this

**Comment by Secure96t** [comment]
![Screenshot_2022-09-12-13-49-02-654_com lonelycatgames Xplore](https://user-images.githubusercontent.com/113331700/189605963-39f98f04-ab18-401c-90ae-93cee09c75a0.jpg)
![Screenshot_2022-09-12-13-48-52-716_com lonelycatgames Xplore](https://user-images.githubusercontent.com/113331700/189605971-5daa7b65-5a25-45d8-8fd4-746051ea2539.jpg)

Ok this

**Comment by GaucovyAero** [comment]
pick the 1.6.4 one and insert it there

**Comment by Secure96t** [comment]
I am play and this issue java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.6.4-Forge9.11.1.1345/1.6.4-Forge9.11.1.1345.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:624)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:504)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:52)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:25)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.6.4-Forge9.11.1.1345/1.6.4-Forge9.11.1.1345.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:692)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:532)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8171)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 13 more

**Comment by GaucovyAero** [comment]
yes, because you inserted the 1.4.6 one instead of 1.6.4

**Comment by Secure96t** [comment]
![Screenshot_2022-09-12-13-54-07-100_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/113331700/189606973-0aa7d9cd-f5fa-4053-9e1e-285b3069d04d.jpg)

Thank you so much💖💖💖💖💖💓💗💖💓🙂🙂🙂🙂🙂

**Comment by Secure96t** [comment]
Nice app and nice website thank you so much help me

**Comment by GaucovyAero** [comment]
epik!1!!11!1!!!11
