### ISSUE TITLE
[BUG] Game crashes on startup.

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#357]
**Describe the bug**
The game crashes on startup and throws error.

**To Reproduce**
1. Download aarch32_runtime_20200328.tar.xz
2. Start PojavLauncher.
3. Install Runtime.
4. Run any version.

**Expected behavior**
I expected to see the game loading.

**Screenshots**
![Screenshot_20201015-233353_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/69990794/96171851-f653ad00-0f3e-11eb-9325-50d31892a52f.png)

**Platform:**
 - Device Model: Samsung Galaxy A51.
 - CPU architecture: aarch64.
 - Android Version: 10.

**Additional context**
Warning: Text was translated using Google Translate.
I tried to install aarch32 since aarch64 cannot be found in the .tar.xz extension. This runtime works fine with MCinaBox.

I read the information about aarch64, that you need to compile it yourself, but I don't know how to do this, and besides, it's complicated.

Log:
java.io.FileNotFoundException: /data/data/net.kdt.pojavlaunch/jre_runtime/release: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:755)
	at net.kdt.pojavlaunch.MainActivity.checkJavaArchitecture(MainActivity.java:961)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:951)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:28)
	at net.kdt.pojavlaunch.MainActivity$13$1.run(MainActivity.java:717)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7896)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 8 more

**Comment by mglovers123** [comment]
Cuka Blyat

**Comment by mglovers123** [comment]
@JustM1les  This Runtime for mcinabox not for PojavLauncher

**Comment by Malaska678** [comment]
> @JustM1les This runtime is for mcinabox not for PojavLauncher

Able to use mcinabox runtime but u must do this. Extract j2re image. Then compress it to tar.xz format. Then must modify launcher's runtime loading

**Comment by nightgolem1223** [comment]
How to fix this i have aarch32
java.io.FileNotFoundException: /data/data/net.kdt.pojavlaunch/jre_runtime/release: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at java.io.FileReader.<init>(FileReader.java:66)
	at net.kdt.pojavlaunch.utils.JREUtils.readJREReleaseProperties(JREUtils.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:881)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2300(BaseMainActivity.java:26)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:679)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 8 more

**Comment by hassan342ha** [comment]
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

**Comment by hassan342ha** [comment]
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
https://start.ui.xboxlive.com/CreateAccount

**Comment by wexxiz** [comment]
Здравствуйте! У меня вопрос при запуске Rasty client после 100% выдает ошибку -1 и вылетает, как решить?
