### ISSUE TITLE
cant login with my microsoft account even though i own the game

### ISSUE THREAD

**Issue by epicyeeto** [PojavLauncherTeam/PojavLauncher#3593]
### Describe the bug

cant login with my microsoft account even though i own the game

### The log file and images/videos

java.lang.RuntimeException: 

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "error" : "NOT_FOUND",
  "errorMessage" : "Not Found"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:256)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:200)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

### Steps To Reproduce

```markdown
start pojav
click microsoft login
enter my credentials
```

### Expected Behavior

i expect to login with my account

### Platform

```markdown
- Device model: lenovo 100e chromebook
- CPU architecture: x64 
- Android version: idk
- PojavLauncher version: update on june 3rd 2022
```

**Comment by epicyeeto** [comment]
i can login to minecraft.net but not this

**Comment by GaucovyAero** [comment]
microsoft is having some downtimes and issues rn, just be patient i guess...

**Comment by epicyeeto** [comment]
alr

**Comment by epicyeeto** [comment]
it was microsoft not working
