### ISSUE TITLE
[BUG] Cannot start modded versions

### ISSUE THREAD

**Issue by Blue-Beaker** [PojavLauncherTeam/PojavLauncher#3641]
### Describe the bug

When I try to start modded version like fabric or optifine, it immediately popups an error and can't start:
```java.lang.RuntimeException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList```
Vanilla versions works fine however.

### The log file and images/videos

 the latestlog.txt isn't produced
```
java.lang.RuntimeException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:740)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:644)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:525)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:54)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:27)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:659)
	... 10 more
```

![Screenshot_2022-11-06-10-47-09-553_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/17115547/200151593-a39b884d-67bd-4af7-9d70-f7c27299b431.jpg)

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Login with microsoft
3. Select a modded version created with early versions of pojavlauncher like dahlia-8-f527e8a14-v3_openjdk from google play
4. launch game.
```

### Expected Behavior

Game launches

### Platform

```markdown
- Device model: Mi 8 8/128G
- CPU architecture: arm64-v8a
- Android version: 9
- PojavLauncher version: dahlia-125-8f410d5f7-v3_openjdk from Android CI #4003
```

**Comment by khanhduytran0** [comment]
Known issue, use [#3997](https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3370199705) for this moment

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
