### ISSUE TITLE
Невозможно скачать 

### ISSUE THREAD

**Issue by V-I-L** [PojavLauncherTeam/PojavLauncher#3642]
### Describe the bug

Как блин скачать этот ваш лаунчер с этого долбанного ГитХаба??? КАК??????
Я играть хочу! :(((
А скачанный с других сайтов этот лаунчер не работает и выдаёт ошибку при попытке входа через учётную запись

### The log file and images/videos

java.lang.RuntimeException: 

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "error" : "NOT_FOUND",
  "errorMessage" : "Not Found"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:272)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:235)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:201)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:167)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
Добавить нормальную ссылку для скачивания на главную страницу!
```

### Expected Behavior

Всё должно работать!!!

### Platform

```markdown
- Device model: realme gt 2 pro/256gb
- CPU architecture: Gen 1
- Android version: 12
- PojavLauncher version: latest
```

### Anything else?

ДОБАВЬТЕ ПОЖАЛУЙСТА НОРМАЛЬНУЮ ССЫЛКУ ДЛЯ СКАЧИВАНИЯ С ЭТОГО ИДИОТСКОГО САЙТА!

**Comment by WaviestBalloon** [comment]
https://pojavlauncherteam.github.io/INSTALL.html#android

**Comment by GaucovyAero** [comment]
log into minecraft.net, this is not a pojav issue
