### ISSUE TITLE
[BUG] Null pointer exception after signing in with a Microsoft account

### ISSUE THREAD

**Issue by heitor-lassarote** [PojavLauncherTeam/PojavLauncher#3644]
### Describe the bug

Crashes after signing in with a Microsoft account on a fresh Pojav install.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap net.kdt.pojavlaunch.value.MinecraftAccount.getSkinFace()' on a null object reference
	at net.kdt.pojavlaunch.PojavLauncherActivity.pickAccount(PojavLauncherActivity.java:275)
	at net.kdt.pojavlaunch.PojavLauncherActivity.onCreate(PojavLauncherActivity.java:154)
	at android.app.Activity.performCreate(Activity.java:7148)
	at android.app.Activity.performCreate(Activity.java:7139)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3111)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3270)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1986)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:215)
	at android.app.ActivityThread.main(ActivityThread.java:6939)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9946363/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Sign in with a Microsoft account
3. It might crash with a roughly 50% chance
```

### Expected Behavior

No crash after signing in. BTW, it's annoying that it doesn't remember that I signed in and need to insert e-mail and password every time.

### Platform

```markdown
- Device model: Moto Z2 Play
- CPU architecture: I don't know, but I'd guess arm64?
- Android version: 9
- PojavLauncher version: Download from here: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3401065597
```

**Comment by WaviestBalloon** [comment]
I had a similar bug, after signing in with a Microsoft account it throws a `NullPointerException` and crashes (But not like the log you uploaded)
I found out that it had already logged me in when it crashed, relaunching then clicking Select Account in the login screen made my account appear, after that everything seems to be working normaly.

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
