### ISSUE TITLE
[BUG] Forge Crash when launching the game game

### ISSUE THREAD

**Issue by anshoo2745** [PojavLauncherTeam/PojavLauncher#3654]
### Describe the bug

java.lang.RuntimeException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:740)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:644)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:525)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:54)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:27)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:659)
	... 10 more

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9990555/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open Pojav Launcher
2. use forge client 
3. And it doesn't launch and it crashes
```

### Expected Behavior

I expected it could open with a clean installation but it doesn't 

### Platform

```markdown
- Device model: Realme Narzo 20 4/64GB
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: actions #3997
```

### Anything else?

I am using #3997 and i didn't use chrome for downloading forge i dunno why i am getting this and i reinstalled the #3997 action but the same thing happens

**Comment by wkosh** [comment]
what version did you use?
And if you are trying to start forge with a local account I say my condolences because it will not work

**Comment by GaucovyAero** [comment]
can you send vanilla latestlog.txt even if it works?

**Comment by anshoo2745** [comment]
I am using 1.8.9 version and i have a premium account ok

**Comment by anshoo2745** [comment]
> can you send vanilla latestlog.txt even if it works?
Yeah sure 
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9990797/latestlog.txt)

**Comment by GaucovyAero** [comment]
> > can you send vanilla latestlog.txt even if it works?
> > Yeah sure
> > [latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9990797/latestlog.txt)

you are not using #3997, because 3997 is dahlia-114 and yours is dahlia-116

**Comment by anshoo2745** [comment]
Can you give me the link

**Comment by GaucovyAero** [comment]
> Can you give me the link

i wont, try doing it yourself

**Comment by anshoo2745** [comment]
Hello i have already downloaded that and it is of the same thing which i have the pojav launcher is this not because of backup i have taken from old version

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
