### ISSUE TITLE
[BUG] ClassCastException when running Fabric 0.14.10 on 1.19.2

### ISSUE THREAD

**Issue by TheoCGaming** [PojavLauncherTeam/PojavLauncher#3655]
### Describe the bug

Game crashes on startup with
```
java.lang.RuntimeException: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:740)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:644)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:525)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:54)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:27)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to net.kdt.pojavlaunch.JMinecraftVersionList
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:659)
	... 10 more
```

### The log file and images/videos

No log is generated.

Device Info: Samsung SM-G965U, Android 10
Installation info:
- Game version: 1.19.2
- Fabric version: 0.14.10
- Modpack: Fabulously Optimized *(irrelevant?)*

### Steps To Reproduce

```markdown
0. Prerequisites: Fabric Mod Loader, Fabulously Optimized, Android 10
1. Start Pojav
2. Log in
3. Install Fabric and F.O.
4. Run the Fabric installation
```

### Expected Behavior

The game launches (maybe with issues) but it'll at least *run*

### Platform

```markdown
- Device model: Samsung G965U (Galaxy S9+ 64GB)
- CPU architecture: aarch64 rev12
- Android version: 10
- PojavLauncher version: Commit 8f410d5 (11/5/2022)
```

**Comment by GaucovyAero** [comment]
pretty sure this is a java version issue, you have to use java 17 for 1.19.2, it should unpack automatically if you select auto

**Comment by GaucovyAero** [comment]
oh uhm, sorry, this is fixed in the latest play store build
