### ISSUE TITLE
[BUG] Json Version Error (Lastest Action)

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#3657]
### Describe the bug

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.8.9/1.8.9.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:766)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:670)
	at net.kdt.pojavlaunch.LauncherActivity.lambda$new$7$LauncherActivity(LauncherActivity.java:135)
	at net.kdt.pojavlaunch.-$$Lambda$LauncherActivity$B1-B7QhxyBQLFI7s1ErNsYBNkIg.onValueSet(Unknown Source:4)
	at net.kdt.pojavlaunch.extra.ExtraCore.setValue(ExtraCore.java:58)
	at net.kdt.pojavlaunch.fragments.MainMenuFragment.lambda$onViewCreated$4(MainMenuFragment.java:41)
	at net.kdt.pojavlaunch.fragments.-$$Lambda$MainMenuFragment$DRjVNqdrEsBB2fl8f4PU-NjHNC4.onClick(Unknown Source:0)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:858)
	at android.view.View$PerformClick.run(View.java:29126)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8302)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/versions/1.8.9/1.8.9.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:835)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:675)
	... 18 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8172)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 22 more

### The log file and images/videos

[latestcrash.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9994102/latestcrash.txt)

### Steps To Reproduce

```markdown
1.Start Poja
2 Login Account
3. Create Profile
4. Click Play
```

### Expected Behavior

Need To Download

### Platform

```markdown
- Device model: Redmi Note 10
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: Lastest Action Build
```

**Comment by artdeell** [comment]
Known issue

**Comment by ssaagamemer** [comment]
Oh ok
