### ISSUE TITLE
[BUG] Forge 1.12.2 refuse to start

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#3665]
### Describe the bug

Exception in thread "main" 
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java Exit code: 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/9996544/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Login With Microsoft Account
3. Select Forge 1.12.2 Version
4. Crash
```

### Expected Behavior

Game Will Launch

### Platform

```markdown
- Device model: Redmi Note 10
- CPU architecture: aarch64
- Android version: 11 (MIUI 13.0.10)
- PojavLauncher version: Lastest Action #4021
```

**Comment by ssaagamemer** [comment]
i know before but i forgot (Wrong jre)
