### ISSUE TITLE
The launcher crashes as soon as I enter it.

### ISSUE THREAD

**Issue by Kolyanpetuh** [PojavLauncherTeam/PojavLauncher#3689]
### Describe the bug

When I open the app, it instantly crashes. downloaded from Google Play, I have purchased the game.

### The log file and images/videos

PojavLauncher crash report
 - Time: 17 нояб. 2022 г. 08:51:26
 - Device: aosp_miatoll Redmi Note 9 Pro
 - Android version: 12
 - Crash stack trace:
 - Launcher version: dahlia-159-b581c7ba8-v3_openjdk
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.LauncherActivity}: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:155)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1345)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288)
	at com.kdt.mcgui.mcAccountSpinner.reloadAccounts(mcAccountSpinner.java:241)
	at com.kdt.mcgui.mcAccountSpinner.init(mcAccountSpinner.java:133)
	at com.kdt.mcgui.mcAccountSpinner.<init>(mcAccountSpinner.java:53)
	... 29 more

### Steps To Reproduce

```markdown
To be honest, I don't know.
```

### Expected Behavior

I expect the launcher to launch normally.

### Platform

```markdown
- Device model: Xiaomi Redmi Note 9 Pro
- CPU architecture: Qualcomm Snapdragon 620G
- Android version: 12L
- PojavLauncher version: dahlia-159-b581c7ba8-v3_openjdk
```

**Comment by GaucovyAero** [comment]
Have you tried uninstalling and deleting all pojav data, restarting your phone and reinstalling?

**Comment by Kolyanpetuh** [comment]
> Have you tried uninstalling and deleting all pojav data, restarting your phone and reinstalling?

I tried it all. First the launcher started But when I tried to sign in to my Microsoft account, it crashed again. Here is the file latestcrash.txt:
PojavLauncher crash report
 - Time: 17 нояб. 2022 г. 18:56:44
 - Device: aosp_miatoll Redmi Note 9 Pro
 - Android version: 12
 - Crash stack trace:
 - Launcher version: dahlia-159-b581c7ba8-v3_openjdk
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.LauncherActivity}: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:155)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1345)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288)
	at com.kdt.mcgui.mcAccountSpinner.reloadAccounts(mcAccountSpinner.java:241)
	at com.kdt.mcgui.mcAccountSpinner.init(mcAccountSpinner.java:133)
	at com.kdt.mcgui.mcAccountSpinner.<init>(mcAccountSpinner.java:53)
	... 29 more

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
