### ISSUE TITLE
PojavLauncher Team, a little question for you (Forge not working on v3.2) 

### ISSUE THREAD

**Issue by Statzar** [PojavLauncherTeam/PojavLauncher#370]
Pojav Launcher Team, such a question for you. Will forge work if you transfer the folder with it from .minecraft to the pc version? Primarily interested in 1.12.2

**Comment by Statzar** [comment]
I just really want to play minecraft forge on my phone. By the way, thank you very much for the work done so far, almost all the versions that I downloaded have started

**Comment by khanhduytran0** [comment]
It should work, in v3, after you disable Forge splash screen.

**Comment by Statzar** [comment]
> Он должен работать в версии 3 после того, как вы отключите заставку Forge.

And how and where to turn it off?

**Comment by khanhduytran0** [comment]
Edit file `.minecraft/config/splash.properties`:
```
enabled=true
```
Change true to false.

**Comment by Statzar** [comment]
Thank

**Comment by Statzar** [comment]
@khanhduytran0, Doesn't work, what happened?
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2020-10-21 07:28
Description: Initializing game

java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newFieldAccessor(java.lang.reflect.Field, boolean)
	at net.minecraftforge.registries.ObjectHolderRef.<init>(ObjectHolderRef.java:93)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:132)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:80)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:626)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at ClassWrapper.main(ClassWrapper.java:30)
Caused by: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newFieldAccessor(java.lang.reflect.Field, boolean)
	at java.base/java.lang.Class.getDeclaredMethod(Unknown Source)
	at net.minecraftforge.registries.ObjectHolderRef$FinalFieldHelper.makeWritable(ObjectHolderRef.java:168)
	at net.minecraftforge.registries.ObjectHolderRef.<init>(ObjectHolderRef.java:89)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ObjectHolderRef.<init>(ObjectHolderRef.java:93)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:132)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:80)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:626)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at ClassWrapper.main(ClassWrapper.java:30)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version 8.1.0
	Java Version: 9-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 343679008 bytes (327 MB) / 536870912 bytes (512 MB) up to 905969664 bytes (864 MB)
	JVM Flags: 8 total; -Xms384m -Xmx850m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LC    | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LC    | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LC    | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	Launched Version: Forge 1.12.2
	LWJGL: 3.2.3 build 13
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 5x null

**Comment by khanhduytran0** [comment]
It seems that Forge 1.12.2 and below does not run correctly on java9...

**Comment by khanhduytran0** [comment]
You may try other like 1.12.

**Comment by Statzar** [comment]
@khanhduytran0, Artdell said that the problem can be solved with 8 jdk. But I will still try other versions of forge

**Comment by Statzar** [comment]
"And this is an example of how the program uses internal APIs
which are not on OpenJDK, because they were replaced there" - Artdell (rus discord) Maybe he's right

**Comment by Statzar** [comment]
@khanhduytran0 1.12 and 1.7.10 crashed
![Screenshot_20201021-115000](https://user-images.githubusercontent.com/64459276/96696938-0383f800-1394-11eb-8b8c-878b7c626e94.png)
![Screenshot_20201021-114949](https://user-images.githubusercontent.com/64459276/96696946-054dbb80-1394-11eb-92aa-0ae0c00dbbee.png)
![Screenshot_20201021-115141](https://user-images.githubusercontent.com/64459276/96696950-05e65200-1394-11eb-87a9-6e26b902a4fd.png)
![Screenshot_20201021-115016](https://user-images.githubusercontent.com/64459276/96696953-067ee880-1394-11eb-952c-26c3d0c62e94.png)
![Screenshot_20201021-114838](https://user-images.githubusercontent.com/64459276/96696955-07177f00-1394-11eb-89b0-4b14ae3b9cbb.png)
![Screenshot_20201021-114914](https://user-images.githubusercontent.com/64459276/96696957-0848ac00-1394-11eb-8532-3cc8b8d3bca9.png)
![Screenshot_20201021-114847](https://user-images.githubusercontent.com/64459276/96696960-0979d900-1394-11eb-80e6-c665ceca8641.png)
[crash-2020-10-21_08.49.46-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5414580/crash-2020-10-21_08.49.46-client.txt)
[crash-2020-10-21_08.51.37-client.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/5414584/crash-2020-10-21_08.51.37-client.txt)

**Comment by Statzar** [comment]
Screenshots are mixed. Where there is only one line in the log, it is 1.7.10, and where there is a lot, it is 1.12

**Comment by WesleyVanNeck** [comment]
forge isnt suported

**Comment by Statzar** [comment]
> Forge isnt support

![Screenshot_20201021-120604](https://user-images.githubusercontent.com/64459276/96698530-e7815600-1395-11eb-9967-ba064fce2147.png)

**Comment by khanhduytran0** [comment]
> forge isnt suported

It isn't true at all. Forge 1.13.2 could be launch normally in Java9.

**Comment by khanhduytran0** [comment]
> Screenshots are mixed. Where there is only one line in the log, it is 1.7.10, and where there is a lot, it is 1.12

Maybe wait for several minutes (1.7.10?)

**Comment by Statzar** [comment]
> > Скриншоты смешанные. Если в журнале только одна строка, это 1.7.10, а там, где много, это 1.12.
> 
> Maybe wait for several minutes (1.7.10?)

On 1.7.10 also crashes

**Comment by khanhduytran0** [comment]
So
- Try Forge 1.13.2
- If want Forge 1.12.2 and below working, wait us to port JRE8 to Android.

**Comment by Malaska678** [comment]
> So
> 
> * Try Forge 1.13.2
> * If want Forge 1.12.2 and below working, wait us to port JRE8 to Android.

But wut about using mcinabox's runtime before port?

**Comment by WesleyVanNeck** [comment]
> > forge isnt suported
> 
> It isn't true at all. Forge 1.13.2 could be launch normally in Java9.

doesnt work for me

**Comment by WesleyVanNeck** [comment]
you will get same error as always

**Comment by khanhduytran0** [comment]
> But wut about using mcinabox's runtime before port?

As you have tried.

**Comment by Statzar** [comment]
@khanhduytran0 Another question. Is it possible to get the keyboard to work on version 1.12.2? I cannot login to chat

**Comment by mglovers123** [comment]
Ululu

**Comment by khanhduytran0** [comment]
> @khanhduytran0 Another question. Is it possible to get the keyboard to work on version 1.12.2? I cannot login to chat

Use Gboard.

**Comment by Statzar** [comment]
> > @khanhduytran0 Another question. Is it possible to get the keyboard to work on version 1.12.2? I cannot login to chat
> 
> Use Gboard.

Thanks. @khanhduytran0, can you see the screenshots of the forge magazine that I sent yesterday while you were sleeping? In the "Discord" on "pojavlauncher-en"?

**Comment by khanhduytran0** [comment]
So, it crashes?

**Comment by Statzar** [comment]
Yes, there are 1.7.10, 1.12.2 and 1.13.2

> Итак, вылетает?

**Comment by Statzar** [comment]
I used a PC to download forge 1.13.2 but it still crashed. But optifine 1.12.2 works

**Comment by Statzar** [comment]
@khanhduytran0, By the way, maybe the problem is that I downloaded and played forge on java 8, and pojavlauncher works on java 9? I'm right?

**Comment by khanhduytran0** [comment]
```
java.lang.RuntimeException: java.lang.NoSuchMethodException: sun.reflect.ReflectionFactory.newFieldAccessor(java.lang.reflect.Field, boolean)
```
Maybe, I think it was a breaking change that make Forge not working on Java9.

**Comment by Statzar** [comment]
ok then i try to update java on pc and install forge then transfer to android and run

**Comment by khanhduytran0** [comment]
No, the Forge itself does not work on Java 9.

**Comment by khanhduytran0** [comment]
(1.12.2 and below)

**Comment by Statzar** [comment]
> (1.12.2 и ниже)

1.13.2?

**Comment by Statzar** [comment]
Ok, then the last question and I will close this issue. What is the approximate time frame for the launcher for java 8?

**Comment by CosineMath** [comment]
I think openjdk-8 in MCinaBox's runtime pack can help.

**Comment by Malaska678** [comment]
> I think openjdk-8 in MCinaBox's runtime pack can help.

They attempt to use jdk8 mcinabox becoz i recommend it to test speed. But duy is crashing becoz of libnet.so. Also no keys is working and cant click. So they will create own port @CosineMath

**Comment by khanhduytran0** [comment]
For me, it crashes at libnet.so, so I gonna do my port (see some changes by you, based on JDK9 mobile port, right?)

**Comment by Malaska678** [comment]
> For me, it crashes at libnet.so, so I gonna do my port (see some changes by you, based on JDK9 mobile port, right?)

But older ports by them requires alot of work.

**Comment by Malaska678** [comment]
https://github.com/CosineMath/openjdk-jdk8u-aarch32-android-old/commit/b35018b09cfab447eefc81424ea2de97b6eb670c

**Comment by khanhduytran0** [comment]
But https://github.com/CosineMath/openjdk-jdk8u-aarch32-android/commit/232d78685dabd13412995d6d87076ec0b426650e is diff

**Comment by CosineMath** [comment]
Sorry to hear that it could not help :(
Would you provide some logs about crashing at libnet.so?

**Comment by CosineMath** [comment]
Yes, I copy more codes from jdk9mobile in my new port.

**Comment by khanhduytran0** [comment]
It happens on both your port (aarch32) and longjunyu's port (aarch64)
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: Lenovo/A6010/A6010:5.0.2/LRX22G/A6010_S1118_160825_16G_SF:user/release-keys
Revision: '0'
ABI: 'arm'
pid: 23793, tid: 23878, name: Thread-675  >>> com.aof.mcinabox <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1b
    r0 00000001  r1 00000005  r2 00000000  r3 00000000
    r4 e3fa5158  r5 00000014  r6 00000005  r7 dfaba8e0
    r8 00000000  r9 00000000  sl 00000000  fp 00000000
    ip 00000000  sp dfaba890  lr e3fa042f  pc e3fa0382  cpsr 600b0030
 
backtrace:
    #00 pc 0000c382  /data/data/com.aof.mcinabox/app_runtime/j2re-image/lib/aarch32/libnet.so (initLocalIfs+181)
    #01 pc 0000c42b  /data/data/com.aof.mcinabox/app_runtime/j2re-image/lib/aarch32/libnet.so (initLocalIfs+350)
```

**Comment by khanhduytran0** [comment]
Also, how you got x11 libs linked even it's unavailable, so libawt_xawt.so and libsplashscreen.so still be built?

**Comment by CosineMath** [comment]
Thanks.
(I met this crash in early stage of developing Boat. But then it disappeared without fix ...... Need more research.)

**Comment by CosineMath** [comment]
libawt_xawt and some other libs related to x11 would not be loaded when running in headless mode. So I just use fake x11 libs to cheat compiler.

**Comment by khanhduytran0** [comment]
Why don't you just remove them as how you removed `-lpthread`, then allow undefined symbols.

**Comment by CosineMath** [comment]
x11 libs and includes are also for passing configure checks. (I don't know how to skip the checks then)

**Comment by khanhduytran0** [comment]
But only x11 includes are required for building OpenJDK headless only.

**Comment by CosineMath** [comment]
(Because I don't know much about building openjdk when I started this work.)

So in new port I don't build libawt_xawt.so, etc.

**Comment by khanhduytran0** [comment]
I think I found a reason for libnet.so crashing on Android 5.x. I have compared that your ported [`net_util_md.c`](https://github.com/CosineMath/openjdk-jdk8u-aarch32-android/blob/master/jdk/src/solaris/native/java/net/net_util_md.c) and jdk9 mobile and see that you haven't put this.
In your port: [here](https://github.com/CosineMath/openjdk-jdk8u-aarch32-android/blob/762442bc53861bfab86db8c69e4be8da14783622/jdk/src/solaris/native/java/net/net_util_md.c#L582) and [here](https://github.com/CosineMath/openjdk-jdk8u-aarch32-android/blob/762442bc53861bfab86db8c69e4be8da14783622/jdk/src/solaris/native/java/net/net_util_md.c#L1110).
```
        if ( (dest_plen < 0 || dest_plen > 128)  ||
             (src_plen != 0) ||
             (flags & (RTF_POLICY | RTF_FLOW)) ||
             ((flags & RTF_REJECT) && dest_plen == 0) ) {
            continue;
        }
```

In OpenJDK9 mobile:
```
        if ( (dest_plen < 0 || dest_plen > 128)  ||
             (src_plen != 0) ||
#ifndef __ANDROID__
             (flags & (RTF_POLICY | RTF_FLOW)) ||
#endif
             ((flags & RTF_REJECT) && dest_plen == 0) ) {
            continue;
        }
```

**Comment by khanhduytran0** [comment]
After that modify, libnet.so still crashes.

**Comment by khanhduytran0** [comment]
Another thing I found by addr2line:
```
Got it
$ addr2line -e libnet.debuginfo 0000000000011e2c
openjdk/jdk/src/solaris/native/java/net/net_util_md.c:720
```
![_20201104_125635](https://user-images.githubusercontent.com/40482367/98098633-2d273e00-1ec1-11eb-911d-1c3dc98d86f3.jpg)

On `initLocalIfs` method, it attempt reads `/proc/net/if_inet6` or skip, which is readable on Android 5.x and below (maybe Android inet6 output is different with Linux?) so it cause crashes.
```

```

**Comment by khanhduytran0** [comment]
After skip read `/proc/net/if_inet6`, JRE8 worked on Android 5. 

> I met this crash in early stage of developing Boat.

Guessing you ran java as root, so `if_inet6` become readable and did the crash.

**Comment by WesleyVanNeck** [comment]
fixed in the latest dev build

**Comment by EspressoDepresso9863** [comment]
When i go into my file manager the .minecraft folder is missing. What do i do?

**Comment by GameWatch21** [comment]
Make the hidden folder turn on and it will show you the folder

**Comment by NOM425378** [comment]
is minecraft 1.16.4 isnt support forge

**Comment by hellow161** [comment]
I can't put forge in 1.12.2 and here is the log plss helpp!!

[00:32:43] [Client thread/INFO]: Setting user: fyrc
[00:32:46] [Client thread/WARN]: Skipping bad option: lastServer:
[00:32:46] [Client thread/WARN]: Skipping bad option: streamPreferredServer:
[00:32:46] [Client thread/INFO]: LWJGL Version: 3.2.3 SNAPSHOT
[00:32:46] [Client thread/INFO]: [STDOUT]: LWJGLX: GL caps init
[00:32:47] [Client thread/INFO]: [STDOUT]: LWJGLX: ready-handle context created
[00:32:47] [Client thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: net/java/openjdk/cacio/ctc/ExternalMouseReader
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName0(Native Method)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName(Class.java:375)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.input.Mouse.<clinit>(Mouse.java:158)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.Display.create(Display.java:421)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.Display.create(Display.java:245)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at bib.at(SourceFile:622)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at bib.aq(SourceFile:458)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[00:32:47] [Client thread/INFO]: [STDERR]: Caused by: java.lang.ClassNotFoundException: net.java.openjdk.cacio.ctc.ExternalMouseReader
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[00:32:47] [Client thread/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[00:32:47] [Client thread/INFO]: [STDERR]: 	... 18 more
[00:32:47] [Client thread/INFO]: [STDOUT]: Grab: false
[00:32:47] [Client thread/INFO]: Reloading ResourceManager: Default
[00:32:47] [Sound Library Loader/INFO]: Starting up SoundSystem...
[00:32:48] [Thread-2/INFO]: Initializing LWJGL OpenAL
[00:32:48] [Thread-2/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[00:32:48] [Thread-2/INFO]: OpenAL initialized.
[00:32:48] [Sound Library Loader/INFO]: Sound engine started
[00:32:54] [Client thread/INFO]: Created: 1024x512 textures-atlas
[00:32:56] [Client thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Native library (linux-aarch64/libfliteWrapper.so) not found in resource path ([])
[00:32:59] [Client thread/INFO]: Stopping!
[00:32:59] [Client thread/INFO]: SoundSystem shutting down...
[00:32:59] [Client thread/ERROR]: Error in class 'SoundSystem'
[00:32:59] [Client thread/ERROR]: Problem during Library.cleanup()!
[00:32:59] [Client thread/INFO]: Ignoring errors... continuing clean-up.
[00:32:59] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by mchnjt** [comment]
v3.2 is....what the fuck...why would you play on that
Get the latest build on our [**actions tab**](https://github.com/PojavLauncherTeam/PojavLauncher/actions)
