### ISSUE TITLE
[BUG] <I can't sign in with my microsoft account!>

### ISSUE THREAD

**Issue by LUKA1029** [PojavLauncherTeam/PojavLauncher#3707]
### Describe the bug

**I can't sign in with my microsoft account. It was done before. Please correct. Otherwise, you can't play Minecraft!**

### The log file and images/videos

java.lang.RuntimeException: Unauthorized
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.throwResponseError(MicrosoftBackgroundLogin.java:324)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:215)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

### Steps To Reproduce

```markdown
when i signed in with my microsoft account
```

### Expected Behavior

can't login

### Platform

```markdown
- Device model: android
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: Latest Release || version 3.3.1.1_rel_20210206 ]
```

**Comment by GaucovyAero** [comment]
releases are old, use actions

**Comment by bitten2up** [comment]
> releases are old, use actions

it also happens on the latest actions build

**Comment by Dedieu123** [comment]
Good morning

**Comment by Omakoo** [comment]
Hellp

**Comment by GaucovyAero** [comment]
try logging into minecraft.net, this is not a pojav issue

**Comment by alexandre0021** [comment]
I can't play minecraft in pojavlauncher

**Comment by InfGhostx** [comment]
I can't play Minecraft on pojavlauncher
