### ISSUE TITLE
hi[BUG] <Short description>

### ISSUE THREAD

**Issue by JEXCRAFTER57177** [PojavLauncherTeam/PojavLauncher#3709]
### Describe the bug

PojavLauncher crash report
 - Time: Nov 20, 2022 1:49:09 PM
 - Device: CPH2083 CPH2083
 - Android version: 9
 - Crash stack trace:
 - Launcher version: dahlia-176-641eae051-v3_openjdk
android.view.InflateException: Binary XML file line #62: Binary XML file line #62: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: android.view.InflateException: Binary XML file line #62: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:658)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:827)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:900)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:861)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1740)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at net.kdt.pojavlaunch.LauncherActivity.onStart(LauncherActivity.java:187)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7399)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3215)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:185)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:170)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:147)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:73)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:7225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.Map net.kdt.pojavlaunch.value.launcherprofiles.MinecraftLauncherProfiles.profiles' on a null object reference
	at net.kdt.pojavlaunch.profiles.ProfileAdapter.<init>(ProfileAdapter.java:35)
	at com.kdt.mcgui.mcVersionSpinner.<init>(mcVersionSpinner.java:54)
	... 36 more

### The log file and images/videos

...

### Steps To Reproduce

```markdown
1.Start Pojav
2.Download Assets
3.In Downloading Crashed
4.Open Pojav Again Keep Crashing
```

### Expected Behavior

....

### Platform

```markdown
- Device model: Oppo A12
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version:Playstore
```

### Anything else?

pls fix

**Comment by GaucovyAero** [comment]
fixed in the latest play store build
