### ISSUE TITLE
Latest release optifine 1.7.10 crash

### ISSUE THREAD

**Issue by CriticalRange** [PojavLauncherTeam/PojavLauncher#372]
Game crashed after some time

As I said I was using the latest release 

Error log :  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1070)
	at net.kdt.pojavlaunch.MainActivity.access$3100(MainActivity.java:37)
	at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:709)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	... 5 more
Caused by: java.lang.IncompatibleClassChangeError: Structural change of sw is hazardous (/storage/emulated/0/games/minecraft/versions/1.7.10-OptiFine_HD_U_E3/oat/arm/1.7.10-OptiFine_HD_U_E3.odex at compile time, /storage/emulated/0/games/minecraft/libraries/optifine/OptiFine/1.7.10_HD_U_E3/oat/arm/OptiFine-1.7.10_HD_U_E3.odex at runtime): Static field count off: 0 vs 1
Lsw; (Compile time):
 Static fields:
 Instance fields:
  I a_
  I b
  Ltt; bm
  Ltr; bn
  Lvv; bo
  Lsv; bp
  Lvw; bq
  [Ladd; br
  Z bs
  Z bt
  Lsa; bu
  Z bv
  Lsa; bw
  Ldh; bx
  Luj; c
  Luj; d
  [F e
  F f
  I g
  Ltu; h
  Ltv; i
 Direct methods:
  <init>(Lahb;)V
  a(II)Ladb;
  b(FFF)F
  b(Ladd;)I
  bP()V
 Virtual methods:
  C()V
  a(Lsy;)Lsy;
  a(IF)V
  a(Ldh;)V
  a(Ljava/lang/String;)V
  a(Lsa;FF)V
  a(ZI)V
  a(ZZ)V
  a(Ljava/lang/Class;)Z
  a(Lyz;)Z
  aD()V
  ak()[Ladd;
  ax()I
  b(Ldh;)V
  b(Lsa;Z)V
  b(ZI)V
  bB()I
  bC()V
  bD()V
  bE()Z
  bF()V
  bG()Ljava/lang/String;
  bH()Z
  bI()Z
  bJ()Z
  bK()Z
  bL()V
  bM()Z
  bN()Z
  bO()Lsa;
  b_()Ljava/lang/String;
  be()Ladd;
  bi()Z
  bk()Z
  bn()V
  bq()V
  by()Z
  bz()F
  c()V
  c(ILadd;)V
  c(Lyz;)Z
  d(Lsv;)V
  e(Lyz;)I
  e()V
  f(FF)F
  g(Z)V
  h()V
  h(Z)V
  i(F)V
  j()Ltu;
  k()Ltv;
  l()Ltt;
  m()Lvv;
  n()Lvw;
  n(F)V
  o()Lsv;
  p()V
  q()I
  q(I)Ladd;
  r(I)Ladd;
  r()V
  s()V
  t()Ljava/lang/String;
  u()Ladb;
  v()Z
  w()V
  x()I
Lsw; (Runtime):
 Static fields:
  Ljava/lang/String; __OBFID
 Instance fields:
  I a_
  I b
  Ltt; bm
  Ltr; bn
  Lvv; bo
  Lsv; bp
  Lvw; bq
  [Ladd; br
  Z bs
  Z bt
  Lsa; bu
  Z bv
  Lsa; bw
  Ldh; bx
  Luj; c
  Luj; d
  [F e
  F f
  I g
  Ltu; h
  Ltv; i
  I randomMobsId
  Lahu; spawnBiome
  LBlockPos; spawnPosition
 Direct methods:
  <init>(Lahb;)V
  a(II)Ladb;
  b(FFF)F
  b(Ladd;)I
  bP()V
 Virtual methods:
  C()V
  a(Lsy;)Lsy;
  a(IF)V
  a(Ldh;)V
  a(Ljava/lang/String;)V
  a(Lsa;FF)V
  a(ZI)V
  a(ZZ)V
  a(Ljava/lang/Class;)Z
  a(Lyz;)Z
  aD()V
  ak()[Ladd;
  ax()I
  b(Ldh;)V
  b(Lsa;Z)V
  b(ZI)V
  bB()I
  bC()V
  bD()V
  bE()Z
  bF()V
  bG()Ljava/lang/String;
  bH()Z
  bI()Z
  bJ()Z
  bK()Z
  bL()V
  bM()Z
  bN()Z
  bO()Lsa;
  b_()Ljava/lang/String;
  be()Ladd;
  bi()Z
  bk()Z
  bn()V
  bq()V
  by()Z
  bz()F
  c()V
  c(ILadd;)V
  c(Lyz;)Z
  d(Lsv;)V
  e(Lyz;)I
  e()V
  f(FF)F
  g(Z)V
  h()V
  h(Z)V
  i(F)V
  j()Ltu;
  k()Ltv;
  l()Ltt;
  m()Lvv;
  n()Lvw;
  n(F)V
  o()Lsv;
  p()V
  q()I
  q(I)Ladd;
  r(I)Ladd;
  r()V
  s()V
  t()Ljava/lang/String;
  u()Ladb;
  v()Z
  w()V
  x()I
 (declaration of 'td' appears in /storage/emulated/0/games/minecraft/versions/1.7.10-OptiFine_HD_U_E3/1.7.10-OptiFine_HD_U_E3.jar:classes8.dex)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:282)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
	at dalvik.system.DexPathList.findClass(DexPathList.java:466)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:91)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:282)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
	at dalvik.system.DexPathList.findClass(DexPathList.java:466)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:91)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:282)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
	at dalvik.system.DexPathList.findClass(DexPathList.java:466)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:91)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:282)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:275)
	at dalvik.system.DexPathList$Element.findClass(DexPathList.java:677)
	at dalvik.system.DexPathList.findClass(DexPathList.java:466)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:91)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at adb.l(SourceFile:206)
	at kl.b(SourceFile:358)
	at bao.<init>(SourceFile:216)
	at net.minecraft.client.main.Main.main(SourceFile:129)
	... 7 more

**Comment by khanhduytran0** [comment]
Use v3 instead.
