### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'boolean net.kdt.pojavlaunch.value.launcherprofiles.MinecraftLauncherProfiles.profilesWereMigrated' on a null object reference 	at net.kdt.pojavlaunch.PojavProfile.launch(PojavProfile.java:107) 	at net.kdt.pojavlaunch.PojavLoginActivity$3.onClick(PojavLoginActivity.java:603) 	at android.view.View.performClick(View.java:6392) 	at android.view.View$PerformClick.run(View.java:25133) 	at android.os.Handler.handleCallback(Handler.java:790) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:198) 	at android.app.ActivityThread.main(ActivityThread.java:7055) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

### ISSUE THREAD

**Issue by Pheaktramc** [PojavLauncherTeam/PojavLauncher#3736]
### Describe the bug

java.lang.NullPointerException: Attempt to read from field 'boolean net.kdt.pojavlaunch.value.launcherprofiles.MinecraftLauncherProfiles.profilesWereMigrated' on a null object reference
	at net.kdt.pojavlaunch.PojavProfile.launch(PojavProfile.java:107)
	at net.kdt.pojavlaunch.PojavLoginActivity$3.onClick(PojavLoginActivity.java:603)
	at android.view.View.performClick(View.java:6392)
	at android.view.View$PerformClick.run(View.java:25133)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:7055)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)

### The log file and images/videos

Pls help me to use acc not work

### Steps To Reproduce

```markdown
Help
```

### Expected Behavior

Help

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Help

**Comment by Pheaktramc** [comment]
Help me pls

**Comment by Pheaktramc** [comment]
I don't know

**Comment by Pheaktramc** [comment]
Help me pls #3464

**Comment by Pheaktramc** [comment]
Help me pls

**Comment by Pheaktramc** [comment]
Help me pls

**Comment by Pheaktramc** [comment]
Pls
Help

**Comment by Pheaktramc** [comment]
Help

**Comment by Pheaktramc** [comment]
Help me pls brother

**Comment by Pheaktramc** [comment]
Kskkakwkwkkssj
