### ISSUE TITLE
Can't put optifine

### ISSUE THREAD

**Issue by TheBestXann** [PojavLauncherTeam/PojavLauncher#3750]
### Describe the bug

java.lang.SecurityException: com.android.providers.downloads has no access to content://media/external_primary/file/1000026188
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
	at android.os.Parcel.createException(Parcel.java:2422)
	at android.os.Parcel.readException(Parcel.java:2405)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at net.kdt.pojavlaunch.Tools.lambda$launchModInstaller$11(Tools.java:1022)
	at net.kdt.pojavlaunch.-$$Lambda$Tools$46FTZmdCg2wQlH_7QdcqTtuXPaI.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

.

### Steps To Reproduce

```markdown
When I click optifine jar my game crash
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Galaxy A12 
- CPU architecture: Aarch64 
- Android version: 12
- PojavLauncher version: dahlia-176-641eae051-v3_openjdk
```

**Comment by AverageFemale** [comment]
Just get forge and put it into your mods folder.

**Comment by GaucovyAero** [comment]
not a pojav issue
