### ISSUE TITLE
4[BUG]

### ISSUE THREAD

**Issue by WolfLegend6321** [PojavLauncherTeam/PojavLauncher#377]
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:1087)
	at net.kdt.pojavlaunch.MainActivity.access$3100(MainActivity.java:37)
	at net.kdt.pojavlaunch.MainActivity$14$1.run(MainActivity.java:709)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.BootstrapMethodError: Exception from call site #50 bootstrap method
	at k.<clinit>(SourceFile:42)
	at k.b(SourceFile:65)
	at net.minecraft.client.main.Main.main(SourceFile:54)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: .
	... 8 more

**Comment by khanhduytran0** [comment]
Minecraft 1.12+ will not run on v2.
