### ISSUE TITLE
[Crash] <Crash upon login>

### ISSUE THREAD

**Issue by TrollTransplantYT** [PojavLauncherTeam/PojavLauncher#3775]
### Describe the bug

Crash when logged in with Microsoft 

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288)
	at com.kdt.mcgui.mcAccountSpinner.onItemSelected(mcAccountSpinner.java:150)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:1387)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1376)
	at android.widget.AdapterView.access$300(AdapterView.java:61)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1334)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

### The log file and images/videos

![Screenshot_20221213-141330_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/106499403/207424532-c6e234bb-a977-4856-8059-e0f7e9ecac5b.jpg)

### Steps To Reproduce

```markdown
1. Open pojav
2. Log in with Microsoft
3. Crash
```

### Expected Behavior

Keeps working 

### Platform

```markdown
- Device model: Samsung S9 & S7 active 
- CPU architecture: Arm64 
- Android version: 10 & 8.1
- PojavLauncher version: Google play latest
```

### Anything else?

Started today on every device I own and my friends are having the same problem

**Comment by Eriksonthegreat** [comment]
I am also having the same issue:
Device model: Samsung S22 
- CPU architecture: Arm64 
- Android version: 13
- PojavLauncher version: Google play latest

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288)
	at com.kdt.mcgui.mcAccountSpinner.onItemSelected(mcAccountSpinner.java:150)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:1396)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1385)
	at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1343)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by TrollTransplantYT** [comment]
Solution is run this https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3685824442

**Comment by Eriksonthegreat** [comment]
> Solution is run this https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/3685824442

If you don't mind me asking but how do I run that? I am new here

**Comment by GaucovyAero** [comment]
update to the latest play store build
