### ISSUE TITLE
[BUG] I can't understand please help

### ISSUE THREAD

**Issue by Tpax-cekcoM** [PojavLauncherTeam/PojavLauncher#379]
device: xiaomi redmi note 4 16\3gb 8core arm cpu.
problem: when I'm trying to choice my java file in directory is writing "no such file or directory" ,but I downloaded the file 
after I'm trying to launch version but game crushes every time 
code: java.lang.RuntimeException: java.io.IOException: No such file or directory
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.setLastCrash(CrashFragment.java:82)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.onPostExecute(MCLauncherActivity.java:679)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.onPostExecute(MCLauncherActivity.java:485)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
	at java.io.File.createNewFile(File.java:948)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:762)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:771)
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.setLastCrash(CrashFragment.java:80)
	... 11 more
![Screenshot_2020-11-03-00-09-56-228_net kdt pojavlaunch](https://user-images.githubusercontent.com/73855140/97919585-12da4c80-1d69-11eb-9520-c30bae516e5b.jpg)
![Screenshot_2020-11-03-00-09-34-577_net kdt pojavlaunch](https://user-images.githubusercontent.com/73855140/97919628-2ab1d080-1d69-11eb-878c-f7b75607ec76.jpg)
![Screenshot_2020-11-03-00-10-41-954_net kdt pojavlaunch](https://user-images.githubusercontent.com/73855140/97919645-2f768480-1d69-11eb-85d3-5dda43bb0c7a.jpg)
p.s. I downloaded correct arm type of java file please help me

**Comment by khanhduytran0** [comment]
- Is storage permission granted correctly?
- Is runtime get corrupted?

**Comment by khanhduytran0** [comment]
@Tpax-cekcoM will you reply?

**Comment by WesleyVanNeck** [comment]
no reply so close
