### ISSUE TITLE
[BUG] Cannot Login : "Not found" on Chromebook ARM

### ISSUE THREAD

**Issue by Turbomortel** [PojavLauncherTeam/PojavLauncher#3801]
### Describe the bug

Hi team, merry christmas

I recently bought minecraft for my son but when I tried to login with his account in PojavLauncher I got a "not found" error with the following trace : 
java.lang.RuntimeException: Not Found
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.throwResponseError(MicrosoftBackgroundLogin.java:324)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:278)
at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:76)
at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

### The log file and images/videos

n/A

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. click on add account
3. click on "microsoft account"
4. fill in email address and password
5. got the error message
```

### Expected Behavior

I expect to be able to log in

### Platform

```markdown
- Device model: Aus Chromebook CM3200FM1
- CPU architecture: Mediatek MT8192 ARM
- Android version: Chrome OS, last version
- PojavLauncher version: last version from google play store
```

### Anything else?

I bought the game trough a new microsoft account (with a gmail address) created for my son
My son is under 18 so the account is managed trough microsoft family .
He did a request to purchase the game, then the game was bought by me within microsoft family
When I connect to his minecraft profile, everything looks ok : I can see that the java edition and bedrock are correctly attached to my son's account
I authorised the third apps connection in microsoft family

**Comment by GaucovyAero** [comment]
ah yes, this is either /minecraft/profile not found or AddChildToFamily error, which basically means that you either have to just log into minecraft.net, or link your child to a parent account, or maybe make your child an adult linked to a parent, idk? i mean these issues are basically microsoft's fault so dunno

**Comment by GaucovyAero** [comment]
stale
