### ISSUE TITLE
Game crash after login

### ISSUE THREAD

**Issue by CreeperboyMCVN** [PojavLauncherTeam/PojavLauncher#3807]
### Describe the bug

The game crash after i login with Microsoft account 

### The log file and images/videos

![Screenshot_2022-12-30-08-28-53-006_net kdt pojavlaunch](https://user-images.githubusercontent.com/78776810/210026017-4cd580dd-72e8-456d-a90d-b217671feacb.jpg)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Login with Microsoft account
3. Game crash
```

### Expected Behavior

I want the game start normally 

### Platform

```markdown
- Device model: Mi 11T 5G
- CPU architecture: 
- Android version: 12
- PojavLauncher version: dahlia-176-641eae051-v3_openjdk
```

**Comment by CreeperboyMCVN** [comment]
latestcrash.txt: https://pastebin.com/w0fFNjnP

**Comment by GaucovyAero** [comment]
try reinstalling

**Comment by CreeperboyMCVN** [comment]
Tried but doesn't work

The launcher still run properly when login using local account but I want to use my Microsoft account

**Comment by GaucovyAero** [comment]
> Tried but doesn't work
> 
> The launcher still run properly when login using local account but I want to use my Microsoft account

hmm, download here from github actions where it says "mouse grab something", download app-debug, extract it and install

**Comment by SYZYGYGAMER** [comment]
It's happening to me too

**Comment by EVSkyFall** [comment]
Same problem here
works fine with local account
but when you log in with microsoft account, application keeps crash and never opens again until reinstall it.



java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:288)
	at com.kdt.mcgui.mcAccountSpinner.onItemSelected(mcAccountSpinner.java:150)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
	at android.widget.AdapterView.access$300(AdapterView.java:55)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:8001)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)

**Comment by GaucovyAero** [comment]
Issue fixed in the latest play store build.
