### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by SomeonesSon** [PojavLauncherTeam/PojavLauncher#3821]
### Describe the bug

Hello,
trying to login to a microsoft account, i out email + password, i press sign in and it says ERROR, copy, show more or ok
ERROR code:
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.throwResponseError(MicrosoftBackgroundLogin.java:324)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:278)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:76)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### The log file and images/videos

![68d944de-9824-4638-91d4-54b0be1b5e24](https://user-images.githubusercontent.com/121937132/210530467-bb301f96-ddb7-457d-ad70-89e0686314da.jpg)

![0b49825c-a2fd-4c23-a3ca-e07dcae332d8](https://user-images.githubusercontent.com/121937132/210530537-a113a7c7-b28b-4973-8714-54c99b2d9b4c.jpg)

### Steps To Reproduce

```markdown
help
```

### Expected Behavior

i expect the account to launch.

### Platform

```markdown
- Device model: samsung note9
- CPU architecture: 
- Android version: 11-12
- PojavLauncher version: latest from playstore
```

### Anything else?

Local account doesn't work if i press it nothing will happen

**Comment by GaucovyAero** [comment]
game pass?

**Comment by CriticalRange** [comment]
I had the same issue and it somehow got fixed after I logged in on minecraft.net lol

**Comment by fifa255** [comment]
have same issue and error message with login on a firehd 10 tablet.

**Comment by GaucovyAero** [comment]
We can't do anything about this. Try logging into minecraft.net, but this isn't a pojav issue.

**Comment by hk436** [comment]
help không thể đăng nhập

**Comment by GaucovyAero** [comment]
> help không thể đăng nhập

not enough info

**Comment by thecrepperepic12** [comment]
WTF my pojav  not funcional men xddd(my english is a trash brooo)

**Comment by thecrepperepic12** [comment]
WTF i buy my mc account i not generator premium account im no pirate its igual error my english is a fukynnnn trash :v
