### ISSUE TITLE
[BUG] <File not found Exception> 2 identical tablets, 2 accounts -> 1 works both accounts, other doesn't work for both either accounts

### ISSUE THREAD

**Issue by gabrielsallum** [PojavLauncherTeam/PojavLauncher#3822]
### Describe the bug

After the brand-new installation of this application on my account worked well, I wanted to install it on my other (identical) tablet.
tried to clean the cache, delete files, and reinstall but nothing gives, even used different accounts on the tablet to see if it was something related. 

### The log file and images/videos

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/Unknown/Unknown.json (No such file or directory)
 at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:767)
 at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:671)
 at net.kdt.pojavlaunch.MainActivity.initLayout(MainActivity.java:150)
 at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:85)
 at android.app.Activity.performCreate(Activity.java:7245)
 at android.app.Activity.performCreate(Activity.java:7236)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1287)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3011)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3166)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6975)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/PojavLauncher/.minecraft/versions/Unknown/Unknown.json (No such file or directory)
 at java.io.FileInputStream.open0(Native Method)
 at java.io.FileInputStream.open(FileInputStream.java:231)
 at java.io.FileInputStream.<init>(FileInputStream.java:165)
 at java.io.FileInputStream.<init>(FileInputStream.java:112)
 at net.kdt.pojavlaunch.Tools.read(Tools.java:836)
 at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:676)
 ... 18 more

### Steps To Reproduce

```markdown
-Install or Re-install the app.
- wait for it to init (the first start takes a long time and usually asks to force-quit a couple of times)
- login to Ms. Account (Login Successfully modal briefly appears). 
- when, finally, trying to launch the game, this error message appears. 
(from recollection here, some of the UI wording may be a bit off)
```

### Expected Behavior

launch the game and the red screen to appear as in my other tablet. 

### Platform

```markdown
- Device model: Lenovo 10e Chromebook (installed via android play store)
- CPU architecture: Arm 64
- Android version: 
- ChromeOS version: 
- PojavLauncher version:
```

### Anything else?

it seems weird that the "unknown" path seems generated and somewhere somehow I see the files where It should live which is under ..../versions/<ver>/<ver>.json and not unknown..... 
![image](https://user-images.githubusercontent.com/6403964/210627309-4c63b843-4ae5-4426-9a53-33bb96ffbf83.png)

**Comment by gabrielsallum** [comment]
Sorry IDK how it came out like that above, here is what  I have below:
- Device model: Lenovo 10e Chromebook (installed via android play store)
- CPU architecture: Arm 
- Android version: 9
- ChromeOS version: 108.0.5359.111
- PojavLauncher version: latest from today.

**Comment by Bel69420** [comment]
Play store version is broke on some devices
(You have to install debug app from github)
In chromebook, you have to activate developer mode (may erase all of your datas)(Recommended to backup all data)

**Comment by Bel69420** [comment]
Its seem like something went wrong with your version file

**Comment by Bel69420** [comment]
Wait for Aero

**Comment by gabrielsallum** [comment]
Whats an Aero ?

Thanks,
Gabriel Sallum

**Comment by Bel69420** [comment]
He's a moderator of pojav server, I think he knows about this problem or wait for another people who could solve this

**Comment by GaucovyAero** [comment]
be sure to select a specific minecraft version

**Comment by gabrielsallum** [comment]
the Minecraft version was left as the default it said: "(default) - unknown)" so I created a new profile and targeted 1.19.3-rc3 (from the dropdown list) didn't do anything tho.....

**Comment by gabrielsallum** [comment]
All right I guess that was the issue. I was able to work from now on. thanks

Thanks,
Gabriel Sallum

**Comment by VenomousSteam81** [comment]
~~I've had similar issues on the same chromebook. Let me guess, Lenovo 100e Second Gen MTK? Only my issue was with fabric, and i had to delete the issue-causing folder~~ ignore my rambling im kind of tired

**Comment by Cube5x59999** [comment]
having a knowledge of java (basics), i think java runtime corrupted

**Comment by GaucovyAero** [comment]
Fixed.
