### ISSUE TITLE
[BUG] Can't log in 

### ISSUE THREAD

**Issue by maurix649** [PojavLauncherTeam/PojavLauncher#3824]
### Describe the bug

When trying to log in with my Microsoft account it starts to load but then interrupts with a message that says unauthorized with the following code:
java.lang.RuntimeException: Unauthorized
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.throwResponseError(MicrosoftBackgroundLogin.java:324)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:215)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

### The log file and images/videos

![Screenshot_20230104_235236_net kdt pojavlaunch](https://user-images.githubusercontent.com/122000593/210711909-0c619c89-a841-4571-9f25-2f00c57bef84.jpg)

### Steps To Reproduce

```markdown
help
```

### Expected Behavior

i expect the account to launch

### Platform

```markdown
- Device model: Huawei Nova 5t
- CPU architecture: 
- Android version: 11-12
- PojavLauncher version: lastest from pl
```

**Comment by TarikBR** [comment]
do you own the original PC version of minecrat?

remember playstore original minecraft doesn't work to login

**Comment by maurix649** [comment]
yes, i have minecraft java for pc in that microsoft account

**Comment by GaucovyAero** [comment]
> yes, i have minecraft java for pc in that microsoft account

log into minecraft.net first, we can't do anything about this issue.
