### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by jackyleo1234** [PojavLauncherTeam/PojavLauncher#3850]
### Describe the bug

what do i do when i want 66  mods and dont have enough storage because of the app because then it says application exited with code 1 i cant remove anymore storage
 

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-209-0a485c9b0-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.7.10-Forge10.13.4.1614-1.7.10
--------- beginning of main

I/jrelog  (15060): Going to free args
I/jrelog  (15060): Free done

I/jrelog  (15138): dlopen libxhook.so success
I/jrelog  (15169): dlopen libxhook.so success

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1368
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-EtQcMat5Vg7ond9S_2AoLw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-EtQcMat5Vg7ond9S_2AoLw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=768
I/jrelog  (15224): dlopen libxhook.so success

I/LIBGL   (15224): Initialising gl4es
I/LIBGL   (15224): v1.1.4 built on Dec  6 2022 11:42:26
I/LIBGL   (15224): Using GLES 2.0 backend

I/LIBGL   (15224): loaded: libGLESv2.so
I/LIBGL   (15224): loaded: libEGL.so

I/LIBGL   (15224): Using GLES 2.0 backend

I/LIBGL   (15224): Hardware Full NPOT detected and used
I/LIBGL   (15224): Extension GL_EXT_blend_minmax  detected and used
I/LIBGL   (15224): FBO are in core, and so used
I/LIBGL   (15224): PointSprite are in core, and so used
I/LIBGL   (15224): CubeMap are in core, and so used
I/LIBGL   (15224): BlendColor is in core, and so used
I/LIBGL   (15224): Blend Substract is in core, and so used
I/LIBGL   (15224): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (15224): Texture Mirrored Repeat is in core, and so used

I/LIBGL   (15224): Extension GL_OES_mapbuffer  detected
I/LIBGL   (15224): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (15224): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (15224): Extension GL_OES_depth24  detected and used
I/LIBGL   (15224): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (15224): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (15224): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (15224): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (15224): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (15224): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   (15224): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (15224): high precision float in fragment shader available and used
I/LIBGL   (15224): Max vertex attrib: 16
I/LIBGL   (15224): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (15224): Max texture size: 8192
I/LIBGL   (15
224): Max Varying Vector: 31
I/LIBGL   (15224): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6

I/LIBGL   (15224): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   (15224): Max Anisotropic filtering: 16
I/LIBGL   (15224): Hardware vendor is ARM

I/LIBGL   (15224): GLSL 300 es supported
I/LIBGL   (15224): GLSL 310 es supported and used
I/LIBGL   (15224): GLSL 320 es supported
I/LIBGL   (15224): Max Color Attachments: 4 / Draw buffers: 4
I/LIBGL   (15224): sRGB surface supported
I/LIBGL   (15224): EGLImage to Texture2D supported
I/LIBGL   (15224): EGLImage to RenderBuffer supported

I/LIBGL   (15224): ignore MipMap
I/LIBGL   (15224): Targeting OpenGL 2.1
I/LIBGL   (15224): No hack in shader converter to define overloaded function with int
I/LIBGL   (15224): NPOT texture handled in hardware
I/LIBGL   (15224): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (15224): try to use VBO
I/LIBGL   (15224): glXMakeCurrent FBO workaround enabled

I/LIBGL   (15224): FBO workaround for using binded texture enabled
I/LIBGL   (15224): glX Will try to recycle EGL Surface
I/LIBGL   (15224): Current folder is:/
I/jrelog  (15224): dlopen libgl4es_114.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (15224): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so failed: dlopen failed: library "libtinyiconv.so" not found

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success

I/jrelog  (15224): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  (15224): dlopen /data/app/net.kdt.pojavlaunch-EtQcMat5Vg7ond9S_2AoLw==/lib/arm64/libopenal.so success

I/jrelog  (15224): Done processing args

I/jrelog  (15224): Found JLI lib
I/jrelog  (15224): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
2023-01-14 21:27:07,957 ERROR appender Console has no parameter that matches element Policies

[21:27:08] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:27:08] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[21:27:08] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[21:27:08] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[21:27:08] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0-internal, running on Linux:aarch64:Android-9, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal
2023-01-14 21:27:08,555 ERROR appender Console has no parameter that matches element Policies

[21:27:08] [main/WARN]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
Downloading file http://files.minecraftforge.net/maven/codechicken/CodeChickenLib/1.7.10-1.1.3.138//CodeChickenLib-1.7.10-1.1.3.138-universal.jar
[21:27:09] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[21:27:09] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:scanDepInfo:510]: Failed to load dependencies.info from CodeChickenLib-1.7.10-1.1.3.138-universal.jar as JSON
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.util.zip.ZipException: error in opening zip file
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.ZipFile.open(Native Method)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.ZipFile.<init>(Unknown Source)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.ZipFile.<init>(Unknown Source)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.util.zip.ZipFile.<init>(Unknown Source)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.scanDepInfo(DepLoader.java:503)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.download(DepLoader.java:345)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:480)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.loadDeps(DepLoader.java:466)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader$DepLoadInst.load(DepLoader.java:449)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.DepLoader.load(DepLoader.java:584)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.core.launch.CodeChickenCorePlugin.<init>(CodeChickenCorePlugin.java:47)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:27:09] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Downloading file 
http://bspk.rs/MC/bspkrsCore/[1.7.10]bspkrsCore-universal-6.15.jar

[21:27:10] [main/INFO]: [codechicken.core.launch.DepLoader$DepLoadInst:download:343]: Download complete
[21:27:11] [main/WARN]: The coremod mods.battlegear2.coremod.BattlegearLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:11] [main/WARN]: The coremod tw.pearki.mcmod.muya.asm.MuyaASMCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:11] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more
[21:27:11] [main/ERROR]: An error occurred trying to configure the minecraft home at /storage/emulated/0/games/PojavLauncher/.minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18) ~[NotEnoughItems-1.7.10-1.0.5.120-universal%20(1).jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0-internal]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassL
oader.loadClass(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0-internal]
	... 15 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0-internal]
	... 15 more
Exception in thread "main" 
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ASMInit
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.nei.asm.NEICorePlugin.<init>(NEICorePlugin.java:18)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:501)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ASMInit
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[21:27:11] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more
Java Exit code: 1
I/jrelog  (15224): Going to free args
I/jrelog  (15224): Free done

### Steps To Reproduce

```markdown
i didnt know what to do i was so confused
```

### Expected Behavior

i expected to work because i have 45gb on my chromebook

### Platform

```markdown
- Device model: 109.0.5414.94 (Official Build) (32-bit) 
- CPU architecture: UNKNOWN
- Android version: UNKNOWN
- PojavLauncher version: dahlia-209-0a485c9b0-v3_openjdk
```

**Comment by khanhduytran0** [comment]
See https://github.com/Chicken-Bones/CodeChickenCore/issues/107#issuecomment-826053215
