### ISSUE TITLE
I cant open my Microsoft account 

### ISSUE THREAD

**Issue by random701** [PojavLauncherTeam/PojavLauncher#3858]
### Describe the bug

java.lang.RuntimeException: Unauthorized
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.throwResponseError(MicrosoftBackgroundLogin.java:324)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:215)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

![Screenshot_2023-01-18-23-03-56-199_net kdt pojavlaunch](https://user-images.githubusercontent.com/122995692/213206434-50692467-7b75-4f7a-9b30-2aac8c96b6dc.jpg)

### Steps To Reproduce

```markdown
1 help me
```

### Expected Behavior

I expected the game to launch 

### Platform

```markdown
- Device model:redmi note 11
- CPU architecture: Kryo 265 Silver
- Android version:12
- PojavLauncher version:1.19.3
```

### Anything else?

How to fix this

**Comment by mchnjt** [comment]
Try relogging in?

**Comment by Thollp** [comment]
You must buy minecraft and then loggin with microsoft account

**Comment by GaucovyAero** [comment]
log into minecraft.net and then try logging into pojav

**Comment by GaucovyAero** [comment]
closing this as it is an issue on your side only
