### ISSUE TITLE
[BUG] login crash

### ISSUE THREAD

**Issue by hanyixuanten** [PojavLauncherTeam/PojavLauncher#3867]
### Describe the bug

when i login,pojav crash

### The log file and images/videos

java.lang.RuntimeException: 

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "error" : "NOT_FOUND",
  "errorMessage" : "Not Found"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:312)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:208)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

### Steps To Reproduce

```markdown
1.start pojav
2.login my microsoft account
3.crash
ps:I cant found the dir "games" in /storage/emulated/0
```

### Expected Behavior

i want to login

### Platform

```markdown
- Device model: redmi 10 x
- CPU architecture: helio g85
- Android version: 12
- PojavLauncher version: 3.3.1.1
```

**Comment by mchnjt** [comment]
Have you bought Minecraft for your account?
Also, outdated launcher version.

**Comment by GaucovyAero** [comment]
Outdated launcher version. Install the launcher from Play Store.
