### ISSUE TITLE
[BUG] 1.165 Forge Error

### ISSUE THREAD

**Issue by BananaManInfiniti** [PojavLauncherTeam/PojavLauncher#3871]
### Describe the bug

Getting and error lauching pojavlauncher forge 1.16.5 moded (1 mod). (Log below).

 Tried the Gplay version and the lasted artifact version. Also used all jre versions available (x64, x86.64, amd64, aarch32, etc) in their latest artifact version. Same issue

### The log file and images/videos

`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 23-01-2023 23:11
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.34.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0-internal] {}
-- MOD pixelmon --
Details:
	Mod File: Pixelmon-1.16.5-9.1.2-universal.jar
	Failure message: Pixelmon Mod (pixelmon) encountered an error during the sided_setup event phase
		java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch.debug/cache/drpc8481859791323613278/libdiscord-rpc.so: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/cache/drpc8481859791323613278/libdiscord-rpc.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
	Mod Version: 9.1.2
	Mod Issue URL: https://pixelmonmod.com/tracker.php?p=2
	Exception message: java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch.debug/cache/drpc8481859791323613278/libdiscord-rpc.so: dlopen failed: "/data/data/net.kdt.pojavlaunch.debug/cache/drpc8481859791323613278/libdiscord-rpc.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183) (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
Stacktrace:
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0-internal] {}
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0-internal] {}
	at java.lang.System.load(Unknown Source) ~[?:1.8.0-internal] {}
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:156) ~[pixelmon:1.16.5-9.1.2] {re:classloading}
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:23) ~[pixelmon:1.16.5-9.1.2] {re:classloading}
	at com.pixelmonmod.pixelmon.client.richpresence.PixelmonRichPresence.init(PixelmonRichPresence.java:56) ~[pixelmon:1.16.5-9.1.2] {re:classloading}
	at com.pixelmonmod.pixelmon.client.richpresence.PixelmonRichPresence.<init>(PixelmonRichPresence.java:42) ~[pixelmon:1.16.5-9.1.2] {re:classloading}
	at com.pixelmonmod.pixelmon.client.ClientProxy.init(ClientProxy.java:211) ~[pixelmon:1.16.5-9.1.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_48_ClientProxy_init_FMLClientSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0-internal] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0-internal] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-13
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1119078312 bytes (1067 MB) / 2145386496 bytes (2046 MB) up to 2145386496 bytes (2046 MB)
	CPUs: 6
	JVM Flags: 4 total; -Xms2210M -Xmx2210M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |ENQUEUE_IM|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Pixelmon-1.16.5-9.1.2-universal.jar               |Pixelmon Mod                  |pixelmon                      |9.1.2               |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 7c6d9fd4-e37e-4222-bdea-d0675df27913`

### Steps To Reproduce

```markdown
1 - Open PojavLauncher
2 - Load Profile (1.165 Forge 36.2.34 with one mod: Pixelmon Reforged lastest version
3 - Loads until error occurs (see log posted)
```

### Expected Behavior

The game loads to the main menu and allow to play.

### Platform

```markdown
- Device model: Galaxy A71
- CPU architecture: AARCH64
- Android version: 13
- PojavLauncher version: Lastest Artifact Version
```

### Anything else?

Cloud be because that the achitecture is not compatible with pojav currently? 
Or is my device unable to run this version?

**Comment by GaucovyAero** [comment]
DiscordRPC is an issue with Pixelmon, you can fix this by going into afaik `.minecraft/config/pixelmon/config.yml` and setting discord rich presence to `false`

**Comment by GaucovyAero** [comment]
Known issue. Closing.
