### ISSUE TITLE
[BUG] Fabric refuses to load

### ISSUE THREAD

**Issue by ender1324** [PojavLauncherTeam/PojavLauncher#3877]
### Describe the bug

When launching the fabric profile it gives this error:
``java.lang.RuntimeException: java.lang.RuntimeException: Can't find the source version for fabric-loader-0.14.13-1.19.2 (req version=1.19.2)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:762)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:671)
	at net.kdt.pojavlaunch.MainActivity.initLayout(MainActivity.java:151)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:85)
	at android.app.Activity.performCreate(Activity.java:8057)
	at android.app.Activity.performCreate(Activity.java:8037)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1345)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: Can't find the source version for fabric-loader-0.14.13-1.19.2 (req version=1.19.2)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:690)
	... 19 more
``

And the file is infact in android/data/net.kdt.pojavlaunch/.minecraft/versions/fabric-loader-0.14.13-1.19.2/fabric-loader-0.14.13-1.19.2.jar

The log file is completely empty as the game doesn't even seem to start launching, also there are no mods

### The log file and images/videos

![Screenshot_20230126-081145_PojavLauncher (Minecraft_ Java Edition for Android)](https://user-images.githubusercontent.com/46723422/214769664-e1841a76-eec5-404a-8122-075b902547fc.png)

### Steps To Reproduce

```markdown
1. Start Pojav
2. Install latest fabric universal installer
3. Install it the 1.19.2 version with all default options
4. Launch the profile it provides
```

### Expected Behavior

Game launches normally 

### Platform

```markdown
- Device model: Mi 8
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest from GPlay
```

**Comment by artdeell** [comment]
You haven't installed the vanilla 1.19.2

**Comment by ender1324** [comment]
> You haven't installed the vanilla 1.19.2

You are indeed right lol, thanks for the help
