### ISSUE TITLE
[BUG] I can download minecraft with local accounts 

### ISSUE THREAD

**Issue by MangyCat** [PojavLauncherTeam/PojavLauncher#3885]
### Describe the bug

I have no account registered on my device, I have the Google play version of pojavlauncher, however I also have minecraft bedrock edition from Google play as well so what I'm suspecting is that pojavlauncher checks if I have minecraft bedrock installed and allows me to download. Is that normal and intended? 

### The log file and images/videos

```
-------- beginning with launcher debug
Info: Launcher version: dahlia-218-6888cb7d8-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 23w04a
--------- beginning of system

--------- beginning of main

I/jrelog  (15012): dlopen libxhook.so success

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1674
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-XoIkvxfFqYjD1b9QCTYzsg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-XoIkvxfFqYjD1b9QCTYzsg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=810
I/LIBGL   (15012): Initialising gl4es
I/LIBGL   (15012): v1.1.4 built on Dec  6 2022 11:42:26
I/LIBGL   (15012): Using GLES 2.0 backend

I/LIBGL   (15012): loaded: libGLESv2.so

I/LIBGL   (15012): loaded: libEGL.so

I/LIBGL   (15012): Using GLES 2.0 backend

I/LIBGL   (15012): Hardware Full NPOT detected and used

I/LIBGL   (15012): Extension GL_EXT_blend_minmax  detected and used

I/LIBGL   (15012): FBO are in core, and so used

I/LIBGL   (15012): PointSprite are in core, and so used
I/LIBGL   (15012): CubeMap are in core, and so used
I/LIBGL   (15012): BlendColor is in core, and so used
I/LIBGL   (15012): Blend Substract is in core, and so used
I/LIBGL   (15012): Blend Function and Equation Separation is in core, and so used
I/LIBGL   (15012): Texture Mirrored Repeat is in core, and so used
I/LIBGL   (15012): Extension GL_OES_mapbuffer  detected
I/LIBGL   (15012): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   (15012): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   (15012): Extension GL_OES_depth24  detected and used
I/LIBGL   (15012): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   (15012): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   (15012): Extension GL_OES_depth_texture  detected and used
I/LIBGL   (15012): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   (15012): Extension GL_EXT_texture_rg  detected and used
I/LIBGL   (15012): Extension GL_E
XT_color_buffer_float  detected and used
I/LIBGL   (15012): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (15012): high precision float in fragment shader available and used
I/LIBGL   (15012): Max vertex attrib: 16
I/LIBGL   (15012): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (15012): Max texture size: 8192
I/LIBGL   (15012): Max Varying Vector: 15
I/LIBGL   (15012): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (15012): Hardware vendor is ARM
I/LIBGL   (15012): GLSL 300 es supported
I/LIBGL   (15012): GLSL 310 es supported and used
I/LIBGL   (15012): GLSL 320 es supported
I/LIBGL   (15012): Max Color Attachments: 4 / Draw buffers: 4
I/LIBGL   (15012): sRGB surface supported
I/LIBGL   (15012): EGLImage to Texture2D supported
I/LIBGL   (15012): EGLImage to RenderBuffer supported
I/LIBGL   (15012): ignore MipMap
I/LIBGL   (15012): Targeting OpenGL 2.1
I/LIBGL   (15012): No hack in shader converter to define overloaded function with in
t
I/LIBGL   (15012): NPOT texture handled in hardware
I/LIBGL   (15012): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (15012): try to use VBO
I/LIBGL   (15012): glXMakeCurrent FBO workaround enabled
I/LIBGL   (15012): FBO workaround for using binded texture enabled
I/LIBGL   (15012): glX Will try to recycle EGL Surface
I/LIBGL   (15012): Current folder is:/
I/jrelog  (15012): dlopen libgl4es_114.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (15012): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (15012): dlopen /data/app/net.kdt.pojavlaunch-XoIkvxfFqYjD1b9QCTYzsg==/lib/arm64/libopenal.so success

I/jrelog  (15012): Done processing args

I/jrelog  (15012): Found JLI lib

I/jrelog  (15012): Calling JLI_Launch

read: unexpected EOF!

--------- beginning of main

--------- beginning of system

I/LIBGL   (15012): Initialising gl4es

I/LIBGL   (15012): v1.1.4 built on Dec  6 2022 11:42:26

I/LIBGL   (15012): Using GLES 2.0 backend

I/LIBGL   (15012): loaded: libGLESv2.so

I/LIBGL   (15012): loaded: libEGL.so

I/LIBGL   (15012): Using GLES 2.0 backend

I/LIBGL   (15012): Hardware Full NPOT detected and used

I/LIBGL   (15012): Extension GL_EXT_blend_minmax  detected and used

I/LIBGL   (15012): FBO are in core, and so used

I/LIBGL   (15012): PointSprite are in core, and so used

I/LIBGL   (15012): CubeMap are in core, and so used

I/LIBGL   (15012): BlendColor is in core, and so used

I/LIBGL   (15012): Blend Substract is in core, and so used

I/LIBGL   (15012): Blend Function and Equation Separation is in core, and so used

I/LIBGL   (15012): Texture Mirrored Repeat is in core, and so used

I/LIBGL   (15012): Extension GL_OES_mapbuffer  detected

I/LIBGL   (15012): Extension GL_OES_element_index_uint  detected and used

I/LIBGL   (15012): Extension GL_OES_packed_depth_stencil  detected and used

I/LIBGL   (15012): Extension GL_OES_depth24  detected and used

I/LIBGL   (15012): Extension GL_OES_rgb8_rgba8  detected and used

I/LIBGL   (15012): Extension GL_EXT_texture_format_BGRA8888  detected and used

I/LIBGL   (15012): Extension GL_OES_depth_texture  detected and used

I/LIBGL   (15012): Extension GL_OES_texture_stencil8  detected and used

I/LIBGL   (15012): Extension GL_EXT_texture_rg  detected and used

I/LIBGL   (15012): Extension GL_EXT_color_buffer_float  detected and used

I/LIBGL   (15012): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   (15012): high precision float in fragment shader available and used
I/LIBGL   (15012): Max vertex attrib: 16
I/LIBGL   (15012): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   (15012): Max texture size: 8192
I/LIBGL   (15012): Max Varying Vector: 15
I/LIBGL   (15012): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   (15012): Hardware vendor is ARM
I/LIBGL   (15012): GLSL 300 es supported
I/LIBGL   (15012): GLSL 310 es supported and used
I/LIBGL   (15012): GLSL 320 es supported
I/LIBGL   (15012): Max Color Attachments: 4 / Draw buffers: 4
I/LIBGL   (15012): sRGB surface supported
I/LIBGL   (15012): EGLImage to Texture2D supported
I/LIBGL   (15012): EGLImage to RenderBuffer supported
I/LIBGL   (15012): ignore MipMap
I/LIBGL   (15012): Targeting OpenGL 2.1
I/LIBGL   (15012): No hack in shader converter to define overloaded function with int
I/LIBGL   (15012): NPOT texture handled
 in hardware
I/LIBGL   (15012): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   (15012): try to use VBO
I/LIBGL   (15012): glXMakeCurrent FBO workaround enabled
I/LIBGL   (15012): FBO workaround for using binded texture enabled
I/LIBGL   (15012): glX Will try to recycle EGL Surface
I/LIBGL   (15012): Current folder is:/
I/jrelog  (15012): dlopen libgl4es_114.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (15012): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (15012): dlopen /data/
user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so su
ccess
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavl
aunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (15012): dlopen /data
/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  (15012): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  (15012): dlopen /data/app/net.kdt.pojavlaunch-XoIkvxfFqYjD1b9QCTYzsg==/lib/arm64/libopenal.so success
I/jrelog  (15012): Done processing args
I/jrelog  (15012): Found JLI lib
I/jrelog  (15012): Calli
ng JLI_Launch

2023-01-28 09:32:21,970 main ERROR appender Console has no parameter that matches element Policies
[09:32:34] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at z.c(SourceFile:75) ~[23w04a.jar:?]
	at z.a(SourceFile:82) ~[23w04a.jar:?]
	at z.a(SourceFile:75) ~[23w04a.jar:?]
	at z.c(SourceFile:52) ~[23w04a.jar:?]
	at z.a(SourceFile:82) ~[23w04a.jar:?]
	at z.<init>(SourceFile:52) ~[23w04a.jar:?]
	at n.<init>(SourceFile:34) ~[23w04a.jar:?]
	at n.h(SourceFile:274) ~[23w04a.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:159) ~[23w04a.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[23w04a.jar:?]
[09:32:34] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at z.a(SourceFile:77) ~[23w04a.jar:?]
	at z.a(SourceFile:82) ~[23w04a.jar:?]
	at z.a(SourceFile:77) ~[23w04a.jar:?]
	at z.c(SourceFile:52) ~[23w04a.jar:?]
	at z.a(SourceFile:82) ~[23w04a.jar:?]
	at z.<init>(SourceFile:52) ~[23w04a.jar:?]
	at n.<init>(SourceFile:34) ~[23w04a.jar:?]
	at n.h(SourceFile:274) ~[23w04a.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:159) ~[23w04a.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[23w04a.jar:?]
```

### Steps To Reproduce

```markdown
1. Install minecraft bedrock edition from Google play
2. Install pojavlauncher from google
3. Open pojavlauncher
4. Make a local or offline account and stay logged in
5. Make a new profile
6. And..... How is it downloading the client if Im not logged in to a minecraft account.
```

### Expected Behavior

I expected pojavlauncher to give a pop-up saying I need to login into a premium account

### Platform

```markdown
- Device model: Huawei P30 lite MAR-LX1A
- CPU architecture: arm 64 bit 8th version? 
- Android version: Android 10 EMUI 10.0
- PojavLauncher version: Dahlia 218 (from app settings) 6888cb7d8-v3_openjdk
```

### Anything else?

How are there LITERAL patches of popular launchers that are cracked on github, and Microsoft owns github. Why would they specifically target this launcher why not all those cracked launchers just my opinion

**Comment by GaucovyAero** [comment]
im pretty sure they also target other launchers, closing

**Comment by MangyCat** [comment]
> im pretty sure they also target other launchers, closing

What about the bug????
