### ISSUE TITLE
App crashes when trying to install fabric

### ISSUE THREAD

**Issue by YLlywelyn** [PojavLauncherTeam/PojavLauncher#3891]
### Describe the bug

when trying to run the fabric installer this error is given and the app crashes:

```
java.lang.SecurityException: com.samsung.android.providers.media has no access to content://media/external_primary/file/1000018389
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
	at android.os.Parcel.createException(Parcel.java:2422)
	at android.os.Parcel.readException(Parcel.java:2405)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at net.kdt.pojavlaunch.Tools.lambda$launchModInstaller$11(Tools.java:1031)
	at net.kdt.pojavlaunch.-$$Lambda$Tools$46FTZmdCg2wQlH_7QdcqTtuXPaI.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### The log file and images/videos

[latestcrash.txt ](https://pastebin.com/f4n6weuN) 

### Steps To Reproduce

```markdown
- start app
- select 'install .jar'
- select fabric launcher
```

### Expected Behavior

I expect the installer to start

### Platform

```markdown
- Device model: Galaxy Fold 3
- CPU architecture: 
- Android version: 
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
try using firefox to download the jar and try selecting the jar file with another file manager (mix from mixplorer.com)

**Comment by YLlywelyn** [comment]
I already have the installer in my download folder.  I backed out of the file browser and was able to type the path but that just made it close to the home screen with no error message.

I don't get what you mean by selecting the file with a different file browser, it doesn't give me the option of what I want to select the file with, how would I do that?

**Comment by GaucovyAero** [comment]
the samsung file manager or whatever you are using is pointing pojav to a file that doesnt exist
no idea how to switch the file manager on samsung

**Comment by GaucovyAero** [comment]
can you record a video of you selecting the file?

**Comment by YLlywelyn** [comment]
Must have been a problem with android, turns out there are several ways to get to the download folder, one of them gives this error the other works for some reason.  Thanks for the help anyway 🙂
