### ISSUE TITLE
Optifine is not installed

### ISSUE THREAD

**Issue by jrxohan** [PojavLauncherTeam/PojavLauncher#39]
Hello, the final test of mine is that when trying to install recent versions of optifine in 1.7.10, when the screen to be installed appears, it crashes, but when trying to install the older version, it manages to convert and install it, but when it starts, it does not stop  it crashes and it is impossible to play here some images of the results of the new optifine and the old optifine

OptiFine_1.7.10_HD_U_E7 (Latest) 
![Screenshot_20200401_173537_net kdt pojavlaunch](https://user-images.githubusercontent.com/62683247/78196555-0216d080-7440-11ea-9128-55759b1320f7.jpg)

OptiFine_1.7.10_HD_U_D3 (Oldest)
![Screenshot_20200401_173949_net kdt pojavlaunch](https://user-images.githubusercontent.com/62683247/78196665-5752e200-7440-11ea-84aa-e5264d9f9036.jpg)

**Comment by khanhduytran0** [comment]
Can you copy error log and crash report?

**Comment by jrxohan** [comment]
> Can you copy error log and crash report?

java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1026)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lbao;
	at Config.<clinit>(Config.java:106)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at java.lang.Class.forName(Class.java:378)
	at optifine.AndroidInstaller.getConfigValue(AndroidInstaller.java:39)
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:19)
	... 10 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "bao" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/optifine/445062f5aaf982c36c72d90530c26850.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-QHtkPpphgbTN7PPSlrfpQg==/lib/arm64, /system/lib64, /product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 16 more

**Comment by khanhduytran0** [comment]
OK, I'm fixing.

**Comment by jrxohan** [comment]
> Can you copy error log and crash report?

This is the crash report



---- Minecraft Crash Report ----
// Shall we play a game?

Time: 1/4/20 5:58 p. m.
Description: Initializing game

java.lang.ExceptionInInitializerError
	at bao.ag(SourceFile:401)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:797)
	at net.kdt.pojavlaunch.MainActivity.access$1000075(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:585)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List bix.spriteList' on a null object reference
	at bix.addSprite(ModelRenderer.java:329)
	at bif.<init>(SourceFile:15)
	at bou.<init>(SourceFile:18)
	at bnn.<init>(SourceFile:66)
	at bnn.<clinit>(SourceFile:37)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at b.a(CrashReport.java:357)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:357)
	at bao.f(SourceFile:716)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:797)
	at net.kdt.pojavlaunch.MainActivity.access$1000075(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:585)
	at java.lang.Thread.run(Thread.java:784)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version 4.9.148
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (null), The Android Project
	Memory: 19705856 bytes (18 MB) / 112584880 bytes (107 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10-OptiFine_HD_U
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Anisotropic filtering is not supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.

	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (336508784)
	OptiFine Version: OptiFine_1.7.10_HD_U_D3
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
The old one can't be fixed, but I'm fixing the latest one.

**Comment by Azapru** [comment]
> The old one can't be fixed, but I'm fixing the latest one.

Yay!

**Comment by khanhduytran0** [comment]
Try v3.
