### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by omalchielo** [PojavLauncherTeam/PojavLauncher#392]
Hi, I try to play 1.16.4 and its not working its write this: 
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/12/20, 5:35 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dkd.<init>(SourceFile:146)
	at djz.<init>(SourceFile:440)
	at net.minecraft.client.main.Main.main(SourceFile:177)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW
	at deo.<clinit>(SourceFile:46)
	... 3 more
Caused by: java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW
	at deo.<clinit>(SourceFile:41)
	... 3 more
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFW
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dkd.<init>(SourceFile:146)
	at djz.<init>(SourceFile:440)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (aarch64) version 9
	Java Version: 9-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 509365024 bytes (485 MB) / 805306368 bytes (768 MB) up to 838860800 bytes (800 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms512m -Xmx800m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.4
	Backend library: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	Backend API: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	GL Caps: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: ~~ERROR~~ NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI

**Comment by WesleyVanNeck** [comment]
you didnt install lwjgl pls follow the instructions at https://github.com/PojavLauncherTeam/PojavLauncher/wiki/Testing-v3

**Comment by omalchielo** [comment]
I can't when I open games/minecraft a don't have here lwjc3

**Comment by omalchielo** [comment]
I got it thanks
