### ISSUE TITLE
Auth error code

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#393]
Cam you see this
java.lang.RuntimeException: Invalid username or password
	at com.kdt.mojangauth.yggdrasil.YggdrasilAuthenticator.makeRequest(YggdrasilAuthenticator.java:58)
	at com.kdt.mojangauth.yggdrasil.YggdrasilAuthenticator.refresh(YggdrasilAuthenticator.java:86)
	at com.kdt.mojangauth.RefreshTokenTask.doInBackground(RefreshTokenTask.java:38)
	at com.kdt.mojangauth.RefreshTokenTask.doInBackground(RefreshTokenTask.java:11)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1115)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:590)
	at java.lang.Thread.run(Thread.java:818)
i sign in my minecraft account but are this i use a right password and username

**Comment by WesleyVanNeck** [comment]
@ssaagamemer plz use your email and not your username

**Comment by ssaagamemer** [comment]
Oh thx for helping i use a username to login
