### ISSUE TITLE
[BUG] App crashes when i tap the app icon

### ISSUE THREAD

**Issue by Fiz2zy** [PojavLauncherTeam/PojavLauncher#3939]
### Describe the bug

I tap the app icon in my app drawer and it opens to a black screen for a second or two, and then crashes with a crash report.

### The log file and images/videos

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.LauncherActivity}: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:155)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 12 column 3 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:908)
	at com.google.gson.Gson.fromJson(Gson.java:898)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.kdt.pojavlaunch.value.MinecraftAccount.parse(MinecraftAccount.java:62)
	at net.kdt.pojavlaunch.value.MinecraftAccount.load(MinecraftAccount.java:68)
	at net.kdt.pojavlaunch.PojavProfile.getCurrentProfileContent(PojavProfile.java:29)
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:277)
	at com.kdt.mcgui.mcAccountSpinner.reloadAccounts(mcAccountSpinner.java:245)
	at com.kdt.mcgui.mcAccountSpinner.init(mcAccountSpinner.java:137)
	at com.kdt.mcgui.mcAccountSpinner.<init>(mcAccountSpinner.java:52)
	... 29 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 12 column 3 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1405)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:543)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:904)
	... 39 more

### Steps To Reproduce

```markdown
1. Open pojavlauncher
2. Wait a second
3. Crash
```

### Expected Behavior

I expect the app to open

### Platform

```markdown
- Device model: Galaxy A12
- CPU architecture: I dont know
- Android version: Android 11
- PojavLauncher version: dahlia-258-cb44314ab-v3_openjdk
```

### Anything else?

The app has worked fine for the past few months with a few hitches here and there, but after the latest Google Play release, the app doesn't even open. I've tried clearing cache, I don't want to reinstall until I know it's the only option.

**Comment by GaucovyAero** [comment]
uninstall the app and delete all its data, restart your phone, install the app
this is an old issue from dahlia-176, but since you always updated the app instead of fully reinstalling, the issue did not fix itself

**Comment by Fiz2zy** [comment]
> 

Yeah, this was the answer I feared. Thank you for the help though, I'll back up what I can and reinstall

**Comment by GaucovyAero** [comment]
> Yeah, this was the answer I feared. Thank you for the help though, I'll back up what I can and reinstall

okay np
