### ISSUE TITLE
virglrenderer does not work properly

### ISSUE THREAD

**Issue by JakeKimYT** [PojavLauncherTeam/PojavLauncher#3942]
### Describe the bug

everytime i use virglrenderer in minecraft all the texts disappear and when i join a world everything looks buggy grass (not the block) is fully opaque and even the fancy option is on tree leaves are opaque

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-258-cb44314ab-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: fabric-loader-0.14.14-1.19.3
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1520
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-l5WhMKci7p08ci_MTXDZRg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-l5WhMKci7p08ci_MTXDZRg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
OpenJDK 64-Bit Server VM warning: 
getcpu(2) system call not supported by kernel

Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
2023-02-12 09:04:11,268 main ERROR appender Console has no parameter that matches element Policies
[09:04:12] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.14
[09:04:13] [main/INFO]: Loading 61 mods:
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- fabric-api 0.73.2+1.19.3
	- fabric-api-base 0.4.21+70be179c85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.20+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.1+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.5+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.30+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.12+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.22+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.1+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.39+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.47+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.1+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.2+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.14+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.2.1+06937c4b85 via fabric-api
	- fabric-dimensions-v1 2.1.41+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.7+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.40+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.44+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.30+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.10+312c329485 via fabric-api
	- fabric-item-group-api-v1 2.1.12+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.31+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.29+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.10+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.20+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.24+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.14+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.31+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.27+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.17+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.34+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.4.1+eb2a3ba985 via fabric-api
	- fabric-particles-v1 1.0.20
+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.1+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.5+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.1+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.1+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.30+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.18+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.33+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.1+eb2a3ba985 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.3+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.5+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.41+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.13+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.8+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.15+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.1+5b9a588b85 via fabric-api
	- fabricloader 0.14.14
	- ferritecore 5.1.0
	- indium 1.0.14+mc1.19.3
	- java 17
	- lithium 0.10.4
	- minecraft 1.19.3
	- phosphor 0.8.1
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- sodium 0.4.9+build.23
	- sodium-extra 0.4.17+mc1.19.3-build.95
[09:04:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:04:15] [main/INFO]: Compatibility level set to JAVA_16
[09:04:15] [main/INFO]: Compatibility level set to JAVA_17
[09:04:17] [main/INFO]: Loaded configuration file for Lithium: 106 options available, 1 override(s) found
[09:04:17] [main/INFO]: Loaded configuration file for Sodium: 33 options available, 1 override(s) found
[09:04:17] [main/INFO]: Loaded configuration file for Sodium Extra: 28 options available, 3 override(s) found
[09:04:21] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinChunkBuilder' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinClientChunkMap' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinClientPlayNetworkHandler' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinClientWorld' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinPackedIntegerArray' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinPalettedContainer' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinWorldRenderer' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'adaptive_sync.MixinWindow' as option 'mixin.adaptive_sync' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'sodium.resolution.MixinSodiumGameOptionPages' as option 'mixin.sodium.resolution' (added by user configuration) disables it and children
[09:04:22] [main/WARN]: Force-disabling mixin 'sodium.vsync.MixinSodiumGameOptionsPages' as option 'mixin.sodium.vsync' (added by user configuration) disables it and children
[09:04:28] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:?]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:?]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:?]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net
.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]
[09:04:29] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:?]
	at net.minecraft.class_6396.method_37133(class_6396.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:159) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]
[09:05:02] [main/INFO]: Building optimized datafixer
[09:05:23] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[09:05:23] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[09:05:23] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[09:05:23] [Render thread/INFO]: Launching a new process to probe the system configuration!
[09:05:23] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[09:05:23] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[09:05:23] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[09:05:23] [Render thread/ERROR]: Failed to launch driver probe
java.lang.UnsatisfiedLinkError: Failed to locate library: libglfw.so
	at org.lwjgl.system.Library.loadNative(Library.java:324) ~[lwjgl-glfw-classes.jar:?]
	at org.lwjgl.system.Library.loadNative(Library.java:222) ~[lwjgl-glfw-classes.jar:?]
	at me.jellysquid.mods.sodium.client.util.workarounds.classpath.LwjglNatives.findBundledNative(LwjglNatives.java:27) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.util.workarounds.DriverProbeLauncher.launchProbe(DriverProbeLauncher.java:48) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at me.jellysquid.mods.sodium.client.util.workarounds.DriverWorkarounds.init(DriverWorkarounds.java:22) ~[sodium-fabric-mc1.19.3-0.4.9+build.23.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.handler$bdn000$postInitRenderThread(RenderSystem.java:1430) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.initRenderThread(RenderSystem.java:113) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:202) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]
[09:05:25] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:05:28] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.16.29.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:724) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:437) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:87) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.16.29.jar:?]
	... 9 more
[09:05:28] [Render thread/INFO]: Setting user: JakeKim
[09:05:30] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[09:05:30] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
Registered forkAndExec
[09:05:32] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[09:05:33] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
VirGL: OSMesa buffer flush is DISABLED!
VirGL: libvirgl_test_server = 0xa388482de91e7f57
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=26166
EGLBridge: EGLDisplay=0x1, EGLSurface=0x78f5772940
VirGL: created EGL context 0x78f48f7780
EGLBridge: eglMakeCurrent() succeed!
VirGL: vtest_main = 0x79010db278
VirGL: Calling VTest server's main function
OSMDroid: width=1520;height=720, reserving 4377600 bytes for frame buffer
OSMDroid: created frame buffer
OSMDroid: generating context
gl_version 32 - es profile enabled
WARNING: running without ARB/KHR robustness in place may crash
failed to create sync opengl context
vtest_client_dispatch_commands: client context created.
GLSL feature level 430
vrend_renderer_fill_caps: Entering with stale GL error: 1282
GLSL feature level 430
OSMESA_TARGET: screen=0x78ee580000
OSMESA: stmgr=0x78f5484010; stapi=0x78edf25d20
OSMDroid: context=0x78f67a4a60
OSMDroid: making current
unknown format is 19
OSMDroid: vendor: Mesa/X.org
OSMDroid: renderer: virgl
[09:05:41] [Render thread/WARN]: ERROR : Generic error while loading narrator
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:90) ~[jna-5.12.1.jar:?]
	at com.mojang.text2speech.NarratorLinux.<clinit>(NarratorLinux.java:18) ~[text2speech-1.13.9.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:21) ~[text2speech-1.13.9.jar:?]
	at net.minecraft.class_333.<init>(class_333.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:641) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.14-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.14.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.14.jar:?]
[09:05:41] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (CaffeineConfig, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Indium, Lithium, Phosphor, Reese's Sodium Options, Sodium, Sodium Extra)
[09:05:44] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[09:06:05] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:06:05] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[09:06:06] [Render thread/INFO]: OpenAL initialized on device OpenSL
[09:06:06] [Render thread/INFO]: Sound engine started
[09:06:06] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[09:06:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/signs.png-atlas
[09:06:08] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[09:06:08] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[09:06:08] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[09:06:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[09:06:08] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[09:06:11] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[09:06:13] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[09:06:13] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[09:06:13] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[09:06:37] [Server Pinger #0/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 4e:05:8a:31:a4:df:66:03
[09:06:47] [Render thread/INFO]: Connecting to 193.187.129.25, 25028
[09:07:00] [Render thread/INFO]: [System] [CHAT] JakeKim joined the game
[09:07:02] [Render thread/INFO]: Loaded 0 advancements
[09:07:02] [Render thread/INFO]: [System] [CHAT] You're protected from attack by other players as long as your inventory is empty.
[09:07:03] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:03] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:03] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:06] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:11] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:16] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:21] [Render thread/INFO]: [System] [CHAT] Prevent grief!  If you claim your land, you will be grief-proof.
[09:07:21] [Render thread/INFO]: [System] [CHAT] Click for Land Claim Help: bit.ly/mcgpuser
[09:07:22] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:26] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:31] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:36] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:41] [Render thread/INFO]: [System] [CHAT] Please, login with the command: /login <password>
[09:07:47] [Render thread/INFO]: Stopping!
EGLBridge: Terminating

### Steps To Reproduce

```markdown
1.Start Pojavlauncher
2.Use the normal minecraft 1.19.3 because it happens there too
3.Run it
4.Try to join a world
```

### Expected Behavior

I expected that it would work properly

### Platform

```markdown
- Device model: Oppo A3s
- CPU architecture: Octa-core 1.8 GHz Cortex-A53
- Android version: 8.1.0
- PojavLauncher version: dahlia-258-cb44314ab-v3_openjdk
```

### Anything else?

i used minecraft 1.19.3 fabric loader 0.14.14 with sodium, indium, phosphor, ferrite core, sodium extra, reese's sodium options. jre is internal 17

**Comment by GaucovyAero** [comment]
depends on your GPU, we cannot do anything about this
