### ISSUE TITLE
[BUG] Launcher is denying the permission to perform the remapping when installing forge

### ISSUE THREAD

**Issue by JakeKimYT** [PojavLauncherTeam/PojavLauncher#3944]
### Describe the bug

When i try to install forge it says:
"Failed to run processor: java.lang.RuntimeException:Failed to execute task eej$ b.class

See log for more details."
So i got a help from somebody and they said this:
"    "Caused by:

java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")"
Well judging by this, it would seem that there is an access violation. The error could be the launcher denying permission to perform the remapping.    "

### The log file and images/videos
```
JVM info: N/A - 17-internal - 17-internal+0-adhoc.runner.openjdk
java.net.preferIPv4Stack=true
Found java version 17-internal
Extracting json
Considering minecraft client jar
Downloading libraries
Found 0 additional library directories
Considering library cpw.mods:securejarhandler:2.1.6
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-util:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.3
  File exists: Checksum validated.
Considering library net.minecraftforge:accesstransformers:8.0.4
  File exists: Checksum validated.
Considering library org.antlr:antlr4-runtime:4.9.1
  File exists: Checksum validated.
Considering library net.minecraftforge:eventbus:6.0.3
  File exists: Checksum validated.
Considering library net.minecraftforge:forgespi:6.0.0
  File exists: Checksum validated.
Considering library net.minecraftforge:coremods:5.0.1
  File exists: Checksum validated.
Considering library cpw.mods:modlauncher:10.0.8
  File exists: Checksum validated.
Considering library net.minecraftforge:unsafe:0.2.0
  File exists: Checksum validated.
Considering library com.electronwill.night-config:core:3.6.4
  File exists: Checksum validated.
Considering library com.electronwill.night-config:toml:3.6.4
  File exists: Checksum validated.
Considering library org.apache.maven:maven-artifact:3.8.5
  File exists: Checksum validated.
Considering library net.jodah:typetools:0.8.3
  File exists: Checksum validated.
Considering library net.minecrell:terminalconsoleappender:1.2.0
  File exists: Checksum validated.
Considering library org.jline:jline-reader:3.12.1
  File exists: Checksum validated.
Considering library org.jline:jline-terminal:3.12.1
  File exists: Checksum validated.
Considering library org.spongepowered:mixin:0.8.5
  File exists: Checksum validated.
Considering library org.openjdk.nashorn:nashorn-core:15.3
  File exists: Checksum validated.
Considering library net.minecraftforge:JarJarSelector:0.3.19
  File exists: Checksum validated.
Considering library net.minecraftforge:JarJarMetadata:0.3.19
  File exists: Checksum validated.
Considering library cpw.mods:bootstraplauncher:1.1.2
  File exists: Checksum validated.
Considering library net.minecraftforge:JarJarFileSystems:0.3.19
  File exists: Checksum validated.
Considering library net.minecraftforge:fmlloader:1.19.3-44.1.16
  File exists: Checksum validated.
Considering library com.github.jponge:lzma-java:1.3
  File exists: Checksum validated.
Considering library com.google.code.findbugs:jsr305:3.0.2
  File exists: Checksum validated.
Considering library com.google.code.gson:gson:2.8.7
  File exists: Checksum validated.
Considering library com.google.errorprone:error_prone_annotations:2.1.3
  File exists: Checksum validated.
Considering library com.google.guava:guava:20.0
  File exists: Checksum validated.
Considering library com.google.guava:guava:25.1-jre
  File exists: Checksum validated.
Considering library com.google.j2objc:j2objc-annotations:1.1
  File exists: Checksum validated.
Considering library com.nothome:javaxdelta:2.0.1
  File exists: Checksum validated.
Considering library com.opencsv:opencsv:4.4
  File exists: Checksum validated.
Considering library commons-beanutils:commons-beanutils:1.9.3
  File exists: Checksum validated.
Considering library commons-collections:commons-collections:3.2.2
  File exists: Checksum validated.
Considering library commons-io:commons-io:2.4
  File exists: Checksum validated.
Considering library commons-logging:commons-logging:1.2
  File exists: Checksum validated.
Considering library de.oceanlabs.mcp:mcp_config:1.19.3-20221207.122022@zip
  File exists: Checksum validated.
Considering library de.siegmar:fastcsv:2.0.0
  File exists: Checksum validated.
Considering library net.md-5:SpecialSource:1.11.0
  File exists: Checksum validated.
Considering library net.minecraftforge:ForgeAutoRenamingTool:0.1.22:all
  File exists: Checksum validated.
Considering library net.minecraftforge:binarypatcher:1.1.1
  File exists: Checksum validated.
Considering library net.minecraftforge:fmlcore:1.19.3-44.1.16
  File exists: Checksum validated.
Considering library net.minecraftforge:fmlloader:1.19.3-44.1.16
  File exists: Checksum validated.
Considering library net.minecraftforge:forge:1.19.3-44.1.16:universal
  File exists: Checksum validated.
Considering library net.minecraftforge:installertools:1.3.0
  File exists: Checksum validated.
Considering library net.minecraftforge:jarsplitter:1.1.4
  File exists: Checksum validated.
Considering library net.minecraftforge:javafmllanguage:1.19.3-44.1.16
  File exists: Checksum validated.
Considering library net.minecraftforge:lowcodelanguage:1.19.3-44.1.16
  File exists: Checksum validated.
Considering library net.minecraftforge:mclanguage:1.19.3-44.1.16
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.11
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.3
  File exists: Checksum validated.
Considering library net.minecraftforge:srgutils:0.4.9
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:5.0.4
  File exists: Checksum validated.
Considering library net.sf.jopt-simple:jopt-simple:6.0-alpha-3
  File exists: Checksum validated.
Considering library org.apache.commons:commons-collections4:4.2
  File exists: Checksum validated.
Considering library org.apache.commons:commons-lang3:3.8.1
  File exists: Checksum validated.
Considering library org.apache.commons:commons-text:1.3
  File exists: Checksum validated.
Considering library org.checkerframework:checker-qual:2.0.0
  File exists: Checksum validated.
Considering library org.codehaus.mojo:animal-sniffer-annotations:1.14
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-analysis:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-commons:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm-tree:9.3
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.2
  File exists: Checksum validated.
Considering library org.ow2.asm:asm:9.3
  File exists: Checksum validated.
Considering library trove:trove:1.0.2
  File exists: Checksum validated.
Created Temporary Directory: /data/user/0/net.kdt.pojavlaunch/cache/forge_installer11786955900611016212
  Extracting: /data/client.lzma
Building Processors
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/installertools/1.3.0/installertools-1.3.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/md-5/SpecialSource/1.11.0/SpecialSource-1.11.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/srgutils/0.4.11/srgutils-0.4.11.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/opencsv/opencsv/4.4/opencsv-4.4.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
  Args: --task, MCP_DATA, --input, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022.zip, --output, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings.txt, --key, mappings
Task: MCP_DATA
Input:  /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022.zip
Output: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings.txt
Key:    mappings
Extracting: config/joined.tsrg
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/installertools/1.3.0/installertools-1.3.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/md-5/SpecialSource/1.11.0/SpecialSource-1.11.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/srgutils/0.4.11/srgutils-0.4.11.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/opencsv/opencsv/4.4/opencsv-4.4.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
  Args: --task, DOWNLOAD_MOJMAPS, --version, 1.19.3, --side, client, --output, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-mappings.txt
Task: DOWNLOAD_MOJMAPS
MC Version: 1.19.3
Side:       client
Output:     /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-mappings.txt
Downloaded Mojang mappings for 1.19.3
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/installertools/1.3.0/installertools-1.3.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/md-5/SpecialSource/1.11.0/SpecialSource-1.11.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/code/gson/gson/2.8.7/gson-2.8.7.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/siegmar/fastcsv/2.0.0/fastcsv-2.0.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/srgutils/0.4.11/srgutils-0.4.11.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/guava/guava/20.0/guava-20.0.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/opencsv/opencsv/4.4/opencsv-4.4.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-text/1.3/commons-text-1.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
  Args: --task, MERGE_MAPPING, --left, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings.txt, --right, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-mappings.txt, --output, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings-merged.txt, --classes, --reverse-right
Task: MERGE_MAPPING
Left:    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings.txt
         Reversed=false
         null
Right:   /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-mappings.txt
         Reversed=true
         null
Classes: true
Fields:  false
Methods: false
Params:  false
Output:  /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings-merged.txt
===============================================================================
  Cache: 
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-slim.jar Validated: e0bd62d190cd8a4078069d0bba05bf9797dc32ea
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-extra.jar Validated: e552266e2777e0045a578eb69add6f689450502a
  Cache Hit!
===============================================================================
  MainClass: net.minecraftforge.fart.Main
  Classpath:
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/ForgeAutoRenamingTool/0.1.22/ForgeAutoRenamingTool-0.1.22-all.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/6.0-alpha-3/jopt-simple-6.0-alpha-3.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
    /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/srgutils/0.4.9/srgutils-0.4.9.jar
  Args: --input, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-slim.jar, --output, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-srg.jar, --names, /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings-merged.txt, --ann-fix, --ids-fix, --src-fix, --record-fix
Forge Auto Renaming Tool v0.1.22
log: null
input: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-slim.jar
output: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-srg.jar
threads: 8
Names: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.3-20221207.122022/mcp_config-1.19.3-20221207.122022-mappings-merged.txt(reversed: false)
Fix Annotations: true
Fix Records: true
Fix Identifiers: ALL
Fix SourceFile: JAVA
Fix Line Numbers: false
Strip codesigning signatures: false
Adding Libraries to Inheritance
Reading Input: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/client/1.19.3-20221207.122022/client-1.19.3-20221207.122022-slim.jar
Adding input to inheritence map
Processing entries
java.lang.RuntimeException: Failed to execute task eej$b.class
	at net.minecraftforge.fart.internal.AsyncHelper.invokeAll(AsyncHelper.java:70)
	at net.minecraftforge.fart.internal.AsyncHelper.invokeAll(AsyncHelper.java:55)
	at net.minecraftforge.fart.internal.RenamerImpl.run(RenamerImpl.java:121)
	at net.minecraftforge.fart.Main.main(Main.java:173)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.installer.actions.PostProcessors.process(PostProcessors.java:226)
	at net.minecraftforge.installer.actions.ClientInstall.run(ClientInstall.java:144)
	at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:423)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:175)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)
Caused by: java.util.concurrent.ExecutionException: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at net.minecraftforge.fart.internal.AsyncHelper.invokeAll(AsyncHelper.java:66)
	... 12 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessDeclaredMembers")
	at java.base/java.security.AccessControlContext.checkPermission(Unknown Source)
	at java.base/java.security.AccessController.checkPermission(Unknown Source)
	at java.base/java.lang.SecurityManager.checkPermission(Unknown Source)
	at java.base/java.lang.Class.checkMemberAccess(Unknown Source)
	at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
	at net.minecraftforge.fart.internal.InheritanceImpl$ClassInfo.<init>(InheritanceImpl.java:153)
	at net.minecraftforge.fart.internal.InheritanceImpl.computeClassInfo(InheritanceImpl.java:102)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at net.minecraftforge.fart.internal.InheritanceImpl.getClass(InheritanceImpl.java:79)
	at net.minecraftforge.fart.internal.EnhancedRemapper.computeClass(EnhancedRemapper.java:145)
	at net.minecraftforge.fart.internal.EnhancedRemapper.getClass(EnhancedRemapper.java:128)
	at net.minecraftforge.fart.internal.EnhancedRemapper.access$100(EnhancedRemapper.java:46)
	at net.minecraftforge.fart.internal.EnhancedRemapper$MClass.<init>(EnhancedRemapper.java:172)
	at net.minecraftforge.fart.internal.EnhancedRemapper.computeClass(EnhancedRemapper.java:149)
	at net.minecraftforge.fart.internal.EnhancedRemapper.getClass(EnhancedRemapper.java:128)
	at net.minecraftforge.fart.internal.EnhancedRemapper.map(EnhancedRemapper.java:90)
	at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:78)
	at org.objectweb.asm.commons.Remapper.mapType(Remapper.java:97)
	at org.objectweb.asm.commons.ClassRemapper.visit(ClassRemapper.java:107)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:569)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at net.minecraftforge.fart.internal.RenamingTransformer.process(RenamingTransformer.java:54)
	at net.minecraftforge.fart.internal.EntryImpl$ClassEntry.process(EntryImpl.java:72)
	at net.minecraftforge.fart.internal.EntryImpl$ClassEntry.process(EntryImpl.java:50)
	at net.minecraftforge.fart.internal.RenamerImpl.processEntry(RenamerImpl.java:194)
	at net.minecraftforge.fart.internal.AsyncHelper.lambda$null$2(AsyncHelper.java:54)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Cant Find Class: org/lwjgl/stb/STBIWriteCallback
Cant Find Class: com/google/common/cache/CacheLoader
Cant Find Class: org/apache/commons/io/output/CountingOutputStream
Cant Find Class: org/apache/http/entity/InputStreamEntity
Cant Find Class: it/unimi/dsi/fastutil/longs/Long2IntLinkedOpenHashMap
Cant Find Class: it/unimi/dsi/fastutil/longs/Long2FloatLinkedOpenHashMap
Cant Find Class: com/google/gson/reflect/TypeToken
Cant Find Class: com/google/common/collect/ForwardingList
Cant Find Class: com/mojang/serialization/MapCodec
Cant Find Class: io/netty/channel/ChannelInitializer
Cant Find Class: io/netty/channel/SimpleChannelInboundHandler
Cant Find Class: io/netty/channel/Channel
Cant Find Class: io/netty/buffer/ByteBuf
Cant Find Class: com/google/common/collect/AbstractIterator
Cant Find Class: com/google/common/base/Ticker
Cant Find Class: com/mojang/serialization/RecordBuilder$AbstractStringBuilder
Cant Find Class: io/netty/handler/codec/MessageToMessageDecoder
Cant Find Class: io/netty/handler/codec/MessageToByteEncoder
Cant Find Class: io/netty/handler/codec/ByteToMessageDecoder
Cant Find Class: io/netty/handler/codec/EncoderException
Cant Find Class: io/netty/channel/ChannelHandler$Sharable
Cant Find Class: io/netty/channel/ChannelHandler
Cant Find Class: io/netty/channel/ChannelHandlerContext
Cant Find Class: io/netty/channel/ChannelInboundHandlerAdapter
Cant Find Class: org/slf4j/Logger
Cant Find Class: com/google/gson/TypeAdapter
Cant Find Class: com/mojang/datafixers/DataFix
Cant Find Class: com/mojang/datafixers/DSL$TypeReference
Cant Find Class: com/mojang/datafixers/DSL
Cant Find Class: com/mojang/datafixers/types/templates/TaggedChoice$TaggedChoiceType
Cant Find Class: com/google/common/collect/ImmutableMap$Builder
Cant Find Class: com/mojang/datafixers/types/templates/List$ListType
Cant Find Class: com/mojang/datafixers/types/templates/TaggedChoice
Cant Find Class: com/mojang/datafixers/types/templates/List
Cant Find Class: com/google/common/collect/ImmutableMap
Cant Find Class: com/mojang/datafixers/schemas/Schema
Cant Find Class: com/mojang/datafixers/types/templates/Tag$TagType
Cant Find Class: com/mojang/datafixers/types/templates/Tag
Cant Find Class: com/mojang/datafixers/types/templates/CompoundList$CompoundListType
Cant Find Class: com/mojang/datafixers/types/templates/CompoundList
Cant Find Class: com/mojang/datafixers/types/templates/Hook$HookFunction
Cant Find Class: com/mojang/datafixers/types/templates/Hook
Cant Find Class: it/unimi/dsi/fastutil/objects/Object2ByteLinkedOpenHashMap
Cant Find Class: it/unimi/dsi/fastutil/longs/LongLinkedOpenHashSet
Cant Find Class: it/unimi/dsi/fastutil/longs/Long2ByteOpenHashMap
Cant Find Class: it/unimi/dsi/fastutil/longs/Long2LongLinkedOpenHashMap
Cant Find Class: it/unimi/dsi/fastutil/HashCommon
Cant Find Class: it/unimi/dsi/fastutil/doubles/AbstractDoubleList
Cant Find Class: it/unimi/dsi/fastutil/doubles/DoubleList
Failed to run processor: java.lang.RuntimeException:Failed to execute task eej$b.class
See log for more details.
```

### Steps To Reproduce

```markdown
1.Start PojavLauncher
2.Install forge for 1.19.3 then remove then install forge for 1.19.2
```

### Expected Behavior

I expect the forge installation to be successful

### Platform

```markdown
- Device model: Oppo A3s
- CPU architecture: Octa-core 1.8 GHz Cortex-A53
- Android version: 8.1.0
- PojavLauncher version: dahlia-258-cb44314ab-v3_openjdk
```

**Comment by GaucovyAero** [comment]
you may need at least android 10, but for now: dont use google chrome to download the forge installer - use firefox or fennec, use java 8 to install forge
