### ISSUE TITLE
[BUG] [Custom Controls] Changing the default control ingame doesn't work

### ISSUE THREAD

**Issue by Felix14-v2** [PojavLauncherTeam/PojavLauncher#3951]
### Description

The default control selection doesn't work when the game is running (or I don't understand the logic)

### Demo

https://youtu.be/uSYCn3pGBwE

### To Reproduce

- Create multiple control layouts
- Set the default control in the instance settings
- Launch the game
- Try to change the default control
- control does not change

### Anything else?

If the file of the previous control no longer exists, you will see this error (file not found):
```markdown
java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/controlmap/./Controls by Felix14_v2 1.4.5 rc-16.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.customcontrols.LayoutConverter.loadAndConvertIfNecessary(LayoutConverter.java:24)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:48)
	at net.kdt.pojavlaunch.MainActivity.leaveCustomControls(MainActivity.java:414)
	at net.kdt.pojavlaunch.CustomControlsActivity.lambda$null$2(CustomControlsActivity.java:185)
	at net.kdt.pojavlaunch.-$$Lambda$CustomControlsActivity$V5plX1wVGX68cg7OKqbNQfcFYYI.onClick(Unknown Source:11)
	at android.view.View.performClick(View.java:7465)
	at android.view.View.performClickInternal(View.java:7438)
	at android.view.View.access$3600(View.java:813)
	at android.view.View$PerformClick.run(View.java:28511)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:268)
	at android.app.ActivityThread.main(ActivityThread.java:8000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:627)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7884)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 18 more
```

### Expected Behavior

Changing the default control ingame expected to work correctly

### Platform

```markdown
- Device model: TECNO LE7n
- CPU architecture: x64
- Android version: 11
- PojavLauncher version: latest from Actions/GooglePlay
```

**Comment by mchnjt** [comment]
bruh
```
open failed: ENOENT (No such file or directory)
```

**Comment by Felix14-v2** [comment]
> bruh

Please, read _carefully_

**Comment by mchnjt** [comment]
@Felix14-v2 you should use exit instead, not `SAVE` because you're selecting a default control to be loaded for your profile

**Comment by Felix14-v2** [comment]
> @Felix14-v2 you should use exit instead, not `SAVE` because you're selecting a default control to be loaded for your profile

the problem is that it doesn't matter

https://user-images.githubusercontent.com/75726196/218427045-971ded8d-0e31-443b-a9bc-10139f422270.mp4

**Comment by Felix14-v2** [comment]
File not found error seems to have been fixed (latest version from Actions)... now controls doesn't change without any error message :D

https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/fceb31b9-3ab0-45cf-b1a4-30f41fc68f1b

**Comment by GaucovyAero** [comment]
should be fixed in the latest play store release

**Comment by hieudaucat** [comment]
java.io.IOException: Unsupported control layout version
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:60)
	at net.kdt.pojavlaunch.CustomControlsActivity.setDefaultControlJson(CustomControlsActivity.java:223)
	at net.kdt.pojavlaunch.CustomControlsActivity.access$000(CustomControlsActivity.java:26)
	at net.kdt.pojavlaunch.CustomControlsActivity$1.onFileSelected(CustomControlsActivity.java:131)
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:150)
	at com.kdt.pickafile.FileListView.lambda$init$0$FileListView(FileListView.java:84)
	at com.kdt.pickafile.-$$Lambda$FileListView$HLMKWCW4lmZii7cxzrOIrbJTM20.onItemClick(Unknown Source:6)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1203)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3216)
	at android.widget.AbsListView$3.run(AbsListView.java:4182)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:204)
	at android.os.Looper.loop(Looper.java:291)
	at android.app.ActivityThread.main(ActivityThread.java:8133)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

**Comment by hieudaucat** [comment]
How to fix

**Comment by Felix14-v2** [comment]
> How to fix

You are probably using outdated PojavLauncher

**Comment by Magick4** [comment]
> > How to fix
> 
> You are probably using outdated PojavLauncher

This is actually happening to me too

**Comment by Magick4** [comment]
> > How to fix
> 
> You are probably using outdated PojavLauncher

And I'm useing the latest Google Playstore bulid

**Comment by Felix14-v2** [comment]
> And I'm useing the latest Google Playstore bulid

Make sure that the default controlmap field is empty in the instance settings
![Screenshot_20231101-114614](https://github.com/PojavLauncherTeam/PojavLauncher/assets/75726196/e8799602-5d82-4a7e-9137-d7e473ea3bdb)
