### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Perry6074** [PojavLauncherTeam/PojavLauncher#397]
**Describe the bug**
I tried to play minecraft 1.16.14 and it showed an error.

**To Reproduce**
1. Start PojavLauncher
2. Select V1.16.14
3. Play
4. Wait for download to complete
5. Error

**Platform:**
 - Huawei Y6 Prime 2019 2/32
 - Android Version 9

The error:

java.lang.RuntimeException: Architecture arm/aarch32 is incompatible with Java Runtime aarch64.
	at net.kdt.pojavlaunch.MainActivity.checkJavaArchitecture(MainActivity.java:988)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:961)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:28)
	at net.kdt.pojavlaunch.MainActivity$13$1.run(MainActivity.java:725)
	at java.lang.Thread.run(Thread.java:784)

**Comment by MuzsNick** [comment]
I think your device is not compatible with the launcher, you will not be able to play any version because it is a bit bad, I mean it is low-end

**Comment by khanhduytran0** [comment]
You need arm32/aarch32 JRE instead.

**Comment by King26d** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.get(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:91)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:906)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2400(BaseMainActivity.java:27)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:709)
	at java.lang.Thread.run(Thread.java:919)

**Comment by PolarForce9898** [comment]
Can you play on Samsung phone

**Comment by Sean4261** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/397#issuecomment-728712098

**Comment by tushar473** [comment]
Remove all bugs

**Comment by BartMONE** [comment]
can you play on chrome os
