### ISSUE TITLE
[BUG] Download failed after linking microsoft account linked with minecraft.net and minecraft java in profile

### ISSUE THREAD

**Issue by abraini-Nascent** [PojavLauncherTeam/PojavLauncher#3986]
### Describe the bug

I have linked my microsoft account, which is linked with minecraft.net.  The login is successful, I can see my profile name in the top left.  I can see minecraft java in my profile on minecraft.net.  I own minecraft java and bedrock and have profiles in both.  I bought minecraft through the microsoft app store, tho it is linked and is visible on minecraft.net and I can login and play with this account on my mac and pc.

When I hit the play button I get "Failed to download". I've tried on two different devices.

### The log file and images/videos

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/Unknown/Unknown.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:777)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:71)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:52)
	at net.kdt.pojavlaunch.tasks.-$$Lambda$AsyncMinecraftDownloader$PJ58CinqkXoL4aS1zc2TGQSS9zk.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/Unknown/Unknown.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:846)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:691)
	... 6 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7759)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 10 more

### Steps To Reproduce

```markdown
Successfully login with microsoft account
See profile and play button
Tap the play button
```

### Expected Behavior

It should download and start minecraft

### Platform

```markdown
- Device model: Odin Lite and Motorola G Power (2021)
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: dahlia-260-ff1db3127-v3_openjdk
```

### Anything else?

Any help would be appreciated thanks! 🙏

**Comment by abraini-Nascent** [comment]
🤦 I had to select the version.  maybe as a feature request you could default to the lastest version on install
