### ISSUE TITLE
[BUG] <Short description>EVERYTHING DOWN

### ISSUE THREAD

**Issue by TEJASVABG** [PojavLauncherTeam/PojavLauncher#4020]
### Describe the bug

there a bug while i start it
android.view.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: android.view.InflateException: Binary XML file line #73: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:656)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:835)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:775)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:908)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:869)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:521)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
	at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1740)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)

### The log file and images/videos

![Screenshot_20230308_121314](https://user-images.githubusercontent.com/91388013/223638727-8361c060-fce3-45c9-8869-d486a1aa48f5.jpg)

### Steps To Reproduce

```markdown
Nothing
```

### Expected Behavior

i expected the game will start but it did not

### Platform

```markdown
- Device model: vivo1723
- CPU architecture: aarch64
- Android version:9
- PojavLauncher version:Latest Release dahlia-260-ff1db3127-v3_openjdk
```

### Anything else?

Nothing else please solve this promblem

**Comment by GaucovyAero** [comment]
delete all pojav data

**Comment by Pinecone6442** [comment]
> delete all pojav data

you dont watch enough pornhub

**Comment by GaucovyAero** [comment]
how does this happen tho?
