### ISSUE TITLE
[BUG] PojavLauncher broken

### ISSUE THREAD

**Issue by Pinecone6442** [PojavLauncherTeam/PojavLauncher#4024]
### Describe the bug

I somehow fucked up the app heres the log

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.LauncherActivity}: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3797)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3973)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8528)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: android.view.InflateException: Binary XML file line #17 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:155)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Activity.performCreate(Activity.java:8191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3770)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3973)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8528)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 12 column 3 path $
	at com.google.gson.Gson.assertFullConsumption(Gson.java:908)
	at com.google.gson.Gson.fromJson(Gson.java:898)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.kdt.pojavlaunch.value.MinecraftAccount.parse(MinecraftAccount.java:62)
	at net.kdt.pojavlaunch.value.MinecraftAccount.load(MinecraftAccount.java:68)
	at net.kdt.pojavlaunch.PojavProfile.getCurrentProfileContent(PojavProfile.java:29)
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:277)
	at com.kdt.mcgui.mcAccountSpinner.reloadAccounts(mcAccountSpinner.java:245)
	at com.kdt.mcgui.mcAccountSpinner.init(mcAccountSpinner.java:137)
	at com.kdt.mcgui.mcAccountSpinner.<init>(mcAccountSpinner.java:52)
	... 28 more
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 12 column 3 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1405)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:543)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:426)
	at com.google.gson.Gson.assertFullConsumption(Gson.java:904)
	... 38 more

### The log file and images/videos

.

### Steps To Reproduce

```markdown
1. start it
2. uh i dont know what i did
```

### Expected Behavior

d

### Platform

```markdown
no figure it out urself
```

### Anything else?

balls

**Comment by VenomousSteam81** [comment]
looks like the game itself is messed up. which build is this? latest google play or actions

**Comment by Pinecone6442** [comment]
> looks like the game itself is messed up. which build is this? latest google play or actions

Latest

**Comment by GaucovyAero** [comment]
duplicate, most probably fixed in the latest actions build
