### ISSUE TITLE
[BUG] ANGLE renderer does not work

### ISSUE THREAD

**Issue by JakeKimYT** [PojavLauncherTeam/PojavLauncher#4028]
### Describe the bug

whenever i use angle renderer it says something in the log file that theres an error in loading a lib/.so file (just check the log)

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-310-ed1870eec-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.3-OptiFine_HD_U_I2_pre5
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1520
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-cUzTUdGJRw8WInSfilC9DA==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-cUzTUdGJRw8WInSfilC9DA==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_desktopgl_angle_vulkan
Added custom env: LIBGL_ES=3
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: POJAVEXEC_EGL=libEGL_angle.so
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
WARNING: linker: 
"
/data/app/net.kdt.pojavlaunch-cUzTUdGJRw8WInSfilC9DA==/lib/arm64/libGLESv2_angle.so
" unused DT entry: type 
0x70000001
 arg 
0x0

OpenJDK 64-Bit Server VM warning: 
getcpu(2) system call not supported by kernel

Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
2023-03-10 06:57:37,018 main ERROR appender Console has no parameter that matches element Policies
[06:57:37] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[06:57:37] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[06:57:37] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[06:57:37] [main/INFO]: [OptiFine] OptiFineTweaker: acceptOptions
[06:57:37] [main/INFO]: [OptiFine] OptiFineTweaker: injectIntoClassLoader
[06:57:37] [main/INFO]: [OptiFine] OptiFine ClassTransformer
[06:57:37] [main/INFO]: [OptiFine] OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/optifine/OptiFine/1.19.3_HD_U_I2_pre5/OptiFine-1.19.3_HD_U_I2_pre5.jar
[06:57:38] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchArguments
[06:57:38] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchTarget
[06:57:40] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2023-03-10 06:57:40,589 main ERROR appender Console has no parameter that matches element Policies
[06:57:43] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at z.c(SourceFile:75) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.a(SourceFile:82) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.a(SourceFile:75) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.c(SourceFile:52) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.a(SourceFile:82) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.<init>(SourceFile:52) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at n.<init>(CrashReport.java:34) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at n.h(CrashReport.java:345) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:159) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) ~[launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) ~[launchwrapper-of-2.3.jar:2.3]
[06:57:44] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at z.a(SourceFile:77) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.a(SourceFile:82) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.a(SourceFile:77) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.c(SourceFile:52) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.a(SourceFile:82) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at z.<init>(SourceFile:52) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at n.<init>(CrashReport.java:34) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at n.h(CrashReport.java:345) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:159) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) ~[launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) ~[launchwrapper-of-2.3.jar:2.3]
[06:57:46] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[06:57:46] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.common.extensions.IForgeEntity
[06:57:46] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.logging.CrashReportExtender
[06:57:51] [main/INFO]: [OptiFine] (Reflector) Method not present: amk.create
[06:58:10] [main/INFO]: Building optimized datafixer
[06:58:27] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[06:58:27] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[06:58:27] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[06:58:27] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[06:58:29] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[06:58:33] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.16.29.jar:?]
	at ejf.a(SourceFile:724) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at ejf.<init>(SourceFile:437) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:205) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3-OptiFine_HD_U_I2_pre5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) ~[launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) ~[launchwrapper-of-2.3.jar:2.3]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:87) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.16.29.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.16.29.jar:?]
	... 12 more
[06:58:33] [Render thread/INFO]: Setting user: JakeKim
Registered forkAndExec
[06:58:34] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[06:58:34] [Render thread/INFO]: [OptiFine] (Reflector) Method not present: ejd.getKeyModifier
[06:58:34] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[06:58:35] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
WARNING: linker: 
"
/data/app/net.kdt.pojavlaunch-cUzTUdGJRw8WInSfilC9DA==/lib/arm64/libEGL_angle.so
" unused DT entry: type 
0x70000001
 arg 
0x0

WARNING: linker: 
"
/data/app/net.kdt.pojavlaunch-cUzTUdGJRw8WInSfilC9DA==/lib/arm64/libGLESv2_angle.so
" unused DT entry: type 
0x70000001
 arg 
0x0

[06:58:36] [Render thread/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.fml.loading.progress.EarlyProgressVisualization.handOffWindow
EGLBridge: Binding to desktop OpenGL
[06:58:37] [Render thread/INFO]: [OptiFine] 
[06:58:37] [Render thread/INFO]: [OptiFine] OptiFine_1.19.3_HD_U_I2_pre5
[06:58:37] [Render thread/INFO]: [OptiFine] Build: 20230219-203817
[06:58:37] [Render thread/INFO]: [OptiFine] OS: Linux (aarch64) version Android-8.1.0
[06:58:37] [Render thread/INFO]: [OptiFine] Java: 17-internal, N/A
[06:58:37] [Render thread/INFO]: [OptiFine] VM: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
[06:58:37] [Render thread/INFO]: [OptiFine] LWJGL: 3.4.0
[06:58:37] [Render thread/INFO]: [OptiFine] OpenGL: ANGLE (Qualcomm, Vulkan 1.0.61 (Adreno (TM) 506 (0x05000600)), Qualcomm-20.200.1259), version 4.6.0 (ANGLE 2.1.1 git hash: b79b72b53460), Google Inc. (Qualcomm)
[06:58:37] [Render thread/INFO]: [OptiFine] OpenGL Version: 4.6.0
[06:58:37] [Render thread/INFO]: [OptiFine] Maximum texture size: 16384x16384
[06:58:37] [VersionCheck/INFO]: [OptiFine] Checking for new version
[06:58:37] [Render thread/INFO]: [Shaders] OpenGL Version: 4.6.0 (ANGLE 2.1.1 git hash: b79b72b53460)
[06:58:37] [Render thread/INFO]: [Shaders] Vendor:  Google Inc. (Qualcomm)
[06:58:37] [Render thread/INFO]: [Shaders] Renderer: ANGLE (Qualcomm, Vulkan 1.0.61 (Adreno (TM) 506 (0x05000600)), Qualcomm-20.200.1259)
[06:58:37] [Render thread/INFO]: [Shaders] Capabilities:  -  2.1  -  -  - 
[06:58:37] [Render thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[06:58:37] [Render thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS: 8
[06:58:37] [Render thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 16
[06:58:37] [Render thread/INFO]: [Shaders] Load shaders configuration.
[06:58:37] [Render thread/INFO]: [Shaders] No shaderpack loaded.
[06:58:37] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.ModList
[06:58:38] [VersionCheck/INFO]: [OptiFine] java.io.FileNotFoundException: http://optifine.net/version/1.19.3/HD_U.txt

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Choose ANGLE renderer
3. Start any version
```

### Expected Behavior

I expect the game to launch correctly

### Platform

```markdown
- Device model: Oppo A3s
- CPU architecture: aarch64
- Android version: 8.1.0
- PojavLauncher version: [Latest Release]
```

**Comment by GaucovyAero** [comment]
your phone's firmware probably does not support vulkan
