### ISSUE TITLE
[BUG] Unknown Crashed When Mod Installed

### ISSUE THREAD

**Issue by ssaagamemer** [PojavLauncherTeam/PojavLauncher#4043]
### Describe the bug

Application Exited With Code 1

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/10986410/latestlog.txt)

```CrashTrace

I/jrelog  ( 5129): Done processing args
I/jrelog  ( 5129): Found JLI lib
I/jrelog  ( 5129): Calling JLI_Launch

WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
Exception in thread "main" 
java.lang.ExceptionInInitializerError
	at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
	at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
	at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:84)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @6a1aab78
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
	at cpw.mods.niofs.union.UnionFileSystem.<clinit>(UnionFileSystem.java:45)
	... 8 more
Java Exit code: 1
I/jrelog  ( 5129): Going to free args
I/jrelog  ( 5129): Free done
```

### Steps To Reproduce

```markdown
Start Pojavlauncher
Add And Mod
Click Play On Forge Installed Version
And Crash
```

### Expected Behavior

Launch Normal

### Platform

```markdown
- Device model: Redmi Note 10 4/128 (Boosted Added 2 GB Of Ram)
- CPU architecture: Unknown
- Android version: 12 
- PojavLauncher version: dahila-323-b98340a1f
```

### Anything else?

💢💢💢💢💢💢💢💢💢💢💢💢
For Banning Me In Discord Ima Uninstall

**Comment by Mathias-Boulay** [comment]
fixed in dev builds
