### ISSUE TITLE
[BUG] <Exit code 1, When I use OptiFine in Forge 1.19.2>

### ISSUE THREAD

**Issue by Asushi11** [PojavLauncherTeam/PojavLauncher#4085]
### Describe the bug

Application exit with the code 1,  using Forge on 1.19.2

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.2-forge-43.1.33
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1200
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~P293t610wSj-l0a5gb5u5w==/net.kdt.pojavlaunch-X2l7IhldznLm0VL8uSeAfw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~P293t610wSj-l0a5gb5u5w==/net.kdt.pojavlaunch-X2l7IhldznLm0VL8uSeAfw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_desktopgl_angle_vulkan
Added custom env: LIBGL_ES=3
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: POJAVEXEC_EGL=libEGL_angle.so
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=540
--------- beginning of main

I/jrelog  (17292): dlopen libtinywrapper.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (17292): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Inter
nal-17/lib/libsctp.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success
I/jrelog  (17292): dlopen /data/user
/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/j
relog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (17292): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  (17292): dlopen /data/app/~~P293t610wSj-l0a5gb5u5w==/net.kdt.pojavlaunch-X2l7IhldznLm0VL8uSeAfw==/lib/arm64/libopenal.so success
I/jrelog  (17292): Done processing args
I/jrelog  (17292): Found JLI lib
I/jrelog  (17292): Calling JLI_Launch

2023-03-30 20:36:07,666 main ERROR appender Console has no parameter that matches element Policies
[20:36:08] [main/INFO]: ModLauncher running: args [--username, Asushii, --version, 1.19.2, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 1.19, --uuid, 00000000000000000000000000000000, --accessToken, 鉂勨潉鉂勨潉鉂勨潉鉂勨潉, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.1.33, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[20:36:08] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.7-internal by N/A; OS Linux arch aarch64 version Android-12
[20:36:08] [main/INFO]: OptiFineTransformationService.onLoad
[20:36:08] [main/INFO]: OptiFine ZIP file URL: union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/OptiFine_1.19.2_HD_U_I1.jar%23117!/
[20:36:08] [main/INFO]: OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/OptiFine_1.19.2_HD_U_I1.jar
[20:36:08] [main/INFO]: Target.PRE_CLASS is available
[20:36:09] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=CLIENT
[20:36:09] [main/INFO]: OptiFineTransformationService.initialize
[20:36:09] [main/INFO]: Found mod file voicechat-forge-1.19.2-2.3.10.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[20:36:10] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/fmlcore/1.19.2-43.1.33/fmlcore-1.19.2-43.1.33.jar is missing mods.toml file
[20:36:10] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/javafmllanguage/1.19.2-43.1.33/javafmllanguage-1.19.2-43.1.33.jar is missing mods.toml file
[20:36:10] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/lowcodelanguage/1.19.2-43.1.33/lowcodelanguage-1.19.2-43.1.33.jar is missing mods.toml file
[20:36:10] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/mclanguage/1.19.2-43.1.33/mclanguage-1.19.2-43.1.33.jar is missing mods.toml file
[20:36:10] [main/INFO]: Found mod file fmlcore-1.19.2-43.1.33.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@77bb0ab5
[20:36:10] [main/INFO]: Found mod file javafmllanguage-1.19.2-43.1.33.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@77bb0ab5
[20:36:10] [main/INFO]: Found mod file lowcodelanguage-1.19.2-43.1.33.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@77bb0ab5
[20:36:10] [main/INFO]: Found mod file mclanguage-1.19.2-43.1.33.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@77bb0ab5
[20:36:10] [main/INFO]: Found mod file client-1.19.2-20220805.130853-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@77bb0ab5
[20:36:10] [main/INFO]: Found mod file forge-1.19.2-43.1.33-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@77bb0ab5
[20:36:11] [main/INFO]: No dependencies to load found. Skipping!
[20:36:13] [main/INFO]: OptiFineTransformationService.transformers
[20:36:13] [main/INFO]: Targets: 386
[20:36:14] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[20:36:16] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.19.2, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --uuid, 00000000000000000000000000000000, --username, Asushii, --assetIndex, 1.19, --accessToken, 鉂勨潉鉂勨潉鉂勨潉鉂勨潉, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release]
[20:36:32] [pool-3-thread-1/INFO]: Building unoptimized datafixer
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[20:36:39] [Render thread/WARN]: Assets URL 'union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23119!/assets/.mcassetsroot' uses unexpected schema
[20:36:39] [Render thread/WARN]: Assets URL 'union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar%23119!/data/.mcassetsroot' uses unexpected schema
[20:36:40] [Render thread/INFO]: [OptiFine] java.lang.NullPointerException: Cannot read field "ofTelemetry" because "net.optifine.Config.gameSettings" is null
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2023-03-30 20:36:40
Description: Initializing game

java.lang.NoSuchMethodError: 'void net.minecraftforge.resource.ResourceCacheManager.<init>(boolean, java.lang.String, java.util.function.BiFunction)'
	at net.minecraft.server.packs.VanillaPackResources.<init>(VanillaPackResources.java:478) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.resources.DefaultClientPackResources.<init>(DefaultClientPackResources.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading}
	at net.minecraft.client.resources.ClientPackSource.<init>(ClientPackSource.java:80) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:400) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.33.jar%2361!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2374!/:?] {}
	at
 cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.server.packs.VanillaPackResources.<init>(VanillaPackResources.java:478) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.resources.DefaultClientPackResources.<init>(DefaultClientPackResources.java:20) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading}
	at net.minecraft.client.resources.ClientPackSource.<init>(ClientPackSource.java:80) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:400) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.m_239872_(Main.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23119!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at j
dk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.33.jar%2361!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2374!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17.0.7-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1990931296 bytes (1898 MiB) / 2422210560 bytes (2310 MiB) up to 2422210560 bytes (2310 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd0b Stepping r0x1p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics car
d #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 9996.74
	Virtual memory used (MB): 5986.30
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 1616.60
	JVM Flags: 3 total; -Xms2310M -Xmx2310M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.19.2_HD_U_I1
	OptiFine Build: 20221213-150857
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2023-03-30_20.36.40-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7cf10bbcf8)
I/jrelog  (17417): dlopen libxhook.so success

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install Forge
3. Put mods (OptiFine and voicechat)
4. Play with Forge and Mods.
5. Enter in a server and crash
```

### Expected Behavior

I think this is because of OptiFine. every time i use and I enter in a server it crashes.

### Platform

```markdown
- Device model: Redmi Note 11S
- CPU architecture: arm64
- Android version: 12 SP
- PojavLauncher version: dahlia-740-623
```

**Comment by Jiigaw** [comment]
Hello. There are a number of mods that dont work on pojav launcher. You can see a list of them here:
https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html#performance-mods-shaders
I hope that helped!

**Comment by Asushi11** [comment]
Thanks
