### ISSUE TITLE
[BUG] Game crashes when starting forge.

### ISSUE THREAD

**Issue by MovTery** [PojavLauncherTeam/PojavLauncher#4094]
### Describe the bug

I can install forge normally, but once I start the game, it will crash.
Everything else is normal. For example, fabric won't crash.

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-743-c3c907a3c-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.19.2-forge-43.2.8
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2340
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/~~iPADv4Q2iNgA-2SxKXVeaQ==/net.kdt.pojavlaunch.debug-I7WVXd0eTE3N3mmHEILz_Q==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~iPADv4Q2iNgA-2SxKXVeaQ==/net.kdt.pojavlaunch.debug-I7WVXd0eTE3N3mmHEILz_Q==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
Exception in thread "main" 
java.lang.ExceptionInInitializerError
	at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
	at cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
	at cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
	at cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:84)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field static final java.lang.invoke.MethodHandles$Lookup java.lang.invoke.MethodHandles$Lookup.IMPL_LOOKUP accessible: module java.base does not "opens java.lang.invoke" to unnamed module @fe18270
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at cpw.mods.niofs.union.UnionFileSystem.<clinit>(UnionFileSystem.java:45)
	... 8 more
Java Exit code: 1

### Steps To Reproduce

```markdown
1.Start the game
2.The game exits with a code of 1.
```

### Expected Behavior

Help me start forge normally

### Platform

```markdown
- Device model: OPPO A9/128G
- CPU architecture: aarch64
- Android version: 11
- PojavLauncher version: 3.3.1.1_rel_20210206
```

**Comment by ssaagamemer** [comment]
ok this problem you use wrong directory use only .minecraft folder bc .minecraft/(customfolder) i try and crash on mine

**Comment by MovTery** [comment]
> 

Although I don't know why I can't use a custom folder, I still want to thank you for helping me solve the problem. Now I can start forge normally.
