### ISSUE TITLE
[BUG] compatibility problem with mod "emote replay compat" 

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#4098]
### Describe the bug

When you start the game, it comes out with an error of -1

### The log file and images/videos

latestlog.txt failed to load, so here it is:
--------- beginning with launcher debug
Info: Launcher version: dahlia-742-841000702-
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: fabric-loader-0.14.19-1.16.5
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2388
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~Z-7iql9fbgZ5SvyWNzAhAw==/net.kdt.pojavlaunch.debug-35ak09oIYxVKlK_od8mcjw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~Z-7iql9fbgZ5SvyWNzAhAw==/net.kdt.pojavlaunch.debug-35ak09oIYxVKlK_od8mcjw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20210825-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of crash

--------- beginning of main

2023-04-05 10:00:00,592 main ERROR appender Console has no parameter that matches element Policies
[10:00:00] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.19
[10:00:01] [main/INFO]: Loading 66 mods:
	- emotecraft 2.2.6-SNAPSHOT-build.44
	   |-- bendy-lib 1.2.2
	   \-- player-animator 0.3.5+1.16.5
	- emotes-compat-rp 0.1.2
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3c
c0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabric-language-kotlin 1.8.4+kotlin.1.7.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.7.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.7.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0
	- fabricloader 0.14.19
	- java 17
	- minecraft 1.16.5
	- modmenu 1.16.5
	- replaymod 1.16.4-2.6.8
[10:00:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:00:01] [main/INFO]: Compatibility level set to JAVA_17
[10:00:02] [main/WARN]: Reference map 'emotes_replay_compat-refmap.json' for emotes_compat.mixins.json could not be read. If this is a development environment you can ignore this message
[10:00:02] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[10:00:03] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[10:00:03] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[10:00:03] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[10:00:03] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[10:00:03] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[10:00:23] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:00:26] [main/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:125) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:94) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:625) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:409) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:177) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.minecraftservices.com/privileges
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at com.mojang.authlib.HttpAuthenticationService.performGetRequest(HttpAuthenticationService.java:140) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:104) ~[authlib-2.1.28.j
ar:?]
	... 9 more
[10:00:26] [main/INFO]: Setting user: iarkont
[10:00:39] [main/INFO]: [Indigo] Registering Indigo renderer!
[10:00:40] [main/WARN]: WARNING! Mod replaymod is only using deprecated 'modmenu:clientsideOnly' custom value! This is no longer needed and will be removed in 1.18 snapshots.
Registered forkAndExec
[10:00:42] [main/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[10:00:42] [main/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[10:00:42] [main/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 05.04.2023, 10:00
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'emotes-compat-rp'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: org/slf4j/Logger
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:68)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:32)
	at net.fabricmc.language.kotlin.KotlinAdapter.create(KotlinAdapter.kt:109)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.Logger
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at ja
va.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-11
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1475850240 bytes (1407 MB) / 1845493760 bytes (1760 MB) up to 1845493760 bytes (1760 MB)
	CPUs: 8
	JVM Flags: 3 total; -Xms1760M -Xmx1760M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Fabric Mods:
 
		bendy-lib: Bendy api 1.2.2
		emotecraft: Emotecraft 2.2.6-SNAPSHOT-build.44
		emotes-compat-rp: Emotecraft compatibility layer 0.1.2
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.8.4+kotlin.1.7.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (
v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.14.19
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.16.5
		modmenu: Mod Menu 1.16.5
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-j
vm: 
kotlinx-serialization-cbor-jvm 1.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		player-animator: Player Animator 0.3.5+1.16.5
		replaymod: Replay Mod 1.16.4-2.6.8
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/crash-reports/crash-2023-04-05_10.00.42-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x734eef5b58) 

### Steps To Reproduce

```markdown
1. Launched pojavlauncher 
2. Chose JRE 17 because the mod does not work with JRE8
3. launched fabric 1.16.5 loader 0.14.19
4. game crashed
```

### Expected Behavior

i was expecting the game to start

### Platform

```markdown
- Device model: Huawei nova 9 se 8/128G
- CPU architecture: aarch64 adreno 610
- Android version: emui 12
- PojavLauncher version: latest Release
```

### Anything else?

seems to be everything

**Comment by Iarkont** [comment]
I figured out what the problem was: need versions 1.19x, but then there was another problem xd
![Screenshot_20230405_160701_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/230090139-41f4dbf7-11f5-42f0-8579-4d87c9840b6b.jpg)
this is version 1.19.4 on virgl, the problem you see yourself

**Comment by Iarkont** [comment]
> I figured out what the problem was: need versions 1.19x, but then there was another problem xd ![Screenshot_20230405_160701_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/230090139-41f4dbf7-11f5-42f0-8579-4d87c9840b6b.jpg) this is version 1.19.4 on virgl, the problem you see yourself

![Screenshot_20230405_174146_net kdt pojavlaunch debug](https://user-images.githubusercontent.com/75908293/230117190-329cd09a-6770-4266-9393-f2043499af06.jpg)
and this is the same version only on angle render
