### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by Pheterisdumb** [PojavLauncherTeam/PojavLauncher#4101]
### Describe the bug

Application exited code 1

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.12.2-forge-14.23.5.2860
--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success
--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success
--------- beginning of system
read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success
--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success

--------- beginning of system
read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success
--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success
--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success

--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success

--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success
--------- beginning of system

read: unexpected EOF!

--------- beginning of main

I/jrelog  ( 2689): dlopen libxhook.so success

--------- beginning of system

read: unexpected EOF!

ERROR: Unable to get more log.
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1520
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-Jsxw_C9EOT5uQTxR-NJPrw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/vgc/bin:/oem/bin:/sbin:/system/sbin:/product/bin:/apex/com.android.runtime/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-Jsxw_C9EOT5uQTxR-NJPrw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
Arc Capes DNS Injector

Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Failed to inject cache!

java.lang.ClassNotFoundException: java.net.InetAddress$CacheEntry

	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at git.artdeell.arcdns.CacheUtil_J8.getConstructorOfInetAddress$CacheEntry(CacheUtil_J8.java:45)
	at git.artdeell.arcdns.CacheUtil_J8.newCacheEntry(CacheUtil_J8.java:32)
	at git.artdeell.arcdns.CacheUtil_J8.setInetAddressCache(CacheUtil_J8.java:20)
	at git.artdeell.arcdns.ArcDNSInjectorAgent.premain(ArcDNSInjectorAgent.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
2023-04-07 08:12:43,465 main ERROR appender Console has no parameter that matches element Policies

[08:12:44] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:12:44] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:12:44] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[08:12:44] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[08:12:44] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_372-internal, running on Linux:aarch64:Android-10, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal
[08:12:45] [main/INFO]: Searching /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods for mods
[08:12:45] [main/WARN]: The coremod codechicken.nei.asm.NEICorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[08:12:45] [main/WARN]: The coremod NEICorePlugin (codechicken.nei.asm.NEICorePlugin) is not signed!
[08:12:45] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:12:45] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[08:12:45] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:12:45] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[08:12:45] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2023-04-07 08:12:49,376 main ERROR appender Console has no parameter that matches element Policies

[08:12:54] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[08:12:54] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[08:12:54] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[08:12:54] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
Exception in thread "main" 
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: codechicken/core/launch/CodeChickenCorePlugin
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at codechicken.nei.asm.NEICorePlugin.getASMTransformerClass(NEICorePlugin.java:17)
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: codechicken.core.launch.CodeChickenCorePlugin
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[08:12:54] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[08:12:54] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[08:12:54] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[08:12:54] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 6 more
Java Exit code: 1

### Steps To Reproduce

```markdown
1.start Pojavlauncher
2.start forge
3.wait
4.game exited
```

### Expected Behavior

I expected the game would launch

### Platform

```markdown
- Device model: Android 
- CPU architecture: not sure
- Android version:10 
- PojavLauncher version: latest
```

### Anything else?

I hope this get fixed

**Comment by NotAHero04** [comment]
CodeChickenLib was missing.

**Comment by Pheterisdumb** [comment]
What can i do

**Comment by overdrive2902** [comment]
same issue here. no mods. just forge by itself. i noticed there was the same issue before too. something about needing to be in java 8. im on Chromebook. what minecraft version is that forge for that your using? im trying to use 1.12.2 for some mods.

**Comment by Pheterisdumb** [comment]
![Screenshot_20230407_140958.jpg](https://user-images.githubusercontent.com/128298010/230552006-e1c3f305-95be-442b-9cc2-d6e81efa28f6.jpg)

Im using this forge version

**Comment by overdrive2902** [comment]
ok

**Comment by overdrive2902** [comment]
same as me

**Comment by mchnjt** [comment]
Get the CodeChickenLib mod. @NotAHero04 already mentioned it was missing.

**Comment by overdrive2902** [comment]
it didnt fix it but apparently there WAS a mod and removing it fixed it
