### ISSUE TITLE
How do you set up lwjgl on 3.2.0 testing-6?

### ISSUE THREAD

**Issue by zian04** [PojavLauncherTeam/PojavLauncher#411]
When i tap play i get thisjava.lang.RuntimeException: LWJGL3 was not installed!
	at net.kdt.pojavlaunch.MainActivity.checkLWJGL3Installed(MainActivity.java:1005)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:945)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:28)
	at net.kdt.pojavlaunch.MainActivity$13$1.run(MainActivity.java:712)
	at java.lang.Thread.run(Thread.java:818)

(This is on verson of minecraft 1.9 btw)

**Comment by WesleyVanNeck** [comment]
join the discord for qeastions this is a issue tracker not a ticket service
