### ISSUE TITLE
[BUG] Launcher Crashing When Loading

### ISSUE THREAD

**Issue by AwesomePotatoCodes** [PojavLauncherTeam/PojavLauncher#4136]
### Describe the bug

Launcher crashes upon opening. It seems to have issues with the layout rendering.

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11328362/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open launcher
```

### Expected Behavior

The launcher is supposed to open like normal. The issue is undetermined as it was working fine around an hour before.

### Platform

```markdown
- Device model: CTL. Chromebook
- CPU architecture: ARM64
- Android version: (Latest)
- PojavLauncher version: (Latest Release)
```

### Anything else?

Seems to only happen on ChromeOS. Problems with the XML file that helps render the UI from what I can understand.

**Comment by AwesomePotatoCodes** [comment]
Turns out latestlog.txt was empty so I'll just copy and paste the Java error.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.LauncherActivity}: android.view.InflateException: Binary XML file line #18 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #18 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3460)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: android.view.InflateException: Binary XML file line #18 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Binary XML file line #18 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: android.view.InflateException: Binary XML file line #18 in net.kdt.pojavlaunch:layout/activity_pojav_launcher: Error inflating class com.kdt.mcgui.mcAccountSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
	at net.kdt.pojavlaunch.LauncherActivity.onCreate(LauncherActivity.java:154)
	at android.app.Activity.performCreate(Activity.java:8010)
	at android.app.Activity.performCreate(Activity.java:7994)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1327)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3433)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String net.kdt.pojavlaunch.value.MinecraftAccount.accessToken' on a null object reference
	at net.kdt.pojavlaunch.value.MinecraftAccount.load(MinecraftAccount.java:69)
	at net.kdt.pojavlaunch.PojavProfile.getCurrentProfileContent(PojavProfile.java:29)
	at com.kdt.mcgui.mcAccountSpinner.pickAccount(mcAccountSpinner.java:295)
	at com.kdt.mcgui.mcAccountSpinner.reloadAccounts(mcAccountSpinner.java:253)
	at com.kdt.mcgui.mcAccountSpinner.init(mcAccountSpinner.java:144)
	at com.kdt.mcgui.mcAccountSpinner.<init>(mcAccountSpinner.java:52)
	... 28 more
```

**Comment by AwesomePotatoCodes** [comment]
Alright, so I found a fix. The issue can be fixed by uninstalling the game and reinstalling. Hope this helps anyone with the same issue. :)
