### ISSUE TITLE
Cannot run fabric 1.16.5 with mods

### ISSUE THREAD

**Issue by Rty575** [PojavLauncherTeam/PojavLauncher#4148]
### Describe the bug

I installed fabric without a single mod and it was fine but when i added fabric api it crashed here is my log

### The log file and images/videos

[09:44:09] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.19
[09:44:09] [main/WARN]: Mod resolution failed
[09:44:09] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED fabric-api 0.79.2+1.20 {depends minecraft @ [>=1.20- <1.20.1-]}, ROOT_FORCELOAD_SINGLE fabric-api 0.79.2+1.20]
[09:44:09] [main/INFO]: Reason: [HARD_DEP fabric-api 0.79.2+1.20 {depends minecraft @ [>=1.20- <1.20.1-]}, HARD_DEP fabric-command-api-v2 2.2.7+df5b2a9d4e {depends minecraft @ [>1.19-alpha.22.11.a]}, HARD_DEP fabric-convention-tags-v1 1.4.2+9a7c5daa4e {depends minecraft @ [>=1.18.2]}, HARD_DEP fabric-sound-api-v1 1.0.10+75e982114e {depends minecraft @ [>=1.19.2]}]
[09:44:09] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.16.5] -> add:minecraft 1.20- ([[1.20-,1.20.1-)])]
[09:44:09] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.16.5 with any version between 1.20- (inclusive) and 1.20.1- (exclusive).
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.79.2+1.20 requires any version between 1.20- (inclusive) and 1.20.1- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Command API (v2)' (fabric-command-api-v2) 2.2.7+df5b2a9d4e requires any version after 1.19-alpha.22.11.a of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Convention Tags' (fabric-convention-tags-v1) 1.4.2+9a7c5daa4e requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Sound API (v1)' (fabric-sound-api-v1) 1.0.10+75e982114e requires version 1.19.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) [launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102) [launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) [launcher.jar:?]
[09:44:09] [main/WARN]: Failed to open the error gui!
java.lang.RuntimeException: can't find java executable in /private/var/containers/Bundle/Application/2AED738C-17EB-4F12-9B8D-0C3B380A2E5E/PojavLauncher.app/jvm/java-17-openjdk/bin
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.openForked(FabricGuiEntry.java:71) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.open(FabricGuiEntry.java:53) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:141) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:108) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:84) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:141) [launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.launchMinecraft(PojavLauncher.java:102) [launcher.jar:?]
	at net.kdt.pojavlaunch.PojavLauncher.main(PojavLauncher.java:55) [launcher.jar:?]

### Steps To Reproduce

```markdown
1. Installed loader 1.16.5
2. Run it withouwt mods
3. Upload mods
4. Run it again
5. It crashed
```

### Expected Behavior

I expect the game to launch with sodium mod and api fabricc

### Platform

```markdown
- Device model: iphone 6.11 xsmax
- CPU architecture: idk 
- Android version: ios 15.3.1 troll store
- PojavLauncher version: latest
```

**Comment by Jfjfrjdjjd** [comment]
You used the wrong mod version for Minecraft 1.16.5

**Comment by HierarchyMan** [comment]
Bro ur using 1.20 mods with 1.16 close this issue lol

**Comment by Rty575** [comment]
> Bro ur using 1.20 mods with 1.16 close this issue lol

Nope only 1.16.5 mods

**Comment by Rty575** [comment]
> Bro ur using 1.20 mods with 1.16 close this issue lol

Yes im stupid i forgot the api
