### ISSUE TITLE
[F-Req] skip download/check assets

### ISSUE THREAD

**Issue by rhjdvsgsgks** [PojavLauncherTeam/PojavLauncher#4153]
### Is this request related to a bug?

on the old version i can replace assets folder with a empty file to skip download it. not working anymore with recent version (will cause some exception).

### Describe the request.

i have pretty limited storage. and i dont need audio or i18n. assets for me is just wasting space. so i dont want download it

### Anything else?

temporally solution is create a file with `{"objects":{}}` to `.minecraft/assets/indexes/version.json`

**Comment by artdeell** [comment]
Won't happen. We've had enough people who pressed skipt and asked where's the sound or how to switch the language. If you know what you're doing, just do that

**Comment by rhjdvsgsgks** [comment]
can you catch and ignore this exception? so that i dont need to create file for each version anymore.
```
net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$DownloaderException: java.io.IOException: Not a directory
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:101)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:53)
	at net.kdt.pojavlaunch.tasks.-$$Lambda$AsyncMinecraftDownloader$PJ58CinqkXoL4aS1zc2TGQSS9zk.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.io.IOException: Not a directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createTempFile(File.java:2018)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:58)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadIndex(AsyncMinecraftDownloader.java:362)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:98)
	... 5 more
```
