### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Quanle121** [PojavLauncherTeam/PojavLauncher#4162]
### Describe the bug

Nó ghi đã bị rớt là sao?

### The log file and images/videos

![Screenshot_2023-05-03-16-44-38-42](https://user-images.githubusercontent.com/132430266/235883560-6e468e28-e3d2-4aa5-ad4c-b7365aec79e5.png)

### Steps To Reproduce

```markdown
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.LauncherActivity}: android.view.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating class com.kdt.mcgui.mcVersionSpinner
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2829)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2890)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:186)
	at android.app.ActivityThread.main(ActivityThread.java:6513)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
Caused by: android.view.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: android.view.InflateException: Binary XML file line #73: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1740)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at net.kdt.pojavlaunch.LauncherActivity.onStart(LauncherActivity.java:186)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
	at android.app.Activity.performStart(Activity.java:7009)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2792)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2890)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:186)
	at android.app.ActivityThread.main(ActivityThread.java:6513)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'java.util.Map net.kdt.pojavlaunch.value.launcherprofiles.MinecraftLauncherProfiles.profiles' on a null object reference
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.update(LauncherProfiles.java:27)
	at net.kdt.pojavlaunch.profiles.ProfileAdapter.<init>(ProfileAdapter.java:34)
	at com.kdt.mcgui.mcVersionSpinner.<init>(mcVersionSpinner.java:55)
	... 34 more
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.Map net.kdt.pojavlaunch.value.launcherprofiles.MinecraftLauncherProfiles.profiles' on a null object reference
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.update(LauncherProfiles.java:15)
	... 36 more
```

### Expected Behavior

Mong đợi admin sửa lỗi ạ

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Ko

**Comment by GaucovyAero** [comment]
remove .minecraft/launcher-profiles.json
