### ISSUE TITLE
[BUG] Could not run Sodium and Iris Shader with Holy Gl4es

### ISSUE THREAD

**Issue by hsragi** [PojavLauncherTeam/PojavLauncher#4167]
### Describe the bug

I could not run Sodium Mod and Iris Shader with Minecraft1.19.4-Fabric

### The log file and images/videos

[00:09:07] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.19
[00:09:08] [main/INFO]: Loading 87 mods:
	- appleskin 2.4.3+mc1.19.4
	- badpackets 0.4.1
	- cloth-config 10.0.96
	   \-- cloth-basic-math 0.6.1
	- dynamicfps 2.2.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- entityculling 1.6.2-mc1.19.4
	- fabric-api 0.76.0+1.19.4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-command-api-v2 2.2.4+ae0966baf4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.52+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   |-- fabric-networking-v0 0.3.39+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabric-language-kotlin 1.9.2+kotlin.1.8.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
	- fabricloader 0.14.19
	- firstperson 2.2.3
	- inventoryprofilesnext 1.9.3
	- iris 1.6.2
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- libipn 2.0.3
	- malilib 0.15.0
	- minecraft 1.19.4
	- minihud 0.26.0
	- modmenu 6.1.0-rc.1
	- neat 1.19.4-34-FABRIC
	   \-- fiber 0.23.0-2
	- sodium 0.4.11+build.26
	   |-- fabric-api-base 0.4.24+9ff28bcef4
	   |-- fabric-rendering-data-attachment-v1 0.3.28+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.21+f1e4495bf4
	   \-- fabric-resource-loader-v0 0.11.2+1e1fb126f4
	- voxelmap 1.19.4-1.12.5
	- wthit 7.0.0
[00:09:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/C409-7C02/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[00:09:08] [main/INFO]: Compatibility level set to JAVA_17
[00:09:09] [main/INFO]: Loaded configuration file for Sodium: 35 options available, 2 override(s) found
[00:09:11] [main/WARN]: Force-disabling mixin 'features.gui.font.MixinGlyphRenderer' as rule 'mixin.features.gui.font' (added by mods [iris]) disables it and children
[00:09:11] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[00:09:14] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:?]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:?]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:?]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
[00:09:15] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:?]
	at net.minecraft.class_6396.method_37133(class_6396.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:274) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
[00:09:15] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[00:09:15] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
[00:09:29] [Datafixer Bootstrap/INFO]: 180 Datafixer optimizations took 655 milliseconds
[00:09:35] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[00:09:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[00:09:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[00:09:35] [Render thread/INFO]: Launching a new process to probe the system configuration!
[00:09:35] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[00:09:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[00:09:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[00:09:35] [Render thread/ERROR]: Failed to launch driver probe
java.lang.UnsatisfiedLinkError: Failed to locate library: libglfw.so
	at org.lwjgl.system.Library.loadNative(Library.java:324) ~[lwjgl-glfw-classes.jar:?]
	at org.lwjgl.system.Library.loadNative(Library.java:222) ~[lwjgl-glfw-classes.jar:?]
	at me.jellysquid.mods.sodium.client.util.workarounds.classpath.LwjglNatives.findBundledNative(LwjglNatives.java:27) ~[sodium-fabric-mc1.19.4-0.4.11+build.26.jar:?]
	at me.jellysquid.mods.sodium.client.util.workarounds.DriverProbeLauncher.launchProbe(DriverProbeLauncher.java:48) ~[sodium-fabric-mc1.19.4-0.4.11+build.26.jar:?]
	at me.jellysquid.mods.sodium.client.util.workarounds.DriverWorkarounds.init(DriverWorkarounds.java:22) ~[sodium-fabric-mc1.19.4-0.4.11+build.26.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.handler$bgo000$sodium$postInitRenderThread(RenderSystem.java:2950) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.initRenderThread(RenderSystem.java:120) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:195) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
[00:09:36] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:09:38] [Render thread/INFO]: Setting user: PAIMON1145
[00:09:39] [Render thread/INFO]: Loading FirstPerson Mod
[00:09:39] [Render thread/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[00:09:39] [Render thread/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[00:09:39] [Render thread/INFO]: [WTHIT] Using mcp.mobius.waila.plugin.core.pick.ObjectPicker as the object picker
[00:09:40] [Render thread/INFO]: [WTHIT] Plugin config reloaded
[00:09:40] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[00:09:41] [Worker-Main-1/INFO]: Checking mod updates...
[00:09:42] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[00:09:42] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[00:09:43] [Worker-Main-1/INFO]: Update available for 'modmenu@6.1.0-rc.1', (-> 6.2.2)
[00:09:43] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.76.0+1.19.4', (-> 0.80.0+1.19.4)
[00:09:43] [Worker-Main-1/INFO]: Update available for 'fabric-language-kotlin@1.9.2+kotlin.1.8.10', (-> 1.9.4+kotlin.1.8.21)
[00:09:43] [Worker-Main-1/INFO]: Update available for 'libipn@2.0.3', (-> fabric-1.19.4-2.0.7)
[00:09:43] [Worker-Main-1/INFO]: Update available for 'inventoryprofilesnext@1.9.3', (-> fabric-1.19.4-1.9.7)
[00:09:43] [Worker-Main-1/INFO]: Update available for 'wthit@7.0.0', (-> fabric-7.2.3)
[00:09:43] [Render thread/INFO]: Debug functionality is disabled.
[00:09:44] [Render thread/INFO]: DSA support not detected.
[00:09:44] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[00:09:44] [Render thread/INFO]: Shaders are disabled
[00:09:45] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[00:09:46] [Render thread/INFO]: Hardware information:
[00:09:46] [Render thread/INFO]: CPU: <unknown>
[00:09:46] [Render thread/INFO]: GPU: virgl (Supports OpenGL 4.3 (Compatibility Profile) Mesa 21.2.1 (git-c403646518))
[00:09:46] [Render thread/INFO]: OS: Linux (Android-10)
[00:09:47] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.16.7.jar:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.16.7.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.16.7.jar:?]
	at net.minecraft.class_333.<init>(class_333.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:647) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:90) ~[jna-5.12.1.jar:?]
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.16.7.jar:?]
	... 8 more
[00:09:47] [Render thread/INFO]: Reloading ResourceManager: vanilla, Fabric Mods (AppleSkin, Cloth Config v10, Dynamic FPS, EntityCulling-Fabric, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Group API (v1), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, FirstpersonModel, Inventory Profiles Next, Iris, libIPN, MaLiLib, MiniHUD, Mod Menu, Neat, Sodium, Voxelmap, wthit), file/1.19.3-1.8.9-SimpleHotbar.zip, file/1.19.3-Quadral+v.6.07.zip, file/3D Default 1.19.4 v1.7.0.zip
[00:09:48] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[00:09:50] [Render thread/INFO]: PlayerAnimator not found!
[00:09:51] [Render thread/WARN]: CATEGORY ORDER IS 11
[00:09:51] [Render thread/INFO]: Created: 256x256 waypoints-atlas
[00:09:51] [Render thread/INFO]: Created: 256x128 chooser-atlas
[00:09:53] [Render thread/INFO]: Created: 512x256 mobs-atlas
[00:09:53] [Render thread/INFO]: Created: 64x32 pings-atlas
[00:09:56] [Worker-Main-6/WARN]: Missing textures in model minecraft:flowering_azalea_leaves#distance=5,persistent=true,waterlogged=true:
    minecraft:textures/atlas/blocks.png:minecraft:block/azalea_leaves_flowers
[00:09:56] [Render thread/WARN]: Missing sound for event: minecraft:item.brush.brushing
[00:09:56] [Render thread/WARN]: Missing sound for event: minecraft:item.brush.brush_sand_completed
[00:09:56] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[00:09:56] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[00:09:56] [Render thread/WARN]: Missing sound for event: minecraft:music.overworld.cherry_grove
[00:09:57] [Render thread/INFO]: OpenAL initialized on device OpenSL
[00:09:57] [Render thread/INFO]: Sound engine started
[00:09:57] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/blocks.png-atlas
[00:09:57] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/signs.png-atlas
[00:09:57] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[00:09:57] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[00:09:57] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/armor_trims.png-atlas
[00:09:57] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/decorated_pot.png-atlas
[00:09:57] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/chest.png-atlas
[00:09:57] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[00:09:57] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[00:09:59] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[00:09:59] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[00:09:59] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[00:09:59] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[00:10:06] [Server Pinger #0/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 61:07:92:56:db:ce:e4:ca
[00:10:16] [Render thread/INFO]: Connecting to play.simpfun.vip, 35867
[00:10:18] [Render thread/INFO]: Started 2 worker threads
[00:10:21] [Render thread/INFO]: [Inventory Profiles Next] Loaded 0 external GUI hints
[00:10:21] [Render thread/INFO]: [Inventory Profiles Next] Loaded 769 build-in GUI hints
[00:10:21] [Render thread/INFO]: [Inventory Profiles Next] Effective GUI hints after merge: 769
[00:10:23] [Render thread/INFO]: [System] [CHAT] PAIMON1145加入了游戏
[00:10:24] [Render thread/INFO]: Loaded 546 advancements
[00:10:24] [Render thread/INFO]: [System] [CHAT] There's a new Geyser update available to support Bedrock version 1.19.80. Download it here: https://ci.geysermc.org
[00:10:30] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.16.7.jar:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.16.7.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.16.7.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
	at mcp.mobius.waila.gui.hud.TooltipRenderer.narrateObjectName(TooltipRenderer.java:266) ~[wthit-fabric-7.0.0.jar:?]
	at mcp.mobius.waila.gui.hud.TooltipRenderer.endBuild(TooltipRenderer.java:107) ~[wthit-fabric-7.0.0.jar:?]
	at mcp.mobius.waila.gui.hud.TooltipHandler.tick(TooltipHandler.java:189) ~[wthit-fabric-7.0.0.jar:?]
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:63) ~[wthit-fabric-7.0.0.jar:?]
	at mcp.mobius.waila.fabric.FabricWailaClient.lambda$onInitializeClient$0(FabricWailaClient.java:22) ~[wthit-fabric-7.0.0.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:62) ~[fabric-lifecycle-events-v1-2.2.1+5da15ca1f4-82e44bf02244b555.jar:?]
	at net.minecraft.class_310.handler$zfa000$fabric-lifecycle-events-v1$onEndTick(class_310.java:4516) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1958) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1180) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.NativeLibrary
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.16.7.jar:?]
	... 17 more
[00:10:31] [Render thread/INFO]: [System] [CHAT] Inventory Profiles Next: 版本：'1.9.7' 已更新。\n下载链接："Modrinth" 或 "CurseForge"
[00:10:38] [Render thread/INFO]: Resized to: 512x512 mobs-atlas
[00:11:02] [Render thread/INFO]: Stopping worker threads
[00:11:14] [MCO Compatability Checker #1/INFO]: Realms is available for this user

### Steps To Reproduce

```markdown
1. Start PojavLauncher for Android
2. Start Minecraft 1.19.4 with fabric
3. join a server
4. Crash
```

### Expected Behavior

I used all the renderers and couldn't play any worlds (including servers) on Minecraft 1.19.4-Fabric loaded with Sodium and Iris shader

### Platform

```markdown
- Device model: Honor Play5T
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: dahlia-741-3f6ff3f15-
```

### Anything else?

When I use "virglrenderer" and start Minecraft Fabric 1.19.4, when I enter the world or server, only a map-like screen is rendered (I loaded the Voxelmap mod).

**Comment by root-S7** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/1948

and try delete "waila" MOD

**Comment by Coolpowersearch** [comment]
It didn't work, I removed waila and removed any conflicting mods, and the dependencies were not missing. The main menu of the game entered normally, but when I tried to enter the world, it flashed back.

**Comment by hsragi** [comment]
It didn't work, I removed waila and removed any conflicting mods, and the dependencies were not missing. The main menu of the game entered normally, but when I tried to enter the world, it flashed back.

**Comment by Coolpowersearch** [comment]
It didn't work, I removed waila and removed any conflicting mods, and the dependencies were not missing. The main menu of the game entered normally, but when I tried to enter the world, it flashed back.

**Comment by lost72738** [comment]
Use Zink instead
