### ISSUE TITLE
[BUG] I cannot create a profile. 

### ISSUE THREAD

**Issue by aloyen07** [PojavLauncherTeam/PojavLauncher#4169]
### Describe the bug

I can't create a game profile. 
Traceback:
```
java.lang.RuntimeException: java.io.IOException: Failed to create parent directory
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.update(LauncherProfiles.java:38)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.save(ProfileEditorFragment.java:236)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.lambda$onViewCreated$0$net-kdt-pojavlaunch-fragments-ProfileEditorFragment(ProfileEditorFragment.java:89)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7503)
	at android.view.View.performClickInternal(View.java:7480)
	at android.view.View.access$3600(View.java:813)
	at android.view.View$PerformClick.run(View.java:28445)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7950)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.io.IOException: Failed to create parent directory
	at net.kdt.pojavlaunch.Tools.write(Tools.java:745)
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.update(LauncherProfiles.java:32)
	... 14 more
```

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/11403564/latestlog.txt)

https://user-images.githubusercontent.com/129771777/236384601-29794d76-ad27-40dc-b413-b109805a7cec.mp4

### Steps To Reproduce

```markdown
1. Start a Pojav.
2. Press «Create a profile»
3. Select a settings. 
4. Save a profile.
```

### Expected Behavior

Created profile 

### Platform

```markdown
- Device model: Realme C21-Y 
- CPU architecture: 6x ARM Cortex-A55 @ 1820 МГц
2x ARM Cortex-A75 @ 1820 МГц
- Android version: 11
- PojavLauncher version: Latest (From GitHub)
```

**Comment by GaucovyAero** [comment]
try using the latest play store version
