### ISSUE TITLE
[BUG] <Ошибка>

### ISSUE THREAD

**Issue by s6ww0** [PojavLauncherTeam/PojavLauncher#4183]
### Describe the bug

Установил 1.12.2 после чего захотел поставить forge
Но, вечно вылазит эта ошибка
java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/1000526149
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at net.kdt.pojavlaunch.Tools.lambda$launchModInstaller$11(Tools.java:936)
	at net.kdt.pojavlaunch.-$$Lambda$Tools$46FTZmdCg2wQlH_7QdcqTtuXPaI.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

Ранее я установил, но потом удалил forge 1.12.2, решил заново установить, но теперь ввлазят ошибки, я переустанавливал PL, удалял файлы, не помоглл

### The log file and images/videos

 `PojavLauncher crash report
 - Time: 8 мая 2023 г. 19:39:40
 - Device: a51cs SM-A515W
 - Android version: 13
 - Crash stack trace:
 - Launcher version: dahlia-740-623f7dd33-v3_openjdk
java.lang.SecurityException: com.android.externalstorage has no access to content://media/external_primary/file/1000526149
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at net.kdt.pojavlaunch.Tools.lambda$launchModInstaller$11(Tools.java:936)
	at net.kdt.pojavlaunch.-$$Lambda$Tools$46FTZmdCg2wQlH_7QdcqTtuXPaI.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
`

### Steps To Reproduce

```markdown
1. Запустил PL
2. Установил 1.12.2
3. Запустился в игру
4. Вышел, и зашел заново
5. Нажал 'Установить .jar'
6. Выбрал forge 1.12.2
7. Вылет
```

### Expected Behavior

Помочь исправить данную ошибку

### Platform

```markdown
- Device model: Samsung a51
- CPU architecture: ""
- Android version: 13
- PojavLauncher version: Последний выпуск
```

**Comment by FazziCLAY** [comment]
Вряд-ли разрабы понимают русский язык.
**Translate this by google translate** (Переведи это через гугл переводчик)

**Comment by Prostop194** [comment]
if you know the answer to solve this error please help

**Comment by Prostop194** [comment]
> Вряд-ли разрабы проверяют русский язык. **Переведи это с помощью гугл переводчика** (Переведи это через гугл переводчик)



> Вряд-ли разрабы проверяют русский язык. **Переведи это с помощью гугл переводчика** (Переведи это через гугл переводчик)

bro help my friend has an error when installing forge (any) here is the link below 
https://github.com/PojavLauncherTeam/PojavLauncher/issues/4299

**Comment by GaucovyAero** [comment]
use internal storage - download instead of downloads in the file selection
