### ISSUE TITLE
Login on Microsoft account doesn't work

### ISSUE THREAD

**Issue by SoleGazelle3623** [PojavLauncherTeam/PojavLauncher#4192]
### Describe the bug

Chain validation failed error

### The log file and images/videos

None

### Steps To Reproduce

```markdown
javax.net.ssl.SSLHandshakeException: Chain validation failed
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:229)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:472)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:141)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:79)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.security.cert.CertificateException: Chain validation failed
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:707)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:560)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:628)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:208)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:404)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
	... 18 more
Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:703)
	... 31 more
Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 36 more
	Suppressed: java.security.cert.CertPathValidatorException: Unable to determine revocation status due to network error
		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:562)
		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
		at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
		... 38 more
	Caused by: sun.security.provider.certpath.PKIX$CertStoreTypeException: java.io.IOException: Cleartext HTTP traffic to crl4.digicert.com not permitted
		at sun.security.provider.certpath.URICertStore.engineGetCRLs(URICertStore.java:430)
		at java.security.cert.CertStore.getCRLs(CertStore.java:190)
		at sun.security.provider.certpath.DistributionPointFetcher.getCRL(DistributionPointFetcher.java:245)
		at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:189)
		at sun.security.provider.certpath.DistributionPointFetcher.getCRLs(DistributionPointFetcher.java:121)
		at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:552)
		... 40 more
	Caused by: java.io.IOException: Cleartext HTTP traffic to crl4.digicert.com not permitted
		at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:142)
		at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:469)
		at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
		at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
		at sun.security.provider.certpath.URICertStore.engineGetCRLs(URICertStore.java:396)
		... 45 more
```

### Expected Behavior

When I login with Microsoft account it just doesn't and it says chain validation failed 

### Platform

```markdown
- Device model: latest
- CPU architecture: prob 64
- Android version: 9
- PojavLauncher version: latest
```

### Anything else?

Nothing else

**Comment by HeadyHalilEfe** [comment]
Parent Controls momentz

**Comment by SoleGazelle3623** [comment]
> Parent Controls momentz

I don't have parental control 📱
