### ISSUE TITLE
[BUG] Crashing the game when forge for 1.19.2 <43.2.11> and create mod for 1.19.2

### ISSUE THREAD

**Issue by darkpurpleof** [PojavLauncherTeam/PojavLauncher#4194]
### Describe the bug

Well Since I have the launcher I have installed several mods after having installed at least 43 I discovered "create" I tried to install it but at the start of the game [the application/game] ended with the code -1] this with the renderer Hola, GASES - (ay version , fase) the fastest for me then I had to switch to another renderer wich is virglrenderer - (release 1.7, slow) wich is slower then i tryed again it worked fine but really bad fps (3 or 5) that with the other renderer it was 50 or 80 then try another Renderer that is Java edieditio it works fine too but 3 or 6 fps well hope you can fix it here goes the log

### The log file and images/videos

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2023-05-12 17:18:10
Description: Unexpected error

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83950_(RenderTarget.java:139) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83964_(RenderTarget.java:63) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83941_(RenderTarget.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.enableStencil(RenderTarget.java:316) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:288) ~[Create-Mod-Forge-1.19.2.jar%23155!/:0.5.0.e] {re:classloading}
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:38) ~[Create-Mod-Forge-1.19.2.jar%23155!/:0.5.0.e] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.11.jar%2359!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:161) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83950_(RenderTarget.java:139) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83964_(RenderTarget.java:63) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83941_(RenderTarget.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.enableStencil(RenderTarget.java:316) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:288) ~[Create-Mod-Forge-1.19.2.jar%23155!/:0.5.0.e] {re:classloading}
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:38) ~[Create-Mod-Forge-1.19.2.jar%23155!/:0.5.0.e] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:211) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, Mod Resources, custom-offline-skin.zip, ยง6No+Enchant+Glint+1.19.3.zip, Supplementaries Generated Pack
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2287) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23175!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.11.jar%2359!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2372!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17.0.7-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1689331504 bytes (1611 MiB) / 2654994432 bytes (2532 MiB) up to 2654994432 bytes (2532 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: AArch64 Processor rev 1 (aarch64)
	Identifier: 0x41 Family 8 Model 0xd0a Stepping r0x2p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5873.79
	Virtual memory used (MB): 5405.68
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 1929.34
	JVM Flags: 3 total; -Xms2531M -Xmx2531M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	Window size: 1600x720
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/custom-offline-skin.zip (incompatible), file/ยง6No+Enchant+Glint+1.19.3.zip (incompatible), Supplementaries Generated Pack
	Current Language: English (US)
	CPU: 8x AArch64 Processor rev 1 (aarch64)
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.11.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |ENQUEUE_IM|Manifest: NOSIGNATURE
		handcrafted-forge-1.19.2-2.0.6.jar                |Handcrafted                   |handcrafted                   |2.0.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.19.2-eyemod-2.3.2a.jar                    |EyeMod                        |eyemod                        |2.2                 |ENQUEUE_IM|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.31-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.31       |ENQUEUE_IM|Manifest: NOSIGNATURE
		another_furniture-forge-2.0.2-1.19.jar            |Another Furniture             |another_furniture             |2.0.2-1.19          |ENQUEUE_IM|Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |ENQUEUE_IM|Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |ENQUEUE_IM|Manifest: NOSIGNATURE
		mmlib-1.2.2-1.19.jar                              |Mysterious Mountain Lib       |mmlib                         |1.2.2-1.19          |ENQUEUE_IM|Manifest: NOSIGNATURE
		FarmersRespite-1.19-2.0.jar                       |Farmer's Respite              |farmersrespite                |1.19-2.0            |ENQUEUE_IM|Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.6-6.jar                 |Flywheel                      |flywheel                      |0.6.6-6             |ENQUEUE_IM|Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |ENQUEUE_IM|Manifest: NOSIGNATURE
		Create-Mod-Forge-1.19.2.jar                       |Create                        |create                        |0.5.0.e             |ENQUEUE_IM|Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		citadel-2.1.3-1.19.jar                            |Citadel                       |citadel                       |2.1.3               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ParCool-1.19.2-3.0.1.0-R.jar                      |ParCool!                      |parcool                       |1.19.2-3.0.1.0-R    |ENQUEUE_IM|Manifest: NOSIGNATURE
		resourcefullib-forge-1.19.2-1.1.24.jar            |Resourceful Lib               |resourcefullib                |1.1.24              |ENQUEUE_IM|Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |ENQUEUE_IM|Manifest: NOSIGNATURE
		architectury-6.5.82-forge.jar                     |Architectury                  |architectury                  |6.5.82              |ENQUEUE_IM|Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.0-rc.3+1.19.2-universal.|Minecraft Comes Alive         |mca                           |7.5.0-rc.3+1.19.2   |ENQUEUE_IM|Manifest: NOSIGNATURE
		monobank-1.19.2-1.1.2.jar                         |Monobank                      |monobank                      |1.1.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		additional_lights-1.19-2.1.6.jar                  |Additional Lights             |additional_lights             |2.1.6               |ENQUEUE_IM|Manifest: NOSIGNATURE
		corn_delight-1.0.0-1.19.jar                       |Corn Delight                  |corn_delight                  |1.0.0-1.19          |ENQUEUE_IM|Manifest: NOSIGNATURE
		nofallingblocks-1.19.2-1.1.0.jar                  |No Falling Blocks             |nofallingblocks               |1.1.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		blueprint-1.19.2-6.1.2.jar                        |Blueprint                     |blueprint                     |6.1.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		atmospheric-1.19.2-5.0.0.jar                      |Atmospheric                   |atmospheric                   |5.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		abnormals_delight-1.19.2-4.0.2.jar                |Abnormals Delight             |abnormals_delight             |4.0.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		clayworks-1.19.2-2.0.1.jar                        |Clayworks                     |clayworks                     |2.0.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.11-universal.jar                |Forge                         |forge                         |43.2.11             |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		incubation-1.19-3.0.0.jar                         |Incubation                    |incubation                    |3.0.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		Delightful-1.19.2-3.2.4.jar                       |Delightful                    |delightful                    |3.2.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.3.10.jar                 |Supplementaries               |supplementaries               |1.19.2-2.3.10       |ENQUEUE_IM|Manifest: NOSIGNATURE
		domesticationinnovation-1.6.1-1.19.2.jar          |Domestication Innovation      |domesticationinnovation       |1.6.1               |ENQUEUE_IM|Manifest: NOSIGNATURE
	Flywheel Backend: Uninitialized
	Crash Report UUID: f91cdd96-0ca4-4567-890b-8dd0cdf4e231
	FML: 43.2
	Forge: net.minecraftforge:43.2.11

### Steps To Reproduce

```markdown
1. LAUNCH POJAVLAUNCHER 
2. PLAY MINECRAFT VERSION 1.19.2 WITH FORGE 4.2.11 INSTALLED 
3. 45 MODS LOADED WITH ALL DEPENDENCIES INSTALLED CORRECTLY NO OPTIFINE 
4. GAME OPENS LOADING SCREEN 
5: LOADING STOPS AT 72% WITH ERROR GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
```

### Expected Behavior

the game should have started correctly, on the contrary, it stops at 72% and closes with the code -1 

### Platform

```markdown
- Device model: Samsung a03ub
- CPU architecture: aarch64
- Android version: 13 SDK:33
- PojavLauncher version: Latest on playstore
```

**Comment by root-S7** [comment]
Use latest pojav.apk，remove create and flywheel, they require opengl 3.2, pojav only has 2.1。virgl is mesa to work，so it is very slow(because it uses CPU rendering)。

use mods on your own risk, a lot of them don't work

**Comment by root-S7** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/1948

**Comment by ssaagamemer** [comment]
I Recommend if you use better than 1.17+ use ANGLE one (*if supported)

**Comment by Bel69420** [comment]
You need a Adreno device because mali doesn't support Create with GL4ES.

**Comment by Bel69420** [comment]
and PowerVR

**Comment by Bel69420** [comment]
maybe PowerVR does support? I don't know.

**Comment by GaucovyAero** [comment]
create only works on snapdragon devices on gl4es
