### ISSUE TITLE
At selecting jre 8 

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#422]
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1008)
	at net.kdt.pojavlaunch.PojavLoginActivity.uncompressTarXZ(PojavLoginActivity.java:460)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:349)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:28)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:210)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:151)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by khanhduytran0** [comment]
Which jre8 build?

**Comment by RockingDev9** [comment]
> Which jre8 build?

JRE 8

**Comment by ghost** [comment]
jre8-arm64-20201104-release.tar.xz

**Comment by khanhduytran0** [comment]
Maybe try clear app data?

**Comment by khanhduytran0** [comment]
Use this jre8 build https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch/suites/1552671546/artifacts/27770266
