### ISSUE TITLE
Freezing the game after the error Fabric 1 18 2

### ISSUE THREAD

**Issue by Miros77** [PojavLauncherTeam/PojavLauncher#4225]
### Describe the bug

I can't run Fabric loader 1 18 2(vanilla starts, reinstalled the game(I tried it several times))

### The log file and images/videos

-

### Steps To Reproduce

```markdown
Loading Minecraft 1.18.2 with Fabric Loader 0.14.19
[20:09:45] [main/ERROR]: Uncaught exception in thread "main"
java.lang.IllegalArgumentException: Unsupported class file major version 21845
at org.objectweb.asm.ClassReader.(ClassReader.java:199) ~[asm-9.4.jar:9.4]
at org.objectweb.asm.ClassReader.(ClassReader.java:180) ~[asm-9.4.jar:9.4]
at org.objectweb.asm.ClassReader.(ClassReader.java:166) ~[asm-9.4.jar:9.4]
at org.objectweb.asm.ClassReader.(ClassReader.java:287) ~[asm-9.4.jar:9.4]
at net.fabricmc.loader.impl.game.patch.GameTransformer.lambda$locateEntrypoints$0(GameTransformer.java:82) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.game.minecraft.patch.EntrypointPatch.process(EntrypointPatch.java:77) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.game.patch.GameTransformer.locateEntrypoints(GameTransformer.java:92) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:341) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.14.19.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.19.jar:?]
```

### Expected Behavior

-

### Platform

```markdown
- Device model: Redmi 4x 
- CPU architecture: 64
- Android version: 11 (an error occurs on the custom and factory firmware(Android7))
- PojavLauncher version: latest
```

### Anything else?

-

**Comment by GaucovyAero** [comment]
try using the latest play store version now
