### ISSUE TITLE
[Microsoft account] i can't enter in my Microsoft account.

### ISSUE THREAD

**Issue by Lunaewe** [PojavLauncherTeam/PojavLauncher#4255]
### Describe the bug

It shows me this:java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:231)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### The log file and images/videos

Nope

### Steps To Reproduce

```markdown
???
```

### Expected Behavior

I expected to open my Microsoft account 

### Platform

```markdown
- Device model: Lenovo Tab 10 HD
- CPU architecture: ????
- Android version: yes
- PojavLauncher version: 1.16.5
```

### Anything else?

Nope

**Comment by Mam1241** [comment]
Good afternoon, I have a lump (a sitevaya game is not available to check the subclusions of the makrasovt) why does it squeak like that if mina called everything was normal?and all worked with my nickname

**Comment by GaucovyAero** [comment]
log into minecraft.net first
