### ISSUE TITLE
Can't run latest

### ISSUE THREAD

**Issue by bugger09** [PojavLauncherTeam/PojavLauncher#426]
Error when i open 1.16.4:
java.io.FileNotFoundException: /data/data/net.kdt.pojavlaunch/jre_runtime/release: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:755)
	at net.kdt.pojavlaunch.MainActivity.checkJavaArchitecture(MainActivity.java:961)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:951)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:28)
	at net.kdt.pojavlaunch.MainActivity$13$1.run(MainActivity.java:717)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7727)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 8 more

**Comment by khanhduytran0** [comment]
@LegacyGamerHD stop close instantly

**Comment by khanhduytran0** [comment]
@bugger09 which runtime you used?

**Comment by WesleyVanNeck** [comment]
> @bugger09 which runtime you used?

probely  pojav 3.2 with java 8  or  the stupid mc in the box run time

**Comment by artdeell** [comment]
he used mcina runtime

вт, 1 дек. 2020 г., 19:23 LegacyGamerHD <notifications@github.com>:
