### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by xiaogezi1600** [PojavLauncherTeam/PojavLauncher#4274]
### Describe the bug

![Screenshot_2023-06-15-06-41-07-506_PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher/assets/125271342/18652366-4912-4aad-9b9c-9ab5ed85c863)
![Screenshot_2023-06-15-06-41-07-506_PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher/assets/125271342/52d082b2-5704-455e-a2a6-664a6dcbf01d)

### The log file and images/videos

PojavLauncher crash report
 - Time: Jun 15, 2023 06:40:52
 - Device: delta DT1902A
 - Android version: 10
 - Crash stack trace:
 - Launcher version: LOCAL-20230508
java.lang.IllegalArgumentException: You must pass a valid uri and observer
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	at android.content.ContentResolver.query(ContentResolver.java:946)
	at android.content.ContentResolver.query(ContentResolver.java:881)
	at android.content.ContentResolver.query(ContentResolver.java:837)
	at net.kdt.pojavlaunch.Tools.getFileName(Tools.java:811)
	at net.kdt.pojavlaunch.Tools.lambda$launchModInstaller$11(Tools.java:892)
	at net.kdt.pojavlaunch.Tools$$ExternalSyntheticLambda11.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
1.start pojavlauncher,2.install .JAR 3.use fabric installer
```

### Expected Behavior

i want i can install fabric and run it

### Platform

```markdown
- Device model: delta DT1902A
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: 3.3.1.1_rei_20210206
- CPU: Qualcomm Snapdragon 855 plus
```

**Comment by lolmeme09** [comment]
Do you have connection ? This is most likely the reason, if u want to play u now need internet (at least for me), this includes installing .jar, joining any version without internet, for me it does that if i don't have internet it's annoying and the worst feature if it is.

**Comment by xiaogezi1600** [comment]
oh bro,maybe my issue is not complete, I belong to the state of the Internet, maybe I have to check the problem of my mobile phone・_・? I use Smartisan mobile phone, a brand that has gone bankrupt, it is a Chinese brand, we  The founder of Smartisan is called Teacher Luo, because his name is Luo Yonghao, u can search it

**Comment by GaucovyAero** [comment]
use the latest play store version
