### ISSUE TITLE
I can't install on my device Mi 8 Android 10 fabric 

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#428]
latestlog.txt:--------- beginning of system
--------- beginning of main
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/jli/libjli.so success
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/server/libjvm.so success
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libverify.so success
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libjava.so success
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnet.so success
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libnio.so success
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt.so success
S/LaunchJVM( 8477): dlopen /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_headless.so success
S/LaunchJVM( 8477): dlopen /data/app/net.kdt.pojavlaunch-SLbrpZkBTmxtQozchTKW5A==/lib/arm64/libopenal.so success
S/LaunchJVM( 8477): dlopen /data/app/net.kdt.pojavlaunch-SLbrpZkBTmxtQozchTKW5A==/lib/arm64/libgl04es.so success
S/LaunchJVM( 8477): Done processing args
S/LaunchJVM( 8477): Found JLI lib
S/LaunchJVM( 8477): Calling JLI_Launch
S/jrelog  ( 8477): Loading Fabric Installer: 0.6.1.51
S/jrelog  ( 8477): 
S/jrelog  ( 8477): Using latest loader version
S/jrelog  ( 8477): 
S/jrelog  ( 8477): Installing [minecraft with fabric 0.10.8
S/jrelog  ( 8477): 
S/jrelog  ( 8477): Done
S/jrelog  ( 8477): 
S/jrelog  ( 8477): Creating profile
S/jrelog  ( 8477): 
S/jrelog  ( 8477): Exception in thread "main" 
S/jrelog  ( 8477): java.lang.RuntimeException: Failed to install Client
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at net.fabricmc.installer.Main.main(Main.java:102)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): Caused by: java.io.IOException: Is a directory
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.FileDispatcherImpl.read(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.FileChannelImpl.read(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.ChannelInputStream.read(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.ChannelInputStream.read(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/sun.nio.ch.ChannelInputStream.read(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/java.nio.file.Files.read(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at java.base/java.nio.file.Files.readAllBytes(Unknown Source)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at net.fabricmc.installer.util.Utils.readFile(Utils.java:97)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at net.fabricmc.installer.client.ProfileInstaller.setupProfile(ProfileInstaller.java:38)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at net.fabricmc.installer.client.ClientHandler.installCli(ClientHandler.java:99)
S/jrelog  ( 8477): 
S/jrelog  ( 8477): 	at net.fabricmc.installer.Main.main(Main.java:100)
S/jrelog  ( 8477): 
Java Exit code: 1
S/LaunchJVM( 8477): Freeing args
S/LaunchJVM( 8477): Free done

**Comment by khanhduytran0** [comment]
> Installing [minecraft with fabric 0.10.8

You entered a wrong Minecraft version (`[minecraft`).

**Comment by yanluol** [comment]
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/versions/[minecraft/[minecraft.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:635)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:315)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:47)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/gam

**Comment by khanhduytran0** [comment]
You entered an invalid Minecraft version!! Please replace it with a version you want, not ~~[minecraft~~

**Comment by yanluol** [comment]
Or is it broken
java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/versions/[1.16.4]/[1.16.4].json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:635)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.findVersion(MinecraftDownloaderTask.java:315)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:47)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/games/.minecraft/versions/[1.16.4]/[1.16.4].json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:713)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:578)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 13 more

**Comment by khanhduytran0** [comment]
Do not put to [ ]

**Comment by yanluol** [comment]
Yes, thank you. But how to switch mod

**Comment by khanhduytran0** [comment]
?

For add mods put them to mods folder. Note that on some devices, no Fabric mods will be loaded.

**Comment by yanluol** [comment]
Put mod into mods folder, the game has no change. Mod is sodium

**Comment by artdeell** [comment]
Log?

вс, 29 нояб. 2020 г., 12:15 yanluol <notifications@github.com>:

**Comment by pstube** [comment]
It’s Korean, but please refer to my YouTube
https://youtu.be/NM2EElCDqRY

**Comment by khanhduytran0** [comment]
Fabric known issue: on some device it ignored load all mods.

**Comment by khanhduytran0** [comment]
Also main problem solved, closing.
