### ISSUE TITLE
Download File Error

### ISSUE THREAD

**Issue by SkeveYT** [PojavLauncherTeam/PojavLauncher#4281]
### Describe the bug

java.lang.NullPointerException: Attempt to read from field 'java.lang.String net.kdt.pojavlaunch.value.MinecraftLibraryArtifact.path' on a null object reference in method 'void net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(android.app.Activity, net.kdt.pojavlaunch.JMinecraftVersionList$Version, java.lang.String)'
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:144)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:53)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

![Uploading Screenshot_2023-06-19-19-02-11-99_67a64f1fc1b88908dad3392f76c1969b.jpg…]()
whats This?

### Steps To Reproduce

```markdown
1. I download the newest version on github 
2.yes this i cant download versions
3. I tried anything, try to using data/wifi 
4.and boom it sucks Eeeeeeee
```

### Expected Behavior

I Expect The Game To Download And It Erorr'D

### Platform

```markdown
- Device model: RealMe 10
- CPU architecture: MediaTek G90
- Android version: 12
- PojavLauncher version: Latest Version On GitHub
```

### Anything else?

Nothing Else Just Fix It Fast /:

**Comment by SkeveYT** [comment]
Grrr im mad i cant play Eejehehshhaehbaja

**Comment by ADWAIT987** [comment]
Me to ;(

**Comment by GaucovyAero** [comment]
use the play store version
