### ISSUE TITLE
[BUG] <error when installing forge (any) >

### ISSUE THREAD

**Issue by Prostop194** [PojavLauncherTeam/PojavLauncher#4299]
### Describe the bug

my friend wanted to install forge 1.5.2 and he got an error when he downloaded forge from a normal site 
![IMG-20230627-WA0000](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/dd789408-d2f7-40b2-a8c3-fe79c39244d4)
![IMG-20230627-WA0001](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/683093a5-a7a5-45a7-be0a-f5e26a53cf3c)
![IMG-20230627-WA0002](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/a3bc2088-07bb-40b9-854f-b12d534067f2)
![IMG-20230627-WA0004](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/88115540-0816-4607-9410-08d775206be1)
![IMG-20230627-WA0003](https://github.com/PojavLauncherTeam/PojavLauncher/assets/121510853/f215d541-0938-4cb0-bd2c-9291f94ec3fb)

### The log file and images/videos

.

### Steps To Reproduce

```markdown
.
```

### Expected Behavior

.

### Platform

```markdown
- Device model: Samsung Galaxy A52 
- CPU architecture: 
- Android version: 13
- PojavLauncher version:
```

### Anything else?

.

**Comment by Prostop194** [comment]
java.lang.SecurityException: com.android.providers.downloads has no access to content://media/external_primary/file/1000026725
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3023)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at net.kdt.pojavlaunch.BaseLauncherActivity.lambda$onActivityResult$4$BaseLauncherActivity(BaseLauncherActivity.java:297)
	at net.kdt.pojavlaunch.-$$Lambda$BaseLauncherActivity$nZAD31xvWetbtgUAsrV1kIwVluM.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by GaucovyAero** [comment]
select the file via internal storage - download, not just "downloads"
