### ISSUE TITLE
[BUG] <Error In Forge 1.17.1>

### ISSUE THREAD

**Issue by LenaDedi** [PojavLauncherTeam/PojavLauncher#4300]
### Describe the bug

Plis Fix Bugs Forge 1.17.1 In Versi 
1.17.1-forge-37.0.44:

Exception in thread "main" 
java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:96)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
	at cpw.mods.securejarhandler@0.9.46/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:60)

Java Exit Code: 1

### The log file and images/videos
latestlog.txt

### Steps To Reproduce

```markdown

```

### Expected Behavior
😀

### Platform

```markdown
- Device model: OPPO A77s
- CPU architecture: 
- Android version: 13
- PojavLauncher version:
```

### Anything else?
🙏

**Comment by GaucovyAero** [comment]
missing log file
