### ISSUE TITLE
[BUG] Deleting the only profile (Unknown) causes Pojav Launcher to crash every time (Android)[BUG] <Short description>

### ISSUE THREAD

**Issue by ErrorOliver** [PojavLauncherTeam/PojavLauncher#4325]
### Describe the bug

Opening Pojav Launcher causes it to crash once the bug is in affect.

### The log file and images/videos

android.view.InflateException: Binary XML file line #73 in net.kdt.pojavlaunch.debug:layout/fragment_launcher: Binary XML file line #73 in net.kdt.pojavlaunch.debug:layout/fragment_launcher: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: android.view.InflateException: Binary XML file line #73 in net.kdt.pojavlaunch.debug:layout/fragment_launcher: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1145)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
	at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1924)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at net.kdt.pojavlaunch.LauncherActivity.onStart(LauncherActivity.java:184)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8616)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4204)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.ClassCastException: net.kdt.pojavlaunch.profiles.ProfileAdapterExtra cannot be cast to java.lang.String
	at com.kdt.mcgui.mcVersionSpinner.setSelection(mcVersionSpinner.java:77)
	at com.kdt.mcgui.mcVersionSpinner.setProfileSelection(mcVersionSpinner.java:68)
	at com.kdt.mcgui.mcVersionSpinner.init(mcVersionSpinner.java:99)
	at com.kdt.mcgui.mcVersionSpinner.<init>(mcVersionSpinner.java:48)
	... 36 more

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Delete all the profiles so there is none by clicking on the edit profile button of the profile and pressing 'Delete'.
```

### Expected Behavior

I expect it to not crash every time it opens.

### Platform

```markdown
- Device model: SM-A715F/DS
- CPU architecture: Not sure how to obtain this information.
- Android version: 13
- PojavLauncher version: dahlia-20230702-a7444aa-v3_openjdk
```

### Anything else?

The install is clean.

I'm sorry but I can't seem to get latestlog.txt because it says I have to connect my phone to my pc because of android restrictions to view the folder and I do not have access to my PC at the moment. I got latestcrash.txt though.

**Comment by GaucovyAero** [comment]
delete launcher-profiles.json in your .minecraft folder, be sure to not delete all your profiles, otherwise this will happen again
