### ISSUE TITLE
Crash when creating an account

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#435]
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.PojavLauncherActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8154)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3738)
	at java.util.Arrays.asList(Arrays.java:3725)
	at android.widget.ArrayAdapter.<init>(ArrayAdapter.java:168)
	at net.kdt.pojavlaunch.PojavLauncherActivity.viewInit(PojavLauncherActivity.java:161)
	at net.kdt.pojavlaunch.PojavLauncherActivity.onCreate(PojavLauncherActivity.java:73)
	at android.app.Activity.performCreate(Activity.java:7963)
	at android.app.Activity.performCreate(Activity.java:7952)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
	... 11 more

**Comment by WesleyVanNeck** [comment]
Use your email instead of user name
