### ISSUE TITLE
[BUG] Forge crashes with create

### ISSUE THREAD

**Issue by Blobst** [PojavLauncherTeam/PojavLauncher#4355]
### Describe the bug

Your boat drown with number -1, check debris for more detail

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/12014627/latestlog.txt)

### Steps To Reproduce

```markdown
1. Open PojavLauncher
2. Install Forge (any versions?)
3. Import create mod
4. run a world
5. Play the mod :)

```

### Expected Behavior

[14:33:04] [main/INFO]: Found mod file fmlcore-1.20.1-47.1.0.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6050462a
[14:33:04] [main/INFO]: Found mod file javafmllanguage-1.20.1-47.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6050462a
[14:33:04] [main/INFO]: Found mod file lowcodelanguage-1.20.1-47.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6050462a
[14:33:04] [main/INFO]: Found mod file mclanguage-1.20.1-47.1.0.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6050462a
[14:33:04] [main/INFO]: Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6050462a
[14:33:04] [main/INFO]: Found mod file forge-1.20.1-47.1.0-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@6050462a
[14:33:04] [main/INFO]: No dependencies to load found. Skipping!
[14:33:06] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/assets, --uuid, 00000000000000000000000000000000, --username, Microdevy, --assetIndex, 5, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release]
[14:33:07] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at net.minecraft.SystemReport.m_143569_(SystemReport.java:75) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143516_(SystemReport.java:82) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143535_(SystemReport.java:75) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143564_(SystemReport.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143516_(SystemReport.java:82) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.<init>(SystemReport.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.CrashRe
port.<init>(CrashReport.java:31) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.CrashReport.m_127529_(CrashReport.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.20.1-forge-47.1.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cach
e/JNA/temp/jna17708748539139190833.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna17708748539139190833.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace" [in thread "main"]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.12.1.jar%23108!/:5.12.1 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:93) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	... 30 more
[14:33:07] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at net.minecraft.SystemReport.m_143545_(SystemReport.java:77) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143516_(SystemReport.java:82) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143535_(SystemReport.java:77) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143564_(SystemReport.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143516_(SystemReport.java:82) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.<init>(SystemReport.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.CrashReport.<init>(CrashReport.java:31) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.CrashReport.m_127529_(CrashReport.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.20.1-forge-47.1.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHand
ler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native [in thread "main"]
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar%2382!/:6.
2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at net.minecraft.SystemReport.m_143569_(SystemReport.java:75) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143516_(SystemReport.java:82) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143535_(SystemReport.java:75) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	... 21 more
INFO: 
Initialized TensorFlow Lite runtime.
[14:33:15] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 443 milliseconds
[14:33:19] [Render thread/WARN]: Assets URL 'union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23124!/assets/.mcassetsroot' uses unexpected schema
[14:33:19] [Render thread/WARN]: Assets URL 'union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23124!/data/.mcassetsroot' uses unexpected schema
[14:33:19] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:33:19] [Render thread/INFO]: Setting user: Microdevy
[14:33:20] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[14:33:20] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[14:33:20] [modloading-worker-0/INFO]: Forge mod loading, version 47.1.0, for MC 1.20.1 with MCP 20230612.114412
[14:33:20] [modloading-worker-0/INFO]: MinecraftForge v47.1.0 Initialized
[14:33:23] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar%2393!/:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar%2393!/:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar%2393!/:?]
	at net.minecraft.client.GameNarrator.<init>(GameNarrator.java:19) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:553) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.1.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?
]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:90) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar%2393!/:?]
	... 20 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna17708748539139190833.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna17708748539139190833.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace" [in thread "main"]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.12.1.jar%23109!/:5.12.1 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.12.1.
jar%23108!/:5.12.1 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:93) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar%2382!/:6.2.2]
	at net.minecraft.SystemReport.m_143569_(SystemReport.java:75) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143516_(SystemReport.java:82) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143535_(SystemReport.java:75) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143564_(SystemReport.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.m_143516_(SystemReport.java:82) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.SystemReport.<init>(SystemReport.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.CrashReport.<init>(CrashReport.java:31) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.CrashReport.m_127529_(CrashReport.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23124!/:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.20.1-forge-47.1.0.jar:?]
	... 15 more
[14:33:23] [Render thread/INFO]: Reloading ResourceManager: vanilla, mod_resources
[14:33:23] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[14:33:23] [Worker-Main-7/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[14:33:25] [Forge Version Check/INFO]: [forge] Found status: UP_TO_DATE Current: 47.1.0 Target: null
[14:33:30] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[14:33:30] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[14:33:31] [Render thread/INFO]: OpenAL initialized on device OpenSL
[14:33:31] [Render thread/INFO]: Sound engine started
[14:33:31] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/blocks.png-atlas
[14:33:31] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/signs.png-atlas
[14:33:31] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[14:33:31] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[14:33:31] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/armor_trims.png-atlas
[14:33:31] [Render thread/INFO]: Created: 128x64x0 minecraft:textures/atlas/decorated_pot.png-atlas
[14:33:31] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[14:33:31] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:33:31] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[14:33:32] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
version string: 150 coreversion string: 150 coreversion string: 150 coreversion string: 150 coreversion string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string:
 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version st
[14:33:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:33:33] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:33:33] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:33:33] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id

### Platform

```markdown
- Device model: Huawei p40 lite JNY-LX1
- CPU architecture: Octa-core Armv8-A (Harvard)
- Android version: non android phone
- PojavLauncher version: Version dahlia-20230709-fcafb3e-v3_openjdk
```

**Comment by Forever2397** [comment]
you only switch the renderer to angle if it crashes

**Comment by Bel69420** [comment]
Lemme explain to you, your phone does not support Create mod.Why? because mali is missing 1 extension and that's it GL_OES_framebuffer_object

**Comment by Bel69420** [comment]
Only Angle,Zink and Virgl support create mod

**Comment by Bel69420** [comment]
if your phone doesn't support vulkan you can't use Angle and Zink

**Comment by Bel69420** [comment]
Only Adreno GPU support create (but the fps still the same as Virgl because flywheel doesn't work with GL4ES)

**Comment by Blobst** [comment]
> if your phone doesn't support vulkan you can't use Angle and Zink 


Hey um I switched to angle and it worked!

**Comment by Bel69420** [comment]
fact that zink is faster than virgl but it has a slowdown in fps
