### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ImadeRamadany** [PojavLauncherTeam/PojavLauncher#437]
java.lang.UnsatisfiedLinkError: org.lwjgl.glfw.GLFW.nglfwSetFramebufferSizeCallback(JJ)J
	at org.lwjgl.glfw.GLFW.nglfwSetFramebufferSizeCallback(Native Method)
	at org.lwjgl.glfw.GLFW.glfwSetFramebufferSizeCallback(GLFW.java:685)
	at dhh.<init>(SourceFile:112)
	at eds.a(SourceFile:21)
	at dmh.<init>(SourceFile:457)
	at net.minecraft.client.main.Main.main(SourceFile:177)

Pls Help Me

**Comment by khanhduytran0** [comment]
Use latest build
