### ISSUE TITLE
[BUG] Can't play optifine, Forge , Dll

### ISSUE THREAD

**Issue by McTutorialID23** [PojavLauncherTeam/PojavLauncher#4370]
### Describe the bug

everyone wants to play optifine, fabric, or Forge versions of Minecraft, Always errors

Log :
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'int net.kdt.pojavlaunch.JMinecraftVersionList$JavaVersionInfo.majorVersion' on a null object reference
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:752)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:72)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:53)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to read from field 'int net.kdt.pojavlaunch.JMinecraftVersionList$JavaVersionInfo.majorVersion' on a null object reference
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:747)
	... 6 more

Even though I have downloaded the vanilla version, and for my account I use a premium account and the internet signal is safe and smooth without lag.

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/130224195/191e7892-7997-4c9a-9318-84bea97ef7c6

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Install Minecraft vanilla
3. Install optifine, fabric, Forge version
4. Play Minecraft with optifine, Forge, fabric
5. Error Because of something weird
```

### Expected Behavior

I hope this bug or problem can be resolved quickly, and one more thing please add the Zink and vgpu renderers so that there are 5 renderers.

### Platform

```markdown
- Device model: Android
- CPU architecture: aarch64
- Android version: 10
- PojavLauncher version: Latest version from github
```

### Anything else?

-

**Comment by MegaGaming** [comment]
I Cant play optifine/forge/Fabric 
Its Show this :
Log :
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'int net.kdt.pojavlaunch.JMinecraftVersionList$JavaVersionInfo.majorVersion' on a null object reference
at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:752)
at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:72)
at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:53)
at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to read from field 'int net.kdt.pojavlaunch.JMinecraftVersionList$JavaVersionInfo.majorVersion' on a null object reference
at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:747)
... 6 more

This is my Device

Platform
- Device model: Android
- CPU architecture: aarch64
- Android version: 12
- PojavLauncher version: Latest version from

**Comment by GaucovyAero** [comment]
downgrade to the play store version, or to an older github version
