### ISSUE TITLE
[BUG] Unable to use "INSTALL .JAR" and Modded Version

### ISSUE THREAD

**Issue by Flyrder** [PojavLauncherTeam/PojavLauncher#4374]
### Describe the bug

Unable to use "INSTALL .JAR" and Modded Version

### The log file and images/videos

Turned off
![1689407141029](https://github.com/PojavLauncherTeam/PojavLauncher/assets/106471753/80cfcb93-7648-416f-a21b-98dbd45ade23)

### Steps To Reproduce

```markdown
1.Add a newest JDK 8
(jdk8 arm64 20230504 release)
2.Install fabric by clicking "INSTALL .JAR"
3.It will crash
```

### Expected Behavior

It won't crash and keep the installation

### Platform

```markdown
- Device model: Xiaomi Pad 5 Pro 6/128G
- CPU architecture: aarch61
- Android version: 11
- PojavLauncher version: 
Package Name：net.kdt.pojavlaunch.debug
Version Name：dahlia-20230713-75850de-feat/automatic_drawer_actuation
Version Number：9939222
```

### Anything else?

It will get two different logs when i turn on / off about "Sandbox .jar installer"

**Comment by Flyrder** [comment]
```java
Turned off logs
Info: Java arguments: [-Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=net.java.openjdk.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment, -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.beta/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.beta/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.beta/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar, -jar, /data/user/0/net.kdt.pojavlaunch.beta/cache/fabric-installer-0.11.2 (1).jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.beta/cache
Added custom env: AWTSTUB_WIDTH=2561
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~2nBHv43VNErRi78Ublazkg==/net.kdt.pojavlaunch.beta-zVZKfXzAGIB1eLQ49Qhtsg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.beta/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.beta/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~2nBHv43VNErRi78Ublazkg==/net.kdt.pojavlaunch.beta-zVZKfXzAGIB1eLQ49Qhtsg==/lib/arm64
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.beta/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1600
WARNING: linker: Warning: "/data/app/~~2nBHv43VNErRi78Ublazkg==/net.kdt.pojavlaunch.beta-zVZKfXzAGIB1eLQ49Qhtsg==/lib/arm64/libawt_headless.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
--------- beginning of system

--------- beginning of crash

--------- beginning of main

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/jre/lib/aarch64/libnio.so: dlopen failed: library "libnet.so" not found: needed by /data/data/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/jre/lib/aarch64/libnio.so in namespace classloader-namespace
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
	at java.lang.Runtime.loadLibrary0(Runtime.java:843)
	at java.lang.System.loadLibrary(System.java:1136)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:578)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:576)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:576)
	at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
	at sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:46)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:39)
	at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
	at sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:63)
	at java.io.FilePermission.<clinit>(FilePermission.java:191)
	at sun.net.www.protocol.file.FileURLConnection.getPermission(FileURLConnection.java:225)
	at java.net.URLClassLoader.getPermissions(URLClassLoader.java:671)
	at sun.misc.Launcher$AppClassLoader.getPermissions(Launcher.java:360)
	at java.security.SecureClassLoader.getProtectionDomain(SecureClassLoader.java:206)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
Java Exit code: 1
Success in th' ship
I/jrelog  (20319): dlopen /data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/jli/libjli.so success
I/jrelog  (20319): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (20319): dlopen /data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/client/libjvm.so failed: dlopen failed: library "/data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/client/libjvm.so" not found
I/jrelog  (20319): dlopen libverify.so failed: dlopen failed: library "libverify.so" not found
I/jrelog  (20319): dlopen libjava.so failed: dlopen failed: library "libjava.so" not found
I/jrelog  (20319): dlopen libnet.so failed: dlopen failed: library "libnet.so" not found
I/jrelog  (20319): dlopen libnio.so failed: dlopen failed: library "libnio.so" not found

I/jrelog  (20319): dlopen libawt.so failed: dlopen failed: library "libawt.so" not found
I/jrelog  (20319): dlopen /data/app/~~2nBHv43VNErRi78Ublazkg==/net.kdt.pojavlaunch.beta-zVZKfXzAGIB1eLQ49Qhtsg==/lib/arm64/libawt_headless.so success
I/jrelog  (20319): dlopen /data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/libfreetype.so success
I/jrelog  (20319): dlopen libfontmanager.so failed: dlopen failed: library "libfontmanager.so" not found
I/jrelog  (20319): dlopen /data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/libjawt.so failed: dlopen failed: library "libawt.so" not found: needed by /data/data/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/libjawt.so in namespace classloader-namespace
I/jrelog  (20319): dlopen /data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/jli/libjli.so success
I/jrelog  (20319): dlopen /data/user/0/net.kdt.pojavlaunch.bet
a/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/libfreetype.so success
I/jrelog  (20319): dlopen /data/user/0/net.kdt.pojavlaunch.beta/runtimes/jdk8-arm64-20230504-release.tar.xz/lib/aarch64/libawt_xawt.so success
I/jrelog  (20319): dlopen /data/app/~~2nBHv43VNErRi78Ublazkg==/net.kdt.pojavlaunch.beta-zVZKfXzAGIB1eLQ49Qhtsg==/lib/arm64/libopenal.so success
I/jrelog  (20319): Done processing args
I/jrelog  (20319): Found JLI lib
I/jrelog  (20319): Calling JLI_Launch
I/jrelog  (20319): Going to free args
I/jrelog  (20319): Free done


```

**Comment by Flyrder** [comment]
**PROBLEM SOLVED
USE THE DEFAULT JAVA 8 AND INSTALL THE MOD LOADER**
