### ISSUE TITLE
[BUG] wont login on my microsoft account

### ISSUE THREAD

**Issue by remfaoe** [PojavLauncherTeam/PojavLauncher#4378]
### Describe the bug

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/139686267/26e3d3e8-4ba8-4370-a0ca-6da11ece7018

### Steps To Reproduce

```markdown
1 open pojavlauncher
2 press add account
3 login with microsoft account
```

### Expected Behavior

I expect it to login on my acc

### Platform

```markdown
- Device model: Infinix ZERO ULTRA
- CPU architecture: Dimensity 920
- Android version: 12
- PojavLauncher version: latest release
```

**Comment by ghost** [comment]
Do you own Minecraft: Java Edition on the account you are trying to sign in on?

**Comment by GaucovyAero** [comment]
buy minecraft

**Comment by amir74711** [comment]
Me aparece el error del video

**Comment by PGdarlyson22991** [comment]
No cosigo

**Comment by Ibrahim9788** [comment]
Iiiiii

**Comment by PGdarlyson22991** [comment]
Iiiiii

**Comment by PGdarlyson22991** [comment]
> Iiiiii

Iiiii

**Comment by PGdarlyson22991** [comment]
Iiiii

Em seg., 9 de out. de 2023 11:46, Ibrahim ***@***.***>
escreveu:

**Comment by Sourovthenoob** [comment]
It shows login error everytime when I login my Microsoft account :(

**Comment by ghost266** [comment]
nem megy hiába mindent meg csináltam

**Comment by GaucovyAero** [comment]
> It shows login error everytime when I login my Microsoft account :(

> nem megy hiába mindent meg csináltam

buy minecraft guys

**Comment by Johnmatthewberecio** [comment]
Why i can't login

**Comment by RajminecGamer70** [comment]
How to fix

**Comment by GaucovyAero** [comment]
@Johnmatthewberecio @RajminecGamer70 buy minecraft

**Comment by jdhhsvgvv** [comment]
> java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by jdhhsvgvv** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by GokuSonOf** [comment]
I am trying don't work

**Comment by Dwaipayan2010** [comment]
Please fixed the launcher I don't sign in

**Comment by GokuSonOf** [comment]
Is it working now?

**Comment by IndianBartonka** [comment]
![Screenshot_2023-12-03-17-06-04-524_com android chrome](https://github.com/PojavLauncherTeam/PojavLauncher/assets/68228599/6cd4069e-9e5a-4fa3-9d17-730d90e68c81)
Me also dont have Minecraft XD?

**Comment by Liviu397** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by ghost** [comment]
Please help
![Screenshot_20231214-235608](https://github.com/PojavLauncherTeam/PojavLauncher/assets/67903447/2e300133-8688-4cc0-8f45-a03021b8ae70)

**Comment by IndianBartonka** [comment]
> Please help ![Screenshot_20231214-235608](https://private-user-images.githubusercontent.com/67903447/290672589-2e300133-8688-4cc0-8f45-a03021b8ae70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NjAzODUsIm5iZiI6MTcwMjY2MDA4NSwicGF0aCI6Ii82NzkwMzQ0Ny8yOTA2NzI1ODktMmUzMDAxMzMtODY4OC00Y2MwLThmNDUtYTAzMDIxYjhhZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE3MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliY2RhZmIwOGJkNGY4YWQ3MGFkODdiMWM2MThkMmY3NjAxYWQ3NjlhNDc1M2RiZmY5NGM4ZmM3MmQ5ODAzMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q2xkQDFi1R9VscwIp0GhNPdmNwXq0VaazmtvzZuksUc)

Login bro in Minecraft.net

**Comment by Nshdhdjdj** [comment]
Hai bro keep it up bro by bro

**Comment by Zulfikay** [comment]
😭😭😭😭😭😭😭😭

**Comment by Xhiyrrhgry** [comment]
AM NOT SIG AN PUGAF LANSHER

**Comment by daviwallacy** [comment]
Noooo

**Comment by blockgaming1410** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Alanidklol** [comment]
i dont have money to buy minecraft what do i do

**Comment by Mahamedsdg** [comment]
You can close the wifi the multiplayer will unlock when you click on it turn on wifi



🐐👍
Thats the onely way to play multiplayer

**Comment by Pipocadoce816** [comment]
buavuabava

**Comment by Kyy443** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by azaxlite** [comment]
> ![Tangkapan layar_2023-12-03-17-06-04-524_com android chrome](https://private-user-images.githubusercontent.com/68228599/287532272-6cd4069e-9e5a-4fa3-9d17-730d90e68c81.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzE2ODksIm5iZiI6MTczMjAzMTM4OSwicGF0aCI6Ii82ODIyODU5OS8yODc1MzIyNzItNmNkNDA2OWUtOWU1YS00ZmEzLTlkMTctNzMwZDkwZTY4YzgxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1NDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNjNkOWFlN2IxOTczNDkyNjQwMmM3ZmJkMDYyNDM3MWVjNzkyODNiNjA2ODZhMjk3OGI1YmRkMzEwZWY5MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3bq0CtjbkU0OgMyzPyMIbEIHH6iOAIBeCqssK-kXYDg) Saya juga tidak punya Minecraft XD?

How?

**Comment by Max4079** [comment]
Me sucede lo mismo, como se puede solucionar??

**Comment by Max4079** [comment]
- Device model: Motorola g34
- CPU architecture: nose que es
- Android version: 12
- PojavLauncher version: latest release
