### ISSUE TITLE
[BUG] <Short description>Don't Launch Labymod4

### ISSUE THREAD

**Issue by ht7813** [PojavLauncherTeam/PojavLauncher#4393]
### Describe the bug

Application exit with code 1
library"libpthread.so.0" not found
Renderer:Virgl
Account Type:Local

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-20230713-c65ef07-feat/lwjgl-3.3.1
Info: Architecture: arm64
Info: Device model: OPPO PBBM30
Info: API version: 27
Info: Selected Minecraft version: LabyMod-4-1.18-808c29e2
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=1520
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch.debug-VHwLP7gnTIeiEmdSP4ALvQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230504-release.tar.xz/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230504-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230504-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch.debug-VHwLP7gnTIeiEmdSP4ALvQ==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230504-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=720
OpenJDK 64-Bit Server VM warning: getcpu(2) system call not supported by kernel
2023-07-22 09:56:38,127 main ERROR appender Console has no parameter that matches element Policies
[09:56:39] [main/INFO]: Loading tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
[09:56:39] [main/INFO]: Using primary tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
[09:56:39] [main/INFO]: Calling tweak class net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
2023-07-22 09:56:41,877 main ERROR appender Console has no parameter that matches element Policies
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-linux-arm64.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-linux-arm64.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-linux-arm64.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-linux-arm64.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-linux-arm64.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-linux-arm64.jar
[09:56:43] [main/INFO]: Library /storage/emulated/0/games/PojavLauncher/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-linux-arm64.jar
[09:56:43] [main/INFO]: Preloaded org.lwjgl.opengl.GL
[09:56:43] [main/INFO]: Preloaded org.lwjgl.system.MemoryStack
[09:56:43] [main/INFO]: Preloaded org.lwjgl.system.macosx.MacOSXLibraryBundle
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCursorPosCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWKeyCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCharModsCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeNSGL
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWMouseButtonCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWGL
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWMonitorCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWErrorCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCursorEnterCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.package-info
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWin32
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowRefreshCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFW
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowContentScaleCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWVulkan
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeGLX
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWGammaRamp
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowIconifyCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWScrollCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeEGL
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.EventLoop
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeCocoa
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowSizeCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowPosCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowMaximizeCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWFramebufferSizeCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWImage
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWJoystickCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowCloseCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWDropCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowFocusCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWVidMode
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.Callbacks
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCharCallback
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWayland
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeX11
[09:56:43] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWGamepadState
[09:56:44] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/labymod/sponge-mixin/0.3.5.0.12.5.mixin.0.8.5/sponge-mixin-0.3.5.0.12.5.mixin.0.8.5.jar Service=LabyMod Env=UNKNOWN
[09:56:44] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[09:56:44] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[09:56:46] [main/INFO]: Removed JNDI lookup
[09:56:50] [main/WARN]: The requested compatibility level JAVA_17 is higher than the level supported by the active subsystem 'LabyMod' which supports JAVA_8. This is not a supported configuration and instability may occur.
[09:56:50] [main/INFO]: Compatibility level set to JAVA_17
[09:57:03] [main/INFO]: Checking for addon updates...
[09:57:08] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[09:57:08] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[09:57:11] [main/WARN]: Error loading class: net/optifine/render/VertexBuilderDummy (java.lang.ClassNotFoundException: The specified class 'net.optifine.render.VertexBuilderDummy' was not found)
[09:57:14] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
Completely ignored arguments: [--dummyMinecraftClass, net.minecraft.client.main.Main]
[09:57:18] [main/INFO]: Removed JNDI lookup
[09:57:42] [main/WARN]: Ignored fix registered for version: 2825 as the DataVersion of the game is: 2730
[09:57:42] [main/WARN]: Ignored fix registered for version: 2831 as the DataVersion of the game is: 2730
[09:57:42] [main/WARN]: Ignored fix registered for version: 2832 as the DataVersion of the game is: 2730
[09:57:42] [main/WARN]: Ignored fix registered for version: 2832 as the DataVersion of the game is: 2730
[09:57:42] [main/WARN]: Ignored fix registered for version: 2833 as the DataVersion of the game is: 2730
[09:57:42] [main/WARN]: Ignored fix registered for version: 2838 as the DataVersion of the game is: 2730
[09:57:42] [main/WARN]: Ignored fix registered for version: 2841 as the DataVersion of the game is: 2730
[09:57:43] [main/WARN]: Ignored fix registered for version: 2842 as the DataVersion of the game is: 2730
[09:57:43] [main/WARN]: Ignored fix registered for version: 2843 as the DataVersion of the game is: 2730
[09:57:43] [main/WARN]: Ignored fix registered for version: 2843 as the DataVersion of the game is: 2730
[09:57:43] [main/WARN]: Ignored fix registered for version: 2846 as the DataVersion of the game is: 2730
[09:57:43] [main/WARN]: Ignored fix registered for version: 2852 as the DataVersion of the game is: 2730
[09:57:43] [main/WARN]: Ignored fix registered for version: 2967 as the DataVersion of the game is: 2730
[09:57:43] [main/WARN]: Ignored fix registered for version: 2970 as the DataVersion of the game is: 2730
[09:57:58] [Render thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:217) [launchwrapper-3.1.4.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70) [launchwrapper-3.1.4.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ac.a(SourceFile:65) ~[ac.class:?]
	at dyr.a(SourceFile:2394) ~[dyr.class:?]
	at dyr.a(SourceFile:2389) ~[dyr.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:206) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch.debug/cache/lwjglu0_a707/3.3.1-SNAPSHOT/liblwjgl.so: dlopen failed: library "libpthread.so.0" not found [in thread "Render thread"]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:179) ~[Library.class:?]
	at org.lwjgl.system.Library.loadSystemFromLibraryPath(Library.java:169) ~[Library.class:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:124) ~[Library.class:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:63) ~[Library.class:?]
	at org.lwjgl.system.Library.<clinit>(Library.java:51) ~[Library.class:?]
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100) ~[MemoryUtil.class:?]
	at dsk.<clinit>(SourceFile:8) ~[dsk.class:?]
	at dth.<init>(SourceFile:56) ~[dth.class:?]
	at dto.<init>(SourceFile:19) ~[dto.class:?]
	at dto.<init>(SourceFile:23) ~[dto.class:?]
	at dto.<clinit>(SourceFile:11) ~[dto.class:?]
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:46) ~[RenderSystem.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:194) ~[Main.class:?]
	... 6 more

### Steps To Reproduce

```markdown
1 .Start PojavLauncher
2 .Select Version:"LabyMod-4-1.18"
3 .Launch Minecraft
4 .Minecraft Crash
```

### Expected Behavior

I Installed Labymod 4.

### Platform

```markdown
- Device model: OPPO PBBM30 3/64G
- CPU architecture: arm64
- Android version: 8.1
- PojavLauncher version: dahlia-20230713-c65ef07-feat/lwjgl-3.3.1
```

**Comment by GaucovyAero** [comment]
labymod generally doesnt work on pojav
