### ISSUE TITLE
Game not able to launch after installing jar mods without forge

### ISSUE THREAD

**Issue by Daveethan1904** [PojavLauncherTeam/PojavLauncher#4403]
### Describe the bug

I installed some jar mods [like 64bit mods farlands mods etc] after pressing play it said Error! Failed to download minecraft! Heres the entire log for it java.lang.RuntimeException: com.google.gson.JsonSyntaxException: duplicate key: server
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:753)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:72)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:53)
	at net.kdt.pojavlaunch.tasks.-$$Lambda$AsyncMinecraftDownloader$PJ58CinqkXoL4aS1zc2TGQSS9zk.run(lambda)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: com.google.gson.JsonSyntaxException: duplicate key: server
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:190)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:667)
	... 6 more

### The log file and images/videos

![az_recorder_20230725_082454](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139778710/0dc9e6d1-f08f-45df-afeb-0fdf0ecb2328)
![az_recorder_20230725_082209](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139778710/8c4150da-b8bb-417e-aea8-db36a3a353c3)
![az_recorder_20230725_082433](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139778710/91f0d937-19e5-49d5-8d0d-14fff3bada5b)
![az_recorder_20230725_082445](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139778710/13a4d596-48bd-45fe-bc3d-6a2510c74d15)
![az_recorder_20230725_084116](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139778710/ee34ad93-4fdf-4cba-9e6f-93f1ded0cfac)
![az_recorder_20230725_082420](https://github.com/PojavLauncherTeam/PojavLauncher/assets/139778710/f5f11d10-1412-4522-93c3-338e4b72b117)
 

### Steps To Reproduce

```markdown
1. Download 64bit mods in the cursedcreationsteam.github.io/downloads/
2. Make a folder with one of the 64bit mod names
3. Copy the jar and json file from the 64b it version you want to install
4. Copy the contents in the jar file from the version you want to install and after that delete Meta-inf folder
5. Go to the json and go remove client and replace it with server and rename id to -64bit
After that launch the game and see if the error pops up.
```

### Expected Behavior

Just press play and the error would pop up!

### Platform

```markdown
- Device model: S6 edge plus/32gb
- CPU architecture: aarch64
- Android version: 7.0
- PojavLauncher version: dalhia - 740
```

### Anything else?

It just keeps happening!!

**Comment by GaucovyAero** [comment]
as the error popup suggests, you have incorrectly edited the json, probably ask cursedcreationsteam on how to do it properly
