### ISSUE TITLE
make mistakes; malfunction; error

### ISSUE THREAD

**Issue by yanluol** [PojavLauncherTeam/PojavLauncher#442]

**Comment by yanluol** [comment]
java.io.FileNotFoundException: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/libawt_xawt.so: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at net.kdt.pojavlaunch.PojavLoginActivity.copyDummyNativeLib(PojavLoginActivity.java:365)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:353)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:30)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:138)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:79)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 13 more

**Comment by WesleyVanNeck** [comment]
known issue

**Comment by khanhduytran0** [comment]
Use latest build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/397662794

**Comment by khanhduytran0** [comment]
Please reply @yanluol

**Comment by pablodz** [comment]
4 months without answer
