### ISSUE TITLE
[BUG] the game crashes while remove all the version

### ISSUE THREAD

**Issue by QuantumnKat** [PojavLauncherTeam/PojavLauncher#4425]
### Describe the bug

When you remove all the game version it crashes

### The log file and images/videos

android.view.InflateException: Binary XML file line #73 in net.kdt.pojavlaunch.debug:layout/fragment_launcher: Binary XML file line #73 in net.kdt.pojavlaunch.debug:layout/fragment_launcher: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: android.view.InflateException: Binary XML file line #73 in net.kdt.pojavlaunch.debug:layout/fragment_launcher: Error inflating class com.kdt.mcgui.mcVersionSpinner
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at androidx.fragment.app.Fragment.onCreateView(Fragment.java:1924)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at net.kdt.pojavlaunch.LauncherActivity.onStart(LauncherActivity.java:184)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8157)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3537)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7974)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)
Caused by: java.lang.ClassCastException: net.kdt.pojavlaunch.profiles.ProfileAdapterExtra cannot be cast to java.lang.String
	at com.kdt.mcgui.mcVersionSpinner.setSelection(mcVersionSpinner.java:77)
	at com.kdt.mcgui.mcVersionSpinner.setProfileSelection(mcVersionSpinner.java:68)
	at com.kdt.mcgui.mcVersionSpinner.init(mcVersionSpinner.java:99)
	at com.kdt.mcgui.mcVersionSpinner.<init>(mcVersionSpinner.java:48)
	... 35 more

### Steps To Reproduce

```markdown
remove all the version on the list
```

### Expected Behavior

it crashes and cant go to the game again

### Platform

```markdown
- Device model: rmx3506
- CPU architecture: mali g57
- Android version: 11
- PojavLauncher version: daliha-20230173-c65ef07-feat/lwjgl-3.3.1
```

**Comment by Quan2992** [comment]
The video

**Comment by QuantumnKat** [comment]
This is the video
https://drive.google.com/file/d/1IFYWB4Dpk9i2QXgkuqFYqIzuQNZJM9_J/view?usp=drivesdk

**Comment by GaucovyAero** [comment]
duplicate
