### ISSUE TITLE
[BUG] If you use the new version of zink, you cannot launch the game

### ISSUE THREAD

**Issue by FiCn7430** [PojavLauncherTeam/PojavLauncher#4430]
### Describe the bug

WHEN THE GAME STARTS, THE JAVA PROCESS COMES HERE:
[22:16:10] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[22:16:10] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
process killed with signal 4 code 0x1 addr 0x72d7784278
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x72dc4bae30)

The game will exit directly, and the last line shows that the process was killed and the game cannot be started.
Personally, I think it should be pojavlauncher here to start loading zink, but I don't know why the process is killed.

### The log file and images/videos

Pojav's latestlog .txt overwritten, only the logs file in the .minecraft folder
[22:47:56] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.c(SourceFile:75) ~[1.20.jar:?]
	at ab.a(SourceFile:82) ~[1.20.jar:?]
	at ab.a(SourceFile:75) ~[1.20.jar:?]
	at ab.c(SourceFile:52) ~[1.20.jar:?]
	at ab.a(SourceFile:82) ~[1.20.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.jar:?]
	at o.h(SourceFile:274) ~[1.20.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:164) ~[1.20.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna3431659084406931216.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.cache/JNA/temp/jna3431659084406931216.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace" [in thread "main"]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.12.1.jar:5.12.1 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:93) ~[oshi-core-6.2.2.jar:6.2.2]
	... 15 more
[22:47:56] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.a(SourceFile:77) ~[1.20.jar:?]
	at ab.a(SourceFile:82) ~[1.20.jar:?]
	at ab.a(SourceFile:77) ~[1.20.jar:?]
	at ab.c(SourceFile:52) ~[1.20.jar:?]
	at ab.a(SourceFile:82) ~[1.20.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.jar:?]
	at o.h(SourceFile:274) ~[1.20.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:164) ~[1.20.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native [in thread "main"]
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.c(SourceFile:75) ~[1.20.jar:?]
	at ab.a(SourceFile:82) ~[1.20.jar:?]
	at ab.a(SourceFile:75) ~[1.20.jar:?]
	... 6 more
[22:47:59] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 178 milliseconds
[22:48:00] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[22:48:00] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[22:48:00] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[22:48:00] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:48:02] [Render thread/INFO]: Setting user: ##
[22:48:02] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[22:48:02] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT

### Steps To Reproduce

```markdown
1. Launch PojavLauncher (with the latest Zink with driver version)
2. Select any version
3. Choose the zink renderer
4. Launch the game
5. An error occurs and the game exits
```

### Expected Behavior

Hope to fix this bug

### Platform

```markdown
- Device model: OPPO OnePlus Ace 2 (PHK110)
- CPU architecture: Qualcomm8
SnapdragonTm 8+Gen 1
- Android version: 13
- PojavLauncher version: Latest version
```

**Comment by Bel69420** [comment]
Use english when

**Comment by T-CATHOME** [comment]
你需要使用英语来反馈bug。

**Comment by FiCn7430** [comment]
Can it be now

**Comment by GaucovyAero** [comment]
zink doesn't work on many devices (yet)
