### ISSUE TITLE
[BUG] PojavLauncher crashes on launch with GLFW NoSuchMethodError

### ISSUE THREAD

**Issue by Spider9326** [PojavLauncherTeam/PojavLauncher#4449]
### Describe the bug

PojavLauncher crashes on launch with a NoSuchMethodError related to the GLFW library.

### The log file and images/videos

[--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 23w31a
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2326
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~4Pi9Ax31i8IMigHVi6Gprw==/net.kdt.pojavlaunch-si1iKykodnmviQI7w-xEHw==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~4Pi9Ax31i8IMigHVi6Gprw==/net.kdt.pojavlaunch-si1iKykodnmviQI7w-xEHw==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_virgl
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=430
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.3
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
2023-08-06 05:33:08,859 main ERROR appender Console has no parameter that matches element Policies
[05:33:10] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.c(SourceFile:75) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.a(SourceFile:75) ~[23w31a.jar:?]
	at ab.c(SourceFile:52) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.<init>(SourceFile:52) ~[23w31a.jar:?]
	at o.<init>(SourceFile:34) ~[23w31a.jar:?]
	at o.h(SourceFile:274) ~[23w31a.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[23w31a.jar:?]
[05:33:10] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.a(SourceFile:77) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.a(SourceFile:77) ~[23w31a.jar:?]
	at ab.c(SourceFile:52) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.<init>(SourceFile:52) ~[23w31a.jar:?]
	at o.<init>(SourceFile:34) ~[23w31a.jar:?]
	at o.h(SourceFile:274) ~[23w31a.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[23w31a.jar:?]
[05:33:17] [Datafixer Bootstrap/INFO]: 191 Datafixer optimizations took 490 milliseconds
[05:33:20] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[05:33:20] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[05:33:20] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[05:33:20] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[05:33:22] [Render thread/INFO]: Setting user: Spider93267
Registered forkAndExec
[05:33:22] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[05:33:22] [Render thread/ERROR]: Error parsing option value  for option Text Background Opacity: Not a boolean: ""
[05:33:22] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
VirGL: OSMesa buffer flush is DISABLED!
VirGL: libvirgl_test_server = 0x475faf9ea0943a39
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=5718
EGLBridge: EGLDisplay=0xb4000076211a99f0, EGLSurface=0x75d12cf700
VirGL: created EGL context 0x75d12cf040
EGLBridge: eglMakeCurrent() succeed!
VirGL: vtest_main = 0x7482320278
VirGL: Calling VTest server's main function
OSMDroid: width=2326;height=1080, reserving 10048320 bytes for frame buffer
OSMDroid: created frame buffer
OSMDroid: generating context
gl_version 32 - es profile enabled
WARNING: running without ARB/KHR robustness in place may crash
failed to create sync opengl context
vtest_client_dispatch_commands: client context created.
GLSL feature level 430
vrend_renderer_fill_caps: Entering with stale GL error: 1282
GLSL feature level 430
OSMESA_TARGET: screen=0x76711d1db0
OSMESA: stmgr=0x75912f9fd0; stapi=0x74d56b2d20
OSMDroid: context=0x75c1215730
OSMDroid: making current
unknown format is 19
OSMDroid: vendor: Mesa/X.org
OSMDroid: renderer: virgl
[05:33:23] [Render thread/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.c(SourceFile:75) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.a(SourceFile:75) ~[23w31a.jar:?]
	at ab.c(SourceFile:52) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.<init>(SourceFile:52) ~[23w31a.jar:?]
	at o.<init>(SourceFile:34) ~[23w31a.jar:?]
	at o.a(SourceFile:266) ~[23w31a.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:219) ~[23w31a.jar:?]
[05:33:23] [Render thread/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.linux.LinuxGlobalMemory
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.a(SourceFile:77) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.a(SourceFile:77) ~[23w31a.jar:?]
	at ab.c(SourceFile:52) ~[23w31a.jar:?]
	at ab.a(SourceFile:82) ~[23w31a.jar:?]
	at ab.<init>(SourceFile:52) ~[23w31a.jar:?]
	at o.<init>(SourceFile:34) ~[23w31a.jar:?]
	at o.a(SourceFile:266) ~[23w31a.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:219) ~[23w31a.jar:?]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-08-06 05:33:23
Description: Initializing game

java.lang.NoSuchMethodError: 'int org.lwjgl.glfw.GLFW.glfwGetPlatform()'
	at ekl.a(SourceFile:153)
	at eqn.<init>(SourceFile:497)
	at net.minecraft.client.main.Main.main(SourceFile:213)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at ekl.a(SourceFile:153)
	at eqn.<init>(SourceFile:497)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:213)

-- System Details --
Details:
	Minecraft Version: 23w31a
	Minecraft Version ID: 23w31a
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17.0.7-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1445947616 bytes (1378 MiB) / 1610612736 bytes (1536 MiB) up to 1610612736 bytes (1536 MiB)
	CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	JVM Flags: 3 total; -Xms1536M -Xmx1536M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 23w31a
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2023-08-06_05.33.23-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7806437d20)

### Steps To Reproduce

```markdown
Launch PojavLauncher version dahlia-740-623f7dd33-v3_openjdk on LineageOS 20.0 on an ARM64-V8A device
Select Minecraft version 23w31a
Start game launch
Crash occurs during game initialization
```

### Expected Behavior

PojavLauncher should successfully launch Minecraft 23w31a without crashing.

### Platform

```markdown
Device: lineage_spes 2201117TG
OS: LineageOS 20.0 (Android 13)
Architecture: ARM64-V8A
PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
Minecraft version: 23w31a
```

### Anything else?

I have tried clearing the cache and data for PojavLauncher as well as reinstalling, but the crash persists.
Launching older Minecraft versions like 1.20.1 does not have this issue. It seems to only affect newer versions.

**Comment by Spider9326** [comment]
After troubleshooting a crash when launching Minecraft 23w31a with PojavLauncher, I wanted to provide feedback that I was able to resolve the issue by adding the JVM argument:

```-XX:-UseCompressedOops```

By passing this argument to the JVM on launch, I can now successfully start Minecraft 23w31a without any crashing issues. It seems this argument addresses some compatibility problem that was leading to the crashes.

I wanted to share this in case it helps anyone else who might be encountering similar PojavLauncher crashes when trying to load certain versions of Minecraft. Please let me know if any other details could be useful to have documented about what resolved this problem. I appreciate the knowledgeable community members who have provided assistance troubleshooting these types of issues.

**Comment by GaucovyAero** [comment]
*im making sure to specify that this argument is only going to help if you are on the latest github actions version (that adds the missing lwjgl method first)
