### ISSUE TITLE
java.lang.RuntimeException: Not Found 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87) 	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 	at java.lang.Thread.run(Thread.java:1012)

### ISSUE THREAD

**Issue by Hasantahsin2** [PojavLauncherTeam/PojavLauncher#4456]

**Comment by Hasantahsin2** [comment]
Pojavlanchur olmuyor

**Comment by GaucovyAero** [comment]
buy minecraft
