### ISSUE TITLE
[BUG] Download the fabric version in the launcher and report an error when the launcher starts

### ISSUE THREAD

**Issue by Tangshijieboy** [PojavLauncherTeam/PojavLauncher#4467]
### Describe the bug

Startup shows that the download Microsoft failed, may be due to network connection file placement errors, etc., but my network is no problem
![Screenshot_2023-08-13-07-37-56-686_net kdt pojavlaunch debug](https://github.com/PojavLauncherTeam/PojavLauncher/assets/109576776/df035eda-eeb1-47bd-984c-f992e4f0b821)

### The log file and images/videos

java.lang.RuntimeException: java.lang.NullPointerException: Attempt to read from field 'int net.kdt.pojavlaunch.JMinecraftVersionList$JavaVersionInfo.majorVersion' on a null object reference
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:752)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:72)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:53)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NullPointerException: Attempt to read from field 'int net.kdt.pojavlaunch.JMinecraftVersionList$JavaVersionInfo.majorVersion' on a null object reference
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:747)
	... 6 more

### Steps To Reproduce

```markdown
1.After the starter is turned on
2.After switching to fabric version
3.Download fabric Version, Fast Download Complete
4.Start the version of fabric and generate an error
```

### Expected Behavior

The fabric version should be downloaded for a while, then go back to fabric and start successfully

### Platform

```markdown
- Device model: 红米k30pro/8+128G
- CPU architecture: arm64-v8a
- Android version: 12
- PojavLauncher version: dahlia-20230812-2 b879e8-v3_openjdk
```

**Comment by GaucovyAero** [comment]
update your pojav
