### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by SamTheBest17** [PojavLauncherTeam/PojavLauncher#4468]
### Describe the bug

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### The log file and images/videos

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

### Expected Behavior

I want to launch it on my Minecraft

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

How do I fix this error

**Comment by GaucovyAero** [comment]
buy minecraft

**Comment by Bel69420** [comment]
Yeah, buy Minecraft and don't even try to play it for free
