### ISSUE TITLE
[BUG] can't play virgl rendering in all versions, black screen

### ISSUE THREAD

**Issue by AuraRoket** [PojavLauncherTeam/PojavLauncher#4483]
### Describe the bug

Log error :👇

Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.

[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.

[07:20:03] [Client thread/INFO]: Setting user: AuraRoket
[07:20:07] [Client thread/WARN]: Skipping bad option: lastServer:
[07:20:07] [Client thread/WARN]: Skipping bad option: streamPreferredServer:
[07:20:07] [Client thread/INFO]: LWJGL Version: 3.2.3 SNAPSHOT
VirGL: OSMesa buffer flush is DISABLED!
VirGL: libvirgl_test_server = 0xfd728d12f5c4d1eb
EGLBridge: Initializing
EGLBridge: Initialized!
EGLBridge: ThreadID=22433
EGLBridge: EGLDisplay=0xb400007a47ebfd00, EGLSurface=0x799d326d00
VirGL: created EGL context 0x799cb39600
EGLBridge: eglMakeCurrent() succeed!
VirGL: vtest_main = 0x7a53eec278
VirGL: Calling VTest server's main function
OSMDroid: width=2316;height=1080, reserving 10005120 bytes for frame buffer
OSMDroid: created frame buffer
[07:20:08] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[07:20:08] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.Pointer$Default.<init>(Pointer.java:88)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.CustomBuffer.<init>(CustomBuffer.java:25)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.StructBuffer.<init>(StructBuffer.java:20)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWImage$Buffer.<init>(GLFWImage.java:362)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.Display.setIcon(Display.java:945)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at bib.av(SourceFile:661)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at bib.aq(SourceFile:456)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[07:20:08] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
OSMDroid: generating context
gl_version 32 - es profile enabled
failed to create sync opengl context
vtest_client_dispatch_commands: client context created.
GLSL feature level 430
GLSL feature level 430
OSMESA_TARGET: screen=0x799d322600
OSMESA: stmgr=0x799c9fffd0; stapi=0x79c5afad20
OSMDroid: context=0x799d76b440
[07:20:08] [Client thread/INFO]: [STDOUT]: LWJGLX: ready-handle context created
OSMDroid: making current
unknown format is 19
OSMDroid: vendor: Mesa/X.org
OSMDroid: renderer: virgl
[07:20:08] [Client thread/INFO]: [STDOUT]: LWJGLX: GL caps init
[07:20:09] [Client thread/INFO]: [STDOUT]: Grab: false
[07:20:09] [Client thread/INFO]: Reloading ResourceManager: Default
I/NativeInput(22367): Input ready: 1

[07:20:09] [Sound Library Loader/INFO]: Starting up SoundSystem...
[07:20:10] [Thread-2/INFO]: Initializing LWJGL OpenAL
[07:20:10] [Thread-2/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[07:20:10] [Thread-2/INFO]: OpenAL initialized.
[07:20:10] [Sound Library Loader/INFO]: Sound engine started
[07:20:18] [Client thread/INFO]: Created: 1024x512 textures-atlas
[07:20:22] [Client thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Native library (linux-aarch64/libfliteWrapper.so) not found in resource path ([file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-glfw-classes.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlau
nch/files/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar, file:/storage/
emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.12.2/1.12.2.jar])
[07:20:24] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id

### The log file and images/videos

![Screenshot_2023-08-16-07-25-12-87_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/PojavLauncherTeam/PojavLauncher/assets/142362866/fe443a51-21bf-4957-b0d7-c4fa7a37b39b)

Black screen ,

### Steps To Reproduce

```markdown
1.My cellphone is practically new, and I just downloaded the Pojav launcher 
2.I downloaded 1.12.2 , and I chose virgl rendering because I want to install shaders
3.I'm stuck on a black screen, no mojang image appears, and only hear the song from Minecraft
4.I have tried all versions like 1.8.9 and others
```

### Expected Behavior

I hope this is fixed soon, because later people will feel what I experienced, I want all players to be able to use shaders and no more bugs in virgl rendering.

### Platform

```markdown
- Device model: realme c55
- CPU architecture: mali mediatek g88
- Android version:13
- PojavLauncher version:all
```

### Anything else?

freeze black screen .No mojang image appears, only the sound of music from Minecraft is heard .I'm from Indonesia, this is a bug. Can't use Virgl, black screen. Please fix it

**Comment by AuraRoket** [comment]
Do you feel what I'm going through right now,If true then report it

**Comment by AuraRoket** [comment]
Do you guys experience the same thing. if true please report it

**Comment by GaucovyAero** [comment]
issues with virgl will not be adressed, as it will later be replaced with zink (opengl 4.6 over vulkan), please use gl4es instead

**Comment by masoomshado** [comment]
Bro this is why bcz you have installed wrong version of mods or incompatible mods btw you can checkout my videos if have same problem bcz I uploaded there solution yt: Roiz Gaming
