### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by theDANiMC** [PojavLauncherTeam/PojavLauncher#4516]
### Describe the bug

The PojavLauncher ended with code 1

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.16.5-forge-36.2.0
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2790
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~CmuW-VArfjwHUiMpjoWKtg==/net.kdt.pojavlaunch-e_zcDzy9dI0Vp0IqTLuXjg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~CmuW-VArfjwHUiMpjoWKtg==/net.kdt.pojavlaunch-e_zcDzy9dI0Vp0IqTLuXjg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1440
--------- beginning of main

I/LIBGL   ( 3025): Initialising gl4es
I/LIBGL   ( 3025): v1.1.4 built on Mar 11 2023 20:15:08
I/LIBGL   ( 3025): Using GLES 2.0 backend

I/LIBGL   ( 3025): loaded: libGLESv2.so

I/LIBGL   ( 3025): loaded: libEGL.so

I/LIBGL   ( 3025): Using GLES 2.0 backend

I/LIBGL   ( 3025): Hardware Full NPOT detected and used

I/LIBGL   ( 3025): FBO are in core, and so used

I/LIBGL   ( 3025): PointSprite are in core, and so used

I/LIBGL   ( 3025): CubeMap are in core, and so used

I/LIBGL   ( 3025): BlendColor is in core, and so used

I/LIBGL   ( 3025): Blend Substract is in core, and so used

I/LIBGL   ( 3025): Blend Function and Equation Separation is in core, and so used

I/LIBGL   ( 3025): Texture Mirrored Repeat is in core, and so used

I/LIBGL   ( 3025): Extension GL_OES_element_index_uint  detected and used

I/LIBGL   ( 3025): Extension GL_OES_packed_depth_stencil  detected and used

I/LIBGL   ( 3025): Extension GL_OES_depth24  detected and used

I/LIBGL   ( 3025): Extension GL_OES_rgb8_rgba8  detected and used

I/LIBGL   ( 3025): Extension GL_EXT_texture_format_BGRA8888  detected and used

I/LIBGL   ( 3025): Extension GL_OES_depth_texture  detected and used

I/LIBGL   ( 3025): Extension GL_OES_texture_stencil8  detected and used

I/LIBGL   ( 3025): Extension GL_OES_texture_float  detected and used

I/LIBGL   ( 3025): Extension GL_OES_texture_half_float  detected and used

I/LIBGL   ( 3025): Extension GL_EXT_color_buffer_float  detected and used

I/LIBGL   ( 3025): Extension GL_EXT_color_buffer_half_float  detected and used

I/LIBGL   ( 3025): high precision float in fragment shader available and used

I/LIBGL   ( 3025): Max vertex attrib: 32

I/LIBGL   ( 3025): Extension GL_OES_standard_derivatives  detected and used

I/LIBGL   ( 3025): Max texture size: 16384

I/LIBGL   ( 3025): Max Varying Vector: 31

I/LIBGL   ( 3025): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6

I/LIBGL   ( 3025): Extension GL_EXT_texture_filter_anisotropic  detected and used

I/LIBGL   ( 3025): Max Anisotropic filtering: 16

I/LIBGL   ( 3025): Hardware vendor is Qualcomm

I/LIBGL   ( 3025): GLSL 300 es supported
I/LIBGL   ( 3025): GLSL 310 es supported and used
I/LIBGL   ( 3025): GLSL 320 es supported
I/LIBGL   ( 3025): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   ( 3025): sRGB surface supported

I/LIBGL   ( 3025): EGLImage to Texture2D supported
I/LIBGL   ( 3025): EGLImage to RenderBuffer supported

I/LIBGL   ( 3025): ignore MipMap
I/LIBGL   ( 3025): Targeting OpenGL 2.1
I/LIBGL   ( 3025): No hack in shader converter to define overloaded function with int
I/LIBGL   ( 3025): NPOT texture handled in hardware
I/LIBGL   ( 3025): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 3025): try to use VBO
I/LIBGL   ( 3025): glX Will try to recycle EGL Surface
I/LIBGL   ( 3025): Current folder is:/

I/jrelog  ( 3025): dlopen libgl4es_114.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success

I/jrelog  ( 3025): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace classloader-namespace

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success

I/jrelog  ( 3025): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success

I/jrelog  ( 3025): dlopen /data/app/~~CmuW-VArfjwHUiMpjoWKtg==/net.kdt.pojavlaunch-e_zcDzy9dI0Vp0IqTLuXjg==/lib/arm64/libopenal.so success

I/jrelog  ( 3025): Done processing args

I/jrelog  ( 3025): Found JLI lib
I/jrelog  ( 3025): Calling JLI_Launch

OpenJDK 64-Bit Server VM warning: 
No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
2023-08-26 07:27:52,572 main ERROR appender Console has no parameter that matches element Policies

[07:27:52] [main/INFO]: ModLauncher running: args [--username, xx_DaNieLit0_, --version, 1.16.5, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 1.16, --uuid, 00000000000000000000000000000000, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.0, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[07:27:52] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_372-internal by Oracle Corporation
[07:27:53] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[07:27:53] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[07:27:55] [main/INFO]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --uuid, 00000000000000000000000000000000, --username, xx_DaNieLit0_, --assetIndex, 1.16, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release]
Exception in thread "main" 
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[07:27:56] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:72)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:38)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:248)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:122)
[07:27:56] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more
Java Exit code: 1
I/jrelog  ( 3025): Going to free args
I/jrelog  ( 3025): Free done

### Steps To Reproduce

```markdown
1. start PojavLauncher
2. select the version 1.16.5 with Forge
3. The game crashed
```

### Expected Behavior

I think it will crash but at the same time I think it will open

### Platform

```markdown
- Device model: Pixel 3 XL 
- CPU architecture: Idk
- Android version: 12
- PojavLauncher version: dahlia-740-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
update your pojavlauncher to the latest github actions build, the issue has been already resolved
