### ISSUE TITLE
the app crashed after enter a word

### ISSUE THREAD

**Issue by FFDVDGD** [PojavLauncherTeam/PojavLauncher#4535]
### Describe the bug

the app crashed after i enter a word for a while(within 1 minutes), it runs good except entering a word. the game version is 1.20.1fabric.

### The log file and images/videos

错误信息
java.io.FileNotFoundException: open failed: EACCES (Permission denied)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2029)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1520)
	at l.ۦۗۦ.ۧۙ(X14X:199)
	at l.ۛۚۦ.ۘۙ(F183:310)
	at l.ۢۢۗ.ۥ(OB3B:128)
	at l.ۢۢۗ.ۥ(Native Method)
	at l.۫ۚۗ.call(5ATD:365)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
1.start pojavlauncher
2.open the game
3.enter a world
```

### Expected Behavior

the game runs

### Platform

```markdown
- Device model: Mi Pad 6Pro
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: dahlia-20230829-c8a462a-feat/fabric_refactor
```

**Comment by GaucovyAero** [comment]
send latestlog.txt

**Comment by FFDVDGD** [comment]
> send latestlog.txt

"The log file and images/videos" is just the latestlog.txt

**Comment by alexytomi** [comment]
> > send latestlog.txt
> 
> "The log file and images/videos" is just the latestlog.txt

send the latestlog.txt not just that

**Comment by lzfddkd** [comment]
请发送日志文件lastlog.txt

**Comment by MovTery** [comment]
你这个是MT管理器的报错，谢谢，请直接把latestlog.txt发上来

**Comment by FFDVDGD** [comment]
> 你这个是MT管理器的报错，谢谢，请直接把latestlog.txt发上来

我无法上传latestlog.txt，当我在GitHub中上传它时报错，试图把它移动到别的文件夹时也报错

**Comment by GaucovyAero** [comment]
> > 你这个是MT管理器的报错，谢谢，请直接把latestlog.txt发上来
> 
> 我无法上传latestlog.txt，当我在GitHub中上传它时报错，试图把它移动到别的文件夹时也报错

click the share log file button and share it onto discord for example, then download it to your phone and upload it to here (make sure that when you are selecting latestlog.txt, go into internal storage - Download for example, not just Downloads)

**Comment by GaucovyAero** [comment]
no log provided
