### ISSUE TITLE
[BUG] libjvm.so not accessible 

### ISSUE THREAD

**Issue by Gogo64pro** [PojavLauncherTeam/PojavLauncher#4542]
### Describe the bug

I get the following error
```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 9/1/23, 10:53 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna10621272388706259345.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna10621272388706259345.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
```
Saw a similar issue, but they were using fabric and they fixed it by deleting ferritecore and sodium. I tried deleting ferritecore and rubidium (sodium forge fork), but I got the same issue. Tried it with all 3 renderers, but still got the same error
Thanks 

### The log file and images/videos

Full log is too long here's the important part
`

```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 9/1/23, 10:53 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna10621272388706259345.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna10621272388706259345.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] {}
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?] {}
	at java.lang.Runtime.load0(Unknown Source) ~[?:?] {}
	at java.lang.System.load(Unknown Source) ~[?:?] {re:mixin}
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at me.hypherionmc.discordapi.DiscordRPC.<clinit>(DiscordRPC.java:41) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:classloading}
	at me.hypherionmc.simplerpclib.discord.DiscordController.<init>(DiscordController.java:30) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:classloading}
	at me.hypherionmc.simplerpclib.discord.RichPresenceCore.<init>(RichPresenceCore.java:61) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:mixin,re:classloading}
	at me.hypherionmc.simplerpc.SimpleRPCClient.init(SimpleRPCClient.java:22) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:mixin,re:classloading}
	at net.minecraft.client.tutorial.Tutorial.handler$blo000$TutorialManager(Tu
torial.java:517) ~[client-1.18.2-20220404.173914-srg.jar%23233!/:?] {re:mixin,re:classloading,pl:mixin:APP:simplerpc.mixins.json:TutorialBundleMixin,pl:mixin:A}
	at net.minecraft.client.tutorial.Tutorial.<init>(Tutorial.java:32) ~[client-1.18.2-20220404.173914-srg.jar%23233!/:?] {re:mixin,re:classloading,pl:mixin:APP:simplerpc.mixins.json:TutorialBundleMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.18.2-20220404.173914-srg.jar%23233!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:redirectionor-common.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:customwindowtitle.mixins.json:DisableVanillaTitle,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:simplerpc.mixins.json:ScreenEventsMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:drippyloadingscreen.mixin.json:client.IMixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:client.MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin
:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23233!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%231!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
-------------------------------------
--------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] {}
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?] {}
	at java.lang.Runtime.load0(Unknown Source) ~[?:?] {}
	at java.lang.System.load(Unknown Source) ~[?:?] {re:mixin}
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at me.hypherionmc.discordapi.DiscordRPC.<clinit>(DiscordRPC.java:41) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:classloading}
	at me.hypherionmc.simplerpclib.discord.DiscordController.<init>(DiscordController.java:30) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:classloading}
	at me.hypherionmc.simplerpclib.discord.RichPresenceCore.<init>(RichPresenceCore.java:61) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:mixin,re:classloading}
	at me.hypherionmc.simplerpc.SimpleRPCClient.init(SimpleRPCClient.java:22) ~[simple-rpc-1.18.2-3.2.3.jar%23203!/:3.2.3] {re:mixin,re:classloading}
	at net.minecraft.client.tutorial.Tutorial.handler$blo000$TutorialManager(Tutorial.java:517) ~[client-1.18.2-20220404.173914-srg.jar%23233!/:?] {re:mixin,re:classloading,pl:mixin:APP:simplerpc.mixins.json:TutorialBundleMixin,pl:mixin:A}
	at net.minecraft.client.tutorial.Tutorial.<init>(Tutorial.java:32) ~[client-1.18.2-20220404.173914-srg.jar%23233!/:?] {re:mixin,re:classloading,pl:mixin:APP:simplerpc.mixins.json:TutorialBundleMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.18.2-20220404.173914-s
rg.jar%23233!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:redirectionor-common.mixins.json:client.MinecraftMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.blast_search_trees.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:feature.measure_time.MinecraftMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.concurrency.MinecraftMixin,pl:mixin:APP:modernfix-forge.mixins.json:feature.measure_time.MinecraftMixin_Forge,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinMinecraft,pl:mixin:APP:konkrete.mixin.json:client.MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:customwindowtitle.mixins.json:DisableVanillaTitle,pl:mixin:APP:fastload.mixins.json:client.MinecraftClientMixin,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:simplerpc.mixins.json:ScreenEventsMixin,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinMinecraftClient,pl:mixin:APP:drippyloadingscreen.mixin.json:client.IMixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:client.MixinMinecraft,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:APP:freecam.mixins.json:MinecraftMixin,pl:mixin:APP:fancymenu.general.mixin.json:IMixinMinecraft,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18.2-20220404.173914-srg.jar%2323
3!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%231!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2314!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17.0.7-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1370486784 bytes (1306 MiB) / 2883584000 bytes (2750 MiB) up to 2883584000 bytes (2750 MiB)
	CPUs: 8
	Processor Vendor: 0x51
	Processor Name: 
	Identifier: 0x51 Family 8 Model 0x804 Stepping r0xdp14
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical package
s: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 6317.43
	Virtual memory used (MB): 7058.77
	Swap memory total (MB): 3584.00
	Swap memory used (MB): 1497.76
	JVM Flags: 3 total; -Xms2750M -Xmx2750M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2023-09-01_10.53.16-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7428cb8d30)

```

### Steps To Reproduce

```markdown
1. Install forge 40.2.9
2. Copy create arcane engineering modpack from PC
3. Start the game
```

### Expected Behavior

The game launches

### Platform

```markdown
- Device model: Nokia XR20
- CPU architecture/instruction set: ARMv8-A/aarch64
- Android version: 13
- PojavLauncher version: Latest
```
```


### Anything else?

_No response_

**Comment by GaucovyAero** [comment]
remove simplerpc
