### ISSUE TITLE
[BUG] fancyvideo_api crash

### ISSUE THREAD

**Issue by Taratorcho** [PojavLauncherTeam/PojavLauncher#4553]
### Describe the bug

The mod Fancy Video API makes the game display 
Fancyviseoapi has failed to load correctly

### The log file and images/videos

```
-- Head --
Thread: Render thread
Stacktrace:
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
-- MOD fancyvideo_api --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.9.jar%23238!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.9.jar%23237!/:?] {re:mixin}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
		at java.ut
il.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

	Mod File: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/FancyVideo-API-forge-2.2.0.0.jar
	Failure message: FancyVideo API (fancyvideo_api) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 2.2.0.0
	Mod Issue URL: https://github.com/Nick1st/FancyVideo-API/issues
	Exception message: java.lang.UnsatisfiedLinkError: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna9469201114256927529.tmp: dlopen failed: library "/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.cache/JNA/temp/jna9469201114256927529.tmp" needed or dlopened by "/data/data/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so" is not accessible for the namespace "classloader-namespace"
Stacktrace:
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] {}
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?] {}
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?] {}
	at java.lang.Runtime.load0(Unknown Source) ~[?:?] {}
	at java.lang.System.load(Unknown Source) ~[?:?] {re:mixin}
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at com.sun.jna.Native.<clinit>(Native.java:221) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at com.sun.jna
.NativeLibrary.<clinit>(NativeLibrary.java:87) ~[jna-5.10.0.jar%2348!/:5.10.0 (b0)] {}
	at nick1st.fancyvideo.CommonMainClass.onInit(CommonMainClass.java:120) ~[FancyVideo-API-forge-2.2.0.0.jar%23121!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.CommonMainClass.<init>(CommonMainClass.java:80) ~[FancyVideo-API-forge-2.2.0.0.jar%23121!/:2.2.0.0] {re:classloading}
	at nick1st.fancyvideo.FancyVideoAPI.<init>(FancyVideoAPI.java:86) ~[FancyVideo-API-forge-2.2.0.0.jar%23121!/:2.2.0.0] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.9.jar%23238!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.9.jar%23237!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {re:mixin}

```

### Steps To Reproduce

```markdown
1.Install the mod
```

### Expected Behavior

The game launches 

### Platform

```markdown
- CPU architecture: aarch64 
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

Don't expect it to get fixed, just looking for a solution that doesn't involve deleting the mod

**Comment by GaucovyAero** [comment]
its trying to load another program outside of pojav, thats not possible on android, not sure if you can do anything about it

**Comment by Gogo64pro** [comment]
> its trying to load another program outside of pojav, thats not possible on android, not sure if you can do anything about it

I see it's trying to load libjvm.so, but it can't. Is there a way to make it try and load a different copy of libjvm.so that it can access?

**Comment by GaucovyAero** [comment]
nope

**Comment by Taratorcho** [comment]
> its trying to load another program outside of pojav, thats not possible on android, not sure if you can do anything about it

Why can't it load the library? Being used? Permission error? I accidentally closed and reopened

**Comment by GaucovyAero** [comment]
android's security, you can't just open a program without permission

**Comment by Taratorcho** [comment]
> android's security, you can't just open a program without permission

Is it a permission you can give it or just not possible without shading into the jar

**Comment by Gogo64pro** [comment]
> 



> > android's security, you can't just open a program without permission
> 
> Is it a permission you can give it or just not possible without shading into the jar

How do you share a .so file into a jar? It's not possible

**Comment by GaucovyAero** [comment]
> > android's security, you can't just open a program without permission
> 
> Is it a permission you can give it or just not possible without shading into the jar

no, i already said that its trying to launch it outside of pojav
