### ISSUE TITLE
My account is not login

### ISSUE THREAD

**Issue by LANGAMERP** [PojavLauncherTeam/PojavLauncher#4576]
### Is this request related to a bug?

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Describe the request.

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Anything else?

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:297)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:87)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by GaucovyAero** [comment]
buy minecraft
