### ISSUE TITLE
Bug In Join Game

### ISSUE THREAD

**Issue by HeyBlueMito** [PojavLauncherTeam/PojavLauncher#46]
java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar", zip file "/storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar", zip file "/storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar", zip file "/storage/emulated/0/games/minecraft/versions/1.8/1.8.jar"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-2/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:849)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(MainActivity.java)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:818)
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/mojang/netty/1.6/netty-1.6.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/google/guava/guava/17.0/guava-17.0.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9/log4j-api-2.0-beta9.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9/log4j-core-2.0-beta9.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.io.IOException: Failed to open dex files from /storage/emulated/0/games/minecraft/versions/1.8/1.8.jar
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:295)
		at dalvik.system.DexFile.<init>(DexFile.java:111)
		at dalvik.system.DexFile.loadDex(DexFile.java:151)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:282)
		at dalvik.system.DexPathList.makePathElements(DexPathList.java:248)
		at dalvik.system.DexPathList.<init>(DexPathList.java:120)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:57)
		at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:846)
		... 3 more
	Suppressed: java.lang.ClassNotFoundException: Didn't find class "net.minecraft.client.main.Main" on path: DexPathList[[zip file "/data/app/net.kdt.pojavlaunch-2/base.apk"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-2/lib/arm, /data/app/net.kdt.pojavlaunch-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 5 more
		Suppressed: java.lang.ClassNotFoundException: net.minecraft.client.main.Main
			at java.lang.Class.classForName(Native Method)
			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
			... 6 more
		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by khanhduytran0** [comment]
??? It didn't download any libraries/client

**Comment by khanhduytran0** [comment]
Try another versions

**Comment by HeyBlueMito** [comment]
Im try 1.7.10 and 1.11

**Comment by khanhduytran0** [comment]
Also check if Storage permission is granted.
If still not success, delete folder /sdcard/games/minecraft and try again
### THIS WILL DELETE ALL INSTALLED VERSIONS AND DOWNLOAD ASSET.

**Comment by khanhduytran0** [comment]
Is your device Android 6? @HeyBlueMito

**Comment by khanhduytran0** [comment]
Try v3
