### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by ENDERdaragon** [PojavLauncherTeam/PojavLauncher#4617]
### Is this request related to a bug?

java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.throwResponseError(MicrosoftBackgroundLogin.java:347)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:153)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:79)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by ENDERdaragon** [comment]
Mana

**Comment by GaucovyAero** [comment]
log into minecraft.net first and make sure you are not on school internet or something similar
