### ISSUE TITLE
Minecraft 1.20.2 crash

### ISSUE THREAD

**Issue by Edo2048** [PojavLauncherTeam/PojavLauncher#4629]
### Describe the bug

when i start Minecraft Version 1.20.2 crash

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [lwjgl-glfw-classes.jar, version]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.20.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2320
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~NmqIr82NbGJUBv2cqBqiMQ==/net.kdt.pojavlaunch--tAigUM_tu5zBPEBEXw_yg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~NmqIr82NbGJUBv2cqBqiMQ==/net.kdt.pojavlaunch--tAigUM_tu5zBPEBEXw_yg==/lib/arm64
Added custom env: POJAV_RENDERER=opengles3_desktopgl_angle_vulkan
Added custom env: LIBGL_ES=3
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: POJAVEXEC_EGL=libEGL_angle.so
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main

I/jrelog  (28820): dlopen libtinywrapper.so success

I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (28820): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (28820): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

2023-09-24 13:19:56,517 main ERROR appender Console has no parameter that matches element Policies
[13:19:57] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[13:19:57] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at oshi.jna.platform.linux.LinuxLibc.<clinit>(LinuxLibc.java:22) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:97) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:170) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:57) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.c(SourceFile:75) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:75) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.h(SourceFile:274) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:167) ~[1.20.2.jar:?]
[13:19:57] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.h(SourceFile:274) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:167) ~[1.20.2.jar:?]
[13:20:04] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 694 milliseconds
[13:20:06] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:20:06] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:20:06] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:20:07] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:20:08] [Render thread/INFO]: Setting user: GreeperDragon
Registered forkAndExec
[13:20:08] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[13:20:08] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[13:20:08] [Render thread/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:170) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:57) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.c(SourceFile:75) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:75) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.a(SourceFile:266) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:220) ~[1.20.2.jar:?]
[13:20:08] [Render thread/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.linux.LinuxGlobalMemory
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.a(SourceFile:266) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:220) ~[1.20.2.jar:?]
---- Minecraft Crash Report ----
// My bad.

Time: 2023-09-24 13:20:08
Description: Initializing game

java.lang.NoSuchMethodError: 'void org.lwjgl.glfw.GLFWNativeGLX.setPath(org.lwjgl.system.FunctionProvider)'
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)
	at net.minecraft.client.main.Main.main(SourceFile:214)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:214)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1991769016 bytes (1899 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	JVM Flags: 3 total; -Xms2048M -Xmx2048M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	JVM uptime in seconds: 14.931
	Launched Version: 1.20.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and bra
nd is untouched
	Type: Client (map_client.txt)
	Locale: en
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2023-09-24_13.20.08-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x795897ed08)

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Select Minecraft version 1.20.2
3. When starting crash
```

### Expected Behavior

Should to able to play Minecraft 1.20.2

### Platform

```markdown
- Device model: Xiaomi POCO X4 Pro 5G
- CPU architecture: Snapdragon 695
- Android version: 12
- PojavLauncher version: Lastest Version of Play Store
```

**Comment by GaucovyAero** [comment]
install the latest github actions build, lwjgl is outdated on the play store version
