### ISSUE TITLE
[Crash] 1.20.2 Crash

### ISSUE THREAD

**Issue by CommanderTho** [PojavLauncherTeam/PojavLauncher#4639]
### Describe the bug

Application exited with code -1

### The log file and images/videos

`--------- beginning with launcher debug
Info: Launcher version: dahlia-740-623f7dd33-v3_openjdk
Info: LWJGL3 directory: [version, lwjgl-glfw-classes.jar]
Architecture: arm64
Info: Custom Java arguments: ""
Info: Selected Minecraft version: 1.20.2
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1632
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-ssLUu2yvPuivjRgqcTMPug==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-ssLUu2yvPuivjRgqcTMPug==/lib/arm64
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=918
--------- beginning of main

I/LIBGL   ( 4387): Initialising gl4es
I/LIBGL   ( 4387): v1.1.4 built on Mar 11 2023 20:15:08
I/LIBGL   ( 4387): Using GLES 2.0 backend
I/LIBGL   ( 4387): loaded: libGLESv2.so
I/LIBGL   ( 4387): loaded: libEGL.so
I/LIBGL   ( 4387): Using GLES 2.0 backend
I/LIBGL   ( 4387): Hardware Full NPOT detected and used
I/LIBGL   ( 4387): FBO are in core, and so used
I/LIBGL   ( 4387): PointSprite are in core, and so used
I/LIBGL   ( 4387): CubeMap are in core, and so used
I/LIBGL   ( 4387): BlendColor is in core, and so used
I/LIBGL   ( 4387): Blend Substract is in core, and so used
I/LIBGL   ( 4387): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 4387): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 4387): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 4387): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 4387): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 4387): Extension GL_OES_rgb8_rgba8  detected and used
I/LIBGL   ( 4387
): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 4387): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 4387): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 4387): Extension GL_OES_texture_float  detected and used
I/LIBGL   ( 4387): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 4387): Extension GL_EXT_color_buffer_float  detected and used
I/LIBGL   ( 4387): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 4387): high precision float in fragment shader available and used
I/LIBGL   ( 4387): Max vertex attrib: 32
I/LIBGL   ( 4387): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 4387): Max texture size: 16384
I/LIBGL   ( 4387): Max Varying Vector: 31
I/LIBGL   ( 4387): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
I/LIBGL   ( 4387): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 4387): Max Anisotropic filtering: 16
I/LIBGL   ( 4387): Hardware 
vendor is Qualcomm
I/LIBGL   ( 4387): GLSL 300 es supported
I/LIBGL   ( 4387): GLSL 310 es supported and used
I/LIBGL   ( 4387): GLSL 320 es supported
I/LIBGL   ( 4387): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   ( 4387): sRGB surface supported
I/LIBGL   ( 4387): EGLImage to Texture2D supported
I/LIBGL   ( 4387): EGLImage to RenderBuffer supported
I/LIBGL   ( 4387): ignore MipMap
I/LIBGL   ( 4387): Targeting OpenGL 2.1
I/LIBGL   ( 4387): No hack in shader converter to define overloaded function with int
I/LIBGL   ( 4387): NPOT texture handled in hardware
I/LIBGL   ( 4387): Not trying to batch small subsequent glDrawXXXX
I/LIBGL   ( 4387): try to use VBO
I/LIBGL   ( 4387): glX Will try to recycle EGL Surface
I/LIBGL   ( 4387): Current folder is:/
I/jrelog  ( 4387): dlopen libgl4es_114.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 4387): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 4387)
: dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  ( 4387): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  ( 4387): dlopen /data/app/net.kdt.pojavlaunch-ssLUu2yvPuivjRgqcTMPug==/lib/arm64/libopenal.so success

I/jrelog  ( 4387): Done processing args
I/jrelog  ( 4387): Found JLI lib
I/jrelog  ( 4387): Calling JLI_Launch

Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
2023-09-27 19:53:22,832 main ERROR appender Console has no parameter that matches element Policies
[19:53:24] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[19:53:24] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at oshi.jna.platform.linux.LinuxLibc.<clinit>(LinuxLibc.java:22) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:97) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:170) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:57) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.c(SourceFile:75) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:75) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.h(SourceFile:274) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:167) ~[1.20.2.jar:?]
[19:53:24] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.h(SourceFile:274) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:167) ~[1.20.2.jar:?]
[19:53:34] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 860 milliseconds
[19:53:39] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[19:53:39] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[19:53:39] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[19:53:39] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:53:41] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:159) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:53) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:55) ~[authlib-5.0.47.jar:?]
	at eqv.a(SourceFile:787) ~[1.20.2.jar:?]
	at eqv.<init>(SourceFile:451) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:214) ~[1.20.2.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:130) ~[authlib-5.0.47.jar:?]
	... 5 more
[19:53:41] [Render thread/INFO]: Setting user: v4mpyxl
Registered forkAndExec
[19:53:41] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[19:53:41] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
I/LIBGL   ( 4387): Initialising gl4es
I/LIBGL   ( 4387): v1.1.4 built on Mar 11 2023 20:15:08
I/LIBGL   ( 4387): Using GLES 2.0 backend

I/LIBGL   ( 4387): loaded: libGLESv2.so

I/LIBGL   ( 4387): loaded: libEGL.so
I/LIBGL   ( 4387): Using GLES 2.0 backend

I/LIBGL   ( 4387): Hardware Full NPOT detected and used
I/LIBGL   ( 4387): FBO are in core, and so used
I/LIBGL   ( 4387): PointSprite are in core, and so used
I/LIBGL   ( 4387): CubeMap are in core, and so used

I/LIBGL   ( 4387): BlendColor is in core, and so used
I/LIBGL   ( 4387): Blend Substract is in core, and so used
I/LIBGL   ( 4387): Blend Function and Equation Separation is in core, and so used
I/LIBGL   ( 4387): Texture Mirrored Repeat is in core, and so used
I/LIBGL   ( 4387): Extension GL_OES_element_index_uint  detected and used
I/LIBGL   ( 4387): Extension GL_OES_packed_depth_stencil  detected and used
I/LIBGL   ( 4387): Extension GL_OES_depth24  detected and used
I/LIBGL   ( 4387): Extension GL_OES_rgb8_rgba8  detected and used

I/LIBGL   ( 4387): Extension GL_EXT_texture_format_BGRA8888  detected and used
I/LIBGL   ( 4387): Extension GL_OES_depth_texture  detected and used
I/LIBGL   ( 4387): Extension GL_OES_texture_stencil8  detected and used
I/LIBGL   ( 4387): Extension GL_OES_texture_float  detected and used

I/LIBGL   ( 4387): Extension GL_OES_texture_half_float  detected and used
I/LIBGL   ( 4387): Extension GL_EXT_color_buffer_float  detected and used

I/LIBGL   ( 4387): Extension GL_EXT_color_buffer_half_float  detected and used
I/LIBGL   ( 4387): high precision float in fragment shader available and used
I/LIBGL   ( 4387): Max vertex attrib: 32

I/LIBGL   ( 4387): Extension GL_OES_standard_derivatives  detected and used
I/LIBGL   ( 4387): Max texture size: 16384
I/LIBGL   ( 4387): Max Varying Vector: 31

I/LIBGL   ( 4387): Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6

I/LIBGL   ( 4387): Extension GL_EXT_texture_filter_anisotropic  detected and used
I/LIBGL   ( 4387): Max Anisotropic filtering: 16

I/LIBGL   ( 4387): Hardware vendor is Qualcomm

I/LIBGL   ( 4387): GLSL 300 es supported

I/LIBGL   ( 4387): GLSL 310 es supported and used
I/LIBGL   ( 4387): GLSL 320 es supported
I/LIBGL   ( 4387): Max Color Attachments: 8 / Draw buffers: 8
I/LIBGL   ( 4387): sRGB surface supported

I/LIBGL   ( 4387): EGLImage to Texture2D supported
I/LIBGL   ( 4387): EGLImage to RenderBuffer supported

I/LIBGL   ( 4387): ignore MipMap

I/LIBGL   ( 4387): Targeting OpenGL 2.1
I/LIBGL   ( 4387): No hack in shader converter to define overloaded function with int
I/LIBGL   ( 4387): NPOT texture handled in hardware
I/LIBGL   ( 4387): Not trying to batch small subsequent glDrawXXXX

I/LIBGL   ( 4387): try to use VBO
I/LIBGL   ( 4387): glX Will try to recycle EGL Surface
I/LIBGL   ( 4387): Current folder is:/storage/emulated/0/games/PojavLauncher/.minecraft

[19:53:41] [Render thread/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:170) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:57) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.c(SourceFile:75) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:75) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.a(SourceFile:266) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:220) ~[1.20.2.jar:?]
[19:53:41] [Render thread/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.linux.LinuxGlobalMemory
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:77) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.a(SourceFile:266) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:220) ~[1.20.2.jar:?]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2023-09-27 19:53:41
Description: Initializing game

java.lang.NoSuchMethodError: 'void org.lwjgl.glfw.GLFWNativeGLX.setPath(org.lwjgl.system.FunctionProvider)'
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)
	at net.minecraft.client.main.Main.main(SourceFile:214)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:64)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:847)
	at eqv.<init>(SourceFile:491)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:214)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 17.0.7-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1816766464 bytes (1732 MiB) / 2086666240 bytes (1990 MiB) up to 2086666240 bytes (1990 MiB)
	CPUs: 7
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	JVM Flags: 3 total; -Xms1990M -Xmx1990M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	JVM uptime in seconds: 21.841
	Launched Version: 1.20.2
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature
 and brand is untouched
	Type: Client (map_client.txt)
	Locale: en
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/games/PojavLauncher/.minecraft/crash-reports/crash-2023-09-27_19.53.41-client.txt
--------- beginning of system

FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x74a043a728)
--------- beginning of crash

`

### Steps To Reproduce

```markdown
Just Start A Vanilla Game
```

### Expected Behavior

Nothing

### Platform

```markdown
- Device model: Mi Note 3
- CPU architecture: aarch64
- Android version: 9
- PojavLauncher version:dahlia-740-623f7dd33-v3_openjdk
```

**Comment by GaucovyAero** [comment]
install the latest github actions build (instructions are on the wiki), the play store build's lwjgl is out of date
