### ISSUE TITLE
[BUG] zink and vulkan no work.

### ISSUE THREAD

**Issue by Coloryr** [PojavLauncherTeam/PojavLauncher#4654]
### Describe the bug

Using zink render and open `Use system Vulkan driver` can't run game.
```
2023-09-29 13:12:20.193 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            I  Loaded layer VK_LAYER_KHRONOS_timeline_semaphore
2023-09-29 13:12:20.201 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  ===== BEGIN DUMP OF OVERRIDDEN SETTINGS =====
2023-09-29 13:12:20.201 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  ===== END DUMP OF OVERRIDDEN SETTINGS =====
2023-09-29 13:12:20.202 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  QUALCOMM build          : 1a285a84ae, I2991b7e11e
                                                                                                    Build Date              : 06/04/23
                                                                                                    Shader Compiler Version : E031.41.03.36
                                                                                                    Local Branch            : 
                                                                                                    Remote Branch           : 
                                                                                                    Remote Branch           : 
                                                                                                    Reconstruct Branch      : 
2023-09-29 13:12:20.202 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  Build Config            : S P 14.1.4 AArch64
2023-09-29 13:12:20.202 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
2023-09-29 13:12:20.202 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  Driver Version          : 0676.32
2023-09-29 13:12:20.202 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  PFP                     : 0x01740158
2023-09-29 13:12:20.202 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  ME                      : 0x00000000
2023-09-29 13:12:20.202 30759-30817 AdrenoVK-0              net.kdt.pojavlaunch.debug            I  Application Name    : net.kdt.pojavlaunch.debug:game
                                                                                                    Application Version : 0x00000000
                                                                                                    Engine Name         : mesa zink
                                                                                                    Engine Version      : 0x00000000
                                                                                                    Api Version         : 0x00403000
2023-09-29 13:12:20.214 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            E  internal vkGetDeviceProcAddr called for vkGetInstanceProcAddr
2023-09-29 13:12:20.214 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            E  internal vkGetDeviceProcAddr called for vkEnumeratePhysicalDevices
2023-09-29 13:12:20.214 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            E  internal vkGetDeviceProcAddr called for vkEnumerateDeviceExtensionProperties
2023-09-29 13:12:20.214 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            E  internal vkGetDeviceProcAddr called for vkGetPhysicalDeviceFeatures2
2023-09-29 13:12:20.214 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            E  internal vkGetDeviceProcAddr called for vkGetPhysicalDeviceProperties2
2023-09-29 13:12:20.214 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            E  internal vkGetDeviceProcAddr called for vkGetPhysicalDeviceExternalSemaphoreProperties
2023-09-29 13:12:20.214 30759-30817 vulkan                  net.kdt.pojavlaunch.debug            E  internal vkGetDeviceProcAddr called for vkDestroyInstance
2023-09-29 13:12:20.254 30759-30817 libc                    net.kdt.pojavlaunch.debug            A  ../src/gallium/drivers/zink/zink_resource.c:991: struct zink_resource_object *resource_object_create(struct zink_screen *, const struct pipe_resource *, struct winsys_handle *, _Bool *, uint64_t *, int, const void *): assertion "reqs.memoryTypeBits & BITFIELD_BIT(mai.memoryTypeIndex)" failed
2023-09-29 13:12:20.255 30759-30817 libc                    net.kdt.pojavlaunch.debug            A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 30817 (Render thread), pid 30759 (unch.debug:game)
```

### The log file and images/videos

```
--------- beginning with launcher debug
Info: Launcher version: edelweiss-10-9484d0c52-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 2211133C
Info: API version: 33
Info: Selected Minecraft version: 1.20.2
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=1514
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~ybb7xSXVBxBAM_qO0uD9pQ==/net.kdt.pojavlaunch.debug-KSEg9RI7oX8bwFOX7Td_HQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: POJAV_ZINK_PREFER_SYSTEM_DRIVER=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~ybb7xSXVBxBAM_qO0uD9pQ==/net.kdt.pojavlaunch.debug-KSEg9RI7oX8bwFOX7Td_HQ==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=702
--------- beginning of main
I/jrelog  (30759): dlopen libOSMesa.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjli.so success
I/jrelog  (30759): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libverify.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjava.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libnet.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libnio.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunc
h.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libawt.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libfreetype.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libextnet.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libprefs.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libinstrument.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjavajp
eg.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libnet.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjli.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/liblcms.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libverify.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjaas.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/r
untimes/jre17-arm64-20230817-release.tar.xz/lib/librmi.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libnio.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjimage.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjsig.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libj2gss.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libsctp.so success
I/jrelog  
(30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libzip.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libfreetype.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libmlib_image.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjava.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libdt_socket.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/ru
ntimes/jre17-arm64-20230817-release.tar.xz/lib/libjawt.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libmanagement.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libjdwp.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libawt.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  (30759): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20230817-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  (30759): dlopen /data/app/~~ybb7xSXVBxBAM_qO0uD9pQ==/net.kdt.pojavlaunch.debug-KSEg9RI7oX8bwFOX7Td_HQ==/lib/arm64/libopenal.so success
I/jrelog  (30759): Done processing args
I/jrelog  (30759): Found JLI lib
I/jrelog  (30759): Calling JLI_Launch

2023-09-29 13:12:13,285 main ERROR appender Console has no parameter that matches element Policies
[13:12:13] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[13:12:13] [main/WARN]: File not found or not readable: /proc/stat
[13:12:14] [main/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.a(SourceFile:66) ~[1.20.2.jar:?]
	at ab.a(SourceFile:128) ~[1.20.2.jar:?]
	at ab.c(SourceFile:75) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.a(SourceFile:75) ~[1.20.2.jar:?]
	at ab.c(SourceFile:52) ~[1.20.2.jar:?]
	at ab.a(SourceFile:82) ~[1.20.2.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20.2.jar:?]
	at o.<init>(SourceFile:34) ~[1.20.2.jar:?]
	at o.h(SourceFile:274) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:167) ~[1.20.2.jar:?]
[13:12:17] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 185 milliseconds
[13:12:18] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:12:18] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:12:18] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:12:18] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:12:19] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:159) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:53) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:55) ~[authlib-5.0.47.jar:?]
	at eqv.a(SourceFile:787) ~[1.20.2.jar:?]
	at eqv.<init>(SourceFile:451) ~[1.20.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:214) ~[1.20.2.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-5.0.47.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:130) ~[authlib-5.0.47.jar:?]
	... 5 more
[13:12:19] [Render thread/INFO]: Setting user: dghgggh
Registered forkAndExec
[13:12:20] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[13:12:20] [Render thread/ERROR]: Error parsing option value  for option Text Background Opacity: Not a boolean: ""
[13:12:20] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
OSMDroid: loading vulkan regularly...
OSMDroid: loaded vulkan, ptr=0xbb7099e32a17959d
OSMDroid: generating context
../src/gallium/drivers/zink/zink_resource.c:991: struct zink_resource_object *resource_object_create(struct zink_screen *, const struct pipe_resource *, struct winsys_handle *, _Bool *, uint64_t *, int, const void *): assertion "reqs.memoryTypeBits & BITFIELD_BIT(mai.memoryTypeIndex)" failed

```

### Steps To Reproduce

```markdown
1. change render to zink
2. open `Use system Vulkan driver`
3. Start game
```

### Expected Behavior

game can start

### Platform

```markdown
- Device model: Mi 13
- CPU architecture: aarch64
- Android version: 13
- PojavLauncher version: 9484d0c52d053a81b82fa17b047eb52dbae73c2b
```

**Comment by artdeell** [comment]
This is why we put turnip into pojav. Adreno's official vulkan driver can't run zink properly most of the time. If you want zink to work, just don't turn it on.

**Comment by Coloryr** [comment]
Ok
