### ISSUE TITLE
it returns an error on startup

### ISSUE THREAD

**Issue by Mousetop** [PojavLauncherTeam/PojavLauncher#469]
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.FatalErrorActivity}: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = android.view.InflateException)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = android.view.InflateException)
	at android.os.Parcel.readSerializable(Parcel.java:2694)
	at android.os.Parcel.readValue(Parcel.java:2475)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2796)
	at android.os.BaseBundle.unparcel(BaseBundle.java:271)
	at android.os.BaseBundle.getBoolean(BaseBundle.java:705)
	at net.kdt.pojavlaunch.FatalErrorActivity.onCreate(FatalErrorActivity.java:28)
	at android.app.Activity.performCreate(Activity.java:6857)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	... 9 more
Caused by: java.lang.ClassNotFoundException: org.chromium.base.library_loader.ProcessInitException
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:400)
	at android.os.Parcel$2.resolveClass(Parcel.java:2680)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1772)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1992)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:502)
	at java.lang.Throwable.readObject(Throwable.java:904)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1006)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1894)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1992)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1916)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1992)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:502)
	at java.lang.Throwable.readObject(Throwable.java:904)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1006)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1894)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1992)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1916)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1992)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:502)
	at java.lang.Throwable.readObject(Throwable.java:904)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1006)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1894)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1992)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:502)
	at java.lang.Throwable.readObject(Throwable.java:904)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1006)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1894)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1799)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at android.os.Parcel.readSerializable(Parcel.java:2688)
	... 17 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.base.library_loader.ProcessInitException" on path: DexPathList[[zip file "/data/app/net.kdt.pojavlaunch-2/base.apk"],nativeLibraryDirectories=[/data/app/net.kdt.pojavlaunch-2/lib/arm64, /data/app/net.kdt.pojavlaunch-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 66 more

**Comment by khanhduytran0** [comment]
Update WebView and try again.

**Comment by khanhduytran0** [comment]
@Mousetop please reply
