### ISSUE TITLE
[BUG]LABY MOD 4 BLACK SCREEN 

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#4696]
### Describe the bug

I just launch it and it's a black screen and the console doesn't do anything.

### The log file and images/videos

2023-10-05 13:13:11,703 ERROR appender Console has no parameter that matches element Policies
[13:13:11] [main/INFO]: Loading tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
[13:13:11] [main/INFO]: Using primary tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
[13:13:11] [main/INFO]: Calling tweak class net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
2023-10-05 13:13:12,396 ERROR appender Console has no parameter that matches element Policies
[13:13:14] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
[13:13:14] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
[13:13:14] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
[13:13:14] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
[13:13:14] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
[13:13:14] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
[13:13:14] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
[13:13:15] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[13:13:16] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[13:13:16] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-linux-arm64.jar
[13:13:17] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-linux-arm64.jar
[13:13:18] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-linux-arm64.jar
[13:13:18] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-linux-arm64.jar
[13:13:19] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-linux-arm64.jar
[13:13:19] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-linux-arm64.jar
[13:13:20] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-linux-arm64.jar
[13:13:20] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[13:13:20] [main/INFO]: Library /storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[13:13:20] [main/INFO]: Preloaded org.lwjgl.opengl.GL
[13:13:20] [main/INFO]: Preloaded org.lwjgl.system.MemoryStack
[13:13:20] [main/INFO]: Preloaded org.lwjgl.system.macosx.MacOSXLibraryBundle
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCursorPosCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWKeyCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCharModsCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeNSGL
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWMouseButtonCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWGL
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWMonitorCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWErrorCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCursorEnterCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.package-info
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWin32
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowRefreshCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFW
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowContentScaleCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWVulkan
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeGLX
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWGammaRamp
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowIconifyCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWScrollCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeEGL
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.EventLoop
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeCocoa
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowSizeCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowPosCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowMaximizeCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWFramebufferSizeCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWImage
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWJoystickCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowCloseCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWDropCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowFocusCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWVidMode
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.Callbacks
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCharCallback
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWayland
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeX11
[13:13:20] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWGamepadState
[13:13:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/12/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/labymod/sponge-mixin/0.3.5.0.12.5.mixin.0.8.5/sponge-mixin-0.3.5.0.12.5.mixin.0.8.5.jar Service=LabyMod Env=UNKNOWN
[13:13:20] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[13:13:20] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
Exception in thread "main" 
org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config 1.8.9-labymod4.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfigurations(Mixins.java:77)
	at net.labymod.core.loader.vanilla.launchwrapper.Java17LabyModLaunchWrapperTweaker.injectIntoClassLoader(Java17LabyModLaunchWrapperTweaker.java:245)
	at net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker.injectIntoClassLoader(LabyModLaunchWrapperTweaker.java:117)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:197)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70)
Caused by: java.lang.IllegalArgumentException: The specified resource '1.8.9-labymod4.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1300)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more
Caused by: java.lang.RuntimeException: A fatal error has occurred.
	at net.labymod.core.loader.ReflectLabyModLoader.invokeGetMixinServiceResourceAsStream(ReflectLabyModLoader.java:149)
	at net.labymod.core.loader.vanilla.launchwrapper.mixin.LabyModMixinService.getResourceAsStream(LabyModMixinService.java:32)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1288)
	... 7 more
Caused by: java.lang.NoClassDefFoundError: jdk/jshell/spi/ExecutionControl$NotImplementedException
	at net.labymod.api.util.io.web.request.Request.ofGson(Request.java:24)
	at net.labymod.core.util.jsonfilecache.DefaultJsonFileCacheFactory.create(DefaultJsonFileCacheFactory.java:41)
	at net.labymod.core.util.jsonfilecache.DefaultJsonFileCacheFactory.createJsonFileCache(DefaultJsonFileCacheFactory.java:23)
	at net.labymod.core.flint.index.FlintIndexLoader.<init>(FlintIndexLoader.java:28)
	at net.labymod.core.flint.index.FlintIndexLoader.getInstance(FlintIndexLoader.java:40)
	at net.
labymod.core.flint.downloader.FlintUpdater.<init>(FlintUpdater.java:38)
	at net.labymod.core.addon.AddonLoader.<init>(AddonLoader.java:90)
	at net.labymod.core.addon.DefaultAddonService.<init>(DefaultAddonService.java:52)
	at net.labymod.core.addon.DefaultAddonService.<clinit>(DefaultAddonService.java:50)
	at net.labymod.core.loader.DefaultLabyModLoader.getMixinServiceResourceAsStream(DefaultLabyModLoader.java:263)
	at net.labymod.core.loader.ReflectLabyModLoader.invokeGetMixinServiceResourceAsStream(ReflectLabyModLoader.java:143)
	... 9 more
Caused by: java.lang.ClassNotFoundException: jdk.jshell.spi.ExecutionControl$NotImplementedException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.loadClassLoaderExclusionClass(LaunchClassLoader.java:244)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:291)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:235)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.loadClass(LaunchClassLoader.java:225)
	... 20 more

### Steps To Reproduce

```markdown
I launch, pressing, launch Laba 4
```

### Expected Behavior

So that it starts

### Platform

```markdown
- teclast t40 pro eea
- idk
- 12
- Latest version
```

**Comment by savvacorgi** [comment]
I launched if anything from the auction fix laby

**Comment by GaucovyAero** [comment]
use a different client, labymod is bloating their client full of useless stuff (e.g. visuals) that a) decrease fps and b) dont work on pojav
