### ISSUE TITLE
[BUG] rise

### ISSUE THREAD

**Issue by ilikehotpotateos** [PojavLauncherTeam/PojavLauncher#4705]
### Describe the bug

Rise doesn't download on pojav

### The log file and images/videos

java.io.FileNotFoundException: https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/lastSuccessfulBuild/artifact/all/target/ViaRewind-2.0.3-SNAPSHOT.jar
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:103)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadLibrary(AsyncMinecraftDownloader.java:339)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:150)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:54)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
1. Run rise
```

### Expected Behavior

I expected rise to run good

### Platform

```markdown
- Device model: pixel 6a
- CPU architecture: arm64-v8a armeabi-v7a armeabi
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

_**balls**_

**Comment by artdeell** [comment]
no support, as:
- we don't support hack clients (they tend do weird opengl stuff that we dont support)
- rise is a paid cliend and we don't know if you paid for it
