### ISSUE TITLE
Will Pojav support Microsoft Account in the future?

### ISSUE THREAD

**Issue by xszqxszq** [PojavLauncherTeam/PojavLauncher#471]
I purchased Minecraft Java Edition recently on my Microsoft account, and it seems that Pojav only supports Mojang account login at present.

**Comment by artdeell** [comment]
If we would know how...

**Comment by khanhduytran0** [comment]
Luckily, I found a [documentation about Microsoft OAuth](https://wiki.vg/Microsoft_Authentication_Scheme), so I easily added MSA login. You can try it on this build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/412471830
Note that it could be buggy, because there is very rare chance to meet somebody have a paid Microsoft account like you to able to test.

**Comment by khanhduytran0** [comment]
(Don't use above) A first bug fix for MSA https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/412496701

**Comment by xszqxszq** [comment]
> Luckily, I found a [documentation about Microsoft OAuth](https://wiki.vg/Microsoft_Authentication_Scheme), so I easily added MSA login. You can try it on this build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/412471830
> Note that it could be buggy, because there is very rare chance to meet somebody have a paid Microsoft account like you to able to test.

This build seems to be unable to login. After I clicked "Microsoft Login" button and logged in my account and clicked the "next" button, the browser closed and it returned to the launcher's login page (which status was still not logged in)

**Comment by xszqxszq** [comment]
> Luckily, I found a [documentation about Microsoft OAuth](https://wiki.vg/Microsoft_Authentication_Scheme), so I easily added MSA login. You can try it on this build https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/412471830
> Note that it could be buggy, because there is very rare chance to meet somebody have a paid Microsoft account like you to able to test.

And after that I tried newer builds in "actions" page of this repo, still not working

**Comment by xszqxszq** [comment]
@khanhduytran0 The latest build finally have something responsed after login steps, but this error happened:
```
java.lang.RuntimeException: Error 401: {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.acquireXsts(MicrosoftAuthenticator.java:227)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.doInBackground(MicrosoftAuthenticator.java:62)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.doInBackground(MicrosoftAuthenticator.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```
Please notice that my Xbox account seems to be identified as a child account, which might be the reason of this error.

**Comment by khanhduytran0** [comment]
> Please notice that my Xbox account seems to be identified as a child account

Yeah, probably you need link to a family to be able to login.

**Comment by xszqxszq** [comment]
> > Please notice that my Xbox account seems to be identified as a child account
> 
> Yeah, probably you need link to a family to be able to login.

OK I'll try, but official launcher on Windows didn't block me before so I think that's probably just a bug

**Comment by xszqxszq** [comment]
@khanhduytran0 Now I linked to a family and another error happened:
```
java.lang.RuntimeException: Error 400: {
  "path" : "/minecraft/profile",
  "errorType" : "BAD_REQUEST",
  "error" : "BAD_REQUEST",
  "errorMessage" : "Bad Request",
  "developerMessage" : "Bad Request"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.checkMcProfile(MicrosoftAuthenticator.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.doInBackground(MicrosoftAuthenticator.java:69)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.doInBackground(MicrosoftAuthenticator.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Comment by khanhduytran0** [comment]
It's a known issue currently.

**Comment by Zeyrox1090** [comment]
hmmm

**Comment by khanhduytran0** [comment]
@xszqxszq try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/423298647

**Comment by xszqxszq** [comment]
@khanhduytran0 
```
java.lang.RuntimeException: Error 415: {
  "message" : "Content Type [application/x-www-form-urlencoded] not allowed. Allowed types: [application/json]",
  "_links" : {
    "self" : {
      "href" : "/minecraft/profile",
      "templated" : false
    }
  },
  "_embedded" : { }
}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.checkMcProfile(MicrosoftAuthTask.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:69)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Comment by artdeell** [comment]
Let me fix that up real quick

**Comment by artdeell** [comment]
Please try the latest action.

**Comment by xszqxszq** [comment]
@artdeell Now 400 Bad request again

**Comment by artdeell** [comment]
Don't try latest (yet), it still gives the error 400, but I changed the auth system, so it whould be ready after some time

**Comment by xszqxszq** [comment]
Latest build works, except that it will raise an error saying no such directory or file, and I have to choose the new generated account json manually to launch. Thank you all for your efforts on supporting Microsoft accounts

**Comment by Aslamsiyad** [comment]
> I purchased Minecraft Java Edition recently on my Microsoft account, and it seems that Pojav only supports Mojang account login at present.

Ok

**Comment by Miawril** [comment]
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by Miawril** [comment]
How to fix this?

**Comment by khanhduytran0** [comment]
> How to fix this?

See #1323

**Comment by AMEL1623** [comment]
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by ghost** [comment]
> java.lang.RuntimeException: 
> 
> MSA Error: 401: Unauthorized, error stream:
> {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
> 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
> 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:923)
> 

what?

**Comment by ghost** [comment]
kinda like the same problem in above

**Comment by Alwaleed-ux** [comment]
java.lang.RuntimeException: 

MSA Error: 401: Unauthorized, error stream:
{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:293)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:169)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:122)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:75)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:35)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:72)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:22)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by Alwaleed-ux** [comment]
يارب

**Comment by Alwaleed-ux** [comment]
xz

**Comment by mchnjt** [comment]
> java.lang.RuntimeException:
> 
> MSA Error: 401: Unauthorized, error stream: {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"[https://start.ui.xboxlive.com/AddChildToFamily"}

The error says "Add Child To Family", common issue for accounts with underaged birthdate. Please follow the instructions provided by Microsoft; just Google it.

**Comment by wtf161** [comment]
Wiwi

**Comment by andrystar98** [comment]
REAMID

**Comment by Anos4life** [comment]
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:231)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by Anos4life** [comment]
6;

**Comment by BROYOTH** [comment]
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:231)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.-$$Lambda$MicrosoftBackgroundLogin$OEveGMBM2A4Udo4At1NLOur_Jy4.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by ryanlucas7772** [comment]
Opa

**Comment by crystall1nedev** [comment]
Locking issue because it has turned into spam.
