### ISSUE TITLE
[BUG] <Create mod crashing with ANGLE>

### ISSUE THREAD

**Issue by Faked4075** [PojavLauncherTeam/PojavLauncher#4725]
### Describe the bug

Create mod crashing with render angle on 1.18.2.
when I entered the world and placed blocks from the create mod it crashed.
---------------
crash report:
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 11.10.2023, 17:37
Description: Unexpected error

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at net.minecraft.client.shader.Framebuffer.func_147611_b(Framebuffer.java:164) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.shader.Framebuffer.func_216492_b(Framebuffer.java:143) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.shader.Framebuffer.func_227586_d_(Framebuffer.java:58) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.shader.Framebuffer.func_216491_a(Framebuffer.java:46) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.shader.Framebuffer.enableStencil(Framebuffer.java:307) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.gui.UIRenderHelper.createFramebuffer(UIRenderHelper.java:48) ~[create:mc1.16.5_v0.3.2g] {re:mixin,re:classloading}
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:40) ~[create:mc1.16.5_v0.3.2g] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(SourceFile:116) ~[?:?] {re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:103) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:306) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:997) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-forge-36.2.39.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (aarch64) version Android-12
	Java Version: 17.0.9-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3466269696 bytes (3305 MB) / 4162846720 bytes (3970 MB) up to 4162846720 bytes (3970 MB)
	CPUs: 8
	JVM Flags: 4 total; -Xms3970M -Xmx3970M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |ENQUEUE_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |ENQUEUE_IM|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		flywheel-1.16-0.2.5.jar                           |Flywheel                      |flywheel                      |1.16-0.2.5          |ENQUEUE_IM|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                       |Create                        |create                        |v0.3.2g             |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 48bae3ec-280f-46cd-8a78-e4369b494f99
	Launched Version: 1.16.5
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Mali-G76 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 8x null

### The log file and images/videos

.

### Steps To Reproduce

```markdown
My actions:
Launch pojav with create mod and render angle
Joining world
Placing the block from mod create
And crahed
```

### Expected Behavior

I expected that the blocks from the create mod would be placed and did not crash.

### Platform

```markdown
- Device model: samsung s10
- CPU architecture: ex9820
- Android version: 12
- PojavLauncher version: edelweis-20230928-9484d0c-v3_openjdk
```

### Anything else?

End

**Comment by GaucovyAero** [comment]
disable the flywheel backend and send latestlog.txt (the file, not whats inside it) with angle (you are using gl4es here)

**Comment by Faked4075** [comment]
Вот
