### ISSUE TITLE
[BUG] zink render not working in poco f5

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#4750]
### Describe the bug

I try to use zink render but it,s crashes and i try to fix it but not working my phone is poco f5 snapdragon 7+ gen 2 adreno 725 vulkan 1.1.128

### The log file and images/videos

[04:07:31] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[04:07:31] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[04:07:31] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[04:07:31] [main/INFO]: [OptiFine] OptiFineTweaker: acceptOptions
[04:07:31] [main/INFO]: [OptiFine] OptiFineTweaker: injectIntoClassLoader
[04:07:31] [main/INFO]: [OptiFine] OptiFine ClassTransformer
[04:07:31] [main/INFO]: [OptiFine] OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/optifine/OptiFine/1.20.1_HD_U_I6_pre6/OptiFine-1.20.1_HD_U_I6_pre6.jar
[04:07:31] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchArguments
[04:07:31] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchTarget
[04:07:31] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[04:07:32] [main/WARN]: File not found or not readable: /proc/stat
[04:07:32] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[04:07:32] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeEntity.canUpdate
[04:07:32] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.logging.CrashReportExtender
[04:07:33] [main/INFO]: [OptiFine] (Reflector) Method not present: ane.create
[04:07:36] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 320 milliseconds
[04:07:37] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[04:07:37] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[04:07:37] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[04:07:37] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[04:07:37] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[04:07:39] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
	at enn.a(SourceFile:733) ~[1.20.1-OptiFine_HD_U_I6_pre6.jar:?]
	at enn.<init>(SourceFile:442) ~[1.20.1-OptiFine_HD_U_I6_pre6.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:211) ~[1.20.1-OptiFine_HD_U_I6_pre6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) ~[launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) ~[launchwrapper-of-2.3.jar:2.3]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
	... 11 more
[04:07:39] [Render thread/INFO]: Setting user: kasra
[04:07:39] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[04:07:39] [Render thread/INFO]: [OptiFine] (Reflector) Method not present: enl.getKeyModifier
[04:07:39] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[04:07:39] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.forge.snapshots.ForgeSnapshotsMod
[04:07:39] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyModifier
[04:07:39] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.versions.forge.ForgeVersion
[04:07:39] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[04:07:39] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.internal.BrandingControl
[04:07:39] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.loading.ImmediateWindowHandler

### Steps To Reproduce

```markdown
. . .
```

### Expected Behavior

In game is start launching

### Platform

```markdown
- Device model: poco f5 12/256G
- CPU architecture: arm64-v8a 
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

And sodium mod  crashes

**Comment by GaucovyAero** [comment]
adreno 725 is not yet fully supported by turnip
