### ISSUE TITLE
[BUG] NOT SHOWING RESOURCE PACKS [TEXTURE PACKS SPECIFICALLY]

### ISSUE THREAD

**Issue by ToxicDevilGamer** [PojavLauncherTeam/PojavLauncher#4758]
### Describe the bug

Not Showing & Not Being Able To Use Texture Pack
![Screenshot_20231020-224906](https://github.com/PojavLauncherTeam/PojavLauncher/assets/93937235/485ef357-bbe2-45de-85ec-d9b85558aa04)
![Screenshot_20231020-224853](https://github.com/PojavLauncherTeam/PojavLauncher/assets/93937235/39bca6de-e5ab-45f9-b3d6-319f817f78be)
![Screenshot_20231020-224548](https://github.com/PojavLauncherTeam/PojavLauncher/assets/93937235/e0abdd82-96d7-4ef0-9697-33af196829c9)

### The log file and images/videos

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://net.kdt.pojavlaunch.scoped.gamefolder/document//storage/emulated/0/games/PojavLauncher/.minecraft/resourcepacks/ flg=0x3 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1879)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1546)
	at android.app.Activity.startActivityForResult(Activity.java:4298)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:4245)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:4582)
	at android.app.Activity.startActivity(Activity.java:4550)
	at net.kdt.pojavlaunch.BaseActivity.startActivity(BaseActivity.java:33)
	at net.kdt.pojavlaunch.MainActivity.lambda$openLink$13(MainActivity.java:535)
	at net.kdt.pojavlaunch.MainActivity$$ExternalSyntheticLambda9.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
![Screenshot_20231020-224906](https://github.com/PojavLauncherTeam/PojavLauncher/assets/93937235/d9a8a087-9a08-4d4c-88a4-b90b2517fc43)
![Screenshot_20231020-224853](https://github.com/PojavLauncherTeam/PojavLauncher/assets/93937235/a156bf67-29a0-458c-8cb0-aa0146ca5221)

### Steps To Reproduce

```markdown
1. Install 1.8.9 Optifine M6 pre2
2. In Game 
     Options >Resources Packs >Open resources pack folder
3. Error only in this mobile [2gb ram Samsung Galaxy J7]

In other mobile no error it opens director of resource packs[4gb ram Redmi Note 9]
```

### Expected Behavior

To Show Texture Pack That i Had Added [Nebula 32x]

### Platform

```markdown
- Device model: SAMSUNG GALAXY SM-J700F
- CPU architecture: MALI
- Android version: 6.0.1
- PojavLauncher version: GOOGLE PLAYSTORE LATEST
```

**Comment by Mathias-Boulay** [comment]
Resources packs should not be unzipped
"latest" is not a valid version, there are several "latest" versions.

**Comment by GaucovyAero** [comment]
the error that pops up says that there is no program that can open the directory
the fact that the resource pack doesnt show for you is only your issue, because you installed it incorrectly

**Comment by ToxicDevilGamer** [comment]
Even If In .zip it doesnt show

**Comment by GaucovyAero** [comment]
its still an issue with your installation
