### ISSUE TITLE
[BUG] [MODPACKS] FTB Modpacks Doesn't download Minecraft 

### ISSUE THREAD

**Issue by Alberto836DX** [PojavLauncherTeam/PojavLauncher#4787]
### Describe the bug

> When you create a ModPack Profile and you install an FTB (Feed The Beast) ModPack like SkyFactory 4 or others like FTB Infinity Evolved it doesn't start and says "Failed to download Minecraft!" I think it can be solved by idk, adding compatibility or something. Here is a screenshot. 
![Screenshot_20231029-171929](https://github.com/PojavLauncherTeam/PojavLauncher/assets/89942895/fc2695ca-0709-4486-b018-611a8153adad)

### The log file and images/videos

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.12.2-forge-14.23.5.2846/1.12.2-forge-14.23.5.2846.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:795)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:73)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:54)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.12.2-forge-14.23.5.2846/1.12.2-forge-14.23.5.2846.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:823)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:708)
	... 6 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7972)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 10 more

### Steps To Reproduce

```markdown
Attempt to Launch Minecraft FTB ModPack and others
```

### Expected Behavior

The game would launch correctly. 

### Platform

```markdown
- Device model: Motorola G71 5G
- CPU architecture: 64-bit
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk (PlayStore)
```

### Anything else?

It also happens with other mod packs that aren't FTB ModPacks.

**Comment by GaucovyAero** [comment]
click show more and send log

**Comment by Alberto836DX** [comment]
I did not know that the "show more" gives a log, but for some reason the log that makes isn't the modpack log. I only can copy+paste the text that Pojav shows. Even the "latestlog".

**Comment by Mathias-Boulay** [comment]
Hmm, can you show us the version folder ?

**Comment by GaucovyAero** [comment]
> I did not know that the "show more" gives a log, but for some reason the log that makes isn't the modpack log. I only can copy+paste the text that Pojav shows. Even the "latestlog".

send everything you possibly can lol

**Comment by GaucovyAero** [comment]
closing because of inactivity
