### ISSUE TITLE
Issue with mods 1.12.2 forge

### ISSUE THREAD

**Issue by Kirillka22** [PojavLauncherTeam/PojavLauncher#479]
I need these mods for the server. How can i fix that?
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.1-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/10/20 5:47 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at org.lwjgl.opengl.SharedDrawable.<init>(SharedDrawable.java:50)
	at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:229)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:217)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.SharedDrawable.<init>(SharedDrawable.java:50)
	at net.minecraftforge.fml.client.SplashProgress.start(SplashProgress.java:229)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:217)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 344660872 bytes (328 MB) / 838860800 bytes (800 MB) up to 1610612736 bytes (1536 MB)
	JVM Flags: 8 total; -Xms800m -Xmx1536m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=150 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.1-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'ptitSeb' Version: '2.1 gl4es wrapper 1.1.4' Renderer: 'GL4ES wrapper'
	Launched Version: 1.12.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by khanhduytran0** [comment]
You need disable Forge splash screen. Auto disable build is at https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/412278153

**Comment by khanhduytran0** [comment]
> TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)


Oh.. attempting to get TLauncher skin management work on?

**Comment by Kirillka22** [comment]
> You need disable Forge splash screen. Auto disable build is at https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/412278153

I already disabled it. Minecraft works with mods, but with this configuration it is crushing.

**Comment by Kirillka22** [comment]
> Oh.. attempting to get TLauncher skin management work on?

Yes, but I don't really need it

**Comment by Kirillka22** [comment]
And there is a list of mods I am trying to run.
![image](https://user-images.githubusercontent.com/63144929/101783406-e9000c80-3b02-11eb-9675-f3859c5a6506.png)

**Comment by Kirillka22** [comment]
help me, please

**Comment by Kirillka22** [comment]
So i installed that build and the problem is still there.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.1-core.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 12/12/20 9:45 AM
Description: Initializing game

java.lang.RuntimeException: Error creating shaders thebetweenlands:shaders/postprocessing/starfield/starfield.vsh and thebetweenlands:shaders/postprocessing/starfield/starfield.fsh
	at thebetweenlands.client.render.shader.postprocessing.PostProcessingEffect.initShaders(PostProcessingEffect.java:440)
	at thebetweenlands.client.render.shader.postprocessing.PostProcessingEffect.init(PostProcessingEffect.java:58)
	at thebetweenlands.client.gui.menu.GuiMainMenuBackground.func_73866_w_(GuiMainMenuBackground.java:53)
	at thebetweenlands.client.gui.menu.GuiBLMainMenu.func_73866_w_(GuiBLMainMenu.java:91)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:545)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.RuntimeException: Error creating fragment shader: 0:55: L0002: Undeclared variable 'F'
0:56: L0002: Undeclared variable 'F'
0:61: L0002: Undeclared variable 'F'
0:62: L0002: Undeclared variable 'from'
0:63: L0002: Undeclared variable 'from'
0:66: L0002: Undeclared variable 'F'
0:67: L0002: Undeclared variable 'F'
0:68: L0002: Undeclared variable 'F'
0:70: L0002: Undeclared variable 'from'
0:71: L0002: Undeclared variable 'p'
0:72: L0002: Undeclared variable 'F'
0:74: L0002: Undeclared variable 'p'
0:75: L0002: Undeclared variable 'a'
0:76: L0002: Undeclared variable 'p'
0:78: L0002: Undeclared variable 'F'
0:79: L0002: Undeclared variable 'a'
0:80: L0002: Undeclared variable 'fade'
0:82: L0002: Undeclared variable 'v'
0:83: L0002: Undeclared variable 'v'
0:84: L0002: Undeclared variable 'fade'
0:85: L0002: Undeclared variable 's'
0:85: L0001: Expected literal or '(', got '}'
	at thebetweenlands.client.render.shader.postprocessing.PostProcessingEffect.createShader(PostProcessingEffect.java:501)
	at thebetweenlands.client.render.shader.postprocessing.PostProcessingEffect.initShaders(PostProcessingEffect.java:434)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thebetweenlands.client.render.shader.postprocessing.PostProcessingEffect.initShaders(PostProcessingEffect.java:440)
	at thebetweenlands.client.render.shader.postprocessing.PostProcessingEffect.init(PostProcessingEffect.java:58)
	at thebetweenlands.client.gui.menu.GuiMainMenuBackground.func_73866_w_(GuiMainMenuBackground.java:53)
	at thebetweenlands.client.gui.menu.GuiBLMainMenu.func_73866_w_(GuiBLMainMenu.java:91)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:545)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 120443392 bytes (114 MB) / 838860800 bytes (800 MB) up to 838860800 bytes (800 MB)
	JVM Flags: 8 total; -Xms512m -Xmx800m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version        | Source                                        | Signature                                |
	|:------ |:-------------------------- |:-------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2         | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                        | 9.42           | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                        | 8.0.99.99      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2854   | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore              |                | minecraft.jar                                 | None                                     |
	| LCHIJA | foamfixcore                | 7.7.4          | minecraft.jar                                 | None                                     |
	| LCHIJA | biomesoplenty              | 7.0.1.2444     | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHIJA | codechickenlib             | 3.2.3.358      | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | divinerpg                  | 1.7.1          | DivineRPG-1.7.1.jar                           | None                                     |
	| LCHIJA | foamfix                    | 0.10.10-1.12.2 | foamfix-0.10.10-1.12.2.jar                    | None                                     |
	| LCHIJA | ic2                        | 2.8.221-ex112  | industrialcraft-2-2.8.221-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | galacticraftcore           | 4.0.2.281      | GalacticraftCore-1.12.2-4.0.2.281.jar         | None                                     |
	| LCHIJA | galacticraftplanets        | 4.0.2.272      | Galacticraft-Planets-1.12.2-4.0.2.272.jar     | None                                     |
	| LCHIJA | jei                        | 4.15.0.294     | jei_1.12.2-4.15.0.294.jar                     | None                                     |
	| LCHIJA | journeymap                 | 1.12.2-5.7.1   | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | nei                        | 2.4.3          | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | randomloot                 | 1.7.3          | randomloot+1.7.4.jar                          | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4            | tlskincape1.12.2-1.4.jar                      | None                                     |
	| LCHIJA | thebetweenlands            | 3.7.1          | TheBetweenlands-3.7.1-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.1-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	Launched Version: ДРАТУТИ
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by khanhduytran0** [comment]
Hm something weird in mod shader

**Comment by khanhduytran0** [comment]
Could shader in that mod be disabled?
