### ISSUE TITLE
[BUG] <Log in error>

### ISSUE THREAD

**Issue by senina4** [PojavLauncherTeam/PojavLauncher#4798]
### Describe the bug

When I log in to my Microsoft account it crash 

### The log file and images/videos

PojavLauncher crash report
 - Time: 2023年11月2日 21:07:12
 - Device: RMX3661 RMX3661
 - Android version: 13
 - Crash stack trace:
 - Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1996)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:764)
	at

### Steps To Reproduce

```markdown
1. Start app
2. Login to Microsoft account
3. Crash
```

### Expected Behavior

# Log in to my Minecraft account

### Platform

```markdown
- Device model: Realme 10 pro 256G
- CPU architecture: arm64-v8a(64 bit)
- Android version: 13
- PojavLauncher version: Latest Release (From google play(11/2))
```

**Comment by GaucovyAero** [comment]
stale issue
