### ISSUE TITLE
Optifine installed but not working (crashes) 

### ISSUE THREAD

**Issue by jrxohan** [PojavLauncherTeam/PojavLauncher#48]
The problem of installing is already solved now what happens is that when I try to start 1.7.10 with optifine in its latest version the mojang screens load but it gives a crash report and I don't know what happens try to erase all the optifine data again  but the same does not work here I leave the crash report

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2/4/20 12:00 p. m.
Description: Initializing game

java.lang.ExceptionInInitializerError
	at bao.ag(SourceFile:401)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:784)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List bix.spriteList' on a null object reference
	at bix.addSprite(ModelRenderer.java:340)
	at bif.<init>(SourceFile:15)
	at bou.<init>(SourceFile:18)
	at bnn.<init>(RenderManager.java:142)
	at bnn.<clinit>(RenderManager.java:101)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at b.a(CrashReport.java:357)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:357)
	at bao.f(SourceFile:716)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:784)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version 4.9.148
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (HUAWEI STK-LX3), The Android Project
	Memory: 21831680 bytes (20 MB) / 133738528 bytes (127 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10-OptiFine_HD_U_E7
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Anisotropic filtering is not supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.

	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (349724696)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by artdeell** [comment]
You may try the fix from [this video](https://youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by jrxohan** [comment]
> You may try the fix from [this video](https://youtube.com/watch?v=dQw4w9WgXcQ)

OMG it works...

**Comment by artdeell** [comment]
Nice, you have been rickrolled in 2020

Okay, now we will be serious. What's your Android version?

**Comment by artdeell** [comment]
As an attempt you may try to use oldest available Optifine for 1.7.10.

**Comment by jrxohan** [comment]
> Nice, you have been rickrolled in 2020
> 
> Okay, now we will be serious. What's your Android version?

Android 9

**Comment by jrxohan** [comment]
> As an attempt you may try to use oldest available Optifine for 1.7.10.

Im using the most recent optifine

**Comment by jrxohan** [comment]
I have been trying with 1.11 and the same thing happens and with that of the library corrected the same only loads the mojang logo and from there it does not happen all crashes is android 9 in case of doubts

**Comment by khanhduytran0** [comment]
Do it have any crash report?

**Comment by jrxohan** [comment]
> Do it have any crash report?

This is the crash report

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/4/20 4:50 p. m.
Description: Initializing game

java.lang.NullPointerException: Attempt to invoke virtual method 'cbe cbh.bakeModel(brg, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)
	at beq.an(SourceFile:516)
	at beq.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:784)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:338)
	at beq.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:784)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Linux (aarch64) version 4.9.148
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (HUAWEI STK-LX3), The Android Project
	Memory: 23821888 bytes (22 MB) / 130126112 bytes (124 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.11-OptiFine_HD_U_F5
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer, OpenGL 1.4
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null
	OptiFine Version: OptiFine_1.11_HD_U_F5
	OptiFine Build: 20191204-142752
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
So `java.lang.NullPointerException` anywhere

**Comment by jrxohan** [comment]
> So `java.lang.NullPointerException` anywhere

But this only happens in Android 9 and below, right?  Since all Android 10 works, but can this be fixed for Android 9?

**Comment by khanhduytran0** [comment]
I will decompile to see something NULL inside (this phone might be unsupported)
Playable in Android-x86

**Comment by UDPSendToFailed** [comment]
I have exactly the same crash log on Samsung Galaxy Tab A 2018 (Android 9, Snapdragon 450 8x A53, Adreno 506).


```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2020. 04. 03. 9:35
Description: Initializing game

java.lang.ExceptionInInitializerError
	at bao.ag(SourceFile:401)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.List bix.spriteList' on a null object reference
	at bix.addSprite(ModelRenderer.java:340)
	at bif.<init>(SourceFile:15)
	at bou.<init>(SourceFile:18)
	at bnn.<init>(RenderManager.java:142)
	at bnn.<clinit>(RenderManager.java:101)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at b.a(CrashReport.java:357)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:357)
	at bao.f(SourceFile:716)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (armv8l) version 3.18.120-17818260
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-T590), The Android Project
	Memory: 19513344 bytes (18 MB) / 126315752 bytes (120 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10-OptiFine_HD_U_E7
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.

	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (345419624)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8
```

**Comment by artdeell** [comment]
We have some issues with Android P

**Comment by WesleyVanNeck** [comment]
fixed in v3
