### ISSUE TITLE
[ISSUE] <Cant login intro a premium account>

### ISSUE THREAD

**Issue by RealTTraction** [PojavLauncherTeam/PojavLauncher#4819]
### Describe the bug

THIS BUG IS ABOUT THAT I CANT LOG IN INTRO AN ACCOUNT EVERY TIME I LOG IN IS SAYS:
java.lang.RuntimeException: {"Identity":"0","XErr":2148916227,"Redirect":"https://start.ui.xboxlive.com/enforcement"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:80)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/150144130/db507726-f3d3-4338-bd13-b836d1a3cb1b

### Steps To Reproduce

```markdown
java.lang.RuntimeException: {"Identity":"0","XErr":2148916227,"Redirect":"https://start.ui.xboxlive.com/enforcement"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:80)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Expected Behavior

.

### Platform

```markdown
- Device model: samsung SM-M127F
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by khanhduytran0** [comment]
Never seen such error before, but anyway, [Error 8015D003 occurs when you try to sign in to Xbox Live](https://support.xbox.com/en-US/help/errors/xbox-360/error-code-8015d003) should be relevant. (2148916227 = 0x8015D003)

**Comment by GaucovyAero** [comment]
maybe the link that its trying to redirect you to has something to tell you, this is not a pojav issue tho, theres something wrong with your xbox live profile

**Comment by Mathias-Boulay** [comment]
We should at least have a proper presentation for this error I guess

**Comment by kjjjjjjjjjjjj** [comment]
So much bug around here

**Comment by RealTTraction** [comment]
Guys please i need help

**Comment by kjjjjjjjjjjjj** [comment]
What happened to you tell me about

**Comment by GaucovyAero** [comment]
> What happened to you tell me about

nothing
