### ISSUE TITLE
java.lang.RuntimeException: Bad Request 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:334) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:150) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:76) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 	at java.lang.Thread.run(Thread.java:1012)

### ISSUE THREAD

**Issue by NEELGAMER0903** [PojavLauncherTeam/PojavLauncher#4878]
### Describe the bug

The bug describe

### The log file and images/videos

Hwhwh

### Steps To Reproduce

```markdown
Hhw
```

### Expected Behavior

Hwh

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

Heh

**Comment by GaucovyAero** [comment]
just relog
