### ISSUE TITLE
Cant Log in to microsoft

### ISSUE THREAD

**Issue by bananenpannenkoek** [PojavLauncherTeam/PojavLauncher#4915]
### Describe the bug

When i try logging in to microsoft it gives me the following error(also for that one guy, Yes i own minecraft)

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

...

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

...

### Platform

```markdown
- Device model: Moto g84
- CPU architecture: ?
- Android version: 13
- PojavLauncher version: newest idk
```

**Comment by GaucovyAero** [comment]
buy minecraft

**Comment by bananenpannenkoek** [comment]
> buy minecraft

I did :/
