### ISSUE TITLE
1.20.3 [crash] <when i create world it crashes>

### ISSUE THREAD

**Issue by system32crowdstrikewin11** [PojavLauncherTeam/PojavLauncher#4932]
### Describe the bug

So it was an normal day that I was running PojavLauncher and was happy about 1.20.3 and after that without mods it was lagging very badly that i understood then installed sodium that i ran in 1.20.1 and when I created a world in 1.20.3 it unexpectedly crashed when it was showing joining the world
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13603258/latestlog.txt)

### The log file and images/videos

1.20.3 and 1.20.2 crashing when creating world's and yes I use the holy render and java 17 so it shouldn't supposed to be crash because you told us that java 17 and holy render supports all version 

### Steps To Reproduce

```markdown
[23:06:26] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.0-1.20.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.0.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.scheduleRebuild(int, int, int, boolean)" because "this.renderSectionManager" is null
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.scheduleRebuildForChunk(SodiumWorldRenderer.java:461) ~[sodium-fabric-mc1.20.3-0.5.4.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.scheduleRebuildForChunks(SodiumWorldRenderer.java:451) ~[sodium-fabric-mc1.20.3-0.5.4.jar:?]
	at net.minecraft.class_761.method_18145(class_761.java:4288) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18113(class_638.java:577) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_2870(class_634.java:2209) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_38543(class_634.java:2128) ~[client-
intermediary.jar:?]
	at net.minecraft.class_634.method_38545(class_634.java:2119) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.redirect$bai000$starlight$starlightCallUpdateImmediately(class_634.java:4987) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11143(class_634.java:2119) ~[client-intermediary.jar:?]
	at net.minecraft.class_2676.method_11560(class_2676.java:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_2676.method_11054(class_2676.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 10 more
[23:06:34] [Server thread/INFO]: Stopping server
[23:06:34] [Server thread/INFO]: Saving players
[23:06:34] [Server thread/INFO]: Saving worlds
--------- beginning of system

INFO: Initialized TensorFlow Lite runtime.
```

### Expected Behavior

Are you running on 1.13 
This is very begining of crash

### Platform

```markdown
- Device model: tecno camon 15
- CPU architecture: arm x64
- Android version: 10
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

So why it's crashing when I also tried with 1.20.2 it was also behaving the same what's the problem

**Comment by system32crowdstrikewin11** [comment]
Last thing to describe that in the top left corner a red error code like a square was appearing and the whole game was running normally

**Comment by GaucovyAero** [comment]
dont use sodium, it uses gl functions that are not supported, hence why it says `No context is current or a function that is not available in the current context was called.`

**Comment by system32crowdstrikewin11** [comment]
But sodium works well in my device and all versions work correctly

**Comment by system32crowdstrikewin11** [comment]
Except 1.20.2 and 1.20.3

**Comment by system32crowdstrikewin11** [comment]
Can you suggest me a lag fix mod like optifine because it's not available for the newer versions
