### ISSUE TITLE
[BUG] <"Resource Reload Failed" when loading wynncraft resourcepack>

### ISSUE THREAD

**Issue by edremy-Ohagi** [PojavLauncherTeam/PojavLauncher#4937]
### Describe the bug

When trying loading Wynncraft server resourcepack, it will show "Resource Reload Failed"  and failed loading resourcepack.
[98b76b0b89c55c5665689ec9ef6630a46e0c4609.zip](https://github.com/PojavLauncherTeam/PojavLauncher/files/13622958/98b76b0b89c55c5665689ec9ef6630a46e0c4609.zip)

### The log file and images/videos

[14:18:20] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[fabric-loader-0.15.1-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at net.minecraft.class_757.method_34538(class_757.java:568) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/position_color.json: Couldn't compile vertex program (file/Wynn1.20.zip, render/chat) : ERROR: 0:45: 'vx' : undeclared identifier 
ERROR: 0:45: '<<' :  wrong operand types  no operation '<<' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:45: '|' :  wrong operand types  no operation '|' exists that takes a left-hand operand of type 'int' and a right operand of type 'in 3-component vector of float' (or there is no acceptable conversion)
ERROR: 0:45: 'y' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 4 compilation errors.  No code generated.
	at net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:203) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:508) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: java.io.IOException: Couldn't compile vertex program (file/Wynn1.20.zip, render/chat) : ERROR: 0:45: 'vx' : undeclared identifier 
ERROR: 0:45: '<<' :  wrong operand types  no operation '<<' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:45: '|' :  wrong operand types  no operation '|' exists that takes a left-hand operand of type 'int' and a right operand of type 'in 3-component vector of float' (or there is no acceptable conversion)
ERROR: 0:45: 'y' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 4 compilation errors.  No code generated.
	at net.minecraft.class_281.method_34416(class_281.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.method_34579(class_5944.java:242) ~[client-intermediary.jar:?]
	at net.minecraft.class_5944.<init>(class_5944.java:185) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_34538(class_757.java:508) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_45777(class_757.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_757$1.method_18788(class_757.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
[14:18:20] [Render thread/INFO]: Reloading ResourceManager: vanilla
[14:18:20] [Worker-Main-8/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[14:18:21] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[14:18:21] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[14:18:21] [Render thread/INFO]: OpenAL initialized on device OpenSL
[14:18:21] [Render thread/INFO]: Sound engine started
[14:18:21] [Render thread/INFO]: Created: 4096x2048x0 minecraft:textures/atlas/blocks.png-atlas
[14:18:21] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/signs.png-atlas
[14:18:21] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[14:18:21] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[14:18:21] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/armor_trims.png-atlas
[14:18:21] [Render thread/INFO]: Created: 128x64x0 minecraft:textures/atlas/decorated_pot.png-atlas
[14:18:21] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[14:18:21] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:18:21] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[14:18:22] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[14:18:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:18:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:18:22] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:18:22] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[14:18:36] [Render thread/INFO]: Stopping!
version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150version string: 150EGLBridge: Terminating
I/NativeInput(31308): Input ready: 0

### Steps To Reproduce

```markdown
1. Install 1.20.2 Minecraft.
2. Load the resourcepack.
3. The Message "Resource Reload Failed" appears, and loading failed.
```

### Expected Behavior

It should success loading texture pack.

### Platform

```markdown
Info: Launcher version: edelweiss-20231129-3635f53-feat/secure_modpacks_downloads
Info: Architecture: arm64
Info: Device model: Xiaomi 23043RP34C
Info: API version: 33

Android: MIUI 14, based on Android 13.
```

**Comment by GaucovyAero** [comment]
dont just put all the text from the log here, thats spam
instead turn on the shader dump in experimental settings, crash it again and send the file
we might be able to fix these shader conversion issues later (gl4es doesnt support opengl functions that wynncraft needs but sometimes its possible to convert the shaders so that gl4es works with them)

**Comment by edremy-Ohagi** [comment]
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13623630/latestlog.txt)
Here is the file with shader dump on. Thanks!

**Comment by Marcemcc** [comment]
play in 1.16.5

**Comment by GaucovyAero** [comment]
check on the latest actions build

**Comment by GaucovyAero** [comment]
closing because of inactivity
