### ISSUE TITLE
[Error?] Refuses to launch

### ISSUE THREAD

**Issue by nepredatel** [PojavLauncherTeam/PojavLauncher#4944]
### Describe the bug

I made a modpack with like 35 mods and it just refuses to launch both on mobile and pc, i need help fr

### The log file and images/videos

[16:15:17] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:15:17] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:15:17] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:15:17] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[16:15:17] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_392-internal, running on Linux:aarch64:Android-12, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal
[16:15:17] [main/INFO]: Searching /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods for mods
[16:15:17] [main/INFO]: Searching /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/1.12.2 for mods
[16:15:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in betterbiomeblend-1.12.2-1.1.7-forge.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:15:17] [main/WARN]: The coremod Better Biome Blend (fionathemortal.betterbiomeblend.core.CoreMod) is not signed!
[16:15:17] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[16:15:17] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Born+In+A+Barn+1.8-1.12-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:15:17] [main/WARN]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:15:17] [main/WARN]: The coremod Born in a Barn (com.chocohead.biab.BornInABarn) is not signed!
[16:15:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from EntityCulling-1.12.2-6.4.2.jar
[16:15:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Galacticraft-1.12.2-4.0.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:15:18] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[16:15:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from getittogetherdrops-1.12.2-v1.0.2.jar
[16:15:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from lesslag-1.0-1.12.2.jar
[16:15:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in LucraftCore-1.12.2-2.4.17 (1).jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:15:18] [main/WARN]: The coremod lucraft.mods.lucraftcore.core.LucraftCoreCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:15:18] [main/WARN]: The coremod LucraftCoreCoreMod (lucraft.mods.lucraftcore.core.LucraftCoreCoreMod) is not signed!
[16:15:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from particleculling-1.12.2-v1.4.1.jar
[16:15:18] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[16:15:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in techguns-1.12.2-2.0.2.0_pre3.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:15:18] [main/WARN]: The coremod Techguns Core (techguns.core.TechgunsFMLPlugin) is not signed!
[16:15:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in TickDynamic-1.12.2-1.0.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[16:15:18] [main/WARN]: The coremod LoadingPlugin (com.wildex999.tickdynamic.LoadingPlugin) is not signed!
[16:15:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-150.jar
[16:15:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-forge-mc1.12.2-0.2.7-universal.jar
[16:15:18] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:15:18] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[16:15:18] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[16:15:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/1.12.2/getittogetherdrops-1.12.2-v1.0.2.jar Service=LaunchWrapper Env=CLIENT
[16:15:18] [main/DEBUG]: Instantiating coremod class GITDLoadingPlugin
[16:15:18] [main/DEBUG]: The coremod bl4ckscor3.mod.getittogetherdrops.GITDLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[16:15:18] [main/WARN]: The coremod GITDLoadingPlugin (bl4ckscor3.mod.getittogetherdrops.GITDLoadingPlugin) is not signed!
[16:15:18] [main/INFO]: Compatibility level set to JAVA_8
[16:15:18] [main/DEBUG]: Enqueued coremod GITDLoadingPlugin
[16:15:18] [main/DEBUG]: Instantiating coremod class EntityCullingPlugin
[16:15:18] [main/DEBUG]: The coremod meldexun.entityculling.asm.EntityCullingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[16:15:18] [main/WARN]: The coremod EntityCullingPlugin (meldexun.entityculling.asm.EntityCullingPlugin) is not signed!
[16:15:18] [main/DEBUG]: Enqueued coremod EntityCullingPlugin
[16:15:18] [main/DEBUG]: Instantiating coremod class LesslagCorePlugin
[16:15:18] [main/DEBUG]: The coremod com.minecolonies.lesslag.LesslagCorePlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[16:15:18] [main/WARN]: The coremod LesslagCorePlugin (com.minecolonies.lesslag.LesslagCorePlugin) is not signed!
[16:15:18] [main/ERROR]: Mixin config mixins.lesslag.json does not specify "minVersion" property
[16:15:18] [main/DEBUG]: Enqueued coremod LesslagCorePlugin
[16:15:18] [main/DEBUG]: Instantiating coremod class ParticleCullingLoadingPlugin
[16:15:18] [main/DEBUG]: The coremod bl4ckscor3.mod.particleculling.ParticleCullingLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[16:15:18] [main/WARN]: The coremod ParticleCullingLoadingPlugin (bl4ckscor3.mod.particleculling.ParticleCullingLoadingPlugin) is not signed!
[16:15:18] [main/DEBUG]: Enqueued coremod ParticleCullingLoadingPlugin
[16:15:18] [main/DEBUG]: Instantiating coremod class VanillaFixLoadingPlugin
[16:15:18] [main/INFO]: Initializing VanillaFix
[16:15:18] [main/INFO]: Initializing StacktraceDeobfuscator
[16:15:18] [main/INFO]: Downloading MCP method mappings to: methods-stable_39.csv
[16:15:18] [main/ERROR]: Failed to get MCP data!
java.lang.RuntimeException: java.net.UnknownHostException: export.mcpbot.bspk.rs
	at org.dimdev.vanillafix.crashes.StacktraceDeobfuscator.init(StacktraceDeobfuscator.java:52) ~[StacktraceDeobfuscator.class:?]
	at org.dimdev.vanillafix.VanillaFixLoadingPlugin.initStacktraceDeobfuscator(VanillaFixLoadingPlugin.java:60) [VanillaFix-1.0.10-150.jar:?]
	at org.dimdev.vanillafix.VanillaFixLoadingPlugin.<clinit>(VanillaFixLoadingPlugin.java:43) [VanillaFix-1.0.10-150.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_392-internal]
	at java.lang.Class.forName(Unknown Source) [?:1.8.0_392-internal]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) [forge-1.12.2-14.23.5.2860.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.injectCorePlugin(MixinPlatformAgentFMLLegacy.java:244) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.initFMLCoreMod(MixinPlatformAgentFMLLegacy.java:171) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFMLLegacy.accept(MixinPlatformAgentFMLLegacy.java:157) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.platform.MixinContainer.<init>(MixinContainer.java:74) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:143) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:135) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:220) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.init(MixinPlatformManager.java:107) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.getPlatform(MixinBootstrap.java:107) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.MixinBootstrap.start(MixinBootstrap.java:154) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:46) [getittogetherdrops-1.12.2-v1.0.2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_392-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_392-internal]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_392-internal]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_392-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.net.UnknownHostException: export.mcpbot.bspk.rs
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_392-internal]
	at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.NetworkClient.doConnect(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.http.HttpClient.New(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[?:1.8.0_392-internal]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_392-internal]
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_392-internal]
	at org.dimdev.vanillafix.crashes.StacktraceDeobfuscator.init(StacktraceDeobfuscator.java:31) ~[StacktraceDeobfuscator.class:?]
	... 27 more
[16:15:18] [main/INFO]: Done initializing StacktraceDeobfuscator
[16:15:18] [main/INFO]: Initializing Bug Fix Mixins
[16:15:18] [main/INFO]: Initializing Crash Fix Mixins
[16:15:18] [main/INFO]: Initializing Profiler Improvement Mixins
[16:15:18] [main/INFO]: Initializing Texture Fix Mixins
[16:15:18] [main/INFO]: Initializing Mod Support Mixins
[16:15:18] [main/DEBUG]: The coremod org.dimdev.vanillafix.VanillaFixLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[16:15:18] [main/WARN]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[16:15:18] [main/DEBUG]: Enqueued coremod VanillaFixLoadingPlugin
[16:15:18] [main/DEBUG]: Instantiating coremod class PhosphorFMLLoadingPlugin
[16:15:18] [main/DEBUG]: The coremod me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[16:15:18] [main/WARN]: The coremod PhosphorFMLLoadingPlugin (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin) is not signed!
[16:15:18] [main/DEBUG]: Enqueued coremod PhosphorFMLLoadingPlugin
[16:15:18] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:15:18] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:15:18] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:15:18] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:15:18] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[16:15:18] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:15:18] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:15:18] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:15:18] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:15:18] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[16:15:18] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[16:15:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[16:15:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[16:15:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[16:15:19] [main/DEBUG]: Injection complete
[16:15:19] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[16:15:19] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[16:15:23] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:15:24] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:15:24] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[16:15:24] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:15:24] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[16:15:24] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[16:15:24] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:15:24] [main/DEBUG]: Injecting coremod Better Biome Blend \{fionathemortal.betterbiomeblend.core.CoreMod\} class transformers
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for Better Biome Blend \{fionathemortal.betterbiomeblend.core.CoreMod\}
[16:15:24] [main/DEBUG]: Running coremod plugin Better Biome Blend
[16:15:24] [main/INFO]: Found valid Mixin framework! Proceeding to load.
[16:15:24] [main/DEBUG]: Coremod plugin class CoreMod run successfully
[16:15:24] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:15:24] [main/DEBUG]: Injecting coremod MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\} class transformers
[16:15:24] [main/INFO]: Successfully Registered Transformer
[16:15:24] [main/TRACE]: Registering transformer micdoodle8.mods.miccore.MicdoodleTransformer
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for MicdoodlePlugin \{micdoodle8.mods.miccore.MicdoodlePlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin MicdoodlePlugin
[16:15:24] [main/DEBUG]: Coremod plugin class MicdoodlePlugin run successfully
[16:15:24] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[16:15:24] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@7ee3d262
[16:15:24] [main/DEBUG]: Injecting coremod GITDLoadingPlugin \{bl4ckscor3.mod.getittogetherdrops.GITDLoadingPlugin\} class transformers
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for GITDLoadingPlugin \{bl4ckscor3.mod.getittogetherdrops.GITDLoadingPlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin GITDLoadingPlugin
[16:15:24] [main/DEBUG]: Coremod plugin class GITDLoadingPlugin run successfully
[16:15:24] [main/DEBUG]: Injecting coremod EntityCullingPlugin \{meldexun.entityculling.asm.EntityCullingPlugin\} class transformers
[16:15:24] [main/TRACE]: Registering transformer meldexun.entityculling.asm.EntityCullingClassTransformer
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for EntityCullingPlugin \{meldexun.entityculling.asm.EntityCullingPlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin EntityCullingPlugin
[16:15:24] [main/DEBUG]: Coremod plugin class EntityCullingPlugin run successfully
[16:15:24] [main/DEBUG]: Injecting coremod LesslagCorePlugin \{com.minecolonies.lesslag.LesslagCorePlugin\} class transformers
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for LesslagCorePlugin \{com.minecolonies.lesslag.LesslagCorePlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin LesslagCorePlugin
[16:15:24] [main/DEBUG]: Coremod plugin class LesslagCorePlugin run successfully
[16:15:24] [main/DEBUG]: Injecting coremod ParticleCullingLoadingPlugin \{bl4ckscor3.mod.particleculling.ParticleCullingLoadingPlugin\} class transformers
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for ParticleCullingLoadingPlugin \{bl4ckscor3.mod.particleculling.ParticleCullingLoadingPlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin ParticleCullingLoadingPlugin
[16:15:24] [main/DEBUG]: Coremod plugin class ParticleCullingLoadingPlugin run successfully
[16:15:24] [main/DEBUG]: Injecting coremod VanillaFixLoadingPlugin \{org.dimdev.vanillafix.VanillaFixLoadingPlugin\} class transformers
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for VanillaFixLoadingPlugin \{org.dimdev.vanillafix.VanillaFixLoadingPlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin VanillaFixLoadingPlugin
[16:15:24] [main/DEBUG]: Coremod plugin class VanillaFixLoadingPlugin run successfully
[16:15:24] [main/DEBUG]: Injecting coremod PhosphorFMLLoadingPlugin \{me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin\} class transformers
[16:15:24] [main/DEBUG]: Injection complete
[16:15:24] [main/DEBUG]: Running coremod plugin for PhosphorFMLLoadingPlugin \{me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin\}
[16:15:24] [main/DEBUG]: Running coremod plugin PhosphorFMLLoadingPlugin
[16:15:24] [main/DEBUG]: Coremod plugin class PhosphorFMLLoadingPlugin run successfully
[16:15:24] [main/INFO]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[16:15:24] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:15:24] [main/DEBUG]: Validating minecraft
[16:15:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:15:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:15:26] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:15:28] [main/INFO]: [org.lwjgl.system.Library:printError:555]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[16:15:28] [main/INFO]: [org.lwjgl.system.Library:printError:557]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[16:15:28] [main/INFO]: [org.lwjgl.system.Library:printError:559]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[16:15:28] [main/INFO]: [org.lwjgl.opengl.GLContext:initCapabilities:13]: LWJGLX: GL caps init
[16:15:29] [main/INFO]: Patching net.minecraft.client.Minecraft... (bib)
[16:15:29] [main/INFO]: Entity Inject: net.minecraft.entity.Entity
[16:15:29] [main/INFO]: Patching net.minecraft.client.entity.EntityPlayerSP... (bud)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.ExceptionInInitializerError
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at $wrapper.com.therandomlabs.randompatches.core.RPTransformer.<init>(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.newInstance(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: net.minecraft.util.ReportedException: Failed to reload configuration category
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.TRLUtils.crashReport(TRLUtils.java:183)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.TRLCategory.onReload(TRLCategory.java:42)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.writeToDisk(ConfigManager.java:160)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.reloadFromConfig(ConfigManager.java:144)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.reloadFromDisk(ConfigManager.java:93)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.register(ConfigManager.java:86)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.therandomlabs.randompatches.core.RPTransformer.<clinit>(RPTransformer.java:18)
[16:15:31] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 16 more
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.reflect.InvocationTargetException
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.TRLCategory.onReload(TRLCategory.java:40)
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 21 more
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at com.therandomlabs.randompatches.client.WindowIconHandler.setWindowIcon(WindowIconHandler.java:41)
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at com.therandomlabs.randompatches.config.RPConfig$Window.onReloadClient(RPConfig.java:418)
[16:15:31] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 26 more

### Steps To Reproduce

```markdown
1. Starting pojavlauncher
2. Waiting a few seconds
3. Getting crash
```

### Expected Behavior

Launch without crashing

### Platform

```markdown
- Device model: Redmi note 9
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Mathias-Boulay** [comment]
discord rpc not supported
