### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Rahmanllu** [PojavLauncherTeam/PojavLauncher#4954]
### Describe the bug

Java hesabina girirken olusan hata ve benden minecraft profil fotosunu değistirmemi istiyor ama değiştiremiyorum

### The log file and images/videos

Böyle bi yazı yaziyor ve bunun çaresini bilmiyorum lütfen soyleyin

### Steps To Reproduce

```markdown
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Expected Behavior

Hesabimin acilmasi

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
not a pojav issue, it says you dont have minecraft
