### ISSUE TITLE
Application/game exited with code 1. 

### ISSUE THREAD

**Issue by Fuenzo4889** [PojavLauncherTeam/PojavLauncher#4992]
### Describe the bug

Whenever I try to play on forge 1.19 with jei & journeymap mods this error pops up when I launch the game

### The log file and images/videos

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/13789878/latestlog.txt)
### 

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Launch Forge 1.19 with JEI, Journeymap mods
3. Wait
```

### Expected Behavior

It was expected the game to open normaly as usually

### Platform

```markdown
- Device model: Tecno Pova 4
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
access denied, try using a different file manager, not much else you can do, some phones are just like this

**Comment by Bruno1234-lab** [comment]
Hello! This happened to me, but the version is forge 1.20.4
I found a text in a txt called `lastcrash.txt`
This is the text:
`PojavLauncher crash report
 Time: 31 de dez. de 2023 11:48:50
 Device: spes_global 2201117TL
 Android version: 13
 Crash stack trace:
 Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
java.lang.NullPointerException: Attempt to write to field 'java.lang.String net.kdt.pojavlaunch.value.launcherprofiles.MinecraftProfile.controlFile' on a null object reference in method 'android.view.View net.kdt.pojavlaunch.fragments.ProfileEditorFragment.onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle)'
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.onCreateView(ProfileEditorFragment.java:61)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2180)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:781)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:692)
	at net.kdt.pojavlaunch.Tools.removeCurrentFragment(Tools.java:921)
	at net.kdt.pojavlaunch.fragments.FileSelectorFragment.lambda$onViewCreated$3$net-kdt-pojavlaunch-fragments-FileSelectorFragment(FileSelectorFragment.java:80)
	at net.kdt.pojavlaunch.fragments.FileSelectorFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7569)
	at android.view.View.performClickInternal(View.java:7546)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29738)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)`

**Comment by Raldiminecraft** [comment]
I have this same exact thing
