### ISSUE TITLE
The custom keyboard menu is very unstable

### ISSUE THREAD

**Issue by matt995** [PojavLauncherTeam/PojavLauncher#501]
Will show me error on custom keyboard config area and then crash.

**To Reproduce**
1. Start PojavLauncher
2. Login with offline
3. Press setting for keyboard 
4. Press button 
5. Crash

**Expected behavior**
I expected for it to show the edit /delete menu

**Platform:**
 - Device Model huawei p30lite aka mar-lx3a
 - CPU architecture aarch64
 - Android Version 10 android Q

**Comment by khanhduytran0** [comment]
Please send the crash message!

**Comment by matt995** [comment]
It’s fixed in the beta it only happens to 3.3 v3

**Comment by matt995** [comment]
I just got it again here's error
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@d4b3c58 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1000)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1595)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1353)
	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1319)
	at net.kdt.pojavlaunch.customcontrols.handleview.PinnedPopupWindow.updatePosition(PinnedPopupWindow.java:117)
	at net.kdt.pojavlaunch.customcontrols.handleview.PinnedPopupWindow.show(PinnedPopupWindow.java:64)
	at net.kdt.pojavlaunch.customcontrols.handleview.ActionPopupWindow.show(ActionPopupWindow.java:75)
	at net.kdt.pojavlaunch.customcontrols.handleview.HandleView$1.run(HandleView.java:199)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
