### ISSUE TITLE
[BUG] Edit/Create Profile Crash

### ISSUE THREAD

**Issue by lost72738** [PojavLauncherTeam/PojavLauncher#5043]
### Describe the bug

When i press save it crash then i restart and it remove my profile but the installed versions are still but i can't press save that causes crashes

### The log file and images/videos

java.lang.RuntimeException: java.io.IOException: write failed: ENOSPC (No space left on device)
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.write(LauncherProfiles.java:51)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.save(ProfileEditorFragment.java:208)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.lambda$onViewCreated$0$net-kdt-pojavlaunch-fragments-ProfileEditorFragment(ProfileEditorFragment.java:80)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7585)
	at android.view.View.performClickInternal(View.java:7541)
	at android.view.View.access$3900(View.java:842)
	at android.view.View$PerformClick.run(View.java:28877)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.io.IOException: write failed: ENOSPC (No space left on device)
	at libcore.io.IoBridge.write(IoBridge.java:540)
	at java.io.FileOutputStream.write(FileOutputStream.java:398)
	at java.io.FileOutputStream.write(FileOutputStream.java:376)
	at org.apache.commons.io.IOUtils.write(Unknown Source:10)
	at org.apache.commons.io.IOUtils.write(Unknown Source:4)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:833)
	at net.kdt.pojavlaunch.value.launcherprofiles.LauncherProfiles.write(LauncherProfiles.java:48)
	... 14 more
Caused by: android.system.ErrnoException: write failed: ENOSPC (No space left on device)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:293)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:418)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:240)
	at libcore.io.IoBridge.write(IoBridge.java:535)
	... 20 more

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Create or edit an profile
3. Press save
4. Crashes
```

### Expected Behavior

Idk

### Platform

```markdown
- Device model: realme RMX2189
- CPU architecture: arm64
- Android version: 11
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

Pls fix this crash it remove my profile

**Comment by artdeell** [comment]
Your phone ran out of storage space

**Comment by lost72738** [comment]
Oh ok

**Comment by lost72738** [comment]
when i press edit i crashed

**Comment by lost72738** [comment]
I getting mid storage but it doesn't work

**Comment by lost72738** [comment]
> Your phone ran out of storage space

When I Edit/pencil button it crashed pls fix it

**Comment by lost72738** [comment]
Im lied
