### ISSUE TITLE
embeddium mod doesn't work in PojavLauncher 

### ISSUE THREAD

**Issue by agent1243** [PojavLauncherTeam/PojavLauncher#5058]
### Describe the bug

When I use the exoddium mod in version 1.20.1 Forge, and open the minecraft home menu , and I enter a world, us logs says that the world is saving and the game crashes, I know there is a patch for rubidium, but is there a patch for the embeddium? 

### The log file and images/videos

---- Minecraft Crash Report ----
// Oops.

Time: 2024-01-14 09:40:07
Description: Unexpected error

java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:57) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:36) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:80) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.DefaultChunkRenderer.render(DefaultChunkRenderer.java:55) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:272) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:231) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:3688) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1166) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.19.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Embeddium (embeddium), Version: 0.2.16+mc1.20.1
		at TRANSFORMER/embeddium@0.2.16+mc1.20.1/me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:57) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:36) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:80) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.DefaultChunkRenderer.render(DefaultChunkRenderer.java:55) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:272) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:classloading}
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:231) ~[embeddium-0.2.16+mc1.20.1.jar%23121!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.m_172993_(LevelRenderer.java:3688) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1166) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.render.world.clouds.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:core.render.world.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.options.weather.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.gui.outlines.WorldRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['agente123'/261, l='ClientLevel', x=-97.05, y=64.00, z=210.34]]
	Chunk stats: 256, 45
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,66,0), Section: (at 0,2,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 14793 game time, 14793 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:455) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:embeddium.mixins.json:core.world.biome.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:core.world.map.ClientWorldMixin,pl:mixin:APP:embeddium.mixins.json:features.render.world.sky.ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2319) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.2.19.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.19.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 376856808 bytes (359 MiB) / 1310720000 bytes (1250 MiB) up to 1310720000 bytes (1250 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd0a Stepping r1p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5953.26
	Virtual memory used (MB): 5786.30
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 2261.91
	JVM Flags: 4 total; -Xmn100m -Xms1250M -Xmx1250M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Mali-G52 MC2 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
	Window size: 1600x720
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: pt_br
	CPU: 8x 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['agente123'/261, l='ServerLevel[Meu Querido Mundo]', x=-97.05, y=64.00, z=210.34]]
	Data Packs: vanilla, mod:forge, mod:embeddium
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.2.19-universal.jar                |Forge                         |forge                         |47.2.19             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		embeddium-0.2.16+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.2.16+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 90570950-ec9b-4735-9248-ae9241519673
	FML: 47.2
	Forge: net.minecraftforge:47.2.19 

### Steps To Reproduce

```markdown
1. start PojavLauncher
2. open the minecraft home menu
3. I enter my world
4. begins to carry the world
5. the game crashes
```

### Expected Behavior

I expected the embeddium mod to work normally in pojavlauncher 

### Platform

```markdown
- Device model: Galaxy M22 4GB ram
- CPU architecture: arm64
- Android version:13
- PojavLauncher version: latest version (which is in the play store)
```

### Anything else?

I used version 1.20.1 Forge 47.2.19, and I used the embeddium version 0.2.16

**Comment by GaucovyAero** [comment]
no

**Comment by agent1243** [comment]
why not

**Comment by agent1243** [comment]
Why did you close it?

**Comment by agent1243** [comment]
you didn't tell me there will or won't be a patch for embeddium

**Comment by GaucovyAero** [comment]
> you didn't tell me there will or won't be a patch for embeddium

if it is using an older version of sodium as the core and doesnt change much stuff that cant be turned off you might aswell try adapting the sodium patch file to embeddium
otherwise there wont be any patch

**Comment by agent1243** [comment]
I don't know much about programming, I think I'll use rubidium instead of embeddium, thank you very much for answering me
