### ISSUE TITLE
Yu BenZer 

### ISSUE THREAD

**Issue by YuBenZer** [PojavLauncherTeam/PojavLauncher#5085]
Is this request related to a bug?

_No response_

**Comment by YuBenZer** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by YuBenZer** [comment]
Hi Guys
