### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by tvt282930tp** [PojavLauncherTeam/PojavLauncher#5097]
### Is this request related to a bug?

I want to create my minecraft id but can't. Please help me.

### Describe the request.

I want to create my minecraft id but can't. Please help me.

### Anything else?

I want to create my minecraft id but can't. Please help me.

**Comment by tvt282930tp** [comment]
I want to create my minecraft id but can't. Please help me.

**Comment by tvt282930tp** [comment]
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:222)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:80)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by tvt282930tp** [comment]
tvtyz

**Comment by GaucovyAero** [comment]
log into minecraft.net and buy java edition first, then set up your minecraft nickname and skin and then try again
