### ISSUE TITLE
java.lang.RuntimeException: Not Found 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 	at java.lang.Thread.run(Thread.java:1012)[BUG] <Short description>

### ISSUE THREAD

**Issue by mynameisorion** [PojavLauncherTeam/PojavLauncher#5115]
### Describe the bug

I cant log into my Microsoft acount

### The log file and images/videos

Nothing

### Steps To Reproduce

```markdown
Idk
```

### Expected Behavior

When i log in my acount this message apears

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

And that it

**Comment by mynameisorion** [comment]
Someone help :(
