### ISSUE TITLE
[BUG] I can't sign in in Microsoft account 

### ISSUE THREAD

**Issue by shreygamer12073** [PojavLauncherTeam/PojavLauncher#5124]
### Describe the bug

When i sign so my account don't sign in

### The log file and images/videos

No things 

### Steps To Reproduce

```markdown
1:i add account and open Microsoft
2: then I sign in
3:I just sign but after a Java runtime show and also when I play servers so this also so and server crash and ban
```

### Expected Behavior

No things 

### Platform

```markdown
- Device model:realmec25y 
- CPU architecture: RMX3265
- Android version: 11
- PojavLauncher version: latest
```

### Anything else?

No things

**Comment by shreygamer12073** [comment]
Pls help

**Comment by shreygamer12073** [comment]
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by GaucovyAero** [comment]
buy minecraft, if you already have it then try logging into minecraft.net, set up your username, skin, etc. and then try again
