### ISSUE TITLE
[BUG] optifabric crashing on 1.20.1

### ISSUE THREAD

**Issue by TotallyNotSaeed** [PojavLauncherTeam/PojavLauncher#5129]
### Describe the bug

It keeps crashing after waiting a bit with exit code 1

### The log file and images/videos

[15:59:42] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.6
[15:59:43] [main/INFO]: Loading 6 mods:
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- minecraft 1.20.1
	- optifabric 1.13.25
	   \-- mm 2.3
[15:59:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[15:59:47] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[15:59:48] [main/WARN]: File not found or not readable: /proc/stat
[16:00:02] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 948 milliseconds
[16:00:11] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[16:00:11] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[16:00:11] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[16:00:12] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:00:17] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:733) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.15.6-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
	... 8 more
[16:00:17] [Render thread/INFO]: Setting user: TotallyNotSaeed
[16:00:17] [Render thread/INFO]: Definitely not up to no good
[16:00:18] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[16:00:18] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[16:00:22] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
	at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:640) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.15.6-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'flite':
dlopen failed: library "libflite.so" not found
dlopen failed: library "libflite.so" not found
Native library (linux-aarch64/libflite.so) not found in resource path (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-glfw-classes.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/fabric-loader/0.15.6/fabric-loader-0.15.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/github/oshi/oshi-core/6.3.0/oshi-core-6.3.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/fabric-loader-0.15.6-1.20.1/fabric-loader-0.15.6-1.20.1.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:323) ~[jna-5.13.0.jar:?]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
	... 8 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflite.so" not found
		at com.sun.jna.Native.open(Native Method) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:211) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
		at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
		at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.<init>(class_310.java:640) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.15.6-1.20.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflite.so" not found
		at com.sun.jna.Native.open(Native Method) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:224) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
		at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
		at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.<init>(class_310.java:640) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.15.6-1.20.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	Suppressed: java.io.IOException: Native library (linux-aarch64/libflite.so) not found in resource path (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-glfw-classes.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/fabric-loader/0.15.6/fabric-loader-0.15.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/intermediary/1.20.1/intermediary-1.20.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/github/oshi/oshi-core/6.3.0/oshi-core-6.3.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/fabric-loader-0.15.6-1.20.1/fabric-loader-0.15.6-1.20.1.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1145) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:295) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:483) ~[jna-5.13.0.jar:?]
		at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:425) ~[jna-5.13.0.jar:?]
		at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
		at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar:?]
		at net.minecraft.class_333.<init>(class_333.java:19) ~[client-intermediary.jar:?]
		at net.minecraft.class_310.<init>(class_310.java:640) ~[client-intermediary.jar:?]
		at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.15.6-1.20.1.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
[16:00:22] [Render thread/INFO]: Reloading ResourceManager: vanilla
[16:00:22] [Worker-Main-1/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading

### Steps To Reproduce

```markdown
1. Launch pojavlauncher
2. Crash
```

### Expected Behavior

Not to crash

### Platform

```markdown
- Device model: Galaxy A31
- CPU architecture: MediaTek Helio P65
- Android version: 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
try loader 0.14.x
