### ISSUE TITLE
[BUG] <labymod4 cannot start>

### ISSUE THREAD

**Issue by villager1314** [PojavLauncherTeam/PojavLauncher#5145]
### Describe the bug

[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14238757/latestlog.txt)

### The log file and images/videos

The application crashes at startup

### Steps To Reproduce

```markdown
--------- beginning with launcher debug
Info: Launcher version: edelweiss-20240208-b9b2dae-
Info: Architecture: arm64
Info: Device model: HONOR ANY-AN00
Info: API version: 33
Info: Selected Minecraft version: LabyMod-4-1.20.4-48ca5e2b
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2328
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_BIG_CORE_AFFINITY=1
Added custom env: POJAV_NATIVEDIR=/data/app/~~vPdwrYpzMotfX5GcqFLZrA==/net.kdt.pojavlaunch.debug-qvd2QDcMQ2kBk_CqS9e1IA==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20240117-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LIBGL_VGPU_DUMP=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20240117-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20240117-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~vPdwrYpzMotfX5GcqFLZrA==/net.kdt.pojavlaunch.debug-qvd2QDcMQ2kBk_CqS9e1IA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre17-arm64-20240117-release.tar.xz
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
2024-02-12 20:39:48,610 main ERROR appender Console has no parameter that matches element Policies
[20:39:49] [main/INFO]: Loading tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
[20:39:49] [main/INFO]: Using primary tweak class name net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
[20:39:49] [main/INFO]: Calling tweak class net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker
2024-02-12 20:39:49,899 main ERROR appender Console has no parameter that matches element Policies
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-linux-arm64.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-linux-arm64.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-linux-arm64.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-linux-arm64.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-linux-arm64.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-linux-arm64.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-linux-arm64.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
[20:39:50] [main/INFO]: Library /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/labymod-neo/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
[20:39:50] [main/INFO]: Preloaded org.lwjgl.opengl.GL
[20:39:50] [main/INFO]: Preloaded org.lwjgl.system.MemoryStack
[20:39:50] [main/INFO]: Preloaded org.lwjgl.system.macosx.MacOSXLibraryBundle
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCursorPosCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWKeyCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCharModsCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeNSGL
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWMouseButtonCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWGL
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWMonitorCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWErrorCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCursorEnterCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.package-info
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWin32
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowRefreshCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFW
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowContentScaleCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWVulkan
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeGLX
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWGammaRamp
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowIconifyCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWScrollCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeEGL
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.EventLoop
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeCocoa
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowSizeCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowPosCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowMaximizeCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWFramebufferSizeCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWImage
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWJoystickCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowCloseCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWDropCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWWindowFocusCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWVidMode
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.Callbacks
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWCharCallback
[20:39:50] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeWayland
[20:39:51] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWNativeX11
[20:39:51] [main/INFO]: Preloaded org.lwjgl.glfw.GLFWGamepadState
[20:39:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/labymod/sponge-mixin/0.3.5.0.12.5.mixin.0.8.5/sponge-mixin-0.3.5.0.12.5.mixin.0.8.5.jar Service=LabyMod Env=UNKNOWN
[20:39:51] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[20:39:51] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[20:39:53] [main/WARN]: The requested compatibility level JAVA_17 is higher than the level supported by the active subsystem 'LabyMod' which supports JAVA_8. This is not a supported configuration and instability may occur.
[20:39:53] [main/INFO]: Compatibility level set to JAVA_17
[20:39:58] [main/INFO]: Checking for addon updates...
[20:39:59] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:39:59] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[20:40:01] [main/WARN]: Error loading class: net/optifine/render/VertexBuilderDummy (java.lang.ClassNotFoundException: The specified class 'net.optifine.render.VertexBuilderDummy' was not found)
[20:40:01] [main/WARN]: Error loading class: net/optifine/gui/TooltipManager (java.lang.ClassNotFoundException: The specified class 'net.optifine.gui.TooltipManager' was not found)
[20:40:01] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[20:40:03] [main/INFO]: Completely ignored arguments: [--dummyMinecraftClass, net.minecraft.client.main.Main]
[20:40:04] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[20:40:04] [main/WARN]: File not found or not readable: /proc/stat
[20:40:04] [main/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.a(SourceFile:66) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:128) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.c(SourceFile:75) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:82) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:75) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.c(SourceFile:52) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:82) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.<init>(SourceFile:52) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at o.<init>(SourceFile:36) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at o.h(SourceFile:277) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:167) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:217) ~[launchwrapper-3.1.5.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70) ~[launchwrapper-3.1.5.jar:?]
[20:40:22] [Render thread/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:6.4.5]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:6.4.5]
	at ab.a(SourceFile:66) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:128) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.c(SourceFile:75) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:82) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:75) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.c(SourceFile:52) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.a(SourceFile:82) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at ab.<init>(SourceFile:52) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at o.<init>(SourceFile:36) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at o.a(SourceFile:269) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:230) ~[LabyMod-4-1.20.4-48ca5e2b.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:217) ~[launchwrapper-3.1.5.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70) ~[launchwrapper-3.1.5.jar:?]
[20:40:23] [Render thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:217) ~[launchwrapper-3.1.5.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70) ~[launchwrapper-3.1.5.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ab.a(SourceFile:66) ~[ab.class:?]
	at evi.a(SourceFile:2605) ~[evi.class:?]
	at evi.a(SourceFile:2580) ~[evi.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:233) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch.debug/cache/lwjglu0_a242/3.3.1-SNAPSHOT/liblwjgl.so: dlopen failed: library "libpthread.so.0" not found: needed by /data/data/net.kdt.pojavlaunch.debug/cache/lwjglu0_a242/3.3.1-SNAPSHOT/liblwjgl.so in namespace classloader-namespace [in thread "Render thread"]
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:?]
	at java.lang.Runtime.load0(Unknown Source) ~[?:?]
	at java.lang.System.load(Unknown Source) ~[?:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:182) ~[Library.class:?]
	at org.lwjgl.system.Library.loadSystemFromLibraryPath(Library.java:172) ~[Library.class:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:127) ~[Library.class:?]
	at org.lwjgl.system.Library.loadSystem(Library.java:66) ~[Library.class:?]
	at org.lwjgl.system.Library.<clinit>(Library.java:54) ~[Library.class:?]
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100) ~[MemoryUtil.class:?]
	at eoz.<clinit>(SourceFile:8) ~[eoz.class:?]
	at epw.<init>(SourceFile:49) ~[epw.class:?]
	at eqd.<init>(SourceFile:33) ~[eqd.class:?]
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:51) ~[RenderSystem.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:220) ~[Main.class:?]
	... 6 more
```

### Expected Behavior

I hope to add back the previous renderer virgl
zink crash

### Platform

```markdown
Device model:Huawei
Android version:13
PojavLauncher version:edelweiss-20240208
```

### Anything else?

The previous version fixed the laby, but it has now expired and cannot be downloaded. After downloading the file through other means, I found that it still cannot work

**Comment by GaucovyAero** [comment]
this is normal, you cant load custom lwjgl on pojav because the lwjgl that is in pojav is very customized and specifically made to work with android/ios, therefore loading a different one is blocked because it wouldnt work anyway
