### ISSUE TITLE
Launcher crashes when entering

### ISSUE THREAD

**Issue by KazzyUwU** [PojavLauncherTeam/PojavLauncher#5167]
### Describe the bug

When i enter the app it just crashes instantly after a few seconds
![Screenshot_PojavLauncher (Minecraft_ Java Edition para Android)_2024-02-20-20-28-45-436](https://github.com/PojavLauncherTeam/PojavLauncher/assets/160556807/678ee86f-e835-4a4a-b250-07c990b8822c)

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:559)
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:551)
	at com.kdt.mcgui.mcAccountSpinner.lambda$new$2$com-kdt-mcgui-mcAccountSpinner(mcAccountSpinner.java:104)
	at com.kdt.mcgui.mcAccountSpinner$$ExternalSyntheticLambda2.onLoginError(Unknown Source:2)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$1(MicrosoftBackgroundLogin.java:109)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:374)
	at android.app.ActivityThread.main(ActivityThread.java:8911)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:671)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:951)

### Steps To Reproduce

```markdown
just start the game and it crashes
```

### Expected Behavior

i just expected to play 💀

### Platform

```markdown
- Device model: Redmagic 8 Pro
- CPU architecture: x64
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

no

**Comment by GaucovyAero** [comment]
latest isnt a version lol, please declare

**Comment by KazzyUwU** [comment]
alr alr
Version: edelweiss-20230928-9484d0c-v3_openjdk

**Comment by KazzyUwU** [comment]
i fixed it myself
