### ISSUE TITLE
[BUG] <The default download source and mirror. The download source is sometimes good and sometimes bad in China>

### ISSUE THREAD

**Issue by bsjssjjs** [PojavLauncherTeam/PojavLauncher#5190]
### Describe the bug

In many cases, the official default source can be downloaded very quickly in China.It's the same in the other starters.It can be downloaded normally.But in pojavlauncher,Sometimes it works, but sometimes it just doesn't,Since the failure of mcbbs,In China, it is very difficult to download the version, which is very troublesome

### The log file and images/videos

https://github.com/PojavLauncherTeam/PojavLauncher/assets/136832400/6846c9f9-c5f0-418e-9fbc-0bfc016a2eed

### Steps To Reproduce

```markdown
1.Start pojav
2.Download a version that has not been downloaded and use the official default
3.Unable to download properly
```

### Expected Behavior

Like other launchers, it can use the mirror edge and the official download cloud normally

### Platform

```markdown
- Device model: 64
- CPU architecture: 
- Android version: 8.1.0
- PojavLauncher version: edelweiss-20240219-195568c-v3_openjdk
```

**Comment by zkitefly** [comment]
![image](https://github.com/PojavLauncherTeam/PojavLauncher/assets/64117916/a11a1d47-77e9-4cc7-89b4-1fa378b6692b)

将“显示细节”的内容发上来？

**Comment by zkitefly** [comment]
关于 MCBBS 下载源：https://github.com/PojavLauncherTeam/PojavLauncher/issues/5174

**Comment by bsjssjjs** [comment]
java.io.IOException: Unable to download from https://piston-meta.mojang.com/v1/packages/e0e7ab5ed6f55bbd874ef95be3c9356d67e64b57/1.17.1.json
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:39)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:20)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:61)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:66)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$downloadGameJson$1(MinecraftDownloader.java:157)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda1.call(Unknown Source:4)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:125)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:147)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGameJson(MinecraftDownloader.java:154)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:198)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7d121b8280: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:301)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:239)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:31)
	... 15 more
显示细节的内容

**Comment by bsjssjjs** [comment]
java.io.IOException: Unable to download from https://piston-meta.mojang.com/v1/packages/e0e7ab5ed6f55bbd874ef95be3c9356d67e64b57/1.17.1.json
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:39)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:20)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:61)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:66)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$downloadGameJson$1(MinecraftDownloader.java:157)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda1.call(Unknown Source:4)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:125)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:147)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGameJson(MinecraftDownloader.java:154)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:198)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7d121b8280: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:301)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:239)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:31)
	... 15 more
显示细节的内容

**Comment by zkitefly** [comment]
你可以打开这个链接吗?

https://piston-meta.mojang.com/v1/packages/e0e7ab5ed6f55bbd874ef95be3c9356d67e64b57/1.17.1.json

**Comment by victorYghor** [comment]
this error only happen in when the app is in the chinese language?

**Comment by victorYghor** [comment]
Is not clear to me how replicate the error @zkitefly

**Comment by SHENGRUI11** [comment]
me too

**Comment by ghost** [comment]
Pojav launcher deleted msbbs downloader so don't use it
