### ISSUE TITLE
How to login pojav with microsoft

### ISSUE THREAD

**Issue by Frj99825** [PojavLauncherTeam/PojavLauncher#5191]
### Describe the bug

I want to play minecraft java with my friends but need to login microsoft to play when I login it tell me there are no java profile with my account 
Error code 

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at _java.lang.Thread.run(Thread.java:764)

but I already buy minecraft 
help me plz ☹️

### The log file and images/videos

No

### Steps To Reproduce

```markdown
1 start pojavlauncher 
2 login my microsoft account 
3 bug 😥
```

### Expected Behavior

I want to play minecraft with my friends!!!
😢

### Platform

```markdown
- Device model: asus zo1kda
- CPU architecture: arm64
- Android version: 8
- PojavLauncher version: the new
```

### Anything else?

No

**Comment by GaucovyAero** [comment]
buy minecraft: java edition

if you have bought it and it still doesnt work, log into minecraft.net and set up your username and skin
