### ISSUE TITLE
[BUG] Login issue

### ISSUE THREAD

**Issue by MalikAliShair** [PojavLauncherTeam/PojavLauncher#5232]
### Describe the bug

I have A premium Minecraft Account that i bought a few months ago it logins and works on PC just fine but it recently stopped working on pojav launcher and I'm getting error everything I login 

### The log file and images/videos

java.io.IOException: unexpected end of stream on com.android.okhttp.Address@20f2a50e
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireMinecraftToken(MicrosoftBackgroundLogin.java:245)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:82)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	... 14 more

### Steps To Reproduce

```markdown
1.start pojav launcher 
2.login
3.the login process shows error after 
 finishing
```

### Expected Behavior

The login should have gone smoothly

### Platform

```markdown
- Device model: Samsung A52s
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: latest
```

### Anything else?

It's been happening for quite a while first I thought it was just a server error but it wasnt

**Comment by sa1672ndo** [comment]
log onto minecraft.net and try again
