### ISSUE TITLE
Can't start any version on Pojav Launcher 

### ISSUE THREAD

**Issue by conttdj** [PojavLauncherTeam/PojavLauncher#5249]
### Describe the bug

Unable to install versions, or do anything at all

### The log file and images/videos

`java.io.IOException: Unable to download from https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.15.7/profile/json
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:37)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:18)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadString(DownloadUtils.java:51)
	at net.kdt.pojavlaunch.modloaders.FabriclikeDownloadTask.runCatching(FabriclikeDownloadTask.java:45)
	at net.kdt.pojavlaunch.modloaders.FabriclikeDownloadTask.run(FabriclikeDownloadTask.java:36)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackApi$-CC.$private$lambda$handleInstallation$0(ModpackApi.java:58)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackApi$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:29)
	... 9 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:656)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:260)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:569)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 29 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	... 42 more
`

### Steps To Reproduce

```markdown
1. Start Pojav Launcher
2. Attempt to install literally any version or modpack
```

### Expected Behavior

Should install the requested version

### Platform

```markdown
- Device model: Samsung S23 Ultra
- CPU architecture: 3x ARM Cortex-A510 @ 2016 MHz
2x ARM Cortex-A715 @ 2803 MHz
2x ARM Cortex-A710 @ 2803 MHz
ARM Cortex-X3 @ 3360 MHz
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by GaucovyAero** [comment]
have you tried reinstalling or changing out your internet connection (wifi and mobile data)? i mean it seems like you are the only person having this issue

**Comment by GaucovyAero** [comment]
stale

**Comment by dimkinkot** [comment]
I have the same problem, the infinix 40 device, and on xiaomi mi8 everything is fine with the same version.
