### ISSUE TITLE
[BUG] <ошибка с номером 1>

### ISSUE THREAD

**Issue by RaZrad** [PojavLauncherTeam/PojavLauncher#5252]
### Describe the bug

Никакие гайди с ютюба не помогают, в latestlog.txt  написано это:

Exception in thread "main" java.lang.NoClassDefFoundError: misc/tweaker/Tweaker
	at misc.tweaker.StubMain.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: misc.tweaker.Tweaker
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
Java Exit code: 1
I/jrelog  (23431): Going to free args
I/jrelog  (23431): Free done

(Остальное succes) 

Умоляю вас помогите решить

### The log file and images/videos

![Screenshot_2024-03-24-11-55-29-426_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/164731463/809e2ef1-1737-4f04-90e7-cdc63231f9a6)

### Steps To Reproduce

```markdown
1. Установить моды на fabric 1.20.1
2. Играть с ними
3. Установить новый мод
4. При заходе с родом выдает ошибку 1
5. Удалить мод
6. Ошибка осталась даже после удаления мода
```

### Expected Behavior

Я ожидаю, что pojavlauncher запустится без ошибок и с модами и я смогу играть 

### Platform

```markdown
- Device model: Xiaomi 13T (Model: 2306EPN60G) 
- CPU architecture: Dimensity 8200-Ultra
Восемь ядер, макс. 3,1ГГц
- Android version: 14 UP1A.230905.011 | обновление безопасности Android: 2024-01-01
- PojavLauncher version: edelweiss-20230928-9484d
0c-v3_openjdk
```

**Comment by RaZrad** [comment]
Я просто тупой, извиняюсь за ложное обвинение я просто установил ещё одну версию фабрика и все заработало даже с тем модом)))
