### ISSUE TITLE
[BUG] Latest build will download broken files

### ISSUE THREAD

**Issue by xszqxszq** [PojavLauncherTeam/PojavLauncher#527]
**Describe the bug**
1.16.4 with fabric will crash after launched

**To Reproduce**
1. Start PojavLauncher
2. Install 1.16.4
3. Use Mod Installer in menu to install fabric 0.6.1.51
4. Launch the game

**Expected behavior**
I expected 1.16.4 works fine with fabric

**latestlog.txt**
```
--------- beggining with launcher debug
Info: LWJGL3 directory: [ClassWrapper.jar, jsr305.jar, lwjgl-glfw-classes.jar, lwjgl-jemalloc.jar, lwjgl-openal.jar, lwjgl-opengl.jar, lwjgl-stb.jar, lwjgl-tinyfd.jar, lwjgl.jar, version]
Architecture: arm64/aarch64
Info: Custom Java arguments: "-Xms768m -Xmx800m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
--------- beginning of system
--------- beginning of main
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x361
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/jli/libjli.so success
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/server/libjvm.so success
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x450
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libverify.so success
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x33c0
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libjava.so success
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x13b8
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "/data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so" has unsupported flags DT_FLAGS_1=0x81 (ignoring unsupported flags)
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnet.so success
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x2196
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libnio.so success
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x6a46
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt.so success
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x4d9
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libawt_headless.so success
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfreetype.so success
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0xda0
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/LaunchJVM(20819): dlopen /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so success
S/LaunchJVM(20819): dlopen /data/app/net.kdt.pojavlaunch-yLm0adxqZD6FNS-tq9KQNg==/lib/arm64/libopenal.so success
S/LaunchJVM(20819): dlopen /data/app/net.kdt.pojavlaunch-yLm0adxqZD6FNS-tq9KQNg==/lib/arm64/libgl04es.so success
S/LaunchJVM(20819): Done processing args
S/LaunchJVM(20819): Found JLI lib
S/LaunchJVM(20819): Calling JLI_Launch
S/jrelog  (20819): OpenJDK 64-Bit Server VM warning: 
S/jrelog  (20819): No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (20819): " unused DT entry: 
S/jrelog  (20819): DT_RPATH
S/jrelog  (20819):  (type 
S/jrelog  (20819): 0xf
S/jrelog  (20819):  arg 
S/jrelog  (20819): 0x8ff
S/jrelog  (20819): ) (ignoring)
S/jrelog  (20819): 
S/jrelog  (20819): WARNING: linker: 
S/jrelog  (20819): Warning: "
S/jrelog  (20819): /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libzip.so
S/jrelog  (20819): " has unsupported flags DT_FLAGS_1=
S/jrelog  (20819): 0x81
S/jrelog  (20819):  (ignoring unsupported flags)
S/jrelog  (20819): 
S/jrelog  (20819): Error: Could not find or load main class net.fabricmc.loader.launch.knot.KnotClient
S/jrelog  (20819): 
S/jrelog  (20819): [ERROR:mailbox_manager_sync.cc(57)] eglCreateSyncKHR failed
```

**Platform:**
 - Device Model: Huawei Mate30
 - CPU architecture: aarch64
 - Android Version: 10
 - Pojav Version: latest build in "Actions"

**Comment by xszqxszq** [comment]
Found the reason: Latest build cannot download ANY FILE CORRECT, and the libraries automatically downloaded are broken. Old builds  do not seem to have this problem

**Comment by WesleyVanNeck** [comment]
Works fine fabric is broken rn

**Comment by WesleyVanNeck** [comment]
Some run time flags arnt supported

**Comment by WesleyVanNeck** [comment]
Also give the full latest log file

**Comment by WesleyVanNeck** [comment]
> Found the reason: Latest build cannot download ANY FILE CORRECT, and the libraries automatically downloaded are broken. Old builds do not seem to have this problem

Welk yes but actuely no it could not get a depencie

**Comment by khanhduytran0** [comment]
So what it does when **cannot download CORRECT**?

**Comment by WesleyVanNeck** [comment]
> So what it does when **cannot download CORRECT**?

The knot client

**Comment by xszqxszq** [comment]
> So what it does when **cannot download CORRECT**?

Basically all libraries and minecraft game assets files downloaded in this build are broken. For example, when I tried to download 1.16 version in the latest build, one 8.0KB json is downloaded and I found the file obviously not complete. As for libraries downloaded in this build, they are all just 7.55 KB big and smaller than they should be.
One error raised during the download:
```
java.util.IllegalFormatConversionException: d != java.lang.Double
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2885)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2839)
	at java.util.Formatter.format(Formatter.java:2524)
	at java.util.Formatter.format(Formatter.java:2459)
	at java.lang.String.format(String.java:2911)
	at android.content.res.Resources.getString(Resources.java:534)
	at android.content.Context.getString(Context.java:655)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.publishDownloadProgress(MinecraftDownloaderTask.java:211)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.access$000(MinecraftDownloaderTask.java:17)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask$2.updateProgress(MinecraftDownloaderTask.java:103)
	at net.kdt.pojavlaunch.Tools.downloadFileMonitored(Tools.java:698)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:97)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloaderTask.doInBackground(MinecraftDownloaderTask.java:17)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Comment by xszqxszq** [comment]
> Also give the full latest log file

Above is really the full log file (in .minecraft folder), and I already found this is not related to fabric but download codes of pojav

**Comment by WesleyVanNeck** [comment]
> > Also give the full latest log file
> 
> Above is really the full log file (in .minecraft folder), and I already found this is not related to fabric but download codes of pojav

not really the file

**Comment by WesleyVanNeck** [comment]
its easyer to read

**Comment by khanhduytran0** [comment]
- Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/437819802
- Then delete folder `/storage/sdcard0/games/PojavLauncher/.minecraft/versions` and try again.

**Comment by xszqxszq** [comment]
>     * Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/437819802
> 
>     * Then delete folder `/storage/sdcard0/games/PojavLauncher/.minecraft/versions` and try again.

Works fine now, thank you
