### ISSUE TITLE
Español a inglés

### ISSUE THREAD

**Issue by pablo3240** [PojavLauncherTeam/PojavLauncher#53]
well, I spoke on YouTube and I report this error that the optifime does not run well in 1.7.10 I followed the steps indicated by YouTube and it marks this error java.lang.reflect.InvocationTargetException

**Comment by khanhduytran0** [comment]
Please copy full error, click Show more and copy all

**Comment by pablo3240** [comment]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(MainActivity.java)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	... 5 more
Caused by: java.lang.IncompatibleClassChangeError: Structural change of sw is hazardous (/data/user/0/net.kdt.pojavlaunch/app_dalvik-cache/1.7.10-OptiFine_HD_U_E3.dex at compile time, /data/user/0/net.kdt.pojavlaunch/app_dalvik-cache/OptiFine-1.7.10_HD_U_E3.dex at runtime): Static field count off: 0 vs 1
Lsw; (Compile time):
 Static fields:
 Instance fields:
  I a_
  I b
  Ltt; bm
  Ltr; bn
  Lvv; bo
  Lsv; bp
  Lvw; bq
  [Ladd; br
  Z bs
  Z bt
  Lsa; bu
  Z bv
  Lsa; bw
  Ldh; bx
  Luj; c
  Luj; d
  [F e
  F f
  I g
  Ltu; h
  Ltv; i
 Direct methods:
  <init>(Lahb;)V
  a(II)Ladb;
  b(FFF)F
  b(Ladd;)I
  bP()V
 Virtual methods:
  C()V
  a(Lsy;)Lsy;
  a(IF)V
  a(Ldh;)V
  a(Ljava/lang/String;)V
  a(Lsa;FF)V
  a(ZI)V
  a(ZZ)V
  a(Ljava/lang/Class;)Z
  a(Lyz;)Z
  aD()V
  ak()[Ladd;
  ax()I
  b(Ldh;)V
  b(Lsa;Z)V
  b(ZI)V
  bB()I
  bC()V
  bD()V
  bE()Z
  bF()V
  bG()Ljava/lang/String;
  bH()Z
  bI()Z
  bJ()Z
  bK()Z
  bL()V
  bM()Z
  bN()Z
  bO()Lsa;
  b_()Ljava/lang/String;
  be()Ladd;
  bi()Z
  bk()Z
  bn()V
  bq()V
  by()Z
  bz()F
  c()V
  c(ILadd;)V
  c(Lyz;)Z
  d(Lsv;)V
  e(Lyz;)I
  e()V
  f(FF)F
  g(Z)V
  h()V
  h(Z)V
  i(F)V
  j()Ltu;
  k()Ltv;
  l()Ltt;
  m()Lvv;
  n()Lvw;
  n(F)V
  o()Lsv;
  p()V
  q()I
  q(I)Ladd;
  r(I)Ladd;
  r()V
  s()V
  t()Ljava/lang/String;
  u()Ladb;
  v()Z
  w()V
  x()I
Lsw; (Runtime):
 Static fields:
  Ljava/lang/String; __OBFID
 Instance fields:
  I a_
  I b
  Ltt; bm
  Ltr; bn
  Lvv; bo
  Lsv; bp
  Lvw; bq
  [Ladd; br
  Z bs
  Z bt
  Lsa; bu
  Z bv
  Lsa; bw
  Ldh; bx
  Luj; c
  Luj; d
  [F e
  F f
  I g
  Ltu; h
  Ltv; i
  I randomMobsId
  Lahu; spawnBiome
  LBlockPos; spawnPosition
 Direct methods:
  <init>(Lahb;)V
  a(II)Ladb;
  b(FFF)F
  b(Ladd;)I
  bP()V
 Virtual methods:
  C()V
  a(Lsy;)Lsy;
  a(IF)V
  a(Ldh;)V
  a(Ljava/lang/String;)V
  a(Lsa;FF)V
  a(ZI)V
  a(ZZ)V
  a(Ljava/lang/Class;)Z
  a(Lyz;)Z
  aD()V
  ak()[Ladd;
  ax()I
  b(Ldh;)V
  b(Lsa;Z)V
  b(ZI)V
  bB()I
  bC()V
  bD()V
  bE()Z
  bF()V
  bG()Ljava/lang/String;
  bH()Z
  bI()Z
  bJ()Z
  bK()Z
  bL()V
  bM()Z
  bN()Z
  bO()Lsa;
  b_()Ljava/lang/String;
  be()Ladd;
  bi()Z
  bk()Z
  bn()V
  bq()V
  by()Z
  bz()F
  c()V
  c(ILadd;)V
  c(Lyz;)Z
  d(Lsv;)V
  e(Lyz;)I
  e()V
  f(FF)F
  g(Z)V
  h()V
  h(Z)V
  i(F)V
  j()Ltu;
  k()Ltv;
  l()Ltt;
  m()Lvv;
  n()Lvw;
  n(F)V
  o()Lsv;
  p()V
  q()I
  q(I)Ladd;
  r(I)Ladd;
  r()V
  s()V
  t()Ljava/lang/String;
  u()Ladb;
  v()Z
  w()V
  x()I
 (declaration of 'td' appears in /storage/emulated/0/games/minecraft/versions/1.7.10-OptiFine_HD_U_E3/1.7.10-OptiFine_HD_U_E3.jar:classes8.dex)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:299)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:292)
	at dalvik.system.DexPathList.findClass(DexPathList.java:418)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:299)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:292)
	at dalvik.system.DexPathList.findClass(DexPathList.java:418)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:299)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:292)
	at dalvik.system.DexPathList.findClass(DexPathList.java:418)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:299)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:292)
	at dalvik.system.DexPathList.findClass(DexPathList.java:418)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:151)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at adb.l(SourceFile:206)
	at kl.b(SourceFile:358)
	at bao.<init>(SourceFile:216)
	at net.minecraft.client.main.Main.main(SourceFile:129)
	... 7 more

**Comment by pablo3240** [comment]
> Copie el error completo, haga clic en Mostrar más y copie todo
Ready pass this error that is in the game

**Comment by khanhduytran0** [comment]
Uh, it's a weird error, delete folder `/storage/emulated/0/games/minecraft/libraries/optifine/OptiFine/1.7.10_HD_U_E3` then re-install OptiFine and try again.

**Comment by pablo3240** [comment]
> Es un error extraño, elimine la carpeta `/storage/emulated/0/games/minecraft/libraries/optifine/OptiFine/1.7.10_HD_U_E3`, vuelva a instalar OptiFine e intente nuevamente.

No, it does not work, I received the same error thanks anyway 1.7.10 works a little well for me on my device

**Comment by khanhduytran0** [comment]
Try v3
