### ISSUE TITLE
Error code 1

### ISSUE THREAD

**Issue by ZjaaranyWilk21** [PojavLauncherTeam/PojavLauncher#5301]
### Describe the bug

I start the game on mods and when I click the start button I get an error with code 1

### The log file and images/videos

	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-srg.jar, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-extra.jar, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/forge/1.18.2-40.2.17/forge-1.18.2-40.2.17-client.jar]
	... 25 more
Java Exit code: 1
I/jrelog  (10661): Going to free args
I/jrelog  (10661): Free done

### Steps To Reproduce

```markdown
I turn on the pojavlauncher application, then I select the Dawncraft 1.18.2 mod and click the start button and after some time I get an error code 1 message
```

### Expected Behavior

spodziewam się pomocy 

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
update pojav to the latest github actions build, guide is on the wiki
