### ISSUE TITLE
[BUG] pojavlauncher keeps getting blackscreen after installing fabric 1.18.2 with 43 TOTAL mod i have used to optimize my game

### ISSUE THREAD

**Issue by grosioso** [PojavLauncherTeam/PojavLauncher#5324]
### Describe the bug

when I installed 1.18.2 with fabric alongside with jre-17 runtime everything was about to work perfectly until this happened.

I did use 43 mods to optimize the game however that's before the blackscreen being occurred. The problem MIGHT be through the mods, but idk. none of the YouTube tutorials literally helped me. speaking of YouTube tutorials, all of the vids I watched to fix the problem are from indian people. i did try to fix it all by myself but that didn't work either. the only version it worked is vanilla.

anybody that has a fix, please let me know.

### The log file and images/videos
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/14892880/latestlog.txt)

![Screenshot_20240406-083557_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/166200108/39baf606-93b0-40e2-807c-8abe2f6e2f49)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Install 1.18.2 & Fabric
3. As I said, the mods might be the problem(?) so install these mods.
4. Start the game
```

### Expected Behavior

I expect my game being launched successfully just like vanilla, not a fully blackscreen from the game.

### Platform

```markdown
- Device model: Samsung Galaxy A12 (SM-A125F/DS)
- CPU architecture: MediaTek Helio P35 (MT6765V/CB)
- Android version: Android 12
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk (latest version in play store)
```

### Anything else?

this is seriously some sort of bug I have never encountered. Anyways, thank you.

**Comment by GaucovyAero** [comment]
anybody can have a blackscreen anytime, an image does not help lol
send log

**Comment by grosioso** [comment]
> anybody can have a blackscreen anytime, an image does not help lol
> send log

2024-04-06 10:51:25,874 main ERROR appender Console has no parameter that matches element Policies
[10:51:26] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.15.9
[10:51:28] [main/INFO]: Loading 131 mods:
	- accurateblockplacement 1.0.12
	- betterbiomeblend 1.18.2-1.3.5-fabric
	- betterdroppeditems 1.3.2-1.18.2
	- betterhurtcam 1.3.1+mc1.18.2
	   |-- fabric-key-binding-api-v1 1.0.12+54e5b2ec60
	   \-- ukulib 0.2.0+1.18.2
	        \-- com_moandjiezana_toml_toml4j 0.7.2
	- betterthirdperson 1.8.1
	- boostedbrightness 2.1.1
	- c2me 0.2.0+alpha.7.38
	   |-- c2me-base 0.2.0+alpha.7.38
	   |-- c2me-client-uncapvd 0.2.0+alpha.7.38
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.7.38
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.7.38
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.7.38
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.7.38
	   |-- c2me-notickvd 0.2.0+alpha.7.38
	   |-- c2me-opts-allocs 0.2.0+alpha.7.38
	   |-- c2me-opts-chunk-access 0.2.0+alpha.7.38
	   |-- c2me-opts-chunkio 0.2.0+alpha.7.38
	   |-- c2me-opts-math 0.2.0+alpha.7.38
	   |-- c2me-opts-scheduling 0.2.0+alpha.7.38
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.7.38
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.7.38
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.7.38
	   |-- c2me-server-utils 0.2.0+alpha.7.38
	   |-- c2me-threading-chunkio 0.2.0+alpha.7.38
	   |-- c2me-threading-lighting 0.2.0+alpha.7.38
	   |-- c2me-threading-scheduling 0.2.0+alpha.7.38
	   |-- c2me-threading-worldgen 0.2.0+alpha.7.38
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   \-- org_threadly_threadly 6.6
	- clumps 8.0.0+17
	- colormeoutlines 1.1.0
	- darkkore 0.1.1
	   |-- com_electronwill_night-config_json 3.6.5
	   |-- com_github_darkkronicle_konstruct_addons 2.0.3-build1
	   \-- com_github_darkkronicle_konstruct_core 2.0.3-build1
	- dynamic_fps 3.2.1
	- eatinganimationid 1.8
	- enhancedblockentities 0.7.1+1.18.2
	   |-- advanced_runtime_resource_pack 0.5.5
	   \-- spruceui 3.3.0+1.17
	        \-- org_aperlambda_lambdajcommon 1.8.1
	- entityculling 1.6.1-mc1.18.2
	- exordium 1.0.1-mc1.18.2
	- fabric-api 0.76.0+1
.18.2
	   |-- fabric-api-base 0.4.5+64b7c69360
	   |-- fabric-api-lookup-api-v1 1.6.3+2373a54560
	   |-- fabric-biome-api-v1 8.0.7+e83becad60
	   |-- fabric-block-api-v1 1.0.0+ee3621fc60
	   |-- fabric-blockrenderlayer-v1 1.1.13+3ac43d9560
	   |-- fabric-command-api-v1 1.1.10+d7c144a860
	   |-- fabric-commands-v0 0.2.9+b4f4f6cd60
	   |-- fabric-containers-v0 0.1.24+d7c144a860
	   |-- fabric-content-registries-v0 3.1.3+c85f2e3860
	   |-- fabric-convention-tags-v1 1.1.0+43ce63a460
	   |-- fabric-crash-report-info-v1 0.2.1+ee261a3e60
	   |-- fabric-data-generation-api-v1 3.1.0+6c70b68e60
	   |-- fabric-dimensions-v1 2.1.21+489d6f8260
	   |-- fabric-entity-events-v1 1.4.9+d7c144a860
	   |-- fabric-events-interaction-v0 0.4.20+d7c144a860
	   |-- fabric-events-lifecycle-v0 0.2.22+d7c144a860
	   |-- fabric-game-rule-api-v1 1.0.13+d7c144a860
	   |-- fabric-item-api-v1 1.6.2+8165403660
	   |-- fabric-item-groups-v0 0.3.16+91896a4960
	   |-- fabric-keybindings-v0 0.2.10+b4f4f6cd60
	   |-- fabric-lifecycle-events-v1 2.1.1+cc71601c60
	   |-- fabric-loot-api-v2 1.1.2+1997ad1260
	   |-- fabric-loot-tables-v1 1.1.4+e747827960
	   |-- fabric-mining-level-api-v1 2.1.6+cc71601c60
	   |-- fabric-models-v0 0.3.7+d7c144a860
	   |-- fabric-networking-api-v1 1.0.24+2d30af4b60
	   |-- fabric-networking-v0 0.3.11+b4f4f6cd60
	   |-- fabric-object-builder-api-v1 2.1.5+032c981d60
	   |-- fabric-particles-v1 0.2.13+526dc1ac60
	   |-- fabric-registry-sync-v0 0.9.12+bb2e047760
	   |-- fabric-renderer-api-v1 0.5.0+bf48649860
	   |-- fabric-renderer-indigo 0.6.1+03e2b68760
	   |-- fabric-renderer-registries-v1 3.2.12+b4f4f6cd60
	   |-- fabric-rendering-data-attachment-v1 0.3.9+ee3621fc60
	   |-- fabric-rendering-fluids-v1 2.0.3+54e5b2ec60
	   |-- fabric-rendering-v0 1.1.14+b4f4f6cd60
	   |-- fabric-rendering-v1 1.10.8+54e5b2ec60
	   |-- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660
	   |-- fabric-resource-loader-v0 0.5.3+047a5ecb60
	   |-- fabric-screen-api-v1 1.0.11+d882b91560
	   |-- fabric-screen-handler-api-v1 1.2.3+1f6558e860
	   |-- fa
bric-textures-v0 1.0.13+3ac43d9560
	   |-- fabric-transfer-api-v1 1.6.4+f4563ac860
	   \-- fabric-transitive-access-wideners-v1 1.1.0+e747827960
	- fabricloader 0.15.9
	   \-- mixinextras 0.3.5
	- fastload 1.5.10
	- ferritecore 4.2.1
	- immediatelyfast 1.1.9
	- indium 1.0.7+mc1.18.2
	- inventoryhud 3.4.18
	- java 17
	- kronhud 2.0.4
	- krypton 0.1.9
	   \-- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
	- lazydfu 0.1.2
	- lithium 0.10.3
	- malilib 0.12.1
	- marlows-crystal-optimizer 1.0.0
	- memoryleakfix 1.0.0
	- minecraft 1.18.2
	- modmenu 3.2.5
	- morecosmetics 1.2
	- moreculling 1.18.2-0.8.2
	   |-- cloth-config 6.2.62
	   |    \-- cloth-basic-math 0.6.1
	   \-- conditional-mixin 0.3.0
	- no_fog 1.3.1+1.16.5-1.19.2
	- offlineskins 1.18.2-v2-fabric
	- reeses-sodium-options 1.5.0+mc1.18.2-build.70
	- replaymod 1.18.2-2.6.13
	- skinlayers 1.4.6-mc1.18.2
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	   \-- org_joml_joml 1.10.2
	- sodium-extra 0.4.18+mc1.18.2-build.98
	   |-- caffeineconfig 1.1.0+1.17
	   \-- crowdin-translate 1.4+1.18.2
	- starlight 1.0.2+fabric.89b8d9f
	- vmp 0.2.0+beta.3.126
	- waveycapes 1.3.2
	- wi_zoom 1.3-MC1.18.2
[10:51:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:51:29] [main/INFO]: Compatibility level set to JAVA_17
[10:51:31] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.client.uncapvd.mixin
[10:51:32] [main/INFO]: Disabling com.ishland.c2me.client.uncapvd.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[10:51:32] [main/INFO]: Disabling com.ishland.c2me.notickvd.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[10:51:32] [main/INFO]: Disabling com.ishland.c2me.rewrites.chunkio.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.threading.scheduling.mixin
[10:51:32] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[10:51:33] [main/INFO]: Loaded configuration file for Lithium: 105 options available, 2 override(s) found
[10:51:34] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[10:51:34] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[10:51:34] [main/INFO]: Loaded configuration file for Sodium Extra: 30 options available, 4 override(s) found
[10:51:34] [main/INFO]: Successfully started async appender with [SysOut, File]
[10:51:37] [main/WARN]: Mixin malte0811.ferritecore.mixin.threaddetec.PalettedContainerMixin is disabled automatically as lithium is installed
[10:51:37] [main/WARN]: Error loading class: nukeduck/armorchroma/GuiArmor (java.lang.ClassNotFoundException: nukeduck/armorchroma/GuiArmor)
[10:51:37] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[10:51:38] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, krypton, vmp]) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinChunkBuilder' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinClientChunkMap' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinClientPlayNetworkHandler' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinClientWorld' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinPackedIntegerArray' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinPalettedContainer' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'features.chunk_rendering.MixinWorldRenderer' as rule 'mixin.features.chunk_rendering' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'adaptive_sync.MixinWindow' as option 'mixin.adaptive_sync' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'fog.DimensionOptionsAccessor' as option 'mixin.fog' (added by mods [no_fog]) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'fog.MixinBackgroundRenderer' as option 'mixin.fog' (added by mods [no_fog]) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'sodium.resolution.MixinSodiumGameOptionPages' as option 'mixin.sodium.resolution' (added by user configuration) disables it and children
[10:51:39] [main/WARN]: Force-disabling mixin 'sodium.vsync.MixinSodiumGameOptionsPages' as option 'mixin.sodium.vsync' (added by user configuration) disables it and children
[10:51:39] [main/INFO]: [MemoryLeakFix] Will be applying 5 memory leak fixes!
[10:51:39] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [tagKeyLeak, targetEntityLeak, entityMemoriesLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[10:51:41] [main/INFO]: I used the json to destroy the json
[10:51:41] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[10:51:41] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[10:51:41] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[10:51:41] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[10:51:41] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[10:51:42] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[10:51:42] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.9.jar:?]
	... 7 more
Caused by: java.lang.ClassCastException: class com.llamalad7.mixinextras.lib.apache.commons.tuple.ImmutablePair cannot be cast to class org.apache.commons.lang3.tuple.Pair (com.llamalad7.mixinextras.lib.
apache.commons.tuple.ImmutablePair and org.apache.commons.lang3.tuple.Pair are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a01e23)
	at ca.fxco.memoryleakfix.config.mixinExtension.UnMixinExtension.preApply(UnMixinExtension.java:23) ~[memoryleakfix-fabric-1.17+-1.0.0.jar:?]
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.preApply(Extensions.java:156) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.preApply(TargetClassContext.java:413) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:401) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.9.jar:?]
	... 7 more

**Comment by GaucovyAero** [comment]
wrong log, send latestlog.txt as said in the issue template

**Comment by GaucovyAero** [comment]
and be sure to send it as a file and not as output as that generates spam, also delete your previous spam message

**Comment by grosioso** [comment]
> and be sure to send it as a file and not as output as that generates spam, also delete your previous spam message

happy or something is also wrong?

**Comment by GaucovyAero** [comment]
good, remove memoryleakfix

**Comment by grosioso** [comment]
> good, remove memoryleakfix

How??

**Comment by GaucovyAero** [comment]
its a mod just delete it

**Comment by grosioso** [comment]
> its a mod just delete it

got it

**Comment by grosioso** [comment]
> > its a mod just delete it
> 
> got it

I have deleted the mod, now I am about to test it so I will give you an update if it works successfully

**Comment by grosioso** [comment]
> its a mod just delete it

it actually works now. tysm. little bit of the game taking a bit long to load compared to vanilla but that is seriously good! I will close it from now on.
