### ISSUE TITLE
[BUG] Unable to offline login when i compiled source at current date

### ISSUE THREAD

**Issue by noobimpostor** [PojavLauncherTeam/PojavLauncher#534]
**Describe the bug**
I compiled from source code , and i found this on offline login

**Screenshots**
![Screenshot_2020-12-23-18-28-23-214_net kdt pojavlaunch](https://user-images.githubusercontent.com/65805762/102998458-30e45200-454d-11eb-95e7-994bfaf4d520.jpg)

**File path**
app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/Tools.java

**Comment by noobimpostor** [comment]
@khanhduytran0

**Comment by khanhduytran0** [comment]
Why would you compile from source while we've using GitHub Actions for auto build?

**Comment by khanhduytran0** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/actions?query=branch%3Av3_openjdk
it is where to get GH actions auto build every commit.

Try latest build.

**Comment by noobimpostor** [comment]
> Why would you compile from source while we've using GitHub Actions for auto build?

How can i do this @khanhduytran0

**Comment by noobimpostor** [comment]
Ok i downloaded from GH auto build , but still same error. I tried to find in source code , but couldn't reach to it @khanhduytran0

**Comment by khanhduytran0** [comment]
Does the path to Json different or same?

**Comment by noobimpostor** [comment]
@khanhduytran0 i have noticed ".json" is extra in string , if it could reduced then access to file will get but I think error is in PojavProfile.getCurrentTempProfile() method

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/441931001
(It likely that you have java programming knowledge?)

**Comment by khanhduytran0** [comment]
`PojavProfile.getCurrentTempProfile()` is only used when user login without save account.

**Comment by noobimpostor** [comment]
I cant send u message on discord it says sending failed @khanhduytran0

**Comment by noobimpostor** [comment]
> `PojavProfile.getCurrentTempProfile()` is only used when user login without save account.

This method for offline account , and issue is in offline account

**Comment by khanhduytran0** [comment]
You need to be on Discord server to able to talk with me.

**Comment by noobimpostor** [comment]
> Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/441931001
> (It likely that you have java programming knowledge?)

I tried but launching failed with same error , but when u select account it continued. and when launching downloaded game , again crashes with same error

![IMG_20201224_150312](https://user-images.githubusercontent.com/65805762/103079076-34351780-45f9-11eb-9f49-3a0211b87ede.jpg)

**Comment by noobimpostor** [comment]
Again .json is repeated

**Comment by khanhduytran0** [comment]
Maybe clear data?

**Comment by khanhduytran0** [comment]
Also it's on different screen so stack trace would be different. Could you please send it.

**Comment by noobimpostor** [comment]
> Also it's on different screen so stack trace would be different. Could you please send it.

java.io.FileNotFoundException: /data/user/0/net.kdt.pojavlaunch/accounts/data/user/0/net.kdt.pojavlaunch/accounts/noibs.json.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:231)
	at java.io.FileInputStream.<init>(FileInputStream.java:165)
	at java.io.FileInputStream.<init>(FileInputStream.java:112)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:645)
	at net.kdt.pojavlaunch.value.MinecraftAccount.load(MinecraftAccount.java:30)
	at net.kdt.pojavlaunch.PojavProfile.getCurrentProfileContent(PojavProfile.java:18)
	at net.kdt.pojavlaunch.BaseMainActivity.initLayout(BaseMainActivity.java:125)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:22)
	at android.app.Activity.performCreate(Activity.java:7232)
	at android.app.Activity.performCreate(Activity.java:7221)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2964)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3119)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by noobimpostor** [comment]
When minecraft game is launched , this error is shown @khanhduytran0 , btw i haven't knowledge of java and android studio😅i am marketing and finance student

**Comment by noobimpostor** [comment]
Profile requested when launched minecraft 1.16.4, returned filenpath with .json.json but only 1 .json is path

**Comment by khanhduytran0** [comment]
Try https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/442130912

**Comment by khanhduytran0** [comment]
Bug fixed
