### ISSUE TITLE
[BUG]Faild to download Minecraft!

### ISSUE THREAD

**Issue by moserkoter** [PojavLauncherTeam/PojavLauncher#5393]
### Describe the bug

The version is not displayed, and Minecraft cannot be downloaded when you click PLAY, the download source is the default

### The log file and images/videos

jjava.io.IOException: Unable to read Version JSON for version latest-release
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:203)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1015)

### Steps To Reproduce

```markdown
1.I don't have a version shown in the original
2.When I click PLAY, it prompts me with a bad network connection and the wrong file location
3.I tried rebooting the network and restarting pojav, but the problem persists
```

### Expected Behavior

Ability to display the version and launch the game successfully

### Platform

```markdown
- Device model: IQOO9/256G
- CPU architecture: Snapdragon 8 Gen1
- Android version: 13
- PojavLauncher version: edelweiss-20240418-7d674f2-v3_openjdk
```

### Anything else?

No anything

**Comment by GaucovyAero** [comment]
select a version lol

**Comment by moserkoter** [comment]
> select a version 
It isn't show

**Comment by moserkoter** [comment]
> select a version lol

It isn't show

**Comment by moserkoter** [comment]
> select a version lol

It isn't show in release

**Comment by dimkinkot** [comment]
I have the same problem, the infinix 40 device, and on xiaomi mi8 everything is fine with the same version.

**Comment by rikiipufy** [comment]
java.lang.RuntimeException: Download failed. Please make sure you are logged in with a Microsoft Account.
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.downloadFile(MinecraftDownloader.java:520)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.verifyFileSha1(MinecraftDownloader.java:514)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.runCatching(MinecraftDownloader.java:499)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.run(MinecraftDownloader.java:487)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
any help?

**Comment by jhonnysamuel** [comment]
Quando eu coloco um cliente do manicraft pojaval não consigo entrar

**Comment by ninja20414** [comment]
Deu problema quando fui usar o cm client

**Comment by ninja20414** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5393

**Comment by BigodeXScar** [comment]
Bug de n querer baixar o Minecraft
