### ISSUE TITLE
[BUG] <Forge Crash>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5396]
### Describe the bug

I run just forge 1.16.5 and he crash

### The log file and images/videos

PojavLauncher crash report
 - Time: 25 Р°РїСЂ. 2024 Рі. 15:14:13
 - Device: T40Pro_2022_EEA T40 Pro_EEA
 - Android version: 12
 - Crash stack trace:
 - Launcher version: edelweiss-20240411-4caa308-v3_openjdk
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.setWebViewClient(android.webkit.WebViewClient)' on a null object reference
	at net.kdt.pojavlaunch.fragments.MicrosoftLoginFragment.onSaveInstanceState(MicrosoftLoginFragment.java:76)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3151)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:683)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:649)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:177)
	at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2655)
	at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
	at androidx.fragment.app.FragmentActivity$1.saveState(FragmentActivity.java:133)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:338)
	at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:544)
	at android.app.Activity.performSaveInstanceState(Activity.java:2201)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1508)
	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5842)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5235)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5197)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5266)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

### Steps To Reproduce

```markdown
Just start forge and he crashing
```

### Expected Behavior

Forge dont crash

### Platform

```markdown
- Time: 25 Р°РїСЂ. 2024 Рі. 15:14:13
 - Device: T40Pro_2022_EEA T40 Pro_EEA
 - Android version: 12
 - Crash stack trace:
 - Launcher version: edelweiss-20240411-4caa308-v3_openjdk
```

**Comment by savvacorgi** [comment]
im run dont with mods

**Comment by GaucovyAero** [comment]
looks like you have an issue with your system

**Comment by savvacorgi** [comment]
> looks like you have an issue with your system
idk Im launch everyday 1.16.5 forge but today he crashing

**Comment by GaucovyAero** [comment]
try rebooting

**Comment by Uiop98** [comment]
Hi

**Comment by Uiop98** [comment]
Can someone tell me how to fix code minus one error in the release version

**Comment by Uiop98** [comment]
Can someone write this report on this issue and send to them I cannot send to them because I not know how to report

**Comment by GaucovyAero** [comment]
> Can someone write this report on this issue and send to them I cannot send to them because I not know how to report

ask somebody to help you report it

**Comment by savvacorgi** [comment]
> попробуй перезагрузиться

I tried 7 times...

**Comment by GaucovyAero** [comment]
make sure you have android system webview installed and up to date, maybe try seeing if the via browser works just for testing

**Comment by GaucovyAero** [comment]
stale issue, cannot reproduce, closing
