### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by zcxllt** [PojavLauncherTeam/PojavLauncher#5427]
### Describe the bug

There is no item list when using Holy GL4es

### The log file and images/videos

[17:03:59] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.10
[17:04:01] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.5.5+mc1.20.6-build.118 recommends version 1.4.2 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.4.2 or later of reeses-sodium-options for the optimal experience.
[17:04:01] [main/INFO]: Loading 56 mods:
	- fabric-api 0.97.8+1.20.6
	   |-- fabric-api-base 0.4.40+80f8cf51ff
	   |-- fabric-api-lookup-api-v1 1.6.59+e9d2a72bff
	   |-- fabric-biome-api-v1 13.0.25+be5d88beff
	   |-- fabric-block-api-v1 1.0.20+6dfe4c9bff
	   |-- fabric-block-view-api-v2 1.0.8+80f8cf51ff
	   |-- fabric-blockrenderlayer-v1 1.1.50+80f8cf51ff
	   |-- fabric-client-tags-api-v1 1.1.12+7f945d5bff
	   |-- fabric-command-api-v1 1.2.45+f71b366fff
	   |-- fabric-command-api-v2 2.2.24+80f8cf51ff
	   |-- fabric-commands-v0 0.2.62+df3654b3ff
	   |-- fabric-content-registries-v0 8.0.4+b82b2392ff
	   |-- fabric-convention-tags-v1 2.0.3+7f945d5bff
	   |-- fabric-convention-tags-v2 2.0.0+2b43c5c8ff
	   |-- fabric-crash-report-info-v1 0.2.27+80f8cf51ff
	   |-- fabric-data-attachment-api-v1 1.1.15+2a2c66b6ff
	   |-- fabric-data-generation-api-v1 19.0.6+7f945d5bff
	   |-- fabric-dimensions-v1 2.1.68+94793913ff
	   |-- fabric-entity-events-v1 1.6.8+e9d2a72bff
	   |-- fabric-events-interaction-v0 0.7.6+c5fc38b3ff
	   |-- fabric-game-rule-api-v1 1.0.50+80f8cf51ff
	   |-- fabric-item-api-v1 8.1.1+17e985d6ff
	   |-- fabric-item-group-api-v1 4.0.38+aae0949aff
	   |-- fabric-key-binding-api-v1 1.0.45+80f8cf51ff
	   |-- fabric-keybindings-v0 0.2.43+df3654b3ff
	   |-- fabric-lifecycle-events-v1 2.3.4+c5fc38b3ff
	   |-- fabric-loot-api-v2 3.0.4+97f703daff
	   |-- fabric-message-api-v1 6.0.10+109a837cff
	   |-- fabric-model-loading-api-v1 1.0.12+80f8cf51ff
	   |-- fabric-models-v0 0.4.11+9386d8a7ff
	   |-- fabric-networking-api-v1 4.0.8+0dca0349ff
	   |-- fabric-object-builder-api-v1 15.1.3+c5fc38b3ff
	   |-- fabric-particles-v1 4.0.0+c5fc38b3ff
	   |-- fabric-recipe-api-v1 5.0.3+c5fc38b3ff
	   |-- fabric-registry-sync-v0 5.0.15+f1240ba7ff
	   |-- fabric-renderer-api-v1 3.2.12+97f703daff
	   |-- fabric-renderer-indigo 1.5.12+80f8cf51ff
	   |-- fabric-renderer-registries-v1 3.2.61+df3654b3ff
	   |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eff
	   |-- fabric-rendering-fluids-v1 3.1.3+2c869dedff
	   |-- fabric-rendering-v0 1.1.64+df3654b3ff
	   |-- fabric-rendering-v1 4.2.4+b21c00cbff
	   |-- fabric-resource-conditions-api-v1 4.0.1+74e2f560ff
	   |-- fabric-resource-loader-v0 1.0.5+c5f2432cff
	   |-- fabric-screen-api-v1 2.0.21+7b70ea8aff
	   |-- fabric-screen-handler-api-v1 1.3.72+b21c00cbff
	   |-- fabric-sound-api-v1 1.0.21+c5fc38b3ff
	   |-- fabric-transfer-api-v1 5.1.6+c5fc38b3ff
	   \-- fabric-transitive-access-wideners-v1 6.0.10+74e2f560ff
	- fabricloader 0.15.10
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.20.6
	- sodium 0.5.8+mc1.20.6
	- sodium-extra 0.5.5+mc1.20.6-build.118
	   \-- caffeineconfig 1.3.0+1.17
[17:04:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/10/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:04:02] [main/INFO]: Compatibility level set to JAVA_17
[17:04:04] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[17:04:05] [main/INFO]: Loaded configuration file for Sodium Extra: 35 options available, 0 override(s) found
[17:04:10] [main/INFO]: Searching for graphics cards...
[17:04:10] [main/WARN]: No graphics cards were found. Either you have no hardware devices supporting 3D acceleration, or something has gone terribly wrong!
[17:04:10] [main/WARN]: Unable to determine desktop session type because the environment variable XDG_SESSION_TYPE is not set! Your user session may not be configured correctly.
[17:04:13] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[17:04:15] [main/WARN]: Failed retrieving info for group processor
java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch.debug-mlKKxsNRhVGB0fRdmfGZ6g==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:?]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:?]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) [client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) [client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) [client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:277) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.10.jar:?]
[17:04:15] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory

[17:06:03] [IO-Worker-1/INFO]: Could not authorize you against Realms server: Invalid session id
[17:06:03] [IO-Worker-1/ERROR]: Couldn't connect to realms
net.minecraft.class_4355: Realms authentication error with message 'Invalid session id'
	at net.minecraft.class_4341.method_20998(class_4341.java:447) ~[client-intermediary.jar:?]
	at net.minecraft.class_4341.method_21027(class_4341.java:232) ~[client-intermediary.jar:?]
	at net.minecraft.class_8647.method_52627(class_8647.java:51) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[17:06:23] [Render thread/INFO]: Loaded 1175 recipes
[17:06:26] [Render thread/INFO]: Loaded 1276 advancements
[17:06:30] [Sound engine/ERROR]: Stop: Invalid name parameter.
[17:06:30] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 10.55 ms
[17:06:31] [Server thread/INFO]: Starting integrated minecraft server version 1.20.6
[17:06:31] [Server thread/INFO]: Generating keypair
[17:06:47] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[17:07:03] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:04] [Render thread/INFO]: 准备生成区域中：0%
[17:07:05] [Render thread/INFO]: 准备生成区域中：0%
[17:07:05] [Render thread/INFO]: 准备生成区域中：0%
[17:07:06] [Render thread/INFO]: 准备生成区域中：18%
[17:07:06] [Render thread/INFO]: 准备生成区域中：55%
[17:07:07] [Render thread/INFO]: 准备生成区域中：81%
[17:07:07] [Render thread/INFO]: Time elapsed: 20333 ms
[17:07:08] [Server thread/INFO]: Changing view distance to 2, from 10
[17:07:08] [Server thread/INFO]: Changing simulation distance to 5, from 0
[17:07:09] [Render thread/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 51:f8:15:49:ff:b1:59:b3
[17:07:11] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2031ms or 40 ticks behind
[17:07:17] [Server thread/INFO]: jenene[local:E:c83631ad] logged in with entity id 104 at (4.074519589892628, 64.0, 37.15849757356335)
[17:07:18] [Server thread/INFO]: jenene加入了游戏
[17:07:20] [Render thread/INFO]: Loaded 58 advancements
[17:07:40] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 14796ms or 295 ticks behind

### Steps To Reproduce

```markdown
1.Start pojavlauncher
2.Entering the World
3.No item list
```

### Expected Behavior

Appear in the item list

### Platform

```markdown
- Device model: Lenovo TB-X606F
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: -
```

**Comment by GaucovyAero** [comment]
what does item list even mean, show a screenshot

**Comment by GaucovyAero** [comment]
stale
