### ISSUE TITLE
Error Comes up while trying to start the "liteloader with forge" profile.

### ISSUE THREAD

**Issue by GamingFruit** [PojavLauncherTeam/PojavLauncher#5438]
### Describe the bug

java.lang.NullPointerException: Attempt to read from field 'net.kdt.pojavlaunch.JMinecraftVersionList$FileProperties net.kdt.pojavlaunch.JMinecraftVersionList$LoggingConfig$LoggingClientConfig.file' on a null object reference in method 'void net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(android.app.Activity, net.kdt.pojavlaunch.JMinecraftVersionList$Version, java.lang.String)'
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.downloadGame(AsyncMinecraftDownloader.java:109)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader.lambda$new$0$net-kdt-pojavlaunch-tasks-AsyncMinecraftDownloader(AsyncMinecraftDownloader.java:54)
	at net.kdt.pojavlaunch.tasks.AsyncMinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

This is the error, please tell me how to fix it, I did everything to fix this error, removed all mods, please tell me a way to fix it. I am losing my mind right now.

### The log file and images/videos

![Screenshot_20240507_193231_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/96644588/b92e8e76-fcae-4f8f-b7db-6f0bda974e21)
![Screenshot_20240507_193219_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/96644588/e4cb6896-f6a9-4b6d-9665-fcba186d6f1b)

### Steps To Reproduce

```markdown
Start Pojav Launcher
Click Play on "liteloader with forge 1.12.2"
Error pops up.
```

### Expected Behavior

I expected that the profile will run without any problems.

### Platform

```markdown
- Device model: Samsung Galaxy Tab A8
- CPU architecture: idk
- Android version: 14
- PojavLauncher version: Latest
```

### Anything else?

I installed both forge and liteloader, liteloader has a profile to install on called "liteloader with forge" which is the one I installed for the version 1.12.2 to run both .jar and .litemod mods. Removed all the mods but still did not run and showed the error given below. Thanks.

**Comment by GaucovyAero** [comment]
latest is not a version

**Comment by SAFTDGG22** [comment]
It's the same.
![Screenshot_20240825_132715_net kdt pojavlaunch](https://github.com/user-attachments/assets/eee2b3a5-1b0b-49b2-a6a0-553de32c8341)
![Screenshot_20240825_132722_net kdt pojavlaunch](https://github.com/user-attachments/assets/fbff01b0-d27e-4abe-98cc-4839b9ac6968)
Platform
- Device model: Huawei P smart 2021
- Android version: 10



If the words seem a bit strange, I apologize, Thai person .
--> Google Translate

**Comment by GaucovyAero** [comment]
i got it to work, but it requires a pretty difficult json patch

![25727](https://github.com/user-attachments/assets/b354672e-3de9-4abe-b85b-73b59bf39a09)

**Comment by GaucovyAero** [comment]
ima try creating a guide for it

**Comment by GaucovyAero** [comment]
[LiteLoader-with-Forge-Guide-v1.0.txt](https://github.com/user-attachments/files/17046137/LiteLoader-with-Forge-Guide-v1.0.txt)

https://github.com/user-attachments/assets/55938471-219e-46f3-8ac9-b2a0da9319b7

**Comment by GaucovyAero** [comment]
help wanted: dunno if devs wanna fix the double inheritance thing or the weird thing where you have to remove the logging line
