### ISSUE TITLE
Can't log into Microsoft account, but I have bought minecraft.

### ISSUE THREAD

**Issue by Elka2233** [PojavLauncherTeam/PojavLauncher#5452]
### Describe the bug

 Can't log into Microsoft account, but I have bought minecraft long time ago.

### The log file and images/videos

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
1. Start Pojav launcher
2. Try to log into the Microsoft account
3. Error that says that I probably don't have license of Minecraft on this account.
```

### Expected Behavior

To log into the Microsoft account.

### Platform

```markdown
- Device model: Poco F5
- CPU architecture: Snapdragon® 7+ Gen 2 Mobile Platform.
- Android version: 14
- PojavLauncher version: latest
```

### Anything else?

I have bought official minecraft.

**Comment by artdeell** [comment]
Try this version of pojav: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9022894637

**Comment by GaucovyAero** [comment]
or log into minecraft.net and then into pojav
