### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by Malik8001** [PojavLauncherTeam/PojavLauncher#5471]
### Describe the bug

1 open pojavlauncher
2 press add account
3 login with microsoft account

### The log file and images/videos

1 open pojavlauncher
2 press add account
3 login with microsoft account

### Steps To Reproduce

```markdown
1 open pojavlauncher
2 press add account
3 login with microsoft account
```

### Expected Behavior

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

- Device model: Infinix ZERO ULTRA
- CPU architecture: Dimensity 920
- Android version: 12
- PojavLauncher version: latest release

**Comment by Malik8001** [comment]
1 open pojavlauncher
2 press add account
3 login with microsoft account

**Comment by Malik8001** [comment]
Hi this good

**Comment by Mathias-Boulay** [comment]
if you have a microsoft account with mc java on it, connect to minecraft.net before logging to pojav

**Comment by AndreCodin24** [comment]
I use Xbox Game Pass Ultimate. It works for me.
