### ISSUE TITLE
Create crash

### ISSUE THREAD

**Issue by IgnacRobotics** [PojavLauncherTeam/PojavLauncher#5478]
### Describe the bug

I launched the game with create mod and created a world. It went fine until I placed down the first item from create when the game crashed and showed the saving world screen

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 22101316G
Info: API version: 31
Info: Selected Minecraft version: 1.20.1-forge-47.1.44
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2344
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~J1PsD_p2VNsJggrjEAh9Sw==/net.kdt.pojavlaunch-_6VZvA8pGEWRk6MIAO-8-w==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~J1PsD_p2VNsJggrjEAh9Sw==/net.kdt.pojavlaunch-_6VZvA8pGEWRk6MIAO-8-w==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles3_desktopgl_angle_vulkan
Added custom env: LIBGL_ES=3
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: POJAVEXEC_EGL=libEGL_angle.so
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main

I/jrelog  ( 8069): dlopen libtinywrapper.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 8069): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.
pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 8069)
: dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_he
adless.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.
kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success
I/jrelog  ( 8069): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  ( 8069): dlopen /data/app/~~J1PsD_p2VNsJggrjEAh9Sw==/net.kdt.pojavlaunch-_6VZvA8pGEWRk6MIAO-8-w==/lib/arm64/libopenal.so success
I/jrelog  ( 8069): Done processing args
I/jrelog  ( 8069): Found JLI lib
I/jrelog  ( 8069): Calling JLI_Launch

2024-05-14 18:07:05,664 main ERROR appender Console has no parameter that matches element Policies
[18:07:05] [main/INFO]: ModLauncher running: args [--username, Ignac, --version, 1.20.1, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 5, --uuid, 00000000000000000000000000000000, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.1.44, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[18:07:05] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.9-internal by N/A; OS Linux arch aarch64 version Android-12
[18:07:06] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[18:07:06] [main/INFO]: Trying GL version 4.6
EGLBridge: Binding to desktop OpenGL
[18:07:06] [main/INFO]: Requested GL version 4.6 got version 0.0
I/NativeInput( 8069): Input ready: 1

[18:07:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2366!/ Service=ModLauncher Env=CLIENT
[18:07:06] [pool-2-thread-1/INFO]: GL info: ANGLE (ARM, Vulkan 1.1.177 (Mali-G68 MC4 (0x92041010)), Mali-G68 MC4-32.1.0) GL version 4.6.0 (ANGLE 2.1.1 git hash: b79b72b53460), Google Inc. (ARM)
[18:07:06] [main/INFO]: Found mod file create-1.20.1-0.5.1.f.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[18:07:07] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/fmlcore/1.20.1-47.1.44/fmlcore-1.20.1-47.1.44.jar is missing mods.toml file
[18:07:07] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.1.44/javafmllanguage-1.20.1-47.1.44.jar is missing mods.toml file
[18:07:07] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.1.44/lowcodelanguage-1.20.1-47.1.44.jar is missing mods.toml file
[18:07:07] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/mclanguage/1.20.1-47.1.44/mclanguage-1.20.1-47.1.44.jar is missing mods.toml file
[18:07:07] [main/INFO]: Found mod file fmlcore-1.20.1-47.1.44.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@64030b91
[18:07:07] [main/INFO]: Found mod file javafmllanguage-1.20.1-47.1.44.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@64030b91
[18:07:07] [main/INFO]: Found mod file lowcodelanguage-1.20.1-47.1.44.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@64030b91
[18:07:07] [main/INFO]: Found mod file mclanguage-1.20.1-47.1.44.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@64030b91
[18:07:07] [main/INFO]: Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@64030b91
[18:07:07] [main/INFO]: Found mod file forge-1.20.1-47.1.44-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@64030b91
[18:07:07] [main/INFO]: Found 2 dependencies adding them to mods collection
[18:07:07] [main/INFO]: Found mod file flywheel-forge-1.20.1-0.6.10-7.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@4a8df3e2
[18:07:07] [main/INFO]: Found mod file Registrate-MC1.20-1.3.3.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@4a8df3e2
[18:07:09] [main/INFO]: Compatibility level set to JAVA_17
[18:07:09] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --uuid, 00000000000000000000000000000000, --username, Ignac, --assetIndex, 5, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release]
[18:07:11] [main/WARN]: File not found or not readable: /proc/stat
[18:07:19] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 418 milliseconds
[18:07:23] [Render thread/WARN]: Assets URL 'union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23122!/assets/.mcassetsroot' uses unexpected schema
[18:07:23] [Render thread/WARN]: Assets URL 'union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-srg.jar%23122!/data/.mcassetsroot' uses unexpected schema
[18:07:23] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:07:23] [Render thread/INFO]: Setting user: Ignac
[18:07:23] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[18:07:23] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[18:07:24] [modloading-worker-0/INFO]: Forge mod loading, version 47.1.44, for MC 1.20.1 with MCP 20230612.114412
[18:07:24] [modloading-worker-0/INFO]: MinecraftForge v47.1.44 Initialized
[18:07:24] [modloading-worker-0/INFO]: No shaders mod detected.
[18:07:30] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[18:07:30] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[18:07:30] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[18:07:31] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar%2393!/:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar%2393!/:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) ~[text2speech-1.17.9.jar%2393!/:?]
	at net.minecraft.client.GameNarrator.<init>(GameNarrator.java:19) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:553) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?]
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.1.44.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.44.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.44.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.44.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'flite':
dlopen failed: library "libflite.so" not found
dlopen failed: library "libflite.so" not found
Native library (linux-aarch64/libflite.so) not found in resource path (/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/lwjgl3/lwjgl-glfw-classes.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/fmlearlydisplay/1.20.1-47.1.44/fmlearlydisplay-1.20.1-47.1.44.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/fmlloader/1.20.1-47.1.44/fmlloader-1.20.1-47.1.44.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.

### Steps To Reproduce

```markdown
1. Start pojavlauncher
2. Choose create: all in one modpack profile
3. Choose angle renderer
4. Launch the game
5. Create a world
6. Place down a mechanical arm
```

### Expected Behavior

Work without crashing 

### Platform

```markdown
- Device model: redmi note 12 pro
- CPU architecture: dimensity 1080 
octa score max 2,6 GHz 
- Android version: 12SP1A.210812.016
- PojavLauncher version: 2023. September 28 android
```

**Comment by Bel69420** [comment]
Disable the flywheel by doing /flywheel backend off before placing create stuff

**Comment by IgnacRobotics** [comment]
Thanks, it helped
