### ISSUE TITLE
Forge doesn't work

### ISSUE THREAD

**Issue by test-apk** [PojavLauncherTeam/PojavLauncher#5490]
### Describe the bug

When I try to use forge I get an error when starting it up (not the installation) I have no mods installed

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-G950U
Info: API version: 28
Info: Selected Minecraft version: 1.20.4-forge-49.0.50
Info: Custom Java arguments: ""
--------- beginning of main

--------- beginning of system

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2960
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/net.kdt.pojavlaunch-z31DnEkk8EbU4WBoadfEZQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/games/PojavLauncher
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/bin:/sbin:/system/sbin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/net.kdt.pojavlaunch-z31DnEkk8EbU4WBoadfEZQ==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1440
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
I/jrelog  ( 7153): dlopen libgl4es_114.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success

I/jrelog  ( 7153): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_agent.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libinstrument.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjdwp.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmlib_image.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjsig.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_ext.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/liblcms.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libdt_socket.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsyslookup.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libextnet.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libzip.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjavajpeg.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjimage.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libprefs.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjaas.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2pkcs11.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/librmi.so success
I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2gss.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success
I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt.so success
I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjawt.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsctp.so success

I/jrelog  ( 7153): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  ( 7153): dlopen /data/app/net.kdt.pojavlaunch-z31DnEkk8EbU4WBoadfEZQ==/lib/arm64/libopenal.so success

I/jrelog  ( 7153): Done processing args
I/jrelog  ( 7153): Found JLI lib
I/jrelog  ( 7153): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(Unknown Source)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(Unknown Source)
	at java.base/java.lang.System.initPhase3(Unknown Source)
2024-05-24 11:53:19,548 main ERROR appender Console has no parameter that matches element Policies
[11:53:20] [main/INFO]: ModLauncher running: args [--username, TestAPK, --version, 1.20.4, --gameDir, /storage/emulated/0/games/PojavLauncher/.minecraft, --assetsDir, /storage/emulated/0/games/PojavLauncher/.minecraft/assets, --assetIndex, 12, --uuid, 00000000000000000000000000000000, --accessToken, **********, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release, --launchTarget, forge_client]
[11:53:20] [main/INFO]: JVM identified as Oracle Corporation OpenJDK 64-Bit Server VM 21.0.1-internal-adhoc.runner.openjdk
[11:53:20] [main/INFO]: ModLauncher 10.1.2 starting: java version 21.0.1-internal by N/A; OS Linux arch aarch64 version Android-9
[11:53:20] [main/WARN]: Configuration file /storage/emulated/0/games/PojavLauncher/.minecraft/config/fml.toml is not correct. Correcting
[11:53:20] [main/INFO]: Incorrect key [earlyWindowSkipGLVersions] was corrected from null to []
[11:53:20] [main/INFO]: Incorrect key [earlyWindowLogHelpMessage] was corrected from null to true
[11:53:20] [main/INFO]: Incorrect key [earlyWindowSquir] was corrected from null to false
[11:53:20] [main/INFO]: Incorrect key [earlyWindowShowCPU] was corrected from null to false
[11:53:20] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[11:53:21] [main/INFO]: Trying GL version 4.6
[11:53:21] [main/INFO]: If this message is the only thing at the bottom of your log before a crash, you probably have a driver issue.

Possible solutions:
A) Make sure Minecraft is set to prefer high performance graphics in the OS and/or driver control panel
B) Check for driver updates on the graphics brand's website
C) Try reinstalling your graphics drivers
D) If still not working after trying all of the above, ask for further help on the Forge forums or Discord

You can safely ignore this message if the game starts up successfully.
EGLBridge: Binding to OpenGL ES
[11:53:21] [main/INFO]: Requested GL version 4.6 got version 0.0
I/NativeInput( 7153): Input ready: 1

Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/storage/emulated/0/games/PojavLauncher/.minecraft
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[11:53:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=jar:file:///storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar!/ Service=ModLauncher Env=CLIENT
[11:53:22] [EarlyDisplay/INFO]: GL info: Adreno (TM) 540 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
version string: 150 coreERROR: 0:10: 'in' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 1 compilation errors.  No code generated.

version string: 150 coreversion string: 150 coreERROR: 0:8: 'in' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 1 compilation errors.  No code generated.

[11:53:22] [main/INFO]: Found mod file forge-1.20.4-49.0.50-client.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@7f8633ae
[11:53:22] [main/INFO]: Found mod file javafmllanguage-1.20.4-49.0.50.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@499683c4
[11:53:22] [main/INFO]: Found mod file mclanguage-1.20.4-49.0.50.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@499683c4
[11:53:22] [main/INFO]: Found mod file fmlcore-1.20.4-49.0.50.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@499683c4
[11:53:22] [main/INFO]: Found mod file lowcodelanguage-1.20.4-49.0.50.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@499683c4
[11:53:22] [main/INFO]: No dependencies to load found. Skipping!
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133)
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53)
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19)
Caused by: java.lang.IllegalStateException: Failed to find system mod: forge
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.ModSorter.detectSystemMods(ModSorter.java:170)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.ModSorter.buildUniqueList(ModSorter.java:148)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.ModSorter.sort(ModSorter.java:54)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.moddiscovery.ModValidator.stage2Validation(ModValidator.java:127)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.FMLLoader.completeScan(FMLLoader.java:162)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.50/net.minecraftforge.fml.loading.FMLServiceProvider.completeScan(FMLServiceProvider.java:63)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServiceDecorator.onCompleteScan(TransformationServiceDecorator.java:104)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.lambda$triggerScanCompletion$11(TransformationServicesHandler.java:171)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at ja

### Steps To Reproduce

```markdown
1. Start PoJavLauncher
2. Install any forge version
3. error
```

### Expected Behavior

I expect it to start up normally

### Platform

```markdown
- Device model: Samsung Galaxy S8
- CPU architecture: arm64
- Android version: 9
- PojavLauncher version: latest
```

**Comment by GaucovyAero** [comment]
update pojav to the latest github actions build, guide is on the wiki
