### ISSUE TITLE
(DATA)My pojavlauncher data folder is not opening

### ISSUE THREAD

**Issue by Vamsi0012** [PojavLauncherTeam/PojavLauncher#5492]
### Describe the bug

I wanted to add a control map for my pojavlauncher and I tried to open pojavlauncher folder and it did not work,it says it needs a root or something.

### The log file and images/videos

java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/controlmap/ULTIMATE_CUSTOM_HUD.json: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:823)
	at net.kdt.pojavlaunch.customcontrols.LayoutConverter.loadAndConvertIfNecessary(LayoutConverter.java:19)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:73)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout$2.onFileSelected(ControlLayout.java:567)
	at com.kdt.pickafile.FileListView.listFileAt(FileListView.java:150)
	at com.kdt.pickafile.FileListView.lambda$init$0$com-kdt-pickafile-FileListView(FileListView.java:84)
	at com.kdt.pickafile.FileListView$$ExternalSyntheticLambda1.onItemClick(Unknown Source:6)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3304)
	at android.widget.AbsListView$3.run(AbsListView.java:4270)
	at android.os.Handler.handleCallback(Handler.java:1000)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:362)
	at android.app.ActivityThread.main(ActivityThread.java:8393)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8275)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 21 more

### Steps To Reproduce

```markdown
Open File Manager
Go to Android 
Data 
Pojavlauncher folder
But it doesn't open it says access denied.
```

### Expected Behavior

I think I need a special type of root to access the folder.Can anyone say how can I create a root to it.

### Platform

```markdown
- Device model: moto g54 5G
- CPU architecture:aarch64
- Android version:14
- PojavLauncher version:Latest playstore version
```

### Anything else?

Nothing but please help me.I can't even add any mods and resource packs if I can't access the folder

**Comment by GaucovyAero** [comment]
not a bug in pojav, try a different method to put the file in that directory (e. g. pojav's import controls option) or try moving the file manually with com.marc.files from play store by clicking the 3 lines button (its called hamburger menu) and then pojavlauncher - controlmap

**Comment by Vamsi0012** [comment]
How can I do this
