### ISSUE TITLE
[BUG] <Faild load modpack>

### ISSUE THREAD

**Issue by savvacorgi** [PojavLauncherTeam/PojavLauncher#5499]
### Describe the bug

PLz help i just download haste modpack bad error

### The log file and images/videos

net.kdt.pojavlaunch.utils.DownloadUtils$SHA1VerificationException: SHA1 verifcation failed after 5 download attempts
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:154)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackInstaller.installModpack(ModpackInstaller.java:33)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModrinthApi.installMod(ModrinthApi.java:116)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.CommonApi.installMod(CommonApi.java:112)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackApi$-CC.$private$lambda$handleInstallation$0(ModpackApi.java:56)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackApi$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
1. start pojav
2. install modpack
3. error
```

### Expected Behavior

install suficli

### Platform

```markdown
- Device model: Teclast t40 pro eea
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: last
```

**Comment by kiokori-git** [comment]
haste modpack is an unofficial modpack, we will not provide support for it.

**Comment by savvacorgi** [comment]
> haste modpack is an unofficial modpack, we will need not provide support for it.

why?

**Comment by kiokori-git** [comment]
> > haste modpack is an unofficial modpack, we will need not provide support for it.
> 
> why?

it uses modified builds, like i said, its unofficial and we will not provide support for it, thats all.
