### ISSUE TITLE
[BUG] Can't login into Microsoft account

### ISSUE THREAD

**Issue by Johny-adri2** [PojavLauncherTeam/PojavLauncher#5518]
### Describe the bug

I just bought a copy of Minecraft but Pojavlauncher thinks that I don't own it, but the desktop Minecraft Launcher says the opposite.

### The log file and images/videos

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
![Снимок экрана 2024-05-31 191941](https://github.com/PojavLauncherTeam/PojavLauncher/assets/136599603/3ccf4ba9-45a7-41d2-b3a6-21eaa8746c70)

### Steps To Reproduce

```markdown
1. Get a copy of Minecraft
2. Start Pojavlauncher
3. Try to login with that Microsoft account
```

### Expected Behavior

I expected that the Microsoft account would add without any problems.

### Platform

```markdown
- Device model: Tecno Lh7n
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Johny-adri2** [comment]
You just need to create a username in the launcher

**Comment by Johny-adri2** [comment]
LOL
