### ISSUE TITLE
java.lang.RuntimeException: Not Found 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 	at java.lang.Thread.run(Thread.java:1012)[BUG] <Short description>

### ISSUE THREAD

**Issue by Ahmdgaming815** [PojavLauncherTeam/PojavLauncher#5539]
### Describe the bug

java.lang.Thread.runjava.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### The log file and images/videos

`
![Screenshot_٢٠٢٤-٠٦-٠٦-٢٢-٣٧-٣٠-٩٦٣_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/171976341/7b2f841c-314f-4574-8804-46a68c1ea04b)
![Screenshot_٢٠٢٤-٠٦-٠٦-٢٢-٣٧-٣٠-٩٦٣_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/171976341/7b2f841c-314f-4574-8804-46a68c1ea04b)

### Steps To Reproduce

```markdown
1 open pojavlauncher
2 press add account
3 login with microsoft account
```

### Expected Behavior

لم أتوقع يحدث ذلك

### Platform

```markdown
- Device model: Redmi note 10S
- CPU architecture: Helio G95 
- Android version: 13
- PojavLauncher version: latest release
```

### Anything else?

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Ahmdgaming815** [comment]
ارجو مساعدتي ليس لدي كمبيوتر

**Comment by Ahmdgaming815** [comment]
هل misecroft سيقبل

**Comment by AndreCodin24** [comment]
You have to need an Xbox Game Pass in order to make PojavLauncher work. Just thank me later

**Comment by TarikBR** [comment]
https://bugs.mojang.com/browse/WEB-7179

**Comment by GaucovyAero** [comment]
buy minecraft java edition
if you already have it and it doesnt work, log into minecraft.net first, then log into pojav

**Comment by AndreCodin24** [comment]
Correct...

**Comment by Ahmdgaming815** [comment]
> يجب أن تحتاج إلى Xbox Game Pass لكي تعمل PojavLauncher. فقط أشكرني لاحقا

لدي لكنني لا اعلم ماذا افعل


> يجب أن تحتاج إلى Xbox Game Pass حتى تتمكن من استخدام PojavLauncher. ولم يخلفني
لدي لكن
