### ISSUE TITLE
Game exited with code -1

### ISSUE THREAD

**Issue by RonitNarkhede** [PojavLauncherTeam/PojavLauncher#5542]
### Describe the bug

I was playing a mod in version 1.7.10 and I got the error. I tried to figure it out but I can't so, please help me to solve it

### The log file and images/videos

---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/8/24 9:18 AM
Description: Registering texture

net.minecraft.client.renderer.StitcherException: Unable to fit: nhm:Tsuchigumo, size: 800x800, atlas: 3680x3680, atlasMax: 4096x4096 - Maybe try a lower resolution resourcepack?
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:76)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:357)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.Stitcher.func_94305_f(Stitcher.java:76)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:357)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:152)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/items.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:101)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:215)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (arm) version Android-13
	Java Version: 1.8.0_392-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 245266736 bytes (233 MB) / 892010496 bytes (850 MB) up to 892010496 bytes (850 MB)
	JVM Flags: 3 total; -Xms880M -Xmx880M -Xbootclasspath/p:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/ResConfHack.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJA	very_mod_samuracraftaddon2{0.5.3} [Very Mod samuracraftaddon] (NarutoMod2V.jar) 
	UCHIJA	ArmorObj{1.0.0} [ArmorObj] (NarutoMod2V.jar) 
	UCHIJA	AM{1.0.0} [Naruto Mod] (NarutoMod2V.jar) 
	UCHIJA	NMR{1.0} [NMR] (NarutoMod2V.jar) 
	UCHIJA	NBTEdit{1.7.10} [In-game NBTEdit] (NarutoMod2V.jar) 
	UCHIJA	narutopartymod{1.0} [RinKirin Naruto Party] (NarutoMod2V.jar) 
	Launched Version: 1.7.10
	LWJGL: 3.3.1 SNAPSHOT
	OpenGL: PowerVR Rogue GE8322 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is not supported.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.5
	OpenGlRenderer: PowerVR Rogue GE8322
	OpenGlVendor: PojavLauncherTeam & ptitSeb
	CpuCount: 8

### Steps To Reproduce

```markdown
I don't know
```

### Expected Behavior

I want mod should work properly 

### Platform

```markdown
- Device model: Samsung galaxy A03 core 
- CPU architecture: ARMV8I
- Android version: 13
- PojavLauncher version: latest
```

### Anything else?

I expect that mod should work properly in my device or atleast. I should know about the error which is caused

**Comment by GaucovyAero** [comment]
your naruto mod textures are too big for pojav to handle, that mod likely wont work, maybe try using a more higher-end device to see if it works?

**Comment by Oshnik5** [comment]
There are two or more mods not compatible with each other
