### ISSUE TITLE
forge 1.20.6 crashes

### ISSUE THREAD

**Issue by kaizer0920** [PojavLauncherTeam/PojavLauncher#5544]
### Describe the bug

here's the logfile

beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi M2102J20SG
Info: API version: 31
Info: Selected Minecraft version: 1.20.6-forge-50.1.3
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2328
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~QmyIr5Ry9zUJVDiMmJbzIA==/net.kdt.pojavlaunch-w4SmbIU5UrB5Y1jd7GLQ0g==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~QmyIr5Ry9zUJVDiMmJbzIA==/net.kdt.pojavlaunch-w4SmbIU5UrB5Y1jd7GLQ0g==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  ( 5443): dlopen libgl4es_114.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjli.so success
I/jrelog  ( 5443): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libverify.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjava.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libnet.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libnio.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-r
elease.tar.xz/lib/libawt.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjava.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libinstrument.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libj2pcsc.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/r
untimes/jdk21-arm64-20240309-release.tar.xz/lib/libattach.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjdwp.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libmlib_image.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjsig.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/server/libjsig.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/liblcms.so success
I/jrelog  ( 5443): dlopen /data/user/
0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libdt_socket.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libsyslookup.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libnio.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libextnet.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libzip.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjimage.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libprefs.so success
I/jrelog  ( 5443): dlopen /d
ata/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libmanagement.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjaas.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libfreetype.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libnet.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/librmi.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjli.so success
I/jrelog  ( 5443):
 dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libj2gss.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libverify.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libawt.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/lible.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libjawt.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libsctp.so success
I/jrelog  ( 5443): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jdk21-arm64-20240309-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  ( 54
43): dlopen /data/app/~~QmyIr5Ry9zUJVDiMmJbzIA==/net.kdt.pojavlaunch-w4SmbIU5UrB5Y1jd7GLQ0g==/lib/arm64/libopenal.so success
I/jrelog  ( 5443): Done processing args
I/jrelog  ( 5443): Found JLI lib
I/jrelog  ( 5443): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
ERROR StatusConsoleListener appender Console has no parameter that matches element Policies
[16:11:09] [main/INFO]: ModLauncher running: args [--username, Kaizer, --version, 1.20.6, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/./.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 16, --uuid, 00000000000000000000000000000000, --accessToken, **********, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release, --launchTarget, forge_client]
[16:11:09] [main/INFO]: JVM identified as Oracle Corporation OpenJDK 64-Bit Server VM 21.0.1-internal-adhoc.runner.openjdk
[16:11:09] [main/INFO]: ModLauncher 10.2.1 starting: java version 21.0.1-internal by N/A; OS Linux arch aarch64 version Android-12
[16:11:09] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
Registered forkAndExec
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[16:11:10] [main/INFO]: Trying GL version 4.6
EGLBridge: Binding to OpenGL ES
[16:11:10] [main/INFO]: Requested GL version 4.6 got version 0.0
I/NativeInput( 5443): Input ready: 1

[16:11:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=jar:file:///storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar!/ Service=ModLauncher Env=CLIENT
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[16:11:10] [main/INFO]: Found mod file forge-1.20.6-50.1.3-client.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@258ee7de
[16:11:10] [EarlyDisplay/INFO]: GL info: Adreno (TM) 640 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
[16:11:10] [main/INFO]: Found mod file lowcodelanguage-1.20.6-50.1.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@6df3e44c
[16:11:10] [main/INFO]: Found mod file javafmllanguage-1.20.6-50.1.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@6df3e44c
[16:11:10] [main/INFO]: Found mod file fmlcore-1.20.6-50.1.3.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@6df3e44c
[16:11:10] [main/INFO]: Found mod file mclanguage-1.20.6-50.1.3.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.ClasspathLocator@6df3e44c
version string: 150 coreERROR: 0:10: 'in' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 1 compilation errors.  No code generated.

version string: 150 coreversion string: 150 coreERROR: 0:8: 'in' : Syntax error:  syntax error
INTERNAL ERROR: no main() function!
ERROR: 1 compilation errors.  No code generated.

[16:11:10] [main/INFO]: No dependencies to load found. Skipping!
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133)
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53)
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19)
Caused by: java.lang.IllegalStateException: Failed to find system mod: forge
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.3/net.minecraftforge.fml.loading.ModSorter.detectSystemMods(ModSorter.java:170)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.3/net.minecraftforge.fml.loading.ModSorter.buildUniqueList(ModSorter.java:148)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.3/net.minecraftforge.fml.loading.ModSorter.sort(ModSorter.java:54)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.3/net.minecraftforge.fml.loading.moddiscovery.ModValidator.stage2Validation(ModValidator.java:127)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.3/net.minecraftforge.fml.loading.FMLLoader.completeScan(FMLLoader.java:162)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.6-50.1.3/net.minecraftforge.fml.loading.FMLServiceProvider.completeScan(FMLServiceProvider.java:63)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.TransformationServiceDecorator.onCompleteScan(TransformationServiceDecorator.java:104)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.TransformationServicesHandler.lambda$triggerScanCompletion$11(TransformationServicesHandler.java:171)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.TransformationServicesHandler.triggerScanCompletion(TransformationServicesHandler.java:173)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:97)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
	at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 4 more
Java Exit code: 1
I/jrelog  ( 5443): Going to free args
I/jrelog  ( 5443): Free done

### The log file and images/videos

![Screenshot_2024-06-08-16-03-32-909_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172106874/d0ea259e-f3b0-42d1-81af-b976a81ed502)

### Steps To Reproduce

```markdown
1. starts pojav
2. downloaded forge 1.20.6 thru pojav
3. downloaded and opened it 
4. crashes
```

### Expected Behavior

nothing

### Platform

```markdown
- Device model: Poco x3 pro
- CPU architecture: arm64
- Android version: 12
- PojavLauncher version: Latest
```

### Anything else?

none

**Comment by GaucovyAero** [comment]
this seems to happen on 1.20.6 on some devices, no idea why, please if anybody else has this issue write here, works for me just fine

taken from pojav discord, also crashes on a Realme Narzo 70 Pro 5G

**Comment by GaucovyAero** [comment]
try using jre and not jdk perhaps? i dont think its an issue with that tho

**Comment by GaucovyAero** [comment]
but the final issue you are dealing with is an actual forge crash and that issue is fixed in the latest github actions build, try that first

**Comment by GaucovyAero** [comment]
fixed in the latest github actions build

**Comment by User12349282** [comment]
Same crash 

Device : Redmi 9T
