### ISSUE TITLE
[BUG] Game crashes whenever I login with a microsoft account

### ISSUE THREAD

**Issue by shulkerpart** [PojavLauncherTeam/PojavLauncher#5552]
### Describe the bug

before this happened, Pojav would crash whenever it tried to automatically log in. I uninstalled Pojav and reinstalled it to see if it would work, and it just does the same thing whenever I try to log in with a Microsoft account

### The log file and images/videos

java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace()' on a null object reference
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:559)
	at net.kdt.pojavlaunch.Tools.showError(Tools.java:551)
	at com.kdt.mcgui.mcAccountSpinner.lambda$new$2$com-kdt-mcgui-mcAccountSpinner(mcAccountSpinner.java:104)
	at com.kdt.mcgui.mcAccountSpinner$$ExternalSyntheticLambda2.onLoginError(Unknown Source:2)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$1(MicrosoftBackgroundLogin.java:109)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. try to log in with a Microsoft account
3. wait a few seconds
4. pojav crashes
```

### Expected Behavior

for Pojav to log me in without crashing

### Platform

```markdown
- Device model: Galaxy A32 5G
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

this only happened after I haven't played Pojav in a while(around 2 weeks)

**Comment by GaucovyAero** [comment]
always read the previous issues man, microsoft is having server outages right now, try logging into minecraft.net first and then into pojav or try again later
