### ISSUE TITLE
When I open pojav launcher 1.21 with java21 installed it doesn't open instead it crashes

### ISSUE THREAD

**Issue by Adss953** [PojavLauncherTeam/PojavLauncher#5580]
### Describe the bug

When I open pojav launcher 1.21 version with installed Java 21 runtime it crashes 

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: vivo V2315
Info: API version: 34
Info: Selected Minecraft version: 1.21
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1176
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~NDFQ9O5w0SwWG92FHmPIcQ==/net.kdt.pojavlaunch-3KbcaFe7x1Hy4WQWf695Xg==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~NDFQ9O5w0SwWG92FHmPIcQ==/net.kdt.pojavlaunch-3KbcaFe7x1Hy4WQWf695Xg==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=540
Initialising gl4es
v1.1.5 built on Sep 27 2023 17:42:09
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(Unknown Source)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(Unknown Source)
	at java.base/java.lang.System.initPhase3(Unknown Source)
ERROR StatusConsoleListener appender Console has no parameter that matches element Policies
[13:24:52] [main/WARN]: Failed retrieving info for group processor
java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~NDFQ9O5w0SwWG92FHmPIcQ==/net.kdt.pojavlaunch-3KbcaFe7x1Hy4WQWf695Xg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.g(SourceFile:234) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.jar:?]
[13:24:53] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.g(SourceFile:234) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~NDFQ9O5w0SwWG92FHmPIcQ==/net.kdt.pojavlaunch-3KbcaFe7x1Hy4WQWf695Xg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	... 6 more
[13:24:53] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 1091 milliseconds
[13:25:04] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[13:25:04] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[13:25:04] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[13:25:05] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[13:25:05] [Render thread/INFO]: Setting user: Aryan_fuckall
Registered forkAndExec
[13:25:05] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[13:25:05] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
EGLBridge: Binding to OpenGL ES
[13:25:05] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[13:25:06] [Render thread/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.a(SourceFile:226) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:246) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~NDFQ9O5w0SwWG92FHmPIcQ==/net.kdt.pojavlaunch-3KbcaFe7x1Hy4WQWf695Xg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.<init>(SourceFile:56) ~[1.21.jar:?]
	at o.<init>(SourceFile:35) ~[1.21.jar:?]
	at o.g(SourceFile:234) ~[1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) ~[1.21.jar:?]
[13:25:06] [Render thread/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.linux.LinuxGlobalMemory
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.a(SourceFile:226) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:246) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem [in thread "main"]
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.<init>(SourceFile:56) ~[1.21.jar:?]
	at o.<init>(SourceFile:35) ~[1.21.jar:?]
	at o.g(SourceFile:234) ~[1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) ~[1.21.jar:?]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2024-06-14 13:25:06
Description: Initializing game

java.lang.NoSuchMethodError: 'void org.lwjgl.glfw.GLFW.glfwSetWindowSizeLimits(long, int, int, int, int)'
	at fam.<init>(SourceFile:117)
	at gfr.a(SourceFile:21)
	at fgo.<init>(SourceFile:505)
	at net.minecraft.client.main.Main.main(SourceFile:239)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fam.<init>(SourceFile:117)
	at gfr.a(SourceFile:21)
	at fgo.<init>(SourceFile:505)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:239)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (aarch64) version Android-14
	Java Version: 21.0.1-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1382680912 bytes (1318 MiB) / 1604321280 bytes (1530 MiB) up to 1604321280 bytes (1530 MiB)
	CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 74382.03, total: 111581.97
	Space in storage for workdir (MiB): available: 74382.03, total: 111581.97
	JVM Flags: 3 total; -Xms1530M -Xmx1530M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.21
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2024-06-14_13.25.06-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7156325178)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x71471fc038)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x713c6c6ed8)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x71471fc178)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x713c6c6ed8)

### Steps To Reproduce

```markdown
1. Install Java 21 runtime
2. Install 1.21 version 
3. Click on play and then it says
   Application exited with code - 1
```

### Expected Behavior

I expect it to be open I last time installed Java runtime 21 and opened 1.20.6 in an another device Realme C31 and it worked exactly as the same everything fine

### Platform

```markdown
- Device model: Vivo y28 5G
- CPU architecture: 64 
- Android version: 14
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

### Anything else?

![Screenshot_20240614_133418_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172757235/e30c2050-551b-41f6-a62e-70ce0641bee4)

**Comment by GaucovyAero** [comment]
update to the latest github actions build, guide is on the wiki

**Comment by Adss953** [comment]
> update to the latest github actions build, guide is on the wiki

What but my problem isn't solved why closed?
