### ISSUE TITLE
Error code -1 any time i launch 1.21 minecraft

### ISSUE THREAD

**Issue by gooigi74** [PojavLauncherTeam/PojavLauncher#5600]
### Describe the bug

Basicly when i launch the game its a black screen and then it turns gray then takes me back to the home screen on my phone then hands me the error message

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: edelweiss-20230928-9484d0c-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-S908U
Info: API version: 34
Info: Selected Minecraft version: 1.21
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2260
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~n4_dOGr7uKLR3PFqaxEoRw==/net.kdt.pojavlaunch-E7KjnVSosx-Tgofgue6TqQ==/lib/arm64
Added custom env: REGAL_GL_VERSION=4.5
Added custom env: REGAL_GL_VENDOR=Android
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~n4_dOGr7uKLR3PFqaxEoRw==/net.kdt.pojavlaunch-E7KjnVSosx-Tgofgue6TqQ==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: MESA_GLSL_VERSION_OVERRIDE=460
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz
Added custom env: MESA_GL_VERSION_OVERRIDE=4.6
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: REGAL_GL_RENDERER=Regal
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/jrelog  (14023): dlopen libOSMesa.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success
I/jrelog  (14023): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-rele
ase.tar.xz/lib/libawt.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjava.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libinstrument.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjdwp.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtim
es/jre21-arm64-20240309-release.tar.xz/lib/libmlib_image.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjsig.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement_ext.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/liblcms.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libdt_socket.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsyslookup.so success
I/jrelog  (14023): dlopen /data/us
er/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnio.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libextnet.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libzip.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjimage.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libprefs.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libmanagement.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjaas.so success
I/jrelog  (14023): dlopen /da
ta/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfreetype.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libnet.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/librmi.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjli.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libj2gss.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libverify.so success
I/jrelog  (14023): dlo
pen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_headless.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libjawt.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libsctp.so success
I/jrelog  (14023): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/jre21-arm64-20240309-release.tar.xz/lib/libawt_xawt.so success
I/jrelog  (14023): dlopen /data/app/~~n4_dOGr7uKLR3PFqaxEoRw==/net.kdt.pojavlaunch-E7KjnVSosx-Tgofgue6TqQ==/lib/arm64/libopenal.so success
I/jrelog  (14023): Done processing args
I/jrelog  (14023): Found JLI lib
I/jrelog  (14023): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(Unknown Source)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(Unknown Source)
	at java.base/java.lang.System.initPhase3(Unknown Source)
ERROR StatusConsoleListener appender Console has no parameter that matches element Policies
[22:35:48] [main/WARN]: Failed retrieving info for group processor
java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~n4_dOGr7uKLR3PFqaxEoRw==/net.kdt.pojavlaunch-E7KjnVSosx-Tgofgue6TqQ==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.g(SourceFile:234) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.jar:?]
[22:35:48] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.g(SourceFile:234) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~n4_dOGr7uKLR3PFqaxEoRw==/net.kdt.pojavlaunch-E7KjnVSosx-Tgofgue6TqQ==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	... 6 more
[22:35:48] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 317 milliseconds
[22:35:52] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[22:35:52] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[22:35:52] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[22:35:53] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[22:35:53] [Render thread/INFO]: Setting user: BODIZZLY
Registered forkAndExec
[22:35:53] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[22:35:53] [Render thread/ERROR]: Error parsing option value 0.5d for option Text Background Opacity: Failed to parse either. First: Not a number: "0.5d"; Second: Not a boolean: "0.5d"
[22:35:53] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
AdrenoSupp: Loaded Turnip, loader address: 0xfe4a327b99b8347
OSMDroid: generating context
OSMDroid: context=0x7c52c2c530
OSMDroid: making current 0x7c12b82120
OSMDroid: vendor: Mesa
OSMDroid: renderer: zink (Turnip Adreno (TM) 730)
[22:35:53] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[22:35:53] [Render thread/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.a(SourceFile:226) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:246) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~n4_dOGr7uKLR3PFqaxEoRw==/net.kdt.pojavlaunch-E7KjnVSosx-Tgofgue6TqQ==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.<init>(SourceFile:56) ~[1.21.jar:?]
	at o.<init>(SourceFile:35) ~[1.21.jar:?]
	at o.g(SourceFile:234) ~[1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) ~[1.21.jar:?]
[22:35:53] [Render thread/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.linux.LinuxGlobalMemory
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.a(SourceFile:226) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:246) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem [in thread "main"]
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.<init>(SourceFile:56) ~[1.21.jar:?]
	at o.<init>(SourceFile:35) ~[1.21.jar:?]
	at o.g(SourceFile:234) ~[1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) ~[1.21.jar:?]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-06-15 22:35:53
Description: Initializing game

java.lang.NoSuchMethodError: 'void org.lwjgl.glfw.GLFW.glfwSetWindowSizeLimits(long, int, int, int, int)'
	at fam.<init>(SourceFile:117)
	at gfr.a(SourceFile:21)
	at fgo.<init>(SourceFile:505)
	at net.minecraft.client.main.Main.main(SourceFile:239)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fam.<init>(SourceFile:117)
	at gfr.a(SourceFile:21)
	at fgo.<init>(SourceFile:505)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:239)

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (aarch64) version Android-14
	Java Version: 21.0.1-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2048873208 bytes (1953 MiB) / 2275409920 bytes (2170 MiB) up to 2275409920 bytes (2170 MiB)
	CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 1536.64, total: 106607.95
	Space in storage for workdir (MiB): available: 1536.64, total: 106607.95
	JVM Flags: 3 total; -Xms2170M -Xmx2170M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.21
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2024-06-15_22.35.53-client.txt
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7aeb765480)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7e2e27cee0)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7e33630dd8)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7b032a8298)
FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x7e33630dd8)

![Screenshot_20240615_225541_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/86253866/641c32b3-bae6-4810-9df1-283f7aa04cbc)

### Steps To Reproduce

```markdown
I just downloaded this i have no idea how to
```

### Expected Behavior

I expected the game to boot up like normal

### Platform

```markdown
- Device model:samsung 22s ulta 
- CPU architecture:arch64
- Android version:14
- PojavLauncher version: edelweiss-20230928-9484dOc-v3_openj dk
```

**Comment by Marshall2439** [comment]
BRO USE latest version of pojav from "actions" above

**Comment by Marshall2439** [comment]
There is no lwjgl 3.3.3 yet thats why the game is crashing

**Comment by frdude** [comment]
I fixed it by downloading the latest version from here: https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/9521311277

download the "noruntime" APK if you want to update, make sure you have java 21

**Comment by theoparis** [comment]
I'm still getting ```
Installed version: 3.3.1 SNAPSHOT
Required version: 3.3.3

You must change the LWJGL version in your launcher to continue. This is usually controlled by the settings for a profile or instance in your launcher.

```
With the latest github actions build...
