### ISSUE TITLE
I cannot sign in my Microsoft account 

### ISSUE THREAD

**Issue by hackerman4ctrl** [PojavLauncherTeam/PojavLauncher#5601]
### Describe the bug

I cannot sign in my Microsoft account in pojav Launcher. When i try to sign in, became the error: 
java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:284)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:84)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

![Screenshot_2024-06-16-09-16-47-040_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172955669/270de895-4ca1-4923-bfb3-de3a785ce02e)

Yes, i know that i can play offline, but i want play online with my frends
Help me please 🥺

### The log file and images/videos

![Screenshot_2024-06-16-09-16-47-040_net kdt pojavlaunch](https://github.com/PojavLauncherTeam/PojavLauncher/assets/172955669/50450091-ccf0-49b7-9344-d18af83b1499)

### Steps To Reproduce

```markdown
1. Start Pojav Launcher 
2. Click 'Play'
3. Click 'Microsoft account'
4. Enter my g-mail adres
5. Enter my password 
6. *Error*
```

### Expected Behavior

I expect that i sing in my Microsoft account and start playing Minecraft 

### Platform

```markdown
- Redmi 10 Pro 6/128 Gb
- Snapdragon 732G Mobile Platform 8 cores 2.3GGz
- Android 12
- 3.3.1.1; also tried the last version of 28 sept 2023
```

### Anything else?

At first I tried to sign in on the last version in Google Play (it made 28 Sept 2023). Than I tried version 3.1.1.1 by  guides from Google. I saw the same error.

**Comment by GaucovyAero** [comment]
try logging into minecraft.net and then into pojav, otherwise buy minecraft java edition
