### ISSUE TITLE
[BUG] Minecraft won't download.

### ISSUE THREAD

**Issue by Wycat0913** [PojavLauncherTeam/PojavLauncher#5609]
### Describe the bug

All I get is this
![Uploading Screenshot_20240617-104954.png…]()
But I have the download source se
![Screenshot_20240617-105426](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173076216/cd5a9d33-986e-4509-9fa3-bac428d8d360)
t to default.

### The log file and images/videos

![Screenshot_20240617-104954](https://github.com/PojavLauncherTeam/PojavLauncher/assets/173076216/f6657d0a-3c7b-469a-ad78-b8cd11cae382)

### Steps To Reproduce

```markdown
Not reproducible
```

### Expected Behavior

For Minecraft to download.

### Platform

```markdown
- Device model: Nokia C110
- CPU architecture:
- Android version: 12
- PojavLauncher version: newest
```

### Anything else?

java.io.IOException: Unable to read Version JSON for version 1.7.10
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:203)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by ghost** [comment]
Try this
![Screenshot_2024-06-17-21-53-20-402_com android settings-edit](https://github.com/PojavLauncherTeam/PojavLauncher/assets/140465266/db8b3794-014b-47d2-825d-09a0a7b42461)
Go to settings>additional settings>developer options and you find it if problem doesn't fix delete pojav and install it again be sure backup you world to not delete

**Comment by Wycat0913** [comment]
Also there are no versions in the menu

**Comment by Wycat0913** [comment]
It isn't in my settings

**Comment by Wycat0913** [comment]
It isn't in my settings

**Comment by Wycat0913** [comment]
I have a Nokia c110

**Comment by 5ghzx** [comment]
go to about phone, tap on the build number 7 times, then try those steps

**Comment by Wycat0913** [comment]
I fixed it another way!

**Comment by Wycat0913** [comment]
> I fixed it by resetting connection settings!
