### ISSUE TITLE
[BUG] 1.21 crash 

### ISSUE THREAD

**Issue by DrookPi** [PojavLauncherTeam/PojavLauncher#5618]
### Describe the bug

1.21 is crashing 

### The log file and images/videos

this is inside of the latest.log: [10:24:53] [main/WARN]: Failed retrieving info for group processor
java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch-2/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.g(SourceFile:234) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.jar:?]
[10:24:53] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.g(SourceFile:234) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch-2/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	... 6 more
[10:24:56] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 3035 milliseconds
[10:25:30] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[10:25:30] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[10:25:30] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[10:25:31] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:25:31] [Render thread/INFO]: Setting user: ProDrook
[10:25:32] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[10:25:33] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[10:25:33] [Render thread/INFO]: [STDERR]: [LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
[10:25:34] [Render thread/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.a(SourceFile:226) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:246) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/net.kdt.pojavlaunch-2/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:79) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.<init>(SourceFile:56) ~[1.21.jar:?]
	at o.<init>(SourceFile:35) ~[1.21.jar:?]
	at o.g(SourceFile:234) ~[1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) ~[1.21.jar:?]
[10:25:34] [Render thread/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.linux.LinuxGlobalMemory
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) [1.21.jar:?]
	at ac.<init>(SourceFile:56) [1.21.jar:?]
	at o.<init>(SourceFile:35) [1.21.jar:?]
	at o.a(SourceFile:226) [1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:246) [1.21.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem [in thread "main"]
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.a(SourceFile:81) ~[1.21.jar:?]
	at ac.e(SourceFile:56) ~[1.21.jar:?]
	at ac.a(SourceFile:87) ~[1.21.jar:?]
	at ac.<init>(SourceFile:56) ~[1.21.jar:?]
	at o.<init>(SourceFile:35) ~[1.21.jar:?]
	at o.g(SourceFile:234) ~[1.21.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) ~[1.21.jar:?]

### Steps To Reproduce

```markdown
1. Start pojavlauncher.
2. Select 1.21
3. Play.
4. Crash.
```

### Expected Behavior

![IMG_20240618_224701](https://github.com/PojavLauncherTeam/PojavLauncher/assets/146542776/d07db782-eeb6-4191-be98-de4265d60620)
open Minecraft normally 

### Platform

```markdown
- Device model:Oppo A1601
- CPU architecture: 64-bit ARM
- Android version: 6
- PojavLauncher version: edelweiss-20230928-9484d0c-v3_openjdk
```

**Comment by Xirren** [comment]
did you fix this?

**Comment by DrookPi** [comment]
> did you fix this?

yes, I updated pojav launcher and then the crash was gone

**Comment by Jl0621** [comment]
**Is your problem solve? Cause I have the same issue._**

**Comment by Xirren** [comment]
> **Is your problem solve? Cause I have the same issue._**

**Comment by Xirren** [comment]
> **Is your problem solve? Cause I have the same issue._**

i remember i downloaded another java runtime，and it worked.
unfortunately ,i don't remember which did i download....

**Comment by octozinho** [comment]
Im having the same issue using fabric with mods, did ya solve it ?

**Comment by amexz1** [comment]
I have this problem how to solve this 
I updated pojav launcher but didn't solve that bug

**Comment by Ronak726** [comment]
- remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the
