### ISSUE TITLE
[NOTICE] Create Mod is working when using new Flywheel.

### ISSUE THREAD

**Issue by Eggmanplant** [PojavLauncherTeam/PojavLauncher#5652]
### Is this request related to a bug?

On the page, it is stated that the Create Mod is not working

### Describe the request.

Here is the mod, freshly built from the 1.20.1/flywheel-upgrade branch with flywheel 1.0.0-beta-92:
[create-1.20.1-0.5.1.f-updated.zip](https://github.com/user-attachments/files/15953404/create-1.20.1-0.5.1.f-updated.zip)
Make sure to unzip the file, move the contents to the mods folder, install Forge, change the renderer to ANGLE, and enjoy!

### Anything else?

Tested on Pixel 7a, which has an Mali GPU.
You may need to run `/flywheel backend flywheel:off` in the Minecraft chat to fix train rendering, and get better performance.
Most addons should be patched to work with this version.
EDIT: Here is an example (Dramatic Doors patched to work with my Create version): [DramaticDoors-1.20.1-3.2.2-forge-updated.zip](https://github.com/user-attachments/files/15953321/DramaticDoors-1.20.1-3.2.2-forge-updated.zip)
Source code: https://github.com/Eggmanplant/DramaticDoors

**Comment by Doorpol** [comment]
> ### Is this request related to a bug?
> On the page, it is stated that the Create Mod is not working
> 
> ### Describe the request.
> Here is the mod, freshly built from the 1.20.1/flywheel-upgrade branch with flywheel 1.0.0-beta-92: [create-1.20.1-0.5.1.f-updated.zip](https://github.com/user-attachments/files/15953404/create-1.20.1-0.5.1.f-updated.zip) Make sure to unzip the file, move the contents to the mods folder, install Forge, change the renderer to ANGLE, and enjoy!
> 
> ### Anything else?
> Tested on Pixel 7a, which has an Mali GPU. You may need to run `/flywheel backend flywheel:off` in the Minecraft chat to fix train rendering, and get better performance. Most addons should be patched to work with this version. EDIT: Here is an example (Dramatic Doors patched to work with my Create version): [DramaticDoors-1.20.1-3.2.2-forge-updated.zip](https://github.com/user-attachments/files/15953321/DramaticDoors-1.20.1-3.2.2-forge-updated.zip) Source code: https://github.com/Eggmanplant/DramaticDoors

Crash man

**Comment by Eggmanplant** [comment]
> > ### Is this request related to a bug?
> > On the page, it is stated that the Create Mod is not working
> > ### Describe the request.
> > Here is the mod, freshly built from the 1.20.1/flywheel-upgrade branch with flywheel 1.0.0-beta-92: [create-1.20.1-0.5.1.f-updated.zip](https://github.com/user-attachments/files/15953404/create-1.20.1-0.5.1.f-updated.zip) Make sure to unzip the file, move the contents to the mods folder, install Forge, change the renderer to ANGLE, and enjoy!
> > ### Anything else?
> > Tested on Pixel 7a, which has an Mali GPU. You may need to run `/flywheel backend flywheel:off` in the Minecraft chat to fix train rendering, and get better performance. Most addons should be patched to work with this version. EDIT: Here is an example (Dramatic Doors patched to work with my Create version): [DramaticDoors-1.20.1-3.2.2-forge-updated.zip](https://github.com/user-attachments/files/15953321/DramaticDoors-1.20.1-3.2.2-forge-updated.zip) Source code: https://github.com/Eggmanplant/DramaticDoors
> 
> Crash man

What device?
And, please post the crash log.
Please change the renderer to "ANGLE (mid, 1.17+)" if you didn't.

**Comment by MustafaMokhtar** [comment]
Whenever i try to install rubidium it causes an immediate crash and without create it works fine . Any idea how to fix

**Comment by Eggmanplant** [comment]
> Whenever i try to install rubidium it causes an immediate crash and without create it works fine . Any idea how to fix

Don't use Rubidium or Embeddium. They cause issues.

**Comment by MustafaMokhtar** [comment]
Then what do i use for performance? 
With out it the game will be unplayable.

**Comment by Eggmanplant** [comment]
For last chance try using Embeddium, which is a fork of Rubidium which has greater compatibility with mods, buy a stronger phone, or use superflat.
Does the mod at least work without performance mods?

**Comment by Muazraza** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 2024-11-20 11:24:31
Description: Unexpected error

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:162) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83950_(RenderTarget.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83964_(RenderTarget.java:64) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83941_(RenderTarget.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.enableStencil(RenderTarget.java:317) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:295) ~[create-1.20.1-0.5.1.f-updated.jar%23121!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:36) ~[create-1.20.1-0.5.1.f-updated.jar%23121!/:0.5.1.f] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.backend.mixins.json:RenderSystemMixin,pl:mixin:APP:create.mixins.json:accessor.RenderSystemAccessor,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.backend.mixins.json:RenderSystemMixin,pl:mixin:APP:create.mixins.json:accessor.RenderSystemAccessor,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.impl.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.impl.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.3.11.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Create (create), Version: 0.5.1.f
		Issue tracker URL: https://github.com/Creators-of-Create/Create/issues
		at TRANSFORMER/create@0.5.1.f/com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:295)
Stacktrace:
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83949_(RenderTarget.java:162) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83950_(RenderTarget.java:140) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83964_(RenderTarget.java:64) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.m_83941_(RenderTarget.java:52) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mojang.blaze3d.pipeline.RenderTarget.enableStencil(RenderTarget.java:317) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.simibubi.create.foundation.gui.UIRenderHelper$CustomRenderTarget.create(UIRenderHelper.java:295) ~[create-1.20.1-0.5.1.f-updated.jar%23121!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.foundation.gui.UIRenderHelper.lambda$init$0(UIRenderHelper.java:36) ~[create-1.20.1-0.5.1.f-updated.jar%23121!/:0.5.1.f] {re:mixin,re:classloading}
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:226) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.backend.mixins.json:RenderSystemMixin,pl:mixin:APP:create.mixins.json:accessor.RenderSystemAccessor,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:213) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,re:classloading,pl:mixin:APP:flywheel.backend.mixins.json:RenderSystemMixin,pl:mixin:APP:create.mixins.json:accessor.RenderSystemAccessor,pl:mixin:A}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, mod_resources
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2326) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.impl.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23122!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.impl.mixins.json:MinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.3.11.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3437706472 bytes (3278 MiB) / 3808428032 bytes (3632 MiB) up to 3808428032 bytes (3632 MiB)
	CPUs: 8
	Processor Vendor: 0x53
	Processor Name: 
	Identifier: 0x53 Family 8 Model 0x002 Stepping r0p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7895.81
	Virtual memory used (MB): 6906.61
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 1862.14
	JVM Flags: 3 total; -Xms3632M -Xmx3632M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Mali-G72 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
	Window size: 1440x648
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: en_us
	CPU: 8x 
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.11.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.3.11-universal.jar                |Forge                         |forge                         |47.3.11             |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.20.1-1.0.0-beta-92.jar           |Flywheel                      |flywheel                      |1.0.0-beta          |ENQUEUE_IM|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f-updated.jar                 |Create                        |create                        |0.5.1.f             |ENQUEUE_IM|Manifest: NOSIGNATURE
	Flywheel Backend: flywheel:off
	Crash Report UUID: 5cf3f0e6-b197-4d7c-b1cb-21da2628a194
	FML: 47.3
	Forge: net.minecraftforge:47.3.11

**Comment by Eggmanplant** [comment]
Sorry, I'm unsubscribing from this thread. Way too many skids that even don't know that Sodium has issues on Pojav. I made this mainly for myself to run Create on my Google Pixel. Not using Pojav anymore.

**Comment by ghost** [comment]
> Sorry, I'm unsubscribing from this thread. Way too many skids that even don't know that Sodium has issues on Pojav. I made this mainly for myself to run Create on my Google Pixel. Not using Pojav anymore.

Use LTW renderer for sodium compatibility on pojav.
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158

**Comment by DLuis1313** [comment]
> > Sorry, I'm unsubscribing from this thread. Way too many skids that even don't know that Sodium has issues on Pojav. I made this mainly for myself to run Create on my Google Pixel. Not using Pojav anymore.
> 
> Use LTW renderer for sodium compatibility on pojav. https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158

But LTW doesn't support Create Mod, it actually does but if you create a train the game 
Crash

**Comment by Brickmaster1** [comment]
> > > Sorry, I'm unsubscribing from this thread. Way too many skids that even don't know that Sodium has issues on Pojav. I made this mainly for myself to run Create on my Google Pixel. Not using Pojav anymore.
> > 
> > 
> > Use LTW renderer for sodium compatibility on pojav. https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158
> 
> But LTW doesn't support Create Mod, it actually does but if you create a train the game Crash

You have to turn off flywheel's features, as they are incompatible with pojav, by going into a world where you won't crash (no contraptions) and type "/flywheel backend off" in chat (no quotes of course)

**Comment by Marshall2439** [comment]
you can use instancing flywheel with new ltw but some malis would have rendering bugs so use batching/off instead

**Comment by DLuis1313** [comment]
Yeah it works but for me only when flywheel is off cause batching and instancing makes the game lag and have render bugs maybe cause my phone gpu is mali¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
