### ISSUE TITLE
[BUG] The latest Forge 1.7.10 install does not load

### ISSUE THREAD

**Issue by FlookyPupper** [PojavLauncherTeam/PojavLauncher#5713]
### Describe the bug

The latest Forge 1.7.10 doesn't install and the installer apparently crashes.

### The log file and images/videos

```
Info: Java arguments: [-Djava.security.policy=/data/user/0/net.kdt.pojavlaunch.debug/security/java_sandbox.policy, -Djava.security.manager=net.sourceforge.prograde.sm.ProGradeJSM, -Xbootclasspath/a:/data/user/0/net.kdt.pojavlaunch.debug/security/pro-grade.jar, -Djava.awt.headless=false, -Dcacio.managed.screensize=720x600, -Dcacio.font.fontmanager=sun.awt.X11FontManager, -Dcacio.font.fontscaler=sun.font.FreetypeFontScaler, -Dswing.defaultlaf=javax.swing.plaf.metal.MetalLookAndFeel, -Dawt.toolkit=com.github.caciocavallosilano.cacio.ctc.CTCToolkit, -Djava.awt.graphicsenv=com.github.caciocavallosilano.cacio.ctc.CTCGraphicsEnvironment, -Djava.system.class.loader=com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader, --add-exports=java.desktop/java.awt=ALL-UNNAMED, --add-exports=java.desktop/java.awt.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED, --add-exports=java.desktop/sun.java2d=ALL-UNNAMED, --add-exports=java.desktop/java.awt.dnd.peer=ALL-UNNAMED, --add-exports=java.desktop/sun.awt=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.event=ALL-UNNAMED, --add-exports=java.desktop/sun.awt.datatransfer=ALL-UNNAMED, --add-exports=java.desktop/sun.font=ALL-UNNAMED, --add-exports=java.base/sun.security.action=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.desktop/java.awt=ALL-UNNAMED, --add-opens=java.desktop/sun.font=ALL-UNNAMED, --add-opens=java.desktop/sun.java2d=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.net=ALL-UNNAMED, -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar, -javaagent:/data/user/0/net.kdt.pojavlaunch.debug/forge_installer/forge_installer.jar=NPS, -jar, /data/user/0/net.kdt.pojavlaunch.debug/cache/forge-installer.jar]
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=2340
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~pOZQPQCzBULxyzn3tS2J-A==/net.kdt.pojavlaunch.debug-5MHZGjiyXHZlOxc8OARQtg==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~pOZQPQCzBULxyzn3tS2J-A==/net.kdt.pojavlaunch.debug-5MHZGjiyXHZlOxc8OARQtg==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: LIBGL_ES=null
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjli.so success
I/jrelog  (31804): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/server/libjvm.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libverify.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjava.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libnet.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libnio.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libawt.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libfreetype.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libfontmanager.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libawt_xawt.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjimage.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libdt_socket.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjava.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libsyslookup.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libfontmanager.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libmanagement_agent.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjaas.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjsig.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libprefs.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libawt.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libfreetype.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/liblcms.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjli.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libnio.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libmanagement_ext.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/server/libjsig.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/server/libjvm.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libawt_headless.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libmlib_image.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libj2gss.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjdwp.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libzip.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libinstrument.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libj2pkcs11.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libmanagement.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjawt.so success

I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libextnet.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libnet.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libverify.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libjavajpeg.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/libsctp.so success
I/jrelog  (31804): dlopen /data/user/0/net.kdt.pojavlaunch.debug/runtimes/jre21-arm64-20240423-release.tar.xz/lib/librmi.so success

I/jrelog  (31804): dlopen /data/app/~~pOZQPQCzBULxyzn3tS2J-A==/net.kdt.pojavlaunch.debug-5MHZGjiyXHZlOxc8OARQtg==/lib/arm64/libopenal.so success

I/jrelog  (31804): Done processing args
I/jrelog  (31804): Found JLI lib
I/jrelog  (31804): Calling JLI_Launch

Policy policy.url.2=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.java.policy wasn't successfully parsed. Exception message: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.java.policy (No such file or directory)
WARNING: A command line option has enabled the Security Manager
WARNING: The Security Manager is deprecated and will be removed in a future release
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(Unknown Source)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(Unknown Source)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(Unknown Source)
	at java.base/java.lang.System.initPhase3(Unknown Source)
Setting up logger: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/forge-installer.jar.log
JVM info: N/A - 21.0.1-internal - 21.0.1-internal-adhoc.runner.openjdk
java.net.preferIPv4Stack=true
Found java version 21.0.1-internal
Exception in thread "main" java.awt.HeadlessException
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(Unknown Source)
	at java.desktop/sun.font.FontDesignMetrics.getDefaultFrc(Unknown Source)
	at java.desktop/sun.font.FontDesignMetrics.getMetrics(Unknown Source)
	at java.desktop/sun.swing.SwingUtilities2.getFontMetrics(Unknown Source)
	at java.desktop/javax.swing.JComponent.getFontMetrics(Unknown Source)
	at java.desktop/javax.swing.text.PlainView.calculateLongestLine(Unknown Source)
	at java.desktop/javax.swing.text.PlainView.updateMetrics(Unknown Source)
	at java.desktop/javax.swing.text.PlainView.updateDamage(Unknown Source)
	at java.desktop/javax.swing.text.PlainView.insertUpdate(Unknown Source)
	at java.desktop/javax.swing.text.FieldView.insertUpdate(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.insertUpdate(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$UpdateHandler.insertUpdate(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(Unknown Source)
	at java.desktop/javax.swing.text.PlainDocument.insertString(Unknown Source)
	at java.desktop/javax.swing.text.AbstractDocument.replace(Unknown Source)
	at java.desktop/javax.swing.text.JTextComponent.setText(Unknown Source)
	at net.minecraftforge.installer.InstallerPanel.updateFilePath(InstallerPanel.java:328)
	at net.minecraftforge.installer.InstallerPanel.<init>(InstallerPanel.java:319)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:178)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:65)
```
![Screenshot_20240629-152148_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/69437909/92729cc0-bcda-48bd-b5a8-b96b90d6c415)
![Screenshot_20240629-152107_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/69437909/5c468e59-4aca-433c-b443-18c1e8b59c8e)
![Screenshot_20240629-152030_PojavLauncher (Minecraft_ Java Edition for Android)](https://github.com/PojavLauncherTeam/PojavLauncher/assets/69437909/7b2b191b-a87d-4935-a659-1916f001b1bb)

### Steps To Reproduce

```markdown
1. Start PojavLauncher (latest debug automation build)
2. Open the Profile dropdown (where it says the current selected version)
3. Touch on "Create new profile"
4. Select "CREATE FORGE PROFILE"
5. Scroll down and find 1.7.10.
6. Select the latest Forge 1.7.10 build (in this case its 1.7.10-10.13.4.1614-1.7.10)
7. Click on it and wait until the launcher downloads the file.
```

### Expected Behavior

Information dialog should come up downloading.

### Platform

```markdown
- Device model: OnePlus 6T
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240626-df0b762-v3_openjdk
```

### Anything else?

I have tried other Forge builds of 1.7.10 and they work fine. I'm putting this here, I don't want to be entitled and stuff even though I do prefer to use the latest Forge. So I understand if this will be a wontfix. For now, I will be using an older Forge version. I deeply apologise to the maintainers if this is an invalid or wontfix issue in advance.

**Comment by FlookyPupper** [comment]
how do I delete an issue
