### ISSUE TITLE
Controllerable forge mod yields java.lang.UnsatisfiedLinkError while launching

### ISSUE THREAD

**Issue by toosyou** [PojavLauncherTeam/PojavLauncher#573]
## Environment
* Xiaomi 9T pro
* Android 10
* PojavLauncher: 3.3.1b_6409b_20201210
* Minecraft: 1.16.4
* forge-1.16.4-35.1.15
    * controllable: 1.16.3-0.8.3

## What I did
I tried to install [controllable mod](https://www.curseforge.com/minecraft/mc-mods/controllable) for joystick support.
While nothing wrong happened in the PC version, PojavLauncher+forge yields `UnsatisfiedLinkError`.
Since it stated something about `org.libsdl.SDL`, I wondered if it's lacking some libraries in the android port JDK?

## Crash Report

```java
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 21-1-6 下午4:39
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
 at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
 at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
 at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:controllable:send_click,xf:fml:controllable:process_keys,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
 at net.minecraft.util.Util.func_215077_a(SourceFile:404) ~[?:?] {re:classloading}
 at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:controllable:send_click,xf:fml:controllable:process_keys,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
 at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
 at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:controllable:screen_render_patch,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinGameRenderer_B,pl:mixin:APP:imm_ptl_mixins.json:client.render.MixinGameRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
 at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:controllable:send_click,xf:fml:controllable:process_keys,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:controllable:send_click,xf:fml:controllable:process_keys,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
 at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.15.jar:?] {re:classloading,pl:runtimedistcleaner:A}
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
 at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
 at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.15.jar:35.1] {}
 at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
 at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
 at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
 at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
 at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
 at org.libsdl.SDL.SDL_INIT_TIMER(Native Method) ~[controllable:1.16.3-0.8.3] {re:classloading}
-- MOD controllable --
Details:
 Mod File: controllable-1.16.3-0.8.3.jar
 Failure message: Controllable (controllable) encountered an error during the sided_setup event phase
  java.lang.UnsatisfiedLinkError: org.libsdl.SDL.SDL_INIT_TIMER()I
 Mod Version: 0.8.3
 Mod Issue URL: https://github.com/MrCrayfish/Controllable/issues
 Exception message: java.lang.UnsatisfiedLinkError: org.libsdl.SDL.SDL_INIT_TIMER()I
Stacktrace:
 at org.libsdl.SDL.SDL_INIT_TIMER(Native Method) ~[controllable:1.16.3-0.8.3] {re:classloading}
 at org.libsdl.SDL.<clinit>(SDL.java:348) ~[controllable:1.16.3-0.8.3] {re:classloading}
 at uk.co.electronstudio.sdl2gdx.SDL2ControllerManager.<init>(SDL2ControllerManager.java:44) ~[controllable:1.16.3-0.8.3] {re:classloading}
 at uk.co.electronstudio.sdl2gdx.SDL2ControllerManager.<init>(SDL2ControllerManager.java:25) ~[controllable:1.16.3-0.8.3] {re:classloading}
 at com.mrcrayfish.controllable.Controllable.onClientSetup(Controllable.java:72) ~[controllable:1.16.3-0.8.3] {re:classloading}
 at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
 at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
 at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
 at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
 at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
 at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0-internal] {}
 at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0-internal] {}
 at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0-internal] {}
 at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0-internal] {}
 at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0-internal] {}
 at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0-internal] {}


-- System Details --
Details:
 Minecraft Version: 1.16.4
 Minecraft Version ID: 1.16.4
 Operating System: Linux (aarch64) version Android-10
 Java Version: 1.8.0-internal, Oracle Corporation
 Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 340696528 bytes (324 MB) / 838860800 bytes (800 MB) up to 838860800 bytes (800 MB)
 CPUs: 8
 JVM Flags: 8 total; -Xms512m -Xmx800m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
 ModLauncher: 8.0.6+85+master.325de55
 ModLauncher launch target: fmlclient
 ModLauncher naming: srg
 ModLauncher services: 
  /mixin-0.8.2.jar mixin PLUGINSERVICE 
  /eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
  /forge-1.16.4-35.1.15.jar object_holder_definalize PLUGINSERVICE 
  /forge-1.16.4-35.1.15.jar runtime_enum_extender PLUGINSERVICE 
  /accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
  /forge-1.16.4-35.1.15.jar capability_inject_definalize PLUGINSERVICE 
  /forge-1.16.4-35.1.15.jar runtimedistcleaner PLUGINSERVICE 
  /mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
  /forge-1.16.4-35.1.15.jar fml TRANSFORMATIONSERVICE 
 FML: 35.1
 Forge: net.minecraftforge:35.1.15
 FML Language Providers: 
  javafml@35.1
  minecraft@1
 Mod List: 
  forge-1.16.4-35.1.15-client.jar |Minecraft |minecraft |1.16.4 |ENQUEUE_IM|NOSIGNATURE
  immersive-portals-0.11-mc1.16.4-forge.jar |Immersive Portals |immersive_portals |0.7 |ENQUEUE_IM|NOSIGNATURE
  OfflineSkins-1.16.4-v1.jar |OfflineSkins |offlineskins |1.16.4-v1 |ENQUEUE_IM|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
  justmobheads_1.16.4-3.7.jar |Just Mob Heads |justmobheads |3.7 |ENQUEUE_IM|NOSIGNATURE
  forge-1.16.4-35.1.15-universal.jar |Forge |forge |35.1.15 |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
  justplayerheads_1.16.4-1.4.jar |Just Player Heads |justplayerheads |1.4 |ENQUEUE_IM|NOSIGNATURE
  controllable-1.16.3-0.8.3.jar |Controllable |controllable |0.8.3 |ERROR |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
  collective-1.16.4-1.53.jar |Collective |collective |1.53 |ENQUEUE_IM|NOSIGNATURE
 Crash Report UUID: eee4364d-8163-4ef6-abe2-4bd99bd23a54
```

**Comment by artdeell** [comment]
To function, Controllable requires the SDL library, and we can't get it on Android to function as the Controllable mod expects
