### ISSUE TITLE
[BUG] Game Crashes when using Labymod 4

### ISSUE THREAD

**Issue by AikaAyane** [PojavLauncherTeam/PojavLauncher#5738]
### Describe the bug

I just downloaded and installed Labymod 4 on pojavlauncher but it just keeps exiting itself with error code 1

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16089570/latestlog.txt)
![Screenshot_20240704-025726](https://github.com/PojavLauncherTeam/PojavLauncher/assets/174644048/44e4e298-c26d-41af-917f-a36446a1767e)

### Steps To Reproduce

```markdown
1. Download Labymod 4 from their official website 

2. Install on Pojavlauncher with the jar file

3. Run game and crash occurred
```

### Expected Behavior

Expected to run but...

### Platform

```markdown
- Device model: Pixel 4a
- CPU architecture: arm-v8a
- Android version: 10
- PojavLauncher version: foxglove-20240626-df0b762-v3_openjdk
```

**Comment by Dilen0001** [comment]
.

**Comment by GaucovyAero** [comment]
no idea
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.labymod.api.loader.platform.PlatformEnvironment.<clinit>(PlatformEnvironment.java:16)
	at net.labymod.core.loader.vanilla.launchwrapper.Java17LabyModLaunchWrapperTweaker.acceptOptions(Java17LabyModLaunchWrapperTweaker.java:82)
	at net.labymod.core.loader.vanilla.launchwrapper.LabyModLaunchWrapperTweaker.acceptOptions(LabyModLaunchWrapperTweaker.java:105)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:188)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:70)
Caused by: java.lang.NullPointerException: Cannot invoke "net.labymod.api.loader.MinecraftVersion.getReleaseTime()" because "current" is null
	at net.labymod.api.loader.MinecraftVersion.initialize(MinecraftVersion.java:32)
	at net.labymod.api.loader.MinecraftVersions.<clinit>(MinecraftVersions.java:1018)
	... 5 more
Java Exit code: 1
```

**Comment by PurpleBear31** [comment]
Я наверное сделаю решение...
