### ISSUE TITLE
[BUG] Forge 1.8.9 Crashes with some random Mods

### ISSUE THREAD

**Issue by SirMrNecron** [PojavLauncherTeam/PojavLauncher#5764]
### Describe the bug

When i use some mods like essentials and Patcher Mods before that i see white mojang screen it crash , but not all mods 

### The log file and images/videos

LOG : 
[02:16:42] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[02:16:43] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[02:16:43] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[02:16:43] [main/INFO]: Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9 loading
[02:16:43] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_392-internal, running on Linux:aarch64:Android-7.0, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal
[02:16:43] [main/INFO]: Loading tweaker gg.essential.loader.stage0.EssentialSetupTweaker from essential_1-3-2-8_forge_1-8-9.jar
[02:16:43] [main/INFO]: Loading tweaker com.spiderfrog.gadgets.main.OAMTweaker from OldAnimationsMod-Animations & Cosmetics_2.7.1-mc_Forge1.8.9.jar
[02:16:43] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.9_HD_U_L5.jar
[02:16:43] [main/INFO]: Loading tweaker gg.essential.loader.stage0.EssentialSetupTweaker from Patcher-1.8.9 (1.8.9).jar
[02:16:43] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[02:16:43] [main/INFO]: Loading tweak class name gg.essential.loader.stage0.EssentialSetupTweaker
[02:16:46] [main/INFO]: Starting Essential Loader (stage2) version 1.6.2 (04447d7f5abf361e4fe3d7d995d4d000) [stable]
[02:16:46] [main/INFO]: Downloading 58021KB of updates...
[02:16:46] [main/INFO]: 1KB / 58021KB (0%)
[02:16:47] [main/INFO]: 24350KB / 58021KB (41%)
[02:16:49] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:28) ~[essential_1-3-2-8_forge_1-8-9.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53) ~[essential_1-3-2-8_forge_1-8-9.jar:?]
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) ~[essential_1-3-2-8_forge_1-8-9.jar:?]
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293) ~[stage1.jar:9]
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44) ~[stage1.jar:9]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53) ~[essential_1-3-2-8_forge_1-8-9.jar:?]
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) ~[essential_1-3-2-8_forge_1-8-9.jar:?]
	... 7 more
Caused by: java.nio.file.FileSystemException: /storage/emulated/0/games/PojavLauncher/.minecraft/essential/Essential (forge_1.8.9).jar: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.nio.fs.UnixCopyFile.copyFile(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.nio.fs.UnixCopyFile.move(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.nio.fs.UnixFileSystemProvider.move(Unknown Source) ~[?:1.8.0_392-internal]
	at java.nio.file.Files.move(Unknown Source) ~[?:1.8.0_392-internal]
	at gg.essential.loader.stage2.EssentialLoaderBase$Mod.installFile(EssentialLoaderBase.java:1018) ~[stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoaderBase$Mod.installPinnedFile(EssentialLoaderBase.java:1034) ~[stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoaderBase.loadMod(EssentialLoaderBase.java:250) ~[stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:133) ~[stage2.forge_1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_392-internal]
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293) ~[stage1.jar:9]
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44) ~[stage1.jar:9]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_392-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_392-internal]
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53) ~[essential_1-3-2-8_forge_1-8-9.jar:?]
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) ~[essential_1-3-2-8_forge_1-8-9.jar:?]
	... 7 more
[02:16:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[02:16:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[02:16:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[02:16:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[02:16:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[02:16:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[02:16:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Steps To Reproduce

```markdown
I add some mods to .minecraft mods folder and i launch it and with code error 1 app crash
```

### Expected Behavior

I test some things like the ram , downloading mods older versions and... But rly i run out of ideas now 

### Platform

```markdown
- Device model: Asus (i rly dont rember lol)
- CPU architecture: arm64
- Android version: 7
- PojavLauncher version: 20230907-5d010fc-v3
```

### Anything else?

Just help me pls :)

**Comment by GaucovyAero** [comment]
try using a different file manager to move the file

**Comment by NDG312** [comment]
I also had the same error, when I use cut this phenomenon happens but when I use copy it doesn't (RS File Manager).
