### ISSUE TITLE
[MCSR] <When downloading the modpack MCSR it crashed>

### ISSUE THREAD

**Issue by AzonexShits** [PojavLauncherTeam/PojavLauncher#5783]
### Describe the bug

When I download a modpack profile of MCSR it crashed before downloading it it shows an error

### The log file and images/videos

java.lang.RuntimeException: java.lang.InterruptedException
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:130)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:151)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask.run(ModDownloader.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.InterruptedException
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask.tryDownload(ModDownloader.java:145)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask.lambda$run$0$net-kdt-pojavlaunch-modloaders-modpacks-api-ModDownloader$DownloadTask(ModDownloader.java:124)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask$$ExternalSyntheticLambda0.call(Unknown Source:4)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:125)
	... 5 more

### Steps To Reproduce

```markdown
Strat Pojav
Install new modpack profile named MCSR
CRASHES
```

### Expected Behavior

To run perfectly and not crash

### Platform

```markdown
- Device model: Samsung a23 5G
- CPU architecture:arm64
- Android version:14
- PojavLauncher version: foxglove-20240709-045018f-v3_openjdk
```

**Comment by GaucovyAero** [comment]
does not work on PrismLauncher (PC) too, it means the modpack is faulty.
