### ISSUE TITLE
[CRASH] Pojav launcher Zink vulkan crash 1.20.1 OPTIFINE 

### ISSUE THREAD

**Issue by Bludose** [PojavLauncherTeam/PojavLauncher#5787]
### Describe the bug

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240709-045018f-v3_openjdk
Info: Architecture: arm64
Info: Device model: vivo V2249
Info: API version: 34
Info: Selected Minecraft version: 1.20.1-OptiFine_HD_U_I6
Info: Custom Java arguments: "-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Ddiscordfix=net.minecraft.client.main.Main"
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: AWTSTUB_WIDTH=1390
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~KBf-SfhoGAqOzc3RqTkpjw==/net.kdt.pojavlaunch.debug-2BwOR-U4UB4CwFPL2_jQmg==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch.debug/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~KBf-SfhoGAqOzc3RqTkpjw==/net.kdt.pojavlaunch.debug-2BwOR-U4UB4CwFPL2_jQmg==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch.debug/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch.debug/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=648
2024-07-13 11:16:00,063 main ERROR appender Console has no parameter that matches element Policies
[11:16:00] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[11:16:00] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[11:16:00] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[11:16:00] [main/INFO]: [OptiFine] OptiFineTweaker: acceptOptions
[11:16:00] [main/INFO]: [OptiFine] OptiFineTweaker: injectIntoClassLoader
[11:16:00] [main/INFO]: [OptiFine] OptiFine ClassTransformer
[11:16:00] [main/INFO]: [OptiFine] OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/optifine/OptiFine/1.20.1_HD_U_I6/OptiFine-1.20.1_HD_U_I6.jar
[11:16:00] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchArguments
[11:16:00] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchTarget
[11:16:02] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2024-07-13 11:16:02,363 main ERROR appender Console has no parameter that matches element Policies
[11:16:04] [main/WARN]: File not found or not readable: /proc/stat
[11:16:05] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[11:16:05] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeEntity.canUpdate
[11:16:05] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.logging.CrashReportExtender
[11:16:07] [main/INFO]: [OptiFine] (Reflector) Method not present: ane.create
[11:16:18] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 1675 milliseconds
[11:16:24] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[11:16:24] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[11:16:24] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[11:16:24] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[11:16:25] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[11:16:27] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
	at enn.a(SourceFile:733) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at enn.<init>(SourceFile:442) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:211) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) ~[launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) ~[launchwrapper-of-2.3.jar:2.3]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
	... 11 more
[11:16:27] [Render thread/INFO]: Setting user: nando
Registered forkAndExec
[11:16:28] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[11:16:28] [Render thread/INFO]: [OptiFine] (Reflector) Method not present: enl.getKeyModifier
[11:16:28] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[11:16:28] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.forge.snapshots.ForgeSnapshotsMod
[11:16:28] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.versions.forge.ForgeVersion
[11:16:28] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
OSMDroid: loading vulkan regularly...
OSMDroid: loaded vulkan, ptr=0x4c040708589aad49
[11:16:28] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.internal.BrandingControl
[11:16:28] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.loading.ImmediateWindowHandler
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
[11:16:29] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.ClassNotFoundException: sun.misc.SharedSecrets
[11:16:29] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.ClassNotFoundException: jdk.internal.misc.SharedSecrets
[11:16:29] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.ClassNotFoundException: sun.misc.VM
[11:16:29] [Render thread/WARN]: [OptiFine] (Reflector) java.lang.reflect.InaccessibleObjectException: Unable to make public static long jdk.internal.misc.VM.maxDirectMemory() accessible: module java.base does not "exports jdk.internal.misc" to unnamed module @12676a70
[11:16:29] [Render thread/INFO]: [OptiFine] 
[11:16:29] [Render thread/INFO]: [OptiFine] OptiFine_1.20.1_HD_U_I6
[11:16:29] [Render thread/INFO]: [OptiFine] Build: 20231221-120401
[11:16:29] [Render thread/INFO]: [OptiFine] OS: Linux (aarch64) version Android-14
[11:16:29] [Render thread/INFO]: [OptiFine] Java: 17.0.12-internal, N/A
[11:16:29] [Render thread/INFO]: [OptiFine] VM: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
[11:16:29] [Render thread/INFO]: [OptiFine] LWJGL: 3.4.0
[11:16:29] [Render thread/INFO]: [OptiFine] OpenGL: zink Vulkan 1.1(Mali-G52 MC2 (ARM_PROPRIETARY)), version 3.1 Mesa 23.2.0-devel (git-957009978e), Mesa
[11:16:29] [Render thread/INFO]: [OptiFine] OpenGL Version: 3.1.0
[11:16:29] [Render thread/INFO]: [OptiFine] Maximum texture size: 16384x16384
[11:16:29] [VersionCheck/INFO]: [OptiFine] Checking for new version
[11:16:29] [Render thread/INFO]: [Shaders] OpenGL Version: 3.1 Mesa 23.2.0-devel (git-957009978e)
[11:16:29] [Render thread/INFO]: [Shaders] Vendor:  Mesa
[11:16:29] [Render thread/INFO]: [Shaders] Renderer: zink Vulkan 1.1(Mali-G52 MC2 (ARM_PROPRIETARY))
[11:16:29] [Render thread/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  - 
[11:16:29] [Render thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8
[11:16:29] [Render thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS: 8
[11:16:29] [Render thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32
[11:16:29] [Render thread/INFO]: [Shaders] Load shaders configuration.
[11:16:29] [Render thread/INFO]: [Shaders] Save shaders configuration.
[11:16:29] [Render thread/INFO]: [Shaders] No shaderpack loaded.
[11:16:29] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.ModList
[11:16:30] [VersionCheck/INFO]: [OptiFine] java.io.FileNotFoundException: http://optifine.net/version/1.20.1/HD_U.txt
[11:16:30] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.ForgeItemModelShaper
[11:16:30] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.lighting.ForgeModelBlockRenderer
[11:16:31] [Render thread/ERROR]: OpenGL SHADER COMPILER ERROR: 1 (0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES)
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.glCompileShader(Native Method) ~[lwjgl-glfw-classes.jar:?]
	at org.lwjgl.opengl.GL20.glCompileShader(GL20.java:593) ~[lwjgl-glfw-classes.jar:?]
	at com.mojang.blaze3d.platform.GlStateManager.glCompileShader(GlStateManager.java:386) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at ehx.b(Program.java:87) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at ehx.a(Program.java:53) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at fki.a(ShaderInstance.java:269) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at fki.<init>(ShaderInstance.java:201) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at fki.<init>(ShaderInstance.java:108) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at fjq.a(GameRenderer.java:500) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at enn.<init>(SourceFile:633) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:211) ~[1.20.1-OptiFine_HD_U_I6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:569) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) ~[launchwrapper-of-2.3.jar:2.3]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) ~[launchwrapper-of-2.3.jar:2.3]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-07-13 11:16:33
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at fjq.a(GameRenderer.java:504)
	at enn.<init>(SourceFile:633)
	at net.minecraft.client.main.Main.main(SourceFile:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: act: Invalid shaders/core/blit_screen.json: Couldn't compile vertex program (vanilla, blit_screen) : 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
	at act.a(SourceFile:48)
	at fki.<init>(ShaderInstance.java:228)
	at fki.<init>(ShaderInstance.java:108)
	at fjq.a(GameRenderer.java:500)
	... 8 more
Caused by: java.io.IOException: Couldn't compile vertex program (vanilla, blit_screen) : 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
	at ehx.b(Program.java:92)
	at ehx.a(Program.java:53)
	at fki.a(ShaderInstance.java:269)
	at fki.<init>(ShaderInstance.java:201)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at fjq.a(GameRenderer.java:504)
	at enn.<init>(SourceFile:633)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (aarch64) version Android-14
	Java Version: 17.0.12-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 693506960 bytes (661 MiB) / 973078528 bytes (928 MiB) up to 973078528 bytes (928 MiB)
	CPUs: 8
	Processor Vendor: 0x41
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd0a Stepping r1p0
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 9007.10
	Virtual memory used (MB): 5736.14
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 1894.99
	JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms920M -Xmx920M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: zink Vulkan 1.1(Mali-G52 MC2 (ARM_PROPRIETARY)) GL version 3.1 Mesa 23.2.0-devel (git-957009978e), Mesa
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'optifine'
	Type: Client (map_client.txt)
	CPU: 8x 
	OptiFine Version: OptiFine_1.20.1_HD_U_I6
	OptiFine Build: 20231221-120401
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1 Mesa 23.2.0-devel (git-957009978e)
	OpenGlRenderer: zink Vulkan 1.1(Mali-G52 MC2 (ARM_PROPRIETARY))
	OpenGlVendor: Mesa
	CpuCount: 8
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/crash-reports/crash-2024-07-13_11.16.32-client.txt

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16201039/latestlog.txt)

### Steps To Reproduce

```markdown
the game is crashing with vulkan Zink not with holy renderer
```

### Expected Behavior

shoud be run

### Platform

```markdown
- Device model: V2249
- CPU architecture: Mali G52
- Android version: 14
- PojavLauncher version: latest
```

### Anything else?

idk help me

**Comment by GaucovyAero** [comment]
please read what the log has to say about your device

```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G52 MC2) doesn't support base Zink requirements: feats.features.logicOp 
```
