### ISSUE TITLE
[BUG] <Zink bug(i think)>

### ISSUE THREAD

**Issue by rgDK039** [PojavLauncherTeam/PojavLauncher#5813]
### Describe the bug

![Screenshot_2024-07-18-14-30-30-71_bab8561a5f94f0a53956d8cbbeaad774](https://github.com/user-attachments/assets/305516aa-5521-4a02-97d7-621439b56700)
![Screenshot_2024-07-18-15-44-16-99_157888a6fcdf6147cb3f40e862978649](https://github.com/user-attachments/assets/b38163ba-2e81-491d-b23c-40f40a153cae)
When I try to use zink render, it keeps showing the error above, but when I use Holy render, it works as usual.

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240709-045018f-v3_openjdk
Info: Architecture: arm64
Info: Device model: realme RMX3630
Info: API version: 33
Info: Selected Minecraft version: fabric-loader-0.15.11-1.20.4
Info: Custom Java arguments: "-Xms1952m -Xmx3148m"
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1146
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~7z7EiREvwN32tmgltPBj_A==/net.kdt.pojavlaunch-xil8Z6hXdAu0YyLAARaKyw==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~7z7EiREvwN32tmgltPBj_A==/net.kdt.pojavlaunch-xil8Z6hXdAu0YyLAARaKyw==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=540
--------- beginning of main
I/jrelog  (10103): dlopen libOSMesa.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (10103): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success

I/jrelog  (10103): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (10103): dlopen /data/app/~~7z7EiREvwN32tmgltPBj_A==/net.kdt.pojavlaunch-xil8Z6hXdAu0YyLAARaKyw==/lib/arm64/libopenal.so success

I/jrelog  (10103): Done processing args
I/jrelog  (10103): Found JLI lib
I/jrelog  (10103): Calling JLI_Launch

2024-07-18 14:26:35,188 main ERROR appender Console has no parameter that matches element Policies
[14:26:35] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[14:26:35] [main/INFO]: Loading 4 mods:
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 17
	- minecraft 1.20.4
[14:26:35] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:26:37] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[14:26:37] [main/WARN]: File not found or not readable: /proc/stat
[14:26:38] [main/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:?]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37130(class_6396.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:277) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:167) ~[fabric-loader-0.15.11-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
[14:26:48] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 576 milliseconds
[14:26:51] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[14:26:51] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[14:26:51] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[14:26:52] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:26:52] [Render thread/INFO]: Setting user: KhanhDinh2k8
Registered forkAndExec
[14:26:52] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[14:26:52] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
OSMDroid: loading vulkan regularly...
OSMDroid: loaded vulkan, ptr=0x1fdb32c5049f36eb
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G57 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance 
[14:26:53] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[authlib-6.0.52.jar:?]
	at net.minecraft.class_310.method_55608(class_310.java:467) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-6.0.52.jar:?]
	... 5 more
[14:26:54] [Render thread/INFO]: OpenGL debug message: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES'
[14:26:54] [Render thread/WARN]: Failed to get system info for Microarchitecture
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "this.cpuVendor" is null
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.queryMicroarchitecture(CentralProcessor.java:825) ~[oshi-core-6.4.5.jar:?]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.5.jar:?]
	at oshi.hardware.CentralProcessor$ProcessorIdentifier.getMicroarchitecture(CentralProcessor.java:816) ~[oshi-core-6.4.5.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37130(class_6396.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37146(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37128(class_6396.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37143(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37121(class_6396.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_560(class_128.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:230) ~[fabric-loader-0.15.11-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-07-18 14:26:54
Description: Initializing game

java.lang.RuntimeException: could not preload blit shader
	at net.minecraft.class_757.method_34521(class_757.java:467)
	at net.minecraft.class_310.<init>(class_310.java:677)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.minecraft.class_2973: Invalid shaders/core/blit_screen.json: Couldn't compile vertex program (vanilla, blit_screen) : 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
	at net.minecraft.class_2973.method_12856(class_2973.java:48)
	at net.minecraft.class_5944.<init>(class_5944.java:203)
	at net.minecraft.class_757.method_34521(class_757.java:465)
	... 5 more
Caused by: java.io.IOException: Couldn't compile vertex program (vanilla, blit_screen) : 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
	at net.minecraft.class_281.method_34416(class_281.java:69)
	at net.minecraft.class_281.method_1283(class_281.java:51)
	at net.minecraft.class_5944.method_34579(class_5944.java:242)
	at net.minecraft.class_5944.<init>(class_5944.java:185)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_757.method_34521(class_757.java:467)
	at net.minecraft.class_310.<init>(class_310.java:677)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (aarch64) version Android-13
	Java Version: 17.0.12-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2508840160 bytes (2392 MiB) / 2852126720 bytes (2720 MiB) up to 2852126720 bytes (2720 MiB)
	CPUs: 8
	Processor Vendor: null
	Processor Name: 
	Identifier: 0x41 Family 8 Model 0xd0b Stepping r2p0
	Microarchitecture: ERR
	Frequency (GHz): -0.00
	Number of physical packages: 2
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 9478.70
	Virtual memory used (MB): 8042.46
	Swap memory total (MB): 5632.00
	Swap memory used (MB): 2430.03
	JVM Flags: 3 total; -Xms2720M -Xmx2720M -Xbootclasspath/a:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-shared-1.18-SNAPSHOT.jar:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/caciocavallo17/cacio-tta-1.18-SNAPSHOT.jar
	Launched Version: 1.20.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: zink Vulkan 1.1(Mali-G57 MC2 (ARM_PROPRIETARY)) GL version 3.1 Mesa 23.2.0-devel (git-957009978e), Mesa
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: vi
	CPU: 8x 
#@!@# Game crashed! Crash report saved to: #@!@# /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/crash-reports/crash-2024-07-18_14.26.54-client.txt

### Steps To Reproduce

```markdown
1. start pojavlauncher 
2. Set renderder to Zink
3. Open any version of minecraft
```

### Expected Behavior

Open the game normally 

### Platform

```markdown
- Device model: realme 10|RMX3630
- CPU architecture: Helio G99 Ocar-core
- Android version: 13
- PojavLauncher version: every version
```

### Anything else?

.

**Comment by GaucovyAero** [comment]
```
WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G57 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance
```

you gotta get a better phone for it to run

**Comment by rgDK039** [comment]
> ```
> WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G57 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance
> ```
> 
> you gotta get a better phone for it to run

No, i was be able to run the game normally before with renderder Zink on

**Comment by ghost** [comment]
You using another renderers like holy gl4es and angle renderer before using zink. GaucovyAero is talk about zink renderer not holy gl4es or angle

**Comment by rgDK039** [comment]
> You using another renderers like holy gl4es and angle renderer before using zink. GaucovyAero is talk about zink renderer not holy gl4es or angle

Yeah no shit, i was be able to use zink b4, i just can't use its now

**Comment by ArisT137** [comment]
> > ```
> > WARNING: Some incorrect rendering might occur because the selected Vulkan device (Mali-G57 MC2) doesn't support base Zink requirements: feats.features.logicOp feats.features.fillModeNonSolid feats.features.shaderClipDistance
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you gotta get a better phone for it to run
> 
> No, i was be able to run the game normally before with renderder Zink on

I too, Did you manage to do anything about it?
