### ISSUE TITLE
java.lang.RuntimeException: Bad Request 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 	at java.lang.Thread.run(Thread.java:929)[BUG] <Short description>

### ISSUE THREAD

**Issue by Ernestop19** [PojavLauncherTeam/PojavLauncher#5820]
### Describe the bug

java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

### The log file and images/videos

java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

### Steps To Reproduce

```markdown
java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

### Expected Behavior

java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by GaucovyAero** [comment]
try logging into minecraft.net first, then into pojav
