### ISSUE TITLE
[BUG] <Short description>java.io.IOException: Unable to read Version JSON for version Alpha 0.0.0 	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:203) 	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90) 	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63) 	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 	at java.lang.Thread.run(Thread.java:1012)

### ISSUE THREAD

**Issue by AnnesSeven31** [PojavLauncherTeam/PojavLauncher#5834]
### Describe the bug

java.io.IOException: Unable to read Version JSON for version Alpha 0.0.0
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:203)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Bu hatayı veriyor

### The log file and images/videos

java.io.IOException: Unable to read Version JSON for version Alpha 0.0.0
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:203)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Bu oluyor

### Steps To Reproduce

```markdown
java.io.IOException: Unable to read Version JSON for version Alpha 0.0.0
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:203)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Bu oluyor
```

### Expected Behavior

Ben tablet oynuyorum

### Platform

```markdown
- Device model: Alpha 0.0.0
- CPU architecture:Alpha 0.0.0
- Android version:Alpha 0.0.0 
- PojavLauncher version:Alpha 0.0.0
```

**Comment by GaucovyAero** [comment]
[a0.0.0.zip](https://github.com/user-attachments/files/16426080/a0.0.0.zip)

1. extract this zip into your downloads and you will get a json
2. create a folder in .minecraft/versions called a0.0.0
3. put the extracted json file into that directory
4. put your alpha 0.0.0 jar into that directory and rename it to a0.0.0.jar
5. if there are any other files in the version folder that doesnt work, copy then over into the a0.0.0 folder
6. try launching version a0.0.0

**Comment by GaucovyAero** [comment]
maybe if sounds or skins dont work and you want them (if that even works on a0.0.0), you can try the betacraft proxy
put `-Dhttp.proxyHost=betacraft.uk -Djava.util.Arrays.useLegacyMergeSort=true` into your JVM arguments
