### ISSUE TITLE
[F-Req] <Short description>

### ISSUE THREAD

**Issue by Polar8750** [PojavLauncherTeam/PojavLauncher#5877]
### Is this request related to a bug?

It's not going 

### Describe the request.

It's not going 

### Anything else?

Shows this java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:301)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:86)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

**Comment by Polar8750** [comment]
Está bugado

**Comment by GaucovyAero** [comment]
try logging into minecraft.net first, then set up your username, then try logging into pojav
