### ISSUE TITLE
[BUG] <Short description>java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"} 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 	at java.lang.Thread.run(Thread.java:1012)

### ISSUE THREAD

**Issue by zobovalena** [PojavLauncherTeam/PojavLauncher#5878]
### Describe the bug

I tried to make a folder 3 times, but I got an error!!!

### The log file and images/videos

It returned an ERROR 3 times!!!

### Steps To Reproduce

```markdown
1. Зарегалась2. Выдолу ошибку
```

### Expected Behavior

proximity

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version:
```

### Anything else?

I want to register

**Comment by zobovalena** [comment]
horror

**Comment by zobovalena** [comment]
Ужас

**Comment by zobovalena** [comment]
horror

**Comment by GaucovyAero** [comment]
you gotta buy minecraft, thus creating a microsoft account and set up your username, all only on minecraft.net

**Comment by PROROT** [comment]
i cant make new acc ow to fix
