### ISSUE TITLE
[BUG] PowerVR GPU crashes on Zink Renderer

### ISSUE THREAD

**Issue by HenriquePlays544** [PojavLauncherTeam/PojavLauncher#5884]
### Describe the bug

When I launch the game with the Zink Renderer it's definitely crash and I tried everything (clean cache, uninstall and install again, tutorials, etc. Plz fix this bug (or error) because I want to run shaders.

### The log file and images/videos

[latestlog.txt](https://github.com/user-attachments/files/16427946/latestlog.txt)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
--------- beginning with launcher debug
Info: Launcher version: foxglove-20240727-ae48e8e-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-T225
Info: API version: 34
Info: Selected Minecraft version: 1.20.1-OptiFine_HD_U_I6
Info: Custom Java arguments: "-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Ddiscordfix=net.minecraft.client.main.Main"
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=670
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~YoTkIEJr___4GlDhGsNw9w==/net.kdt.pojavlaunch-SXtjTNPns7OhnOACLrbbCA==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~YoTkIEJr___4GlDhGsNw9w==/net.kdt.pojavlaunch-SXtjTNPns7OhnOACLrbbCA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=400
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
2024-07-30 09:21:42,464 main ERROR appender Console has no parameter that matches element Policies
[09:21:43] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[09:21:44] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[09:21:44] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
[09:21:44] [main/INFO]: [OptiFine] OptiFineTweaker: acceptOptions
[09:21:44] [main/INFO]: [OptiFine] OptiFineTweaker: injectIntoClassLoader
[09:21:44] [main/INFO]: [OptiFine] OptiFine ClassTransformer
[09:21:44] [main/INFO]: [OptiFine] OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/optifine/OptiFine/1.20.1_HD_U_I6/OptiFine-1.20.1_HD_U_I6.jar
[09:21:44] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchArguments
[09:21:44] [main/INFO]: [OptiFine] OptiFineTweaker: getLaunchTarget
[09:21:46] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2024-07-30 09:21:46,221 main ERROR appender Console has no parameter that matches element Policies
[09:21:49] [main/WARN]: File not found or not readable: /proc/stat
[09:21:52] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.eventbus.api.Event$Result
[09:21:52] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeEntity.canUpdate
[09:21:52] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.logging.CrashReportExtender
[09:21:57] [main/INFO]: [OptiFine] (Reflector) Method not present: ane.create
[09:22:17] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 1720 milliseconds
[09:22:28] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.ForgeHooksClient
[09:22:28] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[09:22:30] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[09:22:33] [Render thread/INFO]: Setting user: HenriquePlays0
Registered forkAndExec
[09:22:33] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.settings.KeyConflictContext
[09:22:33] [Render thread/INFO]: [OptiFine] (Reflector) Method not present: enl.getKeyModifier
[09:22:34] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[09:22:34] [Render thread/ERROR]: Error parsing option value  for option Text Background Opacity: Not a boolean: ""
[09:22:34] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.forge.snapshots.ForgeSnapshotsMod
[09:22:34] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.versions.forge.ForgeVersion
[09:22:34] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
OSMDroid: loading vulkan regularly...
OSMDroid: loaded vulkan, ptr=0xe100fdf2c346bc41
[09:22:34] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.internal.BrandingControl
[09:22:34] [Render thread/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.loading.ImmediateWindowHandler
```

### Expected Behavior

I think it's gonna to work correctly and I can run my shaders but it definitely crashes...

### Platform

```markdown
- Device model: Samsung Galaxy Tab A7 Lite
- CPU architecture: PowerVR GE8320
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk (PlayStore Version)
```

**Comment by GaucovyAero** [comment]
not a pojav issue, zink just doesnt support powervr gpus (we dont develop zink)

**Comment by HenriquePlays544** [comment]
> not a pojav issue, zink just doesnt support powervr gpus (we dont develop zink)
Who develop zink renderer?

**Comment by HenriquePlays544** [comment]
> not a pojav issue, zink just doesnt support powervr gpus (we dont develop zink)

Who develop zink?

**Comment by CowSheep72** [comment]
> > not a pojav issue, zink just doesnt support powervr gpus (we dont develop zink)
> 
> Who develop zink?

mesa

**Comment by HenriquePlays544** [comment]
Thanks CowSheep72!
