### ISSUE TITLE
Pojav launcher crashes when starting forge 1.20.1 

### ISSUE THREAD

**Issue by pixel848** [PojavLauncherTeam/PojavLauncher#5902]
### Describe the bug

at startup pojav launcher forge 1.20.1 is crashing 

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240727-ae48e8e-v3_openjdk
Info: Architecture: arm64
Info: Device model: INFINIX Infinix X6528B
Info: API version: 33
Info: Selected Minecraft version: 1.20.1-forge-47.2.23
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1532
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~IGenHlF9P3RgXjFiDre5kQ==/net.kdt.pojavlaunch-EN23u-F2WbrZGLxAMjR7xw==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~IGenHlF9P3RgXjFiDre5kQ==/net.kdt.pojavlaunch-EN23u-F2WbrZGLxAMjR7xw==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=720
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 64), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  ( 8318): dlopen libgl4es_114.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success

I/jrelog  ( 8318): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavla
unch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  ( 8318): dlop
en /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  ( 8318): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  ( 8318): dlopen /data/app/~~IGenHlF9P3RgXjFiDre5kQ==/net.kdt.pojavlaunch-EN23u-F2WbrZGLxAMjR7xw==/lib/arm64/libopenal.so success
I/jrelog  ( 8318): Done processing args
I/jrelog  ( 8318): Found JLI lib
I/jrelog  ( 8318): Calling JLI_Launch

2024-08-04 23:48:01,380 main ERROR appender Console has no parameter that matches element Policies
[23:48:01] [main/INFO]: ModLauncher running: args [--username, pixel_play578, --version, 1.20.1, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 5, --uuid, 00000000000000000000000000000000, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.23, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[23:48:01] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.12-internal by N/A; OS Linux arch aarch64 version Android-13
[23:48:02] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
Registered forkAndExec
[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[23:48:02] [main/INFO]: Trying GL version 4.6
EGLBridge: Binding to OpenGL ES
[23:48:02] [main/INFO]: Requested GL version 4.6 got version 0.0
[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
I/NativeInput( 8318): Input ready: 1

[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[23:48:03] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23114!/ Service=ModLauncher Env=CLIENT
[23:48:03] [pool-2-thread-1/INFO]: GL info: Mali-G57 GL version 2.1 gl4es wrapper 1.1.5, PojavLauncherTeam & ptitSeb
Thread[pool-2-thread-1,5,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[pool-2-thread-1,5,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
[23:48:03] [main/INFO]: Found mod file Forgematica-0.1.5-mc1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:48:03] [main/INFO]: Found mod file jei-1.20.1-forge-15.3.0.8.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:48:03] [main/INFO]: Found mod file tl_skin_cape_forge_1.20_1.20.1-1.32.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:48:03] [main/INFO]: Found mod file Xaeros_Minimap_24.1.0_Forge_1.20.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:48:04] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/fmlcore/1.20.1-47.2.23/fmlcore-1.20.1-47.2.23.jar is missing mods.toml file
[23:48:04] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.2.23/javafmllanguage-1.20.1-47.2.23.jar is missing mods.toml file
[23:48:04] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.2.23/lowcodelanguage-1.20.1-47.2.23.jar is missing mods.toml file
[23:48:04] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/mclanguage/1.20.1-47.2.23/mclanguage-1.20.1-47.2.23.jar is missing mods.toml file
[23:48:04] [main/INFO]: Found mod file fmlcore-1.20.1-47.2.23.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55b8dbda
[23:48:04] [main/INFO]: Found mod file javafmllanguage-1.20.1-47.2.23.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55b8dbda
[23:48:04] [main/INFO]: Found mod file lowcodelanguage-1.20.1-47.2.23.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55b8dbda
[23:48:04] [main/INFO]: Found mod file mclanguage-1.20.1-47.2.23.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55b8dbda
[23:48:04] [main/INFO]: Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55b8dbda
[23:48:04] [main/INFO]: Found mod file forge-1.20.1-47.2.23-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@55b8dbda
[23:48:04] [main/INFO]: No dependencies to load found. Skipping!
[23:48:04] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'mafglib', Requested by: 'forgematica', Expected range: '*', Actual version: '[MISSING]'
[23:48:08] [main/INFO]: Compatibility level set to JAVA_17
[23:48:08] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[23:48:08] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --uuid, 00000000000000000000000000000000, --username, pixel_play578, --assetIndex, 5, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, msa, --versionType, release]
[23:48:09] [main/WARN]: Error loading class: fi/dy/masa/malilib/config/options/ConfigBoolean (java.lang.ClassNotFoundException: fi.dy.masa.malilib.config.options.ConfigBoolean)
Exception in thread "main" java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3427)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3433)
	at java.base/java.lang.Class.getMethods(Class.java:2019)
	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.2.23/net.minecraftforge.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:599)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.23/net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.23/net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.23/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 7 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: fi.dy.masa.malilib.config.options.ConfigBoolean
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 30 more
Java Exit code: 1
I/jrelog  ( 8318): Going to free args
I/jrelog  ( 8318): Free done

### Steps To Reproduce

```markdown
1. to run pojav launcher 
2. error output 1
3. Exit
```

### Expected Behavior

I expect the game to start without any problems 

### Platform

```markdown
- Device model: infinix HOT 40i
- CPU architecture: 
- Android version: 13
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
install malilib i think

**Comment by pixel848** [comment]
forge 1.20.1 crashes, not fabric
