### ISSUE TITLE
[BUG] I can't sign in into my Microsoft account 

### ISSUE THREAD

**Issue by Liam461** [PojavLauncherTeam/PojavLauncher#5919]
### Describe the bug

Basically I tried to sign in into my account in Microsoft but there's a bug that doesn't let me sign in 

### The log file and images/videos

java.lang.RuntimeException: Not Found
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.checkMcProfile(MicrosoftBackgroundLogin.java:301)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:86)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

### Steps To Reproduce

```markdown
1 I started pojavlauncher 
2 I tried to sign in on my Microsoft account 
3 I tried to sign in but there's an error
```

### Expected Behavior

I expected to get signed in

### Platform

```markdown
- Device model: Tecno spark 6 go ke7
- CPU architecture:don't know 
- Android version: 10
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

U can't sign in into ur Microsoft account

**Comment by GaucovyAero** [comment]
not a bug, buy minecraft and try logging into minecraft.net

**Comment by Liam461** [comment]
Doesn't work
