### ISSUE TITLE
[BUG] <Short description>

### ISSUE THREAD

**Issue by zaquwan123** [PojavLauncherTeam/PojavLauncher#5925]
### Describe the bug

java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### The log file and images/videos

java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Steps To Reproduce

```markdown
java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

### Expected Behavior

java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

### Anything else?

java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by zaquwan123** [comment]
Why

**Comment by GaucovyAero** [comment]
log into minecraft.net and if you have not bought minecraft: java edition, be sure to buy it
also be sure that your microsoft minecraft account is 18+ or older
