### ISSUE TITLE
[BUG] <crash>

### ISSUE THREAD

**Issue by amiktampan** [PojavLauncherTeam/PojavLauncher#5960]
### Describe the bug

fabric 1.21.1 is crashing pls help

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240727-ae48e8e-v3_openjdk
Info: Architecture: arm64
Info: Device model: vivo V2207
Info: API version: 33
Info: Selected Minecraft version: fabric-loader-0.16.2-1.21.1
Info: Custom Java arguments: "X * m * 4096M - Xms * 4096M"
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=1568
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_BIG_CORE_AFFINITY=1
Added custom env: POJAV_NATIVEDIR=/data/app/~~d1zOz6dalR2v_GkjmlASsg==/net.kdt.pojavlaunch-xyVUSKLsO5c7V0lTMF7Vrw==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~d1zOz6dalR2v_GkjmlASsg==/net.kdt.pojavlaunch-xyVUSKLsO5c7V0lTMF7Vrw==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=720
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16383
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 4 / Draw buffers: 4
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Failed to inject cache!
java.lang.ClassNotFoundException: java.net.InetAddress$CacheEntry
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at git.artdeell.arcdns.CacheUtil_J8.getConstructorOfInetAddress$CacheEntry(CacheUtil_J8.java:45)
	at git.artdeell.arcdns.CacheUtil_J8.newCacheEntry(CacheUtil_J8.java:32)
	at git.artdeell.arcdns.CacheUtil_J8.setInetAddressCache(CacheUtil_J8.java:20)
	at git.artdeell.arcdns.ArcDNSInjectorAgent.premain(ArcDNSInjectorAgent.java:12)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:562)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:572)
	Suppressed: java.lang.ClassNotFoundException: java.net.InetAddress$CachedAddresses
		at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
		at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:421)
		at java.base/java.lang.Class.forName(Class.java:412)
		at git.artdeell.arcdns.CacheUtil_J9.getConstructorOfInetAddress$CachedAddresses(CacheUtil_J9.java:42)
		at git.artdeell.arcdns.CacheUtil_J9.newCachedAddresses(CacheUtil_J9.java:30)
		at git.artdeell.arcdns.CacheUtil_J9.setInetAddressCache(CacheUtil_J9.java:20)
		at git.artdeell.arcdns.ArcDNSInjectorAgent.premain(ArcDNSInjectorAgent.java:9)
		... 4 more
logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

logcat: Unexpected EOF!

This means that either the device shut down, logd crashed, or this instance of logcat was unable to read log
messages as quickly as they were being produced.

If you have enabled significant logging, look into using the -G option to increase log buffer sizes.

ERROR: Unable to get more log.
ERROR StatusConsoleListener appender Console has no parameter that matches element Policies
[22:52:51] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.2
[22:52:51] [ForkJoinPool-1-worker-2/WARN]: Mod stutterfix uses the version mc1.21-0.2.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:52:51] [main/WARN]: Mod resolution failed
[22:52:51] [main/INFO]: Immediate reason: [HARD_DEP continuity 3.0.0-beta.5+1.21 {depends fabric-api @ [>=0.100.1]}, HARD_DEP_INCOMPATIBLE_PRESELECTED fabric-api 0.100.1+1.21 {depends minecraft @ [>=1.21- <1.21.1-]}, ROOT_FORCELOAD_SINGLE continuity 3.0.0-beta.5+1.21]
[22:52:51] [main/INFO]: Reason: [HARD_DEP fabric-api 0.100.1+1.21 {depends minecraft @ [>=1.21- <1.21.1-]}, HARD_DEP entityculling 1.6.6 {depends minecraft @ [1.21]}, HARD_DEP immediatelyfast 1.2.18+1.21 {depends minecraft @ [1.21]}, HARD_DEP lithium 0.12.5 {depends minecraft @ [1.21]}, HARD_DEP packetfixer 1.4.1 {depends minecraft @ [>=1.21 <=1.21]}, HARD_DEP skinlayers3d 1.6.6 {depends minecraft @ [1.21]}]
[22:52:51] [main/INFO]: Fix: add [], remove [], replace [[minecraft 1.21.1] -> add:minecraft 1.21 ([[1.21,1.21]])]
[22:52:51] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with version 1.21.
More details:
	 - Mod 'Fabric API' (fabric-api) 0.100.1+1.21 requires any version between 1.21- (inclusive) and 1.21.1- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'EntityCulling' (entityculling) 1.6.6 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'ImmediatelyFast' (immediatelyfast) 1.2.18+1.21 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Lithium' (lithium) 0.12.5 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'Packet Fixer' (packetfixer) 1.4.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod '3d-Skin-Layers' (skinlayers3d) 1.6.6 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
[22:52:52] [main/WARN]: Failed to open the error gui!
java.lang.reflect.InvocationTargetException: null
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1371) ~[?:?]
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1346) ~[?:?]
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open0(FabricMainWindow.java:94) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.open(FabricMainWindow.java:88) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.open(FabricGuiEntry.java:51) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:141) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:108) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:86) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
Caused by: java.awt.HeadlessException
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:58) ~[?:?]
	at java.desktop/java.awt.Window.initGC(Window.java:493) ~[?:?]
	at java.desktop/java.awt.Window.init(Window.java:512) ~[?:?]
	at java.desktop/java.awt.Window.<init>(Window.java:554) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Frame.java:428) ~[?:?]
	at java.desktop/java.awt.Frame.<init>(Frame.java:393) ~[?:?]
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180) ~[?:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.createUi(FabricMainWindow.java:104) ~[fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.gui.FabricMainWindow.lambda$open0$0(FabricMainWindow.java:95) ~[fabric-loader-0.16.2.jar:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]

### Steps To Reproduce

```markdown
start pojav and crash kode 1
```

### Expected Behavior

i expect too play 1.21.1 

### Platform

```markdown
- Device model: vivo y22
- CPU architecture: 	Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)
- Android version: 13
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

please help me

**Comment by GaucovyAero** [comment]
1.21 mods wont work on 1.21.1
also, remove your jvm arguments cause they dont do anything as its improper syntax and also -Xms and -Xmx arguments are blocked by pojav, cause you should use the slider instead
