### ISSUE TITLE
[BUG] Babric Do not work

### ISSUE THREAD

**Issue by sharusu** [PojavLauncherTeam/PojavLauncher#5964]
### Describe the bug

when installing Babric all versions the game does not start. just a black screen 

### The log file and images/videos

java.lang.NumberFormatException: For input string: "*"
	at java.lang.Integer.parseInt(Integer.java:776)
	at java.lang.Integer.parseInt(Integer.java:908)
	at net.kdt.pojavlaunch.Tools.preProcessLibraries(Tools.java:721)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.scheduleLibraryDownloads(MinecraftDownloader.java:243)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:217)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Start Babric Installer
3. Start Game
```

### Expected Behavior

The game was supposed to start with Babric

### Platform

```markdown
- Device model: Samsung Galaxy S20FE
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: foxglove
```

**Comment by GaucovyAero** [comment]
you gotta do a bit of json patching

https://github.com/user-attachments/assets/6feb6cde-7e68-41cb-8c4f-5eecfdf4511d

**Comment by sharusu** [comment]
Thanks! :D

**Comment by sharusu** [comment]
I got another error
[latestlog.txt](https://github.com/user-attachments/files/16710118/latestlog.txt)

**Comment by GaucovyAero** [comment]
not sure tbh, try redoing the install shown in the video from scratch, do you have any mods installed?

**Comment by sharusu** [comment]
> not sure tbh, try redoing the install shown in the video from scratch, do you have any mods installed?

replacing the .jar file b1.7.3-custom everything worked for me!

**Comment by Sunflames0** [comment]
Any tutorial for new Babric?

**Comment by Sunflames0** [comment]
0.16.10
