### ISSUE TITLE
How can i fix this error

### ISSUE THREAD

**Issue by ZianDaTester** [PojavLauncherTeam/PojavLauncher#598]
java.io.FileNotFoundException: /data/data/net.kdt.pojavlaunch/jre_runtime/release: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at java.io.FileReader.<init>(FileReader.java:66)
	at net.kdt.pojavlaunch.utils.JREUtils.readJREReleaseProperties(JREUtils.java:72)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:832)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2300(BaseMainActivity.java:23)
	at net.kdt.pojavlaunch.BaseMainActivity$10$1.run(BaseMainActivity.java:683)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)
	... 8 more

**Comment by artdeell** [comment]
redownload runtime and clear the app data

**Comment by khanhduytran0** [comment]
- Is your device 32bit/aarch32?
- Don't use 3rd party runtime.
- Please give info about which java runtime you are using.

**Comment by ZianDaTester** [comment]
Yes

**Comment by ZianDaTester** [comment]
Ok give me a sec

**Comment by ZianDaTester** [comment]
aarch32-20200928.tar.xz this one

**Comment by artdeell** [comment]
why r u using an mcinabox runtime

**Comment by ZianDaTester** [comment]
Bc i cant find the pojav runtime

**Comment by ZianDaTester** [comment]
On github

**Comment by artdeell** [comment]
https://drive.google.com/file/d/103EheBh7Vvss7pYKD2m9CG5yRuBOGtJB/view?usp=drivesd

**Comment by ZianDaTester** [comment]
Ty
