### ISSUE TITLE
failed to install optifine on minecraft 1.11.2 via inbuilt installer

### ISSUE THREAD

**Issue by rhjdvsgsgks** [PojavLauncherTeam/PojavLauncher#60]
i has already created 'launcher_profiles.json' by content in #22 to avoid "file not found" error

version of launcher which i was using is 2.4.2_preview10_6390b_20200403

here is the log
```
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1037)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:32)
	... 9 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at optifine.ReflectCall.invokeMethodStatic(ReflectCall.java:31)
	at optifine.AndroidInstaller.invokeStatic(AndroidInstaller.java:37)
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:30)
	... 9 more
Caused by: Unexpected character ( ) at position 2.
	at optifine.json.Yylex.yylex(Yylex.java:610)
	at optifine.json.JSONParser.nextToken(JSONParser.java:269)
	at optifine.json.JSONParser.parse(JSONParser.java:118)
	at optifine.json.JSONParser.parse(JSONParser.java:81)
	at optifine.json.JSONParser.parse(JSONParser.java:75)
	at optifine.Installer.updateLauncherJson(Installer.java:154)
	... 13 more
```

**Comment by khanhduytran0** [comment]
> `Unexpected character ( ) at position 2.`

Meaning the json file has something wrong. Try to download the raw file https://github.com/khanhduytran0/PojavLauncher/blob/master/launcher_profiles.json
Don't copy, download the file then replace old error file.

**Comment by rhjdvsgsgks** [comment]
sorry , i haven't notice that file before . now the optifine successfuly installed , but crash at launching (the mojang logo) ,here is the log
```
java.lang.NullPointerException: Attempt to invoke virtual method 'cbh cbk.bakeModel(bri, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at cbk.a(ModelBakery.java:725)
	at cbl.a(SourceFile:23)
	at cae.a(SourceFile:100)
	at bes.an(SourceFile:519)
	at bes.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:764)
```

I'm using Android 9 on a arm64 device

**Comment by khanhduytran0** [comment]
What version are you Launching?

**Comment by rhjdvsgsgks** [comment]
Minecraft 1.11.2 with OptiFine_HD_U_F5

**Comment by khanhduytran0** [comment]
Try Minecraft 1.11 with OptiFine HD_U_F5

**Comment by rhjdvsgsgks** [comment]
still crashed
```
java.lang.NullPointerException: Attempt to invoke virtual method 'cbe cbh.bakeModel(brg, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)
	at beq.an(SourceFile:516)
	at beq.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:823)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by artdeell** [comment]
Try OptiFine HD U H5, that worked for me.

**Comment by rhjdvsgsgks** [comment]
1.11/1.11.2 has no optifine which version is your said supposed yet

**Comment by khanhduytran0** [comment]
OptiFine crashes happend at method `bakeModel` and by `NullPointerException`. Something wrong cause the field can't be initialized before `bakeModel` method call.

**Comment by khanhduytran0** [comment]
@rhjdvsgsgks can you give me the OptiFine library file at `/sdcard/games/minecraft/libraries/optifine` by archive them and attach here.

@artdeell My device seems to be not supported by OptiFine 1.8.8 installer and above, when almost complete the convert stage, dialog dismiss with some error on logcat then app not respond. So that's why I need the OptiFine libraries.

**Comment by rhjdvsgsgks** [comment]
[OptiFine library files](https://send.firefox.com/download/7195e987b5a4fae1/#EpVYdNrsnqCh2Ey_uG7WRg)

**Comment by khanhduytran0** [comment]
Thank you, I will do some decompiles to attempt fix.

**Comment by khanhduytran0** [comment]
What is your device (Huawei?)

**Comment by rhjdvsgsgks** [comment]
no , I'm using a simple phone with snapdragon 835 and android(aosp-like) 9 arm64

**Comment by khanhduytran0** [comment]
a simple phone?

**Comment by rhjdvsgsgks** [comment]
I'm sorry for using this vague statement , but if i publish my phone model to the public place (like github) ,  someone will cross-validation this account with my other social media , that will leak my private information (like phone number, address and ssn) , in Chinese this action called "出道" . although hidden phone model may not have any help on protecting myself , i will still try to protect it

**Comment by rhjdvsgsgks** [comment]
in [this version](https://github.com/khanhduytran0/PojavLauncher/issues/59#issuecomment-612366940) 1.11.2 with OptiFine_HD_U_F5 working successfully on my device . but 1.12.2 still not work (with the same error) , i has already try to delete the dex file compiled before

**Comment by khanhduytran0** [comment]
Can you copy that error (1.12.2)?

**Comment by khanhduytran0** [comment]
> someone will cross-validation this account with my other social media , that will leak my personal information (like phone number, address and ssn)

You think same phone model with you can log in to your account without password?

**Comment by rhjdvsgsgks** [comment]
> Can you copy that error (1.12.2)?

```
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:939)
	at net.kdt.pojavlaunch.MainActivity.access$2700(MainActivity.java:40)
	at net.kdt.pojavlaunch.MainActivity$11$1.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
	at bib.<init>(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	... 5 more
Caused by: java.lang.ClassCastException: Bootstrap method returned null
	... 7 more
```

**Comment by rhjdvsgsgks** [comment]
> You think same phone model with you can log in to your account without password?

no . in China , cause of the law any account must bind a phone number , and phone number must registered with real name . so if i have your phone number , i can get almost all your private information (like address in real world , real name , Identity in any other social media) . because this "feature" , if someone know which account is i owned on social media in China , they will know my private information .  i had also put some activity on github to a chinese technology forum ,  at that forum phone model is public , and my phone model is slightly unpopular ,  if i publish my phone model here , someone can easily know my private information by cross-validation

**Comment by khanhduytran0** [comment]
Ok.

**Comment by rhjdvsgsgks** [comment]
minecraft 1.11.2 with OptiFine_HD_U_F5 still work even if i update the launcher to 2.4.2_preview11b3 , may I close this issue?

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine#since-optifine-mc-19-a-file-called-launchwrapper-of-21jar-cause-error-unable-to-launch-simply-fix-by-follow-the-video-or-do-actions-as-below

**Comment by khanhduytran0** [comment]
Work or not?

**Comment by rhjdvsgsgks** [comment]
working successfully

**Comment by khanhduytran0** [comment]
You should close because there are many duplicate.

**Comment by rhjdvsgsgks** [comment]
after update to 2.5.1 , Minecraft 1.11.2 with OptiFine_1.11.2_HD_U_F5 crashes at the mojang logo again
```
java.lang.NullPointerException: Attempt to invoke virtual method 'cbh cbk.bakeModel(bri, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at cbk.a(ModelBakery.java:725)
	at cbl.a(SourceFile:23)
	at cae.a(SourceFile:100)
	at bes.an(SourceFile:519)
	at bes.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:943)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000016$100000015.run(MainActivity.java:651)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by khanhduytran0** [comment]
I said that it's internal problem and can't be fixed.

**Comment by khanhduytran0** [comment]
so 2.5.0 works or not?

**Comment by rhjdvsgsgks** [comment]
not work

**Comment by rhjdvsgsgks** [comment]
and i found that the launchwrapper-of-2.1.jar file hasn't be compiled to dex file ( oat folder not exist under  minecraft/libraries/optifine/launchwrapper-of/2.1 ) , does the normal behavior should be something like this?

**Comment by khanhduytran0** [comment]
I not sure, PojavLauncher use LaunchWrapper from Mojang GitHub public repo.

**Comment by rhjdvsgsgks** [comment]
i noticed that every jar file have a oat folder in the same directory and dex file compiled by dx is in it ,  but launchwrapper-of-2.1.jar not ,  it seems like this jar doesn't compiled by dx , is this related to the crash?

**Comment by khanhduytran0** [comment]
No, look at crash stacktrace, it does not have crash head at `net.minecraft.launchwrapper`. However, it trace two launchwrapper places, at start, but no problem.

**Comment by khanhduytran0** [comment]
You may try rename launchwrapper to _orig.jar and try, but may not have effect since Android VM does not allow overwrite class definition.

**Comment by rhjdvsgsgks** [comment]
you are right , it's no matter with launchwrapper-of-2.1.jar file , after rename it  , the dex file appeared , and the game still crash at the same position
