### ISSUE TITLE
Bad requeat

### ISSUE THREAD

**Issue by GoofyRaspberry** [PojavLauncherTeam/PojavLauncher#6000]
### Describe the bug

Can't log in bto Microsoft because of a bad request.

### The log file and images/videos

java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### Steps To Reproduce

```markdown
I'm not sure how, I just logged into my Microsoft account with the correct email and password.
```

### Expected Behavior

I expect to login normally

### Platform

```markdown
- Device model: Samsung Galaxy S21 Ultra
- CPU architecture: ARMv8
- Android version: 13
- PojavLauncher version: latest from playstore
```

**Comment by GoofyRaspberry** [comment]
I restarted my phone and it automatically logged in
