### ISSUE TITLE
[BUG] Cannot Play Minecraft Version

### ISSUE THREAD

**Issue by Dilen0001** [PojavLauncherTeam/PojavLauncher#6006]
### Describe the bug

Minecraft 1.19 Experimental Snapshot Won't Run

### The log file and images/videos

![Screenshot_20240830_193242](https://github.com/user-attachments/assets/959114d3-d987-4264-bef3-036ce0fdda4b)

### Steps To Reproduce

```markdown
Install Minecraft Version Experimental Snapshot 1.19
```

### Platform

```markdown
- Device model: Vivo V23e
- CPU architecture: arm64
- Android version: 13
- PojavLauncher version: Foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

Please Fix Bug

**Comment by artdeell** [comment]
you have not installed it correctly

**Comment by Dilen0001** [comment]
I Have Installed It Correctly

**Comment by GaucovyAero** [comment]
you have not installed the json

**Comment by kasrarouhi** [comment]
Be sure you turned on  check library after download
.
![Screenshot_2024-08-31-14-34-17-464_net kdt pojavlaunch](https://github.com/user-attachments/assets/a4f4f780-3cba-46ee-b6d5-dd8dda104ab2)

**Comment by Dilen0001** [comment]
I've activated it but it still doesn't work

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.19_deep_dark_experimental_snapshot-1/1.19_deep_dark_experimental_snapshot-1.json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:844)
	at net.kdt.pojavlaunch.utils.DateUtils.getOriginalReleaseDate(DateUtils.java:54)
	at net.kdt.pojavlaunch.Tools.getMinecraftClientArgs(Tools.java:360)
	at net.kdt.pojavlaunch.Tools.launchMinecraft(Tools.java:205)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:355)
	at net.kdt.pojavlaunch.MainActivity.lambda$initLayout$4$net-kdt-pojavlaunch-MainActivity(MainActivity.java:210)
	at net.kdt.pojavlaunch.MainActivity$$ExternalSyntheticLambda14.isReady(Unknown Source:6)
	at net.kdt.pojavlaunch.MinecraftGLSurface.lambda$realStart$0$net-kdt-pojavlaunch-MinecraftGLSurface(MinecraftGLSurface.java:375)
	at net.kdt.pojavlaunch.MinecraftGLSurface$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/versions/1.19_deep_dark_experimental_snapshot-1/1.19_deep_dark_experimental_snapshot-1.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:872)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:754)
	... 9 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8352)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 13 more

**Comment by GaucovyAero** [comment]
it tries to find a 1.19 file but finds 1_19, please check your file names more carefully, closing
