### ISSUE TITLE
[BUG] <Short description> pojav fabric bug

### ISSUE THREAD

**Issue by asumy1** [PojavLauncherTeam/PojavLauncher#6014]
### Describe the bug

2024-09-01 17:29:05,628 main ERROR appender Console has no parameter that matches element Policies
[17:29:05] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.15.3
[17:29:05] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[17:29:06] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:197) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.3.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:147) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:147) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.3.jar:?]
	... 3 more
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar (Permission denied)
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
		at java
.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
		at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
		at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
		at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:144) ~[fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.3.jar:?]
	Caused by: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar (Permission denied)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:288) ~[fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.15.3.jar:?]
		at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThrea
d.run(ForkJoinWorkerThread.java:165) ~[?:?]
	Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar (Permission denied)
		at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
		at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
		at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
		at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
		at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480) ~[?:?]
		at java.util.zip.ZipFile$Source.get(ZipFile.java:1445) ~[?:?]
		at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717) ~[?:?]
		at java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
		at java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
		at java.util.zip.ZipFile.<init>(ZipFile.java:194) ~[?:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:309) ~[fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278) ~[fabric-loader-0.15.3.jar:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.15.3.jar:?]
		at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1
.18.2.jar (Permission denied)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:144) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:215) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.15.3.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar (Permission denied)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:288) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.15.3.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWor
ker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1445) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:194) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:309) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:278) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237) ~[fabric-loader-0.15.3.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### The log file and images/videos

idk how to screenshot

### Steps To Reproduce

```markdown
idk
```

### Expected Behavior

bah bah

### Platform

```markdown
- Device model: Samsung tab a9+
- CPU architecture:idk 
- Android version:15
- PojavLauncher version:new update
```

### Anything else?

how to fix it

**Comment by asumy1** [comment]
ok how to fix @LabyStudio @itsnebulalol @Mathias-Boulay @Google61

**Comment by asumy1** [comment]
log file this

**Comment by asumy1** [comment]
[latest.log](https://github.com/user-attachments/files/16828879/latest.log)

**Comment by asumy1** [comment]
[latest login.txt](https://github.com/user-attachments/files/16828886/latest.login.txt)
I renamed it latest login.txt ok?

**Comment by itsnebulalol** [comment]
Please do not tag me in issues

**Comment by ghost** [comment]
Why are you tag laby studio. He/she is created labymod it's not related to pojav.

**Comment by CowSheep72** [comment]
> [latest login.txt](https://github.com/user-attachments/files/16828886/latest.login.txt) I renamed it latest login.txt ok?

renaming log files does not make it the right log file

**Comment by CowSheep72** [comment]
> ok how to fix @LabyStudio @itsnebulalol @Mathias-Boulay @Google61

smh

**Comment by whal-whales** [comment]
## why the hell did you do that.

**Comment by GaucovyAero** [comment]
dont cut your mods, copy your mods
