### ISSUE TITLE
[BUG] Zink renderer related crash

### ISSUE THREAD

**Issue by user5495439** [PojavLauncherTeam/PojavLauncher#6015]
### Describe the bug

Game crashes at startup when I try to use Zink as the renderer on any game or java runtime version. This crash doesn't happen on other renderers.

Also the game doesn't crash if I turn on the option 'Use system vulkan driver'. However using this option makes the game only display a single solid color, making it unplayable.

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240727-ae48e8e-v3_openjdk
Info: Architecture: arm64
Info: Device model: samsung SM-S926U1
Info: API version: 34
Info: Selected Minecraft version: 1.21.1
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=3016
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~u6QiKDEbfcXK-ZvhFHezuQ==/net.kdt.pojavlaunch-NG4LuUuzBAGWHDvO_3EmPQ==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~u6QiKDEbfcXK-ZvhFHezuQ==/net.kdt.pojavlaunch-NG4LuUuzBAGWHDvO_3EmPQ==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1440
--------- beginning of main
I/jrelog  ( 7148): dlopen libOSMesa.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  ( 7148): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success

I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success

I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjawt.so success

I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/librmi.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjavajpeg.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsctp.so success

I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libdt_socket.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjsig.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2gss.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_ext.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_agent.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmlib_image.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/run
times/Internal-21/lib/libmanagement.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjimage.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libinstrument.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libprefs.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjdwp.so success

I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjsig.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/liblcms.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2pkcs11.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libzip.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success

I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsyslookup.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjaas.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libextnet.so success
I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success

I/jrelog  ( 7148): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_xawt.so success
I/jrelog  ( 7148): dlopen /data/app/~~u6QiKDEbfcXK-ZvhFHezuQ==/net.kdt.pojavlaunch-NG4LuUuzBAGWHDvO_3EmPQ==/lib/arm64/libopenal.so success

I/jrelog  ( 7148): Done processing args
I/jrelog  ( 7148): Found JLI lib
I/jrelog  ( 7148): Calling JLI_Launch

java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
ERROR StatusConsoleListener appender Console has no parameter that matches element Policies
[16:41:06] [main/WARN]: Failed retrieving info for group processor
java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~u6QiKDEbfcXK-ZvhFHezuQ==/net.kdt.pojavlaunch-NG4LuUuzBAGWHDvO_3EmPQ==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.1.jar:?]
	at ac.a(SourceFile:87) ~[1.21.1.jar:?]
	at ac.a(SourceFile:79) ~[1.21.1.jar:?]
	at ac.e(SourceFile:56) ~[1.21.1.jar:?]
	at ac.a(SourceFile:87) [1.21.1.jar:?]
	at ac.<init>(SourceFile:56) [1.21.1.jar:?]
	at o.<init>(SourceFile:35) [1.21.1.jar:?]
	at o.g(SourceFile:234) [1.21.1.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.1.jar:?]
[16:41:07] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:28) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:38) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:60) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.a(SourceFile:81) ~[1.21.1.jar:?]
	at ac.a(SourceFile:87) ~[1.21.1.jar:?]
	at ac.a(SourceFile:81) ~[1.21.1.jar:?]
	at ac.e(SourceFile:56) ~[1.21.1.jar:?]
	at ac.a(SourceFile:87) [1.21.1.jar:?]
	at ac.<init>(SourceFile:56) [1.21.1.jar:?]
	at o.<init>(SourceFile:35) [1.21.1.jar:?]
	at o.g(SourceFile:234) [1.21.1.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:125) [1.21.1.jar:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~u6QiKDEbfcXK-ZvhFHezuQ==/net.kdt.pojavlaunch-NG4LuUuzBAGWHDvO_3EmPQ==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:5.14.0 (b0)]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:6.4.10]
	at ac.c(SourceFile:79) ~[1.21.1.jar:?]
	at ac.a(SourceFile:87) ~[1.21.1.jar:?]
	at ac.a(SourceFile:79) ~[1.21.1.jar:?]
	... 6 more
[16:41:07] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 201 milliseconds
[16:41:09] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[16:41:09] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[16:41:09] [Render thread/INFO]: Setting user: steve843736
Registered forkAndExec
[16:41:09] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[16:41:09] [Render thread/ERROR]: Error parsing option value 0.5d for option Text Background Opacity: Failed to parse either. First: Not a number: "0.5d"; Second: Not a boolean: "0.5d"
[16:41:09] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
AdrenoSupp: Loaded Turnip, loader address: 0x39a0c251f012ee29

### Steps To Reproduce

```markdown
1. Select Zink as the renderer on any game version
2. Hit play
3. Game displays a black screen then crashes
```

### Expected Behavior

Game loads up succesfully using the Zink renderer.

### Platform

```markdown
- Device model: samsung SM-S926U1 (Galaxy S24+ US Model Snapdragon 8 Gen 3 12/256G)
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

This crash doesn't happen on my other phone.

**Comment by rishabha102010** [comment]
Use this MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460 put this in custom_env.txt or crate the that name and paste it it solved for me

**Comment by user5495439** [comment]
> Use this MESA_GL_VERSION_OVERRIDE=4.6 MESA_GLSL_VERSION_OVERRIDE=460 put this in custom_env.txt or crate the that name and paste it it solved for me

I tried that, it doesn't change anything for me.

**Comment by rishabha102010** [comment]
> Use this MESA_GL_VERSION_OVERRIDE=4.6 MESA_GLSL_VERSION_OVERRIDE=460 put this in custom_env.txt or crate the that name and paste it it solved for me

Let me explain clearly make a text named:custom_env.txt create the text in the opening file.clearly after opening pojavlauncher files and open (files) and appears latestlog.txt in last so crate the custom_env.txt text down after latestlog.txt and paste
MESA_GL_VERSION_OVERRIDE=4.6
MESA_GLSL_VERSION_OVERRIDE=460
If you paste them in minecraft files it won't work I tested if still crashes then ask others

**Comment by GaucovyAero** [comment]
unsupported gpu by turnip as of now

**Comment by user5495439** [comment]
> unsupported gpu by turnip as of now

Do you know when y'all are planning on adding support for my GPU? I would really like to see how well shaders would work on my phone.
