### ISSUE TITLE
[BUG] Crash with fabulously optimized

### ISSUE THREAD

**Issue by Marcosayfi** [PojavLauncherTeam/PojavLauncher#6024]
### Describe the bug

when i go to world with the fabulously optimized modpack, it crashes.

### The log file and images/videos

in this case, i have to send crash log, because pojav crash thing told me to.
java.lang.NullPointerException: Attempt to read from field 'java.util.Map net.kdt.pojavlaunch.value.launcherprofiles.MinecraftLauncherProfiles.profiles' on a null object reference
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackInstaller.installModpack(ModpackInstaller.java:59)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModrinthApi.installMod(ModrinthApi.java:116)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.CommonApi.installMod(CommonApi.java:112)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackApi$-CC.$private$lambda$handleInstallation$0(ModpackApi.java:56)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModpackApi$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
:)

### Steps To Reproduce

```markdown
just get fabulously opti.ized. (install from pojav interface, modrinth version)
```

### Expected Behavior

the world to load and for me to get like 1000 fps.

### Platform

```markdown
- Device model: TECHNO KG8.
- CPU architecture: 64-bit.
- Android version: 11.
- PojavLauncher version: foxglove-20240727-ae48e8e-v3_openjdk
```

### Anything else?

no.

**Comment by ghost** [comment]
Again

**Comment by GaucovyAero** [comment]
show video and send latestlog.txt

**Comment by Marcosayfi** [comment]
ok i eill.

**Comment by Marcosayfi** [comment]
https://github.com/user-attachments/assets/9f69e05d-5db4-413c-a5e3-8766e64d50c4

[latestlog.txt](https://github.com/user-attachments/files/16869864/latestlog.txt)

**Comment by Marcosayfi** [comment]
https://github.com/user-attachments/assets/270218e4-6194-4ad7-a84c-5b4af1908eb5

**Comment by Marcosayfi** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16875323/latestlog.txt)

**Comment by GaucovyAero** [comment]
try disabling compact vertex format and fog occlusion in sodium settings, if that doesnt work, you have to remove sodium
