### ISSUE TITLE
[BUG] Pojav Team Please im begging

### ISSUE THREAD

**Issue by asumy1** [PojavLauncherTeam/PojavLauncher#6025]
### Describe the bug

I started pojav 1.18.2 fabric fabric Loader 0.16.3 it says this:[21:58:25] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.16.3
[21:58:25] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:198) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:160) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:160) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:216) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:193) ~[fabric-loader-0.16.3.jar:?]
	... 3 more
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar (Permission denied)
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
		at java
.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
		at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
		at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
		at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:157) ~[fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:216) ~[fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:193) ~[fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
	Caused by: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar (Permission denied)
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:305) ~[fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:254) ~[fabric-loader-0.16.3.jar:?]
		at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThrea
d.run(ForkJoinWorkerThread.java:165) ~[?:?]
	Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/modmenu-3.2.5.jar (Permission denied)
		at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
		at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
		at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
		at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
		at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480) ~[?:?]
		at java.util.zip.ZipFile$Source.get(ZipFile.java:1445) ~[?:?]
		at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717) ~[?:?]
		at java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
		at java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
		at java.util.zip.ZipFile.<init>(ZipFile.java:194) ~[?:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:326) ~[fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:295) ~[fabric-loader-0.16.3.jar:?]
		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:254) ~[fabric-loader-0.16.3.jar:?]
		at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1
.18.2.jar (Permission denied)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:562) ~[?:?]
	at java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:604) ~[?:?]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:981) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:157) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:216) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:193) ~[fabric-loader-0.16.3.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Error analyzing [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar]: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar (Permission denied)
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:305) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:254) ~[fabric-loader-0.16.3.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWor
ker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/fabric-api-0.77.0+1.18.2.jar (Permission denied)
	at java.io.RandomAccessFile.open0(Native Method) ~[?:?]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:344) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:259) ~[?:?]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:213) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1480) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1445) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:251) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:180) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:194) ~[?:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:326) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:295) ~[fabric-loader-0.16.3.jar:?]
	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:254) ~[fabric-loader-0.16.3.jar:?]
	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:100) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### The log file and images/videos

![Screenshot_20240903_215357_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/18f9b2f9-b979-4702-8789-6b5f60d0f9be)
![Screenshot_20240903_215337_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/f6dc228d-35ea-4fad-b6b8-ce2c6168acfa)
![Screenshot_20240903_215336_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/7e137526-8d96-4d36-9144-9a6f22967854)
![Screenshot_20240903_215328_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/136f84a6-a192-431d-b180-572ff1c68ee2)
![Screenshot_20240903_215327_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/25b2c816-fcd8-425c-8241-267457339644)
![Screenshot_20240903_215326_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/3d00ec89-51ce-4c7d-a23f-b23617aaf0e5)
![Screenshot_20240903_215325_PojavLauncher (Minecraft Java Edition for Android)](https://github.com/user-attachments/assets/2d2e3420-c102-4885-a895-2b5e2211db11)
![2020_05_30_hot-e-boy-14479502](https://github.com/user-attachments/assets/967be0db-5b9e-436a-a5a6-5a7aa4ec3c10)

### Steps To Reproduce

```markdown
start pojav
Black screen
```

### Expected Behavior

fix it

### Platform

```markdown
- Device model: Samsung tab a9+
- CPU architecture:idk 
- Android version: 15
- PojavLauncher version:lastest
```

### Anything else?

please fix it I  can't play without mods

**Comment by asumy1** [comment]
log file 
[latest.log](https://github.com/user-attachments/files/16851946/latest.log)

**Comment by GaucovyAero** [comment]
dont cut your mods, copy your mods

**Comment by asumy1** [comment]
ok
