### ISSUE TITLE
[BUG] Help me please!

### ISSUE THREAD

**Issue by 1337Vlad228** [PojavLauncherTeam/PojavLauncher#603]
https://www.mediafire.com/file/t2g6d5jue42oerc/mobizen_20210114_201833.mp4/file
Model: Lenovo TB-X304L
CPU architecture: arm64
Android version: 7.1.1
I can't play in Minecraft.
Help me please!

**Comment by artdeell** [comment]
try remove your .minecraft folder

**Comment by 1337Vlad228** [comment]
> try remove your .minecraft folder

I'm removed this folder

**Comment by 1337Vlad228** [comment]
> try remove your .minecraft folder

But idk what to do next

**Comment by 1337Vlad228** [comment]
> try remove your .minecraft folder

When i'm open Pojav, i have to choose runtime, and when i chose runtime, i see this:

java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
	at java.io.File.createNewFile(File.java:948)
	at net.kdt.pojavlaunch.PojavLoginActivity.uncompressTarXZ(PojavLoginActivity.java:561)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:386)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:34)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:142)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:78)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by khanhduytran0** [comment]
It likely something wrong in java runtime.

**Comment by 1337Vlad228** [comment]
> It likely something wrong in java runtime.

https://yadi.sk/d/lrvzpXmuqo_YeQ
I'm used this

**Comment by 1337Vlad228** [comment]
> It likely something wrong in java runtime.

https://www.mediafire.com/file/tx9cnj762ypgpoy/jre8-arm64-20201104-release.tar.xz/file

If it's more comfortable
