### ISSUE TITLE
[BUG] Babric not work

### ISSUE THREAD

**Issue by Kna2137** [PojavLauncherTeam/PojavLauncher#6058]
### Describe the bug

Babric not work

### The log file and images/videos

java.lang.NumberFormatException: For input string: "*"
	at java.lang.Integer.parseInt(Integer.java:604)
	at java.lang.Integer.parseInt(Integer.java:650)
	at net.kdt.pojavlaunch.Tools.preProcessLibraries(Tools.java:721)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.scheduleLibraryDownloads(MinecraftDownloader.java:243)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:217)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:90)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:63)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

### Steps To Reproduce

```markdown
1. Pojav launcher start
2. Babric Play
3. Babric error
```

### Expected Behavior

Babric work and play b1.7.3 mod

### Platform

```markdown
- Device model: Android
- CPU architecture: ?
- Android version: 10
- PojavLauncher version: ?
```

**Comment by GaucovyAero** [comment]
https://www.mediafire.com/folder/sukd2efwb2du6/AppletMains

will send installation video if i dont forget, seems like it wont fit in here cause its like 5 minutes long
from the folder i sent here, you should download the appletmain.class thats in the folder that has impl in it

edit: i recommend watching it at 0.5x or 0.25x speed

**Comment by GaucovyAero** [comment]
https://github.com/user-attachments/assets/756bf64f-6a6e-478a-ab50-52f97c438644

**Comment by Kna2137** [comment]
would it be possible to send b1.7.3-custom and fabric from version?

**Comment by GaucovyAero** [comment]
> would it be possible to send b1.7.3-custom and fabric from version?

i can send you b1.7.3-custom but please deal with other stuff yourself, as babric is going to update, if you need more support, ping me on the pojav discord

**Comment by Kna2137** [comment]
Okey

**Comment by GaucovyAero** [comment]
[b1.7.3-custom.zip](https://github.com/user-attachments/files/16978991/b1.7.3-custom.zip)
