### ISSUE TITLE
[BUG]Keyboard

### ISSUE THREAD

**Issue by pedrosouzabrasil** [PojavLauncherTeam/PojavLauncher#606]
**Describe the bug**
Keyboard (gboard)not working properly in game

**To Reproduce**
1. Start PojavLauncher
...

**Expected behavior**
I expected ...working.

**Screenshots**

**Platform:**
 - Device Model [e.g. núbia 5s 8/128]
 - CPU architecture [e.g. aarch64] 
 - Android Version [e.g. 10]

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>when using Microsoft keyboard keyboard Works but game crash..sent email for dev..
</details>

**Comment by khanhduytran0** [comment]
> when using Microsoft keyboard keyboard Works but game crash..sent email for dev..

But.. you only sent to me, not send here?

**Comment by artdeell** [comment]
Wait, where does the game crash with Micro keyboard?

**Comment by khanhduytran0** [comment]
The latestcrash.txt I received
```

PojavLauncher crash report
 - Time: 13 de jan de 2021 10:08:40
 - Device: NX659J-EEA NX659J
 - Android version: 10
 - Crash stack trace:
java.lang.IndexOutOfBoundsException: replace (0 ... -1) has end before start
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1318)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:513)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:37)
	at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:250)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:450)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:249)
	at android.app.ActivityThread.main(ActivityThread.java:8335)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:511)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```
Weird it does not contains PojavLaunch code stack trace...

**Comment by artdeell** [comment]
I think you aren't on latest, because i patched that bug just 1 hour ago

**Comment by pedrosouzabrasil** [comment]
I used es file Explorer ..can i help in something ?

**Comment by pedrosouzabrasil** [comment]
I Will try again..thanks

**Comment by pedrosouzabrasil** [comment]
Send a vídeo for dev..on drive https://drive.google.com/file/d/11noQ3QAD77W64y2B3xFFaW_YfL48goja/view?usp=drivesdk

**Comment by pedrosouzabrasil** [comment]
Gn and blessed day/night

**Comment by khanhduytran0** [comment]
> Send a vídeo for dev..on drive https://drive.google.com/file/d/11noQ3QAD77W64y2B3xFFaW_YfL48goja/view?usp=drivesdk

Please open access for everyone/other devs also

**Comment by pedrosouzabrasil** [comment]
Ok

Em qua, 13 de jan de 2021 11:55, Duy Tran Khanh <notifications@github.com>
escreveu:

**Comment by khanhduytran0** [comment]
@pedrosouzabrasil is this fixed or not?

**Comment by pedrosouzabrasil** [comment]
I will test again

**Comment by pedrosouzabrasil** [comment]
really Sorry ..im using github a little...

**Comment by pedrosouzabrasil** [comment]
Not fixed ..only hackers keyboard is working in my device ..nubia 5

**Comment by Mathias-Boulay** [comment]
Bug fixed in latest mainline.
closing
