### ISSUE TITLE
[BUG]  i want to play minecraft,but it crashes if i open custom controls or edit controls, i also guess i need the ''TMP_IMPORT_FILE.json''

### ISSUE THREAD

**Issue by Sukuna303** [PojavLauncherTeam/PojavLauncher#6077]
### Describe the bug

java.lang.RuntimeException: Unable to start activity ComponentInfo{net.kdt.pojavlaunch/net.kdt.pojavlaunch.CustomControlsActivity}: com.google.gson.JsonSyntaxException: Failed to load
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8900)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: com.google.gson.JsonSyntaxException: Failed to load
	at net.kdt.pojavlaunch.customcontrols.LayoutConverter.loadAndConvertIfNecessary(LayoutConverter.java:39)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:73)
	at net.kdt.pojavlaunch.CustomControlsActivity.onCreate(CustomControlsActivity.java:73)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8929)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	... 12 more
Caused by: org.json.JSONException: Value PKU�qXMETA-INF of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:112)
	at org.json.JSONObject.<init>(JSONObject.java:172)
	at org.json.JSONObject.<init>(JSONObject.java:185)
	at net.kdt.pojavlaunch.customcontrols.LayoutConverter.loadAndConvertIfNecessary(LayoutConverter.java:21)
	... 18 more

### The log file and images/videos

i cant play because i cant edit my controls because of crashing

### Steps To Reproduce

```markdown
if i open the custom controls, It eventually crashes after i edit a control
```

### Expected Behavior

a

### Platform

```markdown
- Device model: Galaxy A05
- CPU architecture: 6 x 1.80 GHz
2 x 2.00 GHz
- Android version: 14
- PojavLauncher version: foxglove-20240905-8c90b54-v3_openjdk
```

### Anything else?

 nothing else

**Comment by GaucovyAero** [comment]
record the issue pls

**Comment by Sukuna303** [comment]
Uploading XRecorder_Edited_19092024_192443.mp4…

**Comment by Sukuna303** [comment]
Uploading XRecorder_Edited_19092024_192443.mp4…

**Comment by Sukuna303** [comment]
> record the issue pls

here

**Comment by GaucovyAero** [comment]
you never uploaded it, you gotta wait till it actually uploads and do not click anything while you do it

**Comment by Sukuna303** [comment]
Uploading XRecorder_Edited_19092024_192443.mp4…

**Comment by Sukuna303** [comment]
https://github.com/user-attachments/assets/aec6cf0d-6d5f-4427-bbd6-a08989ea9f13

**Comment by Sukuna303** [comment]
> you never uploaded it, you gotta wait till it actually uploads and do not click anything while you do it

sorry bro
my fault

**Comment by GaucovyAero** [comment]
can you try removing all the files inside the /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/controlmap?

**Comment by Sukuna303** [comment]
> can you try removing all the files inside the /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/controlmap?

i did it yesterday but it still didnt work :(

**Comment by GaucovyAero** [comment]
> > can you try removing all the files inside the /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/controlmap?
> 
> i did it yesterday but it still didnt work :(

show video of you doing it

**Comment by Sukuna303** [comment]
https://github.com/user-attachments/assets/5d47a9e7-2798-481b-8b28-23edde7f5e51

**Comment by Sukuna303** [comment]
it gives this error   java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/controlmap/TMP_IMPORT_FILE.json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:179)
	at java.io.FileInputStream.<init>(FileInputStream.java:133)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:872)
	at net.kdt.pojavlaunch.customcontrols.LayoutConverter.loadAndConvertIfNecessary(LayoutConverter.java:19)
	at net.kdt.pojavlaunch.customcontrols.ControlLayout.loadLayout(ControlLayout.java:73)
	at net.kdt.pojavlaunch.CustomControlsActivity.onCreate(CustomControlsActivity.java:73)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8929)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8900)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8763)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 22 more

**Comment by Sukuna303** [comment]
after i click the custom controls

**Comment by GaucovyAero** [comment]
try importing controls via your file manager - click on the json file and press pojav, here are some example controls you can try importing
[aerov16r21.json](https://github.com/user-attachments/files/17077349/aerov16r21.json)

**Comment by GaucovyAero** [comment]
if that doesnt work, go to the pojav directory into controlmap and copy my controlmap and rename it to TMP_IMPORT_FILE.json, then change the default controlmap you have, if all that doesnt work, reinstall pojav, cant help more than this, closing

**Comment by Sukuna303** [comment]
> if that doesnt work, go to the pojav directory into controlmap and copy my controlmap and rename it to TMP_IMPORT_FILE.json, then change the default controlmap you have, if all that doesnt work, reinstall pojav, cant help more than this, closing

Thank you so much bro,it is fixed now im so happy righy now bro
