### ISSUE TITLE
[BUG] Crash JNA wrong version

### ISSUE THREAD

**Issue by slulttbr** [PojavLauncherTeam/PojavLauncher#6116]
### Describe the bug

I'm trying to run a modpack on 1.7.10 but it's crashing every time, I don't know what else to try to make it work.

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240922-a6a6a29-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 2311DRK48G
Info: API version: 34
Info: Selected Minecraft version: 1.7.10-Forge10.13.4.1614-1.7.10
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2610
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~XIeuc9V9bftAKE9K15oWrA==/net.kdt.pojavlaunch-lQWUdfL8z3XyZlvAQ1qOVA==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~XIeuc9V9bftAKE9K15oWrA==/net.kdt.pojavlaunch-lQWUdfL8z3XyZlvAQ1qOVA==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1220
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 32768
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is ARM
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
glXMakeCurrent FBO workaround enabled
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
OpenJDK 64-Bit Server VM warning: No monotonic clock was available - timed services may be adversely affected if the time-of-day clock changes
--------- beginning of main
I/jrelog  ( 6041): dlopen libgl4es_114.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  ( 6041): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  ( 6041): dlopen /d
ata/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so failed: dlopen failed: library "libtinyiconv.so" not found: needed by /data/data/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnpt.so in namespace clns-4
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2gss.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/liblcms.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/server/libjvm.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libdt_socket.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pcsc.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libzip.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libverify.so success
I/jrelog  ( 6041): dl
open /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libunpack.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsctp.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/jli/libjli.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfontmanager.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libhprof.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libtinyiconv.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libfreetype.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmanagement.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsig.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kd
t.pojavlaunch/runtimes/Internal/lib/aarch64/libjaas_unix.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjawt.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libinstrument.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsdt.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnet.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libsunec.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libnio.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_headless.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/li
b/aarch64/libawt.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libawt_xawt.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjpeg.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjdwp.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjava_crw_demo.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libmlib_image.so success

I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libjsound.so success
I/jrelog  ( 6041): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal/lib/aarch64/libj2pkcs11.so success
I/jrelog  ( 6041): dlopen /data/app/~~XIeuc9V9bftAKE9K15oWrA==/net.kdt.pojavlaunch-lQWUdfL8z3XyZlvAQ1qOVA==/lib/arm64/libopenal.so success
I/jrelog  ( 6041): Done processing args
I/jrelog  ( 6041): Found JLI lib
I/jrelog  ( 6041): Calling JLI_Launch

2024-09-29 14:42:05,564 ERROR appender Console has no parameter that matches element Policies
[14:42:05] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:42:05] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[14:42:05] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[14:42:05] [main/INFO]: Forge Mod Loader version 7.99.40.1614 for Minecraft 1.7.10 loading
[14:42:05] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_432-internal, running on Linux:aarch64:Android-14, installed at /data/user/0/net.kdt.pojavlaunch/runtimes/Internal
[14:42:05] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from +unimixins-all-1.7.10-0.1.17.jar
[14:42:05] [main/WARN]: The coremod am2.preloader.AM2PreloaderContainer does not have a MCVersion annotation, it may cause issues with this version of Minecraft
2024-09-29 14:42:05,806 ERROR appender Console has no parameter that matches element Policies
[14:42:05] [main/INFO]: Core initializing...stand back!  I'm going to try MAGIC!
[14:42:05] [main/INFO]: [AppEng] Core Init
[14:42:05] [main/INFO]: Loading tweaker me.guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.0.1.jar
[14:42:06] [main/WARN]: Warning: version of ForgeMultipart, 1.2.0.347 is newer than request 1.2.0.345
[14:42:06] [main/WARN]: The coremod cofh.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/ERROR]: Unable to read the jar file ForgeMultipart-1.7.10-1.2.0.347-universal.jar - ignoring
java.io.FileNotFoundException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/ForgeMultipart-1.7.10-1.2.0.347-universal.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_432-internal]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_432-internal]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_432-internal]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_432-internal]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_432-internal]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:308) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[14:42:06] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/INFO]: [micdoodle8.mods.miccore.DepLoader$DepLoadInst:<init>:333]: MicdoodleCore searching for dependencies in mods file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods
[14:42:06] [main/WARN]: The coremod ic2.core.coremod.IC2core does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/WARN]: The coremod net.thecondemned.LumySkinPatch.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/WARN]: The coremod mekanism.common.asm.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/WARN]: The coremod openblocks.OpenBlocksCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/WARN]: The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_U_D8.jar
[14:42:06] [main/WARN]: The coremod io.dogboy.serializationisbad.legacyforge.SerializationIsBadCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/INFO]: Initializing SerializationIsBad, implementation type: legacyforge
[14:42:06] [main/INFO]: Using remote config file
[14:42:06] [main/INFO]: Loaded config file
[14:42:06] [main/INFO]:   Blocking Enabled: true
[14:42:06] [main/INFO]:   Loaded Patch Modules: 39
[14:42:06] [main/WARN]: The coremod thaumcraft.codechicken.core.launch.DepLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:42:06] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from ThaumicTinkerer-2.10.0.jar
[14:42:06] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from WitcheryExtras-1.7.10-1.1.6-dev.jar
[14:42:06] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:42:06] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[14:42:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/+unimixins-all-1.7.10-0.1.17.jar Service=LaunchWrapper Env=CLIENT
[14:42:06] [main/DEBUG]: Instantiating coremod class AllCore
[14:42:07] [main/INFO]: MixinBootstrap Initializing...
[14:42:07] [main/INFO]: Compatibility level set to JAVA_8
[14:42:07] [main/INFO]: Initializing GasStationCore
[14:42:07] [main/INFO]: Initializing GTNHMixins Core
[14:42:07] [main/DEBUG]: The coremod io.github.legacymoddingmc.unimixins.all.AllCore requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[14:42:07] [main/INFO]: Instantiating AllCore
[14:42:07] [main/INFO]: Instantiating CompatCore
[14:42:07] [main/INFO]: Instantiating MixinExtrasCore
[14:42:07] [main/DEBUG]: Added access transformer class io.github.legacymoddingmc.unimixins.all.AllCore$CombinedAccessTransformer to enqueued access transformers
[14:42:07] [main/DEBUG]: Enqueued coremod AllCore
[14:42:07] [main/DEBUG]: Instantiating coremod class ThaumicTLoaderContainer
[14:42:07] [main/DEBUG]: The coremod thaumic.tinkerer.preloader.ThaumicTLoaderContainer requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[14:42:07] [main/DEBUG]: Enqueued coremod ThaumicTLoaderContainer
[14:42:07] [main/DEBUG]: Instantiating coremod class WE_CORE_FMLLoadingPlugin
[14:42:07] [main/DEBUG]: The coremod alkalus.main.asm.WE_CORE_FMLLoadingPlugin requested minecraft version 1.7.10 and minecraft is 1.7.10. It will be loaded.
[14:42:07] [main/DEBUG]: Enqueued coremod WE_CORE_FMLLoadingPlugin
[14:42:07] [main/INFO]: Loading tweak class name me.guichaguri.betterfps.tweaker.BetterFpsTweaker
[14:42:07] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[14:42:07] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[14:42:07] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[14:42:07] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[14:42:07] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:42:07] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:42:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:42:07] [main/DEBUG]: Injecting coremod GTNHLibCore {com.gtnewhorizon.gtnhlib.core.GTNHLibCore} class transformers
[14:42:07] [main/DEBUG]: Injection complete
[14:42:07] [main/DEBUG]: Running coremod plugin for GTNHLibCore {com.gtnewhorizon.gtnhlib.core.GTNHLibCore}
[14:42:07] [main/DEBUG]: Running coremod plugin GTNHLibCore
[14:42:07] [main/DEBUG]: Coremod plugin class GTNHLibCore run successfully
[14:42:07] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[14:42:07] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[14:42:07] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[14:42:07] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
[14:42:07] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/OptiFine_1.7.10_HD_U_D8.jar
[14:42:07] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/OptiFine_1.7.10_HD_U_D8.jar
[14:42:07] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:42:07] [main/DEBUG]: Injecting coremod FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin} class transformers
[14:42:07] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.MarkerTransformer
[14:42:07] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.SideTransformer
[14:42:07] [main/TRACE]: Registering transformer cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
[14:42:07] [main/DEBUG]: Injection complete
[14:42:07] [main/DEBUG]: Running coremod plugin for FMLCorePlugin {cpw.mods.fml.relauncher.FMLCorePlugin}
[14:42:07] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[14:42:07] [main/DEBUG]: Read 527 binary patches
[14:42:08] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:42:08] [main/ERROR]: FML appears to be missing any

### Steps To Reproduce

```markdown
1. Start Pojavlauncher
2. Play modpack
3. Mojang screen and then crash
```

### Expected Behavior

I expected the modpack to open without any major issues.

### Platform

```markdown
- Device model: Xiaomi Poco X6 Pro 12/512GB
- CPU architecture: arm64
- Android version: 14
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

I saw some possible solutions, but I couldn't apply them very well, such as modifying the apk and installing another runtime, I couldn't find a runtime that was compatible, the ones I installed the Mojang screen didn't even appear, it was an instant crash.

**Comment by GaucovyAero** [comment]
closing as spam, please send the log file
