### ISSUE TITLE
[BUG] Crash On Launch with Mods

### ISSUE THREAD

**Issue by YuriBrezm** [PojavLauncherTeam/PojavLauncher#6134]
### Describe the bug

Crash on Launch evertime I play with any Mod,  And If I don't use any mods it launches normally. This has been happening for months.

### The log file and images/videos

[17:07:13] [main/INFO]: ModLauncher running: args [--username, TangoSix, --version, 1.21, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/assets, --assetIndex, 17, --uuid, 00000000000000000000000000000000, --accessToken, **********, --clientId, ${clientid}, --xuid, , --userType, msa, --versionType, release, --launchTarget, forge_client]
[17:07:14] [main/INFO]: JVM identified as Oracle Corporation OpenJDK 64-Bit Server VM 21.0.1-internal-adhoc.runner.openjdk-21
[17:07:14] [main/INFO]: ModLauncher 10.2.1 starting: java version 21.0.1-internal by N/A; OS Linux arch aarch64 version Android-13
[17:07:14] [main/ERROR]: Error during early discovery
java.nio.file.AccessDeniedException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/mods/CustomSkinLoader_ForgeV3-14.20.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:355) ~[?:?]
	at jdk.zipfs@21.0.1-internal/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:170) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.1-internal/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125) ~[jdk.zipfs:?]
	at jdk.zipfs@21.0.1-internal/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106) ~[jdk.zipfs:?]
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339) ~[?:?]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.newFileSystem(Jar.java:195) ~[securemodules-2.2.19.jar!/:?]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:89) ~[securemodules-2.2.19.jar!/:?]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:73) ~[securemodules-2.2.19.jar!/:?]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:64) ~[securemodules-2.2.19.jar!/:?]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:60) ~[securemodules-2.2.19.jar!/:?]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:52) ~[securemodules-2.2.19.jar!/:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:76) ~[fmlloader-1.21-51.0.33.jar!/:51.0.33]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:65) [fmlloader-1.21-51.0.33.jar!/:51.0.33]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:48) [fmlloader-1.21-51.0.33.jar!/:51.0.33]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21-51.0.33/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:38) [fmlloader-1.21-51.0.33.jar!/:51.0.33]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:128) [modlauncher-10.2.1.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.run(Launcher.java:84) [modlauncher-10.2.1.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.1.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.1/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.1.jar!/:?]
	at net.minecraftforge.bootstrap@2.1.3/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.3.jar!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.3.jar:2.1.3]
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.3.jar:2.1.3]
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.3.jar:2.1.3]
[17:07:14] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[17:07:15] [main/INFO]: Trying GL version 4.6
[17:07:15] [main/INFO]: Requested GL version 4.6 got version 0.0
[17:07:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=jar:file:///storage/emulated/0/Android/data/net.kdt.pojavlaunch.debug/files/.minecraft/libraries/org/spongepowered/mixin/0.8.7/mixin-0.8.7.jar!/ Service=ModLauncher Env=CLIENT

### Steps To Reproduce

```markdown
1. Start PojavLauncher
2. Click Launch Minecraft Forge 1.21
3. Game should start normally
```

### Expected Behavior

Expect to launch normally with Mods

### Platform

```markdown
- Device model: Realme C35
- CPU architecture: Adreno
- Android version: 13
- PojavLauncher version: version foxglove-20240930-c8ab4e5-feat/vm_signal_fix
```

**Comment by YuriBrezm** [comment]
Nvm, found a way to fix it. Zip and unzip the mods.

**Comment by GaucovyAero** [comment]
when installing, you can prevent this by copying the mods and not cutting them
