### ISSUE TITLE
No such file or directory [BUG]

### ISSUE THREAD

**Issue by thesaguaro** [PojavLauncherTeam/PojavLauncher#615]
I downloaded 64bit Runtime for PojavLauncher, and every time I select it to install it in PojavLauncher, it says: ```No such file or directory```
Also, when I click show more, it says this:
```
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1008)
	at net.kdt.pojavlaunch.PojavLoginActivity.uncompressTarXZ(PojavLoginActivity.java:561)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:386)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:34)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:142)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:78)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```
I use v3.3 testing 1 stable build, and jre8-arm64-20210115-release.tar.xz Runtime.
Please help.

**Comment by khanhduytran0** [comment]
Download 70mb app instead. No runtime required.

**Comment by thesaguaro** [comment]
> Download 70mb app instead. No runtime required.

I used that one and it asked me for runtime.

**Comment by khanhduytran0** [comment]
But does it ask for aarch32? Or 64?

**Comment by thesaguaro** [comment]
I downloaded the latest dev build now, and it's working. But I can't log in with Microsoft acc.

**Comment by thesaguaro** [comment]
![0-02-0a-4efac299d273e41028600fc7bc2f479643e08efbd8a42573338bbe7c79b126d8_ee2fd730](https://user-images.githubusercontent.com/50411983/104783561-96abae80-5786-11eb-9720-5299eda0e91f.jpg)
also, when I try check keep me logged in, it says this

**Comment by khanhduytran0** [comment]
If you get something like below, this means you haven't bought Minecraft.
```
{
   "path" : "/minecraft/profile",
   "errorType" : "NOT_FOUND",
   "error" : "NOT_FOUND",
   "errorMessage" : "The server has not found anything matching the request URI",
   "developerMessage" : "The server has not found anything matching the request URI"
}
```

**Comment by thesaguaro** [comment]
hmmmmmmmmm, I'm sure that I bought it, but I don't get that error. It just says that the username or password is incorrect, and when I tried to play with offline acc, it just crashed. I somehow managed to install mc in the launcher, but when I click play, it crashes.
Crash log:
```
java.lang.RuntimeException: java.io.IOException: No such file or directory
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.setLastCrash(CrashFragment.java:82)
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.refreshCrashFile(CrashFragment.java:74)
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.onResume(CrashFragment.java:52)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2383)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
	at android.support.v4.app.FragmentManagerImpl.performPendingDeferredStart(FragmentManager.java:1228)
	at android.support.v4.app.FragmentManagerImpl.startPendingDeferredFragments(FragmentManager.java:1845)
	at android.support.v4.app.FragmentManagerImpl.doPendingDeferredStart(FragmentManager.java:2689)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2205)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
	at android.view.Choreographer.doCallbacks(Choreographer.java:793)
	at android.view.Choreographer.doFrame(Choreographer.java:724)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1008)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:503)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:512)
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.setLastCrash(CrashFragment.java:80)
	... 24 more
```

**Comment by khanhduytran0** [comment]
Check `/sdcard/games/PojavLauncher/.minecraft` and make sure it exists. (Enable show hidden folder)

**Comment by thesaguaro** [comment]
It does not exist.

**Comment by thesaguaro** [comment]
![0-02-05-b608bb63107e5c367186b93712aff540d57ac71f962ed3fd85e2482782b0da74_2ac51be3](https://user-images.githubusercontent.com/50411983/104784045-b42d4800-5787-11eb-9b4b-3eb749b18342.jpg)
![0-02-05-4a776d7cb5f67c2cefe0bd59f4e1862b2a4fe8fe3f0af6e3c03e9099c468a3cd_bb4b9652](https://user-images.githubusercontent.com/50411983/104784048-b68fa200-5787-11eb-9356-684268a49011.jpg)
this folders exists.

**Comment by khanhduytran0** [comment]
So, inside games folder, create `PojavLauncher/.minecraft` folder manually and try again.

**Comment by thesaguaro** [comment]
Nothing changed :(

**Comment by thesaguaro** [comment]
Is it going to work if I copy and paste .minecraft folder from my pc in ```PojavLauncher/.minecraft``` directory?

**Comment by khanhduytran0** [comment]
Maybe. But make sure you've granted storage permission for app.

**Comment by thesaguaro** [comment]
I granted storage permission for the app.

**Comment by khanhduytran0** [comment]
Ehhh it sounds like you are on v2, but not v3...

**Comment by thesaguaro** [comment]
![image](https://user-images.githubusercontent.com/50411983/104784549-d378a500-5788-11eb-9996-dde365041908.png)
I downloaded this one

**Comment by khanhduytran0** [comment]
(After download new build)

**Comment by thesaguaro** [comment]
accualy  no

**Comment by thesaguaro** [comment]
![image](https://user-images.githubusercontent.com/50411983/104784609-f1dea080-5788-11eb-82c7-867bdb1f25b3.png)
This one

**Comment by thesaguaro** [comment]
oh its v2

**Comment by thesaguaro** [comment]
wait

**Comment by thesaguaro** [comment]
im stupid

**Comment by thesaguaro** [comment]
sorry I downloaded v3

**Comment by thesaguaro** [comment]
It started patching, and it crashed.

**Comment by thesaguaro** [comment]
```
java.lang.RuntimeException: java.io.IOException: No such file or directory
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.setLastCrash(CrashFragment.java:82)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.onPostExecute(MCLauncherActivity.java:769)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.onPostExecute(MCLauncherActivity.java:476)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
	at java.io.File.createNewFile(File.java:1008)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:503)
	at net.kdt.pojavlaunch.Tools.write(Tools.java:512)
	at net.kdt.pojavlaunch.mcfragments.CrashFragment.setLastCrash(CrashFragment.java:80)
	... 11 more
```

**Comment by khanhduytran0** [comment]
V3 does not patch

**Comment by thesaguaro** [comment]
Im sure I downloaded V3

**Comment by thesaguaro** [comment]
Is this one V3: https://github.com/PojavLauncherTeam/PojavLauncher/releases/tag/v3.3.0-testing

**Comment by khanhduytran0** [comment]
Yes

**Comment by khanhduytran0** [comment]
> Check `/sdcard/games/PojavLauncher/.minecraft` and make sure it exists. (Enable show hidden folder)

Check again

**Comment by khanhduytran0** [comment]
It may not inside PojavLauncher folder, but inside games folder.

**Comment by khanhduytran0** [comment]
Also, check if app is installed on external storage?

**Comment by thesaguaro** [comment]
I got SD card, but my phone set it to be main storage.

**Comment by thesaguaro** [comment]
I literally can't access my phone storage.

**Comment by thesaguaro** [comment]
I don't think that's the problem.

**Comment by netkv** [comment]
Pojav doesnt work on sdcard, i think fat32 isnt enought and it needs unix permissions or something
try uninstalling pojav, removing sdcard, installing pojav, and adding sdcard back

**Comment by thesaguaro** [comment]
I'll try that, but I think that on Xiaomi phones I can't do that until I format SDcard, and then try it. I'm not sure if Xiaomi fixed that.

**Comment by khanhduytran0** [comment]
@SugarWasEaten so?

**Comment by Mathias-Boulay** [comment]
Stale issue on an old build, closing it.
