### ISSUE TITLE
When I launch 1.14.4 forge and 1.16.4 forge with the latest version in actions, the software will crash

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#617]
When I launch 1.14.4 forge and 1.16.4 forge with the latest version in actions:https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/489388095  ,the software will crash.But I can launch 1.16.4forge and 1.14.4forge successfully with older version in actions.
there is the crash-report:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 21-1-16 上午3:56
Description: Unexpected error

java.lang.Error: Could not find class: net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:117) ~[?:1.8.0-internal] {}
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82) ~[?:1.8.0-internal] {}
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181) ~[?:1.8.0-internal] {}
	at com.mamiyaotaru.voxelmap.util.ImageUtils.createBufferedImageFromResourceLocation(ImageUtils.java:103) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.util.ImageUtils.loadImage(ImageUtils.java:315) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.Radar.createImageFromTypeAndImages(Radar.java:611) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.Radar.createImageFromTypeAndResourceLocations(Radar.java:581) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.Radar.loadTexturePackIcons(Radar.java:462) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.Radar.onResourceManagerReload(Radar.java:431) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.VoxelMap.apply(VoxelMap.java:162) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.VoxelMap.lateInit(VoxelMap.java:139) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.forgemod.ClientProxy.postInit(ClientProxy.java:18) ~[voxelmap:1.0] {re:classloading}
	at com.mamiyaotaru.voxelmap.forgemod.ForgeModVoxelMap$1.run(ForgeModVoxelMap.java:68) ~[voxelmap:1.0] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0-internal] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0-internal] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0-internal] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 356636496 bytes (340 MB) / 838860800 bytes (800 MB) up to 838860800 bytes (800 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xms768m -Xmx800m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |ENQUEUE_IM|NOSIGNATURE
		HotLib-1.16.2-0.0.1.jar                           |HotLib                        |hotlib                        |0.0.1               |ENQUEUE_IM|NOSIGNATURE
		WatchDog-AntiCheat-1.16.2-0.0.1.jar               |WatchDog AntiCheat            |watchdog                      |0.0.1               |ENQUEUE_IM|NOSIGNATURE
		VoxelMap-Mod-1.16.4.jar                           |VoxelMap                      |voxelmap                      |1.10.14             |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		torohealth-1.16.4-forge-1.jar                     |ToroHealth                    |torohealth                    |NONE                |ENQUEUE_IM|NOSIGNATURE
		forgeautofish-1.0.5-1.16.3.jar                    |AutoFish for Forge            |forgeautofish                 |1.0.5               |ENQUEUE_IM|NOSIGNATURE
	Crash Report UUID: 44323864-b7c5-45a2-abcd-f5ba4348fb8e
	Launched Version: 1.16.4
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 8x null
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
Try this fix https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/489484820

**Comment by yejunjie10311031** [comment]
Thank you very much.I can launch it now.

**Comment by khanhduytran0** [comment]
You’re welcome.
