### ISSUE TITLE
The software will crash when I launch 1.10.2forge and 1.12.2forge with the newest version in Actions

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#619]
The software will crash when I launch 1.10.2forge and 1.12.2forge with the newest version in Actions:https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/489551289
there is the crash-report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ValkyrienWarfareBase CoreMod (Valkyrien+Warfare+0.9_pre_1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 21-1-16 上午7:53
Description: Initializing game

java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at net.java.openjdk.cacio.ctc.FontManagerUtil$1.run(FontManagerUtil.java:36)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.openjdk.cacio.ctc.FontManagerUtil.setFontManager(FontManagerUtil.java:17)
	at net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment.<clinit>(CTCGraphicsEnvironment.java:31)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at net.optifine.util.TextureUtils.scaleImage(TextureUtils.java:514)
	at net.minecraft.client.renderer.texture.TextureMap.getMissingImageData(TextureMap.java:980)
	at net.minecraft.client.renderer.texture.TextureMap.func_110569_e(TextureMap.java:121)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:158)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.java.openjdk.cacio.ctc.FontManagerUtil$1.run(FontManagerUtil.java:25)
	... 24 more
Caused by: java.lang.ClassCastException: net.java.openjdk.cacio.ctc.CTCFontManager cannot be cast to sun.awt.X11FontManager
	at sun.awt.motif.MFontConfiguration.getFileNameFromComponentFontName(MFontConfiguration.java:267)
	at sun.awt.FontConfiguration.get2DCompositeFontInfo(FontConfiguration.java:1051)
	at sun.font.SunFontManager.initCompositeFonts(SunFontManager.java:3557)
	at sun.font.SunFontManager.access$800(SunFontManager.java:65)
	at sun.font.SunFontManager$2.run(SunFontManager.java:555)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:386)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at net.java.openjdk.cacio.ctc.CTCFontManager.<init>(CTCFontManager.java:59)
	... 29 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.java.openjdk.cacio.ctc.FontManagerUtil$1.run(FontManagerUtil.java:36)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.openjdk.cacio.ctc.FontManagerUtil.setFontManager(FontManagerUtil.java:17)
	at net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment.<clinit>(CTCGraphicsEnvironment.java:31)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at net.optifine.util.TextureUtils.scaleImage(TextureUtils.java:514)
	at net.minecraft.client.renderer.texture.TextureMap.getMissingImageData(TextureMap.java:980)
	at net.minecraft.client.renderer.texture.TextureMap.func_110569_e(TextureMap.java:121)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:158)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 486539152 bytes (463 MB) / 805306368 bytes (768 MB) up to 838860800 bytes (800 MB)
	JVM Flags: 20 total; -Xms768m -Xmx800m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/xml-libs-pack.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 Optifine OptiFine_1.10.2_HD_U_H5 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCH	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCH	flammpfeil.slashblade{mc1.10.2-r39} [SlashBlade] (SlashBlade-mc1.10.2-r39.jar) 
	UCH	valkyrienwarfare{0.9_alpha} [Valkyrien Warfare] (Valkyrien+Warfare+0.9_pre_1.jar) 
	UCH	cannons{cannons} [Cannons!] (Valkyrien+Warfare+0.9_pre_1.jar) 
	UCH	valkyrienwarfarecombat{0.9_alpha} [Valkyrien Warfare Combat] (Valkyrien+Warfare+0.9_pre_1.jar) 
	UCH	valkyrienwarfarecontrol{0.9_alpha} [Valkyrien Warfare Control] (Valkyrien+Warfare+0.9_pre_1.jar) 
	UCH	valkyrienwarfareworld{0.9_alpha} [Valkyrien Warfare World] (Valkyrien+Warfare+0.9_pre_1.jar) 
	Loaded coremods (and transformers): 
ValkyrienWarfareBase CoreMod (Valkyrien+Warfare+0.9_pre_1.jar)
  ValkyrienWarfareBase.CoreMod.ValkyrienWarfareTransformer
	Launched Version: 1.10.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x null
	OptiFine Version: OptiFine_1.10.2_HD_U_H5
	OptiFine Build: 20191204-143012
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
Try latest build.

**Comment by khanhduytran0** [comment]
So this is fixed. Closing
