### ISSUE TITLE
[BUG] <Short description> crash code 1

### ISSUE THREAD

**Issue by Not905** [PojavLauncherTeam/PojavLauncher#6199]
### Describe the bug

Crash when i create or joining world

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240922-a6a6a29-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 2201117PG
Info: API version: 33
Info: Selected Minecraft version: fabric-loader-0.16.7-1.19.2
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2306
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~OqCCDsMlvXRCPre3MiKcLQ==/net.kdt.pojavlaunch-Erns32LmVfBBe97CuD9Ghw==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~OqCCDsMlvXRCPre3MiKcLQ==/net.kdt.pojavlaunch-Erns32LmVfBBe97CuD9Ghw==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles3_desktopgl_angle_vulkan
Added custom env: LIBGL_ES=3
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: POJAVEXEC_EGL=libEGL_angle.so
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/jrelog  ( 9385): dlopen libtinywrapper.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 9385): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  ( 9385): 
dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so s
uccess
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.p
ojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  ( 938
5): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  ( 9385): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success
I/jrelog  ( 9385): dlopen /data/app/~~OqCCDsMlvXRCPre3MiKcLQ==/net.kdt.pojavlaunch-Erns32LmVfBBe97CuD9Ghw==/lib/arm64/libopenal.so success
I/jrelog  ( 9385): Done processing args
I/jrelog  ( 9385): Found JLI lib
I/jrelog  ( 9385): Calling JLI_Launch

Arc Capes DNS Injector
Parts of Alibaba's DCM library were used, please read https://github.com/alibaba/java-dns-cache-manipulator/blob/main/README.md for more info
Added DNS cache entry: s.optifine.net/23.95.137.176
2024-10-25 15:28:31,049 main ERROR appender Console has no parameter that matches element Policies
[15:28:31] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.16.7
[15:28:31] [main/INFO]: Loading 87 mods:
	- create 0.5.1-f-build.1416+mc1.19.2
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-8
	   |-- forge_tags 3.0
	   |-- forgeconfigapiport 4.2.9
	   |-- milk 1.0.51
	   |    \-- dripstone_fluid_lib 2.0.1
	   |-- porting_lib_accessors 2.1.1305+1.19.2
	   |-- porting_lib_base 2.1.1305+1.19.2
	   |    |-- mm 2.3
	   |    |-- porting_lib_attributes 2.1.1305+1.19.2
	   |    |-- porting_lib_common 2.1.1305+1.19.2
	   |    |-- porting_lib_constants 2.1.1305+1.19.2
	   |    |-- porting_lib_lazy_registration 2.1.1305+1.19.2
	   |    |-- porting_lib_loot 2.1.1305+1.19.2
	   |    |-- porting_lib_model_generators 2.1.1305+1.19.2
	   |    |-- porting_lib_model_loader 2.1.1305+1.19.2
	   |    |-- porting_lib_models 2.1.1305+1.19.2
	   |    \-- serialization_hooks 0.3.26
	   |-- porting_lib_entity 2.1.1305+1.19.2
	   |    \-- porting_lib_constants 2.1.1305+1.19.2
	   |-- porting_lib_extensions 2.1.1305+1.19.2
	   |    |-- porting_lib_attributes 2.1.1305+1.19.2
	   |    |-- porting_lib_common 2.1.1305+1.19.2
	   |    \-- porting_lib_constants 2.1.1305+1.19.2
	   |-- porting_lib_fake_players 2.1.1305+1.19.2
	   |-- porting_lib_networking 2.1.1305+1.19.2
	   |-- porting_lib_obj_loader 2.1.1305+1.19.2
	   |    |-- porting_lib_attributes 2.1.1305+1.19.2
	   |    |-- porting_lib_common 2.1.1305+1.19.2
	   |    |-- porting_lib_constants 2.1.1305+1.19.2
	   |    \-- porting_lib_model_loader 2.1.1305+1.19.2
	   |-- porting_lib_transfer 2.1.1305+1.19.2
	   |    |-- porting_lib_attributes 2.1.1305+1.19.2
	   |    |-- porting_lib_common 2.1.1305+1.19.2
	   |    \-- porting_lib_constants 2.1.1305+1.19.2
	   |-- reach-entity-attributes 2.3.0
	   \-- registrate-fabric 1.1.58-MC1.19.2
	- fabric-api 0.77.0+1.19.2
	   |-- fabric-api-base 0.4.15+8f4e8eb390
	   |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
	   |-- fabric-biome-api-v1 9.1.1+16f1e31390
	   |-- fabric-block-api-v1 1.0.2+e415d50e90
	   |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
	   |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
	   |-- fabric-command-api-v1 1.2.16+f71b366f90
	   |-- fabric-command-api-v2 2.2.1+413cbbc790
	   |-- fabric-commands-v0 0.2.33+df3654b390
	   |-- fabric-containers-v0 0.1.42+df3654b390
	   |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
	   |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
	   |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
	   |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
	   |-- fabric-dimensions-v1 2.1.35+0d0f210290
	   |-- fabric-entity-events-v1 1.5.4+9244241690
	   |-- fabric-events-interaction-v0 0.4.34+562bff6e90
	   |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
	   |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
	   |-- fabric-item-api-v1 1.6.6+b7d1888890
	   |-- fabric-item-groups-v0 0.3.39+9244241690
	   |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
	   |-- fabric-keybindings-v0 0.2.23+df3654b390
	   |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
	   |-- fabric-loot-api-v2 1.1.13+83a8659290
	   |-- fabric-loot-tables-v1 1.1.16+9e7660c690
	   |-- fabric-message-api-v1 5.0.7+93d8cb8290
	   |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
	   |-- fabric-models-v0 0.3.21+c6af733c90
	   |-- fabric-networking-api-v1 1.2.12+def3f86d90
	   |-- fabric-networking-v0 0.3.29+df3654b390
	   |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
	   |-- fabric-particles-v1 1.1.0+ee641e7390
	   |-- fabric-recipe-api-v1 1.0.2+413cbbc790
	   |-- fabric-registry-sync-v0 0.9.33+9244241690
	   |-- fabric-renderer-api-v1 1.2.1+1adbf27790
	   |-- fabric-renderer-indigo 0.8.0+1adbf27790
	   |-- fabric-renderer-registries-v1 3.2.25+df3654b390
	   |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
	   |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
	   |-- fabric-rendering-v0 1.1.28+df3654b390
	   |-- fabric-rendering-v1 1.13.0+526f2c6790
	   |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
	   |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
	   |-- fabric-screen-api-v1 1.0.32+4d0d570390
	   |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
	   |-- fabric-sound-api-v1 1.0.2+c4f28df590
	   |-- fabric-textures-v0 1.0.24+aeb40ebe90
	   |-- fabric-transfer-api-v1 2.1.6+413cbbc790
	   \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
	- fabricloader 0.16.7
	   \-- mixinextras 0.4.1
	- java 17
	- minecraft 1.19.2
	- railways 1.6.4+fabric-mc1.19.2
	   \-- mm 2.3
	- sodium 0.4.4+build.18
	   \-- org_joml_joml 1.10.4
[15:28:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[15:28:32] [main/INFO]: Compatibility level set to JAVA_17
[15:28:33] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[15:28:36] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[15:28:44] [main/WARN]: Method overwrite conflict for setTranslation in flywheel.fabric.mixins.json:Matrix4fMixin from mod flywheel, previously written by io.github.fabricators_of_create.porting_lib.mixin.common.Matrix4fMixin. Skipping method.
[15:28:51] [main/INFO]: Building optimized datafixer
[15:29:01] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[15:29:03] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:29:06] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:155) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:161) ~[authlib-3.11.49.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:711) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:431) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:205) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.11.49.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-3.11.49.jar:?]
	... 9 more
[15:29:06] [Render thread/INFO]: Setting user: Zakromzy
[15:29:16] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[15:29:23] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[15:29:23] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[15:29:23] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[15:29:23] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[15:29:27] [Render thread/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[15:29:30] [Render thread/INFO]: Definitely not up to no good
[15:29:32] [Render thread/INFO]: Registered bogey styles from railways
[15:29:33] [Render thread/INFO]: Registering data fixers
[15:29:34] [Render thread/INFO]: Registering tracks for Hex Casting
[15:29:34] [Render thread/INFO]: Registering tracks for Oh The Biomes You'll Go
[15:29:34] [Render thread/INFO]: Registering tracks for Blue Skies
[15:29:34] [Render thread/INFO]: Registering tracks for Twilight Forest
[15:29:34] [Render thread/INFO]: Registering tracks for Biomes O' Plenty
[15:29:34] [Render thread/INFO]: Registering tracks for Dreams and Desires
[15:29:34] [Render thread/INFO]: Registering tracks for Quark
[15:29:39] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[15:29:39] [Render thread/INFO]: No shaders mod detected.
Registered forkAndExec
[15:29:41] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[15:29:42] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
EGLBridge: Binding to desktop OpenGL
[15:29:43] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[15:29:44] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[15:29:44] [Render thread/WARN]: Removed resource pack mod_resources from options because it doesn't seem to exist anymore
[15:29:45] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[15:29:45] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[15:29:46] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='Enum 0x8501 is currently not supported.'
[15:29:46] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, me

### Steps To Reproduce

```markdown
Start pojav
Create world 
Crash
```

### Expected Behavior

No crash 

### Platform

```markdown
- Device model: Poco m4 pro
- CPU architecture: 
- Android version: 13
- PojavLauncher version: 1.19.2
```

**Comment by Not905** [comment]
Help

**Comment by Not905** [comment]
I wanted to play create mod on fabric and this happend

**Comment by GaucovyAero** [comment]
you havent sent the log file, just a cut off part of the text, cant really help here
