### ISSUE TITLE
[BUG] <Short description> ошибка 1 с модом immersive engineering

### ISSUE THREAD

**Issue by biRec** [PojavLauncherTeam/PojavLauncher#6217]
### Describe the bug

В сборке create и аддоны к нему, также rubidium. 

### The log file and images/videos

--------- beginning with launcher debug
Info: Launcher version: foxglove-20240922-a6a6a29-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 23021RAA2Y
Info: API version: 34
Info: Selected Minecraft version: 1.19.2-forge-43.3.2
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2306
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~X9JpZ_exk8fri1Gu_GbEiQ==/net.kdt.pojavlaunch-YKKyVnS2YEYAPfOBD5Kp9w==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~X9JpZ_exk8fri1Gu_GbEiQ==/net.kdt.pojavlaunch-YKKyVnS2YEYAPfOBD5Kp9w==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=vulkan_zink
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
--------- beginning of main
I/jrelog  (24310): dlopen libOSMesa.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (24310): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success
I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (24310): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (24310): dlopen /data/app/~~X9JpZ_exk8fri1Gu_GbEiQ==/net.kdt.pojavlaunch-YKKyVnS2YEYAPfOBD5Kp9w==/lib/arm64/libopenal.so success

I/jrelog  (24310): Done processing args

I/jrelog  (24310): Found JLI lib
I/jrelog  (24310): Calling JLI_Launch

2024-10-31 10:38:12,587 main ERROR appender Console has no parameter that matches element Policies
[10:38:12] [main/INFO]: ModLauncher running: args [--username, bircaeee, --version, 1.19.2, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 1.19, --uuid, 00000000000000000000000000000000, --accessToken, вќ„вќ„вќ„вќ„вќ„вќ„вќ„вќ„, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.3.2, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[10:38:12] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.12-internal by N/A; OS Linux arch aarch64 version Android-14
[10:38:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23111!/ Service=ModLauncher Env=CLIENT
[10:38:14] [main/INFO]: Found mod file create-1.19.2-0.5.1.e.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[10:38:14] [main/INFO]: Found mod file create_structures_arise-137.10.9-forge-1.19.2 (1).jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[10:38:14] [main/INFO]: Found mod file createaddition-1.19.2-1.2.2.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[10:38:14] [main/INFO]: Found mod file ImmersiveEngineering-1.19.2-9.2.4-170.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[10:38:14] [main/INFO]: Found mod file rubidium-extra-0.4.19mc1.19.2-build.105.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[10:38:14] [main/INFO]: Found mod file textruesrubidiumoptions-1.0.7-mc1.19.2.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-extra.jar, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/forge/1.19.2-43.3.2/forge-1.19.2-43.3.2-client.jar]
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:82)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.2/net.minecraftforge.fml.loading.moddiscovery.ModJarMetadata.buildFile(ModJarMetadata.java:41)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.2/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:37)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.2/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:74)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.2/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:166)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.2/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-srg.jar, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraft/client/1.19.2-20220805.130853/client-1.19.2-20220805.130853-extra.jar, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/forge/1.19.2-43.3.2/forge-1.19.2-43.3.2-client.jar]
	... 25 more
Java Exit code: 1
I/jrelog  (24310): Going to free args
I/jrelog  (24310): Free done

### Steps To Reproduce

```markdown
1. Запуск pojav launcher
2. Запуск forge 1.19.2 
3. Ожидание
4. Ошибка 1
```

### Expected Behavior

Я думал что игра запустится

### Platform

```markdown
- Device model: redmi 12 note 8/256
- CPU architecture: 
- Android version: 14
- PojavLauncher version:
```

**Comment by GaucovyAero** [comment]
use the latest version of forge for 1.19.2 (forge 43.4.4), its working for me
