### ISSUE TITLE
[BUG] <Short description>java.lang.RuntimeException: {"Identity":"0","XErr":2148916233,"Message":"","Redirect":"https://start.ui.xboxlive.com/CreateAccount"} 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireXsts(MicrosoftBackgroundLogin.java:224) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:81) 	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 	at java.lang.Thread.run(Thread.java:1012)

### ISSUE THREAD

**Issue by jshbjfuff** [PojavLauncherTeam/PojavLauncher#6225]
### Describe the bug

يقول انه يوجد خطأً
![Screenshot_20241031-200932](https://github.com/user-attachments/assets/9a1dd33e-107c-46e9-8f5f-d68d6e6d684a)
![Screenshot_20241031-175853](https://github.com/user-attachments/assets/7a1dc9e8-fb28-4e0c-8432-78aca1297e46)

### The log file and images/videos

![Screenshot_20241031-200932](https://github.com/user-attachments/assets/5b6117c3-4c23-4271-8690-6ae2306f7f05)

### Steps To Reproduce

```markdown
كل مره
```

### Expected Behavior

عدم حل المشكه انتم

### Platform

```markdown
- Device model: 
- CPU architecture: 
- Android version: 
- PojavLauncher version: 
ماين كرفت البو جفا
```

### Anything else?

اريد حل المشكه

**Comment by GaucovyAero** [comment]
log into minecraft.net
