### ISSUE TITLE
[BUG] <crash when entered world>

### ISSUE THREAD

**Issue by NoahhStill** [PojavLauncherTeam/PojavLauncher#6266]
### Describe the bug

crash when enetered world

### The log file and images/videos

Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[16:56:59] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[16:56:59] [Render thread/INFO]: Setting user: NoahhStil
[16:56:59] [Render thread/INFO]: Loaded C2B lib.
[16:57:02] [Download-2/ERROR]: Failed to fetch user properties
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at knot/com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:59) ~[authlib-6.0.54.jar:?]
	at knot/com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:150) ~[authlib-6.0.54.jar:?]
	at knot/net.minecraft.class_310.method_55608(class_310.java:458) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at knot/com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:100) ~[authlib-6.0.54.jar:?]
	at knot/com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
	at knot/com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-6.0.54.jar:?]
	... 5 more
[16:57:04] [Render thread/INFO]: Initializing Silk
Nov 13, 2024 4:57:04 PM de.miraculixx.veinminer.Veinminer onInitialize
INFO: Veinminer Version: 2.0.7 (fabric)
[16:57:05] [Render thread/INFO]: Dynamic FPS 3.7.6 active on Fabric!
[16:57:06] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[16:57:07] [Render thread/INFO]: IAS: Booting up... (version: 9.0.1, loader: Fabric, loader version: 0.16.9, game version: 1.21)
[16:57:07] [Render thread/INFO]: IAS: Initializing IAS...
[16:57:07] [Render thread/INFO]: IAS: IAS has been loaded.
[16:57:07] [Render thread/INFO]: Checking mod updates...
Registered forkAndExec
[16:57:07] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Main.initialize()
[16:57:08] [Render thread/INFO]: [STDOUT]: [Mouse Tweaks] Initialized.
[16:57:08] [Render thread/INFO]: Initialized mcClientCoroutineScope (MinecraftClient as executor)
[16:57:09] [Worker-Main-1/INFO]: Update available for 'reeses-sodium-options@1.7.2+mc1.21', (-> mc1.21-1.7.3)
[16:57:09] [Worker-Main-1/INFO]: Update available for 'autofish@1.1.1-fabric-1.21', (-> 1.3.4-fabric-mc1.21.1)
[16:57:09] [Worker-Main-1/INFO]: Update available for 'sodium@0.5.9+mc1.21', (-> mc1.21-0.5.11)
[16:57:09] [Worker-Main-1/INFO]: Update available for 'fabric-api@0.100.7+1.21', (-> 0.102.0+1.21)
[16:57:09] [Worker-Main-1/INFO]: Update available for 'veinminer@2.0.7', (-> 2.1.5)
[16:57:09] [Worker-Main-1/INFO]: Update available for 'fabric-language-kotlin@1.11.0+kotlin.2.0.0', (-> 1.12.3+kotlin.2.0.21)
[16:57:10] [Render thread/ERROR]: Error parsing option value off for option Fullscreen: Not a boolean: "off"
[16:57:10] [Render thread/ERROR]: Error parsing option value 12.0 for option Brightness: Failed to parse either. First: Value 12.0 outside of range [0.0:1.0]; Second: Not a boolean: 12.0
[16:57:11] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
EGLBridge: Binding to OpenGL ES
[16:57:11] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[16:57:12] [Render thread/WARN]: Detected presence of environment variable POJAV_LAUNCHER, which seems to indicate we are running on Android
[16:57:12] [Render thread/ERROR]: It appears that PojavLauncher is being used with an OpenGL compatibility layer. This will likely cause severe performance issues, graphical issues, and crashes when used with Sodium. This configuration is not supported -- you are on your own!
[16:57:13] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[16:57:14] [Render thread/WARN]: Removed resource pack Fabric Mods from options because it doesn't seem to exist anymore
[16:57:15] [Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[16:57:21] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at knot/com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar:?]
	at knot/com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
	at knot/com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) [text2speech-1.17.9.jar:?]
	at knot/net.minecraft.class_333.<init>(class_333.java:19) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.<init>(class_310.java:675) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at knot/com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:90) ~[jna-5.14.0.jar:?]
	at knot/com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:67) ~[text2speech-1.17.9.jar:?]
	... 8 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.Error: 

There is an incompatible JNA native library installed on this system
Expected: 7.0.0
Found:    6.1.6
(at /data/app/~~g1ZR2zu4PYDDofhjQ1OMpA==/net.kdt.pojavlaunch-2K2l0Z8MDFOfruBxyX0R0g==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
 [in thread "main"]
	at knot/com.sun.jna.Native.<clinit>(Native.java:230) ~[jna-5.14.0.jar:?]
	at knot/com.sun.jna.platform.linux.Udev.<clinit>(Udev.java:37) ~[jna-platform-5.14.0.jar:?]
	at knot/oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:80) ~[oshi-core-6.4.10.jar:?]
	at knot/oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.4.10.jar:?]
	at knot/oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:67) ~[oshi-core-6.4.10.jar:?]
	at knot/oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:58) ~[oshi-core-6.4.10.jar:?]
	at knot/oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:43) ~[oshi-core-6.4.10.jar:?]
	at knot/oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:?]
	at knot/oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48) ~[oshi-core-6.4.10.jar:?]
	at knot/net.minecraft.class_6396.method_37146(class_6396.java:79) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37121(class_6396.java:87) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37128(class_6396.java:79) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37143(class_6396.java:56) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_6396.method_37121(class_6396.java:87) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_6396.<init>(class_6396.java:56) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.<init>(class_128.java:35) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_128.method_24305(class_128.java:234) ~[client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:125) ~[client-intermediary.jar:?]
	... 3 more
[16:57:21] [Render thread/INFO]: Reloading ResourceManager: vanilla, file/DOC-20240620-WA0211.zip, file/DOC-20240521-WA0152.zip, fabric, accurateblockplacement, autofish, caffeineconfig, cateyes, cloth-config, dynamic_fps, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabrictailor, freecam, ias, libzoomer, modmenu, ok_zoomer, placeholder-api, reeses-sodium-options, silk-all, sodium, sodium-extra, veinminer, wrench_wrapper
[16:57:22] [Worker-Main-1/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
I/NativeInput( 7787): Input ready: 1

Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. Are you running essential and/or <1.13?
[16:57:24] [Worker-Main-7/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[16:57:38] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[16:57:38] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[16:57:38] [Render thread/INFO]: OpenAL initialized on device OpenSL
[16:57:38] [Render thread/INFO]: Sound engine started
[16:57:39] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/blocks.png-atlas
[16:57:39] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/signs.png-atlas
[16:57:39] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/banner_patterns.png-atlas
[16:57:39] [Render thread/INFO]: Created: 512x512x0 minecraft:textures/atlas/shield_patterns.png-atlas
[16:57:39] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/armor_trims.png-atlas
[16:57:40] [Render thread/INFO]: Created: 128x64x0 minecraft:textures/atlas/decorated_pot.png-atlas
[16:57:40] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/chest.png-atlas
[16:57:40] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/shulker_boxes.png-atlas
[16:57:40] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/beds.png-atlas
[16:57:42] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[16:57:42] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[16:57:42] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[16:57:42] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[16:57:42] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[16:57:45] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[16:57:49] [Render thread/INFO]: [STDOUT]: CatEyes by Tee_Six
[16:57:49] [Render thread/INFO]: [STDOUT]: CatEyes by Tee_Six
[16:57:50] [IO-Worker-1/INFO]: Could not authorize you against Realms server: Invalid session id
[16:57:50] [IO-Worker-1/ERROR]: Couldn't connect to realms
net.minecraft.class_4355: Realms authentication error with message 'Invalid session id'
	at knot/net.minecraft.class_4341.method_20998(class_4341.java:447) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4341.method_21027(class_4341.java:232) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8647.method_52627(class_8647.java:51) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[16:58:04] [Render thread/INFO]: Flushed changes to Minecraft configuration
[16:58:09] [Render thread/INFO]: [STDOUT]: CatEyes by Tee_Six
[16:58:28] [Render thread/INFO]: Loaded 1290 recipes
[16:58:31] [Render thread/INFO]: Loaded 1399 advancements
[16:58:36] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 8.940 ms
[16:58:36] [Server thread/INFO]: Initialized mcCoroutineScope (MinecraftServer as executor)
[16:58:36] [Server thread/INFO]: Starting integrated minecraft server version 1.21
[16:58:36] [Server thread/INFO]: Generating keypair
[16:58:38] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:58:40] [Render thread/INFO]: Preparing spawn area: 0%
[16:58:40] [Render thread/INFO]: Preparing spawn area: 0%
[16:58:40] [Render thread/INFO]: Preparing spawn area: 0%
[16:58:40] [Render thread/INFO]: Preparing spawn area: 0%
[16:58:40] [Render thread/INFO]: Preparing spawn area: 0%
[16:58:40] [Render thread/INFO]: Preparing spawn area: 0%
[16:58:41] [Render thread/INFO]: Preparing spawn area: 51%
[16:58:41] [Render thread/INFO]: Time elapsed: 3535 ms
[16:58:42] [Server thread/INFO]: Changing view distance to 2, from 10
[16:58:42] [Server thread/INFO]: Changing simulation distance to 5, from 0
[16:58:43] [Render thread/WARN]: Failed to find a usable hardware address from the network interfaces; using random bytes: 76:17:e8:c3:b7:06:55:29
[16:58:49] [Server thread/INFO]: NoahhStil[local:E:b2a4617d] logged in with entity id 10 at (-50.571576241948584, -63.0, -4.856990875439087)
[16:58:49] [Server thread/INFO]: NoahhStil joined the game
[16:58:50] [Render thread/INFO]: Started 2 worker threads
[16:58:50] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2060ms or 41 ticks behind
[16:58:50] [Render thread/INFO]: Loaded 51 advancements
[16:58:51] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.vsh: Success.

[16:58:51] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.fsh: Success.

[16:58:51] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.vsh: Success.

[16:58:52] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.fsh: Success.

[16:58:52] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.vsh: Success.

[16:58:52] [Render thread/WARN]: Shader compilation log for sodium:blocks/block_layer_opaque.fsh: Success.

--------- beginning of crash
__

### Steps To Reproduce

```markdown
1. start the pojav 
2. entered the world
3. get crashed
```

### Expected Behavior

i expected i can play survival 1.21

### Platform

```markdown
- Device model: Infinix hot 11 play 
- CPU architecture: Octa-core (4x2.3 GHz Cortex-A53 & 4x1.8 GHz Cortex-A53)
- Android version: 13
- PojavLauncher version: foxglove-20240922-a6a6a29-v3_openjdk
```

### Anything else?

sodium 1.21 runtime 21

**Comment by Marshall2439** [comment]
Dude send correct log as a file not text

**Comment by Marshall2439** [comment]
Sodium is causing it. Either remove it, or disable persistent mapping and fog occulsion

**Comment by Yoidiotiamback** [comment]
Sodium is supported using ltw renderer in the actions go down until you see add renderer and compability checks click it downlad select ltw. This renderer gives the fps that you got in gl4es I think so this renderer supports sodium and other various mods

**Comment by TheFantasticLoki** [comment]
> Sodium is supported using ltw renderer in the actions go down until you see add renderer and compability checks click it downlad select ltw. This renderer gives the fps that you got in gl4es I think so this renderer supports sodium and other various mods

Mind explaining step by step how to get to this as I cannot find anything you referenced in PojavLauncher. I see no actions section, no "add renderer and compatibility checks" section and no option for LTW in the select renderer options.

**Comment by Yoidiotiamback** [comment]
Bro this is the website you Added the issue in this website there is a 3 dots box click it select actions and just scroll down and you will see the add renderer and compability checks click it download now downloaded file is marked as app debug click it extract it download the pojavlauncher go to renderer select ltw you could understand right?

**Comment by adr278** [comment]
> > Sodium is supported using ltw renderer in the actions go down until you see add renderer and compability checks click it downlad select ltw. This renderer gives the fps that you got in gl4es I think so this renderer supports sodium and other various mods
> 
> Mind explaining step by step how to get to this as I cannot find anything you referenced in PojavLauncher. I see no actions section, no "add renderer and compatibility checks" section and no option for LTW in the select renderer options.

@TheFantasticLoki they meant this https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158

**Comment by Yoidiotiamback** [comment]
Exactly

**Comment by Muazraza** [comment]
> Bro this is the website you Added the issue in this website there is a 3 dots box click it select actions and just scroll down and you will see the add renderer and compability checks click it download now downloaded file is marked as app debug click it extract it download the pojavlauncher go to renderer select ltw you could understand right?

![Screenshot_20241126_050253_Package installer](https://github.com/user-attachments/assets/9e599802-b7e4-48fc-9e76-a47ba0a36d48)
What should I do???

**Comment by ghost** [comment]
You are download old version of pojav for new versions. Delete pojav and try again

**Comment by Muazraza** [comment]
> You are download old version of pojav for new versions. Delete pojav and try again

I have downloaded the ltw renderer one as they have said
