### ISSUE TITLE
[BUG] feather client cracked not working 

### ISSUE THREAD

**Issue by Emapriya** [PojavLauncherTeam/PojavLauncher#6370]
### Describe the bug

CLIENT
[15:11:04] [main/INFO]: Compatibility level set to JAVA_16
[15:11:04] [main/INFO]: Compatibility level set to JAVA_17
[15:11:09] [Thread-1/INFO]: Feather-Loader for game version 1.20.1
[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Registered forkAndExec
[15:11:09] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'feather-loader' at 'net.digitalingot.loader.chain.ChainEntrypoint'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.9.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'feather-loader' at 'net.digitalingot.loader.chain.ChainEntrypoint'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
Caused by: java.lang.NoSuchMethodError: 'void org.lwjgl.glfw.GLFW.glfwGetMonitorContentScale(long, java.nio.FloatBuffer, java.nio.FloatBuffer)'
	at net.digitalingot.loader.ui.App.init(App.java:87) ~[feather-loader-0.1.0.jar:?]
	at net.digitalingot.loader.ui.App.run(App.java:50) ~[feather-loader-0.1.0.jar:?]
	at net.digitalingot.loader.FeatherEntrypoint.onPreLaunch(FeatherEntrypoint.java:36) ~[feather-loader-0.1.0.jar:?]
	at net.digitalingot.loader.chain.ChainEntrypoint.onPreLaunch(ChainEntrypoint.java:83) ~[feather-standalone-0.2.2.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.kno
t.Knot.init(Knot.java:160) ~[fabric-loader-0.16.9.jar:?]
	... 2 more
[15:11:10] [Thread-1/ERROR]: Unsupported platform! Tried to launch on linux-arm
[15:11:10] [Thread-1/ERROR]: net.digitalingot.loader.error.UnsupportedPlatformException

### The log file and images/videos

Pls tey

### Steps To Reproduce

```markdown
I installed feather client stand alone mod
```

### Expected Behavior

Black screen happen

### Platform

```markdown
- Device model: Vivo v40
- CPU architecture: 
- Android version: 
- PojavLauncher version: before sodium bugs version
```

### Anything else?

I installed feather client stand alone mod from feather client

**Comment by GaucovyAero** [comment]
unsupported
