### ISSUE TITLE
[F-Req] <Short description>pojav bikin seru 

### ISSUE THREAD

**Issue by Branzz655** [PojavLauncherTeam/PojavLauncher#6382]
### Is this request related to a bug?

Asalll

### Describe the request.

Apa

### Anything else?

We

**Comment by Branzz655** [comment]
Assss

**Comment by Branzz655** [comment]
Oy

**Comment by Branzz655** [comment]
Pihak launching

**Comment by Branzz655** [comment]
java.lang.RuntimeException: Bad Request
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.getResponseThrowable(MicrosoftBackgroundLogin.java:351)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireAccessToken(MicrosoftBackgroundLogin.java:152)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:77)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Branzz655** [comment]
#6382

**Comment by Branzz655** [comment]
Pajak bikin seru

**Comment by ImNotTheChiku35** [comment]
wut?

**Comment by GaucovyAero** [comment]
log into minecraft.net or buy minecraft java edition
