### ISSUE TITLE
[BUG] <whenever I add mods the pojavlauncher crashes>

### ISSUE THREAD

**Issue by Zayaan281** [PojavLauncherTeam/PojavLauncher#6386]
### Describe the bug

The mods don't work the latest mods don't work too this is a issue in android 14

### The log file and images/videos

------- Starting game with Launcher Debug!
Info: Launcher version: foxglove-20241124-a5d02c1-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 22111317PI
Info: API version: 33
Info: Selected Minecraft version: 1.19.2-forge-43.4.6
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2400
Added custom env: FORCE_VSYNC=false
Added custom env: POJAV_NATIVEDIR=/data/app/~~QvjPcjPDxpnMxB1vq2w7bA==/net.kdt.pojavlaunch-pTICi_jbAYxtUHbiPYoXbg==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~QvjPcjPDxpnMxB1vq2w7bA==/net.kdt.pojavlaunch-pTICi_jbAYxtUHbiPYoXbg==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1080
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
--------- beginning of main
I/jrelog  (31715): dlopen libgl4es_114.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (31715): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libzip.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libsctp.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjawt.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjimage.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/librmi.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_agent.so success
I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjvm.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/server/libjsig.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/liblcms.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmanagement_ext.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjsig.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libdt_socket.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnet.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjli.so success
I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfreetype.so success
I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_headless.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjdwp.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjavajpeg.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libmlib_image.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libinstrument.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libfontmanager.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libverify.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2pkcs11.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjaas.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libextnet.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libprefs.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libjava.so success
I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libnio.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libj2gss.so success

I/jrelog  (31715): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-17/lib/libawt_xawt.so success

I/jrelog  (31715): dlopen /data/app/~~QvjPcjPDxpnMxB1vq2w7bA==/net.kdt.pojavlaunch-pTICi_jbAYxtUHbiPYoXbg==/lib/arm64/libopenal.so success

I/jrelog  (31715): Done processing args
I/jrelog  (31715): Found JLI lib
I/jrelog  (31715): Calling JLI_Launch

2024-12-16 11:03:31,855 main ERROR appender Console has no parameter that matches element Policies
[11:03:32] [main/INFO]: ModLauncher running: args [--username, itzzayaan, --version, 1.19.2, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 1.19, --uuid, 00000000000000000000000000000000, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 43.4.6, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853]
[11:03:32] [main/INFO]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.14-internal by N/A; OS Linux arch aarch64 version Android-13
Exception in thread "main" cpw.mods.niofs.union.UnionFileSystem$UncheckedIOException: java.nio.file.AccessDeniedException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/mahoutsukai-1.19.2-v1.34.54.jar
Caused by: java.nio.file.AccessDeniedException: /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods/mahoutsukai-1.19.2-v1.34.54.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:313)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:170)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:475)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.openFileSystem(UnionFileSystem.java:112)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:107)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
	at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:66)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
	at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.4.6/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.visitFile(ModDirTransformerDiscoverer.java:61)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.4.6/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.scan(ModDirTransformerDiscoverer.java:50)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.4.6/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.candidates(ModDirTransformerDiscoverer.java:33)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.serviceapi.ITransformerDiscoveryService.candidates(ITransformerDiscoveryService.java:48)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$14(TransformationServicesHandler.java:125)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Java Exit code: 1
I/jrelog  (31715): Going to free args
I/jrelog  (31715): Free done

### Steps To Reproduce

```markdown
1.I added the Mahoutsukai mod for 1.19.2 forge 
2.The Mahoutsukai mod requirements have been added
3.I download forge 1.19.2 
4.I loaded it 
5.The game started and crashed saying game exited with code 1
```

### Expected Behavior

I expect for mods to work again because other mods don't work too 

### Platform

```markdown
- Device model: poco X5 5G 
- CPU architecture:arm64 
- Android version:14 
- PojavLauncher version: foxglove-20241124-a5d02c1-v3_openjdk
```

### Anything else?

This is a unbearable problem

**Comment by GaucovyAero** [comment]
use files by marc to move the files
