### ISSUE TITLE
[BUG] <Short description> Application exited fabric 1.21

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#6396]
### Describe the bug

Fabric 1.21 application exited while starting with some mods. Help pls.

### The log file and images/videos

--------- Starting game with Launcher Debug!
Info: Launcher version: foxglove-20241124-a5d02c1-v3_openjdk
Info: Architecture: arm64
Info: Device model: Xiaomi 23122PCD1I
Info: API version: 34
Info: Selected Minecraft version: fabric-loader-0.16.9-1.21
Info: Custom Java arguments: ""
Added custom env: TMPDIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: AWTSTUB_WIDTH=2712
Added custom env: FORCE_VSYNC=true
Added custom env: POJAV_NATIVEDIR=/data/app/~~Hd-tVD8ifQxGhs5vgBI3Ng==/net.kdt.pojavlaunch-OZCMy_sIclpuoLXd8WZMWw==/lib/arm64
Added custom env: LIBGL_MIPMAP=3
Added custom env: allow_higher_compat_version=true
Added custom env: MESA_GLSL_CACHE_DIR=/data/user/0/net.kdt.pojavlaunch/cache
Added custom env: HOME=/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files
Added custom env: PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/bin:/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin
Added custom env: LIBGL_NOINTOVLHACK=1
Added custom env: force_glsl_extensions_warn=true
Added custom env: LIBGL_NORMALIZE=1
Added custom env: POJAV_VSYNC_IN_ZINK=1
Added custom env: LD_LIBRARY_PATH=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/jli:/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib:/system/lib64:/vendor/lib64:/vendor/lib64/hw:/data/app/~~Hd-tVD8ifQxGhs5vgBI3Ng==/net.kdt.pojavlaunch-OZCMy_sIclpuoLXd8WZMWw==/lib/arm64
Added custom env: LIBGL_NOERROR=1
Added custom env: POJAV_RENDERER=opengles2
Added custom env: LIBGL_ES=2
Added custom env: VTEST_SOCKET_NAME=/data/user/0/net.kdt.pojavlaunch/cache/.virgl_test
Added custom env: MESA_LOADER_DRIVER_OVERRIDE=zink
Added custom env: JAVA_HOME=/data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21
Added custom env: allow_glsl_extension_directive_midshader=true
Added custom env: AWTSTUB_HEIGHT=1220
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_EXT_color_buffer_half_float  detected and used
high precision float in fragment shader available and used
Max vertex attrib: 32
Extension GL_OES_standard_derivatives  detected and used
Extension GL_ARM_shader_framebuffer_fetch detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 16384
Max Varying Vector: 31
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 16
Hardware vendor is Qualcomm
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
sRGB surface supported
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/
java.lang.UnsupportedOperationException
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.makeNonFinal(CTCPreloadClassLoader.java:125)
	at com.github.caciocavallosilano.cacio.ctc.CTCPreloadClassLoader.<clinit>(CTCPreloadClassLoader.java:70)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:2012)
	at java.base/java.lang.System.initPhase3(System.java:2329)
--------- beginning of main
I/jrelog  (  532): dlopen libgl4es_114.so success

I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  (  532): dlopen libjvm.so failed: dlopen failed: library "libjvm.so" not found
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjvm.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so 
success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libzip.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsctp.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjawt.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjimage.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/librmi.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_agent.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtim
es/Internal-21/lib/server/libjvm.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/server/libjsig.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/liblcms.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmanagement_ext.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjsig.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libdt_socket.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnet.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjli.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfreetype.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_headless.so success
I/jrelog  (  532): dl
open /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjdwp.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libsyslookup.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjavajpeg.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libmlib_image.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libinstrument.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libfontmanager.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libverify.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2pkcs11.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjaas.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/
libextnet.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libprefs.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libjava.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libnio.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libj2gss.so success
I/jrelog  (  532): dlopen /data/user/0/net.kdt.pojavlaunch/runtimes/Internal-21/lib/libawt_xawt.so success
I/jrelog  (  532): dlopen /data/app/~~Hd-tVD8ifQxGhs5vgBI3Ng==/net.kdt.pojavlaunch-OZCMy_sIclpuoLXd8WZMWw==/lib/arm64/libopenal.so success

I/jrelog  (  532): Done processing args

I/jrelog  (  532): Found JLI lib
I/jrelog  (  532): Calling JLI_Launch

ERROR StatusConsoleListener appender Console has no parameter that matches element Policies
[23:16:40] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.16.9
[23:16:41] [main/INFO]: Loading 187 mods:
	- animal_feeding_trough 1.1.1+1.21
	- animatica 0.6.1+1.21
	- architectury 13.0.6
	- c2me 0.2.0+alpha.11.100+1.21
	   |-- c2me-base 0.2.0+alpha.11.100+1.21
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.100+1.21
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.100+1.21
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.100+1.21
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.100+1.21
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.100+1.21
	   |-- c2me-notickvd 0.2.0+alpha.11.100+1.21
	   |-- c2me-opts-allocs 0.2.0+alpha.11.100+1.21
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.100+1.21
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.100+1.21
	   |-- c2me-opts-math 0.2.0+alpha.11.100+1.21
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.100+1.21
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.100+1.21
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.100+1.21
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.100+1.21
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.100+1.21
	   |-- c2me-server-utils 0.2.0+alpha.11.100+1.21
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.100+1.21
	   |-- c2me-threading-lighting 0.2.0+alpha.11.100+1.21
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.100+1.21
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cardinal-components 6.1.1
	   |-- cardinal-components-base 6.1.1
	   |-- cardinal-components-block 6.1.1
	   |-- cardinal-components-chunk 6.1.1
	   |-- cardinal-components-entity 6.1.1
	   |-- cardinal-components-item 6.1.1
	   |-- cardinal-components-level 6.1.1
	   |-- cardinal-components-scoreboard 6.1.1
	   \-- cardinal-components-world 6.1.1
	- cloth-config 15.0.127
	   \-- cloth-basic-math 0.6.1
	- clumps 18.0.0.1
	- cobweb 1.1.2
	- connectiblechains 2.4.1+1.21
	- continuity 3.0.0-beta.5+1.21
	- craftsaddles 1.0.1
	- dark-loading-screen 1.6.14
	- dynamic_fps 3.6.0
	   \-- net_lostluma_battery 1.0.1
	- easymagic 21.0.1
	- enhancedblockentities 0.10.1+1.21
	- entityculling 1.6.6
	- fabric-api 0.100.8+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
	   |-- fabric-biome-api-v1 13.0.29+5bd9f1bcd1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.15+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.18+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.4.2+c111832ad1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.25+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.13+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.3+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   |-- fabric-loot-api-v2 3.0.13+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.1+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.13+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10+65089712d1
	   |-- fabric-registry-sync-v0 5.0.26+a5d66753d1
	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.71+df3654b3d1
	   |-- fabric-rendering-v1 5.0.5+df16efd0d1
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
	   |-- fabric-resource-loader-v0 1.2.0+7e687b32d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.83+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- fabricskyboxes 0.7.4+mc1.21
	- fabrictailor 2.5.0
	   |-- config2brigadier 1.2.3
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- fallingleaves 1.16.0
	- ferritecore 7.0.0
	- forgeconfigapiport 21.0.1
	   |-- com_electronwill_night-config_core 3.7.4
	   \-- com_electronwill_night-config_toml 3.7.4
	- fwaystones 3.3.3+mc1.21
	   \-- owo-sentinel 0.12.10+1.21
	- gammautils 1.9.20
	- guardvillagers 2.1.2-1.21
	- hangglider 21.0.0
	- immediatelyfast 1.2.18+1.21
	   \-- net_lenni0451_reflect 1.3.4
	- iris 1.7.1+mc1.21
	   |-- io_github_douira_glsl-transformer 2.0.1
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.13.1
	- jamlib 1.0.11+1.21
	   \-- blue_endless_jankson 1.2.3
	- java 21
	- jumpoverfences 1.6.0
	- lambdynlights 3.0.1+1.21.1
	   |-- pride 1.2.1+1.21
	   \-- spruceui 5.1.0+1.21
	- lazy-language-loader 0.3.7
	- lithium 0.12.7
	- malilib 0.18.9999-sakura.1
	- midnightlib 1.5.7
	- minecraft 1.21
	- modernfix 5.18.2+mc1.21
	- modmenu 11.0.1
	- mousetweaks 2.26
	- mr_villager_transportation 1.3.1
	- no_fog 1.3.6+1.16.5-1.21
	- notenoughanimations 1.7.4
	- puzzleslib 21.0.15
	- reeses-sodium-options 1.7.2+mc1.21
	- rightclickharvest 4.3.1+1.21
	- smallships 2.0.0-b1.3.4
	- sodium 0.5.9+mc1.21
	- sodium-extra 0.5.7+mc1.21
	   \-- caffeineconfig 1.3.0+1.17
	- torch_hit 7.0.0
	- trade_cycling 1.21-1.0.13
	- travelersbackpack 10.1.2
	- ukulib 1.4.0+1.21
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- universal-graves 3.4.2+1.21
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.4.1+1.21
	   |-- polymer-core 0.9.7+1.21
	   |    |-- polymer-networking 0.9.7+1.21
	   |    |    \-- polymer-common 0.9.7+1.21
	   |    |         \-- packet_tweaker 0.5.5+1.21
	   |    \-- polymer-registry-sync-manipulator 0.9.7+1.21
	   |-- polymer-resource-pack 0.9.7+1.21
	   |    \-- polymer-common 0.9.7+1.21
	   |         \-- packet_tweaker 0.5.5+1.21
	   |-- polymer-virtual-entity 0.9.7+1.21
	   |    \-- polymer-common 0.9.7+1.21
	   |         \-- packet_tweaker 0.5.5+1.21
	   |-- predicate-api 0.5.1+1.21
	   |-- server_translations_api 2.3.1+1.21-pre2
	   \-- sgui 1.6.0+1.21
	- xaerominimap 24.5.0
	- yet_another_config_lib_v3 3.5.0+1.21-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zoomify 2.14.0+1.21
	   \-- com_akuleshov7_ktoml-core-jvm 0.5.1
[23:16:41] [main/ERROR]: Error thrown while opening sentinel! Exiting
javax.swing.UnsupportedLookAndFeelException: [GTK look and feel - com.sun.java.swing.plaf.gtk.GTKLookAndFeel] not supported on this platform
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:578) ~[?:?]
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:637) ~[?:?]
	at knot/io.wispforest.owosentinel.SentinelWindow.open(SentinelWindow.java:22) ~[owo-sentinel-0.12.10+1.21-220d742747126f97.jar:?]
	at knot/io.wispforest.owosentinel.OwoSentinel.launch(OwoSentinel.java:45) [owo-sentinel-0.12.10+1.21-220d742747126f97.jar:?]
	at knot/io.wispforest.owosentinel.Maldenhagen.<clinit>(Maldenhagen.java:13) [owo-sentinel-0.12.10+1.21-220d742747126f97.jar:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) [?:?]
	at java.base/java.lang.Class.forName(Class.java:513) [?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:488) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:367) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:116) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:147) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClie
![Screenshot_2024-12-18-23-34-40-516_net kdt pojavlaunch](https://github.com/user-attachments/assets/5401010f-3751-4e1c-bc19-16e740053e0f)
n

### Steps To Reproduce

```markdown
...
```

### Expected Behavior

I expect to be able to play without getting application exited.

### Platform

```markdown
- Device model: Poco X6 5g
- CPU architecture: arm64, Snapdragon 7s gen2, Adreno 710 GPU
- Android version: 14
- PojavLauncher version: 1.21
```

**Comment by ghost** [comment]
I was missing one lib known as owo sentinel lib that was the prob
