### ISSUE TITLE
[BUG] Crashes on opening shaders after 1.21.1

### ISSUE THREAD

**Issue by HenryLogic** [PojavLauncherTeam/PojavLauncher#6408]
### Describe the bug

I use Optifine edition, and shaders worked fine on 1.21.1 and previous minecraft editions. But on minecraft 1.21.3 and 1.21.4, everytime when I join a world with shaders, pojav launcher will crash and exit. The shader is bsl 8.4. (I also try several other shaders, it also will cause crashes.)

### The log file and images/videos

```
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:397)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.a(MultiBufferSource.java:130)
	at glz$a.b(MultiBufferSource.java:141)
	at glt.a(ItemInHandRenderer.java:399)
	at net.optifine.shaders.ShadersRender.renderItemFP(ShadersRender.java:262)
	at glq.renderHand(GameRenderer.java:597)
	at net.optifine.shaders.ShadersRender.renderHand0(ShadersRender.java:201)
	at glv.lambda$addMainPass$1(LevelRenderer.java:1082)
	at fdz.a(SourceFile:67)
	at glv.a(LevelRenderer.java:829)
	at glq.a(GameRenderer.java:1050)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="fen" timestamp="1735027565867" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:398)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.a(MultiBufferSource.java:130)
	at glz$a.b(MultiBufferSource.java:141)
	at glt.a(ItemInHandRenderer.java:399)
	at net.optifine.shaders.ShadersRender.renderItemFP(ShadersRender.java:262)
	at glq.renderHand(GameRenderer.java:597)
	at net.optifine.shaders.ShadersRender.renderHand0(ShadersRender.java:201)
	at glv.lambda$addMainPass$1(LevelRenderer.java:1082)
	at fdz.a(SourceFile:67)
	at glv.a(LevelRenderer.java:829)
	at glq.a(GameRenderer.java:1050)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="fen" timestamp="1735027565868" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:399)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.a(MultiBufferSource.java:130)
	at glz$a.b(MultiBufferSource.java:141)
	at glt.a(ItemInHandRenderer.java:399)
	at net.optifine.shaders.ShadersRender.renderItemFP(ShadersRender.java:262)
	at glq.renderHand(GameRenderer.java:597)
	at net.optifine.shaders.ShadersRender.renderHand0(ShadersRender.java:201)
	at glv.lambda$addMainPass$1(LevelRenderer.java:1082)
	at fdz.a(SourceFile:67)
	at glv.a(LevelRenderer.java:829)
	at glq.a(GameRenderer.java:1050)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="fen" timestamp="1735027565869" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:400)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.a(MultiBufferSource.java:130)
	at glz$a.b(MultiBufferSource.java:141)
	at glt.a(ItemInHandRenderer.java:399)
	at net.optifine.shaders.ShadersRender.renderItemFP(ShadersRender.java:262)
	at glq.renderHand(GameRenderer.java:597)
	at net.optifine.shaders.ShadersRender.renderHand0(ShadersRender.java:201)
	at glv.lambda$addMainPass$1(LevelRenderer.java:1082)
	at fdz.a(SourceFile:67)
	at glv.a(LevelRenderer.java:829)
	at glq.a(GameRenderer.java:1050)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="net.optifine.shaders.SMCLog" timestamp="1735027565871" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[[Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_hand, at: modelViewMatrix]]></log4j:Message>
  </log4j:Event>
  <log4j:Event logger="fen" timestamp="1735027567174" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:397)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.getBuffer(MultiBufferSource.java:107)
	at gtd.a(ItemRenderer.java:98)
	at gwe.a(EquipmentLayerRenderer.java:71)
	at gwe.a(EquipmentLayerRenderer.java:48)
	at gwj.a(SourceFile:61)
	at gwj.a(SourceFile:45)
	at gwj.a(SourceFile:14)
	at gtg.a(LivingEntityRenderer.java:178)
	at gtg.a(LivingEntityRenderer.java:46)
	at gsd.a(EntityRenderDispatcher.java:204)
	at gsd.a(EntityRenderDispatcher.java:179)
	at glv.a(LevelRenderer.java:1603)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:536)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:5001)
	at glq.a(GameRenderer.java:979)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="fen" timestamp="1735027567176" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:398)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.getBuffer(MultiBufferSource.java:107)
	at gtd.a(ItemRenderer.java:98)
	at gwe.a(EquipmentLayerRenderer.java:71)
	at gwe.a(EquipmentLayerRenderer.java:48)
	at gwj.a(SourceFile:61)
	at gwj.a(SourceFile:45)
	at gwj.a(SourceFile:14)
	at gtg.a(LivingEntityRenderer.java:178)
	at gtg.a(LivingEntityRenderer.java:46)
	at gsd.a(EntityRenderDispatcher.java:204)
	at gsd.a(EntityRenderDispatcher.java:179)
	at glv.a(LevelRenderer.java:1603)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:536)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:5001)
	at glq.a(GameRenderer.java:979)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="fen" timestamp="1735027567178" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:399)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.getBuffer(MultiBufferSource.java:107)
	at gtd.a(ItemRenderer.java:98)
	at gwe.a(EquipmentLayerRenderer.java:71)
	at gwe.a(EquipmentLayerRenderer.java:48)
	at gwj.a(SourceFile:61)
	at gwj.a(SourceFile:45)
	at gwj.a(SourceFile:14)
	at gtg.a(LivingEntityRenderer.java:178)
	at gtg.a(LivingEntityRenderer.java:46)
	at gsd.a(EntityRenderDispatcher.java:204)
	at gsd.a(EntityRenderDispatcher.java:179)
	at glv.a(LevelRenderer.java:1603)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:536)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:5001)
	at glq.a(GameRenderer.java:979)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="fen" timestamp="1735027567179" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[OpenGL API ERROR: 1 (GL_INVALID_OPERATION in glVertexAttribPointer(non-VBO array))]]></log4j:Message>
    <log4j:Throwable><![CDATA[java.lang.Exception: Stack trace
	at org.lwjgl.opengl.GL20C.nglVertexAttribPointer(Native Method)
	at org.lwjgl.opengl.GL20C.glVertexAttribPointer(GL20C.java:1892)
	at org.lwjgl.opengl.GL20.glVertexAttribPointer(GL20.java:2089)
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:400)
	at ffy.a(VertexBuffer.java:318)
	at ffr.a(BufferUploader.java:33)
	at gmj.a(RenderType.java:834)
	at glz$a.a(MultiBufferSource.java:186)
	at glz$a.a(MultiBufferSource.java:163)
	at glz$a.getBuffer(MultiBufferSource.java:107)
	at gtd.a(ItemRenderer.java:98)
	at gwe.a(EquipmentLayerRenderer.java:71)
	at gwe.a(EquipmentLayerRenderer.java:48)
	at gwj.a(SourceFile:61)
	at gwj.a(SourceFile:45)
	at gwj.a(SourceFile:14)
	at gtg.a(LivingEntityRenderer.java:178)
	at gtg.a(LivingEntityRenderer.java:46)
	at gsd.a(EntityRenderDispatcher.java:204)
	at gsd.a(EntityRenderDispatcher.java:179)
	at glv.a(LevelRenderer.java:1603)
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:536)
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:5001)
	at glq.a(GameRenderer.java:979)
	at glq.a(GameRenderer.java:693)
	at flk.c(SourceFile:1341)
	at flk.f(SourceFile:922)
	at net.minecraft.client.main.Main.main(SourceFile:267)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
]]></log4j:Throwable>
  </log4j:Event>
  <log4j:Event logger="net.optifine.shaders.SMCLog" timestamp="1735027567181" level="ERROR" thread="Render thread">
    <log4j:Message><![CDATA[[Shaders] OpenGL error: 1282 (Invalid operation), program: shadow, at: modelViewMatrix]]></log4j:Message>
  </log4j:Event>
--------- beginning of crash
```

full version of the latest.log:
[latestlog.txt](https://github.com/user-attachments/files/18238685/latestlog.txt)

### Steps To Reproduce

```markdown
Joining the world with shaders on, pojav launcher will crash and exit.

Joining the world with shaders off, pojav launcher works normally. But turning shaders on will make pojav launcher crash and exit.
```

### Expected Behavior

I wish I can play the game with shaders on minecraft 1.21.4.

### Platform

```markdown
- Device model: Redmi K20 Pro
- CPU architecture: arm64
- Android version: 10
- PojavLauncher version: foxglove-20240909-366f181-v3_openjdk
```

### Anything else?

nothing.

**Comment by GaucovyAero** [comment]
might get fixed in a zink update later
