### ISSUE TITLE
Minecraft download failed

### ISSUE THREAD

**Issue by tarnacop** [PojavLauncherTeam/PojavLauncher#6430]
### Describe the bug

i wanted to instal 1.11 forge version and it's showing me this
Minecraft download failed! This could be due to incorrect network connection, incorrectly placed files, etc. My network works fine

### The log file and images/videos

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 154 column 1 path $.libraries[19].
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadAndProcessMetadata(MinecraftDownloader.java:223)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.downloadGame(MinecraftDownloader.java:97)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader.lambda$start$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader(MinecraftDownloader.java:67)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 154 column 1 path $.libraries[19].
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:514)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 10 more

### Steps To Reproduce

```markdown
1. start pojav
2. try to install version 1.11
3. get the mentioned error
```

### Expected Behavior

I expect to fix this.

### Platform

```markdown
- Device model: Motorola edge 30 neo 8/256G
- CPU architecture: Octa-core (2x2.2 GHz Kryo 660 Gold & 6x1.7 GHz Kryo 660 Silver)
- Android version:14
- PojavLauncher version: foxglove-20241230-5d80d9b-v3_openjdk
```

### Anything else?

nothing yet

**Comment by GaucovyAero** [comment]
seems like the forge devs did an oopsie when making the json for 1.11, heres a guide on how to fix it


https://github.com/user-attachments/assets/2a98faef-16df-48e7-bdf7-5e9cd70d1b86

**Comment by tarnacop** [comment]
thanks:)
