### ISSUE TITLE
When I try to play a 1.16.4 world with v-1.16.4 or optifine 1.16.4 this happens

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#645]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/18/21 8:44 AM
Description: Registering texture

java.lang.SecurityException: SHA-256 digest error for assets/minecraft/textures/entity/steve.png
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:223)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:243)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:484)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at dex.a(SourceFile:98)
	at det.a(SourceFile:97)
	at det.a(SourceFile:90)
	at ejy$a.a(SourceFile:82)
	at ejy.b(SourceFile:57)
	at ejy.a(SourceFile:28)
	at ekd.c(SourceFile:96)
	at ekd.a(SourceFile:68)
	at ekd.d(SourceFile:61)
	at ekd.a(SourceFile:51)
	at eac.a(SourceFile:297)
	at eac.a(SourceFile:414)
	at eac.a(SourceFile:395)
	at dzz.a(SourceFile:483)
	at dzz.a(SourceFile:753)
	at dzz.a(SourceFile:546)
	at djz.e(SourceFile:1048)
	at djz.e(SourceFile:681)
	at net.minecraft.client.main.Main.main(SourceFile:215)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:223)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:243)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:484)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at dex.a(SourceFile:98)
	at det.a(SourceFile:97)
	at det.a(SourceFile:90)
	at ejy$a.a(SourceFile:82)
	at ejy.b(SourceFile:57)
	at ejy.a(SourceFile:28)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/entity/steve.png
	Texture object class: ejy
Stacktrace:
	at ekd.c(SourceFile:96)
	at ekd.a(SourceFile:68)
	at ekd.d(SourceFile:61)
	at ekd.a(SourceFile:51)
	at eac.a(SourceFile:297)
	at eac.a(SourceFile:414)
	at eac.a(SourceFile:395)
	at dzz.a(SourceFile:483)
	at dzz.a(SourceFile:753)

-- Affected level --
Details:
	All players: 1 total; [dzm['ChargedHat42838'/68, l='ClientLevel', x=63.70, y=75.00, z=271.64]]
	Chunk stats: Client Chunk Cache: 441, 108
	Level dimension: minecraft:overworld
	Level spawn location: World: (160,71,96), Chunk: (at 0,4,0 in 10,6; contains blocks 160,0,96 to 175,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 129321 game time, 1001 day time
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at dwt.a(SourceFile:449)
	at djz.c(SourceFile:2239)
	at djz.e(SourceFile:699)
	at net.minecraft.client.main.Main.main(SourceFile:215)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2375910664 bytes (2265 MB) / 3355443200 bytes (3200 MB) up to 3355443200 bytes (3200 MB)
	CPUs: 8
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xms3185M -Xmx3185M
	Launched Version: 1.16.4
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	GPU Warnings: version: 2.1
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 9x null
This happens.

**Comment by khanhduytran0** [comment]
Delete META-INF after modify any files inside .jar file.
