### ISSUE TITLE
Can we join a server ?

### ISSUE THREAD

**Issue by Siiphanopas02** [PojavLauncherTeam/PojavLauncher#66]
I wan't to know, can we join server because when i wan't to do it in 1.9 "Disconnected" and in the console "INFO bei Connecting to funcraft.net, 25565
(HTTPLog)-Static: isSBSettingEnabled false
(HTTPLog)-Static: isSBSettingEnabled false"
So, i wait your answer.
Goodbye

**Comment by matteobranchi** [comment]
> I wan't to know, can we join server because when i wan't to do it in 1.9 "Disconnected" and in the console "INFO bei Connecting to funcraft.net, 25565
> (HTTPLog)-Static: isSBSettingEnabled false
> (HTTPLog)-Static: isSBSettingEnabled false"
> So, i wait your answer.
> Goodbye

You can't join premium servers for now.
You can only join LAN multiplayer or SP (cracked) servers

**Comment by Siiphanopas02** [comment]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 06/04/2020 11:01
Description: Rendering Block Entity

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bwn.a(SourceFile:126)
	at bpu.a(SourceFile:81)
	at bpu.a(SourceFile:43)
	at bpu.a(SourceFile:22)
	at bpm.a(SourceFile:124)
	at bpm.a(SourceFile:112)
	at bno.a(SourceFile:659)
	at bng.a(SourceFile:1260)
	at bng.b(SourceFile:1165)
	at bng.a(SourceFile:1012)
	at bcf.av(SourceFile:985)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:856)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.getTextures(YggdrasilMinecraftSessionService.java:137)
	at bwn$1.a(SourceFile:47)
	at bwn$1.load(SourceFile:44)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
	at bwn.a(SourceFile:126)
	at bpu.a(SourceFile:81)
	at bpu.a(SourceFile:43)

-- Block Entity Details --
Details:
	Name: Skull // aqo
	Block type: ID #144 (tile.skull // aok)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-87,74,217), Chunk: (at 9,4,9 in -6,13; contains blocks -96,0,208 to -81,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #144 (tile.skull // aok)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at b.a(SourceFile:244)
	at bpm.a(SourceFile:127)
	at bpm.a(SourceFile:112)
	at bno.a(SourceFile:659)
	at bng.a(SourceFile:1260)
	at bng.b(SourceFile:1165)
	at bng.a(SourceFile:1012)
	at bcf.av(SourceFile:985)
	at bcf.a(SourceFile:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:856)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [bmt['PinnedTweet'/9654, l='MpServer', x=-79,50, y=79,19, z=182,50], bmu['NicolasSharkosis'/9655, l='MpServer', x=-79,50, y=80,00, z=182,50]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (333,64,520), Chunk: (at 13,4,8 in 20,32; contains blocks 320,0,512 to 335,255,527), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 16546117 game time, 16692973 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 4 total; [bmt['PinnedTweet'/9654, l='MpServer', x=-79,50, y=79,19, z=182,50], bmu['adan2708'/9653, l='MpServer', x=-79,50, y=79,19, z=182,50], bmu['NicolasSharkosis'/9655, l='MpServer', x=-79,50, y=80,00, z=182,50], bmu['NicolasSharkosis'/9655, l='MpServer', x=-79,50, y=80,00, z=182,50]]
	Retry entities: 0 total; []
	Server brand: Flamecord (0.1.4 SNAPSHOT) <- Spigot
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 4.14.62-17428643
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-A505F [Android 28]), The Android Project
	Memory: 2726392 bytes (2 MB) / 283852896 bytes (270 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x ARMv8 Processor rev 4 (v8l)


When i join a server i check another server.

**Comment by artdeell** [comment]
That problem exists on servers witk SkinsRestorer.

**Comment by khanhduytran0** [comment]
This error because Android Apache Library do not support `decodeBase64` and `encodeBase64` method. Since Android 6 ~ 7, built-in Apache Library was removed. So it load full Apache Library of the launcher and no the same error on Android 6~7 and above.

**Comment by khanhduytran0** [comment]
> I wan't to know, can we join server because when i wan't to do it in 1.9 "Disconnected" and in the console "INFO bei Connecting to funcraft.net, 25565
> (HTTPLog)-Static: isSBSettingEnabled false
> (HTTPLog)-Static: isSBSettingEnabled false"
> So, i wait your answer.
> Goodbye 
> 

Because RSA Padding which can't be fixed.

`wontfix` in v2.x

**Comment by khanhduytran0** [comment]
Try v3
