### ISSUE TITLE
Account bug

### ISSUE THREAD

**Issue by davidii12** [PojavLauncherTeam/PojavLauncher#664]
When I try to log in with my Microsoft Account it says:
java.lang.RuntimeException: Error 400: {
  "path" : "/minecraft/profile",
  "errorType" : "BAD_REQUEST",
  "error" : "BAD_REQUEST",
  "errorMessage" : "Bad Request",
  "developerMessage" : "Bad Request"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.checkMcProfile(MicrosoftAuthenticator.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.doInBackground(MicrosoftAuthenticator.java:69)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthenticator.doInBackground(MicrosoftAuthenticator.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

1. Start PojavLauncher
2.Microsoft login
3.the error

I expected that it logged in with my Microsoft Account and I could play Minecraft premium 

**Platform:**
 - Device Model Oneplus 6
 - CPU architecture architectur 64
 - Android Version 10

I already have bought a Minecraft Java edition Account on their website and I can play on my Laptop on servers etc.
But my laptop is a potato and my phone is better than it.

**Comment by bubbelbadHD** [comment]
Have you bought the launcher from official website or a cracked launcher

**Comment by bubbelbadHD** [comment]
You have to buy frome official site

**Comment by bubbelbadHD** [comment]
I also had the same issue some people gave me solution of it see here:https://github.com/PojavLauncherTeam/PojavLauncher/issues/632

**Comment by davidii12** [comment]
That's not the same

**Comment by davidii12** [comment]
But thanks for the help

**Comment by khanhduytran0** [comment]
Buy Minecraft or login on offline mode.

**Comment by khanhduytran0** [comment]
Update to latest build.

**Comment by Mathias-Boulay** [comment]
Stale issue, and people that bought the game are able to login without issues on the google play version.
Closing it.

**Comment by AndreCodin24** [comment]
I think you need a Xbox Game Pass.

**Comment by zkitefly** [comment]
https://github.com/PojavLauncherTeam/PojavLauncher/issues/5370 ？
