### ISSUE TITLE
when i open the game it just crashed and gave me this error

### ISSUE THREAD

**Issue by screepai** [PojavLauncherTeam/PojavLauncher#67]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 06/04/2020 18:01
Description: Initializing game

java.lang.IllegalStateException: Shutdown in progress
	at java.io.DeleteOnExitHook.add(DeleteOnExitHook.java:53)
	at java.io.File.deleteOnExit(File.java:1079)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:65)
	at org.apache.harmony.x.imageio.spi.InputStreamIISSpi.createInputStreamInstance(InputStreamIISSpi.java:52)
	at javax.imageio.spi.ImageInputStreamSpi.createInputStreamInstance(ImageInputStreamSpi.java:129)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:138)
	at javax.imageio.ImageIO.read(ImageIO.java:432)
	at bcf.a(SourceFile:813)
	at bcf.an(SourceFile:451)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:856)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.io.DeleteOnExitHook.add(DeleteOnExitHook.java:53)
	at java.io.File.deleteOnExit(File.java:1079)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:65)
	at org.apache.harmony.x.imageio.spi.InputStreamIISSpi.createInputStreamInstance(InputStreamIISSpi.java:52)
	at javax.imageio.spi.ImageInputStreamSpi.createInputStreamInstance(ImageInputStreamSpi.java:129)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:138)
	at javax.imageio.ImageIO.read(ImageIO.java:432)
	at bcf.a(SourceFile:813)

-- Initialization --
Details:
Stacktrace:
	at b.a(SourceFile:244)
	at bcf.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:856)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 3.18.14-14381225-QB21144449
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-G610F [Android 27]), The Android Project
	Memory: 22257216 bytes (21 MB) / 114099408 bytes (108 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by khanhduytran0** [comment]
Try run again.

**Comment by screepai** [comment]
now it gave me this error


---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 06/04/2020 18:13
Description: Registering texture

java.lang.IllegalStateException: Shutdown in progress
	at java.io.DeleteOnExitHook.add(DeleteOnExitHook.java:53)
	at java.io.File.deleteOnExit(File.java:1079)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:65)
	at org.apache.harmony.x.imageio.spi.InputStreamIISSpi.createInputStreamInstance(InputStreamIISSpi.java:52)
	at javax.imageio.spi.ImageInputStreamSpi.createInputStreamInstance(ImageInputStreamSpi.java:129)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:138)
	at javax.imageio.ImageIO.read(ImageIO.java:432)
	at bvk.a(SourceFile:377)
	at bvd.a(SourceFile:29)
	at bvi.a(SourceFile:56)
	at bvi.a(SourceFile:38)
	at bct.<init>(SourceFile:61)
	at bcf.an(SourceFile:463)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:856)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.io.DeleteOnExitHook.add(DeleteOnExitHook.java:53)
	at java.io.File.deleteOnExit(File.java:1079)
	at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:65)
	at org.apache.harmony.x.imageio.spi.InputStreamIISSpi.createInputStreamInstance(InputStreamIISSpi.java:52)
	at javax.imageio.spi.ImageInputStreamSpi.createInputStreamInstance(ImageInputStreamSpi.java:129)
	at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:138)
	at javax.imageio.ImageIO.read(ImageIO.java:432)
	at bvk.a(SourceFile:377)

**Comment by khanhduytran0** [comment]
Try run again and again, now i will **fix?**

**Comment by screepai** [comment]
dunno man i just try again and its still gave me a initializing game error

**Comment by screepai** [comment]
this initializing game error is different from the old one




---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 06/04/2020 18:19
Description: Initializing game

java.lang.IllegalStateException: Only one LWJGL context may be instantiated at any one time.
	at org.lwjgl.opengl.Display.create(Unknown Source:27)
	at org.lwjgl.opengl.Display.create(Unknown Source:11)
	at bcf.ap(SourceFile:581)
	at bcf.an(SourceFile:430)
	at bcf.a(SourceFile:377)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:856)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.opengl.Display.create(Unknown Source:27)
	at org.lwjgl.opengl.Display.create(Unknown Source:11)
	at bcf.ap(SourceFile:581)

-- Initialization --
Details:
Stacktrace:
	at b.a(SourceFile:244)
	at bcf.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:856)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Linux (armv8l) version 3.18.14-14381225-QB21144449
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (samsung SM-G610F [Android 27]), The Android Project
	Memory: 23344520 bytes (22 MB) / 125543992 bytes (119 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.9
	LWJGL: 2.9.1
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: Attempt to invoke virtual method 'bwp bwq.c()' on a null object reference
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by khanhduytran0** [comment]
Force close

**Comment by screepai** [comment]
nope still the same initializing game error

**Comment by screepai** [comment]
![Screenshot_20200406-184726_PojavLauncher (Minecraft Java Edition for Android)](https://user-images.githubusercontent.com/47375966/78555413-2c4d0180-7837-11ea-96af-07c463b805ec.jpg)
i just tried again and i accidentally active the floating windows mode andddd its somehow works

**Comment by artdeell** [comment]
Try to disable freeform mode.
Go to Options -> Settings -> Disable thr "u can find dat switch manually" switch.

**Comment by screepai** [comment]
ok so it still gave me that initializing game error but i tried to install vmos and it works

**Comment by khanhduytran0** [comment]
Try v3
