### ISSUE TITLE
Minecraft 1.11/1.11.2 With Optifine on Android 8.1

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#70]
I tried Minecraft 1.11/1.11.2 with optifine and it doesn't even work but i have launcher_profiles.json

**Comment by khanhduytran0** [comment]
Did you do all steps in https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine ?

### Since OptiFine MC 1.9, a file called `launchwrapper-of-2.1.jar` cause error unable to launch. Simply fix by [follow the video](https://m.youtube.com/watch?v=eIawM9UmQ88&list=PLPh5XtVV87oZYkAgl1nF_cIpb_cA0lp1p&t=274s) or do actions as below:
 - Open file `/sdcard/games/minecraft/libraries/optifine/OptiFine/{version_of_optifine}/OptiFine{version_of_optifine}.jar`
 - Extract a file called `launchwrapper-of-2.1.jar` to path `/sdcard/games/minecraft/libraries/optifine/launchwrapper-of/2.1/`.

**Comment by GeraldBalingcasag** [comment]
In sdcard/games/minecraft/libraries/optifine/OptiFine says its empty

**Comment by GeraldBalingcasag** [comment]
It failed to run it said

---- Minecraft Crash Report ----
// My bad.

Time: 08/04/2020 1:41 pm
Description: Initializing game

java.lang.NullPointerException: Attempt to invoke virtual method 'cbe cbh.bakeModel(brg, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)
	at beq.an(SourceFile:516)
	at beq.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:822)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:784)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:338)
	at beq.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:822)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:596)
	at java.lang.Thread.run(Thread.java:784)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Linux (armv8l) version 4.9.117+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (HUAWEI MRD-LX2), The Android Project
	Memory: 24608536 bytes (23 MB) / 133516936 bytes (127 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.11-OptiFine_HD_U_F5
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer, OpenGL 1.4
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 5x ARMv8 Processor rev 4 (v8l)
	OptiFine Version: OptiFine_1.11_HD_U_F5
	OptiFine Build: 20191204-142752
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 4

**Comment by khanhduytran0** [comment]
This error happend on some devices.

**Comment by khanhduytran0** [comment]
Oh most of they are `HUAWEI`???

**Comment by khanhduytran0** [comment]
> I tried Minecraft 1.11/1.11.2 with optifine and it doesn't even work but i have launcher_profiles.json

Did you follow steps in link?

**Comment by khanhduytran0** [comment]
Try v3
