### ISSUE TITLE
[BUG] in Microsoft login

### ISSUE THREAD

**Issue by Iarkont** [PojavLauncherTeam/PojavLauncher#727]
java.lang.RuntimeException: Can't login a demo account!

MSA Error: 404: Not Found, error stream:
{
  "path" : "/minecraft/profile",
  "errorType" : "NOT_FOUND",
  "error" : "NOT_FOUND",
  "errorMessage" : "The server has not found anything matching the request URI",
  "developerMessage" : "The server has not found anything matching the request URI"
}
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.throwResponseError(Msa.java:312)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.checkMcProfile(Msa.java:276)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireMinecraftToken(Msa.java:208)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXsts(Msa.java:175)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireXBLToken(Msa.java:130)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.acquireAccessToken(Msa.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.Msa.<init>(Msa.java:44)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:71)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftAuthTask.doInBackground(MicrosoftAuthTask.java:21)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

**Comment by artdeell** [comment]
See the start of the error?
You need to buy Minecraft to use this feature

**Comment by Minecraft855** [comment]
Why

**Comment by RenielKun** [comment]
Awts :<

**Comment by NotStolenTotally** [comment]
> See the start of the error?
> You need to buy Minecraft to use this feature

bruh ;/

**Comment by pro-gam** [comment]
bug is coming in Microsoft login

**Comment by pro-gam** [comment]
how to buy it

**Comment by xinzion123** [comment]
I can't login

**Comment by WesleyVanNeck** [comment]
`: Can't login a demo account!`

**Comment by Hieu1981** [comment]
is there any way to fix it?

**Comment by Jaspher25** [comment]
Hello how can I fix it

**Comment by InfiniXDerg** [comment]
> Hello how can I fix it

https://www.minecraft.net/es-es/store/minecraft-java-edition

**Comment by Corisz** [comment]
Whyy

**Comment by Rahim829** [comment]
Colm

**Comment by Rahim829** [comment]
Jlf

**Comment by khanhduytran0** [comment]
@Minecraft855 @pro-gam @xinzion123 @Hieu1981 @Jaspher25 @Corisz the Microsoft Login button is designed for people who <ins>bought the game, redeemed from a gift code or migrated from a Mojang account</ins>. *Imagine expecting for a free premium access worth of $26.95*

**Comment by khanhduytran0** [comment]
> *Imagine expecting for a free premium access worth of $26.95*

And yes, you can’t use your Minecraft Bedrock account (Xbox account) ~~which can be easily pirated.apk mediafire xbox login working 101%~~ for Minecraft Java “premium” access (such as able to change skin, cape, join “premium” servers)

**Comment by T0NI33** [comment]
> @Minecraft855 @pro-gam @xinzion123 @Hieu1981 @Jaspher25 @Corisz the Microsoft Login button is designed for people who bought the game, redeemed from a gift code or migrated from a Mojang account. _Imagine expecting for a free premium access worth of $26.95_

I am having the same error but it was only after I just migrated my already owned copy of java edition to my microsoft account. My account still works on my computer but I can't log into pojav without getting the same error. All everyone has said was "just buy minecraft" though I have it

**Comment by InfiniXDerg** [comment]
> how to buy it

Buying It? :trollface:

**Comment by ghost** [comment]
https://www.minecraft.net/en-us/get-minecraft

**Comment by Mystery3589** [comment]
How to login with a Microsoft account

**Comment by Mystery3589** [comment]
I can't login with my Microsoft account

**Comment by GaucovyAero** [comment]
> I can't login with my Microsoft account

try logging into minecraft.net first
