### ISSUE TITLE
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

### ISSUE THREAD

**Issue by yejunjie10311031** [PojavLauncherTeam/PojavLauncher#751]
When I use Pojavlauncher to launch Mineceaft1.12.2impact modpack,it will crash after appear the interface of "MoJang"(it works well on 1.12.2 and forge1.12.2，but now I want to hack a serve and have to use 1.12.2impact)
There is the crash-report:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/28/21 4:13 PM
Description: Initializing game

java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at net.impactclient.1z.<init>(1z.java:25)
	at net.impactclient.0rz.<init>(0rz.java:49)
	at net.impactclient.99.<init>(99.java:208)
	at net.impactclient.3V.1(3V.java:34)
	at net.impactclient.0ay.2(0ay.java:69)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at net.impactclient.1z.<init>(1z.java:25)
	at net.impactclient.0rz.<init>(0rz.java:49)
	at net.impactclient.99.<init>(99.java:208)
	at net.impactclient.3V.1(3V.java:34)
	at net.impactclient.0ay.2(0ay.java:69)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1941833016 bytes (1851 MB) / 2193096704 bytes (2091 MB) up to 2193096704 bytes (2091 MB)
	JVM Flags: 3 total; -Xcheck:jni -Xms2182M -Xmx2182M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by yejunjie10311031** [comment]
Sorry for bad English,I'm not sure if my grammar is wrong.

**Comment by khanhduytran0** [comment]
@artdeell maybe add an option to enable Cacio for default?

**Comment by artdeell** [comment]
Maybe, but it seems that this is made for something like ClickGUI, and it wouldn't work

**Comment by WesleyVanNeck** [comment]
is this fixed @artdeell @yejunjie10311031

**Comment by artdeell** [comment]
Impact should work on latest action

**Comment by yejunjie10311031** [comment]
There is a new crash-report:

---- Minecraft Crash Report ----
// You're mean.

Time: 2/1/21 12:32 AM
Description: Initializing game

java.lang.ClassCastException: net.java.openjdk.cacio.ctc.CTCFontManager cannot be cast to sun.awt.X11FontManager
	at sun.awt.motif.MFontConfiguration.getFileNameFromComponentFontName(MFontConfiguration.java:267)
	at sun.awt.FontConfiguration.get2DCompositeFontInfo(FontConfiguration.java:1051)
	at sun.font.SunFontManager.initCompositeFonts(SunFontManager.java:3557)
	at sun.font.SunFontManager.access$800(SunFontManager.java:65)
	at sun.font.SunFontManager$2.run(SunFontManager.java:555)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:386)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at net.java.openjdk.cacio.ctc.CTCFontManager.<init>(CTCFontManager.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Component.getFontMetrics(Component.java:3090)
	at net.impactclient.74.0(74.java:30)
	at net.impactclient.5J.<init>(5J.java:17)
	at net.impactclient.62.0(62.java:6)
	at net.impactclient.62.0(62.java:13)
	at net.impactclient.0ay.2(0ay.java:20)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at sun.awt.motif.MFontConfiguration.getFileNameFromComponentFontName(MFontConfiguration.java:267)
	at sun.awt.FontConfiguration.get2DCompositeFontInfo(FontConfiguration.java:1051)
	at sun.font.SunFontManager.initCompositeFonts(SunFontManager.java:3557)
	at sun.font.SunFontManager.access$800(SunFontManager.java:65)
	at sun.font.SunFontManager$2.run(SunFontManager.java:555)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:386)
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at net.java.openjdk.cacio.ctc.CTCFontManager.<init>(CTCFontManager.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Component.getFontMetrics(Component.java:3090)
	at net.impactclient.74.0(74.java:30)
	at net.impactclient.5J.<init>(5J.java:17)
	at net.impactclient.62.0(62.java:6)
	at net.impactclient.62.0(62.java:13)
	at net.impactclient.0ay.2(0ay.java:20)
	at net.impactclient.4t.0(4t.java:5)
	at bib.handler$init$zzl000(SourceFile:3114)
	at bib.aq(SourceFile:583)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-9
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1675255680 bytes (1597 MB) / 1953497088 bytes (1863 MB) up to 1953497088 bytes (1863 MB)
	JVM Flags: 3 total; -Xms1944M -Xmx1944M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/StubDrawGlyphList.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/xml-libs-pack.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 8x null

**Comment by QuasyStellar** [comment]
Починил?

**Comment by khanhduytran0** [comment]
@yejunjie10311031 add `-Dcacio.font.fontmanager=sun.awt.X11FontManager` to JVM arguments

**Comment by nedogimov** [comment]
Close it pls.
