### ISSUE TITLE
I can't launch optifine on 1.11

### ISSUE THREAD

**Issue by CloserPopcorn20** [PojavLauncherTeam/PojavLauncher#76]
![Screenshot_2020-04-09-23-22-10-457_net kdt pojavlaunch](https://user-images.githubusercontent.com/63425498/78937362-09ca1b00-7ab9-11ea-9ae0-55d64268b957.jpg)
I catching this error when launch the game
Question: What's wrong? 
Phone: Redmi note 8T, Android 9

**Comment by khanhduytran0** [comment]
Unfortunately, Some devices can't launch OptiFine.

**Comment by FranzelDamasco909** [comment]
Have you ever followed the video?

**Comment by CloserPopcorn20** [comment]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 12.04.2020 19:48
Description: Initializing game

java.lang.NullPointerException: Attempt to invoke virtual method 'cbe cbh.bakeModel(brg, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)
	at beq.an(SourceFile:516)
	at beq.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:909)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:764)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:338)
	at beq.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:909)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Linux (armv8l) version 4.14.98-perf-g9296c95
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (Xiaomi Redmi Note 8T [Android 28]), The Android Project
	Memory: 4226648 bytes (4 MB) / 130475456 bytes (124 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.11-OptiFine_HD_U_F5
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer, OpenGL 1.4
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 4 (v8l)
	OptiFine Version: OptiFine_1.11_HD_U_F5
	OptiFine Build: 20191204-142752
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8


And yes. I followed the video.

**Comment by khanhduytran0** [comment]
Unfortunately, this crash is unfixable. But you could get some lucky: Upgrade Android version, install different Android ROM,...

**Comment by Azapru** [comment]
> Unfortunately, this crash is unfixable. But you could get some lucky: Upgrade Android version, install different Android ROM,...

How to do this?

**Comment by khanhduytran0** [comment]
Some Android OTA update might give you lucky to run...

**Comment by khanhduytran0** [comment]
Try v3
