### ISSUE TITLE
----Minecraft Crash Report----

### ISSUE THREAD

**Issue by LANCECRAFT1104** [PojavLauncherTeam/PojavLauncher#778]
// Uh... Did I do that?

Time: 2/1/21 7:09 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:398)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:52)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:170)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:125)
	at net.minecraft.nbt.CompressedStreamTools.func_74794_a(CompressedStreamTools.java:120)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:121)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:20)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:343)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 793280936 bytes (756 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 26 total; -Xmx1G -Xms1G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10 -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/StubDrawGlyphList.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/xml-libs-pack.jar
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

-I'm trying to use Sildur's Shader (lite) and that Happend. It says on YT it is the shader for low end devices.

**Comment by artdeell** [comment]
Probably a Forge/OptiFine/Minecraft bug

**Comment by LanceYTStudioZ** [comment]
Why all shaders now working?

**Comment by 555LPWRCDV** [comment]
Why shader is not working?

**Comment by 555LPWRCDV** [comment]
How to install a shader? Why others can?

**Comment by Druxelite** [comment]
> How to install a shader? Why others can?

We can install shaders because we have better devices and have optifine.

**Comment by Zeyrox1090** [comment]
snapdragon 800+

**Comment by khanhduytran0** [comment]
> Why shader is not working?

@555LPWRCDV simply because Android GPU ≠ PC GPU

**Comment by Mathias-Boulay** [comment]
Issue not related to pojav, closing it.
