### ISSUE TITLE
I can't play optifine (Minecraft 1.11.2)

### ISSUE THREAD

**Issue by FranzelDamasco909** [PojavLauncherTeam/PojavLauncher#81]
I can't play optifine but i have already launcher_profiles.json in Minecraft 1.11.2

Error:
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(MCLauncherActivity.java:1041)
	at net.kdt.pojavlaunch.MCLauncherActivity$OptiFineInstaller.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: java.io.IOException: Base resource not found: aha.class
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:32)
	... 9 more
Caused by: java.io.IOException: Base resource not found: aha.class
	at optifine.Patcher.applyPatch(Patcher.java:143)
	at optifine.Patcher.process(Patcher.java:87)
	at optifine.AndroidInstaller.installOptiFineLibrary(AndroidInstaller.java:56)
	at optifine.AndroidInstaller.doInstall(AndroidInstaller.java:28)
	... 9 more

**Comment by FranzelDamasco909** [comment]
i don't know what to do

**Comment by khanhduytran0** [comment]
Delete folder /storage/sdcard0/games/minecraft/versions/1.11.2 then
- Re-install minecraft 1.11.2 (run once)
- Re-install optifine and try run again.

**Comment by FranzelDamasco909** [comment]
![Screenshot_2020-04-11-17-28-01-98](https://user-images.githubusercontent.com/62983424/79040245-db178600-7c19-11ea-9e80-b8eb665cfa5e.png)

**Comment by FranzelDamasco909** [comment]
i succesfully installed optifine but i can't launch

**Comment by FranzelDamasco909** [comment]
pls reply

**Comment by khanhduytran0** [comment]
Some devices can't run OptiFine. try to copy crash log.

**Comment by FranzelDamasco909** [comment]
why i can't play optifine?

**Comment by FranzelDamasco909** [comment]
what can i do about the crash log?

**Comment by khanhduytran0** [comment]
Copy and paste here.

But it might not help.

**Comment by FranzelDamasco909** [comment]
I'll try

**Comment by FranzelDamasco909** [comment]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 4/11/20 7:38 PM
Description: Initializing game

java.lang.IllegalStateException: Already building!
	at bpy.a(VertexBuffer.java:291)
	at bes.a(SourceFile:856)
	at bes.a(SourceFile:840)
	at bes.an(SourceFile:457)
	at bes.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:909)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:764)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bpy.a(VertexBuffer.java:291)
	at bes.a(SourceFile:856)
	at bes.a(SourceFile:840)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:338)
	at bes.a(SourceFile:386)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:909)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (armv8l) version 4.9.82-perf+
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (OPPO CPH1853 [Android 27]), The Android Project
	Memory: 0 bytes (0 MB) / 88530072 bytes (84 MB) up to 536870912 bytes (512 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.11.2-OptiFine_HD_U_C7
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv8 Processor rev 4 (v8l)
	OptiFine Version: OptiFine_1.11.2_HD_U_C7
	Render Distance Chunks: 3
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
Seems like you are trying to join a world?

**Comment by FranzelDamasco909** [comment]
no, while i first launched, it just game crashed

**Comment by FranzelDamasco909** [comment]
No Mojang Logo appears, it just literally game crashed

**Comment by FranzelDamasco909** [comment]
And what OpenGL you use for pojavlauncher

**Comment by khanhduytran0** [comment]
> And what OpenGL you use for pojavlauncher

Still GL4ES.

**Comment by FranzelDamasco909** [comment]
ok back about the game crashing

**Comment by FranzelDamasco909** [comment]
No Mojang logo appears on my screen after i launched minecraft during with optifine

**Comment by khanhduytran0** [comment]
What version?

**Comment by khanhduytran0** [comment]
Also try other OptiFine

**Comment by khanhduytran0** [comment]
OptiFine_1.11.2_HD_U_C7 made you crash.

**Comment by khanhduytran0** [comment]
Try the HD_U_F5 one http://optifine.net/adloadx?f=OptiFine_1.11.2_HD_U_F5.jar

**Comment by FranzelDamasco909** [comment]
ok thanks

**Comment by FranzelDamasco909** [comment]
doesn't work

java.lang.RuntimeException: Unable to convert library optifine:launchwrapper-of:2.1
java.lang.RuntimeException: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:502)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:556)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:32)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

UNEXPECTED TOP-LEVEL EXCEPTION:
java.io.FileNotFoundException: File doesn't exist: /storage/emulated/0/games/minecraft/libraries/optifine/launchwrapper-of/2.1/launchwrapper-of-2.1_orig.jar
	at java.util.zip.ZipFile.<init>(ZipFile.java:212)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.pojavdx.dx.command.dexer.Main.processOne(Main.java:682)
	at com.pojavdx.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.pojavdx.dx.command.dexer.Main.runMultiDex(Main.java:361)
	at com.pojavdx.dx.command.dexer.Main.runDx(Main.java:283)
	at com.pojavdx.dx.command.dexer.Main.main(Main.java:241)
	at com.pojavdx.dx.command.Main.main(Main.java:95)
	at net.kdt.pojavlaunch.Tools.runDx(Tools.java:339)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:574)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
1 error; aborting
Exiting with code 1

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine#since-optifine-mc-19-a-file-called-launchwrapper-of-21jar-cause-error-unable-to-launch-simply-fix-by-follow-the-video-or-do-actions-as-below

**Comment by FranzelDamasco909** [comment]
i can't find launchwrapper inside the Optifine version(1.11.2-Optifine-HD-U-F5.json)

**Comment by FranzelDamasco909** [comment]
pls reply

**Comment by khanhduytran0** [comment]
Find inside jar file
/storage/sdcard0/games/minecraft/libraries/optifine/OptiFine/1.11.2-Optifine-HD-U-F5/OptiFine-1.11.2-Optifine-HD-U-F5.jar

**Comment by FranzelDamasco909** [comment]
i can't find it and i mispelled the jar to json on the message

**Comment by khanhduytran0** [comment]
You could also find in the installer jar file
![IMG_20200412_144545](https://user-images.githubusercontent.com/40482367/79063526-779a6080-7ccc-11ea-98ff-475e6977ef0a.jpg)

**Comment by FranzelDamasco909** [comment]
ok

**Comment by FranzelDamasco909** [comment]
what's the file path

**Comment by khanhduytran0** [comment]
Put to /storage/emulated/0/games/minecraft/libraries/optifine/launchwrapper-of/2.1/

**Comment by FranzelDamasco909** [comment]
i can't find launchwrapper inside the Optifine version(1.11.2-Optifine-HD-U-F5.json)

**Comment by khanhduytran0** [comment]
I said find in the installer or I upload here?

**Comment by FranzelDamasco909** [comment]
i can't find launchwrapper inside the Optifine version(1.11.2-Optifine-HD-U-F5.json)

**Comment by FranzelDamasco909** [comment]
yes upload the file

**Comment by FranzelDamasco909** [comment]
but i think it won't work because json file is not supported

**Comment by FranzelDamasco909** [comment]
all i need is the optifine json file

**Comment by khanhduytran0** [comment]
The installer file already generated json file

**Comment by khanhduytran0** [comment]
[launchwrapper-of-2.1.jar.zip](https://github.com/khanhduytran0/PojavLauncher/files/4466057/launchwrapper-of-2.1.jar.zip)

**Comment by FranzelDamasco909** [comment]
where can i put that?

**Comment by khanhduytran0** [comment]
The file will be in /storage/emulated/0/games/minecraft/libraries/optifine/launchwrapper-of/2.1/launchwrapper-of-2.1.jar

**Comment by FranzelDamasco909** [comment]
ok thank you!

**Comment by FranzelDamasco909** [comment]
so it means i put launchwrapper-of-2.1.jar to /storage/emulated/0/games/minecraft/libraries/optifine/launchwrapper-of/2.1/(Here)

**Comment by khanhduytran0** [comment]
Yes

**Comment by FranzelDamasco909** [comment]
Yup the mojang logo is shown but it crashed :(
![Screenshot_2020-04-12-17-22-38-87](https://user-images.githubusercontent.com/62983424/79065355-4462cc00-7ce2-11ea-9498-decf386a735f.png)

**Comment by khanhduytran0** [comment]
Yep

**Comment by FranzelDamasco909** [comment]
How to fix pls i need optifine

**Comment by khanhduytran0** [comment]
I'm unable to fix it, seems like works or not depending on device.

**Comment by FranzelDamasco909** [comment]
i tried it on 1.7.10 too but it doesn't work

**Comment by khanhduytran0** [comment]
Unfortunately, some devices will not work any OptiFine versions (but a guy made Minecraft 1.2.5 run with OptiFine).

**Comment by FranzelDamasco909** [comment]
try to check some of your code things if there's a supporting problems on optifine for android 8.1 and others

**Comment by FranzelDamasco909** [comment]
Try to check your codes if there's a problem functioning Optifine on Android 8.1 or others

**Comment by khanhduytran0** [comment]
The error happend inside the game.

**Comment by FranzelDamasco909** [comment]
yes but idk what to fix

**Comment by artdeell** [comment]
@FranzelDamasco909 if you want to track OpenGL compartiblity you can monitor the corresponding thread ( #59 )

**Comment by FranzelDamasco909** [comment]
Sorry can you say it again in the easy way?

**Comment by artdeell** [comment]
> Sorry can you say it again in the easy way?

If you want to know when OpenGL will be fixed, read the linked issue @

**Comment by FranzelDamasco909** [comment]
Ok thank you

**Comment by FranzelDamasco909** [comment]
wait what am i going to do?

**Comment by FranzelDamasco909** [comment]
pls reply @artdeell
