### ISSUE TITLE
PojavLauncher has unexpectedly crashed

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#821]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at net.kdt.pojavlaunch.value.launcherprofiles.VersionProfileAdapter.prepareView(VersionProfileAdapter.java:33)
	at net.kdt.pojavlaunch.value.launcherprofiles.VersionProfileAdapter.getView(VersionProfileAdapter.java:49)
	at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:204)
	at android.widget.Spinner.onMeasure(Spinner.java:622)
	at androidx.appcompat.widget.AppCompatSpinner.onMeasure(AppCompatSpinner.java:436)
	at android.view.View.measure(View.java:22333)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:792)
	at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.measure(BasicMeasure.java:480)
	at androidx.constraintlayout.solver.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:371)
	at androidx.constraintlayout.solver.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:119)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1578)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1690)
	at android.view.View.measure(View.java:22333)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6705)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
	at android.view.View.measure(View.java:22333)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6705)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22333)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6705)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:22333)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6705)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
	at android.view.View.measure(View.java:22333)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6705)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:805)
	at android.view.View.measure(View.java:22333)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2715)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1713)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1974)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1601)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7355)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1038)
	at android.view.Choreographer.doCallbacks(Choreographer.java:850)
	at android.view.Choreographer.doFrame(Choreographer.java:766)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1024)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:200)
	at android.app.ActivityThread.main(ActivityThread.java:6971)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

https://user-images.githubusercontent.com/78294173/107142171-f4877c80-6967-11eb-8602-d2be1043791c.mp4

**Comment by artdeell** [comment]
Don't use builds from "profiles".
They are highly unstable.

**Comment by LanceYTStudioZ** [comment]
> Don't use builds from "profiles".
> They are highly unstable.

Okay

**Comment by LanceYTStudioZ** [comment]
> Don't use builds from "profiles".
> They are highly unstable.

But I can't login and play

**Comment by artdeell** [comment]
Yes, because they are *unstable* and crash for most people.

**Comment by LanceYTStudioZ** [comment]
What I will do now? I can not login any more.

**Comment by Mathias-Boulay** [comment]
You were told to use another version.
Use another version from the v3_openjdk branch

**Comment by LanceYTStudioZ** [comment]
Same problem

**Comment by LanceYTStudioZ** [comment]
> You were told to use another version.
> Use another version from the v3_openjdk branch

Okay

**Comment by LanceYTStudioZ** [comment]
Are you still working for profiles? I hope you can fix it.

**Comment by artdeell** [comment]
Check latest action

**Comment by LanceYTStudioZ** [comment]
> Check latest action

Okay Thank You
