### ISSUE TITLE
[BUG]Игра вылетает из-за "Ticking entity"

### ISSUE THREAD

**Issue by Eurannic** [PojavLauncherTeam/PojavLauncher#822]
После захода в игру спустя пару минут геймплея игра вылетатет, и в краш-репорте указано что это из-за нейкого "Ticking entity". Forge и Optifine не установлен. Крашается в каждом мире. Это проблема моего телефона или это недочёт разработчиков? Это возможно как то исправить?

**Платформа**
 - Модель девайса [Samsung Galaxy A10]
 - Архтектура процессора [aarch32] 
 - Версия Android [10]

**Comment by artdeell** [comment]
А краш-лог?

**Comment by Eurannic** [comment]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/7/21 10:01 AM
Description: Ticking entity

java.lang.IndexOutOfBoundsException: Index: 29, Size: 29
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.remove(ArrayList.java:498)
	at et$b.e(SourceFile:455)
	at et$b.s(SourceFile:437)
	at amu.a(SourceFile:1714)
	at vg.au(SourceFile:1101)
	at vg.Y(SourceFile:445)
	at vp.Y(SourceFile:228)
	at vq.Y(SourceFile:214)
	at vg.B_(SourceFile:364)
	at vp.B_(SourceFile:1681)
	at vq.B_(SourceFile:281)
	at amu.a(SourceFile:1524)
	at oo.a(SourceFile:714)
	at amu.h(SourceFile:1500)
	at amu.k(SourceFile:1382)
	at oo.k(SourceFile:547)
	at net.minecraft.server.MinecraftServer.D(SourceFile:632)
	at net.minecraft.server.MinecraftServer.C(SourceFile:560)
	at chd.C(SourceFile:154)
	at net.minecraft.server.MinecraftServer.run(SourceFile:464)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.remove(ArrayList.java:498)
	at et$b.e(SourceFile:455)
	at et$b.s(SourceFile:437)
	at amu.a(SourceFile:1714)
	at vg.au(SourceFile:1101)
	at vg.Y(SourceFile:445)
	at vp.Y(SourceFile:228)
	at vq.Y(SourceFile:214)
	at vg.B_(SourceFile:364)
	at vp.B_(SourceFile:1681)
	at vq.B_(SourceFile:281)
	at amu.a(SourceFile:1524)
	at oo.a(SourceFile:714)
	at amu.h(SourceFile:1500)

-- Entity being ticked --
Details:
	Entity Type: minecraft:pig (aad)
	Entity ID: 154
	Entity Name: Свинья
	Entity's Exact location: 23.50, 68.00, 320.50
	Entity's Block location: World: (23,68,320), Chunk: (at 7,4,0 in 1,20; contains blocks 16,0,320 to 31,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at amu.k(SourceFile:1382)
	at oo.k(SourceFile:547)

-- Affected level --
Details:
	Level name: Новый мир
	All players: 1 total; [oq['Eurannic'/359, l='Новый мир', x=70.27, y=68.00, z=667.72]]
	Chunk stats: ServerChunkCache: 554 Drop: 0
	Level seed: -6609589040385967946
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (60,64,256), Chunk: (at 12,4,0 in 3,16; contains blocks 48,0,256 to 63,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 10198 game time, 10198 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 92783 (now: false), thunder time: 158948 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.D(SourceFile:632)
	at net.minecraft.server.MinecraftServer.C(SourceFile:560)
	at chd.C(SourceFile:154)
	at net.minecraft.server.MinecraftServer.run(SourceFile:464)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (arm) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 304651064 bytes (290 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 3 total; -Xms512m -Xmx1024m -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/.minecraft/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 4, tcache: 1, allocated: 12, tallocated: 94
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [oq['Eurannic'/359, l='Новый мир', x=70.27, y=68.00, z=667.72]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Probably not. Jar signature remains and both client + server brands are untouched.

**Comment by artdeell** [comment]
Баг игры.

**Comment by Eurannic** [comment]
Просто непонятно, это только у меня или у кого то есть такая же проблема, и как это вообще исправить?

**Comment by artdeell** [comment]
У одного. Исправить - не знаю как.
