### ISSUE TITLE
[BUG] help me

### ISSUE THREAD

**Issue by poopipie** [PojavLauncherTeam/PojavLauncher#831]
where can i put this?
-Dorg.lwjgl.opengl.libname=libgl4es_115.so
help please

**Comment by khanhduytran0** [comment]
Put to jvm arguments

**Comment by poopipie** [comment]
okay thanks ill try

**Comment by poopipie** [comment]
it crashed my game, actually that code is use to fix white eggs and banners but i don't know where to put it

**Comment by poopipie** [comment]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2/9/21 12:34 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: Failed to locate library: liblibgl4es_115.so-Xmx2G.so
	at org.lwjgl.system.Library.loadNative(Library.java:324)
	at org.lwjgl.system.Library.loadNative(Library.java:222)
	at org.lwjgl.system.Library.loadNative(Library.java:203)
	at org.lwjgl.system.Library.loadNative(Library.java:402)
	at org.lwjgl.system.Library.loadNative(Library.java:378)
	at org.lwjgl.opengl.GL.create(GL.java:108)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:90)
	at dew.<init>(SourceFile:106)
	at eam.a(SourceFile:21)
	at djw.<init>(SourceFile:447)
	at net.minecraft.client.main.Main.main(SourceFile:177)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.system.Library.loadNative(Library.java:324)
	at org.lwjgl.system.Library.loadNative(Library.java:222)
	at org.lwjgl.system.Library.loadNative(Library.java:203)
	at org.lwjgl.system.Library.loadNative(Library.java:402)
	at org.lwjgl.system.Library.loadNative(Library.java:378)
	at org.lwjgl.opengl.GL.create(GL.java:108)
	at org.lwjgl.opengl.GL.<clinit>(GL.java:90)
	at dew.<init>(SourceFile:106)
	at eam.a(SourceFile:21)
	at djw.<init>(SourceFile:447)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3182130456 bytes (3034 MB) / 3923771392 bytes (3742 MB) up to 3923771392 bytes (3742 MB)
	CPUs: 8
	JVM Flags: 6 total; -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1000M -Xms3841M -Xmx3841M
	Launched Version: 1.16.3
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by poopipie** [comment]
help

**Comment by khanhduytran0** [comment]
Arguments split by a space, didn't you put?
```
-Dorg.lwjgl.opengl.libname=libgl4es_115.so-Xmx2G
                                          ^ HERE
```

**Comment by poopipie** [comment]
aight problem solved thank you so much for the help i really appreciate it

**Comment by nedogimov** [comment]
> aight problem solved thank you so much for the help i really appreciate it

Close it pls.

**Comment by BriSKLaY** [comment]
[23:44:04] [main/INFO]: ModLauncher running: args [--username, BrisKLaY, --version, 1.20.1, --gameDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft, --assetsDir, /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/assets, --assetIndex, 5, --uuid, 00000000000000000000000000000000, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, , --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.11, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[23:44:04] [main/INFO]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.12-internal by N/A; OS Linux arch aarch64 version Android-13
[23:44:07] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[23:44:07] [main/INFO]: Trying GL version 4.6
[23:44:07] [main/INFO]: Requested GL version 4.6 got version 0.0
[23:44:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23114!/ Service=ModLauncher Env=CLIENT
[23:44:08] [pool-2-thread-1/INFO]: GL info: ANGLE (ARM, Vulkan 1.1.177 (Mali-G57 MC2 (0x90930010)), Mali-G57 MC2-32.1.0) GL version 4.6.0 (ANGLE 2.1.1 git hash: b79b72b53460), Google Inc. (ARM)
[23:44:09] [main/INFO]: Found mod file 1.20-1.20.1-RemindClockHUD-1.0.0-beta.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file abyss_ores_1.20.1_1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file advancements_tracker_1.20.1-6.1.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file almanac-1.20.x-forge-1.0.2.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file ancientsand-forge-1.0.8-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file appleskin-forge-mc1.20.1-2.5.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file appliedenergistics2-forge-15.2.13-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file architectury-9.2.14-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file AttributeFix-Forge-1.20.1-21.0.4.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file balm-forge-1.20.1-7.3.6-all.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file Balmy-Food-3.2.5-FORGE-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file better-cave-dweller-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file bettercombat-forge-1.8.5-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file BetterF3-7.0.2-Forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file betterfpsdist-1.20.1-4.4.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file biome_armors-1.0.2-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file catalogue-forge-1.20.1-1.8.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file cave_dweller-1.20.1-1.7.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file cfm-forge-1.20.1-7.0.0-pre36.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file charms-1.20.1-1.0.0.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file cloth-config-11.1.118-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file cloth-config-11.1.118-forge.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file coalexplosion-forge-1.20.1-1.9.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file cofh_core-1.20.1-11.0.2.56.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file combatroll-forge-1.3.2-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file CraftTweaker-forge-1.20.1-14.0.40.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file cupboard-1.20.1-2.7.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file curios-forge-5.10.0+1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file curios-forge-5.9.1-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file daily_rewards_1.20.1-5.3.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file diet-forge-2.1.1-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file e4mc_minecraft-forge-5.2.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file emotecraft-for-MC1.20.1-2.2.7-a.build.49-forge.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file endertrigon-1.20.1-1.1-all.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file enhanced_boss_bars-1.20.1-1.0.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file entitlements-forge-1.1.1-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file EverlastingSkins-1.20.1-1.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file Female-Gender-Mod-forge-1.20.1-3.0.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file ferritecore-6.0.1-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file flib-1.20.1-0.0.14.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file FpsReducer2-forge-1.20-2.5.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file geckolib-forge-1.20.1-4.4.7.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file gobber2-forge-1.20.1-2.8.9.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file HammerLib-1.20.1-20.1.26.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file herios_helian_mod-1.2.4-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file ironchest-1.20.1-14.4.4.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file ItemProductionLib-1.20.1-1.0.2a-all.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file Jade-1.20.1-forge-11.9.4.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file jei-1.20.1-forge-15.8.0.11.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file just_ctgui-0.1.5_release-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file letmedespawn-1.20.x-forge-1.4.4.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file Luminous-Beast-V1.1-Forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file Miner-sLuck1.2-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file mobstacker-1.20.x-forge-1.0.6c.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file modernfix-forge-5.18.10-mc1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file modernfix-forge-5.18.9-mc1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file MorePlayerModels-1.20.1.20240409.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file noisium-forge-2.3.0-mc1.20-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file onceuponastroll-forge-1.20.1-1.7.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file perrys_decorations-1.0.1-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file pipez-forge-1.20.1-1.2.16.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file player-animation-lib-forge-1.0.2-rc1+1.20.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file polymorph-forge-0.49.5-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file pro_amethyst-1.5.0-forge-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file RingOfRepair-Forge-1.20.1-1.6.3.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file SereneSeasons-1.20.1-9.0.0.46.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file simplelifecrystal-1.0.2-1.20.1-FORGE.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file skeleton-uprising-v2.1.0-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file smoothchunk-1.20.1-3.6.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file Sniffer-s-delicacies-1.20.1-v1.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file SolarFluxReborn-1.20.1-20.1.6.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file SoulBinding1.20.1-Forge-vs1.0.2.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file starlight-1.1.2-forge.1cda73c.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file SuperiorSmithingV4.3-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file thermal_expansion-1.20.1-11.0.1.29.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file thermal_foundation-1.20.1-11.0.4.68.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file travelersbackpack-forge-1.20.1-9.1.16.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file tubesreloaded-1.20.1-3.1.0.0.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file veinmining-forge-1.5.0-1.20.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file venus-mc1.20.1-0.0.1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file waystones-forge-1.20-14.1.4.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file weaponleveling-1.20.1-2.2.2-forge.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file worldplaytime-1.2.2-1.20.1-FORGE_1.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/INFO]: Found mod file Xaeros_Minimap_24.1.0_Forge_1.20.jar of type MOD with provider {mods folder locator at /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/mods}
[23:44:09] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/fmlcore/1.20.1-47.3.11/fmlcore-1.20.1-47.3.11.jar is missing mods.toml file
[23:44:09] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.3.11/javafmllanguage-1.20.1-47.3.11.jar is missing mods.toml file
[23:44:09] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.3.11/lowcodelanguage-1.20.1-47.3.11.jar is missing mods.toml file
[23:44:09] [main/WARN]: Mod file /storage/emulated/0/Android/data/net.kdt.pojavlaunch/files/.minecraft/libraries/net/minecraftforge/mclanguage/1.20.1-47.3.11/mclanguage-1.20.1-47.3.11.jar is missing mods.toml file
[23:44:09] [main/INFO]: Found mod file fmlcore-1.20.1-47.3.11.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@de88ac6
[23:44:09] [main/INFO]: Found mod file javafmllanguage-1.20.1-47.3.11.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@de88ac6
[23:44:09] [main/INFO]: Found mod file lowcodelanguage-1.20.1-47.3.11.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@de88ac6
[23:44:09] [main/INFO]: Found mod file mclanguage-1.20.1-47.3.11.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@de88ac6
[23:44:09] [main/INFO]: Found mod file client-1.20.1-20230612.114412-srg.jar of type MOD with provider net.minecraft

Error -1 pls help me
