### ISSUE TITLE
[ERROR] Attempt to get length null array

### ISSUE THREAD

**Issue by LanceYTStudioZ** [PojavLauncherTeam/PojavLauncher#840]
java.lang.NullPointerException: Attempt to get length of null array
	at net.kdt.pojavlaunch.Tools.write(Tools.java:731)
	at net.kdt.pojavlaunch.Tools.copyAssetFile(Tools.java:396)
	at net.kdt.pojavlaunch.PojavLoginActivity.initMain(PojavLoginActivity.java:396)
	at net.kdt.pojavlaunch.PojavLoginActivity.access$500(PojavLoginActivity.java:74)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:178)
	at net.kdt.pojavlaunch.PojavLoginActivity$InitTask.doInBackground(PojavLoginActivity.java:114)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

https://user-images.githubusercontent.com/78294173/107495238-c81f6a80-6bca-11eb-94b9-b257fbaa8f76.mp4

**Comment by LanceYTStudioZ** [comment]
Android CI #2024

**Comment by LanceYTStudioZ** [comment]
Thanks Man!
