### ISSUE TITLE
[F-REQ] can dev team make pojav launcher with ram allocator this suggestion was hard but increase more experience for pojav launcher useful

### ISSUE THREAD

**Issue by notpvpking** [PojavLauncherTeam/PojavLauncher#855]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by khanhduytran0** [comment]
Change “Xmx” and “Xms” in jvm arguments.

**Comment by Unknitcandy2585** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EarlyLoadPlugin (PixelmonGenerations-1.12.2-8.5.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 8/21/21 8:16 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.pixelmongenerations.common.world.gen.feature.WorldGenPokemonGrass.generate(WorldGenPokemonGrass.java:42)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.pixelmongenerations.common.world.gen.feature.WorldGenPokemonGrass.generate(WorldGenPokemonGrass.java:42)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: New World-
	All players: 1 total; [EntityPlayerMP['UnknitCandy2585'/1177, l='New World-', x=-372.95, y=67.00, z=-33.92]]
	Chunk stats: ServerChunkCache: 316 Drop: 0
	Level seed: 6377602712454401063
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-252,64,28), Chunk: (at 4,4,12 in -16,1; contains blocks -256,0,16 to -241,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 16793 game time, 16793 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 129940 (now: false), thunder time: 80461 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3088263136 bytes (2945 MB) / 4073193472 bytes (3884 MB) up to 4073193472 bytes (3884 MB)
	JVM Flags: 4 total; -Xmx8G -Xms4096M -Xmx4096M -Xbootclasspath/a:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version      | Source                                        | Signature                                |
	|:------ |:--------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp             | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | aearlymodloader | 8.5.1        | minecraft.jar                                 | None                                     |
	| LCHIJA | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | biomesoplenty   | 7.0.1.2444   | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHIJA | pixelmon        | 8.5.1        | PixelmonGenerations-1.12.2-8.5.1.jar          | None                                     |

	Loaded coremods (and transformers): 
EarlyLoadPlugin (PixelmonGenerations-1.12.2-8.5.1.jar)
  com.pixelmongenerations.core.plugin.PixelmonTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['UnknitCandy2585'/1177, l='New World-', x=-372.95, y=67.00, z=-33.92]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2 (Compatibility Profile) Mesa 21.0.2 (git-9d2e7e7940)
	OpenGlRenderer: zink (Mali-G72)
	OpenGlVendor: Collabora Ltd
	CpuCount: 8

**Comment by Unknitcandy2585** [comment]
Oops

**Comment by Unknitcandy2585** [comment]
Sorry
