### ISSUE TITLE
Error when launching 1.8.9 Optifine U H8

### ISSUE THREAD

**Issue by notfoundname** [PojavLauncherTeam/PojavLauncher#86]
Hello again, I am having an issue with launching Minecraft 1.8.9 Optifine U H8. It successfully installs, but after launching  crashes immediately (don't even see Mojang logo).
I tried to reinstall application with file deleting, also tried VMOS but same crap happens. 
My phone is Huawei Honor 6A (Android 7.0, EMUI 5.1.3, 2GBs of RAM and I have ROOT activated). 
![Screenshot_20200413-162238](https://user-images.githubusercontent.com/48317169/79109057-324c6080-7daa-11ea-8e68-2f7fe1751aed.png)

`java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:909)
	at net.kdt.pojavlaunch.MainActivity.access$1000085(MainActivity.java)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:628)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	... 5 more
Caused by: java.lang.IncompatibleClassChangeError: The method 'void bma.<init>(java.io.File, java.lang.String, jy, bfm)' was expected to be of type static but instead was found to be of type direct (declaration of 'nt' appears in /storage/emulated/0/games/minecraft/libraries/optifine/OptiFine/1.8.9_HD_U_H8/OptiFine-1.8.9_HD_U_H8.jar:classes4.dex)
	at nt.<init>(Profiler.java:24)
	at net.minecraft.server.MinecraftServer.<init>(SourceFile:99)
	at bpo.<init>(IntegratedServer.java:52)
	at ave.<init>(SourceFile:293)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	... 7 more`

**Comment by khanhduytran0** [comment]
Delete OptiFine by folder `/storage/emulated/0/games/minecraft/libraries/optifine/OptiFine/1.8.9_HD_U_H8` then re-install OptiFine and try again.

Also try the latest one: `OptiFine 1.8.9 HD U L5`

**Comment by notfoundname** [comment]
Latest doesn't installing.

**Comment by khanhduytran0** [comment]
Launcherwrapper-of-2.1.jar?

**Comment by notfoundname** [comment]
Hmmm, I got it, will try this version again.

**Comment by notfoundname** [comment]
https://pastebin.com/00LWUx2c error when installing OF HD U L5

**Comment by khanhduytran0** [comment]
OptiFine targeting Minecraft 1.8.9 or above requires Android 8.0 or above.

**Comment by notfoundname** [comment]
Sad =( Anyway way make this working? My device is rooted

**Comment by khanhduytran0** [comment]
The only way is install a custom ROM based on Android 8.0+

**Comment by notfoundname** [comment]
Oh, okay. Anyway, thanks for this great fork. Keep it up
