### ISSUE TITLE
[BUG]Forge 1.12.2 crashes when trying to run it

### ISSUE THREAD

**Issue by Dimon245** [PojavLauncherTeam/PojavLauncher#872]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

**Describe the bug**
Forge 1.12.2 crashes on startup. I was using previous builds and it used to crash after a few seconds/minutes into the game and thought the latest build would fix the constant crashes, but it made it worse, lol. 
I've been trying to fix the crash myself by changing lwjgl3 files to previous versions, but to no avail unfortunately

**To Reproduce**
1. Start PojavLauncher
2. Start MC Forge 1.12.2 (doesn't matter if you use mods or not)
3. Wait for it to load the Mojang logo. After a few seconds it crashes

**Expected behavior**
I expected it not to crash at all

**Screenshots**
I don't think screenshots would help xd
**Platform:**
 - Device Model: Samsung S20+
 - CPU architecture: aarch64
 - Android Version: 11

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2/13/21 7:23 AM
Description: Initializing game

java.lang.UnsatisfiedLinkError: /data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so: dlopen failed: cannot locate symbol "_ZTVN10__cxxabiv120__si_class_type_infoE" referenced by "/data/user/0/net.kdt.pojavlaunch/jre_runtime/lib/aarch64/libfontmanager.so"...
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:346)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:342)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.java.openjdk.cacio.ctc.FontManagerUtil$1.run(FontManagerUtil.java:24)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.openjdk.cacio.ctc.FontManagerUtil.setFontManager(FontManagerUtil.java:17)
	at net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment.<clinit>(CTCGraphicsEnvironment.java:31)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at net.minecraftforge.client.model.ModelLoader$White.load(ModelLoader.java:901)
	at net.minecraft.client.renderer.texture.TextureMap.loadTexture(TextureMap.java:148)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:110)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:346)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:342)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.java.openjdk.cacio.ctc.FontManagerUtil$1.run(FontManagerUtil.java:24)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.openjdk.cacio.ctc.FontManagerUtil.setFontManager(FontManagerUtil.java:17)
	at net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment.<clinit>(CTCGraphicsEnvironment.java:31)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at net.minecraftforge.client.model.ModelLoader$White.load(ModelLoader.java:901)
	at net.minecraft.client.renderer.texture.TextureMap.loadTexture(TextureMap.java:148)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:110)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:91)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:159)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-11
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1895569456 bytes (1807 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 26 total; -Xmx2G -Xms2G -Xmn128m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=2000 -XX:ParallelGCThreads=10 -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCH   | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCH   | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x null
</pre>
</details>

**Comment by khanhduytran0** [comment]
Try uninstall Java runtime and let the launcher re-install.

**Comment by Dimon245** [comment]
Yeah, I fixed it by downloading the With Runtime version, I was using the no-runtime (prior).
Idk where I got the runtime, but it was somewhere from your channel (jre8-arm64-20201102-release.tar.xz). Guess it's not stable anymore.
