### ISSUE TITLE
 Minecraft Crash Report 

### ISSUE THREAD

**Issue by joaquinleiva** [PojavLauncherTeam/PojavLauncher#88]
---- Minecraft Crash Report 
----
// I bet Cylons wouldn't have this problem.

Time: 13/4/20 23:43
Description: Initializing game

java.lang.NullPointerException: Attempt to invoke virtual method 'cbe cbh.bakeModel(brg, net.minecraftforge.common.model.ITransformation, boolean)' on a null object reference
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)
	at beq.an(SourceFile:516)
	at beq.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:826)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cbh.a(ModelBakery.java:724)
	at cbi.a(SourceFile:23)
	at cab.a(SourceFile:100)

-- Initialization --
Details:
Stacktrace:
	at b.a(CrashReport.java:338)
	at beq.a(SourceFile:383)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at java.lang.reflect.Method.invoke(Native Method)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:126)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:19)
	at net.kdt.pojavlaunch.MainActivity.runCraft(MainActivity.java:826)
	at net.kdt.pojavlaunch.MainActivity.access$1000078(Unknown Source:0)
	at net.kdt.pojavlaunch.MainActivity$100000014$100000013.run(MainActivity.java:600)
	at java.lang.Thread.run(Thread.java:764)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Linux (armv7l) version 3.18.120-perf-g6759046
	Java Version: 0, The Android Project
	Java VM Version: Dalvik (motorola moto g(6) play [Android 28]), The Android Project
	Memory: 4917608 bytes (4 MB) / 112343736 bytes (107 MB) up to 402653184 bytes (384 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.11-OptiFine_HD_U_F5
	LWJGL: 2.9.1
	OpenGL: GL4ES wrapper GL version 2.0 gl4es wrapper 1.1.2, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer, OpenGL 1.4
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Not using framebuffer objects because OpenGL 1.4 is not supported, EXT_blend_func_separate is not supported, OpenGL 3.0 is not supported, ARB_framebuffer_object is supported, and EXT_framebuffer_object is supported.
Shaders are available because ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.
VBOs are available because ARB_vertex_buffer_object is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'PojavLauncher'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv7 Processor rev 4 (v7l)
	OptiFine Version: OptiFine_1.11_HD_U_F5
	OptiFine Build: 20191204-142752
	Render Distance Chunks: 2
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.0 gl4es wrapper 1.1.2
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8

**Comment by khanhduytran0** [comment]
Unfortunately, this crash is unfixable, some devices can't run OptiFine.

**Comment by Citomonbun** [comment]
so I can't play minecraft

**Comment by artdeell** [comment]
> so I can't play minecraft

You can, but on vanilla

**Comment by Citomonbun** [comment]
great my life is now pointless

**Comment by artdeell** [comment]
> great my life is now pointless

Why?
