### ISSUE TITLE
1.12 and older physical keyboard and mouse bugs [BUG]

### ISSUE THREAD

**Issue by rojaoo** [PojavLauncherTeam/PojavLauncher#886]
# Description
I was playing on a rankup server in 1.8.9, with mouse and keyboard connected to my phone by a otg cable, and i noticed some bugs, so, i will report it. I Hope it got solved.
# <h1> Bugs
**Camera teleport**
- Opening the inventory, chest, pause screen... and moving the mouse, causes the screen to move.

**To Reproduce**
1. Start PojavLauncher
2. Launch 1.8.9
3. Enter in a world or server
4. Press ESC or anything that makes the mouse cursor appears
5. Move the mouse
6. Go back to the game
7. Move the mouse again
- You will notice that the camera teleported.

**Fullscreen**
- Pressing Shift and W or Capslock ON and W, makes the game switch to fullscreen or halfscreen

**To Reproduce**
1. Start PojavLauncher
2. Launch 1.8.9
3. Enter in a world or server
4. Hold down the shift key and the w key
- You will notice that the game isn't in fullscreen anymore

**Copy Paste don't work**
- Ctrl C and Ctrl V works only in 1.13+ versions.

 # <h1> Additional
**Platform:**
 - Device Model: Motorola Moto G7 Play
 - CPU architecture: armv7I
 - Android Version: 10
- With OTG cable

**Game**
- Pojav Version: 3.3.1.1
- Minecraft Version: 1.8.9

**Comment by HedHogie** [comment]
Have the same problem, I think 1.13+ won't have this problem, but 1.13 makes it even worse, it causes the game to freeze you in one position. Looking at one block only

**Comment by khanhduytran0** [comment]
@zigordlc get latest build.

**Comment by rojaoo** [comment]
where is it? the latest release is from 20 days

**Comment by artdeell** [comment]
Actions tab on github

**Comment by rojaoo** [comment]
Ok, i will try

**Comment by rojaoo** [comment]
it just crashes, the game doesnt even launch

**Comment by artdeell** [comment]
Screenshots/latestlog?

**Comment by rojaoo** [comment]
**Here is the crash log**

> ---- Minecraft Crash Report ----
// Shall we play a game?

> Time: 19-02-2021 17:00
Description: Initializing game

> java.lang.UnsatisfiedLinkError: /data/data/net.kdt.pojavlaunch/jre_runtime/lib/aarch32/libfontmanager.so: dlopen failed: library "libfreetype.so.6" not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:339)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.java.openjdk.cacio.ctc.FontManagerUtil$1.run(FontManagerUtil.java:24)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.openjdk.cacio.ctc.FontManagerUtil.setFontManager(FontManagerUtil.java:17)
	at net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment.<clinit>(CTCGraphicsEnvironment.java:31)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at net.optifine.util.TextureUtils.scaleImage(TextureUtils.java:514)
	at bmh.getMissingImageData(TextureMap.java:957)
	at bmh.g(TextureMap.java:118)
	at bmh.a(TextureMap.java:152)
	at bot.j(ModelBakery.java:694)
	at bot.a(ModelBakery.java:89)
	at bou.a(SourceFile:23)
	at bnn.a(SourceFile:99)
	at ave.am(SourceFile:448)
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)


> A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

> -- Head --
Stacktrace:
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:339)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.java.openjdk.cacio.ctc.FontManagerUtil$1.run(FontManagerUtil.java:24)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.java.openjdk.cacio.ctc.FontManagerUtil.setFontManager(FontManagerUtil.java:17)
	at net.java.openjdk.cacio.ctc.CTCGraphicsEnvironment.<clinit>(CTCGraphicsEnvironment.java:31)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at net.optifine.util.TextureUtils.scaleImage(TextureUtils.java:514)
	at bmh.getMissingImageData(TextureMap.java:957)
	at bmh.g(TextureMap.java:118)
	at bmh.a(TextureMap.java:152)
	at bot.j(ModelBakery.java:694)
	at bot.a(ModelBakery.java:89)
	at bou.a(SourceFile:23)
	at bnn.a(SourceFile:99)
	at ave.am(SourceFile:448)

> -- Initialization --
Details:
Stacktrace:
	at ave.a(SourceFile:310)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

> -- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (arm) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK Client VM (mixed mode), Oracle Corporation
	Memory: 100124880 bytes (95 MB) / 194707456 bytes (185 MB) up to 389283840 bytes (371 MB)
	JVM Flags: 3 total; -Xms192m -Xmx384m -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

> 	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: nebulla [16x].zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 9x ARMv7 Processor rev 4 (v7l)
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 5
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 gl4es wrapper 1.1.4
	OpenGlRenderer: GL4ES wrapper
	OpenGlVendor: ptitSeb
	CpuCount: 8
	
**Here is the latest Log**
[latestlog.txt](https://github.com/PojavLauncherTeam/PojavLauncher/files/6011657/latestlog.txt)

**Here is some screenshots**

Launcher open
![Screenshot_20210219-140310](https://user-images.githubusercontent.com/67767832/108536530-5080c800-72bb-11eb-8fb2-641ab0699da6.png)
Launch the game
![Screenshot_20210219-140317](https://user-images.githubusercontent.com/67767832/108536571-5d052080-72bb-11eb-9b98-f00da2edc0c5.png)
Mojang Logo appears
![Screenshot_20210219-140328](https://user-images.githubusercontent.com/67767832/108536657-70b08700-72bb-11eb-9bee-431db125a587.png)
Pojav crashes
![Screenshot_20210219-140335](https://user-images.githubusercontent.com/67767832/108536691-7b6b1c00-72bb-11eb-9034-e943480969ba.png)

**Comment by artdeell** [comment]
Seems like you are still using the old aarch32 patched runtime. You need to use the new one. To use it, download the 60 MB APK from Actions and do a full reinstall

**Comment by rojaoo** [comment]
man, i think that i fixed it , just deleted some mod files and resource packs... My game cant crash anymore, i was trying to crash it by 15 minutes, omg

**Comment by rojaoo** [comment]
no, its just on singleplayer. Joining a server is instant crash

**Comment by rojaoo** [comment]
Ok, i did the full reinstall, now its working. Thank you! <3
![Screenshot_20210219-171001](https://user-images.githubusercontent.com/67767832/108556227-74e99e00-72d5-11eb-8a0d-065be1064161.png)

**Comment by cseanx** [comment]
im still having fullscreen problem

**Comment by Pojavlayer69** [comment]
Guys how did you fix it pleeease teach me
