### ISSUE TITLE
---- Minecraft Crash Report ----

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#903]
Time: 2/16/21 10:51 AM
Description: Unexpected error

java.lang.NoSuchMethodError: org.lwjgl.opengl.ARBVertexShader.glVertexAttribPointerARB(IIZZILjava/nio/ShortBuffer;)V
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at bmh.a(Tessellator.java:169)
	at bno.a(Render.java:304)
	at blo.a(WorldRenderer.java:205)
	at bma.a(RenderGlobal.java:2382)
	at blt.a(EntityRenderer.java:1657)
	at blt.b(EntityRenderer.java:1392)
	at bao.ak(SourceFile:801)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at shadersmod.client.ShadersTess.preDrawArray(ShadersTess.java:168)
	at shadersmod.client.ShadersTess.draw(ShadersTess.java:109)
	at bmh.a(Tessellator.java:169)
	at bno.a(Render.java:304)
	at blo.a(WorldRenderer.java:205)
	at bma.a(RenderGlobal.java:2382)
	at blt.a(EntityRenderer.java:1657)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bjk['Lance_Aldrei'/31, l='MpServer', x=64.50, y=5.62, z=416.50]]
	Chunk stats: MultiplayerChunkCache: 25, 34
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (66,4,426), Chunk: (at 2,0,10 in 4,26; contains blocks 64,0,416 to 79,255,431), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 145 game time, 145 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [bjk['Lance_Aldrei'/31, l='MpServer', x=64.50, y=5.62, z=416.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Integrated singleplayer server
Stacktrace:
	at bjf.a(WorldClient.java:425)
	at bao.b(SourceFile:1972)
	at bao.f(SourceFile:742)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (aarch64) version Android-8.1.0
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2896409072 bytes (2762 MB) / 3140747264 bytes (2995 MB) up to 3140747264 bytes (2995 MB)
	JVM Flags: 26 total; -Xmx3G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10 -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10
	LWJGL: 3.2.3 SNAPSHOT
	OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

When i turn my render distance to 64 what will happen???

**Comment by artdeell** [comment]
What launcher version?

**Comment by LanceAldrei04** [comment]
![Screenshot_2021-02-16-18-56-24-82](https://user-images.githubusercontent.com/78906627/108053695-b89b9800-7088-11eb-865f-fbd408858748.png)

**Comment by lalalalalalalalalalalalalalalalalala000** [comment]
I want a shader plz give me shader for SnapDragon 400+

**Comment by Mathias-Boulay** [comment]
Stale issue on an old version that is probably related to using mods.
> Is Modded: Very likely; Jar signature invalidated

Closing the issue, as it isn't pojav specific.
