### ISSUE TITLE
Lunar Client 1.8.9

### ISSUE THREAD

**Issue by ghost** [PojavLauncherTeam/PojavLauncher#909]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 21/02/17 10:56
Description: Initializing game

java.lang.ExceptionInInitializerError
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:45)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at IlIIIIIllllllIIlllIllllll.llIIIIllIIIIIIIlIIIlIIIIl(Minecraft:292)
	at IlIIIIIllllllIIlllIllllll.IlIllllllIIlIIllllIIlIIIl(Minecraft:274)
	at lIllIlIIIllIlIlIIlIlIlIll.llllIIllIlIlllllllIIlIIlI(Minecraft:591)
	at lIllIlIIIllIlIlIIlIlIlIll.IllIIlllllllIIlIIlIIIIlIl(Minecraft:979)
	at lIlllIlllIIlllllIIIlIlIll.lllIIIllIIIIlllIlIIllIIll(Minecraft:197)
	at Main.main(Main.java:4)
Caused by: java.lang.IllegalStateException: Could not find NarSystem class.

*** ECLIPSE USERS ***
If you're running from within Eclipse, please try closing the "junixsocket-native-common" project

	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:37)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.newsclub.net.unix.NarSystem
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
	at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
	at com.jagrosh.discordipc.entities.pipe.UnixPipe.<init>(UnixPipe.java:45)
	at com.jagrosh.discordipc.entities.pipe.Pipe.createPipe(Pipe.java:163)
	at com.jagrosh.discordipc.entities.pipe.Pipe.openPipe(Pipe.java:67)
	at com.jagrosh.discordipc.IPCClient.connect(IPCClient.java:116)
	at IlIIIIIllllllIIlllIllllll.llIIIIllIIIIIIIlIIIlIIIIl(Minecraft:292)
	at IlIIIIIllllllIIlllIllllll.IlIllllllIIlIIllllIIlIIIl(Minecraft:274)
	at lIllIlIIIllIlIlIIlIlIlIll.llllIIllIlIlllllllIIlIIlI(Minecraft:591)

**Comment by ghost** [comment]
Help me :(

**Comment by khanhduytran0** [comment]
Unsupported client...

**Comment by HiddenBoii** [comment]
So...what does that mean? I have the same issue

**Comment by WesleyVanNeck** [comment]
> So...what does that mean? I have the same issue

says what he say its not supported

**Comment by khanhduytran0** [comment]
Or, it could be launched, but patching is required.

**Comment by EXPress-016** [comment]
https://www.mediafire.com/file/i7pdnp723lrf8vs/LC.rar/file
This one is working but mouse not working

**Comment by ghost** [comment]
Ok thx :)
