### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ArvyPlays** [PojavLauncherTeam/PojavLauncher#916]
I tap play and this pop up pls fix
java.lang.RuntimeException: Architecture arm/aarch32 is incompatible with Java Runtime aarch64.
	at net.kdt.pojavlaunch.utils.JREUtils.checkJavaArchitecture(JREUtils.java:37)
	at net.kdt.pojavlaunch.BaseMainActivity.runCraft(BaseMainActivity.java:877)
	at net.kdt.pojavlaunch.BaseMainActivity.access$2200(BaseMainActivity.java:26)
	at net.kdt.pojavlaunch.BaseMainActivity$9$1.run(BaseMainActivity.java:673)
	at java.lang.Thread.run(Thread.java:764)

**Comment by artdeell** [comment]
bruh just use app-debug.apk from 3.3.1.1 and do a reinstall

**Comment by ArvyPlays** [comment]
Uhh im new to this and umm i don't know what your talking about but i have app debug.apk

**Comment by artdeell** [comment]
So, now, delete the Pojav tjat you already have and install app-debug.apk from 3.3.1.1

**Comment by Mathias-Boulay** [comment]
Stale issue, or at least the user seems happy enough that he didn't return.
Closing the issue.
