### ISSUE TITLE
Crash while trying to run TLauncher modpack.

### ISSUE THREAD

**Issue by PeterScorPioN** [PojavLauncherTeam/PojavLauncher#932]
I have TLauncher in my laptop, and there's a modpack feature there, where you can put some mods in a different Minecraft version. The fact is that these TLauncher modpacks are not depended on anything. They work as a different version and it contains every needed folder inside the version folder. Whoever had TLauncher, will understand. So i tried to run one modpack, but it led to crash, as i wasn't expecting... Is something that i do wrong, or running this modpack is impossible for now?

**Comment by Mathias-Boulay** [comment]
Just look at your crash log and remove every mod that crashes the game
Repeat until it launches.

**Comment by PeterScorPioN** [comment]
> Just look at your crash log and remove every mod that crashes the game
> Repeat until it launches.

I tried removing every mod, but it didn't help.

**Comment by PeterScorPioN** [comment]
My latest crash:

PojavLauncher crash report
 - Time: Feb 14, 2021 5:04:25 PM
 - Device: beryllium POCOPHONE F1
 - Android version: 10
 - Crash stack trace:
java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{3b22dd V.E...... R.....I. 0,0-0,0} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:545)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:439)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:103)
	at android.widget.PopupWindow.update(PopupWindow.java:2224)
	at android.widget.PopupWindow.update(PopupWindow.java:2345)
	at android.widget.PopupWindow.update(PopupWindow.java:2254)
	at net.kdt.pojavlaunch.customcontrols.handleview.PinnedPopupWindow.updatePosition(PinnedPopupWindow.java:115)
	at net.kdt.pojavlaunch.customcontrols.handleview.PinnedPopupWindow.updatePosition(PinnedPopupWindow.java:133)
	at net.kdt.pojavlaunch.customcontrols.handleview.PositionListener.onPreDraw(PositionListener.java:97)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2858)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
	at android.view.Choreographer.doCallbacks(Choreographer.java:865)
	at android.view.Choreographer.doFrame(Choreographer.java:800)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

I cannot understand the reason, that makes it crash.

**Comment by Mathias-Boulay** [comment]
If you want to declare an issue, please fill the bug template.
Else it will be too much time consuming to help you.

**Comment by khanhduytran0** [comment]
@PeterScorPioN also latest__crash__.txt was for launcher crashes, not game log.
