### ISSUE TITLE
Getting error 404 when trying to launch Optifine 1.11.2

### ISSUE THREAD

**Issue by szarik001** [PojavLauncherTeam/PojavLauncher#95]
When launching Optifine 1.11.2 the game doesn't start and this error shows up:
```
Unable to convert library optifine:launchwrapper-of:2.1
java.lang.RuntimeException: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:17)
	at net.kdt.pojavlaunch.util.DownloadUtils.downloadFile(DownloadUtils.java:62)
	at net.kdt.pojavlaunch.Tools.downloadFile(Tools.java:514)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:550)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: Server returned HTTP 404: Not Found
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:32)
	at net.kdt.pojavlaunch.util.DownloadUtils.download(DownloadUtils.java:15)
	... 10 more

UNEXPECTED TOP-LEVEL EXCEPTION:
java.io.FileNotFoundException: /storage/emulated/0/games/minecraft/libraries/optifine/launchwrapper-of/2.1/launchwrapper-of-2.1_orig.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
	at java.util.zip.ZipFile.<init>(ZipFile.java:201)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:245)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.pojavdx.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.pojavdx.dx.command.dexer.Main.processOne(Main.java:682)
	at com.pojavdx.dx.command.dexer.Main.processAllFiles(Main.java:575)
	at com.pojavdx.dx.command.dexer.Main.runMultiDex(Main.java:361)
	at com.pojavdx.dx.command.dexer.Main.runDx(Main.java:283)
	at com.pojavdx.dx.command.dexer.Main.main(Main.java:241)
	at com.pojavdx.dx.command.Main.main(Main.java:95)
	at net.kdt.pojavlaunch.Tools.runDx(Tools.java:347)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(MCLauncherActivity.java:568)
	at net.kdt.pojavlaunch.MCLauncherActivity$GameRunnerTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
1 error; aborting
Exiting with code 1
```

**Comment by khanhduytran0** [comment]
https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine#since-optifine-mc-19-a-file-called-launchwrapper-of-21jar-cause-error-unable-to-launch-simply-fix-by-follow-the-video-or-do-actions-as-below

**Comment by FranzelDamasco909** [comment]
but for me, it game crashed :( i use android 8.1(i repeat)

**Comment by khanhduytran0** [comment]
> https://github.com/khanhduytran0/PojavLauncher/wiki/Install-OptiFine#since-optifine-mc-19-a-file-called-launchwrapper-of-21jar-cause-error-unable-to-launch-simply-fix-by-follow-the-video-or-do-actions-as-below

@szarik001 do above
