### ISSUE TITLE
[BUG] Physics Mod

### ISSUE THREAD

**Issue by LanceAldrei04** [PojavLauncherTeam/PojavLauncher#979]
<details> <summary><b>Read before submit</b></summary>
<br>
- Make sure there was not duplicated issues.<br>
- Make sure you have filled this issue template, or this will get rejected.
</details>

### Describe the bug
I want to play Physics Mod on 1.16.5 but I fails.
**Add a log file if you want to see your bug fixed !**
2021-02-27 12:34:13,551 main WARN Advanced terminal features are not available in this environment

[12:34:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Lance_Aldrei, --version, 1.16.5, --gameDir, /storage/emulated/0/games/PojavLauncher/.minecraft, --assetsDir, /storage/emulated/0/games/PojavLauncher/.minecraft/assets, --assetIndex, 1.16, --uuid, 0, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.0.42, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --fullscreen]
[12:34:14] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0-internal by Oracle Corporation
[12:34:15] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[12:34:15] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: /storage/emulated/0/games/PojavLauncher/.minecraft/mods/OptiFine-1.16.5_HD_U_G7_pre10.jar
[12:34:15] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[12:34:15] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[12:34:16] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[12:34:16] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[12:34:16] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Configuration file /storage/emulated/0/games/PojavLauncher/.minecraft/config/fml.toml is not correct. Correcting
[12:34:16] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[12:34:16] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Incorrect key [maxThreads] was corrected from null to -1
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: com.electronwill.nightconfig.core.io.ParsingException: Invalid TOML data: entry "[maxThreads]" defined twice in its table.
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.toml.TableParser.checkDuplicateKey(TableParser.java:88)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:59)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
[12:34:16] [Thread-1/INFO] [STDERR/]: [com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread:run:183]: 	at com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:181)
[12:34:16] [main/FATAL] [ne.mi.fm.lo.FMLCommonLaunchHandler/CORE]: Failed to find Minecraft resource version 1.16.5-20210115.111550 at /storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/forge/1.16.5-36.0.42/forge-1.16.5-36.0.42-client.jar
Exception in thread "main" 
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:202)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:981)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
[12:34:16] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
Java Exit code: 1

The log file called *lastlog.txt* is located under "*games/PojavLauncher/.minecraft*" .
You may need to activate an option in your file explorer to see hidden files and folders.

Do NOT paste the whole log text ! Instead, add it as a file on this issue.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Download Physics Mod on CurseForge
2. Put Physics Mod on games/PojavLauncher/.minecraft/mod
3. Launch Forge 1.16.5
4. EXIT CODE 1!

### Expected behavior:
I expected it will work.

### Screenshots or videos:
*Upload here screenshots or videos of the buggy behavior, if possible.*

**Platform:**
 - Device Model CPH1853 OPPO A12e
 - CPU architecture arm64/aarch64
 - Android Version 8.1
 - PojavLauncher Version Latest Buid

<details> <summary><b>Additional context</b></summary>
<br>
<pre>
</pre>
</details>

**Comment by khanhduytran0** [comment]
Did you install vanilla 1.16.5?

**Comment by LanceAldrei04** [comment]
> Did you install vanilla 1.16.5?

Yes

**Comment by LanceAldrei04** [comment]
Advanced terminal features are not available in is environment?

**Comment by LanceAldrei04** [comment]
How can I fix it?

**Comment by khanhduytran0** [comment]
Maybe reinstall forge?

**Comment by khanhduytran0** [comment]
> Advanced terminal features are not available in is environment?

Normal behavior.

**Comment by khanhduytran0** [comment]
physics mod is unsupported at the moment
