### ISSUE TITLE
[BUG] can't connect server

### ISSUE THREAD

**Issue by Haocen2004** [PojavLauncherTeam/PojavLauncher#994]
### Describe the bug
can't connect to any server ,both wifi and lte  

log for fabric but vanilla version also has this problem.  
`[00:46:38] [Server Connector #5/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: hellocraft.xyz/43.248.187.28:25565
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0-internal]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716) ~[?:1.8.0-internal]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:325) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:635) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0-internal]
Caused by: java.net.ConnectException: Connection refused
	... 10 more`

.

### To Reproduce:
Indicate steps to reproduce the buggy behavior:

1. Start PojavLauncher
2. start any version
3. try to connect a server

### Expected behavior:
can't connect to server

### Screenshots or videos:
just can't connect to server screen

**Platform:**
 - Device Model Mi 9T pro 8 +128
 - CPU architecture  aarch64
 - Android Version 11
 - PojavLauncher Version  Latest Release

**Comment by artdeell** [comment]
go to mcsrvstat.us and get the real ip and port from the debugging information

or update to latest build (not release)

**Comment by Haocen2004** [comment]
Still can't connect when try to join the `hypixel.net` and the latest build also has this issue with same logs.  





------------------ Original ------------------

**Comment by ghost** [comment]
This ''io.netty.channel'' always causing problems with servers :/

**Comment by Haocen2004** [comment]
so confuse
i rollback to the latest release from latest build and this issue has gone  
permission settings are same

**Comment by lalalalalalalalalalalalalalalalalala000** [comment]
Try to add CORRECT port

**Comment by Mathias-Boulay** [comment]
Stale issue, no answer from author
Closing
